DefectDojo/django-DefectDojo

dojo/forms.py, dojo/jira_link/helper.py, dojo/templates/dojo/view_test.html, dojo/test/views.py
adding a finding to a test from a template failed for two reasons:
- initialization of jira form was broken 
- initialization of finding form was broken
also the paging on view_test was broken 
all this was only in dev I believe
=> aftercare: add finding from template fix

docs/content/integrations/social-authentication.md
see #3890
The SAML integration below is based on [https://github.com/fangli/django-saml2-auth](django-saml2-auth) which is no longer maintained.
=> deprecation warning SAML integration

helm/defectdojo/Chart.yaml, helm/defectdojo/requirements.lock, helm/defectdojo/requirements.yaml, helm/defectdojo/templates/configmap.yaml, helm/defectdojo/templates/django-deployment.yaml, helm/defectdojo/templates/django-ingress.yaml, helm/defectdojo/values.yaml
This PR contains:
-  option to mount CA cert as volume
-  updated values.yaml
- updates ingress to networking.k8s.io/v1 spec
- Updates postgres helm (to respect: postgresql.shmVolume.enabled=false)
=> Helm mount ca volume, ingress spec

dojo/risk_acceptance/helper.py
comments were refactored at some point and are now handled by: https://github.com/DefectDojo/django-DefectDojo/blob/ebca1322fef7fb47a651b96525f80c7b82a2abd6/dojo/risk_acceptance/helper.py#L39
the line removed references 2 variables that don't exist, so need to remove that.
=> remove left over risk acceptance jira comment code

dojo/jira_link/helper.py
While looking into #3944 I realized these 2 `find.save()` calls are no longer needed.  The `jira_change` and `jira_created` are now stored on the `JIRA_Issue` model, so we're changing no data on the finding when pushing to JIRA.
Removing these doesn't fix the timing issue, but reduces the impact quite a bit by not overwriting the finding with old data.
=> jira helper: remove redundant .save() calls

dojo/templates/dojo/finding_related_row.html
fixes #3955 
similar findings list and duplicate cluster now shows the correct date and reimport history for each finding
=> fix dates and reimport history for similar / duplicate findings

dojo/api_v2/serializers.py
Fixed a bug where the 'is_Mitigated' field is not updated when findings are automatically closed, which leads to them not been considered closed internally by DefectDojo (although on the UI it appears "Mitigated"). This causes these findings not to appear on metrics nor at the 'View Closed Findings' option.
=> set mitigation related fields correctly at close_old_findings

dojo/reports/urls.py, dojo/reports/views.py, dojo/templates/base.html, dojo/templates/dojo/findings_list_snippet.html, dojo/templates/dojo/view_eng.html, dojo/templates/dojo/view_test.html
Generate a finding report very quickly with the current findings displayed on a given page with the current filters applied. No need redo the current filter options on the report tab any longer.
=> Quick report based on current finding filters

DOCKER.md, Dockerfile.django, docker-compose.override.dev.yml, docker-compose.override.integration_tests.yml, docker-compose.override.ptvsd.yml, docker-compose.override.unit_tests.yml, docker-compose.override.unit_tests_cicd.yml, docker-compose.yml, docs/content/running/running-in-production.md, tests/base_test_class.py
When using Docker Compose, some users experienced problems with permissions of media files, including me. This is caused by the bind mount for the media folder. Docker volumes are the preferred way of managing persistent data in Docker, see https://docs.docker.com/storage/#good-use-cases-for-volumes, and make the application more independent from the infrastructure of the host. 
This PR uses a docker volume to store files in the media folder. With this we get an out-of-the box working installation of DefectDojo with Docker Compose. There have been several documentation updates to make users aware they have to of the check the configuration for productive use and adjust it if required.
=> Docker volume for media files

requirements.txt
Fix 2 dependencies problems:
1. `gitpython` don't use a pinned version, switching to a pinned one
https://github.com/DefectDojo/django-DefectDojo/blob/920503f93e74b2a266a5f913283f60333ffdff48/requirements.txt#L55
2. remove useless dependency `jsonlines`
https://github.com/DefectDojo/django-DefectDojo/blob/920503f93e74b2a266a5f913283f60333ffdff48/requirements.txt#L62
Relevant issue upstream https://github.com/gitpython-developers/GitPython/issues/983
```
File "/usr/local/lib/python3.6/site-packages/git/compat.py", line 16, in <module>
from gitdb.utils.compat import (
ModuleNotFoundError: No module named 'gitdb.utils.compat'
```
=> Fix gitpython version and remove jsonlines

dojo/db_migrations/0083_remove_ipscan.py
The order of db migrations was not correct anymore after 3 parallel changes
=> Rename db migration for ipscan removal

.github/workflows/unit-tests.yml
Reverts DefectDojo/django-DefectDojo#3992
It was merged with failing tests and now all unit tests are hanging in GHA
=> Revert "unit tests: don't build & start unneeded services"

dojo/templates/dojo/findings_list_snippet.html
Bulk Edit for findings allowed for contradictory selections (e.g. "Active" and "Mitigated" simultaneously). Added functionality similar to Bulk Edit for Endpoints to eliminate this.
=> Updates to Bulk Edit for Findings

DOCKER.md, docker-compose.override.integration_tests.yml, dojo/api_v2/serializers.py, dojo/management/commands/dedupe.py, dojo/models.py, dojo/reimport_utils.py, dojo/settings/settings.dist.py, dojo/test/views.py, dojo/tools/bandit/parser.py, dojo/unittests/dojo_test_case.py, dojo/unittests/scans/sonarqube/sonar-6-findings-1-unique_id_changed.html, dojo/unittests/scans/veracode/many_findings_different_hash_code_different_unique_id.xml, dojo/unittests/scans/veracode/many_findings_same_hash_code_different_unique_id.xml, dojo/unittests/scans/veracode/many_findings_same_unique_id_different_hash_code.xml, dojo/unittests/test_deduplication_logic.py, dojo/unittests/test_import_reimport.py, dojo/utils.py, requirements.txt, tests/dedupe_test.py
… findings to existing findings
This PR includes: 
- **use the deduplication algorithm configured for each parser to identify findings during re-import (instead of title + severity)**
- **remove specific code that was added for Veracode Scan and Arachni Scan.** 
- It's no longer needed no that we can correcly identify findings through the dedupe configuration (it's kept only when using legacy dedupe algorithm just in case someone has an old configuration without the dedupe configuration for those parsers)
- **removed the endpoints from the dedupe configuration for the dynamic parsers that had one (Nessus, ZAP, Qualys)**: 
- we agreed on slack that it's better to identify findings without endpoints (and then handle endpoint status during re-import if using the re-import feature). 
- Note …
=> Reimport feature: use the configurable deduplication for matching new findings to existing findings

README.md, dojo/tools/netsparker/parser.py
The parser is not working (TypeError: object of type 'NoneType' has no len()), which triggers an HTTP 500 response. 
This is because the get_findings(self, filename, test) method defined for the Netsparker parser (line 30) does not return the list of findings as expected in "https://github.com/DefectDojo/django-DefectDojo/blob/master/dojo/engagement/views.py#L583" (line 583) "parser_findings = parser.get_findings(file, t)"
Just adding a return statement solves the import issues.
=> Netsparker: Fix crashing parser at method get_findings()

dojo/finding/helper.py, dojo/jira_link/views.py
Currently in dev there is an error when a finding is closed in JIRA and the webhook is closing the finding in defect dojo.
The new status helper tries to set `mitigated_by` to `get_current_user()`, but the webhook is anonymous so this fails.
Two fixes:
- make status helper robust by only using `get_current_user()` if the user is authenticated
- set `mitigated_by` to the JIRA user in the webhook.
=> JIRA: fix webhook mitigated by

dojo/tools/sslyze/parser.py, dojo/unittests/tools/test_sslyze_json_parser.py, dojo/unittests/tools/test_sslyze_xml_parser.py
There was an unnecessary read of the file with the scan results. Because of this read, the following read didn't get data anymore and therefore the scanner produced a server error.
=> Fix SSLyze scanner: Remove unnecessary read

dojo/decorators.py
Currently our `dojo_async_task` decorator looks at the `block_execution` field in the users profile to determine if a task (deduplication, push to jira, send email, etc) should be performed synchronously, or asynchronously using celery.
There can be situation where this is the right default approach, for example when using the API. But sometimes in the UI you want direct feedback to see if that push to JIRA (or other task) was succesful.
I am going to use this in a future PR, but didn't want to sneak it in there. So here is the `sync=True` flag in its own PR.
example: `jira_helper.push_to_jira(finding, sync=True)` will ensure it's always performed synchronously in the current request/thread and the task won't get posted to celery.
=> celery: allow forced synchronous execution

dojo/api_v2/serializers.py, dojo/api_v2/views.py, dojo/models.py
fix #4069 
For non-staff users, we have queries where we filter objects based on the `authorized_users` property of the product or product type:
```
def get_queryset(self):
if not self.request.user.is_staff:
return self.queryset.filter(
Q(test__engagement__product__authorized_users__in=[self.request.user]) |
Q(test__engagement__product__prod_type__authorized_users__in=[self.request.user])
)
else:
return self.queryset
```  
This works OK, but will join a couple of tables and could lead to objects being in the result multiple times. This PR adds `.distinct()` to resolve this.
There's also one place where we had 2 different queries for the list of findings and the count of that list.
=> fix counts returned to non-staff users in apiv2

dojo/settings/settings.dist.py
It's better to dedup on component-name + component-version + CVE + CWE for a dependency.
=> Fix deduplication for Dependency Track scanner

docker-compose.yml
docker-compose.yml always took `latest` for celery and initializer instead of the possible version passed in.
=> [docker-compose] Fix image version in use

dojo/filters.py
some api endpoints didn't allow ordering the results, some endpoints could use some extra ordering options.
=> add missing ordering for api filters

dojo/forms.py, dojo/settings/settings.dist.py, dojo/templates/base.html, dojo/templates/dojo/report_builder.html, dojo/templatetags/display_tags.py, tests/report_builder_test.py
The reports list is only used to make pdf reports accessible. Now the PDF reports are not supported anymore for more than a year now. This PR hides the list behind a feature flag and renames the button in the report builder to just "Run". Goal is to avoid misunderstandings of users.
Additionally it removes the upper button to generate a report in the report builder because it is redundant and looks different than the one at the bottom.
Shall we additionally include a message, that PDF reports are deprecated and removed in the future, eg. 30.6.2021?
=> Hide reports list behind a feature flag

dojo/tools/nexpose/parser.py, dojo/unittests/scans/nexpose/report_auth.xml, dojo/unittests/tools/test_nexpose_parser.py
Used [for-loop](https://github.com/DefectDojo/django-DefectDojo/blob/6a2b0e5939155554a284f90f58e6287632436ce8/dojo/tools/nexpose/parser.py#L228) processed only last "discovered" host in the XML file. I move it to the upper loop.
There was missing also adding Endpoint - so it wasn't possible to identify where vulnerability is.
For finding on specific service, I added also a protocol name to the Endpoint
I also added a couple of new references used in Nexpose reports.
Test XML changed to easier readable.
\+ Using better names of variables
\+ Tests
=>  Nexpose parser: Process all hosts + add Endpoint(and protocol) + add new reference links + test

dojo/engagement/views.py, dojo/models.py, dojo/product/views.py, dojo/user/helper.py
When the engagement form contained an error while editing an engagement, the error was not shown. This was a generic issue, but we saw it in these cases:
- when adding/editing a product/engagement and changing some of the JIRA fields, but not specifying a JIRA instance or JIRA Project, there was only a generic error message on top of the page. (This was no bug, just a hidden error message)
- when selecting a testing lead, there was an error in the validation rejecting some testing lead values, especially those who are not staff users, but do in fact have staff permission on the product (This was a bug AND a hidden error message)
This PR ensures error messages are shown and fixes the bug around the testing lead field validation.
The cause of the testing lead problem was that on the form …
=> edit engagement: unhide error messages, fix testing lead error

.github/workflows/unit-tests.yml, README.md, requirements.txt, setup.py
Dependabot generated a PR against `master` instead of `dev` and I didn't notice (https://github.com/DefectDojo/django-DefectDojo/pull/4086).
Easest is to just merge master into dev, which is this PR.
=> dependabot: update django from 2.2.17 to 2.2.18

docs/content/running/upgrading.md
Documentation part regarding the fields that have become optional in https://github.com/DefectDojo/django-DefectDojo/pull/4016
This PR also serves as making this change more visible in the release note
=> Make mitigation, impact, url fields optional

docker/entrypoint-unit-tests-devDocker.sh, dojo/tools/clair/parser.py, dojo/unittests/scans/clair/empty.json, dojo/unittests/scans/clair/many_vul.json, dojo/unittests/tools/test_clair_parser.py
Current parser is broken and throws Server Error 500 / "TypeError: string indices must be integers" when uploading a scan.
Also adding some unittests.
----
=> Clair parser: fixes TypeError: string indices must be integers

dojo/tools/sarif/parser.py, dojo/unittests/scans/sarif/DefectDojo_django-DefectDojo__2020-12-11_13 42 10__export.sarif, dojo/unittests/scans/sarif/njsscan.sarif, dojo/unittests/tools/test_sarif_parser.py
ex: https://github.com/DefectDojo/django-DefectDojo/blob/ec47390ef2f8893b2a35c2bf8cbf4dd36584b5fe/dojo/unittests/scans/sarif/appendix_k.sarif#L150
=> SARIF: support date of findings

dojo/finding/helper.py, dojo/tools/veracode/parser.py, dojo/unittests/scans/veracode/mitigated_finding.xml, dojo/unittests/scans/veracode/veracode_scan.xml, dojo/unittests/test_import_reimport.py, dojo/unittests/tools/test_veracode_parser.py
=> Veracode parser: remove lxml dependency

dojo/finding/views.py, dojo/jira_link/helper.py, dojo/templates/dojo/findings_list_snippet.html, dojo/templates/dojo/view_test.html
fixes #4136 
Most code was already in place, but there was a decorator on the bulk edit method that allowed only staff users to perform bulk edits. Removed decorator, updated permission checks and tested all scenarios around True/False for:
```
AUTHORIZED_USERS_ALLOW_CHANGE
AUTHORIZED_USERS_ALLOW_DELETE
AUTHORIZED_USERS_ALLOW_STAFF
```
Moved some code around to make `view_test` align more with `findings_list_snippet.html`
=> allow non-staff users to perform bulk edit

dojo/jira_link/helper.py, dojo/jira_link/views.py, dojo/unittests/test_jira_config_product.py
=> JIRA: Always check credentials when creating/saving a JIRA instance

dojo/templates/base.html
fixes #4147 
In base.html there's jQuery that attaches the get_alerts() function to every element with class dropdown-toggle.
The intention is to get the new alerts whenever somebody clicks on the alerts dropdown. But as a side effect it is also attached to every other dropdown on screen, i.e. opening the filters, opening similar findings, selecting findings for bulk edit, etc.
=> alert count: don't get them on every dropdown click

dojo/forms.py, dojo/jira_link/helper.py, dojo/unittests/dojo_test_case.py, dojo/unittests/test_jira_config_product.py
fixes #4130
Since #4132, when a user entered the wrong credentials when adding/editing a JIRA instance, a 500 errors was generated.
=> jira: fix crash on invalid credentials

docs/content/contributing/how-to-write-a-parser.md
A cookie cutter scanner template generator to aid in rapidly developing new scanners and assuring the requirements are met for adding a new parser.
Code is invoke from: https://github.com/DefectDojo/cookiecutter-scanner-parser
To get started you will need to install [cookiecutter](https://github.com/cookiecutter/cookiecutter).
```bash
$ pip install cookiecutter
```
Then generate your scanner parser from the root of django-DefectDojo:
```bash
$ cookiecutter https://github.com/DefectDojo/cookiecutter-scanner-parser
```
=> Cookie cutter template parser for new scanners

dojo/finding/views.py, dojo/product/views.py
I think something changed recently around authorizations on the product overview as it is doing lots of queries to retrieve authorized users.
This PR ensures authorized users are prefetched.
Also it changes some `selected_related` clauses to `prefetch_related` as it turns it that is a lot faster (thanks @danielnaab)
Also fixes a bug when viewing findings for an engagement where it was not filtering correctly on status.
=> prod overview: fix perf regression

dojo/api.py, dojo/api_v2/serializers.py, dojo/finding/helper.py, dojo/finding/views.py, dojo/fixtures/dojo_testdata.json, dojo/management/commands/dedupe.py, dojo/management/commands/rename_whitesource_findings.py, dojo/models.py, dojo/reimport_utils.py, dojo/risk_acceptance/helper.py, dojo/settings/settings.dist.py, dojo/test/views.py, dojo/unittests/test_deduplication_logic.py, dojo/unittests/test_finding_helper.py, dojo/unittests/test_utils.py, dojo/utils.py
As we have seen in #3944 and #4048 the current `finding.save()` logic triggers multiple processes in parallel, leading to possible race conditions:
- deduplication
- false positive history
- pushing to sonarqube
- push to jira
- applying rules
- product grade calculation
My opinion is that at least we should make sure the logic that possibly changes a findings status should be predictable, i.e. ordered. Same for the hash code calculation which currently is case-sensitive.
This PR wraps all post processing in a single celery task. So we still get a performance benefit by executing these tasks in the background. But inside this celery task there are some sequential steps that possibly change the findings status:
- deduplication
- false positive history
After that some async celery tasks are …
=> finding.save and dedupe streamlining

dojo/settings/settings.dist.py, dojo/tasks.py
The fix_loop_duplicates allows to fix circular dups. It happens that sometimes due to the async dup mechanism, we have some of them forming again.
This gives the ability to schedule this management command if one wishes.
=> Ability to invoke fix_loop_duplicates from celerybeat

dojo/templates/base.html, dojo/templates/dojo/product_type.html, dojo/templates/dojo/report_builder.html, dojo/templatetags/display_tags.py
This is an update to #4065. The Reports entry in the main menu still led to the report list. Now there is no submenu anymore but the report builder is immediately shown when clicking on Reports. Plus a small fix for the product type list for non-staff users and a small refactoring.
=> Optimize (pdf) report in main menu and small fix for product type list

dojo/templates/dojo/view_test.html
a copy-and-pasted dropdown menu was left behind on the finding groups panel
=> finding groups: remove superfluous dropdown

dojo/tools/ort/parser.py
this will fix bug #4161. It's verifying that license and license_source fields are defined. In case they are not, it set them as 'unset'.
=> fix ORT parser error when importing oss-review-toolkit file

dojo/db_migrations/0058_document_finding_model.py, dojo/finding/helper.py, dojo/fixtures/dojo_testdata.json, dojo/models.py, dojo/settings/settings.dist.py, dojo/unittests/test_duplication_loops.py, dojo/utils.py
fixes #3057 
Current behavior:
Assume you have a finding A with two duplicates, so finding B is a duplicate of A and C is a duplicate of A:
B->A and C->A
When deleting finding A, also B and C get deleted. This is confusing as described in #3057 
New behavior:
When A gets deleted, the duplicates B and C remain and they get a new original finding assigned. The oldest of B and C becomes the new original, so C->B and B is the new original and no longer marked as duplicate.
There is a flag `DD_DUPLICATE_CLUSTER_CASCADE_DELETE` / `DUPLICATE_CLUSTER_CASCADE_DELETE` that can be set to `True` to revert to the old behavior. The default is `False`.
To achieve this, we had to change the `on_delete` parameter of the `duplicate_finding` field. This can be done without a new migration as it doesn't …
=> don't delete all duplicates when deleting an original, fix product grade on deletion.

dojo/templates/dojo/view_product_details.html
The panel for benchmark results is currently shown unconditionally in the product details view, even when benchmarks have been disabled in the system settings. With this PR the benchmarks results are only shown when benchmarks are enabled in the system settings.
=> Show benchmark results in Product view only when benchmarks are enabled

dojo/forms.py, dojo/jira_link/helper.py, dojo/jira_link/views.py, dojo/unittests/test_jira_config_product.py
fixes #4225 where authorization to JIRA Cloud fails when adding/editing a JIRA instance.
=> jira: remove validate parameter on config change

dojo/forms.py
Sometimes somebody adds a field on de model, but forgets to exclude it on the form used to delete that model. And the delete page then looks something like this:
This PR changes from `exclude=[field1,field2, ...]` to `fields=[]`. This makes user no model fields are shown. The delete still works as the `id` field is explicitly defined.
To be honest I think we probably shouldn't use a separate from for each model just to be able to delete them, but for now I created this easy PR making it at least more clean.
=> don't show fields on delete forms

dojo/db_migrations/0026_login_banner.py, dojo/models.py, dojo/templates/dojo/login.html, dojo/templatetags/get_banner.py
The login banner currently doesn't allow any html or clickable urls. That could be helpful to add a link to login/sso instructions or terms of use or just a link to fred.com:
This PR allows the basic html tags allowed by the bleach library and a couple of styling tags, i.e. to give a nice blue color to the url and to let it open in a new tab.
Also tried to simplify the setup and do something straightforward like {% if get_banner.banner_enable %} but apparently the django templates require this weird construct with passing in strings into filters/tags.
=> login banner: allow clickable urls

dojo/engagement/views.py, dojo/product/urls.py, dojo/product/views.py, dojo/templates/base.html, dojo/templates/dojo/breadcrumbs/engagement_breadcrumb.html, dojo/templates/dojo/new_eng.html, dojo/templates/dojo/snippets/engagement_list.html, tests/product_test.py, tests/test_test.py
Interactive engagements and CI/CD engagements are currently separated in the Product tab. This might be confusing for users, when they have to look in 2 different lists to search for an engagement. A poll in Slack (https://owasp.slack.com/archives/C2P5BA8MN/p1617816100165000) gave a clear picture other users are thinking the same. This PR integrates both types of engagements in one list under the Product tab:
The list contains a new column to show the type of the engagement. To make room for the new column, the "Updated" column at the end of the list has been removed.
=> Integrate interactive and ci/cd engagements in one list

dojo/tools/nexpose/parser.py, dojo/unittests/scans/nexpose/many_vulns.xml, dojo/unittests/tools/test_nexpose_parser.py
I detected a specific edge-case during uploading the Nexpose scan.
https://github.com/DefectDojo/django-DefectDojo/pull/4253/files#diff-9b8c501e2c41cd9044be3c009bbae118d0c80c454883a40bb0f99602b20b27daR6672
=> Nexpose parser - fix edge-case - port is defined but service is "<unknown>"

dojo/models.py
When the repository is given in the Engagement, the UI shows links to the source code in the repository. With this PR, the line number will be added to the link, so that the line of the vulnerability with the vulnerability will be highlighted. Works with GitHub and GitLab.
=> Add line number to repository link

dojo/finding/helper.py, dojo/forms.py
fixes 2 exceptions in 1.14.1 when adding a finding from a template:
```
File "/home/valentijn/dd/dojo/forms.py", line 2283, in __init__
if self.instance.has_jira_group_issue:
AttributeError: 'NoneType' object has no attribute 'has_jira_group_issue'
```
and
```
File "/home/valentijn/dd/dojo/finding/helper.py", line 58, in update_finding_status
if 'is_Mitigated' in changed_fields or is_new_finding:
TypeError: argument of type 'NoneType' is not iterable
```
=> fix Nonetype when adding from template

dojo/models.py
the __str__ was referencing invalid field names, causing an exception when trying to delete a product with github integration enabled.
=> fix __str__ for GitHub_Issue model

helm/defectdojo/Chart.yaml, helm/defectdojo/values.yaml
Fixes #4276
In the rabbitMQ helm chart, the default for `memoryHighWatermark.enabled` is false, astonishingly, causing it to not push back whenever it starts drowning.
https://github.com/bitnami/charts/tree/master/bitnami/rabbitmq/#installing-the-chart
This PR enables memory high watermark and will prevent rabbitMQ from crashing when processing a lot of messages.
=> Set rabbitMQ memory high watermark

dojo/engagement/views.py, dojo/fixtures/dojo_testdata.json, dojo/importers/utils.py, dojo/test/views.py
for ci/cd engagements the updating of timestamps failed. made sure there's at least 1 ci/cd enagement in the testdata fixture.
=> Fix datetime/date mismatch between CICD engagement and test

dojo/tools/nexpose/parser.py
Python 3.9 removed support for `getchildren` according to https://docs.python.org/3/whatsnew/3.9.html#removed
> * Methods getchildren() and getiterator() of classes ElementTree and Element in the ElementTree module have been removed. They were deprecated in Python 3.2. Use iter(x) or list(x) instead of x.getchildren() and x.iter() or list(x.iter()) instead of x.getiterator(). (Contributed by Serhiy Storchaka in bpo-36543.)
https://bugs.python.org/issue36543
This could lead to error: 
```
AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'getchildren'
```
=> [Nexpose parser] Fix error with Python 3.9

dojo/importers/reimporter/reimporter.py
Both the API and UI set close_old_findings to True for reimport, so all works well.
But in the reimporter.py kwarg the default is False, which is confusing and could lead to future bugs.
=> reimporter: make close_old_findings True by default everywhere

dojo/management/commands/dedupe.py, dojo/templates/dojo/view_finding.html
sometimes it's useful to be able to see the hash_code values for findings when debugging some deduplication behaviour.
also add output to the `dedupe.py` command to show when a hash_code is actually changed.
=> view_finding: show hash_code in title of ID field

dojo/settings/settings.dist.py, dojo/tools/spotbugs/parser.py
With the legacy deduplication algorithm, the reimport of a SpotBugs report closes a majority of the findings. When using the hash_code it produces the expected results.
[EDIT] hash_code uses now the line number as well. There can be multiple instances for one CWE in a file, eg. when you have a controller providing some REST-Endpoints.
Furthermore there are 2 minor enhancements of the parser:
- Newlines for the description, otherwise it is just a long unreadable string
- Removal of 'N/A' for impact and references because they can be NULL now
=> SpotBugs: Use hash_code for deduplication and minor enhancements

dojo/importers/importer/importer.py, dojo/importers/utils.py, dojo/unittests/dojo_test_case.py, dojo/unittests/scans/clair/few_vuln.json, dojo/unittests/test_import_reimport.py
A server error occurs when importing a scan in the apiv2 with the parameter endpoint_to_add and TRACK_IMPORT_HISTORY=True. 
This PR adds a test which (currently) breaks.
---
=> Import History: fix Endpoint JSON Serialization issue

dojo/importers/reimporter/reimporter.py
When re-importing, the hashcode of a finding is computed before it is compared with other findings. The test type is used in this hashcode. Some parsers, such as Qualys WebApp, do not supply the test to each finding object it creates. This results in the following exception:
`dojo.models.Finding.test.RelatedObjectDoesNotExist: Finding has no test.`
to combat this, check for a test object before computing the hash code, and if it does not exist, add the test to the finding. This step was initially done if a new finding was actually created if another finding did not match the new one, but moving that step a bit further up does not change anything.
=> Re-import fix "Finding has not test" exception

dojo/tools/gitlab_sast/parser.py, dojo/unittests/scans/gitlab_sast/gl-sast-report_issue4344.json, dojo/unittests/tools/test_gitlab_sast_parser.py
One attribute is missing 'severity'
Fixes #4344
=> [Gitlab SAST parser] Fixes missing severity error

dojo/tools/nikto/parser.py, dojo/unittests/scans/nikto/nikto-output.xml, dojo/unittests/scans/nikto/tdh.json, dojo/unittests/scans/nikto/tdh.xml, dojo/unittests/tools/test_nikto_parser.py
=> [Nikto parser] Fix severity and add more unit tests

dojo/fixtures/dojo_testdata.json, dojo/unittests/test_jira_import_and_pushing_api.py, dojo/unittests/vcr/jira/JIRAImportAndPushTestApi.test_create_edit_update_finding_no_push_to_jira.yaml, dojo/unittests/vcr/jira/JIRAImportAndPushTestApi.test_engagement_epic_creation.yaml, dojo/unittests/vcr/jira/JIRAImportAndPushTestApi.test_engagement_epic_mapping_disabled_create_epic_and_push_findings.yaml, dojo/unittests/vcr/jira/JIRAImportAndPushTestApi.test_engagement_epic_mapping_disabled_no_epic_and_push_findings.yaml, dojo/unittests/vcr/jira/JIRAImportAndPushTestApi.test_engagement_epic_mapping_enabled_create_epic_and_push_findings.yaml, dojo/unittests/vcr/jira/JIRAImportAndPushTestApi.test_engagement_epic_mapping_enabled_no_epic_and_push_findings.yaml, dojo/unittests/vcr/jira/JIRAImportAndPushTestApi.test_import_no_push_to_jira_but_push_all.yaml, dojo/unittests/vcr/jira/JIRAImportAndPushTestApi.test_import_no_push_to_jira_reimport_no_push_to_jira_but_push_all_issues.yaml, dojo/unittests/vcr/jira/JIRAImportAndPushTestApi.test_import_no_push_to_jira_reimport_push_to_jira_is_false_but_push_all_issues.yaml, dojo/unittests/vcr/jira/JIRAImportAndPushTestApi.test_import_no_push_to_jira_reimport_with_push_to_jira.yaml, dojo/unittests/vcr/jira/JIRAImportAndPushTestApi.test_import_push_to_jira_reimport_with_push_to_jira.yaml, dojo/unittests/vcr/jira/JIRAImportAndPushTestApi.test_import_twice_push_to_jira.yaml, dojo/unittests/vcr/jira/JIRAImportAndPushTestApi.test_import_twice_push_to_jira_push_all_issues.yaml, dojo/unittests/vcr/jira/JIRAImportAndPushTestApi.test_import_with_push_to_jira.yaml, dojo/unittests/vcr/jira/JIRAImportAndPushTestApi.test_import_with_push_to_jira_add_comment.yaml, dojo/unittests/vcr/jira/JIRAImportAndPushTestApi.test_import_with_push_to_jira_epic_as_issue_type.yaml, dojo/unittests/vcr/jira/JIRAImportAndPushTestApi.test_import_with_push_to_jira_is_false_but_push_all.yaml
during unit tests every push to JIRA resulted in an error because dojo was trying to add the issue to an epic, which didn't exist.
this error is swallowed silently by dojo so it was not failing the tests, but the logs were insinuating something was wrong.
most of the files changed are just re-recordings of the jira traffic
=> jira: fix silent epic error during unit tests

dojo/tools/nexpose/parser.py, dojo/unittests/scans/nexpose/dns.xml, dojo/unittests/tools/test_nexpose_parser.py
Nexpose parser: DNS service - add identification of L4 protocol
In the case of DNS, some vulnerabilities are relevant only for UDP and some of them are relevant for TCP+UDP. It is important to identify UDP and TCP services as different endpoints.
=> [Nexpose parser] add identification of L4 protocol tcp/udp for DNS service

.github/workflows/k8s-testing.yml, helm/defectdojo/Chart.yaml, helm/defectdojo/values.yaml
Thanks to @dsever we finally found out why the GHA k8s workflow was failing randomly. This PR enables logging and that showed that the initilializer sometimes went out of memory. So we increase the limits a little bit and now it seems to run more consistently successful.
=> k8s: increase initializer memory

Dockerfile.django, Dockerfile.integration-tests, Dockerfile.nginx
The kubernetes deployment in GHA keeps failing on Python 3.7, but works fine consitently on 3.8 so I propose we go with 3.8.
Fixes #4359
Python 3.8 also uses pip 21.1 which, by default, uses the new dependency resolver algorithm that caused a lot of issues in the past, but is now finally resolved as we can see in the tests in this PR and in #2978
=> Bump python to 3.8

dojo/tools/anchore_engine/parser.py
Add an optional field to add a custom vulnerability description in the Anchore parser. This will allow to enrich the finding description with further details which describes the vulnerability. 
For example, one could augment the details by grabbing informations from Anchore at https://anchore-api.mydomain.com/v1/query/vulnerabilities?id=CVE-ID URL and populate DefectDojo with more useful data.
=> Anchore parser: add optional custom vulnerability description

dojo/tools/nessus/parser.py
As a new DefectDojo user, I thought I had a corrupt .nessus file, until I renamed it with .xml.
This change recognizes XML exports with the `.nessus` extension, matching the documentation at line #245.
Also clarifies the error when trying to import a Nessus file.
=> Recognize .nessus file names

.github/workflows/gh-pages.yml
The GitHub actions step to deploy the GitHub pages with the new documentation theme has failed. This PR uses the Hugo template found in https://github.com/marketplace/actions/hugo-setup#%EF%B8%8F-workflow-for-autoprefixer-and-postcss-cli
=> Use hugo template for github actions

.github/release-drafter.yml
Just to make that more visible in the release notes.
=> Make hashcode recomputation visible in release notes

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md, CONTRIBUTING.md, README.md, docs/config.toml, docs/content/en/integrations/jira.md, dojo/__init__.py, dojo/templates/dojo/view_product_details.html, dojo/templates/dojo/view_product_type.html, dojo/templates/dojo/view_user.html, dojo/tools/risk_recon/api.py, tests/Import_scanner_test.py
Now the new documentation got deployed, great. Unfortunately it wasn't a good idea to make the URL shorter and get rid of the project name. This doesn't work, so this PR puts the project name back in the URL. Sorry about all the PR's.
=> Documentation: Put django-DefectDojo back in the URL

.github/workflows/test-helm-chart.yml
Missed some stuff, testing in my fork (probably not all cases, but good enough I'd say).
Against `master` for immediate effect.
=> Helm chart linting: specify target branch for all ct

dojo/db_migrations/0098_anchore_vuln_id.py, dojo/fixtures/initial_surveys.json, dojo/tools/anchore_engine/parser.py, dojo/unittests/tools/test_anchore_engine_parser.py
As discussed in https://owasp.slack.com/archives/C014H3ZV9U6/p1619635577100800
No real impact out of the box, unless for people that may have used a different dedupe algo than the default for this parser.
=> Anchore parser, use vuln_id_from_tool instead of unique_id_from_tool

dojo/management/commands/dedupe.py, dojo/utils.py
Fixes https://github.com/DefectDojo/django-DefectDojo/issues/4426
=> Fix exception when running dedupe management command

dojo/filters.py, dojo/fixtures/dojo_testdata.json, dojo/unittests/test_metrics_queries.py
Stumbled over a bug while testing: When a user cannot see any Endpoints, the metrics for Endpoints will show a HTTP 500 error, because an Exception is not handled in `dojo.filters.get_earliest_finding()
=> Bugfix: Handle Exception in Endpoint metrics when no Endpoints visible

dojo/tools/mozilla_observatory/parser.py, dojo/unittests/scans/mozilla_observatory/demo.json, dojo/unittests/scans/mozilla_observatory/juicy.json, dojo/unittests/scans/mozilla_observatory/mozilla_org.json, dojo/unittests/scans/mozilla_observatory/nmap_scanme.json, dojo/unittests/scans/nmap_scanme.json, dojo/unittests/tools/test_mozilla_observatory_parser.py
Modify the parser to support reports generated by the Python CLI 
Fixes #4436
=> [Mozilla parser] support Python CLI

dojo/finding/views.py
when setting a finding as original manually via the UI or API, the check on deduplication inside engagement was broken, i.e. not performed
=> mark as duplicate/original: fix deduplication inside engagement check

docs/content/en/usage/permissions.md, dojo/api_v2/serializers.py, dojo/authorization/roles_permissions.py
=> Authorization V2: Fixes for role name in API and permissions for role API_Importer

.github/workflows/test-helm-chart.yml
All the k8s installation tests already run in their own GHA's matrices.
The install step in the linting GHA actually never worked. The secrets were never created in the first place. I've put the (somewhat) working config in comments, but we don't need it (it still time out on some weird conditions and I am not going to investigate).
=> Remove ct install step

docker/entrypoint-uwsgi-dev.sh, dojo/wsgi.py
If `DD_DEBUG` is somehow set to `False`, then the `dev` env would also enter single process mode like `debug`.
This basically ensures that `DD_DEBUG` must be set to `True` in the entrypoint.
=> Fix erroneous comparison causing dev env to also be single process

docs/content/en/contributing/how-to-write-a-parser.md
During development, I tried to run unit tests according to [documentation](https://defectdojo.github.io/django-DefectDojo/contributing/how-to-write-a-parser/#run-your-tests), but I get this error:
```
defectdojo@dccdeec6caf6:/app$ python manage.py test dojo.unittests.test_gitleaks_parser.TestGitleaksParser
[12/May/2021 15:47:00] INFO [dojo.models:3363] enabling audit logging
System check identified no issues (0 silenced).
E
======================================================================
ERROR: test_gitleaks_parser (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_gitleaks_parser
File "/usr/local/lib/python3.6/unittest/loader.py", line 153, in …
```
=> Fix docs example to run unittests

dojo/settings/settings.dist.py
By default, any user, successfully logged in using SAML2 is automatically created in DD.
`DD_SAML2_CREATE_USER = False` (default `True`) brings the ability to deny to log in users who haven't been already created yet.
=> Add DD_SAML2_CREATE_USER

docs/content/en/integrations/import.md, dojo/tools/dockle/parser.py, dojo/unittests/scans/dockle/many_findings.json, dojo/unittests/scans/dockle/no_findings.json, dojo/unittests/tools/test_dockle_parser.py
Dockle - Container Image Linter for Security, Helping build the Best-Practice Docker Image, Easy to start.
It could be found at: https://github.com/goodwithtech/dockle
=> Add new parser - Dockle

dojo/settings/settings.dist.py, dojo/user/urls.py, dojo/user/views.py
If `DD_SOCIAL_AUTH_SHOW_LOGIN_FORM` is set to `False` (local login is not allowed) and there is exactly one Social Auth definition, the `/login` page automatically redirect to the Social login form.
There is no reason to show only one Social button.
=> Auto-redirect when only one Social Auth is defined

dojo/forms.py
Fix a small typo in the engagement's Jira inheritance configuration support message.
=> Fix small UI typo in inherited Jira config

docs/content/en/integrations/api-v2-docs.md, dojo/settings/settings.dist.py, requirements.txt
`drf-yasg` is used for Swagger/OpenAPI spec generation.
https://github.com/axnsan12/drf-yasg/
=> remove obsolete django-rest-swagger dependency

dojo/settings/settings.dist.py, dojo/tools/coverity_api/parser.py, dojo/unittests/tools/test_coverity_api_parser.py
Add `verified` flag and manage it with classification and status data.
This pull request follows #4393
=> [Coverity API parser] add verified data and de-duplication algorythm (unique ID)

requirements.txt
I tested the DefectDojo source code with Snyk and 2 problems were found:
- https://snyk.io/vuln/SNYK-PYTHON-DJANGO-1279042
- https://snyk.io/vuln/SNYK-PYTHON-DJANGO-1290072
Looking at Django releases:
- https://docs.djangoproject.com/en/3.2/releases/3.1.9/
- https://docs.djangoproject.com/en/3.2/releases/3.1.10/
- https://docs.djangoproject.com/en/3.2/releases/3.1.11/
Noticed that there are only CVE fixes and bugfixes.  Checked the work locally and it still works.
=> upgrade django 3.1.8 -> 3.1.11

docs/content/en/integrations/import.md, dojo/settings/settings.dist.py, dojo/tools/terrascan/parser.py, dojo/unittests/scans/terrascan/many_findings.json, dojo/unittests/scans/terrascan/no_findings.json, dojo/unittests/tools/test_terrascan_parser.py
Terrascan is a static code analyzer for Infrastructure as Code.
It could be found at: https://github.com/accurics/terrascan
=> add new parser - terrascan

dojo/templates/dojo/simple_search.html
Simple search view would raise an exception if an `EndPoint` without `product` was in the search results.
=> search: don't fail on endpoints without product

dojo/authorization/authorization.py, dojo/filters.py, dojo/models.py, dojo/unittests/authorization/test_authorization.py
The caching of member and groups wasn't efficient when there are many products or product types in one list. This PR decreases the number of SQL request substantially.
=> Authorization V2: Performance optimization

dojo/api_v2/permissions.py, dojo/api_v2/serializers.py, dojo/api_v2/views.py, dojo/authorization/authorization.py, dojo/authorization/roles_permissions.py, dojo/endpoint/queries.py, dojo/engagement/queries.py, dojo/finding/queries.py, dojo/finding_group/queries.py, dojo/product/queries.py, dojo/product_type/queries.py, dojo/test/queries.py, dojo/unittests/test_metrics_queries.py, dojo/unittests/test_swagger_schema.py, dojo/urls.py, dojo/user/queries.py
As a follow-up to #4503, this PR adds:
- the API for `Dojo_Group`, `Product_Group` and `Product_Type_Group`
- the remaining queries to read data when a user is authorized by being a group member
The only thing missing to make groups fully functional is the user interface. This is currently being developed by Nick Cleary.
=> Authorization V2: API and queries for groups

dojo/api_v2/permissions.py, dojo/unittests/test_apiv2_endpoint.py
Improved error code and message when the primary key of necessary relationship in a POST of the API is missing, This fixes a new unit test that was broken for Authentication V2.
=> Authorization V2: Improved error code and message

dojo/decorators.py, tests/Import_scanner_test.py, tests/base_test_class.py, tests/dedupe_test.py, tests/endpoint_test.py, tests/engagement_test.py, tests/environment_test.py, tests/finding_test.py, tests/ibm_appscan_test.py, tests/note_type_test.py, tests/notes_test.py, tests/product_member_test.py, tests/product_test.py, tests/product_type_member_test.py, tests/product_type_test.py, tests/regulations_test.py, tests/report_builder_test.py, tests/search_test.py
=> Fix celery to be used in integration tests

dojo/utils.py
When using a parser that has a dedupe algorithm set to `DEDUPE_ALGO_UNIQUE_ID_FROM_TOOL_OR_HASH_CODE`, such as Veracode, deduplication would occur between products. This can be seen by importing the same report into two different products
=> Stop deduplication across products

requirements.txt
Reverts DefectDojo/django-DefectDojo#4590
=> Revert "Bump urllib3 from 1.26.4 to 1.26.5"

docs/content/en/integrations/import.md, dojo/tools/generic/parser.py, dojo/unittests/scans/generic/generic_report3.json, dojo/unittests/tools/test_generic_parser.py
Add support for endpoints for Generic parser (JSON)
```JSON
{
"findings": [
{
"title": "test title with endpoints as dict",
"description": "Some very long description with\n\n some UTF-8 chars à qu'il est beau",
"severity": "Medium",
"mitigation": "Some mitigation",
"date": "2021-01-06",
"cve": "CVE-2020-36234",
"cwe": 261,
"cvssv3": "CVSS:3.1/AV:N/AC:L/PR:H/UI:R/S:C/C:L/I:L/A:N",
"file_path": "src/first.cpp",
"line": 13,
"endpoints": [
{
"host": "exemple.com"
}
]
},
{
"title": "test title with endpoints as strings",
"description": "Some very long description with\n\n some UTF-8 chars à qu'il est beau2",
"severity": "Critical",
"mitigation": "Some mitigation",
"date": "2021-01-06",
"cve": "CVE-2020-36235",
"cwe": 287,
"cvssv3": "CVSS:3.1/AV:N/AC:L/PR:H/UI:R/S:C/C:L/I:L/A:N",
"file_path": …
```
=> Add endpoints to generic parser for JSON format

dojo/forms.py, dojo/product/views.py, dojo/product_type/views.py, dojo/templates/dojo/new_product_member.html, dojo/templates/dojo/new_product_member_user.html, dojo/templates/dojo/new_product_type_member.html, dojo/templates/dojo/new_product_type_member_user.html, dojo/templates/dojo/view_product_details.html, dojo/templates/dojo/view_product_type.html, dojo/templates/dojo/view_user.html, dojo/user/views.py, tests/product_member_test.py, tests/product_type_member_test.py
This PR optimizes the user interface and lets the user add multiple product members or product type members at once. When you are adding members for a product or product type you can add multiple users with the same role. When you are adding members for a user you can add multiple products or product types.
=> Authorization V2: Add multiple members at once

docs/content/en/integrations/import.md
The documentation doesn't specify that Yarn Audit is supported.
I was greatly surprised when I was looking for the scanner array in Swagger's API 👍
It's a very small change at the end of **import.md** file, but I just noticed that my VS Code has automatically **removed trailing spaces** after I commit... Hope it doesn't matter too much.
=> fix: missing Yarn Audit support in documentation

dojo/authorization/authorization.py, dojo/endpoint/queries.py, dojo/engagement/queries.py, dojo/finding/queries.py, dojo/finding_group/queries.py, dojo/product/queries.py, dojo/product_type/queries.py, dojo/test/queries.py, dojo/unittests/authorization/test_authorization.py
There are three possibilities for users and global roles:
- User has no Global_Role object: that case worked
- User has a Global_Role object pointing to a Role: that case worked as well
- User has a Global_Role object where the Role is None: that case produced an exception --> That is now fixed with this PR
=> Bugfix for global roles

dojo/api_v2/prefetch/utils.py
Due to a indentation bug the one-to-one relationships were missing from the API specs since #4541
=> fix missing one-to-one relationships from prefetch API specs

dojo/tools/sarif/parser.py, dojo/unittests/scans/sarif/dockle_0_3_15.sarif, dojo/unittests/tools/test_sarif_parser.py
=> SARIF parser: implement 'level' (severity) attribute

dojo/tools/generic/parser.py, dojo/unittests/scans/generic/generic_report4.csv, dojo/unittests/scans/generic/generic_report4.json, dojo/unittests/tools/test_generic_parser.py
The generic importer uses Endpoint.from_uri() see https://github.com/DefectDojo/django-DefectDojo/blob/64701f1dac416b4baa08f9f1d4609ab0438481ef/dojo/tools/generic/parser.py#L49-L53, which relies on hyperlink.parse() introduced in #4473.
This library, however, does not support url's without protocol. Example: hyperlink.parse("www.google.com") creates an object with `host: None` and `path: "/www.google.com"`.
There exists a workaround for this in some places in the code like:
https://github.com/DefectDojo/django-DefectDojo/blob/64701f1dac416b4baa08f9f1d4609ab0438481ef/dojo/forms.py#L1365-L1370
This PR, brings the same capabilities to the generic importer.
=> Fix generic parser import endpoint without protocol

docs/content/en/integrations/import.md, dojo/settings/settings.dist.py, dojo/tools/meterian/parser.py, dojo/unittests/scans/meterian/report_invalid.json, dojo/unittests/scans/meterian/report_many_vulns.json, dojo/unittests/scans/meterian/report_multi_language.json, dojo/unittests/scans/meterian/report_no_vulns.json, dojo/unittests/scans/meterian/report_one_vuln.json, dojo/unittests/scans/meterian/report_one_vuln_no_remediation.json, dojo/unittests/tools/test_meterian_parser.py
Added Meterian scanner which accepts JSON reports.
=> Added Meterian Scanner

docs/content/en/getting_started/upgrading.md, docs/content/en/usage/permissions.md, dojo/db_migrations/0108_auth_v2_migrate_user_roles.py, dojo/db_migrations/0109_auth_v2_migrate_user_roles.py, dojo/management/commands/migrate_authorization_v2.py, dojo/settings/settings.dist.py
The management command `migration_authorization_v2` creates Product_Members and Product_Type_Members:
- Staff users currently have all permissions for all product types and products --> Every staff users gets the Owner role for all product types.
- Authorized users for product types or products types currently are non-staff users. They get a role for the respective product type or product based on the settings parameter `AUTHORIZED_USERS_ALLOW_STAFF`:
- If that parameter is `False`, authorized users can only read the product type / product and they will get the role Reader.
- If that parameter is `True`, they have all permissions and will get the role Owner.
The settings parameters `AUTHORIZED_USERS_ALLOW_CHANGE` and `AUTHORIZED_USERS_ALLOW_DELETE` give authorized users currently …
=> Authorization V2: Management command to migrate users and set Auth V2 as the default

dojo/tools/burp/parser.py
This aims at fixing import issues when:
1. A response is missing from the request/response pair.
2. Propose a simpler way of dealing with non-utf-8 compliant requests/responses. Sometimes it can be a single character that breaks this and not always in the body of the request/response.
=> Fix Burp Import Issues

dojo/group/queries.py, dojo/product/queries.py, dojo/product_type/queries.py, dojo/user/urls.py, dojo/user/views.py
This PR contains 3 topics:
- Bugfix: There was a server error when a staff-user without a global role views another user with a global role
- Optimization: There where duplicated selects to read the Role in dialogues for Product, Product Type, User and Group
- Maintenance: There was still functionality to get a API key for API V1, which caused a server error
=> Authorization V2: One bugfix and some optimizations

docker-compose.yml
A new volume with a generic name gets created everytime you start the dev or other environment with docker. This volume contains files for RabbitMQ. https://hub.docker.com/_/rabbitmq states:
> This image makes all of /var/lib/rabbitmq a volume by default
`var/lib/rabbitmq` contains RabbitMQ's internal database among other things.
This PR inserts a volume statement for docker-compose so that the same volume is used every time the container is started. Otherwise messages, that have not yet been consumed, could get lost with a restart.
=> Docker volume for /var/lib/rabbitmq

dojo/tools/dockle/parser.py, dojo/unittests/tools/test_dockle_parser.py
Findings from the Dockle parser are marked as static and dynamic findings, which causes problems with reimports. This PR marks the findings as static only.
Additionally I removed the prefix "Found " from the title, as it doesn't add any information but makes the titles more crowded and distracts from the useful information.
=> Dockle parser findings marked static and dynamic

dojo/tools/kubebench/parser.py, dojo/unittests/scans/kubebench/kube-bench-controls.json, dojo/unittests/tools/test_kubebench_parser.py
Fix for  #4765. The file format of kube-bench has changed, compared to the file format used when the parser was initially written.
While working on it I have enhanced the description of findings and did some refactoring.
=> Fix kubebench parser to work with newer versions

docker/entrypoint-initializer.sh, dojo/forms.py, dojo/home/views.py, dojo/management/commands/migrate_textquestions.py, dojo/survey/views.py, dojo/templates/defectDojo-engagement-survey/assign_survey.html, dojo/templates/defectDojo-engagement-survey/list_questions.html, dojo/templates/defectDojo-engagement-survey/list_surveys.html, dojo/templates/defectDojo-engagement-survey/surveys.html, dojo/templates/dojo/dashboard.html
This PR solves several problems with questionnaires:
- Operations on questionnaires that are linked to engagements are now completely authorized with AuthV2
- The script to change the `polymorphic_ctype_id` of the fixture for text questions didn't work with docker, because all files in the docker container are write protected. It has been replaced by a new script, which does a SQL update after the fixture has been loaded
- Questions couldn't been edited because of failing check of the type of the question
- The design of the questionnaires list and questions list had some layout problems and are now more in line with other dialogues
=> Bugfixes for Questionnaires

dojo/github.py
There is no `GitHub-body.tpl' file (and never was from what it looks like) so use the Jira one instead since it already does a good job at listing all pertinent info.
=> Fix Github Issue Creation

dojo/tools/factory.py
Made some tests with Python > 3.6 (the current version of our containers) and the loading fail.
This patch will make us ok with version 3.8 and 3.9.
=> Improve factory to support Python >= 3.8

dojo/tools/detect_secrets/parser.py, dojo/unittests/scans/detect_secrets/many_findings.json, dojo/unittests/tools/test_detect_secrets_parser.py
This Pull Request includes a fix in [detect-secrets](https://github.com/Yelp/detect-secrets) parser to skip the findings established as False Positive. For that, I check the value of the `is_secret` field:
- If the `is_secret` field is not present, the finding could be a real secret.
- If the `is_secret` field it's true, the finding it's a real secret.
- If the `is_secret` field it's false, the finding it's a false positive.
The reference to the `is_secret` field can be checked in this [link](https://github.com/Yelp/detect-secrets/blob/b206dc29f274839ebd3c522fed19448c9b8f3f70/detect_secrets/core/potential_secret.py#L40).
=> Skip false positives from detect-secrets report

dojo/db_migrations/0115_test_type_active.py, dojo/db_migrations/0116_test_type_active.py, dojo/models.py, dojo/tools/factory.py
Add a flag `active` in `Test_Type` entity to disable or enable a parser. `True` by default.
I made the modification aligned with the current behavior, i.e. default to "all parser enabled", but it will be easy to block one parser by API or directly in DB for now.
=> Add flag to enable/disable a parser

dojo/templates/dojo/engagement.html, dojo/templates/dojo/engagements_all.html
The bordered tables for Active Engagements and All Engagements where the last tables with borders in DefectDojo. Now the table are visually in sync with the other tables. Plus some other minor changes to improve the user experience for these 2 dialogues.
=> Slight visual overhaul for Engagements

docs/content/en/integrations/rate_limiting.md, dojo/decorators.py, dojo/settings/settings.dist.py, dojo/user/views.py, requirements.txt
Dependent on #4783
Add the ability to rate limit the login page. 
Uses https://github.com/jsocol/django-ratelimit
=> Add Rate Limiting to Login Page

dojo/filters.py
Fixes #4822
There was another user asking for the same thing on Slack and I can see the point of having the `unique_id_from_tool` in the filter. Same goes for `vuln_id_from_tool` so I moved this as well.
=> Bring unique_id_from_tool back to Finding filter

.github/workflows/new-release-master-into-dev.yml
The "merge back into dev" GHA failed because the file no longer exists.
=> Remove setup.py from GHA

dojo/finding/views.py, dojo/forms.py, dojo/user/queries.py
Reviews for findings had 2 problems that are fixed here:
- When a review gets requested, the attribute `under_review` in the finding is set to `True`. When the review is finished, this attribute was not set back to `False`.
- All staff users could be selected for review. This doesn't make sense anymore with the new authorization. Now all users can be selected who have the `Finding_Edit` permission.
While working on these problems I found 2 issue with selecting users by product and permission:
- The group membership was implemented wrongly
- Global roles where not implemented
=> Two problems with reviews for findings

dojo/tools/nessus/parser.py
Fixes following error when fqdn is missing in XML:
```
ERROR [dojo.importers.utils:27] argument of type 'NoneType' is not iterable
File "/app/./dojo/importers/utils.py", line 16, in parse_findings
parsed_findings = parser.get_findings(scan, test)
File "/app/./dojo/tools/nessus/parser.py", line 254, in get_findings
return NessusXMLParser().get_findings(filename, test)
File "/app/./dojo/tools/nessus/parser.py", line 213, in get_findings
if '://' in fqdn:
TypeError: argument of type 'NoneType' is not iterable
```
=> Nessus parser: Fix error when fqdn is missing

dojo/templates/notifications/sla_breach.tpl, dojo/utils.py
Fixes one bug and one enhancement:
- #4848 - Finding has no 'grouped' attribute when sending notifications
- #4871 - Add Product name in MS Teams notifications and enhance URL in View button for SLA Breach
=> Bugfix and enhancement for SLA notifications

Dockerfile.integration-tests, tests/base_test_class.py
Today the integration tests were not running anymore, because the latest chrome driver didn't support the current stable chromium browser, see https://github.com/DefectDojo/django-DefectDojo/runs/3192403317?check_suite_focus=true
According to https://chromedriver.chromium.org/downloads/version-selection the method how the chromium driver was selected is not reliable:
> In addition, the version of ChromeDriver for the current stable release of Chrome can be found at https://chromedriver.storage.googleapis.com/LATEST_RELEASE. However, using on this file may be less reliable than methods described above.
The Python library [chromedriver-autoinstaller](https://pypi.org/project/chromedriver-autoinstaller/) installs automatically the driver for the currently installed chromium browser and seems …
=> Install chromium driver in Python

dojo/engagement/views.py, dojo/templates/dojo/engagements_all.html
Russel Butturini reported 2 problems with engagement lists on Slack (https://owasp.slack.com/archives/C2P5BA8MN/p1627400327160700):
- The active engagements view shows all engagements (even those marked as completed).
- One other thing of note is that closed engagements show the "past due" designation even though they are closed.
This PR fixes both bugs.
=> Two bugfixes for engagemens lists

dojo/api_v2/serializers.py, dojo/api_v2/views.py, dojo/fixtures/dojo_testdata.json, dojo/unittests/test_rest_framework.py, dojo/urls.py
This PR contains 2 enhancements for the API:
- Added `/notifications` endpoint: Fixes  #4827
- Enhanced `/metadata` endpoint: A user asked on Slack to search for products via their metadata (https://owasp.slack.com/archives/C2P5BA8MN/p1627868437022900). This PR makes metadata searchable by values and introduces a prefetch for related objects.
=> Added API for Notifications and enhancements for MetaData API

dojo/fixtures/defect_dojo_sample_data.json
There are two references to a file uploads on a finding that do not exist in the fixtures file. Removing them allows the fixtures to run again without failure
=> Remove nonexisting file reference in sample data

.github/workflows/new-release-master-into-dev.yml, .github/workflows/new-release-pr.yml, helm/defectdojo/Chart.yaml
Submitted against `master` for immediate effect, addresses #4920.
An issue we've been having is at https://github.com/DefectDojo/django-DefectDojo/runs/3173934689?check_suite_focus=true
This PR will check the current chart version with 
```
CURRENT_CHART_VERSION=$(grep -oP 'version: (\K\S*)?' helm/defectdojo/Chart.yaml)
```
and then smartly increment it and also adding a `-dev` suffix (per @valentijnscholten's feedback)
```
sed -r "s/version: \S+/$(echo "version: $CURRENT_CHART_VERSION" | awk -F. -v OFS=. 'NF==1{print ++$NF}; NF>1{$NF=sprintf("%0*d", length($NF), ($NF+1)); print}')/" helm/defectdojo/Chart.yaml
```
(I did not come up with that last regex, some people are smarter than me)
Since we're now adding a `-dev` suffix to the chart's version, that suffix is removed automatically …
=> [GHA - release] Bump chart version when merging master back to dev

components/yarn.lock
based on https://github.com/DefectDojo/django-DefectDojo/pull/4939
=> security: update npm path-parse to 1.0.7

dojo/reports/urls.py, dojo/reports/views.py, dojo/templates/dojo/view_endpoint.html
Fix #4936
How: On report request: 
- show only active findings
- persist "host_view" (it was removed on click "apply filter")
One more: fix link on the top of graph
=> Endpoint: Fix report generation

dojo/models.py, dojo/unittests/test_endpoint_model.py
Hi 👋
I noticed that some ZAP reports weren't importing correctly, because the http queries in the endpoints DefectDojo was trying to create were to long for the database schema. I discussed the issue briefly in the slack channel: https://owasp.slack.com/archives/C2P5BA8MN/p1629462343181800
This PR truncates the path, query and fragment attributes to the max length specified in for the database columns.
=> Truncate Path, Query and Fragment Endpoint Fields to their Max Column Length

WRAPPERS.md
`dd-import` is not directly an API wrapper. It offers some convenience functions to make it easier to import findings and language data from CI/CD pipelines, see https://github.com/MaibornWolff/dd-import.
While I was at it I removed the notes regarding API v1 and API v2 because all wrappers support API v2 and API v1 doesn't exist anymore.
=> Added dd-import to WRAPPERS.md

docs/content/en/getting_started/upgrading.md, dojo/home/views.py
The deprecation notice for the legacy authorization will be shown:
- on top of the upgrading page in the documentation
- on top of the dashboard in the UI for superusers when the legacy authorization is still active
Additionally we might want to add the notice to the release notes for the next releases.
=> Deprecation notice for legacy authorization

dojo/tools/semgrep/parser.py, dojo/unittests/scans/semgrep/many_findings.json, dojo/unittests/tools/test_semgrep_parser.py
Recreated from #4818 
Updated semgrep parser.py to support the INFO severity
=> Semgrep: Add support for INFO severity

dojo/decorators.py, dojo/notifications/helper.py
When an import is done, or some bulk action is performed, Defect Dojo sometimes sends out notifications. Some of these can be quite slow, for example sending an e-mail via SMTP. With lots of users, this can slow down the UI quite a lot. Do an import, wait 30 seconds for the notifications to be sent.
In past, we made the notifications asynchronous for the above reason. However `django-tagulous` had a bug, or missing feature, where it didn't support the pickling used by our celery workers. So we had to make the notifications synchronous again in https://github.com/DefectDojo/django-DefectDojo/pull/3678.
In `django-tagulous` 1.2.0 pickling support was added, which means we can make the notifications asynchronous again in this PR.
We also remove some unused code from earlier attempts to work …
=> make notifications async again

tests/base_test_class.py
On the report builder we're seeing javascript errors since tuesday august 31st.
```
bootstrap.min.js:6 Uncaught TypeError: Cannot read properties of null (reading 'trigger')
at HTMLDivElement.u (bootstrap.min.js:6)
at HTMLDivElement.fn (jquery.js:5175)
at HTMLDivElement.handle (bootstrap.min.js:6)
at HTMLDivElement.dispatch (jquery.js:5430)
at HTMLDivElement.elemData.handle (jquery.js:5234)
at Object.trigger (jquery.js:8719)
at HTMLDivElement.<anonymous> (jquery.js:8797)
at Function.each (jquery.js:385)
at jQuery.fn.init.each (jquery.js:207)
at jQuery.fn.init.trigger (jquery.js:8796)
```
These happen with 2.2.0, 2.1.0 etc. We have a regex in the test suite that ignores this error, but the error message has changed slightly. This PR updates the regex. Also this error happens during manual …
=> fix javascript regex error detection

.github/workflows/unit-tests.yml, docker-compose.override.debug.yml, docker-compose.override.dev.yml, docker-compose.override.integration_tests.yml, docker-compose.override.unit_tests.yml, docker-compose.override.unit_tests_cicd.yml, docker-compose.yml
Fixes #4862
The new version of Docker Compose (see https://docs.docker.com/compose/cli-command/) behaves differently when there a special character like `*` in variables and throws error messages in these cases. This PR quotes all variables where input via environment variables is allowed and works with both versions of Docker Compose.
=> Support Docker Compose V2

dojo/tools/sarif/parser.py, dojo/unittests/scans/sarif/appendix_k4.sarif, dojo/unittests/scans/sarif/flawfinder.sarif, dojo/unittests/scans/sarif/gitleaks_7.5.0.sarif, dojo/unittests/tools/test_sarif_parser.py
According to specification, attribute `ruleId` could be missing from reports. (cf https://docs.oasis-open.org/sarif/sarif/v2.1.0/os/sarif-v2.1.0-os.html#_Toc34317643 )
> Not all existing analysis tools emit the equivalent of a ruleId in their output. 
This PR allow to import reports for tools that don't emit `ruleId` properly (like Gitleaks `7.5.0` which we use for a new unit tests)
=> Better support SARIF ruleId attribute

dojo/settings/settings.dist.py, dojo/tools/safety/parser.py
When using the safety parser in environments without internet connection it take a while until the parser using the fallback offline mode. Now you can configure to use offline mode only.
=> safety-parser: configurable offline mode

dojo/tools/cloudsploit/parser.py, dojo/unittests/scans/cloudsploit/cloudsploit_many_vul.json, dojo/unittests/tools/test_cloudsploit_parser.py
fix: in Aquasecurity's cloudsploit scan result "region" can be either… a string of a list of strings
=> fix: support Aquasecurity's cloudsploit "region" as list 

dojo/static/dojo/css/dojo.css
Old dropdown buttons were light blue, which blended too well with the header color. Changing them to white makes them more visible.
=> Changed Dropdown Button Color to White

dojo/templates/dojo/tool_type.html
In the dropdown menu of the _Tool Type_ page it says "Add Tool Configuration" (seemingly copied from the _Tool Configuration_ page). I updated it to say "Add Tool Type".
| Before | After |
| --- | --- |
| <img width="958" alt="before" src="https://user-images.githubusercontent.com/3742559/133085738-78e61a57-80c7-43c0-a0b4-fc902bbcc7d8.png"> | <img width="958" alt="after" src="https://user-images.githubusercontent.com/3742559/133085719-7f4c8945-91b6-46ac-8499-8f39889397ea.png"> |
Relatedly, I noticed what seems like a similar mistake in [`regulations_config.html`](https://github.com/DefectDojo/django-DefectDojo/blob/b44af80ddfb4535eba85b72e5ec707e96db61996/dojo/templates/dojo/regulations_config.html#L21) (also [the title](https://github.com/DefectDojo/django-DefectDojo/blob/b44af80ddfb4535e …
=> Update dropdown menu of Tool Type page

dojo/tools/detect_secrets/parser.py, dojo/unittests/tools/test_detect_secrets_parser.py
The detect-secrets parser has not some basic information (like description or CWE code). This information can be useful to users in order to have a better UX and filter by more fields (like CWE).
If someone detects more information to add, we can use this Pull Request to include it 😄
=> Improve detect-secrets parser

docs/content/en/getting_started/architecture.md
add note that MyISAM tables are required by `django-watson`
=> docs: add MyISAM requirement

dojo/static/dojo/css/dojo.css, dojo/templates/dojo/filter_snippet.html, dojo/templates/dojo/findings_list_snippet.html, dojo/templates/dojo/paging_snippet.html, dojo/templates/dojo/profile.html, dojo/templates/dojo/report_filter_snippet.html, dojo/templates/dojo/snippets/comments.html, dojo/templates/dojo/view_eng.html, dojo/templates/dojo/view_finding.html, dojo/templates/dojo/view_group.html, dojo/templates/dojo/view_product_details.html, dojo/templates/dojo/view_product_type.html, dojo/templates/dojo/view_test.html, dojo/templates/dojo/view_user.html, tests/group_test.py, tests/product_group_test.py, tests/product_type_group_test.py, tests/user_test.py
Inspired by #5074 I implemented some more UI improvements. The examples here show how it looks with this PR:
- Gaps were missing between some icons:
- Put **Page Size** and icon in one button, looks cleaner and **Page Size** was a button without functionality:
- **Apply Filters** button wasn't visible anymore because it was white:
- Moved the questions marks further left behind the titles of the heading and made them white:
- The **Notes** header in findings and tests is now blue as all the other headings:
=> UI improvements

dojo/tools/detect_secrets/parser.py, dojo/unittests/tools/test_detect_secrets_parser.py
The severity assigned to secrets detected by `detect-secrets` tool should be `High` and not `Medium`.
Hardcoded secrets weakness (CWE-798) is one of the **top 25 Most Dangerous Software Weaknesses** according to the `MITRE 2020 CWE Top 25` report: https://cwe.mitre.org/top25/archive/2020/2020_cwe_top25.html
In the previous reference we can view this table:
Hardcoded secrets weakness (CWE-798) has a averaged CVSS of 8.76 (**High**).
The gitleaks parser has `High` severity by default (https://github.com/DefectDojo/django-DefectDojo/blob/master/dojo/tools/gitleaks/parser.py#L51).
I think that is better use `High` severity by default because is closer to `Medium` for this vulnerability.
=> Change secrets severity in detect-secrets parser

dojo/finding/views.py, dojo/templates/dojo/promote_to_finding.html, dojo/templates/dojo/view_test.html, tests/test_test.py
Fixes #5075
This fix includes an integration tests to add and promote stub findings. There is no test to delete a stub finding because I haven't had the time to find out how Selenium works with a modal dialogue.
=> Repair stub findings

dojo/models.py
viewing engagements (and possible other functions) were broken if a product didn't have a sonarqube config
```
File "/home/dojo/venv/lib/python3.7/site-packages/django/forms/models.py", line 1157, in __iter__
yield self.choice(obj)
File "/home/dojo/venv/lib/python3.7/site-packages/django/forms/models.py", line 1171, in choice
self.field.label_from_instance(obj),
File "/home/dojo/venv/lib/python3.7/site-packages/django/forms/models.py", line 1240, in label_from_instance
return str(obj)
File "./dojo/models.py", line 1454, in __str__
return '{} | {}'.format(self.sonarqube_tool_config.name if self.sonarqube_tool_config else '', self.sonarqube_project_key)
File "/home/dojo/venv/lib/python3.7/site-packages/django/db/models/fields/related_descriptors.py", line 198, in __get__
"%s has no %s." % …
```
=> View engagement: fix sonarqubce config error

dojo/management/commands/validatededupeconfig.py
PR #4963 invented a check of the hashcode configuration. Unfortunately the checks were broken and resulted in a lot of messages during startup of a new instance. With this PR there is only a message when there is an unallowed field in the configuration and the names of field and scanner are part of the error message.
Log before this PR:
```
2021-09-16T12:10:21.2599632Z [36minitializer_1        |[0m [16/Sep/2021 12:10:21] ERROR [dojo.specific-loggers.deduplication:17] compute_hash_code - configuration error: some elements of HASHCODE_FIELDS_PER_SCANNER are not in the allowed list HASHCODE_ALLOWED_FIELDS. Using default fields
2021-09-16T12:10:21.2613437Z [36minitializer_1        |[0m [16/Sep/2021 12:10:21] ERROR [dojo.specific-loggers.deduplication:17] compute_hash_code - configuration …
```
=> Fix deduplication config check

dojo/tools/sarif/parser.py, dojo/unittests/scans/sarif/flawfinder.sarif, dojo/unittests/tools/test_sarif_parser.py
There was a bug when there is no severity in the result but only in the rule. Because of the default in the `get` these findings always got the severity **Medium**. Now they get the default severity of the rule.
While reading the specification about severities I came across the `kind` attribute, which was not taken into account so far.
=> SARIF parser: Fix severity in rule and take into account the kind attribute

dojo/reports/urls.py, dojo/reports/views.py, dojo/templates/dojo/findings_list_snippet.html, dojo/templates/dojo/view_test.html, requirements.txt, tests/base_test_class.py, tests/finding_test.py
The finding lists now provide an export functionality to download CSV and Excel files with the filtered findings:
This is a solution for #4900
Sample reports:
- [findings.xlsx](https://github.com/DefectDojo/django-DefectDojo/files/7224349/findings.xlsx)
- [findings.csv](https://github.com/DefectDojo/django-DefectDojo/files/7224350/findings.csv)
This PR uses the implementation to select findings that was introduced with the quick reports. This implementation didn't respect the filters and reported too many findings. This has been fixed with one exception: Filtering for tags and finding_groups is not trivial and is not yet implemented.
=> Export findings to CSV and Excel

tests/finding_test.py
The integration test for #5148 after it was merged into dev. Problem seems to be the waiting time to download the exported files, which was 4 seconds. This PR makes the test wait for a maximum of 10 seconds, but checks every second to not delay the following tests more than necessary.
=> Make integration test for exports more resilient

.github/ISSUE_TEMPLATE/bug_report.md, .github/workflows/gh-pages.yml
There were some commits against `master`, just making sure `dev` is in sync so we don't get conflicts on release day.
=> merge master into dev

.github/workflows/integration-tests.yml, docker/entrypoint-integration-tests.sh, dojo/finding/views.py, dojo/templates/dojo/add_findings.html, dojo/templates/dojo/findings_list_snippet.html, dojo/templates/dojo/templates.html, dojo/templates/dojo/view_test.html, tests/base_test_class.py, tests/finding_test.py, tests/product_test.py, tests/test_test.py
We have seen some regression on features that weren't covered by integration tests, or integration tests that were disabled at some point because they were broken or unfinished. This PR add / fixes some of those:
- #4586 (test merging of findings)
- #3908 (test create from template)
- #5154 (test list open / closed / accepted findings)
- #2563 (test add note to finding)
- fix and enable `test_add_note` testcase
- fix and enable `test_delete_test` testcase
- add simple risk accept/unaccept tests to allow #5154 to be fixed
=> fix/add missing/disabled integration tests

docs/content/en/getting_started/installation.md
Cleaned up and corrected https://github.com/DefectDojo/django-DefectDojo/pull/5158 to now point to dev in order to fix https://defectdojo.github.io/django-DefectDojo/getting_started/installation/
=> Fix links in installation.md to point to existing files in dev

tests/base_test_class.py, tests/finding_test.py
This integration test fails from time to time on GitHub. With this PR:
- The file will be written into the `media` folder, which is mapped as a volume by Docker Compose
- The waiting time is increased to 30 seconds. If the file exists before that, the test continues immediately, otherwise the integration tests have failed and will be stopped anyway.
=> Fix integration test for export of findings

tests/finding_test.py
Export tests are not stable and therefore disabled
=> Disable integration tests for export of findings

docs/content/en/integrations/import.md, dojo/db_migrations/0123_scan_type.py, dojo/importers/importer/importer.py, dojo/importers/reimporter/reimporter.py, dojo/importers/utils.py, dojo/models.py, dojo/settings/settings.dist.py, dojo/test/views.py, dojo/tools/parser_test.py, dojo/tools/sarif/parser.py, dojo/unittests/scans/sarif/appendix_k1_double.sarif, dojo/unittests/scans/sarif/spotbugs.sarif, dojo/unittests/test_importers_importer.py, dojo/unittests/tools/test_sarif_parser.py
Add feature to customize `Test` from parser data.
This will allow some parsers to handle meta-format like SARIF.
Fixes #3797
1. Test: added a `scan_type` attribute to save the scan_type used during import as string
2. Importer/Reimporter: add a new method `get_tests()` for parsers that are able to build findings **and** tests
3. The importer now take into account the data of the parsers to create the Test.
The core of the modifications are in `dojo/importers/importer/importer.py`.
I implemented like this:
```
*if the parser support creating Test* =>
1. we parse the findings and tests
2. we create the test with these data (with a customized type and name)
* else *
<old behavior>
```
Once this PR is merged I plan to add more attributes like description and more parsers that support this new …
=> Custom Test_Type for parsers (modify "Found by" dynamicaly)

.gitmodules
The https version can be used without registering an SSH key with GitHub.
I stumbled upon this while checking out the django-DefectDojo repository using ansible builtin git. It automatically tries to download the registered submodules. But because of the missing SSH key, the clone fails.
My reasoning for this proposed change:
- docsy is a public repo, using https should just work
- there's no real reason to use SSH, if you want to contribute to google/docsy.git you can still setup an environment with SSH
- if you don't have an SSH key registered with GitHub or you are in an environment where you don't have the key, using the submodule will fail
=> Use https as submodule url of google/docsy.git

dojo/importers/importer/importer.py, dojo/tools/gitlab_sast/parser.py, dojo/unittests/test_importers_importer.py, dojo/unittests/tools/test_gitlab_sast_parser.py
GitLab SAST is a kind of a meta format, similar to SARIF. GitLab SAST uses other Open Source tools to scan the code and reports the results in its own json format. This PR uses the mechanism introduced with #5121 to make the name of the real scanner available as the test type.
While doing this I discovered two possible NullPointerExceptions in the importer:
- Theoratically there could be no test given back by the parser
- There can be no name for the new test type. This can happen with GitLab SAST because the information about the real scanner is optional. In this case the original name of the Test_Type will be used, like **Sarif** or **GitLab SAST Report**
=> Use additional test types for GitLab SAST

dojo/settings/settings.dist.py, requirements.txt
In line with the OWASP Password Storage Cheat Sheet, we switch to `Argon2` as the default password hashing algorithm.
This is a Django setting. Existing password hashes will be rehashed when the user logs in. Password hashes for inactive users will not be rehashed as we don't know the password. We could wrap these hashes inside a Argon2 password hasher, but would require a custom wrapper for each possible password hashing algorithm. Also the example provided by Django on how to do this seems to be incomplete: https://docs.djangoproject.com/en/3.2/topics/auth/passwords/#password-upgrading-without-requiring-a-login (shouldn't the `verify` method be updated as well to cope with the wrapping?).
If admins want their users to reset their password, they will have to inform them an request them …
=> Set Argon2 as default password hasher

dojo/templates/dojo/view_finding.html
For some scans the view finding page can currently look like this:
This finding of Dockle for example has no file or component and is not connected to Jira or GitHub. The second table shows there is 1 occurence of this finding in the scan and the finding is not in a group. Both information are not really important. With this PR the second table is only shown when any of the fields has a content, including nb_occurences is greater than 1.
This makes the user more focused on the important information of the finding.
=> Optimize view finding

dojo/templates/dojo/findings_list_snippet.html, dojo/templates/dojo/snippets/selectpicker_in_dropdown.html, dojo/templates/dojo/view_test.html
After #4766, all select fields were dynamically converted to select picker fields. It did not work so well for those that were contained within a drop down. 
Before:
https://user-images.githubusercontent.com/46459665/135797454-84f9fcdc-3046-4e63-8cc0-1b095b790490.mov
After:
https://user-images.githubusercontent.com/46459665/135798169-3f636d72-c21b-4f0a-9fa3-b91e4abf0dae.mov
=> Fix BulkEdit severity dropdown after #4766

dojo/templates/dojo/action_history.html, dojo/templatetags/display_tags.py
fixes #5334 
The question is, if we really want to implement line breaks here.
It is possible with changing line 315 in dojo/templatetags/display_tags.py to:
`history[k][0] + '" to "' + history[k][1] + '". \n'`
and changing line 34 in dojo/templates/action_history.html to:
`<div style="white-space:pre;">{{ h.changes|action_log_entry }}</div>`
The thing is that linebreaks within a change are then also considered. (e.g. changing the description) Furthermore, a horizontal scroll bar could then appear if a linebreak was missing within a continuous text. (see attached screenshot)
However, I added a little improvement here.
.
=> improve history page layout

dojo/fixtures/dojo_testdata.json, dojo/settings/settings.dist.py, dojo/unittests/test_deduplication_logic.py, tests/dedupe_scans/dedupe_cross_1.csv, tests/dedupe_scans/dedupe_endpoint_1.xml
fixes #5312
Re-imports swallow findings, when deduplication is not set in the System Settings (default) and there is no `DEDUPLICATION_ALGORITHM_PER_PARSER` setting for the parser. This PR sets `DEDUPLICATION_ALGORITHM_PER_PARSER` to `DEDUPE_ALGO_HASH_CODE` for Semgrep and the generic import.
=> Deduplication settings for Semgrep and Generic Findings Import

dojo/endpoint/views.py, dojo/filters.py, dojo/finding/urls.py, dojo/models.py, dojo/static/dojo/css/dojo.css, dojo/templates/base.html, dojo/templates/dojo/add_endpoint_meta_data.html, dojo/templates/dojo/add_product_meta_data.html, dojo/templates/dojo/edit_endpoint_meta_data.html, dojo/templates/dojo/edit_product_meta_data.html, dojo/templates/dojo/endpoints.html, dojo/templates/dojo/view_endpoint.html
Until now the endpoint status hasn't been used to determine if an endpoint is vulnerable. With this PR an endpoint is marked as vulnerable, when it has active / verified findings and their endpoint status is not mitigated. Additionally this PR contains some tlc for the endpoint dialogues and a bugfix for editing metadata.
=> Use endpoint status to determine vulnerable endpoints

dojo/endpoint/utils.py, dojo/endpoint/views.py, dojo/engagement/views.py, dojo/finding/helper.py, dojo/finding/views.py, dojo/forms.py, dojo/product/views.py, dojo/templates/dojo/ad_hoc_findings.html, dojo/templates/dojo/add_findings.html, dojo/templates/dojo/apply_finding_template.html, dojo/templates/dojo/edit_finding.html, dojo/templates/dojo/import_scan_results.html, dojo/templates/dojo/promote_to_finding.html, dojo/test/views.py, tests/product_test.py, tests/test_test.py
fixes  #5278, #5279 and #5291
This PR changes the behaviour of the multiselectbox "Systems / Endpoints" in various dialogues for findings and imports:
- The multiselectbox behaves now as all other multiselectboxes in DefectDojo, showing the available endpoints and let the user select some of them.
- The popup to add new endpoints has been removed. The UI experience was not good, users couldn't see in the dialogue what they have been added after closing the popup. Instead there is now a textbox where the user can enter new endpoints line by line.
=> Enhanced endpoint selection and creation

dojo/templates/dojo/dashboard.html
On the dashboard there's the number of findings created in the last 7 days. When clicking on the number the user is presented a list of findings ordered by `numerical severity, -date, title`.
I think it's make more sense to order just by `-date` in this case.
=> order findings last 7 days by -date

dojo/db_migrations/0131_migrate_sonarcube_cobalt.py
fixes
```
Applying dojo.0131_migrate_sonarcube_cobalt...Traceback (most recent call last):
File "./manage.py", line 11, in <module>
execute_from_command_line(sys.argv)
File "/home/valentijn/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
utility.execute()
File "/home/valentijn/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
self.fetch_command(subcommand).run_from_argv(self.argv)
File "/home/valentijn/venv/lib/python3.8/site-packages/django/core/management/base.py", line 330, in run_from_argv
self.execute(*args, **cmd_options)
File "/home/valentijn/venv/lib/python3.8/site-packages/django/core/management/base.py", line 371, in execute
output = self.handle(*args, **options)
File …
```
=> filter out products without configs

dojo/pipeline.py
see https://owasp.slack.com/archives/C2P5BA8MN/p1635770164087400
The GitLab pipeline to update product access fails if there is a product with the name of a GitLab project exists but is in the wrong product type.
I cannot test it so it needs a very thorough code review.
=> Fix problem with duplicate projects in GitLab pipeline

.github/workflows/flake8.yml, .github/workflows/gh-pages.yml, .github/workflows/integration-tests.yml, .github/workflows/k8s-testing.yml, .github/workflows/new-release-chart.yml, .github/workflows/plantuml.yml, .github/workflows/test-helm-chart.yml, .github/workflows/unit-tests.yml
=> GHA workflows: don't persist git credentials

docker/entrypoint-integration-tests.sh, tests/base_test_class.py, tests/user_test.py
Two tests were reliably failing when re-running integration tests on the same database following an unsuccessful previous run. This is mitigated by simply destroying and re-initalizing the database, but that didn't appear to be the intention in documentation or code.
1. tests.test_user.test_create_user was failing if the user already existed as the "A user with that username already exists." text was not within a 'success' type field.
2. tests.test_user.test_user_notifications_change was failing if the test had already run as the checkboxes were already selected, when clicked again they were un-selected and the test only validated they were 'checked'.
3. ~docker/entrypoint-integration-tests.sh attempts to run tests/user_standard_test.py which does not exist. This run also sets the value …
=> Integration test idempotency

docker-compose.override.integration_tests.yml, docker-compose.override.unit_tests.yml, docker-compose.override.unit_tests_cicd.yml
Using build in sqlite database for unit tests instead of a separate rabbitmq.
=> main(tests): remove rabbitmq from unit-tests

helm/defectdojo/templates/django-deployment.yaml
Fix #5414 
The entrypoint has been changed between version 0.8.0 and 0.9.0 of the nginx-prometheus-exporter
=> Update the nginx-prometheus-exporter entrypoint

components/package.json
We have a yarn package, so it should contain our license.
=> add defectdojo license to yarn package.json

docs/content/en/usage/permissions.md, dojo/api_v2/permissions.py, dojo/authorization/authorization.py, dojo/authorization/authorization_decorators.py, dojo/authorization/roles_permissions.py, dojo/endpoint/queries.py, dojo/engagement/queries.py, dojo/finding/queries.py, dojo/finding_group/queries.py, dojo/fixtures/dojo_testdata.json, dojo/jira_link/views.py, dojo/models.py, dojo/product/queries.py, dojo/product_type/queries.py, dojo/product_type/views.py, dojo/templates/base.html, dojo/templates/dojo/product_type.html, dojo/templates/dojo/view_product_type.html, dojo/templatetags/authorization_tags.py, dojo/test/queries.py, dojo/unittests/authorization/test_authorization.py, dojo/unittests/test_rest_framework.py
We use a Product Types each external client that we build software for. Ideally some non-staff users can add new Product Types, or in our case the CICD process should be able to add new product types. Currently only staff users can add new product types. But I don't want to use a staff user for my CICD deployments or assign staff permissions to architect or project managers. I think Global Owners and Global Maintainers can basically edit all the findings / engagements / products, so I suggest to also let them add new Product Types.
This PR also extracts some repeated code into a central method. The specialty about this `Permission.Product_Type_Add` is that there is no object id to check the permissions against. Luckily @StefanFl agreed the PR was a good idea, let's hope my implementation …
=> Authz: Allow global maintainers/owner to add Product Types

docs/content/en/integrations/social-authentication.md, dojo/context_processors.py, dojo/settings/settings.dist.py, dojo/templates/dojo/login.html
Many companies have their own names for the SAML Service. Non technical user may don't know what SAML is. Now you can choose a custom name for the login button.
=> feat(saml): configurable login button text

docs/content/en/integrations/social-authentication.md, dojo/templates/dojo/login.html, dojo/user/views.py
When `SHOW_LOGIN_FORM` is `False`, `SOCIAL_LOGIN_AUTO_REDIRECT` is `True` and there is only one "Social" or "SAML", the login page is skipped and the request is automatically redirected to IdP. However, sometimes it is useful to have available the standard method as last resort (e.g. `admin` user need to log in because of a change of some settings or permissions).
This PR allows forcing login page with form when `<DD_HOST>/login?force_login_form` is accessed.
=> Allow to force login form

Dockerfile.integration-tests
as part of #5424 I noticed the integration tests are running hardcode as user `1001`. I am not saying this PR is the solution to all problems, but still helpful I think to make the userid a build argument so people can locally select the right user id in order to be able to access the filesystem correctly for example to write logs or screenshots during the integration tests.
=> add build arg for userid integration tests

.github/workflows/unit-tests.yml
I noticed that unit test runs for recent PRs in GHA seem to build the `nginx` image from scratch, even though it's declared as `busybox` in the docker compose override. I don't understand why, but the easier fix is to just not start `nginx` (nor `celerybeat`, `celeryworker`, `initializer`, `rabbitmq`) during unit tests. Those are not needed.
=> optimize GHA unit test

helm/defectdojo/Chart.yaml, helm/defectdojo/templates/celery-beat-deployment.yaml
This PR  mounts EmptyDir  into `/run/defectdojo` for CeleryBeat pod.
`    Mounts:
/run/defectdojo from run (rw)
`
**Why it is important**: When using tools as Kaniko to build image using k8s, build will fail because kaniko can't break symlink for Read Only path (because k8s mounts secret inside of /run/[secrets]...that is symlink to /var/run/[secrets]) during the snapshot.
`
error building image: error building stage: failed to get filesystem from image: error removing var/run to make way for new symlink: unlinkat /var/run/secrets/kubernetes.io/serviceaccount/..data: read-only file system
`
For that reason extra flag in kaniko should be in use to ignore snapshotting  of `/var`. But than snapshot doesn't include `/var/run/defectdojo`, and docker image at the end as resoult.
While in the …
=> Add EmptyDir for CeleryBeat into /run

dojo/templates/dojo/view_user.html, dojo/user/views.py, tests/user_test.py
#5499
Adding a user behaves differently from other dialogues. When you add all other objects, you get redirected to the page to view the object. But when you add an user, you stay on that page and can edit the user. This gets changed with this PR and the user is redirected to the view user page, so they can add the user to a group, product or product type there.
=> Go to user view after user add

dojo/notifications/urls.py
some non-unique names where used for urls. Only the first one of these 3 was used, so I renamed the bottom 2.
as raised in #5513
=> fix duplicate notification urls

dojo/db_migrations/0066_django_tagulous.py
`Product_Type` was not defined as raised in #5513
=> Fix missing import/model in 0066_django_tagulous.py

helm/defectdojo/templates/initializer-job.yaml, helm/defectdojo/values.yaml
There is `initializer.run: true` in default **values.yaml**, but it isn't used anywhere.
I'd like to add the opportunity to disable the initializer job.
Also, it would be great to make it possible to add annotations to the initializer job.
UPD: annotations support for init job was added :)
=> fix(helm): allow disabling initializer job

dojo/api_v2/views.py, unittests/test_rest_framework.py
fixes #5502
The API to upload files to engagements, tests and findings is actually working, but the implementation made it hard to figure out how and generated a not very useful swagger description. With the new implementation the swagger description is consistent with other file uploads. There are 2 changes to the API:
- The return code for a successful ``post`` has been changed to 201 (https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/201)
- The ``patch`` method didn't work at all and has been deleted.
=> Fix files API

.github/workflows/integration-tests.yml
Currently the integration test build uses an action to cache docker layers: https://www.docker.com/blog/docker-github-actions/
This works fine, but is slower than the newer GHA cache backend type supported by buildkit: https://github.com/moby/buildkit#github-actions-cache-experimental
=> use GHA caching for integration tests

dojo/templates/dojo/dashboard-metrics.html, dojo/templates/dojo/dashboard.html, dojo/templates/dojo/metrics.html, dojo/templates/dojo/product_endpoint_pdf_report.html, dojo/templates/dojo/product_metrics.html, dojo/templates/dojo/view_endpoint.html, dojo/templates/dojo/view_engineer.html, dojo/templates/dojo/view_product_details.html
Add some blocks around the metrics page to organize them and easily swap the file out for custom colors
Here are some docs on template inheritance: https://docs.djangoproject.com/en/3.2/ref/templates/language/#template-inheritance
=> Add organizational blocks around metrics.js files

dojo/authorization/authorization.py
#5410 gave non-staff users the permission to add product types when they have a global role. But it removed the permission to add product types for staff users regardless if they have a global role, which was not intended.
=> Fix staff permission to add product types

README.md, docs/content/en/integrations/import.md
=> Typo in README and a missing parser in the documentation

dojo/settings/settings.dist.py
fixes #5538
see https://docs.djangoproject.com/en/3.2/releases/3.2/#customizing-type-of-auto-created-primary-keys and https://docs.djangoproject.com/en/3.2/topics/db/models/#automatic-primary-key-fields
=> Set default_auto_field after migration to Django 3.2

docs/content/en/getting_started/upgrading.md
Documented the steps to update an installation of DefectDojo that was done by godojo and added a link in the DefectDojo docs for those interested.
=> Added info on upgrading godojo installs of DefectDojo to the docs

dojo/db_migrations/0118_remove_finding_images.py
When an instance has a finding with multiple images with the same caption, the migration would only migrate 1 image.
The earlier fix in #5319 shows this can occur, for example when someone uploads all there images with caption  `screenshot`.
This PR retries an image by appending the caption with a `uuid` which should usually ensure all images are migrated.
```
initializer_1   |   Applying dojo.0118_remove_finding_images...[04/Dec/2021 12:28:16] INFO [dojo.db_migrations.0118_remove_finding_images:27] retrying migrate migration for image finding_images/8c69cdcd-9b4a-463d-9835-3f6e9db62508.jpg with caption valentijn by uuid
initializer_1   | [04/Dec/2021 12:28:16] INFO [dojo.db_migrations.0118_remove_finding_images:27] retrying migrate migration for image …
```
=> fix image migration for duplicate captions

nginx/nginx.conf, nginx/nginx_TLS.conf
This is a best practice change for nginx config. There is no misconfiguration at the moment.
There are two reasons for making these changes:
1. It is recommended by the official docs.
2. Prevents path traversal bugs that might happen due to future changes in configs:
```
// not vulnerable to path traversal (current)
location /static {
alias /usr/share/nginx/html/static;
// vulnerable to path traversal (example)
location /static {
alias /usr/share/nginx/html/static/;
```
Docs & References:
https://nginx.org/en/docs/http/ngx_http_core_module.html#alias
https://github.com/yandex/gixy/blob/master/docs/en/plugins/aliastraversal.md
https://blog.detectify.com/2020/11/10/common-nginx-misconfigurations/
=> Fix alias paths in nginx config

helm/defectdojo/templates/configmap.yaml
This PR allows setting custom settings for celery worker.
Values didn't work because there were hardcoded values in configMap template.
=> feat(helm-chart): celery worker app_settings

dojo/static/dojo/js/metrics.js
Previously, some of the plots on the Detailed Metrics page displayed dates with the most recent date on the far left side of the x-axis.
With this change, these plots will display the most recent dates on the far right side of the x-axis.
=> Reversed x-axis on Product's Detailed Metrics Page

dojo/settings/settings.dist.py, dojo/tools/solar_appscreener/parser.py, unittests/tools/test_solar_appscreener_parser.py
Solar Appscreener parcer:
Correct settings to apply hashcode as deduplication algoritm
Add line field to finding in parcer
=> Solar change deduplication model

requirements.txt
their bug is fixed in this release so we no longer need to install that specific hotfix commit
=> update tagulous to 1.3.1 instead of hotfix commit

requirements.txt
dependabot missed release 3.2.10 of Django, maybe because we declined 4.0
This Django version fixes a vulnerability.
=> Update to Django 3.2.10

dojo/engagement/views.py, dojo/test/views.py, dojo/tools/azure_security_center_recommendations/parser.py, dojo/tools/cobalt_api/parser.py, dojo/tools/factory.py, dojo/tools/sonarqube_api/parser.py
The pages to import and re-import show a list of available scan types. Currently it shows the name of the scan type 2 times next to each other:
With this PR the list shows the name of the scan type with its description, which I think would have been the initial idea of that list:
Additionally 3 descriptions have changed because they where wrong or outdated and a method has been removed that was not used anymore.
=> Show descriptions for scan types on pages for import and re-import

dojo/tools/anchore_grype/parser.py, unittests/scans/anchore_grype/check_all_fields.json, unittests/tools/test_anchore_grype_parser.py
This PR is basically a rewrite of the Anchore Grype parser:
- The reports contain a lot of information that was not stored in the findings so far. Now the findings are much richer than before.
- Internal deduplication was based on CVE only. When you have several components with the same CVE, they had been stored in one finding under one component name. Now the internal deduplication is done by the title, which contains CVE, component name and component version.
=> Revamp of the Anchore Grype parser

docs/content/en/usage/permissions.md, dojo/authorization/roles_permissions.py, dojo/finding/views.py, dojo/notes/urls.py, dojo/notes/views.py
solves #5581
There is no harm in letting users with a `Reader` role adding notes. Includes a missing permission check, which doesn't change a lot because a user need a `Reader` role anyway to call this view method. Nevertheless it shall be there for completeness.
=> Give readers the permission to add notes

dojo/db_migrations/0142_environment_delete.py
The rename of a db migration was missed with the last round of merges, causing a conflict when running the initializer.
=> Fix database migration for deletion of development environments

helm/defectdojo/templates/celery-beat-deployment.yaml, helm/defectdojo/templates/celery-worker-deployment.yaml, helm/defectdojo/templates/django-deployment.yaml, helm/defectdojo/values.yaml
hi guys!
I've discovered the issue, that secret name for message broker is hardcoded in the helm chart when redis is used. I've added the logic to fix it.
I fixed the a typo in the values.yaml:  name for the django debug value, and added name of the key in the rabbimq secret.
This is a duplicate of https://github.com/DefectDojo/django-DefectDojo/pull/5533 but with merged recent changes from dev branch.
=> add logic if external redis is used

dojo/notifications/helper.py
=> Slack notification: get user by email instead of searching all users

dojo/api_v2/serializers.py, dojo/forms.py, dojo/importers/importer/importer.py, unittests/dojo_test_case.py, unittests/test_import_reimport.py
implements #5618
When a `service` is specified and **Close old findings** is set as well while importing a scan, only the old findings of the same service shall be closed.
=> Close old findings of same service only

dojo/importers/utils.py
Extended behavior from #5547 to apply to endpoint status objects as well as findings
=> Extend scan_date functionality to Endpoints created at import time

Dockerfile.django
Recent change (Pull Request #5284) changed /app to be owned by root.  This broke the ability for docker-compose installs to bind mount a local_settings.py into the container.
To address this, I've added a defectdojo user and group with a UID and GID of 1337.  This allows /apps/dojo/settings to be writable by the defectdojo group so local_settings.py can be copied in by the entrypoint script.
I also moved the UID from 1001 to 1337 so that it has a much reduced chance of colliding with a OS user if you want to chown the host files that are bind mounted as a host OS user with a UID that matches the UID in the container.  1337 would require 337 local users vs 1 local user for 1001.
=> Updated django dockerfile to work with bind mounts for local_settings.py

Dockerfile.django, Dockerfile.integration-tests, Dockerfile.nginx, docker-compose.override.integration_tests.yml
Mostly doing 2 things:
(1) Making all the dockerfile match in terms of UID/GID for the defectdojo user & group
(2) Cleaned up the formatting of the dockerfiles to make them more readable & added comments
Additionally, I move the entrypoint script in the integration container to / to be consistent will all other entrypoint scripts.
=> Updated all dockerfiles to match the django dockerfile so UID/GIDs are consistent across dockerfiles

dojo/api_v2/views.py
Every user could read Test Types and Development Environments before release 2.6.0. Now it has accidentally been changed to staff users. As there is no sensitive data in these 2 classes and the read access is often helpful in CI/CD scenarios, the old behaviour is reinstated.
=> Revert permission changes for `test_type` and `development_environment`

Dockerfile.django
Copying of files in `docker/extra_settings` as described in https://defectdojo.github.io/django-DefectDojo/getting_started/configuration/#local_settingspy-not-with-kubernetes isn't working anymore with release 2.6.0.
=> Reinstate copying of extra_settings

dojo/api_v2/views.py, dojo/endpoint/views.py, dojo/engagement/views.py, dojo/finding/views.py, dojo/forms.py, dojo/notifications/helper.py, dojo/reports/views.py, dojo/survey/views.py, dojo/templates/dojo/add_user.html, dojo/templates/dojo/endpoints.html, dojo/templates/dojo/findings_list_snippet.html, dojo/templates/dojo/view_test.html, dojo/utils.py
This PR removes some checks of the `is_staff` flag, where the functionality can either be used by all users or gets restricted to superusers:
- Staff users where allowed to delete any notes with the API. This has been restricted to superusers.
- Bulk edits and deletes for Endpoints, Tests and Findings where restricted to staff users. Since the bulk operations respect the permissions of the user for each object, it is save to make it available to all users.
- There was an unnecessary check that only staff users can import Findings without providing an Engagement or Product. This would not work anyway, so an exception is raised in this case.
- Only staff users could be selected as the lead for an Engagement. This has been changed to all users, but only active users can be selected.
- System …
=> Removal of `is_staff` for various functionalities

docs/content/en/getting_started/upgrading.md, docs/content/en/usage/permissions.md, dojo/api_v2/permissions.py, dojo/authorization/authorization.py, dojo/endpoint/queries.py, dojo/engagement/queries.py, dojo/finding/queries.py, dojo/finding_group/queries.py, dojo/group/queries.py, dojo/jira_link/queries.py, dojo/management/commands/migrate_staff_users.py, dojo/product/queries.py, dojo/product_type/queries.py, dojo/test/queries.py, dojo/tool_product/queries.py, unittests/authorization/test_authorization.py, unittests/authorization/test_authorization_decorators.py
The functionality using the flag `AUTHORIZATION_STAFF_OVERRIDE` has been removed. The same result can be achieved with giving the staff users a global Owner role. To make that easier administrators can run a migration script with `./manage.py migrate staff_users`. This script creates a group for all staff users and sets the global Owner role, if `AUTHORIZATION_STAFF_OVERRIDE` is set to True.
The migration script already prepares the configuration permissions for staff users as well.
=> Removal of `AUTHORIZATION_STAFF_OVERRIDE`

docs/content/en/integrations/jira.md
Fixes to documentation snags I ran into while scoping or performing the Jira integration against a Jira Server instance
Done on DD v2.4.1 (in case docs are actually correct in the latest release and I should just upgrade)
=> Update Jira Integration docs for Jira Server

dojo/models.py
The SLA days remaining are currently calculated using the Finding's date, even if the field `sla_start_date` is set. It's curious, because the message that appears when you move the mouse over the SLA number is well calculated using the `sla_start_date`. But the number of the SLA days was being calculated differently. It seems like a bug that would be fixed with this PR.
With this change, the SLA will be calculated using the date from sla_start_date when it's available.
=> Bugfix SLA days remaining

dojo/settings/settings.dist.py, dojo/tools/jfrogxray/parser.py, unittests/tools/test_jfrogxray_parser.py
fixes #5770
Reimports for JFrox Xray Scan where not working properly, because there where no deduplication settings. While I had a look at the parser, I streamlined the output of the parser and added some more checks to the unit tests. 
Now the CVSS3 score is calculated properly, what didn't work before as well.
=> Maintenance of JFrog Xray parser

dojo/tools/snyk/parser.py, unittests/scans/snyk/single_project_one_vuln_with_ampersands.json, unittests/tools/test_snyk_parser.py
The Snyk parser uses the `file_path` field to show dependency paths. Many package names include ampersands in them, which are not being preserved due to truncation when trimming out version numbers. This PR preserves the packages names in the `file_path` field.
=> Bugfix: For Snyk parser, preserve file paths with @ in package name 

dojo/product_type/views.py, dojo/templates/dojo/view_product_type.html
fixes #5778
When a Product Type has many Products, it can lead to long loading times in the details view, because the list of products wasn't paginated. This gets fixed with this PR.
=> Paginated Product list in Product Type details

docker/entrypoint-celery-beat.sh, docker/entrypoint-celery-worker.sh, docker/entrypoint-initializer.sh, docker/entrypoint-uwsgi.sh
I have found that only a single settings file is acceptable for copying a settings file from the host machine in `docker/extra_settings` to the container.
This PR allows for multiple files to be copied over at once via bound mounts
=> Add support for including multiple setting files via extra_settings

dojo/static/dojo/css/dojo.css, dojo/templates/dojo/snippets/engagement_list.html, dojo/templates/dojo/view_endpoint.html, dojo/templates/dojo/view_eng.html, dojo/templates/dojo/view_product_type.html, dojo/templates/dojo/view_test.html
In some views there are separate panels, where some of them have borders and others, with lists and paginations, don't have borders or partially have borders. One example is the list of Findings in the Test views:
With this PR the user interface looks more consistent, having borders around every block, when there are multiple blocks on one page. This is the list of Findings in a Test with the PR:
These dialogues have been touched (all in the Product view):
- Engagement list (lists of active / paused / closed Engagements)
- Engagement details (list of Tests)
- Test details (list of Findings)
- Endpoint / Host details (list of Findings)
=> Facelift: borders for panels with lists

dojo/models.py
When there is the same URL more than one time in the references of a finding, the rendering of the references produced weird results. That's becauce the first URL in the references got replaced multiple times. With this PR only one occurrence of a URL gets rendered with a proper HTML link, all others stay untouched.
Someone could imagine a more sophisticated solution, but it's a rare case and there is at least one link for each URL to click on.
=> Rendering of references is corrupted when the same URL occurs more than one time

helm/defectdojo/templates/django-ingress.yaml, helm/defectdojo/values.yaml
Hello,
this PR will introduce the ingressClassName to the ingress template.
Docs on this: https://kubernetes.io/docs/concepts/services-networking/ingress/
I added a semverCompare since it is available beginning k8s 1.18 and only on v1 of ingress resource and we also make this check for deciding what apiGroup to use.
if `.Values.django.ingress.ingressClassName` is either non-existent or empty, the key will not appear in ingress resource
=> feat(helm): add ingressClassName value to ingress resource

dojo/api_v2/views.py
After enabling `"include_executive_summary": true` in Api_V2 (`product_types` -> `/product_types/{id}/generate_report/`) we started getting 500 errors by api requests. 
In logs:
```
uwsgi_1 | File "./dojo/api_v2/views.py", line 1618, in report_generate
uwsgi_1 | if test.environment:
uwsgi_1 | AttributeError: 'NoneType' object has no attribute 'environment'
```
Rename test var to t solved the problem.
=> Wrong var in include_executive_summary block for product_type

dojo/models.py, dojo/tools/wpscan/parser.py, unittests/scans/wpscan/issue5774.json, unittests/tools/test_wpscan_parser.py
=> WPScan - implement confidence

dojo/user/views.py
Actual keycloak implementation in DD doesn't support ["Login speed-up"](https://defectdojo.github.io/django-DefectDojo/integrations/social-authentication/#login-speed-up). So even if the admin of DD set  `SOCIAL_LOGIN_AUTO_REDIRECT: True` and `SHOW_LOGIN_FORM: False`, the user of DD will not be redirected automatically to IDP.
This PR solve this issue.
Note: Implementation of https://github.com/DefectDojo/django-DefectDojo/pull/5726#issuecomment-1023323371
=> Oauth: enable keycloak to use auto redirect

dojo/templates/dojo/view_test.html
The button to submit a bulk edit in the detailled test view wasn't visible.
**Before:**
**After:**
=> Change colour of submit button for bulk edit in Test view

dojo/decorators.py, dojo/finding/helper.py, dojo/importers/importer/importer.py, dojo/importers/reimporter/reimporter.py, dojo/importers/utils.py, dojo/jira_link/helper.py, dojo/management/commands/test_celery_decorator.py, dojo/tools/tool_issue_updater.py, dojo/utils.py
Add `user` kwarg to finding group assignment helper method to all for the `group_by` flag to work during async imports. The requirement for a kwarg is because the `get_current_user()` crum function does not return anything when the context is async
=> Async Import: Fix group_by flag

dojo/api_v2/serializers.py, dojo/forms.py, unittests/test_import_reimport.py, unittests/tools/test_nuclei_parser.py
Some security tools generate reports as empty file.
For example, Nuclei report format is JSON lines. So an empty report is a possible.
This modification let's the API v2 accept empty files.
=> Allow empty report files (in API v2 and UI)

dojo/pipeline.py, dojo/settings/settings.dist.py
Adding (DD)_SOCIAL_AUTH_CREATE_USER option to:
True, user will be created automatically
False, user will not be created automatically 
Please test it, I have test it on my local instance, but double check would be useful.
=> Option not to create user automatically using SOCIAL_AUTH

docker/entrypoint-celery-beat.sh, docker/entrypoint-celery-worker.sh, docker/entrypoint-initializer.sh, docker/entrypoint-uwsgi.sh
The new approach to copy files from `/app/docker/extra_settings` will fail in **kubernetes** when overwriting the folder through a volume mount. README.md will no longer be there and as such the number of files will be 1, instead of 2 as expected by the if conditions. I propose this be moved to enumerate and copy all *.py files found in the folder.
Additionally, this PR also deals with celery beat and worker, for which the local_settings.py file is being copied only after executing `python3 manage.py dbshell`, causing late-defined variables to not be counted on. In my use case this causes the DB password to not be passed
=> copy python files from extra_settings

dojo/settings/settings.dist.py
**django-auditlog** started to produce the warning `auditlog.LogEntry.additional_data: (django_jsonfield_backport.W001) You are using Django 3.1 or newer, which already has a built-in JSONField.` with its release 1.0.0. That happens because they are importing **django-jsonfield-backport** now. According to https://github.com/laymonage/django-jsonfield-backport/blob/master/README.rst:
> This package is fully compatible with the JSONField from Django 3.1. That means you just need to change your imports and edit your migrations when you finally upgrade to Django 3.1. If you leave them as they are, this package will use the built-in JSONField and system warnings will be raised.
That is why we can ignore the warning.
=> Ignore warning from django-auditlog

docker/entrypoint-celery-beat.sh, docker/entrypoint-celery-worker.sh, docker/entrypoint-initializer.sh, docker/entrypoint-uwsgi.sh
This is a follow-up to #5797 and #5839. Files will be copied from `docker/extra_settings` to `dojo\settings` if there a `*.py` files in the source directory. In that case currently all files are copied, including a `README.md`. This copied readme file appears then in the list of changed files to commit to git, which is unnecessary.
With this PR only `*.py` files are copied from `docker/extra_settings` to `dojo\settings`.
=> Copy only *.py files from extra_settings

docs/content/en/integrations/jira.md
Seems that some people were not aware that username is needed when authenticating with API Token
=> make JIRA authentication docs more explicit

dojo/models.py
When first importing a scan file that contained a NULL char to my sandbox env (running MySQL) I did not experience any issues. After attempting to import to production (running Postgres) I was greeted with the following 
This error is totally dependent on the DB connected to dojo, so a universal fix is sorta out the window. Ideally, removing information from an endpoint is not acceptable, but I figured there was no way to import a scan with a NULL char to a Postgres backend anyways, so might as well remove the offending bits of the URL. 
I added some validation errors to make the log reader aware of what is going on
`uwsgi_1         | [10/Feb/2022 23:29:53] WARNING [dojo.importers.utils:133] DefectDojo is storing broken endpoint because cleaning wasn't successful: ['Query …
=> Add Postgres NULL char validation/removal in Endpoint cleaning

dojo/api_v2/views.py
Allow searching `Users` by parameters `'is_active'` and `'is_superuser'`
=> APIv2: allow searching users by parameters 'is_active' and 'is_superuser'

dojo/templates/base.html
It's strange that in the absence of alerts, we suggest looking at all the alerts or clearing them. 
I suggest showing a big message instead
Before:
After:
=> Don't show 'all alerts' and 'clear all alerts' when no notification found

dojo/forms.py, dojo/user/queries.py, tests/product_test.py, tests/test_test.py
When usernames are anonymized  it is very hard to find the right user for peer review. So it is adapted to use `generate_full_name()`
Before:
After:
=> Format of reviewer form 

dojo/templates/dojo/custom_html_report.html, dojo/templates/report_base.html
fixes  #5917
This PR removes `{{ host }}` from the links for `bootstrap.min.js` in 2 templates and make them similar to all other links for JavaScript files.
=> Remove host from links for custom reports

docs/content/en/getting_started/upgrading.md, helm/defectdojo/templates/secret-redis.yaml, helm/defectdojo/values.yaml
In on of the last updates, bitnami has change the name of some keys. We need to update them too.
[Bitnami Redis Chart](https://github.com/bitnami/charts/tree/master/bitnami/redis)
---
=> fix(helm): update redis keys

docker-compose.override.debug.yml
For some reason, the structure in `docker-compose.override.debug.yml` was indented more then in other `docker-compose.override.*.yml` files
=> Fix indentation in docker-compose.override.debug.yml

.github/ISSUE_TEMPLATE/support_request
As discussed on slack most GitHub issues created as bugs are really support requests. 
This PR allows creation of support requests, which get labeled as such so we don't have to keep relabeling bug reports to support requests :-)
Against `master` for immediate effect.
=> add support_request template

docs/content/en/getting_started/upgrading.md, dojo/api_v2/serializers.py, unittests/test_rest_framework.py
remove obsolete field
https://owasp.slack.com/archives/C2P5BA8MN/p1647430817715979
=> APIv2: remove configuration_url from ToolConfigurationSerializer

dojo/templates/dojo/view_eng.html
The "Add Finding from Template" shortcut is only available within the Test Form.
This commit add the shortcut within the Test menu in the Engagement Form
=> [ADD] Finding from Template Shortcut

dojo/test/views.py
When creating a Finding from a Template, the date given to the finding is not taken into account. Instead, date provided is erased by the date of the day.
This fix allows to create a Finding, from a Template, with a given date or date of the day.
=> [FIX] Date erased when Finding created from Template

docs/content/en/getting_started/upgrading.md
Currently there is a typo in the documentation while the migrate_staff_users is the script that needs to be executed, the underscore was missing in the current documentation.
=> [FIX] Typo fix on migrate_staff_users

dojo/finding/helper.py
When creating a new Finding in the past for an Endpoint (new or already existing one), the 'Date Discovered' of this Endpoint (for the corresponding Finding) is always set to the today's date as defaulted in models.py files.
This date should be fixed to the same value than the Finding's date, because the 'Date Discovered' is linked between the Endpoint and the Finding
=> [FIX] Wrong Endpoint 'Date Discovered'

helm/defectdojo/templates/django-deployment.yaml, nginx/nginx.conf, nginx/nginx_TLS.conf
If `SOCIAL_LOGIN_AUTO_REDIRECT=True`, `/login?next=/` is redirected to `SOCIAL_LOGIN` handler. If it fails (for example because IdP is down) also `SOCIAL_LOGIN` mechanism fails and the container is marked as not ready or not live. This needs to be avoided because the health of DD is independent of the health of IdPs. `force_login_form` will forbid redirection.
=> HELM: Fix probes when SOCIAL_LOGIN_AUTO_REDIRECT is True

dojo/settings/settings.dist.py
fixes #5891 
Swagger for OpenAPI3 now looks like this:
=> Show file selection dialogue in OpenAPI3 Swagger

dojo/templates/dojo/view_tool_product_all.html
fixes https://github.com/DefectDojo/django-DefectDojo/issues/6111
`'view_tool_product' not found when I added a tool or clicked on view tools on product dashboard settings.`
=> Fix view tool product error

docs/content/en/getting_started/upgrading.md, dojo/home/views.py
The deprecation notice for the legacy authorization for configurations will be shown:
* on top of the upgrading page in the documentation
* on top of the dashboard in the UI for superusers when the legacy authorization is still active
=> Deprecation notice for legacy authorization for configurations

dojo/static/dojo/css/dojo.css, dojo/templates/dojo/dashboard.html
Previously, the blue panel on Dojo Dashboard used the "secondary-color" CSS class, created "panel-blue" specific CSS class. Also added a few minor design fixes to add spacing between buttons on forms, as well as the search bar on forms (such as the "View Products" page).
=> Changed blue panel CSS, plus a few minor design fixes

dojo/endpoint/utils.py
I learned that windows attached something the byte order mark onto files that are generated on windows. The endpoint meta importer did not accept that file encoding.
=> Endpoint Meta Importer - Import UTF-8-BOM files

dojo/notifications/helper.py, dojo/tools/sonarqube_api/importer.py
In current implementation in case of Exceptions, e.g SonarQube availability, all users will receive information about it, even those who are not entitled for particular product. 
This PR just detects if product is not defined, and then sends notifications only to admins. 
And enhances sonarqubeAPI parser to distribute product as part of Exception (obj).
=> Improve notifications on Exceptions 

dojo/db_migrations/0150_dedupe_endpoint_status.py, dojo/endpoint/utils.py, dojo/management/commands/fix_broken_endpoint_status.py, unittests/test_endpoint_model.py, unittests/test_migrations.py
Original migration was failing in case the finding or the endpoint of endpoint_status was removed. Removal sets one of the values to null so it changes the related entry to broken (endpoint_status with an empty endpoint or finding doesn't make sense).
This PR:
- fix original migration - it skips broken endpoint_statuses
- unittests checking correctness of migrations
- add command `manage.py remove_broken_endpoint_statuses.py`
https://owasp.slack.com/archives/C2P5BA8MN/p1649278993631269?thread_ts=1649254658.509179&cid=C2P5BA8MN
=> Hotfix 0150 - skip broken endpoint_statuses + command for removal of broken endpoints

docker/entrypoint-uwsgi-dev.sh, docker/entrypoint-uwsgi.sh, dojo/finding/views.py, dojo/middleware.py, dojo/settings/settings.dist.py, dojo/utils.py, nginx/nginx.conf
It adds options to define customized way of uwsgi logging, that can be changed without need to rebuild the images. 
For instance user can specify Apache format by defining (in compose or helm value):
`DD_UWSGI_LOGFORMAT: '"%(addr) - %(user) [%(ltime)] "%(method) %(uri) %(proto)" %(status) %(size) "%(referer)" "%(uagent)"'`
To produce:
`"172.19.0.1 - - [18/Mar/2022:12:52:21 +0000] "GET /alerts/count HTTP/1.1" 200 183 "http://localhost:8080/system_settings" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.109 Safari/537.36 OPR/84.0.4316.31"`
The problem I still see that default is not populating (user) variable, I tried to do it manually in middleware with `set_logvar` but is not working as well (still empty). But it works fine if I define alternative …
=> Logging enhancement 

helm/defectdojo/values.yaml
Hi,
on all my defectdojo instances, the uwsgi DefectDojo container operates with ~250MB. Therefore, I recommend to set the request higher to not get into resource conflicts. 
Kind regards
Timo
=> Enlarge RAM Request

dojo/benchmark/views.py, dojo/cred/views.py, dojo/endpoint/views.py, dojo/engagement/views.py, dojo/finding/views.py, dojo/finding_group/views.py, dojo/google_sheet/views.py, dojo/object/views.py, dojo/product/views.py, dojo/reports/views.py, dojo/test/views.py, dojo/tool_product/views.py, dojo/utils.py, dojo/views.py
We have a lot of duplicated SQL statements at the moment. This PR removes some of them. The `Product_Tab` received the id of a product until now and read the product. But the majority of views has already read the product before. Now the product is given to the `Product_Tab` and removes one duplicate SQL statement.
=> Performance optimization: Don't read product in Product_Tab

README.md
After OWASP removed dedicated project funds, we stopped accepting sponsors, but kept the section to make sure no one was shorted on their contributions. In January we met all requirements for display and it now makes sense to remove to avoid any confusion.
=> Removes Sponsors Section

dojo/engagement/views.py, dojo/filters.py, dojo/forms.py, dojo/static/dojo/css/dojo.css, dojo/templates/dojo/action_history.html, dojo/templates/dojo/snippets/engagement_list.html, dojo/test/views.py, dojo/user/queries.py, dojo/views.py, unittests/test_user_queries.py
Until now some filters and the calendar view listed all DefectDojo users. This might not be desired, e.g. if an instance has external users that should not be visible for everyone.
With this PR a user can only see the users that are authorized for the same products and product types as themselve, including users with global roles and administrators.
=> Read only authorized users in filters and calendar

docs/content/en/usage/performance.md
The new documentation for asynchronous functions contained some typos that needed to be corrected.
=> Typos in documentation for asynchronous functions

dojo/filters.py
Some filters read all endpoints or findings. In installations with a lot of endpoints and findings, this can lead to performance problems. This filter attributes have been changed from lists to CharFilters with `icontains` lookups.
=> Performance optimization: Don't read all endpoints or findings in filters

dojo/tools/mozilla_observatory/parser.py, unittests/tools/test_mozilla_observatory_parser.py
Mozilla Observatory findings/tests can have a numeric rating of 0 (neutral finding) or even positive (defense in depth measures). However, the current implementation of the parser rates everything >= -10 as "Low". Neutral or positive Findings should be rated with "Info" instead.
=> Fixed INFO rating for neutral/positive Mozilla Observatory findings

docs/content/en/integrations/importing.md
fix a typo in the string `auto_create_context`
=> Typo in auto_create_context

dojo/settings/settings.dist.py
This fixes DrHeader deduplication. However, when you upload (no reupload) a new scan, the severity of existing findings is not  adapted yet. (See issue 6280).
=> fix drheader deduplication #6280

dojo/notifications/helper.py, dojo/templates/notifications/other.tpl
- Fix non working get_slack_user_id function
- Switch on system_settings.disclaimer length as the var cannot be null
=> Fix get slack id at 1st notification and disclaimer in slack notifications

helm/defectdojo/templates/celery-beat-deployment.yaml, helm/defectdojo/templates/celery-worker-deployment.yaml, helm/defectdojo/templates/django-deployment.yaml, helm/defectdojo/templates/initializer-job.yaml, helm/defectdojo/values.yaml
This adds an value to the helm chart's `values.yaml` file which can be used to inject extra environment variables into the containers. 
It's different from the existing `extraConfigs` value because this is injected into the container definition, not into the configmap. That matters because you can't dynamically pull values from one configmap into another configmap - so if your parameters are stored elsewhere we need this mechanism to add these values to the containers.
An example (very similar to what I'm currently using with this changeset) is in the docs in the values file (below). We have the built-in postgres container disabled but have another template creating our postgres cluster, which then stores its host name in a configmap, and this allows us to inject that host into the …
=> add extraEnv to helm chart

dojo/reports/views.py, tests/finding_test.py
The Excel export for findings wasn't working anymore after the introduction of the vulnerability ids. With this PR the Excel export works again and both CSV and Excel export contain the vulnerability ids now.
Additionally the integration tests are waiting 5 seconds now for the generation of the file.
=> Fix CSV and Excel export for findings

helm/defectdojo/templates/celery-beat-deployment.yaml, helm/defectdojo/templates/celery-worker-deployment.yaml, helm/defectdojo/templates/django-deployment.yaml
fix(helm): update redis keys [@alles-klar](https://github.com/alles-klar) ([#5886](https://github.com/DefectDojo/django-DefectDojo/pull/5886))
changed the values.yaml keys for redis auth, but did not change those keys in the deployments.
This PR shall fix this
=> fix(helm): redis auth variables changed path

dojo/api_v2/mixins.py, dojo/api_v2/serializers.py, dojo/api_v2/views.py, unittests/test_apiv2_methods.py, unittests/test_rest_framework.py
`GET apiv2/{model}/{id}/delete_preview`
https://owasp.slack.com/archives/C014H3ZV9U6/p1639241564073500
```json
{
"count": 123,
"next": "http://DD/api/v2/users/1/delete_preview/?offset=2&limit=4",
"previous": "http://DD/api/v2/users/1/delete_preview/?offset=10&limit=4",
"results": [
{
"model": "User",
"id": 1,
"name": "admin"
},
{
"model": "Product_Type_Member",
"id": 1,
"name": "Product_Type_Member object (1)"
},
{
"model": "Alerts",
"id": 4,
"name": "Alerts object (4)"
},
{
"model": "Alerts",
"id": 2,
"name": "Alerts object (2)"
}
]
}
```
=> APIv2: Add preview of elements that will be affected by DELETE

dojo/finding/views.py
Replaces user id with a full user name inside of the notification  message.
Previously 
```
User name surname (user) has requested that users 43 review the
```
Now
```
User name surname (user) has requested that user(s) user surname (user) review the...
```
=> Replace user id with full_name

docker/entrypoint-celery-beat.sh, docker/entrypoint-celery-worker.sh, docker/entrypoint-initializer.sh, docker/entrypoint-uwsgi.sh
On one of my dev servers, I am unable to use remote SAML metadata files and instead use XML files. This was restricted to just python files with #5884 as the motive was to remove the possibility of the `README.md` file. I think this approach gives the best of both worlds
=> Add possibility for arbitrary files to get copied to extra settings

dojo/models.py, dojo/tools/bugcrowd/parser.py
I found that the bug crowd parser had a couple pitfalls where information that was expected to be in the scan report was not actually there. Additionally, I found a strange endpoint deciphering bug where if given a uri like `subdomain.domain.com:1234` the `Endpoint.from_uri()` function will attempt to create an endpoint with the protocol being `subdomain.domain.com` and the path would be `1234`. Im nervous to attempt to modify the path because it is sort of the catch all for uri attributes. Hopefully what I have implemented will suffice for now.
=> Add fixes to bugcrowd parser and endpoint uri util

dojo/api_v2/serializers.py, dojo/reports/views.py, unittests/test_deduplication_logic.py, unittests/test_finding_helper.py
`dojo/api_v2/serializers.py`: Renaming of 2 classes
`dojo/reports/views.py`: Fix for CVS und Excel export to include content of CVE field in Vulnerability Ids for older findings
`unittests/test_deduplication_logic.py`: Change from CVE to Vulnerability Ids
`unittests/test_finding_helper.py`: Renaming of 2 classes
=> Vulnerability Id: Various small changes

.github/workflows/k8s-testing.yml, .github/workflows/test-helm-chart.yml
Bitnami has changed the index.yaml for pre-2022 charts, see https://github.com/bitnami/charts/issues/10539. The Kubernetes tests were not running anymore because of this.
This PR uses the pre-2022 index.yaml and fixes this problem. Nevertheless it shows DefectDojo's Kubernetes installation comes with old charts, that we should update from time to time.
=> Fix for Kubernetes tests

.github/workflows/k8s-testing.yml, helm/defectdojo/templates/network-policy.yaml, helm/defectdojo/values.yaml
This brings light network policies option, that blocks k8s defaults to have open communication between all pods within the cluster. When the option is enabled, communication is allowed only within the DD application components within the same namespace, and from an ingressController toward Django pods from the outside of a namespace. 
Default: disabled
=> [HELM] Network policies

helm/defectdojo/templates/network-policy.yaml, helm/defectdojo/values.yaml
When additional monitoring service is in use (e.g. prometheus) it would be nice for the user to specify and let system to scrape statistics.
=> Option to extend ingress network policy

.github/workflows/release-2-tag-docker-push.yml, .github/workflows/release-x-manual-helm-chart.yml, helm/defectdojo/requirements.lock, helm/defectdojo/requirements.yaml
When doing the release, updating index.yml in the [helm-charts](https://github.com/DefectDojo/django-DefectDojo/blob/helm-charts/index.yaml) branch fails due to some uncommitted changes. Here are the [logs of the failed release action](https://github.com/DefectDojo/django-DefectDojo/runs/6779678651?check_suite_focus=true)
Since the release cannot be accomplished without pushing the helm chart, I reverted the ongoing release for now until this gets sorted
I am unsure if this will actually fix the problem though. Still doing testing.  @dsever @alles-klar @StefanFl
=> Update bitnami refs in GHA and requirements

dojo/settings/settings.dist.py
More people (e.g. https://github.com/DefectDojo/django-DefectDojo/issues/6329) started to need the ability to define `CSRF_TRUSTED_ORIGINS`. It is good to have it as EnvVar.
=> Add variable DD_CSRF_TRUSTED_ORIGINS

dojo/tools/semgrep/parser.py, unittests/scans/semgrep/cwe_list.json, unittests/tools/test_semgrep_parser.py
I faced a bug that in some cases Semgrep can init CWE field as a **list** type. 
And I got an error:
`File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
response = handler(request, *args, **kwargs)
File "/usr/local/lib/python3.8/site-packages/rest_framework/mixins.py", line 19, in create
self.perform_create(serializer)
File "/app/./dojo/api_v2/views.py", line 1971, in perform_create
serializer.save(push_to_jira=push_to_jira)
File "/app/./dojo/api_v2/serializers.py", line 1452, in save
test, finding_count, closed_finding_count, test_import = importer.import_scan(scan, scan_type, engagement, lead, environment,
File "/app/./dojo/importers/importer/importer.py", line 297, in import_scan
parsed_findings = parser.get_findings(scan, test)
File …
=> (feat) Semgrep parser cwe list support

dojo/tools/generic/parser.py
The description of the generic parser only mentions that a cvs file can be provided but json files are possible too, therefore this should be mentioned in the description, s.t. it will be shown in the overview when importing a scan result.
=> Adjust description of Generic Parser

dojo/filters.py, dojo/importers/importer/importer.py, dojo/tools/trivy/parser.py, dojo/utils.py, unittests/scans/trivy/kubernetes.json, unittests/tools/test_trivy_parser.py
fixes #6393
The Trivy parser now supports Kubernetes scans. 
Here I had the feeling it makes sense to set the `service` attribute in the parser, because there are different services running on the Kubernetes cluster. Otherwise namespace, kind and service name would have to part of the title to avoid deduplication of findings for different services.
=> Support Trivy Kubernetes scan

dojo/templates/dojo/endpoints.html, dojo/templates/dojo/engagement.html, dojo/templates/dojo/engagements_all.html, dojo/templates/dojo/finding_related_row.html, dojo/templates/dojo/findings_list_snippet.html, dojo/templates/dojo/report_findings.html, dojo/templates/dojo/request_endpoint_report.html, dojo/templates/dojo/request_report.html, dojo/templates/dojo/simple_search.html
A PR end of last year introduced a typo that let tags not to be displayed anymore in several list.
=> Display tags in several lists again

dojo/api_v2/serializers.py, dojo/api_v2/views.py, dojo/fixtures/dojo_testdata.json, dojo/forms.py, dojo/urls.py, dojo/user/utils.py, unittests/test_apiv2_methods.py, unittests/test_rest_framework.py
There are 2 new API endpoints:
- `GET configuration_permissions/`
- `GET configuration_permissions/{id}/`
For listing (+showing) `Permission`s which are part of [`configuration_permissions`](https://defectdojo.github.io/django-DefectDojo/usage/permissions/#configuration-permissions)
These permissions can be assigned through endpoints `POST/PATCH/PUT users/` and `POST/PATCH/PUT dojo_groups/` to users and groups by specifying the list of `Permission ID`s in the field `configuration_permissions` in the original query.
This action will not touch any other permissions.
`GET /configuration_permissions/{id}/`
```json
{
"id": 0,
"name": "string",
"codename": "string"
}
```
`GET /users/{id}/`
```json
{
"id": 0,
"username": "NX-Esa5Ai_CyZzxj9MF2I0x@-ZOYX6yY41gck@SeJjelxt@b6H1jApB15Tcf_Wu9jCb@-EJqJp4 …
```
=> APIv2: Add support for configuration_permissions

dojo/templates/issue-trackers/jira_full/jira-description.tpl
It's the only tag that isn't bold, it looks a bit odd in the JIRA description.
=> Making the vulnerable component tag "bold" in the JIRA description

dojo/finding/views.py
If you merge a number of findings with no references, the resulting merged finding has a ton of "None" lines in the references. This PR only merges the Reference value if it's not "None". Tested successfully locally.
=> Only merge references if the reference is not None

dojo/settings/settings.dist.py
Dependency Track upgraded the export of results format in order to follow the relevant updated FPF format, so now multiple CWEs are included into to the vulnerabilities export. For information visit their release log https://docs.dependencytrack.org/changelog/ version 4.5.0 . 
In order to not change their API and relevant integrations (such as DefectDojo) they created a work around. So, in case there are multiple CWEs in a single finding they would always use the first one in the list (under the same JSON objects "cweId"and "cweName"), while the total count of CWEs and relevant information will be available in a new array. For more information https://github.com/DependencyTrack/dependency-track/issues/1467#issuecomment-1128161152. 
Close old findings and deduplication features breaks …
=> Remove CWE from Dependency Track Hash Code Field

dojo/templates/issue-trackers/jira_full/jira-description.tpl
This PR adds a Due-Date to the JIRA description that looks like:
Due Date: July 22, 2022
In addition, it cleans up the JIRA description not to write out fields that are commonly "None".
=> Add Due-Date to JIRA description and don't write out None values

dojo/tools/sarif/parser.py, unittests/scans/sarif/cxf-3.4.6.sarif, unittests/tools/test_sarif_parser.py
Some parses (Grype/GitHub) don't use level for the severity but instead use properties/security-severity. See:
https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/sarif-support-for-code-scanning
properties.security-severity | Recommended. A string representing a score that indicates the level of severity, between 0.0 and 10.0, for security queries (@tags includes security). This, with the properties.precision property, determines whether the results are displayed by default on GitHub so that the results with the highest security-severity, and highest precision are shown first. Code scanning translates numerical scores as follows: over 9.0 is critical, 7.0 to 8.9 is high, 4.0 to 6.9 is medium and 3.9 or less is low.
-- | --
=> Take SARIF severity and CVSS score from properties/security-severity

dojo/tools/veracode/parser.py, unittests/tools/test_veracode_parser.py
Veracode parser does not set the CVSS score for SCA
=> Veracode parser does not set the CVSS score for SCA

dojo/templates/issue-trackers/jira_full/jira-description.tpl
For SAST parsers such as Sarif and Semgrep, it doesn't write out the file path and line number to JIRA in the default template. Tested manually.
=> Write out the file path and line for static findings

docs/content/en/integrations/api-v2-docs.md, dojo/templates/dojo/api_v2_key.html
Updated the sample code for API key usage to Python3. 
I left it as close to the original as possible (i.e. accessing __dict__), a cleaner example would probably be to simply pretty-print the response? e.g. `print(json.dumps(r.json(), indent=4)` (without any error handling, assuming the API token and code works)
=> Updated API sample code to py3

dojo/tools/veracode/parser.py, unittests/tools/test_veracode_parser.py
When importing findings from Veracode, it's hard to tell whether findings are SCA/SAST/DAST, so adding a tag will make it easier to both see and search for issues matching a particular type.
=> Add sast/sca/dast tags to Veracode findings

dojo/jira_link/helper.py
If there is an error in pushing a finding to JIRA, the alert will be created with an invalid link (404). For example:
http://localhost:8080/finding/%3Cbound%20method%20Finding.get_absolute_url%20of%20%3CFinding:%20javascript.browser.security.insecure-document-method.insecure-document-method%3E%3E
This is because of a typo in calling get_absolute_url on the finding rather than get_absolute_url()
=> Fix bug with alert title link for JIRA creation

dojo/tools/sarif/parser.py, dojo/tools/semgrep/parser.py, unittests/tools/test_sarif_parser.py, unittests/tools/test_semgrep_parser.py
Align severity mapping between SARIF and semgrep as proposed here:
https://github.com/DefectDojo/django-DefectDojo/issues/6289
- Change SARIF "error" to "High" from "Critical"
- Change Semgrep "warning" to "Medium" from "Low"
With this change both SARIF and Semgrep are consistent with how they map warning and errors.
=> Align severity mapping between SARIF/semgrep

dojo/tools/nuclei/parser.py, unittests/tools/test_nuclei_parser.py
The Nuclei parser is not parsing the classification dictionary, and so is missing CWE/CVSS3 score etc.
=> Parse CWE/CVSS3 from Nuclei classification

docs/package-lock.json, docs/package.json
The GitHub action `github-pages` isn't working anymore after the update of `postcss-cli` introduced in #6486. This PR reverts the changes introduced there.
=> Revert update of postcss-cli

dojo/tools/acunetix360/parser.py
When parsing Acunetix 360 findings, it wraps the description and other fields. This should be disabled as it looks odd. The burp parser does something similar.
=> Don't wrap lines when parsing Acunetix

dojo/tools/cyclonedx/parser.py, unittests/tools/test_cyclonedx_parser.py
The code only picks up the old namespace for CWEs.
=> CWE is not parsed properly for CycloneDX 1.4

dojo/settings/settings.dist.py
We noticed that we are missing `DEDUPLICATION_ALGORITHM_PER_PARSER` configuration for the `StackHawk HawkScan` parser to correctly use specific fields for de-duping, as configured in our `HASHCODE_FIELDS_PER_SCANNER`.
=> StackHawk HawkScan Parser Config Tweak

dojo/templates/issue-trackers/jira_full/jira-finding-group-description.tpl, dojo/templates/issue-trackers/jira_limited/jira-finding-group-description.tpl
- Add group severity and due-date
- Avoid writing out "None" when we don't have branch Id, git tag, etc.
- Write out individual finding CVSS score.
- Write out SAST source line/path
=> Improvements for the default finding group JIRA template

dojo/tools/cyclonedx/parser.py, unittests/scans/cyclonedx/spec1_lowfirst.xml, unittests/tools/test_cyclonedx_parser.py
There are a few problems with the CycloneDX severity parsing:
- For the legacy parsing it takes the first severity found, but also the first CVSSv3 score, which may be in a later severity, so they don't align.
- For XML/JSON it takes the severity directly from the CVSSv3 score, instead of using the Severity field if it exists in the Rating.
=> Fix CycloneDX severity parsing

dojo/tools/acunetix360/parser.py, unittests/tools/test_acunetix360_parser.py
On an import from Acunetix360 the finding date is set to the import date rather than from FirstSeenDate in the report
=> Set the finding date for Acunetix360 from FirstSeenDate

dojo/finding/views.py, dojo/forms.py, dojo/templates/dojo/view_test.html
When you try to add a finding to a group by group name, you get a 500 error. This is because the form uses a boolean instead of a charfield. The form name is a bit confusing, so I renamed it to make it clearer that it's an id.
=> Fix 500 error on adding finding to group name

dojo/finding/views.py
When you create a finding group and select "Push to JIRA" it creates two JIRAs for the finding group.
=> Fix bug with creating two finding group JIRAs on group creation

dojo/templates/dojo/merge_findings.html
A fix for https://github.com/DefectDojo/django-DefectDojo/issues/6137
I simplified the code so that on first load it selects all findings to merge that aren't selected by default as the finding to merge into. Then when finding to merge in to is changed, it unselects it from the findings to merge.
=> Fix UI bug with merging fingings

dojo/forms.py, dojo/settings/settings.dist.py, dojo/templates/dojo/view_eng.html, dojo/templates/dojo/view_finding.html, dojo/templates/dojo/view_test.html, dojo/templatetags/display_tags.py, dojo/urls.py, dojo/views.py, nginx/nginx.conf, nginx/nginx_TLS.conf
In order to make the management of arbitrary files more secure,  I have added the following behaviors:
- Users must be able to edit the object a file belongs to download the file
- A whitelist of supported file types is configurable by a setting/env_var
- `['.txt', '.pdf', '.json', '.xml', '.yml', '.png', '.jpeg']`
=> Add file upload extension allow list, Force authorization to download file

dojo/finding/views.py
When merging findings, it generates a note that bundles all the findings together like:
Finding consists of merged findings from the following findings: Calling Cipher.getInstance("AES") Will Return AES ECB Mode by Default. ECB Mode Is Known to Be Weak as It Results in the Same Ciphertext for [...] (4054), The App Uses the Encryption Mode CBC With PKCS5/PKCS7 Padding. This Configuration Is Vulnerable to Padding Oracle Attacks. (4010) which have been deleted.
It's hard to read this. Instead I propose to generate bulletpoints that looks like:
Finding consists of merged findings from the following findings which have been deleted:
- netty-codec:4.1.54.Final | CVE-2021-37137 (4097),
- CVE-2018-15756 org.springframework:spring-core 4.3.18.RELEASE (1281),
- Vulnerable Component: …
=> Add the merged findings as bulletpoints in the note

dojo/tools/cyclonedx/parser.py, unittests/tools/test_cyclonedx_parser.py
The current title of cyclonedx findings is just the CVE number, this PR aligns it with the titles for the vex xml/json findings, so e.g.:
log4j-core:2.13.2 | CVE-2021-44228
=> Align formatting of cyclonedx title with that of the vex xml/json titles

dojo/filters.py
This PR exposes the `test__engagement__product__prod_type ` on the `ApiFindingFilter`.
Previously it was already exposed on the `FindingFilter` and is used in the UI, e.g. here: `/finding/open?test__engagement__product__prod_type=<id>`.
Fixes #6589.
=> Expose prod_type on ApiFindingFilter

dojo/tools/anchore_grype/parser.py, unittests/tools/test_anchore_grype_parser.py
When using grype to scan a filesystem, it doesn't parse the artifact path as the file-path for the finding. For example:
"locations": [
{
"path": "configuration/.m2/repository/log4j/log4j/1.2.12/log4j-1.2.12.jar"
}
=> Parse the location for Grype

dojo/tools/auditjs/parser.py, unittests/scans/auditjs/auditjs_with_package_namespace.json, unittests/tools/test_auditjs_parser.py
based on this issue https://github.com/DefectDojo/django-DefectDojo/issues/6154, the AuditJS parser will throw an error when the package name has a scope or looks like this `@lerna/cli`. It will show an error like the image below. Generated file by auditjs can see [here](https://mikqi.gitlab.io/-/auditjs-poc/-/jobs/2755337092/artifacts/auditjs_report.json)
This PR is to fix manipulate package name in auditjs parser.
=> fix(auditjs-parser): error when npm package has scope

dojo/engagement/urls.py, dojo/engagement/views.py, dojo/finding/urls.py, dojo/finding/views.py, dojo/forms.py, dojo/models.py, dojo/templates/dojo/copy_object.html, dojo/templates/dojo/findings_list_snippet.html, dojo/templates/dojo/snippets/engagement_list.html, dojo/templates/dojo/view_eng.html, dojo/test/urls.py, dojo/test/views.py, unittests/test_copy_model.py
Users with edit permissions can copy an object from one parent to another.  For example, findings can be copied between tests, tests between engagements, and then engagements can be copied to the same product, but not to another product.
=> Implement object copy to parent objects

dojo/api_v2/permissions.py, dojo/endpoint/utils.py, dojo/models.py, dojo/tools/checkmarx_osa/parser.py
First of all, thanks for this project!
Unlike logging functions, Exceptions do not have this "lazy string formatting" that makes `log("message %s", value)` work and be formatted only when the message is to be printed somewhere. Exceptions are always evaluated when raised.
I have found a couple of lines with that wrong pattern `raise ExceptionName("message %s", value)` instead of `raise ExceptionName("message %s" % value)`, and this PR fixes them.
This leads to message bodies such as:
```json
{
"detail": "No permission to create product_type '%s'"
}
```
Hope this helps!
Pierre
=> Fix format strings used in exceptions

dojo/finding/views.py, dojo/notifications/helper.py
When product member is asking for review, all product members are receiving a message. This PR adapts code, so only user that are asked for review will receive the message. Reason is to eliminate noise generated by alerts.
=> Send message only to reviewers

dojo/finding/views.py, dojo/notifications/helper.py
In previous implementation when closing finding message was like:
```
The finding "Make Sure That Hashing Data Is Safe Here." was closed by admin
More information on this event can be found here: http://localhost:8080http://localhost:8080/test/3
```
So url was repeating twice and there was link to test id, not to a particular finding, this improvement adapts it like:
```
More information on this event can be found here: http://localhost:8080/finding/200
```
=> Fix: url of the finding

docs/content/en/integrations/api-v2-docs.md, dojo/settings/settings.dist.py, dojo/templates/base.html
Even if there was `?docExpansion=none` in the URL, the list was still expanded. Now, it is fixed.
=> API-Swagger(drf-yasg): fix docExpansion

dojo/importers/reimporter/reimporter.py
If findings had a service name set, the re-importer would override it with an empty one, unless it is specified. This behaviour seems incorrect. 
This matches behaviour of the importer.
=> Fix a bug that caused re-imports to drop service name of findings

dc-build.sh, dc-down.sh, dc-stop.sh, dc-unittest.sh, dc-up-d.sh, dc-up.sh, docker/docker-compose-check.sh
The first line of many shell scripts are missing the "!" character,
which make them not to be taken as proper shebangs.
=> Fix shebang on shell scripts

dojo/pipeline.py
fixes #6653 
Without this missing method OAuth2 login is not possible, which affects a lot of DefectDojo installations.
=> Reintroduce missing method modify_permissions to fix OAuth2 login

dc-unittest.sh, dojo/tools/cyclonedx/parser.py, unittests/tools/test_cyclonedx_parser.py
For CycloneDX XML, it sets the finding date as the date of the report timestamp, however it doesn't do this for JSON. This PR is to make it consistent. In addition the PR fixes two issues:
1. The "jake.json" testcase for CycloneDX is not actually run, due to a previous change as to how vulnerability IDs are parsed.
2. The dc-unittest.sh fails on my machine (mac) due to a recent shebang change
=> Parse the report timestamp for CycloneDX json

dojo/importers/reimporter/reimporter.py, unittests/test_import_reimport.py
This is clearly a bug, reimporting the same report over and over would reactivate the previously closed findings. (notice that the code before my change reactivates findings by default, even if the reimport adds a mitigated finding, it opens the existing finding and makes it active for no reason)
This can be improved by doing other date comparisons, so that triage done directly in the scanners can be reflected during reimport.
=> Fix: in reimporter, do not reactivate mitigated findings if they have the same date

docs/content/en/integrations/parsers.md, dojo/settings/settings.dist.py, dojo/tools/sarif/parser.py, unittests/tools/test_sarif_parser.py
Add data in `unique_id_from_tool` based on [fingerprints](https://docs.oasis-open.org/sarif/sarif/v2.1.0/os/sarif-v2.1.0-os.html#AppendixFingerprints) in the SARIF reports.
Also this PR enable de-duplication based on this data or fallback to the old hash method.
I also added unit tests for previous reports.
Fix #6598 
Reference: https://docs.oasis-open.org/sarif/sarif/v2.1.0/os/sarif-v2.1.0-os.html#AppendixFingerprints
=> feat: add SARIF basic de-duplication data

.github/workflows/test-helm-chart.yml
When doing the last release, I was really bothered that the helm test failed from merging dev into master (ptsd from last release) but had not failed from merging regular PRs into dev. I know the helm chart version is valid, because a new one was successfully created with the completion of the release, and that would not have happened if the release version was outdated. This tells me the issue is with the unit test itself. 
After looking at the workflow, I believe the issue to be that a new chart version is created **twice** in a row, but only when ran from against the master branch. In this check, a new version is created (before this past release, it was 1.6.35)
```
- name: Run chart-testing (lint)
run: ct lint --config ct.yaml --target-branch ${{ …
```
=> Modify helm test workflow for master branch

dojo/templatetags/get_banner.py, requirements.txt
On the release of Bleach 5.0.0, the CSS module was separated into a different package. When upgrading to the Bleach 5.0 in dojo, I had overlooked that the login banner sanitizes CSS and not just HTML. This is the fix
=> Add BleachCSS for Login Banner

dojo/finding/helper.py
`"verfied"` was used instead of ` "verified"` 
Fixes #6702
=> Fixes wrong column name for pre-save function

dojo/engagement/views.py
On the Engagement Edit page, it is possible to change the product. However, this has no effect on real engagement's product assignment. Adding the line to fix the issue.
https://github.com/DefectDojo/django-DefectDojo/issues/6588
=> [FIX] Reassign an engagement to another product

dojo/jira_link/helper.py, unittests/dojo_test_case.py, unittests/test_jira_import_and_pushing_api.py, unittests/vcr/jira/JIRAImportAndPushTestApi.test_import_add_comments_then_push_to_jira.yaml, unittests/vcr/jira/JIRAImportAndPushTestApi.test_import_with_push_to_jira_add_comment.yaml
Tested locally correctly.
Fixes: https://github.com/DefectDojo/django-DefectDojo/issues/6434
=> Add all existing finding notes to the JIRA when created

dojo/tools/acunetix/parser.py, dojo/tools/acunetix360/parser.py, dojo/tools/generic/parser.py, dojo/tools/github_vulnerability/parser.py, dojo/tools/netsparker/parser.py, dojo/tools/nuclei/parser.py
In a few of the parsers we just set the CVSS vector directly rather than parsing it.
=> Use the CVSS parser to parse the CVSS vector

dojo/api_v2/serializers.py, dojo/models.py
Per the discussion around #6564, I had forgotten to update the URL returned by the API to actually download the file from the server. Previously, the response returned the URL directly that is not permission controlled. As of #6564, the ability to download files from the direct location is totally blocked, so downloading the file is not actually possible.
In this PR, the access controlled URL is returned instead
Before:
After:
=> Update API endpoint for file upload

dojo/static/dojo/css/dojo.css, dojo/templates/base.html, dojo/templates/dojo/ad_hoc_findings.html, dojo/templates/dojo/add_findings.html, dojo/templates/dojo/add_group.html, dojo/templates/dojo/add_template.html, dojo/templates/dojo/apply_finding_template.html, dojo/templates/dojo/edit_finding.html, dojo/templates/dojo/edit_presets.html, dojo/templates/dojo/edit_product.html, dojo/templates/dojo/edit_product_type.html, dojo/templates/dojo/filter_snippet.html, dojo/templates/dojo/new_eng.html, dojo/templates/dojo/new_params.html, dojo/templates/dojo/new_product.html, dojo/templates/dojo/new_product_type.html, dojo/templates/dojo/promote_to_finding.html
Changes to the footer have been made to prevent it from covering the side navbar. On certain pages, the side navbar and the footer conflict with one another.
_Before this change:_ 
_With this change:_
Previously, the input for tags was being rendered as an EasyMDE editor, this is not necessary, nor is it visually pleasing. Propagated this change to all occurrences of `textarea` elements being replaced by EasyMDEs.
_Before this change:_
_With this change:_
The current rendering of filter inputs is poorly styled (inconsistent input box sizes, poor spacing, etc). Added a few new styles to better display these inputs.
_Before this change:_
_With this change:_
=> Design fixes to footer, tags input, and filters snippet

docs/content/en/getting_started/configuration.md
To avoid situations like https://owasp.slack.com/archives/C2P5BA8MN/p1661972243567139?thread_ts=1661970538.645869&cid=C2P5BA8MN
> In the documentation it says it's in the dojo/settings directory but it doesn't have any local_settings.py file.
=> Doc: Update local_settings.py description

dojo/settings/settings.dist.py
There was no deduplication setting explicitly defined for 'Twistlock Image Scan' which lead to deduplication not working correctly for such reports.
=> Corrected deduplication settings for 'Twistlock Image Scan'

dojo/settings/settings.dist.py
There was no deduplication setting explicitly defined for 'Anchore Enterprise Policy Check' which lead to deduplication not working correctly for such reports.
=> Corrected deduplication settings for 'Anchore Enterprise Policy Check'

dojo/risk_acceptance/api.py
Finding's don't get de-activated when the risk is accepted from the API.  See bug #6779
=> Set finding to inactivate after creation of risk acceptance

dojo/tools/edgescan/api_client.py
If no options were provided to the API scan configuration for edgescan then the scan import would fail when searching for a key in the options object, since no object was available. 
Check if options object is available first before checking for keys.
=> Fix bug that caused scan imports to fail

dojo/finding/views.py
current condition : All notes that we sent through the finding detail are sent to jira. But, the closed notes we sent when we close the finding is not sent to jira even if that notes are saved to the finding notes in the finding detail page.
proposed changes : sent the close finding notes to jira also
=> Adding Closed Notes to Jira

dojo/templates/notifications/test_added.tpl
Currently, when a test is added and slack notification is enable is showed: "New test added for engagement {engament.product}" 
I suggest adding the engament name to this phrase: " New test added for engagement {{engagement.name }} in product {{ engagement.produc}}"
=> Update the text that slack notification shows

dojo/utils.py
`log_user_login_failed()` was failing if `username` as missing in `credentials`
=> Fix log_user_login_failed if username is missing

helm/defectdojo/templates/_helpers.tpl, helm/defectdojo/values.yaml
Fix PostgreSQL service name in the Helm chart
When `postgresql.architecture` is `replication`, 2 services with suffixes are created
- `${release-name}-postgresql-primary`
- `${release-name}-postgresql-read`
*Those suffixes are also customizable via `primary.name` and `readReplicas.name`, but the default values are `-primay` and `-read`.
However, the current chart always tries to use `${release-name}-postgresql` regardless of `postgresql.architecture`
=> fix(helm): fix postgresql svc name

dojo/reports/widgets.py
A fix for https://github.com/DefectDojo/django-DefectDojo/issues/6866
When multiple severities are selected, it only picks the first one. This is because it's appending to a list which doesn't modify the internal list.
Tested that the new report contains both high and critical severities when they are selected.
=> Fixing broken report generation when more than one item is selected

dojo/importers/reimporter/reimporter.py
Due to incomplete fix in https://github.com/DefectDojo/django-DefectDojo/pull/6452
Explainer:
The initial fix was too narrow in its decision/conditions, only looking at items/findings that had a `mitigated` timestamp.
Instead, `is_mitigated` should be used, to simply check if the incoming item is already mitigated or not, and if the existing finding is mitigated or not. I have left the timestamp comparison IF it exists on the item.
=> Fix improper reactivation in reimporter, using is_mitigated

dojo/templates/dojo/view_eng.html, dojo/templates/dojo/view_risk_acceptance.html
Removed get_full_name from accepted_by in two templates, as accepted_by doesn't get set to a user, it's free text entry. Prior to this fix, "Accepted By" value was blank on these two pages.
=> Fix accepted by name

dojo/models.py
The URL inside the file location (in Finding view) generated from Repo URL (in Engagement configuration) is only based on `source_code_management_uri` but scanning results come front different commit hash or branches that are provided by CI/CD platform. I added (only for GitHub) a way to generate the right URL for GitHub repositories gathering hash commit or branch from engagement config.
=> Fix url creation for github for file location

dojo/settings/settings.dist.py, dojo/tools/neuvector/parser.py, unittests/scans/neuvector/many_vulns.json, unittests/scans/neuvector/no_vuln.json, unittests/scans/neuvector/one_vuln.json, unittests/tools/test_neuvector_parser.py
This commit adds the support of NeuVector
(https://github.com/neuvector/neuvector) tool for importing scan results. Scan results can be exported via REST API in JSON format (that is why the tool is named 'NeuVector (REST)'). There is no GUI for that at the moment.
Scan results are just a list of issues found in packages installed in a container or an image. Very similar to Twistlock.
NeuVector also provides compliance scan results. This is not supported by the introduced tool.
=> tools: NeuVector: introducing NeuVector (REST) scan type

dojo/utils.py, unittests/test_rest_framework.py
changed the type of user_post_save to generic Django user so all users created (ldap, oauth, ui) will trigger this function. This should fix https://github.com/DefectDojo/django-DefectDojo/issues/6626
Created a new pull request based of the DEV branch, see the old pull request for previous comments: https://github.com/DefectDojo/django-DefectDojo/pull/6725
=> changed type to regular django type to also pick up creation events

dojo/tools/checkov/parser.py
[29/Mar/2022 11:55:54] ERROR [dojo.api_v2.exception_handler:26] 'check_type'
File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
response = handler(request, *args, **kwargs)
File "/usr/local/lib/python3.8/site-packages/rest_framework/mixins.py", line 19, in create
self.perform_create(serializer)
File "/app/./dojo/api_v2/views.py", line 1957, in perform_create
serializer.save(push_to_jira=push_to_jira)
File "/app/./dojo/api_v2/serializers.py", line 1246, in save
test, finding_count, closed_finding_count = importer.import_scan(scan, scan_type, engagement, lead, environment,
File "/app/./dojo/importers/importer/importer.py", line 349, in import_scan
parsed_findings = parser.get_findings(scan, test)
File …
=> Bugfixing when the Checkov report has no findings

docs/content/en/integrations/parsers.md, dojo/tools/sonarqube_api/api_client.py, dojo/tools/sonarqube_api/importer.py
When SonarCloud integration was initially implemented, each API scan config needed to have an org ID in the service key2 slot. In most cases, this is the same org ID. This PR makes the ORG ID set at the Tool Configuration level with the option to override the global value at the API Scan Config level
Also did some code cleanup and docs
=> SonarQube API Importer: Add sonarcloud global org id, code clean up

dojo/jira_link/views.py
In Jira Cloud, if the assignee is set to "Automatic" or "Not Assigned" the assignee in the response body returns as null and creates a none type object. Fix around line 80 or so
Code clean up to move towards more F strings for easier readability
=> Jira Webhook: Catch missing assignee field + code cleanup

dojo/user/views.py
When sending a 'forgot password' button, I was greeted with a 500 error. I was used to having mailhog there on dev servers..
=> Add validation error when users attempt to send email without valid SMTP server

dojo/tools/cyclonedx/parser.py
version is optional for a CycloneDX components, but DefectDojo throws an error if version isn't present.
https://cyclonedx.org/docs/1.4/json/#components_items_version
=> Make version optional for cyclonedx

helm/defectdojo/templates/celery-beat-deployment.yaml, helm/defectdojo/templates/celery-worker-deployment.yaml, helm/defectdojo/templates/django-deployment.yaml
PR #6149 only fixed the keys for redis but not for rabbitmq. This PR fixes this problem and additionally removed unnecessary ifs, which was already discussed in #6054.
=> [Helm] Fix flawed logic in deployment env vars

helm/defectdojo/templates/_helpers.tpl, helm/defectdojo/templates/django-deployment.yaml, helm/defectdojo/templates/media-pvc.yaml, helm/defectdojo/values.yaml, readme-docs/KUBERNETES.md
Managing a persistent volume claim outside the Chart seems to be stressful. The Chart should be self-sufficient hence, the reason for creating this PR.
=> Helm Chart: Create PVC as part of the Chart

dojo/settings/settings.dist.py, dojo/tools/neuvector_compliance/parser.py, unittests/scans/neuvector_compliance/many_vulns.json, unittests/scans/neuvector_compliance/no_vuln.json, unittests/scans/neuvector_compliance/one_vuln.json, unittests/tools/test_neuvector_compliance_parser.py
This commit makes DefectDojo to support compliance scans performed by NeuVector. Such scan results can only be fetched via REST API using endpoints like /v1/scan/workload/{id} and /v1/host/{id}/compliance. The latter one returns the results in a slightly different format. Both of them are supported.
=> dojo: tool: introduce NeuVector compliance scans import support

dojo/forms.py, dojo/jira_link/helper.py
When creating a JIRA Epic, it uses the engagement name as the epic name (and JIRA summary), as well as the default priority specified in JIRA for epics. 
This task is to add the ability to configure the Epic Name and Priority in DefectDojo. It will fall back to the existing defaults if not specified.
=> Add the ability to specify the Epic name and priority in JIRA

dojo/settings/settings.dist.py
Use DEDUPE_ALGO_HASH_CODE with title,description, same as for the Acunetix scanner.
Tested dedup works OK for the same report on different engagements.
=> Use DEDUPE_ALGO_HASH_CODE for Acunetix360

docs/content/en/integrations/parsers.md
I noticed Rubocop has a parser, but it's not documented.
https://github.com/DefectDojo/django-DefectDojo/blob/dev/dojo/tools/rubocop/parser.py
=> Add Rubocop to parser documentation

dojo/filters.py, dojo/finding/helper.py
When filtering with risk acceptance you get a 500 error:
http://localhost:8080/product/3/finding/open?test_import_finding_action__test_import=&title=&component_name=&component_version=&date=&last_reviewed=&last_status_update=&mitigated=&test__engagement__version=&test__version=&status=&active=unknown&verified=unknown&duplicate=&is_mitigated=&out_of_scope=unknown&false_p=unknown&risk_accepted=unknown&has_component=unknown&has_notes=unknown&file_path=&unique_id_from_tool=&vuln_id_from_tool=&service=&param=&payload=&risk_acceptance=1&has_jira_issue=unknown&jira_creation=&jira_change=&jira_issue__jira_key=&has_finding_group=unknown&has_jira_group_issue=unknown&tags=&test__tags=&test__engagement__tags=&test__engagement__product__tags=&tag=&not_tags=&not_test__tags=&not_test__engagement__tags=&n …
=> Fix errors with risk acceptance filter

dojo/tools/veracode/parser.py, unittests/scans/veracode/veracode_maven.xml, unittests/tools/test_veracode_parser.py
Veracode supplies the maven component name in the library_id attribute. We should use this to align with Veracode SourceClear + CycloneDX etc if it's available. Otherwise we can't group findings by component name correctly.
=> Parse Veracode library_id for SCA to get the maven component name

dojo/filters.py, unittests/test_rest_framework.py
It is not possible to filter `Findings` on `steps_to_reproduce`.
There appears to be a typo in the filter expression in filters.py at [`step_to_reproduce = CharFilter(lookup_expr='icontains')`](https://github.com/DefectDojo/django-DefectDojo/blob/e6a88af6109c8d9fdeee9dddc87a319d74292e88/dojo/filters.py#L1108)
1. Fix typo replacing `step_to_reproduce` with `steps_to_reproduce`.
2. Add tests
I could take or leave the tests, there are no other examples of api filters being tested, but it didn't feel right to make a change without a test.
No other occurrences of `step_to_reproduce` exist in the repository.
both `step_to_reproduce` and `steps_to_reproduce`
=> Enable filtering Findings on steps_to_reproduce

dojo/tools/cobalt_api/api_client.py
Update the Cobalt.io API parser's `CobaltAPI` client to fetch the maximum allowed number of findings and assets.
This fixes a bug in the parser due to changes to the Cobalt.io API that resulted in users not being able to
1. import findings from all of their assets, and
2. import all findings from any given asset.
=> Update the Cobalt API parser's API client

dojo/templatetags/display_tags.py
In the findings page you see "None" for the SLA time:
=> Fix out of SLA time

docs/content/en/integrations/parsers.md, dojo/tools/zap/parser.py, unittests/scans/zap/zap-xml-plus-format.xml, unittests/tools/test_zap_parser.py
I have [added a new XML report format to ZAP](https://github.com/zaproxy/zap-extensions/pull/3983) that includes full request and response headers and bodies. This makes ZAP findings a lot more useful, as they now show the entire req/response pair, making it easier to understand what exactly ZAP did and why it believes the response to be a problem. This PR adds support for the new format to DefectDojo.
Here's an example of what the result looks like in DefectDojo, with my patch applied:
As you can see, there is a small inconsistency in how the data is displayed: The response does not have an empty line between HTTP headers and body. This is due to the fact that [the model removes blank lines](https://github.com/malexmave/django-DefectDojo/blob/feature/zap-request-response/dojo/models.py#L2 …
=> Add support for ZAP "XML with requests and responses" format

dojo/templates/dojo/calendar.html, dojo/templates/dojo/metrics.html, dojo/templates/dojo/pt_counts.html
**Fixed footer starting at the top of the critical product metrics page, due to missing div**
_Before_
_After_ 
**Removed accidental curly brace from the product type counts template (when filtering on R&D findings)**
_Before_
_After_
**Fixed calendar filter buttons**
_Before_
_After_
=> Metrics Style Fixes, Calendar Filters Fix

dojo/tools/acunetix360/parser.py, unittests/tools/test_acunetix360_parser.py
It's useful in DefectDojo to be able to click on a link in the report to go back to the dashboard in Acunetix for the finding.
=> Add a link back to the vulnerability in the references for Acunetix360

dojo/finding/views.py
When users have read only access, It makes sense for them to be able to request another user to review a finding
=> Make requests of a peer review available to those with read access

dojo/templates/dojo/engagement.html, dojo/templates/dojo/engagements_all.html
The products and findings tabs have three vertical dots that allow you to edit/delete/etc., however these are missing from the engagements tab. So if you go to "All Engagements" for example you can't delete an engagement.
This PR adds the three vertical dots for "All Engagements", "Active Engagements" and "Engagements by Product"
=> Add the ability to the UI to delete engagements from the engagement tab

docs/content/en/integrations/importing.md
Was reading docs and saw a typo
=> Fix typo in docs

dojo/jira_link/views.py
If a ticket has not been assigned to a user, status changes cannot be applied via the web hook as exceptions are thrown and caught
=> Add assignee_name default in jira web hook

dojo/notifications/helper.py
Before this fix django tried to get one row from database for system notifications settings, but there are two rows when user_id=None - system and template notifications settings. As a result there was used Notifications() instance with default settings (alert, alert) and system notifications settings was ignored.
=> Fixed system notifications

dojo/tools/cobalt_api/parser.py, unittests/scans/cobalt_api/cobalt_api_one_vul_invalid.json, unittests/scans/cobalt_api/cobalt_api_one_vul_out_of_scope.json, unittests/tools/test_cobalt_api_parser.py
Update the Cobalt API parser in accordance with newly introduced severity levels over at Cobalt.io. In particular, this makes explicit that findings with the Cobalt.io severity "informational" should be mapped to "Info" and adds that findings with the Cobalt.io severity "critical" should be mapped to "Critical".
I adjusted the existing test suite for the parser so that one of existing cases now has an "informational" severity and a "critical" severity. Every possible severity (including `null`) is now tested at least once.
<details>
<summary><a href="https://docs.cobalt.io/v1/#findings">See the Cobalt.io API (v1) docs for more details</a></summary> 
</details>
=> Update the Cobalt API parser's severity mapping

dojo/finding/views.py, unittests/test_finding_helper.py
When editing a finding currently only it is checked whether a finding is set to false positive when it is being closed but it could also be closed because it is out of scope. This is added in this PR
=> Adjust possibility of out_of_scope when edit finding

dojo/templatetags/display_tags.py
When using finding groups within a test, the SLA calculation for groups passes the entire group to the SLA calculation for a single finding. There is an expected mismatch there. This PR takes the most severe finding I the group and passes that finding the SLA calculation function so that the group has the fastest approaching SLA.
=> Make SLA calculation of a Finding Group use the most severe finding

dojo/tools/solar_appscreener/parser.py
Error, when trying to parse appscreener report. 
[05/Nov/2022 01:41:15] ERROR [dojo.engagement.views:683] invalid literal for int() with base 10: '' Traceback (most recent call last):
File "/app/./dojo/engagement/views.py", line 668, in import_scan_results
test, finding_count, closed_finding_count, _ = importer.import_scan(scan, scan_type, engagement, user, environment, active=active, verified=verified, tags=tags,
File "/app/./dojo/importers/importer/importer.py", line 298, in import_scan
parsed_findings = parser.get_findings(scan, test)
File "/app/./dojo/tools/solar_appscreener/parser.py", line 50, in get_findings
finding.line = int(finding.line)
ValueError: invalid literal for int() with base 10: ''
Because first line transfer to string after split. This fix should resolve it. I checked …
=> Fix appscreener parser

.github/workflows/integration-tests.yml, .github/workflows/k8s-testing.yml, .github/workflows/release-1-create-pr.yml, .github/workflows/release-2-tag-docker-push.yml, .github/workflows/release-3-master-into-dev.yml, .github/workflows/release-x-manual-helm-chart.yml, .github/workflows/submodule-update.yml, .github/workflows/test-helm-chart.yml
- GitHub has begun adding warnings to actions that are using the `set-output` directive in favor of a different format
- https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/ 
- GitHub is also deprecating the use of Node12 in favor of Node16, so some actions needed to be updated or replaced 
- https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
=> Fix deprecations of GHA (set-output and node12)

dojo/api_v2/serializers.py, dojo/api_v2/views.py, dojo/finding/views.py, dojo/forms.py
This is a try to resolve the issue discussed in #7059 
Result:
=> Add Status of Findings when Close Finding

dojo/tools/twistlock/parser.py, unittests/scans/twistlock/one_vuln_no_link.json, unittests/tools/test_twistlock_parser.py
A fix for https://github.com/DefectDojo/django-DefectDojo/issues/7146
=> Fix import error when twistlock scan has no link

dojo/settings/settings.dist.py, dojo/tools/rusty_hog/parser.py
Currently the same finding (e.g. a secret string in line 3) will not be deduplicated in case its line shifts (e.g. new lines included in between), but instead be found as a new finding, thought the core issue was not resolved.
This change adjusts the hashcode calculation to include the file path + actual occurrence of the secret string.
=> Adjusted Rusty Hog deduplication to be less flaky

dojo/api_v2/serializers.py
The previous functionality only works in the UI. I'll submit the re-importer in a separate PR. Tested:
- Importing in the UI
- Calling import-scan + reimport-scan via the API.
=> Implement create_finding_groups_for_all_findings in the importer

docs/content/en/integrations/parsers.md, dojo/tools/ggshield/parser.py, unittests/scans/ggshield/many_findings.json, unittests/scans/ggshield/no_finding.json, unittests/scans/ggshield/one_finding.json, unittests/tools/test_ggshield_parser.py
This PR will add ggshield (https://github.com/GitGuardian/ggshield) secret scanner JSON Report as a new scanner/importer.
=> Feature/add tool ggshield Parser

dojo/settings/settings.dist.py
On re-import, or if de-dup is enabled, it closes all other findings for a given component name/version that don't have a CVE (Veracode premium data). This takes the severity into account, so it doesn't end up closing a critical finding as a duplicate of a Low severity finding.
=> Add severity for Veracode SCA hashcode calculation

dojo/tools/bugcrowd_api/api_client.py, dojo/tools/bugcrowd_api/importer.py, dojo/tools/bugcrowd_api/parser.py, unittests/scans/bugcrowd_api/bugcrowd_many.json, unittests/scans/bugcrowd_api/bugcrowd_one.json, unittests/tools/test_bugcrowd_api_importer.py, unittests/tools/test_bugcrowd_api_parser.py
I noticed that my implementation did a duplicate detection in the wrong way, since Bugcrowd itself marks submissions as duplicates, but they mean something else: another researcher made a submission about the same thing.
Since my API client is not returning the duplicate submissions, but only the "first come, first served" submission, there is no reason to use the duplicate field, and it was throwing a lot of issues.
So I ripped out the line `duplicate=bugcrowd_duplicate,`
I'm also fixing the links in the defectdojo findings in markdown, I had to propagate the api scan configuration object back to the parser so it can get the service key 1, which is the program name required in the url link.
I also have removed the "Informational" state from the active issues. It is considered to be a …
=> Bugcrowd API parser fixes

dojo/jira_link/helper.py, helm/defectdojo/values.yaml
Fixes: https://github.com/DefectDojo/django-DefectDojo/issues/6963
Depends on: https://github.com/pycontribs/jira/pull/1527
If you don't have the update in the mentioned dependency than behaves as it used to - works until Jira 9 and breaks afterwards.
If you update the dependency than it will continue working after Jira 9.
With the updated dependency it will throw deprecation warnings on Jira versions [8.4 - 9).
Tested manually against JIRA 7.13.8, 8.22.6 and 9.3.1.
=> Support jira 9

dojo/finding/views.py, dojo/templates/dojo/close_finding.html
When note_types activated it should be checked if up to one note_type is missing. When including this note no note_types would be missing and therefore all mandatory notes are included and an additional note is not necessary.
resolve #7160
=> Remove enforcement of unnecessary notes

dojo/models.py
I noticed for SAST, it doesn't generate a correct link back to GitHub when the repo is configured in the engagement, because the if statement for branch/commit hash etc only checks if the value is not None. Instead it should check for not empty.
=> Fixing link generation code

dojo/static/dojo/js/metrics.js, dojo/templates/dojo/view_product_details.html
Fix for #7183. Previews for different sized windows below.
_Window width of ~1600px_
_Window width of ~1300px_
_Window width of ~800px:_
=> Fix for languages plot legend expanding out of panel

.github/workflows/k8s-testing.yml
Per the [Amazon EKS Kubernetes release calendar](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-release-calendar) version 1.18.x of Kubernetess has been dropped off. 
Since we have been testing againt 1.22.x as the latests version, I have made that our oldest supported version, and bumped the latest to 1.23.9
Ii would rather go to 1.24.x or higher,  but do not have the k8 knowledge to debug and make it happen
=> Rev k8 supported versions

dojo/tools/horusec/parser.py, unittests/tools/test_horusec_parser.py
`2022-02-02` is 10 characters long, but it only took the first 9.
=> Fixed bug with the horusec parser's date parser.

dojo/settings/settings.dist.py
It should be possible to change the allowed file size for a scan via an env variable.
closes #6987
=> Update settings.dist.py to include scan file size as env variable

dojo/middleware.py, dojo/settings/settings.dist.py
As the title says, the API does not respond very well to POST requests that do not have a trailing slash. Simply redirecting whatever data in the payload would not be a good idea either, so I took the "update the response" in transit route
=> Add middleware to alert users of missing trailing slash

dojo/templates/dojo/custom_html_report_finding_list.html, dojo/templates/dojo/snippets/endpoints.html
- Made the finding main header smaller to include the counter and the DefectDojo ID number
- Included the score in the severity
- Added the CVE if it exists with the relevant web link
- Location: Added the Service and fixed the issue with the file path width
I hope you like the changes, it produces smaller in size reports and includes additional and important information related to a finding.
=> Improved the design of the custom html report findings

dojo/models.py
I noticed in the Endpoints tab for a product that an Endpoint will be shown as mitigated, but an endpoint associated with a Host will not be shown as mitigated, when the Finding is inactive (but not mitigated). This change excludes inactive findings from Endpoint.host_mitigated_endpoints to make it consistent.
=> Change Endpoint.host_mitigated_endpoints not to include active Findings

dojo/utils.py
In the product list the open findings, and vulnerable endpoints / hosts are listed. However in the product page, the open findings are shown in the tab, but all hosts / endpoints. This PR makes it consistent to only show the numbers for the open hosts / endpoints instead.
=> Show vulnerable hosts / endpoints in the Endpoint product tab

dojo/static/dojo/css/dojo.css
The extra padding added when expanding the sidebar caused the new footer to expand outside of the main page wrapper. This should (hopefully) fix the issue without impacting anything else.
Example of the issue:
[sc-177]
=> Fix for overscroll issue

dojo/product/views.py
For the open endpoint metrics it just shows all open endpoints, as it doesn't check the status of the associated findings.
=> Fix open endpoint count

dojo/templates/dojo/dashboard-metrics.html, dojo/templates/dojo/edit_product_type.html, dojo/templates/dojo/metrics.html, dojo/templates/dojo/paging_snippet.html, dojo/templates/dojo/pt_counts.html, dojo/templates/dojo/view_note_history.html
The following commit introduced some regressions:
commit 7942d70f23c231ebaf29fa0bed82e03cdae4362d
Author: Dmitry <mukovkin@yandex.ru>
Date:   Sat Dec 10 10:04:02 2022 +0700
Translate product type (#7255)
You can't reference a property in blocktranslate, so there was a bunch of empty text in the UI in various places.
=> Fix regression in blocktranslate

dojo/tools/veracode/parser.py, unittests/scans/veracode/mitigated_fixed_finding.xml, unittests/tools/test_veracode_parser.py
We are seeing some recent failures with Veracode, where findings with "Fixed" status but no mitigation information are not being marked as mitigated.
=> Set Veracode "Fixed" findings as mitigated

dojo/settings/settings.dist.py
Fixes an issue introduced by #7085 when trying to load the sample data
```
AttributeError: Problem installing fixture '/app/dojo/fixtures/defect_dojo_sample_data.json': 'Settings' object has no attribute 
```
=> Add AUDITLOG_DISABLE_ON_RAW_SAVE to Settings

dojo/static/dojo/css/dojo.css
Added CSS selector for all "table" elements that are children of "EasyMDEContainers" to remove the "tables" class 100% width style.
Before:
After:
[sc-120]
=> Fix for CSS issue for EasyMDE table icon

dojo/filters.py
There is currently no way to filter or perform product get via the API on an exact product name. This change introduces a new field to the ProductFilter and ApiProductFilter to filter/get a product by exact name.
I do not see a point in adding this to any other objects, as you can have duplicate engagements, findings, etc. with identical names.
[sc-230]
=> Added exact product name filter

helm/defectdojo/templates/media-pvc.yaml
Removing of extra media from the naming
=> Fix: removing typo from PVC name

dojo/api_v2/serializers.py, unittests/test_rest_framework.py
=> API-bugfix: Endpoint_status - do not fail if date is missing

dojo/importers/reimporter/reimporter.py
On re-import, if an open duplicate finding is found it will save the finding if the finding has no component name/version, which will be the case for dynamic findings. It should only save if the new finding has a defined component name/version.
=> Avoid unnecessary save for dynamic findings on reimport

dojo/settings/settings.dist.py
Simpler than https://github.com/DefectDojo/django-DefectDojo/pull/7411 for now, this is simply to expose the settings.dist.py as an env var, that can be used via the Helm chart, to add other Jira issue types.
=> New env var DD_JIRA_EXTRA_ISSUE_TYPES to add Jira issue types

dojo/importers/reimporter/reimporter.py
A fix for https://github.com/DefectDojo/django-DefectDojo/issues/7403
The problem here is that the port is a String in the Endpoint, something that is cleaned up by clean(). Comparison fails compared to the existing endpoint as a result, and the endpoint gets incorrectly mitigated on reimport.
=> Clean unsaved endpoints before comparing them to existing endpoints

dojo/api_v2/serializers.py, dojo/importers/reimporter/reimporter.py, dojo/importers/utils.py
see issue #7367
tags are created while using the reimport_api and creating a new, not already existing test.
when the test exists the newly set tags are ignored.
with this pr tags will be overwritten when tags are set while reimporting a existing test object.
if no tags are set the existing tags will remain.
the integration_tests locally ran without any errors.
i've specified the behaviour in the api help text.
=> Handle test tags when reimporting with reimport_scan api

dojo/tools/awssecurityhub/parser.py, unittests/scans/awssecurityhub/one_finding_active.json, unittests/tools/test_awssecurityhub_parser.py
A fix for https://github.com/DefectDojo/django-DefectDojo/issues/7437
It fixes two bugs in the AWS Security Hub parser:
1. When a finding is mitigated, set it to inactive.
2. The code was setting all issues to mitigated!
=> If findings are mitigated for AWS Security Hub then set them to inactive

dojo/templates/dojo/add_endpoint_meta_data.html, dojo/templates/dojo/breadcrumbs/endpoint_breadcrumb.html, dojo/templates/dojo/delete_endpoint.html, dojo/templates/dojo/edit_endpoint_meta_data.html, dojo/templates/dojo/endpoints.html, dojo/templates/dojo/simple_search.html, dojo/templates/dojo/snippets/endpoints.html, dojo/templates/dojo/view_endpoint.html, dojo/templates/dojo/view_test.html
"Check documentation for look for" -> "Check documentation to look for"
=> Fixing typo in endpoint documentation

dojo/importers/reimporter/reimporter.py
A fix for https://github.com/DefectDojo/django-DefectDojo/issues/7451
Like in the importer, we should catch and log endpoint validation errors from Endpoint.clean()
closes #7451
=> Catch endpoint validation errors in the reimporter

dojo/management/commands/jira_status_reconciliation.py
Fix for the issue:
DEBUG [dojo.management.commands.jira_status_reconciliation:120] None,True,True,True Traceback (most recent call last): File "/app/./manage.py", line 11, in <module> execute_from_command_line(sys.argv) File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line utility.execute() File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 413, in execute self.fetch_command(subcommand).run_from_argv(self.argv) File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 354, in run_from_argv self.execute(*args, **cmd_options) File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 398, in execute output = self.handle(*args, **options) …
=> Fix manual Jira reconciliation issue

dojo/settings/template-local_settings
I changed the method "url" to "re_path" by requirement of Django 4 in template-local_settings
=> Change url -> re-path in template-local_settings

docs/content/en/usage/features.md, dojo/settings/settings.dist.py
Simply a new env var that enables users to hardcode their hashcode fields another way, which will be possible for Kubernetes deployments too.
It copies from `DD_CELERY_BROKER_TRANSPORT_OPTIONS`, because it's loading a JSON String from the env, into a dict, and replaces the settings.dist.py values with the ones in the dict
Not much testing to add I think, it works well, no exception handling needed because we don't want the startup to work if the value isn't valid.
A lot of env vars are kinda undocumented, I think I'll push another commit to mention it.
=> New env var DD_HASHCODE_FIELDS_PER_SCANNER

.github/workflows/detect-merge-conflicts.yaml, .github/workflows/gh-pages.yml, .github/workflows/integration-tests.yml, .github/workflows/k8s-testing.yml, .github/workflows/test-helm-chart.yml, .github/workflows/unit-tests.yml
I have been noticing that unit tests have been running twice on during the merge process:
1. In the PR itself on each commit
2. After merging from contributor branch X to dev/bugfix/master
This is redundant and clogs the actions queue. 
I suspect this may also fix the helm lint tests on master since the primary reason for failing is that the test is running post merge to master (checking master helm version for an increased helm version after it has already been bumped)
=> Disable GHA unit tests on push to branch, limit only to PR

dojo/models.py, dojo/templates/issue-trackers/jira_full/jira-description.tpl
When pushing a semgrep finding to JIRA, it would be nice to add a link to the source code, link can be seen in DefectDojo UI,
=> Add a link to the source code in the JIRA description

dojo/importers/reimporter/utils.py
When using the importer, you can create a product with no description. Then if you try to edit the product in the UI it errors if you don't add a description. I think description should be optional in the UI as well.
=> Use the product name as the description in the importer

Dockerfile.nginx-alpine, Dockerfile.nginx-debian, docker-compose.yml, docs/content/en/getting_started/running-in-production.md, docs/content/en/integrations/ldap-authentication.md
Building locally with `docker-compose --profile mysql-rabbitmq --env-file ./docker/environments/mysql-rabbitmq.env up --build` would fail with `failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /var/lib/docker/tmp/.../Dockerfile.nginx: no such file or directory`
Updated references to Dockerfile.django and Dockerfile.nginx
Not sure of the best location to document the `DEFECT_DOJO_OS` environment variable but leaving it undocumented doesn't seem ideal. Open to advice if nothing comes to mind before this has eyes on it.
=> Add default Dockerfile operating system

docker-compose.override.integration_tests.yml, tests/base_test_class.py
For some reason, the following option does not have any effect on where downloaded files go
```
prefs = {"download.default_directory": cls.export_path}
dd_driver_options.add_experimental_option("prefs", prefs)
```
For the sake of fixing unit tests, I have set the download path to `/app` where the files are ending up
=> Set download path to /app instead of media

dojo/tools/fortify/parser.py, unittests/scans/fortify/issue6082.xml, unittests/tools/test_fortify_parser.py
Maintenance work on Fortify parser to support new versions.
=> Improve Fortify parser to manage new versions

dojo/models.py
The API uses the `get_accessible_url` function in `models.py` when retrieving attached files for engagements/tests/findings. This functions then [returns an URI of the form `access_url/{file_id}/{obj_id}/{obj_type}`](https://github.com/DefectDojo/django-DefectDojo/blob/master/dojo/models.py#L665). Trying to access attached imaged via the returned file URL will result in an error 404 Not Found.
The [`urls.py` only has a routing entry for `access_file`](https://github.com/DefectDojo/django-DefectDojo/blob/master/dojo/urls.py#L191) defined, and the views are using that URI, too. So, `get_access_url` should return the same URI path.
=> Bugfix: get_accessible_url should return access_file instead of access_url

dojo/importers/reimporter/utils.py
This is a performance improvement in the re-importer to:
1. Only mitigate endpoint statuses if it's not already mitigated
2. Only reactivate endpoint statuses if it's already mitigated
=> Only mitigate endpoints that are not already mitigated

dojo/notifications/helper.py, dojo/templates/notifications/alert/engagement_added.tpl, dojo/templates/notifications/alert/report_created.tpl, dojo/templates/notifications/alert/sla_breach.tpl, dojo/templates/notifications/alert/test_added.tpl, dojo/templates/notifications/alert/upcoming_engagement.tpl, dojo/templates/notifications/mail/engagement_added.tpl, dojo/templates/notifications/mail/other.tpl, dojo/templates/notifications/mail/product_added.tpl, dojo/templates/notifications/mail/product_type_added.tpl, dojo/templates/notifications/mail/report_created.tpl, dojo/templates/notifications/mail/risk_acceptance_expiration.tpl, dojo/templates/notifications/mail/test_added.tpl, dojo/templates/notifications/mail/upcoming_engagement.tpl, dojo/templates/notifications/msteams/risk_acceptance_expiration.tpl, dojo/templates/notifications/slack/other.tpl, dojo/templates/notifications/slack/product_added.tpl, dojo/templates/notifications/slack/product_type_added.tpl, dojo/templates/notifications/slack/report_created.tpl, dojo/templates/notifications/slack/risk_acceptance_expiration.tpl, dojo/templates/notifications/slack/scan_added.tpl, dojo/templates/notifications/slack/sla_breach.tpl, dojo/templates/notifications/slack/test_added.tpl, dojo/templates/notifications/slack/upcoming_engagement.tpl
There is a regression in 2.19.0 caused by https://github.com/DefectDojo/django-DefectDojo/pull/7315. Alerts are missing key information, i.e. on slack:
```
DefectDojo
APP  [3:01 PM]
The engagement "" has been created in the product "". It can be viewed here:
```
It's the same fix as for https://github.com/DefectDojo/django-DefectDojo/pull/7301
I tested most of the changes for mails + alerts.
=> Fix missing information in notifications

dojo/importers/reimporter/utils.py
A fix for the last issue raised on https://github.com/DefectDojo/django-DefectDojo/issues/7403#issuecomment-1413909653. When a finding is re-imported, it closes all endpoints not contained in the new finding. However it doesn't reactivate all findings that *are* contained in the new finding. If there is a change in the new finding where an endpoint is reactivated, the existing finding won't have the correct endpoint status.
Tested the scenario with Nessus files in the link above.
=> Old finding endpoints are not reactivated in the reimporter

dojo/templates/notifications/slack/engagement_added.tpl, dojo/templates/notifications/slack/other.tpl, dojo/templates/notifications/slack/product_added.tpl, dojo/templates/notifications/slack/product_type_added.tpl, dojo/templates/notifications/slack/report_created.tpl, dojo/templates/notifications/slack/risk_acceptance_expiration.tpl, dojo/templates/notifications/slack/scan_added.tpl, dojo/templates/notifications/slack/sla_breach.tpl, dojo/templates/notifications/slack/test_added.tpl
There's a further issue with slack notifications, where the display_tags template is not imported leading to errors like:
```
[14/Feb/2023 08:14:03] ERROR [dojo.notifications.helper:141] error during rendering of template notifications/slack/other.tpl exception is Invalid filter: 'full_url'
[14/Feb/2023 08:14:03] ERROR [dojo.notifications.helper:236] Invalid filter: 'full_url'
```
Tested a range of slack notifications.
=> Fix slack notifications

dojo/tools/dependency_track/parser.py, unittests/scans/dependency_track/many_findings_with_alias.json, unittests/tools/test_dependency_track_parser.py
this enhances the dependencytrack parser to add the vulnerability alias information into the vulnerability_id variable of defectdojo.
Fixes issue: https://github.com/DefectDojo/django-DefectDojo/issues/7582 
**Checklist**
- enhancement
- performance
- feature
- bugfix
- dependencies
- settings_changes (when the PR introduces changes or new settings in settings.dist.py)
If the dev branch has changed …
=> read aliases from dependencytrack FPF format

dojo/importers/reimporter/reimporter.py
I found that when we have an active finding, and then reimport where the triage tool has marked the finding as risk accepted upstream, that the original finding in DefectDojo remains active.
Tested this using Acunetix.
=> Risk accepted findings don't close old findings in the reimporter

dojo/settings/settings.dist.py
This prevents the use of environment variables to set the deduplication algorithm for those scanners.
=> Fix missing GitLab scanners in settings file

dojo/tools/mobsfscan/parser.py, unittests/scans/mobsfscan/many_findings_cwe_lower.json, unittests/tools/test_mobsfscan_parser.py
Hello!
Fix for #7630. This error appeared due to the fact that in the new report, mobsfscan CWE was written in lower case.
Thank you!
=> Fix for mobsfscan parser 2

dojo/engagement/views.py, dojo/risk_acceptance/helper.py
There was a possibility to add the same finding to multiple risk exceptions. This was discouraged in the UI, but it was possible to do so by unaccepting, creating a new risk acceptance, and then adding the finding back to the original risk acceptance.
=> Eliminate possibility of adding single finding to multiple risk exceptions

.github/release-drafter.yml, .github/workflows/release-x-manual-helm-chart.yml
This eliminates the need to copy the little rainbow over to the title of the release. It will always be there now. 
The resolver stanza is for the release drafter to not dump the notes into the next minor release every time since we are doing weekly patches now
=> Update the release drafter to make releases less manual

dojo/api_v2/serializers.py, dojo/api_v2/views.py, unittests/test_rest_framework.py
When we moved static files from being served by nginx to uwsgi for added RBAC support, the API endpoint for downloading files was forgotten. I have added endpoints to Finding, Test, and Engagement levels so that RBAC permissions can be inherited from the object rather than creating file based permissions
closes #7608 
[sc-533]
=> Add API endpoint download files by ID

.github/workflows/build-docker-images-for-testing.yml, .github/workflows/integration-tests.yml, .github/workflows/k8s-tests.yml, .github/workflows/rest-framework-tests.yml, .github/workflows/unit-tests.yml
From our monthly meeting in January, we discussed unifying the docker build/cache steps into a single place to take advantage of GitHubs caching mechanism. This PR makes the unit tests one single action that first builds the docker containers, and then run the following tests in parallel:
- unit tests (renamed to "rest framework tests")
- integration tests (renamed to "user interface tests")
- k8s
The hope here is that if there is a build error, it will fail before any of tests actually run. In the event of an isolated failure (usually in the integration tests) then they can singularly be reran like they are today
[sc-515]
=> Update unit test flow to build containers once and store in uniform location

.github/workflows/release-x-manual-docker-containers.yml
Added a matrix dimension for the buildx platform parameter to build both amd64 and arm64 images.
Without Docker Hub secrets, I cannot test. But the workflow change is really straight-forward.
As far as I can see there is no architecture mentioned in the docs. If anything, this will make the tutorial in `Docker.md` work on Apple Silicon.
=> Added amd64 build config for Apple Silicon

dojo/finding/helper.py, dojo/importers/importer/importer.py, dojo/importers/reimporter/reimporter.py
If we didn't previously create finding groups on an import, and if we have a new re-import with a finding that matches a old finding, then a group isn't created.
Tested that a new finding group is correctly created on re-import.
=> Make sure old findings are added to finding groups in the reimporter

dojo/utils.py
When attempting to add a new user, a 500 error is generated. This error occurs when all options for creating a difficult password for new users have been removed.
1. Remove all options for new users to create a difficult password.
2. Attempt to add a new user.
Docker Compose
nginx
Operating System: Kali 6.0.0
DefectDojo version: V2.19.1
____
You can view the issue that I opened for this at: https://github.com/DefectDojo/django-DefectDojo/issues/7673
This is my first time creating a PR, so please let me know if I have missed anything.
=> Fix UnboundLocalError when user remove all options for password

dojo/tools/api_blackduck/api_client.py
Blackduck API request timeout increased from default 15 sec to 120 seconds.
I have faced error, due to slow processing data on my blackduck server, it needed 40 sec to process request and I got error message everytime "message":"The upstream server is timing out".
#7714 
Build and deploy new docker image with this change. Tested on my staging env, worked fine.
**Checklist**
=> BlackDuck API read timout increased

dojo/api_v2/views.py
Reduce the number of calls in engagement presets endpoint from 4 to 1 (engagement presets, product type ID query, test type ID queries, network locations ID queries) [sc-614]
=> Add prefetching to engagement presets endpoint

dojo/api_v2/views.py
Reduce the number of calls in product API scan config endpoint from 3 to 1 (product API scan config, product ID query, tool configuration ID query)  [sc-615]
=> Add prefetching to product API scan config presets endpoint

dojo/finding/helper.py
When adding or removing a finding to/from a finding group, if the finding group is linked with a JIRA, the JIRA is not updated.
Tested:
- Removing a finding from a Finding Group, removes the finding from the linked JIRA
- Adding a finding to a finding group, adds the finding to the linked JIRA
- Adding a finding via group by, adds the finding to the linked JIRA
=> Update JIRA when findings are added/removed to/from the finding group

docs/content/en/integrations/parsers/file/github_vulnerability.md, dojo/settings/settings.dist.py
The GitHub Vulnerability Scan hash list (for dedupe) is too flexible. In a big project with more than one, for instance, Pipfile you should have the same vulnerability (from dependabot for instance) in more than one file. In this case, all these vulnerabilities are deleted because of deduplication.
Adding 'file_path' you are able to maintain both instances of the vulnerability.
=> Fix GitHub dedupe

dojo/api_v2/serializers.py, dojo/api_v2/views.py
Add extra path in Engagement endpoint for checklists because there was not a way to get or create those checklists from the api
=> Add extra path in Engagement endpoint for checklists

dc-unittest.sh, dojo/api_v2/serializers.py, dojo/api_v2/views.py
The risk acceptance API endpoint showed the full media URL path. It has been replaced with the access controlled download link. Also added an api path to download the risk acceptance proof directly
=> Improve Risk Acceptance api endpoint

requirements.txt
Fixes: #6963
Fixes Jira 9 support by requiring the "jira" Python module which includes the corresponding fix. See the referenced bug report for more information.
The fix was validated in our on-premise setup.
N/A
=> requirements: set 'jira' module to 3.5.0 which includes Jira 9 support

dojo/reports/views.py
After the tagulous library migration, querysets are casted to `TagulousCastTaggedQuerySet`
=> Fix product findings report

dojo/api_v2/serializers.py, dojo/tools/veracode_sca/parser.py
The Veracode SCA description contains redundant information available elsewhere in the finding (CVE, Severity). Once pushed to JIRA it results in a seriously cluttered description. This just removes the CVE/Severity information from the description.
Tested it works OK with a Veracode CSV.
=> Removing redundant information from Veracode SCA description

dojo/templates/base.html, dojo/templates/defectDojo-engagement-survey/create_questionnaire.html, dojo/templates/defectDojo-engagement-survey/list_questions.html, dojo/templates/defectDojo-engagement-survey/list_surveys.html, dojo/templates/dojo/dashboard.html, dojo/templates/dojo/dev_env.html, dojo/templates/dojo/edit_dev_env.html, dojo/templates/dojo/edit_regulation.html, dojo/templates/dojo/edit_sla_config.html, dojo/templates/dojo/findings_list_snippet.html, dojo/templates/dojo/github.html, dojo/templates/dojo/groups.html, dojo/templates/dojo/jira.html, dojo/templates/dojo/note_type.html, dojo/templates/dojo/regulations.html, dojo/templates/dojo/rules.html, dojo/templates/dojo/sla_config.html, dojo/templates/dojo/templates.html, dojo/templates/dojo/test_type.html, dojo/templates/dojo/tool_config.html, dojo/templates/dojo/tool_type.html, dojo/templates/dojo/users.html, dojo/templates/dojo/view_cred.html, dojo/templates/dojo/view_finding.html, dojo/templates/dojo/view_test.html, dojo/templates/dojo/view_user.html, dojo/templatetags/authorization_tags.py, unittests/authorization/test_authorization_tags.py
When an error page is shown, various menu items will be unavailable due to a permissions issue.
[sc-724]
=> Fix menu items disappearing on error pages

dojo/jira_link/helper.py
We noticed a problem when de-duplication is enabled and when multiple engagements report the same CVE in a product with push_to_jira enabled. The first Finding creates the JIRA, but then for all subsequent Findings we get notification alerts that they can't push to JIRA, as the deduplication logic sets the Findings to inactive before push_to_jira is called.
The fix is just to check when push_to_jira fails if the finding is already marked as duplicate, and just log this rather than create an alert.
Test it works locally.
=> Don't create a notification alert when a finding is a duplicate

dojo/jira_link/helper.py
I found undefined variables for two functions. It produces an error in a case when **except JIRAError** block is triggered.
=> feat: fix jira errors handling

docs/content/en/integrations/parsers/file/talisman.md, dojo/tools/talisman/parser.py, unittests/scans/talisman/many_findings.json, unittests/scans/talisman/no_finding.json, unittests/scans/talisman/one_finding.json, unittests/tools/test_talisman_parser.py
This PR will add Talisman (https://github.com/thoughtworks/talisman) as a new scanner/importer.
Documentation included in `docs/content/en/integrations/parsers/file/talisman.md`
**Checklist**
=> Add parser for Talisman

dojo/api_v2/views.py
I saw in the DRF docs that `filterset _fields` were all lists. The ones in dojo are all tuples. I could not find when that change occurred, but we should match whatever is in the docs
https://www.django-rest-framework.org/api-guide/filtering/#djangofilterbackend
=> Update DRF Filtersets fields to lists rather than tuples

dojo/tools/trivy/parser.py, unittests/scans/trivy/license_scheme.json, unittests/tools/test_trivy_parser.py
Trivy allows for license scan and the report will be provided in json format. The changes are made to parse the license report
=> add license parser to trivy scan

dojo/templates/notifications/msteams/engagement_added.tpl, dojo/templates/notifications/msteams/other.tpl, dojo/templates/notifications/msteams/product_added.tpl, dojo/templates/notifications/msteams/product_type_added.tpl, dojo/templates/notifications/msteams/report_created.tpl, dojo/templates/notifications/msteams/risk_acceptance_expiration.tpl, dojo/templates/notifications/msteams/scan_added.tpl, dojo/templates/notifications/msteams/sla_breach.tpl, dojo/templates/notifications/msteams/test_added.tpl, dojo/templates/notifications/msteams/upcoming_engagement.tpl, dojo/templates/notifications/msteams/user_mentioned.tpl
Fix for MS Teams notifications template.
Display tags were added for Slack notifications, but were missed out for Teams.
labels: `bugfix` `msteams` `notifications`
=> msteams notifications template fix

dojo/engagement/views.py, dojo/forms.py
A couple months ago import_scan changed its default behavior for closing findings. The `close_old_findings` flag now only covers the same engagement. If you want it to cover all findings in the same product you have to send a second flag along with the first, `close_old_findings_product_scope`. The Import Scan page does not reflect this change, and currently only supports closing findings within the same engagement. 
This PR adds a check box for 'close_old_findings_product_scope' to the Import Scan page. Instead of requiring both check boxes to be selected, which could be confusing, the checkboxes are presented as two separate choices. One to close old findings at the engagement scope, and one for closing old findings at the product scope. The backend code ensures both …
=> bugfix - Add support for current close old findings behavior to UI

dojo/jira_link/helper.py
Jira does not allow spaces in their tags. Remove the spaces in tags coming from dojo before they are pushed out to jira
=> Strip spaces from tags before pushing to jira

dojo/tasks.py, dojo/utils.py
We get this error with SLA computation when a FindingGroup doesn't have a JIRA:
[03/May/2023 07:30:00] INFO [dojo.utils:1796] About to process findings for SLA notifications.
[03/May/2023 07:30:03] ERROR [dojo.tasks:157] An unexpected error was thrown calling the SLA code: Finding_Group has no jira_issue.
=> SLA computation throws exception when a FindingGroup doesn't have a JIRA

docs/content/en/integrations/parsers/file/github_vulnerability.md, dojo/tools/github_vulnerability/parser.py, unittests/scans/github_vulnerability/github-1-vuln-repo-dependabot-link.json, unittests/tools/test_github_vulnerability_parser.py
It's currently quite unusable to view dependabot alerts because they don't give a direct link into the Github platform, to maybe triage things there, get more details... view the PR attached etc...
Funny thing is, Github doesn't return a direct link to the alert, so you must either return the repo URL, or at least the full name with the org/owner, and build from there.
Another thing that I can't fix unfortunately: directly linking to the file in Github is hard, because yet again, Github's API isn't telling you the branch where the issue was detected. Dependabot opens PRs properly though, so maybe you could introspect the PR it has opened and find out the target branch... if someone reads this and wants to bother
=> [Github parser] Parse dependabot alert number and add link in description

dojo/product/views.py, dojo/templates/notifications/alert/sla_breach.tpl, dojo/templates/notifications/slack/sla_breach.tpl, dojo/utils.py
If you delete a product with slack alerting enabled, you get a bad link like:
The product "Test Product2" was deleted by coheigea
More information on this event can be found here: http://localhost:8080http://localhost:8080/product
I changed it just to link to the main product page. I also added in the product name to the SLA breach alert, as I think it's useful to see this information.
Tested both with slack.
=> Replace incorrect link in slack alert for product deletion + add product to SLA breach alert

dojo/importers/reimporter/reimporter.py, unittests/test_import_reimport.py
When parsing a mitigated finding in the re-importer that is already mitigated, it doesn't add it to the list of unchanged items, so it always tries to close the old finding (which causes a JIRA ping if JIRA is enabled for the finding). There is a second bug fixed where newly mitigated findings aren't added to the mitigated list. 
Tested it manually. I fixed the test logic which was incorrect IMO, reimporting a newly mitigated finding should show an issue being closed and not remaining "untouched".
=> Fix bug with mitigated findings

dojo/jira_link/helper.py
If a team resolve a JIRA upstream of DefectDojo, and if the JIRA workflow is such that a JIRA can't be edited when in a resolved/rejected state, then DefectDojo alerts when trying to resolve the Finding if push_to_jira is enabled. Instead we should just log the error, if the upstream JIRA is already resolved/rejected then an alert is not required.
Tested an alert does not happen any more in this scenario.
=> Only alert on a JIRA error where the JIRA is active

README.md, dc-build.sh, dc-down.sh, dc-stop.sh, dc-unittest.sh, dc-up-d.sh, dc-up.sh, docs/content/en/getting_started/architecture.md, docs/content/en/getting_started/running-in-production.md, docs/content/en/getting_started/upgrading.md
MySQL supports case insensitivity out of the box which makes searches and exact match operations more challenging/ineffective. We have been talking about not supporting MySQL in v3 already as well. This is a good first step to test the waters
[sc-963]
=> Make PostgreSQL database the default for containerized deploys

dojo/urls.py
fixes a bug introduced from #7865 that caused the `api-token-auth` endpoint to disappear from the swagger spec. The endpoint is still functional in all versions, just is not easy to find right now
=> Add the "api-token-auth" endpoint back into the swagger spec

dojo/tools/sarif/parser.py, unittests/tools/test_sarif_parser.py
This pull request introduces a new feature to the SARIF parser in DefectDojo. The feature enhances the parser's functionality by extracting tags from both the rules and results sections of the SARIF file. This addition allows users to have a more comprehensive understanding of the findings and better categorize them based on the extracted tags.
- unittests/tools/test_sarif_parser.py 
Updated the parser's unit tests to include a new test case, test_tags_from_result_properties, which verifies the correct extraction and assignment of tags to the findings.
no needed
**Checklist**
=> Add TAGS from SARIF rules and results to findings

dojo/decorators.py, dojo/user/views.py
I noticed that users are getting 403 errors on the login page if any users are hitting it at the same time via VPN
=> Update rate limiting on the login page to only block on unsafe requests

readme-docs/DOCKER.md
Just a typo fix.
The container name is "django-defectdojo-uwsgi-1" instead of "django-defectdojo_uwsgi_1". Probably it isn't just for me, right?
=> Fix container name in DOCKER.md

dojo/finding/views.py, dojo/jira_link/views.py
Sometimes when working with the jira integration, there are instances of a finding being pushed to jira when modifying the status of a finding via the edit page, but not when using the open/close/review buttons. This is confusing and creates disparity.
Here is what this PR does
[sc-1040]
=> Unify push to jira logic for finding/groups  review/open/close

docs/content/en/usage/permissions.md, dojo/authorization/roles_permissions.py
In some cases, if it useful if `API_Importer` can create Engagement - If developer would like to have each build of software in separated Engagement.
Plus, change from https://github.com/DefectDojo/django-DefectDojo/pull/5324 has not been covered in documentation until now.
-
Updated
**Checklist**
=> Add Permissions.Engagement_Add to API_Importer

dojo/test/views.py
This will fix #7015, by keeping request/response fields when a new finding is created from a template.
this fixes #7015 
Please update any documentation when needed in the [documentation …
=> Update views.py to fix #7015

dojo/tools/generic/parser.py, unittests/tools/test_generic_parser.py
This will make lookup (much) faster, since sets are data structures dedicated to such operations.
This PR is a prerequisite to another PR (I need to update the allowed fields and wanted to land this change before that.
**Checklist**
=> Use sets for required & allowed fields

dojo/tools/detect_secrets/parser.py
There was an error when importing not audited reports on Detect Secrets that marked as inactive secrets which haven't "is_secret" field.
=> Fix Detect Secrets parser when .baseline is not audited

docs/content/en/integrations/social-authentication.md, dojo/pipeline.py
When playing around with the azure group mapping, I found that there was an object ID in the groups response that did not match any resource I had in tenant. I tried deleting the application and all groups, and still the same object ID was blocking  my groups from being created in dojo. 
This change updates the exception handling to raise on each error, and then continue attempting the operation for the rest of the groups in the list. This way, if one apple gets in the bunch, the feature is still useful
Also had a very hard time figuring out what needed to be set on the Azure side to make this process work. Added some docs to clear this up for future folks
[sc-1078]
=> Azure Group Mapping: Make group mapping less atomic

dojo/tools/checkmarx/parser.py, unittests/scans/checkmarx/multiple_findings.json
Checkmarx results may contain references to other result types even if they are not present. For example:
```
"scanResults": {
"sast": {
...
},
"sca": null,
"kics": null
}
```
Causes an error because the null value was not checked to be valid before it was attempted to be read
=> Checkmarx: Add safeguards for "null" values in result types

dojo/importers/reimporter/utils.py
When Engagements are created from `auto_create_context`, they come in with no status.
=> Set Engagement status created from `auto_create_context`

docs/content/en/integrations/parsers/file/dependency_check.md, dojo/tools/dependency_check/parser.py, unittests/tools/test_dependency_check_parser.py
The Dependency Check parser currently tags suppressed findings but don't mitigate them. The documentation says they are marked as inactive. But this is not true if you import them via API and the active=true flag.
Suppressing a finding in Dependency Check is usually because these are false positives. So they should be marked as mitigated and not as inactive. When you looking into the code this was also the intended behaviour for the parser (see https://owasp.slack.com/archives/C2P5BA8MN/p1683267640152279).
I have added assertions for the mitigation.
I have change the documentation: "Suppressed vulnerabilities are marked as mitigated."
=> Dependency Check parser mark suppressed findings as mitigated

dojo/tools/tenable/csv_format.py, dojo/tools/tenable/xml_format.py
Went through the old Nessus/NessusWas parsers to look for any deviations between the original parsers and the consolidated parser. Here is what I found:
- CSV
- Endpoint related fields may have been getting set to ""(empty string) in cases of rows being empty
- Removed the duplicated code of adding plugin output to description
- Added default "Info" severity in case one is not found in the report 
- Reverted the dupe key calculation to what was originally in place
- XML
- Returned the check for `NessusClientData_v2` data (though I believe it may be very outdated now)
- Added some light formatting to the description output
[sc-1089]
=> Tenable parser cleanups and improvements

dojo/importers/importer/importer.py
If "active" is not specified in the importer you get a TypeError:
django-defectdojo-uwsgi-1         |     if hash_code["hash_code"] == finding["hash_code"]:
django-defectdojo-uwsgi-1         |        ~~~~~~~~~^^^^^^^^^^^^^
django-defectdojo-uwsgi-1         | TypeError: string indices must be integers, not 'str'
Tested the fix works correctly.
=> Fixing error in importer if active is not specified

dojo/finding/views.py, dojo/reports/views.py
`HttpResponseForbidden` bypass our 403 error page and force the browser to produce scary things
=> Replace `HttpResponseForbidden` with `PermissionDenied`

dojo/finding/views.py, dojo/forms.py, tests/finding_test.py, tests/user_test.py
When requesting reviews on findings, it is possible to select users with read permission that will not have access to actually provide the review. This fix limits the users that can provide reviews to those with at least write access to a given finding. 
In a system with many users, it is pretty annoying to have to select all of them for each review, so I added a checkbox to add all eligible reviews.
=> Request Review improvements

dojo/engagement/views.py, dojo/reports/views.py, dojo/user/validators.py
1. fix some `noqa W605`
2. DeprecationWarning:
```python
/app/dojo/reports/views.py:747: DeprecationWarning: invalid escape sequence '\?'
path_items = list(filter(None, re.split('/|\?', url))) # noqa W605
```
=> Fix DeprecationWarning and some "noqa W605"

dojo/tools/gitlab_sast/parser.py
When importing a gitlab sast report you end up with something like.
Gitlab sast data model for location looks like this:
```
"location": {
"type": "object",
"description": "Identifies the vulnerability's location.",
"properties": {
"file": {
"type": "string",
"description": "Path to the file where the vulnerability is located."
},
"start_line": {
"type": "number",
"description": "The first line of the code affected by the vulnerability."
},
"end_line": {
"type": "number",
"description": "The last line of the code affected by the vulnerability."
},
"class": {
"type": "string",
"description": "Provides the name of the class where the vulnerability is located."
},
"method": {
"type": "string",
"description": "Provides the name of the method where the vulnerability is …
```
=> fix: dont create sast object when nothing given

dojo/settings/settings.dist.py
This makes the SameSite attribute configurable via environment variables for the Session and CSRF cookie - default value is 'Lax' 
Tested default value and setting the value to 'Strict' in a local environment manually
=> Make SameSite attribute configurable for Session / CSRF Cookie

dojo/models.py, dojo/tools/veracode_sca/parser.py, unittests/tools/test_veracode_parser.py, unittests/tools/test_veracode_sca_parser.py
The sla_deadline function doesn't work with mitigated findings, as it just applies sla days remaining to the current date, instead of the mitigated date.
Also I added a mitigated date for the Veracode SCA parser when findings are mitigated, as the date isn't contained in the JSON.
New tests added in PR.
=> sla_deadline doesn't work with mitigated findings

dojo/importers/reimporter/utils.py
For some reason, I have seen cases where the product exists, but is not fetched by the `get_target_product_if_exists` function, but it does exist. 
Updating the `create` function to `get_or_create` makes this process safer across the board
=> Fix occurrence where product exists, but cannot be found

Dockerfile.django-alpine, Dockerfile.django-debian
Avoid warning
```python
WARNINGS:
?: (staticfiles.W004) The directory '/app/components/node_modules' in the STATICFILES_DIRS setting does not exist.
```
=> Fix: STATICFILES_DIRS warning

docs/content/en/getting_started/upgrading.md, dojo/filters.py
PR Fixes a few issues:
- Rename product tag filters. The naming convention was different from all the other tag related queries.
- Add release notes for 2.25.x indicating potentially breaking changes
- Fix all instances of `seperated` -> `separated` in the filters
=> Update naming convention for product tags in related objects

dojo/test/views.py
Since PR #7470 a few months ago, Verified is set to false by default on a finding.
It makes perfectly sense when importing from a scanner, as “Verified” should mean that it has been checked by a human like it was explained in the previous PR.
However, as a side effect, we also noticed that when you add a finding using the web interface, the Verified checkbox is set to false. I think it should be true in this case, because if you add a finding manually, it actually had been checked by a human.
The goal of this PR is just to set the checkbox Active value to true when a Finding is added from the web UI, keeping the default to false in other cases.
=> Verified defaults to true when adding a Finding from web UI

dojo/apps.py, dojo/test/signals.py
When updating the test type of a test, all of the findings under that test will now have an outdated `found_by` value. This column is shown in all of the finding lists, so it is important that it is accurate.
=> Add signal to update Finding `found_by` column

dojo/tools/gitleaks/parser.py, dojo/tools/gosec/parser.py, dojo/tools/govulncheck/parser.py, dojo/tools/h1/parser.py, dojo/tools/hadolint/parser.py, dojo/tools/harbor_vulnerability/parser.py, dojo/tools/horusec/parser.py
Update files with PEP8 standars in folders dojo/tools/
dojo/tools/gitleaks
dojo/tools/gosec
dojo/tools/govulncheck
dojo/tools/h1
dojo/tools/harbor_vulnerability
dojo/tools/horusec
=> Update files with PEP8 standards in folder dojo/tools #003

dojo/static/dojo/css/dojo.css, dojo/templates/base.html
A known issue with the side nav-bar on various display sizes. Prevents users from selecting the bottom configuration options.
**Before:**
**After:**
=> Fixed side navbar cutoff issue

Dockerfile.integration-tests-debian
High level is unit tests are trying to use chrome 115 as it the latest, but the way to fetch the matching chromedriver changed with chrome version 115. We use a pypi package to fetch the driver and there is an issue open for fixing this: https://github.com/yeongbin-jo/python-chromedriver-autoinstaller/issues/47
The motivation for the path change is to make things more unified, so it might be a good time to get on the right track
[sc-1556]
=> Update chromedriver fetching mechanism

dojo/tools/api_sonarqube/api_client.py, dojo/tools/api_sonarqube/importer.py
Description
This PR fixes #8379 by extending the required api calls with the "organization" parameter, which is required for Sonarcloud imports.
Test results
works as expected. Doesn't solve the issue with empty return of get_issue but this doesn't seem to have any effect at all.
=> fix: Sonarqube re-upload #8379

requirements.txt
Reverts DefectDojo/django-DefectDojo#8466
=> Revert "Bump debugpy from 1.6.7 to 1.6.8"

helm/defectdojo/templates/secret-postgresql-ha.yaml, unittests/tools/test_arachni_parser.py
Fixing a couple typos I've encountered:
* `secret-postgresql-ha.yaml`: `repmgrpassword` ➡️  `repmgrPassword`
* `test_arachni_parser.py`: `TestAquaParser` ➡️  `TestArachniParser`
N/A
N/A
=> Fixing some minor typos

docs/content/en/getting_started/upgrading.md, dojo/templates/base.html, dojo/urls.py
The package used to generate the OpenAPIv2 swagger page has a note pointing folks to [def-spectacular](https://github.com/tfranzel/drf-spectacular) which we are already using for the OpenAPIv3 swagger page
The OAPI2 page should be deprecated for the 2.25.0 release with a planned removal in 2.30.0 (Jan2024)
=> Deprecation: OpenAPI 2.0 Documentation page

dojo/settings/settings.dist.py, dojo/urls.py
=> Add drf-spectacular preprocessing hooks to keep a rigid definition of rendered API endpoints

dojo/importers/importer/importer.py, dojo/importers/utils.py
fixes #970 (removes the warnings in the logs anyways)
[sc-1952]
=> Remove naive format warnings during import

dojo/filters.py, dojo/models.py
New filter field to query for object that `Has tags`. Can be used for Products, Engagements, Tests, Findings and Endpoints (API filter fields also added). Selects objects that do not have any tags at all (i.e. untagged objects).
**Example of Has tags for Products**
_All Products:_
_Products filtered by Has tags:_
New filter field to query for objects that are `Outside of SLA`. Can be used for Products and Findings (API filter fields also added). Selects objects that violate their SLA. For products, this is determined by if any of the findings within its engagements violate SLA. For findings, this is determined by if any of the findings themselves violate SLA.
**Example of Outside of SLA for Products**
_All Products:_
_Products filtered that are Outside of SLA:_
=> addition of has_tags and product/finding sla filters

dojo/engagement/views.py
During an import, the Environment will default to "Development", reducing clicks for the user
=> Set a default environment for tests in DefectDojo

helm/defectdojo/templates/configmap.yaml, helm/defectdojo/values.yaml
I've updated the values.yaml file and the configmap template in the helm chart to be able to set a different port for external redis. It was hardcoded to the default 6379.
tested it with empty values.yaml (no external redis), values.yaml with an external redis without specifying port (defaulted to 6379) and with port 6380 (azure cache for redis ssl port).
documentation added inline to values.yaml
**Checklist**
=> updated helm chart to allow setting a different port for external redis

dojo/endpoint/views.py, dojo/filters.py, dojo/importers/utils.py, dojo/models.py, dojo/templates/dojo/endpoints.html, unittests/test_endpoint_model.py
This PR fixes a handful of issues observed with the endpoint model and it's views
Deleting a product type with two products that have endpoints with matching contents (protocol + host + port + path + query) result in a mixup of which endpoint belongs where:
This is the error produced:
```
update or delete on table "dojo_product" violates foreign key constraint "dojo_endpoint_product_id_b86dc143_fk_dojo_product_id" on table "dojo_endpoint"
DETAIL:  Key (id)=(10) is still referenced from table "dojo_endpoint".
```
This issue originates from the endpoint equality method. An endpoint was deemed equal to another if the string representation was the same, but failed to take into account that the endpoints could be from different products. The solution there is to incorporate product matching if …
=> Endpoint model/view corrections

dojo/templates/dojo/alerts.html, dojo/templates/dojo/endpoints.html, dojo/templates/dojo/findings_list_snippet.html, dojo/templates/dojo/snippets/endpoints.html, dojo/templates/dojo/view_test.html
This bugfix makes visible the checkboxes 
Now the windows looks like this:
=> Fix checkbox disappear findings (windows resize)

dojo/product/urls.py, dojo/product/views.py, dojo/static/dojo/css/dojo.css, dojo/static/dojo/js/metrics.js, dojo/templates/dojo/product_metrics.html, dojo/utils.py
Added a new plot to the Product Detailed Metrics section that displays the total count of open findings for all severities.
This graph data is calculated by (for one severity):
1. Getting the count of all findings for the given Product 90 days prior to the current date
2. Iterating over each day to get the counts for total number of findings open and total number of findings mitigated
3. Adding the total number of findings opened to the running total count
4. Subtracting the total number of findings mitigated to the running total count
_Example of graph with Finding data:_
_Example of graph without any Finding data:_
=> added open findings burndown for product metrics

dojo/tools/jfrog_xray_api_summary_artifact/parser.py, unittests/scans/jfrog_xray_api_summary_artifact/malformed_cvssv3.json, unittests/tools/test_jfrog_xray_api_summary_artifact_parser.py
JFrog Xray scan results sometimes have malformed CVSSv3 scores. The current implementation of the parser fails completely when a malformed CVSS v3 score is given to it what results in no findings are imported at all.
Tested that a malformed CVSS v3 score will lead to an empty cvssv3 field in the single finding but not break the whole parsing of the file.
not needed
**Checklist**
=> Catch malformed CVSSv3 bug in JFrog Xray API Summary parser

dojo/tools/whispers/parser.py
Field type mismatch is preventing results from being imported correctly.
See details:
* https://github.com/DefectDojo/django-DefectDojo/issues/7097
* https://github.com/adeptex/whispers/issues/100
This bugfix resolves the issue.
=> [bugfix] Update whispers parser references field type

Dockerfile.integration-tests-debian, dojo/tools/veracode/json_parser.py
From a CVSS perspective, [Veracode offers two levels of informational based findings](https://docs.veracode.com/r/review_severity_exploitability#veracode-finding-severities) each with a CVSS score of 0.0
This PR adds another level of information mapping to accommodate these other informational findings
=> Veracode: Add additional severity mappings for other informational findings

dojo/test/views.py
One old leftover was raising an error if System_Settings hadn't been initiated.
The line was created on https://github.com/DefectDojo/django-DefectDojo/commit/2da3b3e4d5278cdf6b40d11b9a03d1f72dc4bbe7
But haven't been removed https://github.com/DefectDojo/django-DefectDojo/pull/7889
Fix another part of issue #8636
=> Fix: missing System_Settings raised error

dojo/tools/anchorectl_policies/parser.py
This pull request fixes a bug. This bug occurs when uploading an Anchore policies report with an empty details. Exemple : 
```
[
{
"detail": null,
"digest": "sha256:2207ab33cd91cf042751d355536b612f4123497befe67041f0aee1f522b4c26f",
"finalAction": "go",
"finalActionReason": "policy_evaluation",
"lastEvaluation": "2019-08-07T19:27:03Z",
"policyId": "2c53a13c-1765-11e8-82ef-23527761d060",
"status": "pass",
"tag": "<image_tag>"
}
]
```
This pull request add a verification inside the file 'dojo/tools/anchorectl_policies/parser.py' to not iterate thought the list 'image['detail']' if it's  None.
**Checklist**
=> Fix: anchorectl_policies crash when 'detail' is null 

dojo/group/views.py
I optimize db calls for page /group/<id>
Now the number of queries to the database does not depend on the number of existing groups.
=> Optimize group list

docker/setEnv.sh
Wrong processing of `symlink` variable.
Discovered in https://github.com/DefectDojo/django-DefectDojo/pull/8731#issuecomment-1737175771
=> setEnv: Fix symlink processing

dojo/filters.py
Closes #8673
This pull request introduces a new feature that allows users to filter by product lifecycle stages. This enhancement was made in response to issue #8673.
Changes include:
1. the addition of a filtering dropdown "Product lifecycle" in the following screens:
a. Findings,
b. Engagements,
c. Engagements By Product,
3. and a `product_lifecycle` parameter in the `/findings` API, which takes a comma-separated string of product lifecycles.
Screenshot of the filter in Findings:
Filtering in the API could be done in several ways. If it should rather receive several `product_lifecycle=` parameters, then please let me know.
Changes were tested manually. The dropdowns work properly on the three screens, and the API parameter works correctly when called …
=> add filtering on product lifecycles

Dockerfile.integration-tests-debian
This change temporarily pins the versions of chrome and the chrome webdriver. The issue is that there is no guarantee that the version of chrome that is installed has an associated version for webdriver. The long-term solution would be to use one of the selenium browser manager tools, but we do need to unblock our gate and this appears to be the least painful option.
N/A
=> Temporarily pin the versions of chrome and chrome webdriver

Dockerfile.integration-tests-debian
Description
This change temporarily pins the versions of chrome and the chrome webdriver. The issue is that there is no guarantee that the version of chrome that is installed has an associated version for webdriver. The long-term solution would be to use one of the selenium browser manager tools, but we do need to unblock our gate and this appears to be the least painful option.
Test results
N/A
=> Temporarily pin versions of chrome and chrome webdriver

dojo/tools/govulncheck/parser.py, unittests/scans/govulncheck/many_vulns_new_version.json, unittests/tools/test_govulncheck_parser.py
[sc-1976]
New govulncheck format can be parsed with this update. Atest was created and the example file is being tested there.
=> Update govulncheck parser to new format

docs/content/en/integrations/parsers/file/burp.md, docs/content/en/integrations/parsers/file/burp_enterprise.md
Adding Parser documentation for Burp Scan & Burp Enterprise.  I'm not sure how to make a good example of acceptable HTML for the Burp-Enterprise Parser, and I don't know how valuable that would be for debugging anyway.  XML format is much easier to understand and correct errors with.
=> add parser documentation for burp scan & burp-enterprise

docs/content/en/usage/features.md
Small typo -> broken link
Mentioned in https://owasp.slack.com/archives/C2P5BA8MN/p1695843977321899
=> Docs: Fix "data model" link in Features

dojo/tools/jfrog_xray_api_summary_artifact/parser.py
Importing findings without CVEs throws error "IndexError: list index out of range"
Tested it locally and import no longer fails.
=> Check for empty cves array in JFrog Xray API Summary Artifact Parser

Dockerfile.integration-tests-debian, docker/entrypoint-integration-tests.sh, docker/install_chrome_dependencies.py, tests/base_test_class.py
This PR is a follow-up to #8755. There is no guarantee that the version of Chrome installed via apt has a valid chromedriver version. apt also does not keep previous versions of Chrome available for installation. To ensure that we always get a valid pairing of Chrome and chromedriver, this change instead targets the latest stable version of Chrome and chromedriver.
TBD
=> Browser tests should use the latest Chrome stable release

dojo/tools/awssecurityhub/parser.py, unittests/scans/awssecurityhub/README.md, unittests/scans/awssecurityhub/inspector_ecr.json, unittests/tools/test_awssecurityhub_parser.py
This merge request changes the AWS Security Hub parser to include more vulnerability details.
The first commit includes the following changes:
* Capturing related vulnerabilities from `RelatedVulnerabilities`. This follows up after discussion in #5904, where possibility of adding more vulnerability identifiers was implemented. Currently, the Grype report parser already makes use of this. The [documentation](https://docs.aws.amazon.com/inspector/v2/APIReference/API_Vulnerability.html) doesn't precisely explain this field, but from what I observe, it's used for listing other advisories related to the vulnerability (so "aliases", according to the Dependency-Track terminology).
* Capturing "vendor URL" from the vulnerability details and appending it to the references list.
* …
=> [ENHANCEMENT] AWS Security Hub parser: include more vulnerability details

readme-docs/CONTRIBUTING.md
Standards are easier to follow when they are documented. This commit is an initial start to properly set expectations about the code review process so that both contributors and reviewers feel that their opinions have been respected.
No code was changed
=> Adds a code review process section to the contributors guide

README.md, dc-build.sh, dc-down.sh, dc-stop.sh, dc-unittest.sh, dc-up-d.sh, dc-up.sh, docker-compose.yml, docker/docker-compose-check.sh, docker/entrypoint-initializer.sh, docker/setEnv.sh
⚠️ Note on feature completeness ⚠️
From July 2023 Compose V1 stopped receiving updates. It's also no longer available in new releases of Docker Desktop. Compose V2 is included with all currently supported versions of Docker Desktop. For more information, see [Migrate to Compose V2](https://docs.docker.com/compose/migrate).
Compose V2, which was first released in 2020, is included with all currently supported versions of Docker Desktop. It offers an improved CLI experience, improved build performance with BuildKit, and continued new-feature development.
Description
How do I switch to Compose V2?
The easiest and recommended way is to make sure you have the latest version of Docker Desktop, which bundles the Docker Engine and Docker CLI platform including Compose V2. With Docker Desktop, …
=> Migrate to Compose V2 for dev branch

dojo/endpoint/views.py, dojo/finding/views.py, dojo/test/views.py
I've discovered that for notifications of findings creation, findings reopening and endpoint deletion, the url indicated contains 2 times the first part of the URL. 
Example of malformed URL : `https://defectdojo.mydomain.frhttps://defectdojo.mydomain.fr/finding/99`
The problem is apparently linked to the use of the "request.build_absolute_uri" function.
I went to investigate how the URL contained in the notifications that don't have this bug was constructed and modified the ones that do in the same way.
I turned on Slack notifications before change to make sure of the problem.
Made changes and replayed notifications containing a buggy URL. Problem fixed.
=> Fix findings and endpoints URLs in notifications

dojo/tools/whispers/parser.py, unittests/scans/whispers/whispers_one_vul_v2.2.json, unittests/tools/test_whispers_parser.py
Hey team, this is a bugfix for importing results from a newer version of a currently implemented parser.
Whispers reports versions up to 2.1.5 use the following severity levels: `BLOCKER`, `CRITICAL`, `MAJOR`, `MINOR`, `INFO`
Whispers reports versions 2.2.0+ use a different nomenclature: `Critical`, `High`, `Medium`, `Low`, `Info`
When importing new Whispers 2.2 reports into DefectDojo, everything comes out as `Info` due to:
https://github.com/DefectDojo/django-DefectDojo/blob/584371d8dd51404646936097f9dc6c5b843663c4/dojo/tools/whispers/parser.py#L58
This happens because `SEVERITY_MAP` includes only old severity names:
https://github.com/DefectDojo/django-DefectDojo/blob/584371d8dd51404646936097f9dc6c5b843663c4/dojo/tools/whispers/parser.py#L11-L17
The present bugfix adds …
=> [bugfix] Whispers 2.2 report importing support

dojo/engagement/urls.py, dojo/engagement/views.py, dojo/product/urls.py
[sc-2909]
Changed function views Import and reimport to class based views
=> changed function based views to class based views

dojo/models.py, dojo/reports/views.py, dojo/templates/dojo/endpoint_pdf_report.html, dojo/templates/dojo/engagement_pdf_report.html, dojo/templates/dojo/finding_pdf_report.html, dojo/templates/dojo/product_endpoint_pdf_report.html, dojo/templates/dojo/product_pdf_report.html, dojo/templates/dojo/product_type_pdf_report.html, dojo/templates/dojo/test_pdf_report.html
- Removed some fields in HTML reports that does not have any contents to avoid extraneous sections for a given finding
- Removed the FQDN from HTML reports as it often exposed proxy ports and prevented images from being rendered in the report
=> Reporting: Exclude empty fields from report + correct host for HTML reports

dojo/filters.py
This merge request introduces a new feature to the Report Builder.
It enables users to filter findings based on their SLA violation status.
The main use case is to generate reports covering only SLA breaches.
Use cases tested manually:
- no value chosen: displays all findings
- "Any" chosen: displays all findings and the field is reset
- "False" and "True": display only a proper subset of findings
Update not needed for this minor improvement.
=> [ENHANCEMENT] Add Finding Violates SLA filtering to Report Builder
