components/package.json, dojo/__init__.py, dojo/forms.py, dojo/jira_link/helper.py, dojo/jira_link/views.py, dojo/unittests/test_jira_config_product.py, dojo/unittests/tools/test_safety_parser.py, helm/defectdojo/Chart.yaml, setup.py
Reverts DefectDojo/django-DefectDojo#4232
=> Revert "Release: Merge release into master from: release/1.14.1"

dojo/templates/dojo/findings_list_snippet.html
add message to bulk edit finding groups: clarify it's only available per test
=> finding groups: clarify it's only available per test

README.md
and mark setup.bash as EOL'ed.
=> Push godojo in the supported install in README

WRAPPERS.md
The one in this organization might be updated this year to include the securecodebox and build an image.
=> SecureCodeBox - update java wrapper doc

README.md
Rightfully on `master`, clean up the stuff that no longer are correct.
=> Remove swag rewards and paypal

dojo/tools/npm_audit/parser.py
=> update npm audit parser description

dojo/tools/openvas_csv/parser.py, dojo/unittests/tools/test_openvas_csv_parser.py
=> OpenVAS parser: add port and protocol implementation

dojo/tools/burp_enterprise/parser.py
One line patch that fixes #4287
=> [Burp Entreprise parser] fixes HTML read issue #4287

.github/workflows/test-helm-chart.yml
Should fix #4176
On master to take effect.
=> Helm chart linting - pick target branch

dojo/filters.py
=> filters: file_path partial matching instead of exact match

docs/content/integrations/import.md, dojo/tools/cred_scan/parser.py, dojo/unittests/scans/cred_scan/cred_scan_many_vuln.csv, dojo/unittests/scans/cred_scan/cred_scan_no_vuln.csv, dojo/unittests/scans/cred_scan/cred_scan_one_vuln.csv, dojo/unittests/tools/test_cred_scan_parser.py
Add CredScan parser
https://secdevtools.azurewebsites.net/helpcredscan.html
=> Add Microsoft CredScan parser

docker/entrypoint-celery.sh
worker and beat have their own entrypoint
=> Delete unused entrypoint-celery.sh

dojo/tools/cred_scan/parser.py, dojo/unittests/tools/test_cred_scan_parser.py
Fixes from #4299 suggest by @damiencarol after it had already been merged
=> Include suggested CredScan fixes from #4299

docker/entrypoint-integration-tests.sh, dojo/fixtures/product_type.json, dojo/templates/dojo/finding_related_actions.html, dojo/templates/dojo/snippets/endpoints.html, dojo/templates/dojo/view_product_details.html, dojo/templates/dojo/view_product_type.html, dojo/templates/dojo/view_user.html, tests/base_test_class.py, tests/product_member_test.py, tests/product_type_member_test.py, tests/user_test.py
Integrationtests to test the happy path for viewing, adding, editing and deleting product members and product type members.
=> Authorization V2: Integrationtests for management of product members and product type members

dojo/templates/dojo/rules.html
=> Add beta/unsupported warning for rules framework

dojo/authorization/roles_permissions.py
=> Rename role for API Importer

docs/config.toml, docs/content/basics/permissions.md, docs/content/basics/workflows.md, dojo/templates/dojo/view_product_details.html, dojo/templates/dojo/view_product_type.html, dojo/templates/dojo/view_user.html
This PR adds documentation for authorization V2. Please merge #4346 first because of possible conflicts.
=> Documentation for authorization V2

dojo/unittests/scans/generic/generic_report1.csv, dojo/unittests/tools/test_generic_parser.py
Add unit tests for generic parser.
=> [Generic parser] Add more unit tests

dojo/engagement/views.py, dojo/importers/utils.py
=> Duplicate scanner name fix #4275

dojo/tools/retirejs/parser.py, dojo/unittests/scans/retirejs/latest.json, dojo/unittests/tools/test_retirejs_parser.py
=> [RetireJS parser] fix JSON parsing error

dojo/models.py
=> Bulk risk acceptance filter remove need for Verified status

nginx/nginx_TLS.conf
Added media path in nginx_TLS.conf file
=> Added media path

dojo/templates/dojo/view_product_details.html, dojo/templates/dojo/view_product_type.html, dojo/templates/dojo/view_user.html
admin add "prodct (type)", no "member"
=> AuthV2: Change wording (admin set user perms)

dojo/tools/qualys/parser.py, dojo/unittests/scans/qualys/Qualys_Sample_Report.xml, dojo/unittests/tools/test_qualys_parser.py
Qualys has added a cvss vector to some of the cvss field. The parser is now able to handle this. Solves issue #4319.
----
=> [Qualys parser] fix parsing issues when cvss field contains a vector

.github/workflows/k8s-testing.yml
k8s gha: Fix logging check application step
=> k8s gha: Fix logging check application step

.github/workflows/new-release-tag-docker.yml
=> Fix helm chart push

dojo/tools/nessus/parser.py
Reverts DefectDojo/django-DefectDojo#4397
=> Revert "Recognize .nessus file names"

dojo/tools/nessus/parser.py
Re-opening a PR, see #4397
fyi @pburkholder
=> Recognize .nessus file names by @pburkholder

.github/workflows/gh-pages.yml, docs/package-lock.json
Building the documentation has been tested locally using https://github.com/nektos/act. Very good chance it works now.
=> GitHub pages action changed after local tests

docs/content/en/running/upgrading.md
initial docs describing the big and somewhat breaking changes in v2.0.0
=> v2.0.0: Add initial docs

dojo/tools/nmap/parser.py, dojo/unittests/scans/nmap/issue4406.xml, dojo/unittests/tools/test_nmap_parser.py
=> [Nmap parser] Fixes multiple identifiers bug

dojo/templates/dojo/finding_related_row.html
Fixes https://github.com/DefectDojo/django-DefectDojo/issues/4372
=> Fix duplicate cluster original verbiage

dojo/tools/risk_recon/parser.py, dojo/unittests/tools/test_risk_recon_parser.py
=> [Risk Recon parser] Add unique_id and date

dojo/search/views.py
re-enable generic/watson search results
=> re-enable generic/watson search results

.github/workflows/test-helm-chart.yml
All the k8s installations already run in their matrix #4476
=> master to dev: Remove actuall ct install (#4476)

dojo/unittests/test_deduplication_logic.py, dojo/unittests/test_jira_config_engagement.py, dojo/unittests/test_jira_import_and_pushing_api.py, dojo/unittests/test_jira_webhook.py, dojo/unittests/test_rest_framework.py, dojo/unittests/test_search_parser.py
remove or comment out print statements in unit tests
=> remove or comment out print statements

docs/content/en/integrations/import.md, dojo/tools/detect_secrets/parser.py, dojo/unittests/scans/detect_secrets/many_findings.json, dojo/unittests/scans/detect_secrets/no_findings.json, dojo/unittests/tools/test_detect_secrets_parser.py
detect-secrets is an aptly named module for (surprise, surprise) detecting secrets within a code base.
It could be found at: https://github.com/Yelp/detect-secrets
=> add new parser - Detect-secrets

dojo/api_v2/serializers.py, dojo/templates/dojo/profile.html
=> Fixes for 2 bugs for users

dojo/finding/views.py
=> Fix edit finding view to unset duplicate status of a finding

dojo/tools/generic/parser.py, dojo/unittests/scans/generic/generic_report1.json, dojo/unittests/scans/generic/generic_report2.json, dojo/unittests/tools/test_generic_parser.py
Add JSON format for the generic parser
=> [Generic parser] add JSON format

.github/workflows/k8s-testing.yml, helm/defectdojo/Chart.yaml, helm/defectdojo/templates/django-ingress.yaml
Fix of broken Ingress specification
=> Ingress pathtype fix

dojo/settings/settings.dist.py
Resolve #4553 
Now deduplication works fine:
=> Fix aqua deduplication algorithm

dojo/tools/nexpose/parser.py, dojo/unittests/scans/nexpose/many_vulns.xml, dojo/unittests/tools/test_nexpose_parser.py
- Inspired by NMAP parser
- add non-standard service names to nexpose reports
- cleaning service names and tags
=> Nexpose parser: Add "Host Up" + "Open port" and handling non-standard names of services

dojo/db_migrations/0104_endpoint_userinfo_creation.py
move "RunPython(move_fqdn_to_host)"
=> Endpoint: fix migration steps

docs/content/en/contributing/how-to-write-a-parser.md
=> parser guide: show most recent merged PRs first

dojo/models.py, dojo/unittests/test_endpoint_model.py
less strict Endpoint host validation
=> Endpoint: update host validation

dojo/api_v2/views.py
Solution for https://github.com/DefectDojo/django-DefectDojo/issues/4607
=> APIv2: Add DELETE of Product_Type

dojo/forms.py
=> Ignore upper/lower-case for sorting Scan-types

docs/content/en/contributing/how-to-write-a-parser.md
* explain what to do
* talk about `cvss` module
* explain how we use `cvss` module
=> Update how-to-write-a-parser.md to include advice for CVSS data

dojo/templates/dojo/finding_related_row.html
=> show severity of similar finding correctly

dojo/api_v2/permissions.py, dojo/api_v2/views.py, dojo/fixtures/dojo_testdata.json, dojo/unittests/test_metrics_queries.py, dojo/unittests/test_rest_framework.py
This PR implements unit tests for the object-based authorization in the API.
=> Authorization V2 - API unit tests

dojo/fixtures/dojo_testdata.json, dojo/unittests/test_rest_framework.py
https://github.com/DefectDojo/django-DefectDojo/pull/4687 was merged with green tests, but didn't have the rename from Dojo_Group_User to Dojo_Group_Member
=> fix group member rename in tests

dojo/management/commands/print_settings.py
Add Management Command To Easily Display Settings
=> Add Management Command To Easily Display Settings

dojo/unittests/test_apiv2_methods.py
Fix https://github.com/DefectDojo/django-DefectDojo/pull/4711#issuecomment-869002126
=> APIv2: Endpoint methods - fix

dojo/fixtures/test_type.json, dojo/tools/gitlab_container_scan/parser.py, dojo/unittests/scans/gitlab_container_scan/gl-container-scanning-report-0-vuln.json, dojo/unittests/scans/gitlab_container_scan/gl-container-scanning-report-1-vuln.json, dojo/unittests/scans/gitlab_container_scan/gl-container-scanning-report-5-vuln.json, dojo/unittests/tools/test_gitlab_container_scan_parser.py
Adding GitLab container scanning report parser
- https://docs.gitlab.com/ee/user/application_security/container_scanning
=> feat: added GitLab container scanning report parser

.github/workflows/k8s-testing.yml
Downgrade ubuntu to 18.04 in GH k8s actions
=> Downgrade to Ubuntu 18.04

dojo/tools/netsparker/__init__.py, dojo/tools/netsparker/parser.py, dojo/unittests/tools/test_netsparker_parser.py
CWE value was preventing for successful import, fixed with removing several unnecessary code.
=> Fixed CWE integer parsing problem.

dojo/tools/trustwave_fusion_api/parser.py
Fix Trustwave Fusion API parser fails to detect null fields.
@valentijnscholten
=> Fix Trustwave Parser API: properly checking for null data fields

docker/entrypoint-integration-tests.sh, docs/content/en/usage/permissions.md, dojo/group/views.py, dojo/templates/dojo/add_group.html, dojo/templates/dojo/groups.html, dojo/templates/dojo/view_group.html, dojo/templates/dojo/view_product_details.html, dojo/templates/dojo/view_product_type.html, tests/group_test.py, tests/product_group_test.py, tests/product_type_group_test.py
Global roles for for groups were already prepared in the data model. This PR implements the user interface to manage global roles for groups. Additionally there are integration tests for groups and their relationships to Products and Product Types.
=> Authorization V2: Group global roles and integration tests

dojo/templates/base.html
Done as part of the summer intern work on improving our UI testing.  Example PR for the interns.
=> Improved selectors for side menu to allow for better UI testing

dojo/templates/base.html
Walking through an actual PR with the summer interns
=> Added better selector for pop-out add product type

dojo/settings/settings.dist.py
Was implemented 3-4 months ago, got some bugfixes so should be good to enable by default now.
=> Enable import history by default

dojo/settings/settings.dist.py
Implemented some months ago, got some dogfooding from me and bugfixes so should be good to enable by default now.l
=> Enable findings groups by default

dojo/settings/settings.dist.py
The comments for authorization v2 were outdated.
=> AuthV2: comments about default configuration

dojo/fixtures/test_type.json, dojo/tools/gitlab_secret_detection_report/parser.py, dojo/unittests/scans/gitlab_secret_detection_report/gitlab_secret_detection_report_0_vuln.json, dojo/unittests/scans/gitlab_secret_detection_report/gitlab_secret_detection_report_1_vuln.json, dojo/unittests/scans/gitlab_secret_detection_report/gitlab_secret_detection_report_3_vuln.json, dojo/unittests/tools/test_gitlab_secret_detection_report_parser.py
Added a feature to accept GitLab secret detection reports
Ref: https://docs.gitlab.com/ee/user/application_security/secret_detection/
=> feat: added GitLab secret detection report parser

docs/content/en/integrations/import.md
Node JS Scan is not implemented, the PR #1745 was closed without merging it.
=> Remove Node JS Scan from documentation

dojo/forms.py, dojo/templates/dojo/view_tool_product_all.html
=> Fix handling of empty URLs in tool configuration

dojo/pipeline.py
=> Authorization V2: fix Gitlab import

dojo/tools/gitlab_api_fuzzing/parser.py, dojo/tools/gitlab_container_scan/parser.py, dojo/unittests/tools/test_gitlab_container_scan_parser.py
Fix datetime parsing
- better wordings for GitLab API fuzzing + GitLab container scan
=> fix/gitlab-container-datetime: ts parsing

dojo/utils.py
Solution for issue #2835, solved by checking if path exist, create a new one if not.
=> Solution for Issue#2835

dojo/tools/trivy/parser.py, dojo/unittests/scans/trivy/scheme_2_many_vulns.json, dojo/unittests/tools/test_trivy_parser.py
=> Trivy parser - bugfix for initialization of cvssv3

docs/content/en/integrations/import.md, dojo/settings/settings.dist.py, dojo/tools/mobsfscan/parser.py, dojo/unittests/scans/mobsfscan/many_findings.json, dojo/unittests/scans/mobsfscan/no_findings.json, dojo/unittests/tools/test_mobsfscan_parser.py
mobsfscan is a static analysis tool that can find insecure code patterns in your Android and iOS source code. Supports Java, Kotlin, Swift, and Objective C Code. 
It could be found at: https://github.com/MobSF/mobsfscan
=> add new parser - Mobsfscan

docs/content/en/contributing/how-to-write-a-parser.md
Addition to the description how parser classes shall be named.
=> Documentation: Naming of parser classes

.github/workflows/new-release-master-into-dev.yml, .github/workflows/new-release-pr.yml
One was already commented, the other one is just as useless.
=> [GHA] Remove un-needed docker login

dojo/models.py
Fixes #4786.
Also fixes a bug related to the improper use of [`itertools.groupby`](https://docs.python.org/3/library/itertools.html#itertools.groupby) because of the following:
> The operation of `groupby()` is similar to the `uniq` filter in Unix. It generates a break or new group every time the value of the key function changes (which is why it is usually necessary to have sorted the data using the same key function). That behavior differs from SQL’s GROUP BY which aggregates common elements regardless of their input order.
=> Fix and refactor `dojo.models.Finding_Group.components`

.gitignore, dojo/tools/sarif/parser.py, dojo/unittests/scans/sarif/mobsfscan.json, dojo/unittests/tools/test_sarif_parser.py
Fix:#4940
SARIF findings import Error before fix :
after fix SARIF imports findings successfully :
file used for importing:
[sast_mobile_mobsfscan.zip](https://github.com/DefectDojo/django-DefectDojo/files/6991924/sast_mobile_mobsfscan.zip)
=>  Fix CWE parsing for SARIF parser (#4940)

Dockerfile.integration-tests, dojo/templates/defectDojo-engagement-survey/edit_question.html, dojo/templates/defectDojo-engagement-survey/edit_survey_questions.html, dojo/templates/dojo/clear_finding_review.html, dojo/templates/dojo/edit_product.html, dojo/templates/dojo/new_group_member.html, dojo/templates/dojo/new_group_member_user.html, dojo/templates/dojo/new_product_group.html, dojo/templates/dojo/new_product_group_group.html, dojo/templates/dojo/new_product_member.html, dojo/templates/dojo/new_product_member_user.html, dojo/templates/dojo/new_product_type_group.html, dojo/templates/dojo/new_product_type_group_group.html, dojo/templates/dojo/new_product_type_member.html, dojo/templates/dojo/new_product_type_member_user.html, dojo/templates/dojo/review_finding.html, tests/base_test_class.py, tests/finding_test.py, tests/group_test.py, tests/product_group_test.py, tests/product_member_test.py, tests/product_type_group_test.py, tests/product_type_member_test.py
The searchable fields introduced with  #4766 are an awesome enhancement. Unfortunately multiselect fields look weird:
This gets fixed with this PR.
=> Searchable fields are not displayed correctly for multiselect fields

dojo/metrics/views.py, dojo/product/views.py
Fixes #4752 
Fix issue within simple matrix (Accepted Findings).
Display issue on "Inactive Findings" get fixed;
Also solved display issue on "Risk Accepted Matrix" within product page.
*Unable to reproduce the False positive issue within product matrix page.
=> Incorrect False positives and Risk accepted metrics

tests/base_test_class.py
hotfix version of #5038 against master or release/2.2.1
=> fix javascript regex error detection

dojo/models.py, dojo/unittests/test_endpoint_model.py
=> Endpoint: Fix host validation

dojo/api_v2/exception_handler.py
quickfix for #5019 by logging exception
=> Exception handler quick fix

dojo/templatetags/navigation_tags.py
fixes https://github.com/DefectDojo/django-DefectDojo/issues/5070
=> fix incorrect encoding of urls in finding list headings

docker/entrypoint-initializer.sh, dojo/management/commands/validatededupeconfig.py
This script will solve issue #3666 by checking for deduplication configuration at startup.
=> Check deduplication config on startup

dojo/tools/spotbugs/parser.py, dojo/unittests/scans/spotbugs/version_4.4.0.xml, dojo/unittests/tools/test_spotbugs_parser.py
Some data changed with version 4.4.0, the parser was only compatible with version 4.2.x
=> Fix errors with Spotbugs 4.4.x

dojo/tools/sarif/parser.py, dojo/unittests/tools/test_sarif_parser.py
=> SARIF parser - add more information to findings

dojo/templates/dojo/calendar.html, tests/check_various_pages.py
fixes #5079  and ads step to integration test to catch future regressions.
=> calendar: fix to work with bootstrap-chosen

helm/defectdojo/Chart.yaml, helm/defectdojo/templates/configmap.yaml
Add env DD_DATABASE_NAME to helm/defectdojo/templates/configmap.yaml
It's useful when use remote database server
=> Helm - Add DD_DATABASE_NAME env

dojo/tools/harbor_vulnerability/parser.py, dojo/unittests/scans/harbor_vulnerability/harbor-5-vuln.json, dojo/unittests/tools/test_harbor_vulnerability_parser.py
- All severities that are not the same as DD's severities are mapped to `Info` --> fixes #5137
- Refactoring of parser
=> Fix Harbor parser

dojo/tools/dawnscanner/parser.py, dojo/unittests/scans/dawnscanner/dawnscanner_v1.6.9.json, dojo/unittests/tools/test_dawnscanner_parser.py
General maintenance for Dawnscanner parser
=> Add unit tests for Dawnscanner

dojo/forms.py
Fixes an issue introduced in #5064, which was supposed to fix merging. Tested and merging now works.
=> Fix merge of findings - incomplete fix introduced in #5064

.github/workflows/pr-labeler.yml
Add a labeler action which labels PRs based on the files modified in the PR. 
i.e. "New Migration" for PRs with migrations, "docs" for changes to docs, etc.
=> gha: add PR labeler

dojo/templates/base.html
At many organizations, putting their own logo in an application is a desired functionality.
=> Add customizable header and footer logo

SECURITY.md, helm/defectdojo/Chart.yaml
Adds security.md back to root.
=> 2.3.0 Sync Merge

dojo/tools/anchore_grype/parser.py, dojo/unittests/scans/anchore_grype/many_vulns4.json, dojo/unittests/tools/test_anchore_grype_parser.py
replacement for #5357, credits to @gvwalker
=> Change Anchore Grype parser to allow matcher lists

dojo/settings/settings.dist.py, helm/defectdojo/values.yaml
Some small improvements, doesn't change anything. Helm value is already default, just added that people know that it can be changed.
=> main: improve documentation

dojo/templates/base.html, dojo/templates/defectDojo-engagement-survey/surveys.html, dojo/templates/dojo/add_user.html, dojo/templates/dojo/endpoints.html, dojo/templates/dojo/engagements_all.html, dojo/templates/dojo/finding_related_actions.html, dojo/templates/dojo/findings_list_snippet.html, dojo/templates/dojo/product.html, dojo/templates/dojo/product_type.html, dojo/templates/dojo/profile.html, dojo/templates/dojo/snippets/comments.html, dojo/templates/dojo/snippets/endpoints.html, dojo/templates/dojo/snippets/engagement_list.html, dojo/templates/dojo/snippets/risk_acceptance_actions_snippet.html, dojo/templates/dojo/users.html, dojo/templates/dojo/view_endpoint.html, dojo/templates/dojo/view_eng.html, dojo/templates/dojo/view_finding.html, dojo/templates/dojo/view_group.html, dojo/templates/dojo/view_product_details.html, dojo/templates/dojo/view_product_type.html, dojo/templates/dojo/view_risk_acceptance.html, dojo/templates/dojo/view_test.html, dojo/templates/dojo/view_user.html, dojo/templatetags/authorization_tags.py, dojo/templatetags/display_tags.py, dojo/unittests/authorization/test_authorization_tags.py
Auth V2 - Remove legacy authorization part 1
This first of 4-5 PR's removes all decisions in the templates on whether to display UI elements based on legacy authorisation.
=> Auth V2 - Remove legacy authorization part 1: Remove legacy auth from templates

docker/entrypoint-integration-tests.sh
Fix for  https://github.com/DefectDojo/django-DefectDojo/issues/5424
But there should be better way how to test, different configuration
=> Fix integration test users

.github/workflows/unit-tests.yml
to get the fix for https://github.com/moby/buildkit/issues/2426
=> use buildkit master with bugfix

dojo/group/views.py
=> Fix for creating multiple groups containing the same Product Type

dojo/jira_link/helper.py, dojo/unittests/test_jira_import_and_pushing_api.py, dojo/unittests/vcr/jira/JIRAImportAndPushTestApi.test_import_with_push_to_jira_add_tags.yaml, dojo/unittests/vcr/jira/JIRAImportAndPushTestApi.test_import_with_push_to_jira_update_tags.yaml
I noticed today that tags within dojo do not get pushed into jira. This makes that happen.
=> Add support for pushing tags to jira

dojo/tools/trivy/parser.py
Opening this as I still think this is a more general-purpose use as opposed to https://github.com/DefectDojo/django-DefectDojo/pull/5466
Signed-off-by: shubhindia <shubhindia123@gmail.com>
=> add tag for each Trivy vulnerability

.github/release-drafter.yml
fix missing quote introduced in #5431
=> fix release-drafter.xml (against master)

readme-docs/DOCKER.md
Fixing broken link for "Running in Production"
=> Update DOCKER.md to fix broken link

dojo/api_v2/permissions.py, dojo/api_v2/serializers.py, dojo/forms.py, dojo/importers/reimporter/utils.py
A previous PR introduced 2 typos in the UI and the code, which get fixed with this PR.
=> Fixes for typos in UI and code

requirements.txt
forgot to bump in the django 3.2 PR
=> bump django to 3.2.9

dojo/templates/dojo/express_new_jira.html, dojo/templates/dojo/new_cred.html, dojo/templates/dojo/new_cred_mapping.html, dojo/templates/dojo/new_cred_product.html, dojo/templates/dojo/new_github.html, dojo/templates/dojo/new_jira.html, dojo/templates/dojo/new_object.html, dojo/templates/dojo/new_tool_config.html, dojo/templates/dojo/new_tool_product.html, dojo/templates/dojo/new_tool_type.html
removes duplicated `{{block.super}}` lines
=> remove duplicated `{{block.super}}` lines

docker/sample_data/initial_dojo_data.json, dojo/static/dojo/css/dojo.css
=> remove findingimages leftovers

dojo/api_v2/views.py
add missing docstring sentence as reported by @StefanFl
=> api: update reimport docstring

docs/content/en/getting_started/running-in-production.md
Make users aware of the open items to be addressed for DD_ASYNC_FINDING_IMPORT
=> docs: add pointer to open items for DD_ASYNC_FINDING_IMPORT

.github/labeler.yml, .github/release-drafter.yml
It is good to know about changes in UI
=> Add UI label to PR labeler and release drafter

dojo/templates/notifications/engagement_added.tpl, dojo/templates/notifications/other.tpl, dojo/templates/notifications/product_added.tpl, dojo/templates/notifications/product_type_added.tpl, dojo/templates/notifications/report_created.tpl, dojo/templates/notifications/risk_acceptance_expiration.tpl, dojo/templates/notifications/scan_added.tpl, dojo/templates/notifications/sla_breach.tpl, dojo/templates/notifications/test_added.tpl, dojo/templates/notifications/upcoming_engagement.tpl, dojo/templates/notifications/user_mentioned.tpl
- remove redundancy in IF
- consolidate structure (add html tags)
=> Mail notification improvement

dojo/jira_link/helper.py
=> jira: respect summary max length (255)

dojo/api_v2/views.py, dojo/authorization/authorization.py, dojo/development_environment/views.py, dojo/finding/views.py, dojo/forms.py, dojo/home/views.py, dojo/survey/views.py, dojo/templates/base.html, dojo/templates/defectDojo-engagement-survey/create_questionnaire.html, dojo/templates/defectDojo-engagement-survey/edit_question.html, dojo/templates/defectDojo-engagement-survey/list_questions.html, dojo/templates/defectDojo-engagement-survey/list_surveys.html, dojo/templates/dojo/dashboard.html, dojo/templates/dojo/dev_env.html, dojo/templates/dojo/edit_dev_env.html, dojo/templates/dojo/findings_list_snippet.html, dojo/templates/dojo/templates.html, dojo/templates/dojo/test_type.html, dojo/templates/dojo/view_finding.html, dojo/templates/dojo/view_group.html, dojo/templates/dojo/view_user.html, dojo/test_type/views.py, unittests/test_apiv2_methods.py
This PR introduces configurable permissions for:
- Development Environments
- Finding Templates
- Surveys (questionnaires and questions)
- Test Types
=> Configuration authorization 2: Making more staff-permissions configurable

dojo/filters.py
=> add missing comma

Dockerfile.django, Dockerfile.integration-tests, Dockerfile.nginx, docker-compose.override.integration_tests.yml
Reverts DefectDojo/django-DefectDojo#5691
=> Revert "Updated all dockerfiles to match the django dockerfile so UID/GIDs are consistent across dockerfiles"

Dockerfile.django
Reverts DefectDojo/django-DefectDojo#5681
=> Revert "Updated django dockerfile to work with bind mounts for local_settings.py"

dojo/templates/dojo/dashboard.html
Diff looks  bad, but I just reformatted the spacing and added blocks throughout dashboard
=> Make dashboard more modular

.github/labeler.yml
Need this tags for some auto tool that filter PR/issues
=> Update labeler configuration to tag work on parsers

dojo/tools/cyclonedx/parser.py, unittests/tools/test_cyclonedx_parser.py
This PR adds an optional mitigation field to the cyclonedx parser. See issue #5376
=> Add migitation field to cyclonedx parser

dojo/tools/rusty_hog/parser.py
Remove parameter url to determine EssexHog #5821
=> Fix RustyHog subscanner classification #5821

unittests/test_rest_framework.py
The unit test for the rest framework fails in some constellations with PostgreSQL. I am not completely sure why, but the adaptions in this PR make the assertions more straightforward and the test doesn't fail anymore.
=> Make unit test for rest framework more stable

dojo/templates/dojo/product_type_pdf_report.html, dojo/templatetags/display_tags.py
fixes  #5827
Filters had not been applied for findings in Product Type reports.
=> Apply filters for Findings in Product Type report

dojo/templates/dojo/metrics.html
Minor change to align across the DD, previously was Engineer with this commit is Reporter.
=> Product type metrics update

docs/content/en/getting_started/upgrading.md, dojo/settings/settings.dist.py, dojo/templates/base.html, tests/base_test_class.py, tests/group_test.py, tests/user_test.py
The flexible permissions for the configuration of DefectDojo, implemented with release 2.7.0 as a beta version, are now active by default.
=> Flexible permissions for the configuration of DefectDojo are now active by default

README.md
Updates the Quick Start section according to PR #5816
=> Update Quickstart section

dojo/settings/settings.dist.py
=> harbor vulnscan deduplication algorithm #5926

docker-compose.override.debug.yml, docker-compose.override.dev.yml
There are also changes from https://github.com/DefectDojo/django-DefectDojo/pull/5942, so please merge #5942 as first
=> Docker-compose: Add mailhog to dc-debug + remove noise

helm/defectdojo/templates/configmap.yaml
This is fixing missing DD_CELERY_BROKER_PATH variable.
=> Fix missing DD_CELERY_BROKER_PATH variable

helm/defectdojo/Chart.yaml, helm/defectdojo/templates/configmap.yaml
backport #5990 to publish new helm chart from master
=> backport helm celery broker fix

dojo/templates/base.html
I was looking at base.html and noticed I was having a hard time reading it, so I cleaned it up.
The diff looks real large mainly because of change in indention and expanding ugly one liners
=> base.html cleanup and formatting

docker/entrypoint-celery-beat.sh, docker/entrypoint-celery-worker.sh, docker/entrypoint-initializer.sh, docker/entrypoint-uwsgi.sh
This PR provides fix for [#5965](https://github.com/DefectDojo/django-DefectDojo/issues/5965)
=> Fix: #5965

dojo/notifications/helper.py
=> Fix typos & deprecated methods

dojo/settings/settings.dist.py
Make SSO over SAML2 possible (#6092)
=> Update settings.dist.py to force_auth for SAML2

.github/labeler.yml
=> Automate helm labeling for PRs

readme-docs/DOCKER.md
After some users had problems using the scripts for Docker, this PR enhances the documentation with examples.
=> Enhanced documentation for Docker scripts

docs/content/en/getting_started/upgrading.md, dojo/risk_acceptance/api.py, unittests/test_bulk_risk_acceptance_api.py, unittests/test_swagger_schema.py
This PR changes the parameter `cve` to `vulnerability_reference` in the API for risk acceptance.
=> Vulnerability References: Change to vulnerability reference in risk acceptance API

docs/content/en/integrations/notifications.md, dojo/templates/dojo/notifications.html
This PR:
- documents notification template feature
- removes staff from notification option
=> Notifications enhancement 

dojo/filters.py, dojo/finding/helper.py
solves #6142 with including filter for status "under review" and for "reviewers"
=> added filter for status under review

dojo/forms.py
Check if new FEATURE_CONFIGURATION_AUTHORIZATION is enabled to disable is_staff field only if exists.
=> Fix 500 error when editing or adding user and new FEATURE_CONFIGURATION_AUTHORIZATION configuration if not superuser

dojo/search/views.py, dojo/templates/dojo/simple_search.html
I want to divide this big work on small parts. This is the one of them
=> Localization: search page

dc-build.sh, dc-down.sh, dc-stop.sh, dc-unittest.sh, dc-up-d.sh, dc-up.sh, docker/docker-compose-check.sh, readme-docs/DOCKER.md
In this PR:
- check for docker-compose version
- if not specified use default profile mysql-rabbitmq
=> dc command improvements

dojo/templates/notifications/engagement_added.tpl
=> fix links in engagement_added template

helm/defectdojo/templates/django-ingress.yaml
=> Fix empty line between Ingres apiVersion and Kind

dojo/tools/fortify/parser.py, unittests/scans/fortify/issue6260.xml, unittests/tools/test_fortify_parser.py
Date in the report are not reliable. Better to remove this part to make the parser more robust.
Added also more checks in the unit tests.
Fixes #6260
=> Remove date feature in Fortify parser

Dockerfile.django, Dockerfile.integration-tests, Dockerfile.nginx
Reverts DefectDojo/django-DefectDojo#6089
=> Revert "Bump python from 3.8.12-slim-bullseye to 3.10.4-slim-bullseye"

dojo/product/views.py
=> Raise PermissionDenied when user is not allowed to add products

dojo/tools/sonarqube_api/importer.py
=> Fix for error when importing from SonarQube

dojo/tools/trivy/parser.py, unittests/scans/trivy/misconfigurations_and_secrets.json, unittests/tools/test_trivy_parser.py
=> Import misconfigurations and secrets from Trivy

.github/workflows/release-2-tag-docker-push.yml
Reverts DefectDojo/django-DefectDojo#6374
=> Revert "Update release-2-tag-docker-push.yml"

.github/workflows/release-x-manual-helm-chart.yml
Reverts DefectDojo/django-DefectDojo#6373
=> Revert "Update release-x-manual-helm-chart.yml"

README.md
Hi all! Just noticed these on the README and just thought I would propose changes 😄
=> A couple of spelling corrections

readme-docs/DOCKER.md, setup/README.md
fix some indentation in markdown files, also other typos
=> Fix list indentation in docs

dojo/tools/checkmarx/parser.py, unittests/scans/checkmarx/multiple_findings.json, unittests/tools/test_checkmarx_parser.py
Add more code to support reports exported in JSON format.
Fixes #5972
=> (feat) Checkmarx parser JSON support

helm/defectdojo/values.yaml
=> Fix broken linting 

docs/content/en/getting_started/upgrading.md, dojo/apps.py, dojo/finding/queries.py, dojo/models.py, dojo/search/views.py, dojo/templates/dojo/simple_search.html, tests/search_test.py
In the series of changes from `cve` to `vulnerability_id` this PR implements the search for vulnerability ids.
=> Search for vulnerability ids

dojo/tools/burp_enterprise/parser.py, unittests/scans/burp_enterprise/many_vulns.html, unittests/tools/test_burp_enterprise_parser.py
=> Handle Burp Enterprise reports without CWE

dojo/api_v2/serializers.py
=> Save reporter when creating finding

dojo/db_migrations/0064_jira_refactor_populate.py, dojo/db_migrations/0066_django_tagulous.py, dojo/finding/views.py, dojo/jira_link/helper.py, dojo/jira_link/views.py, dojo/templatetags/display_tags.py, unittests/test_jira_import_and_pushing_api.py
"Remediatied" and "Succesfully"
=> Typo fixes

dojo/finding/helper.py, unittests/test_finding_helper.py
fixes #6453
This PR makes saving vulnerability ids more robust.
=> Simplify saving of vulnerability ids

dojo/finding/helper.py
With a tool like Veracode which contains both SAST and SCA findings, if you group on import by component name/version then it will group all SAST findings under one entry with None:None. Similarly, if you group by filepath, it groups all SCA findings under a single entry with FilePath: None.
I think it only makes sense to group if the thing you are grouping by is not None.
=> Only group by if the name/component is not none

dojo/tools/veracode/parser.py, unittests/tools/test_veracode_parser.py
A proposed fix for https://github.com/DefectDojo/django-DefectDojo/issues/6252
=> Fix de-duplication bug with Veracode SCA

dojo/product/views.py
Fixes https://github.com/DefectDojo/django-DefectDojo/issues/6575
=> Don't create two notifications when an engagement is added

dojo/tools/sonarqube_api/importer.py, unittests/scans/sonarqube_api/hotspots/rule_wo_risk_description.json, unittests/tools/test_sonarqube_importer.py
=> SonarQube API: process hotspot rules without riskDescription and fixRecommendations

dojo/tools/ibm_app/parser.py, unittests/scans/ibm_app/testfire.xml, unittests/tools/test_ibm_app_parser.py
=> IBM AppScan: Fix parsing of cve and cwe

dojo/tools/cyclonedx/parser.py, unittests/tools/test_cyclonedx_parser.py
See https://cyclonedx.org/docs/1.4/json/#vulnerabilities_items_analysis_state
=> Parse CycloneDX analysis section to see if findings should be mitigated

dojo/engagement/views.py, dojo/templates/dojo/copy_object.html, dojo/templates/dojo/view_eng.html, dojo/templates/dojo/view_finding.html, dojo/templates/dojo/view_test.html
- Correct the wording on the copy operation on engageements
- Add to the number of places that an object can be copied from
=> Correct wording on copy text, add more places to copy

README.md
It could help faster answer the question: Looks cool but is it compatible with my scanning tool?
=> Add link to Parsers to README

docs/content/en/integrations/ldap-authentication.md
Lets help out the Django newbies (myself included) 😄 
Helping out: #3981 and #6595
=> Add LDAP integration docs

docs/content/en/getting_started/upgrading.md, dojo/management/commands/migrate_cve.py, dojo/utils.py
Introducing a management command to populate the database table for Vulnerability Ids from the CVEs in the findings.
=> Management command to migrate CVEs to Vulnerability Ids

dojo/tools/gitlab_container_scan/parser.py, unittests/scans/gitlab_container_scan/issue6639.json, unittests/tools/test_gitlab_container_scan_parser.py
Some reports doesn't have some data, this PR make the parser more robust.
* make parser more robust (missing data)
* add need data
* add more unit tests
Fixes #6639
=> fixes import GitLab container scan missing date

dojo/settings/settings.dist.py
Added the requested lines for Blackduck Hub Deduplication #6161
=> Update settings.dist.py (Blackduck Hub Deduplication)

docs/content/en/integrations/api-v2-docs.md, dojo/context_processors.py, dojo/settings/settings.dist.py, dojo/templates/base.html, dojo/templates/dojo/profile.html, dojo/urls.py, dojo/user/urls.py, dojo/user/views.py, unittests/test_apiv2_user.py
https://owasp.slack.com/archives/C014H3ZV9U6/p1658840093322619
=> API: Add support for DD_API_TOKENS_ENABLED

dojo/tools/snyk/parser.py, unittests/tools/test_snyk_parser.py
Add the target file attribute in the mitigation section as well as a tag
=> Snyk: update mitigation section

dojo/forms.py, dojo/survey/views.py, dojo/templates/defectDojo-engagement-survey/add_choices.html, dojo/templates/defectDojo-engagement-survey/create_related_question.html, dojo/templates/defectDojo-engagement-survey/edit_survey_questions.html, dojo/templates/defectDojo-engagement-survey/list_questions.html, dojo/templates/defectDojo-engagement-survey/list_surveys.html
I was looking through the questionnaires and noticed a good amount of ugly. Here is what I've fixed
- Various clean ups in code formatting in the views
- Changed some redirects to make sense (ex. redirect to question list after adding a new question)
- The active bar would display outside of the div on most screen sizes
- Before: 
- ![image](https://user-images.githubusercontent.com/46459665/184428565-f947f0b2-709c-46c4-aa4b-0fed7ec10d4c.png)
- After: 
- ![image](https://user-images.githubusercontent.com/46459665/184428496-dfd6228c-b5e5-4d2f-aa21-106a6a4745ed.png)
- Question selection form 
- Every questions selected was being displayed in the dropdown box and would make the page a ridiculous size
- Before:
- ![image](https://user-images.githubusercontent.com/46459665/184428855-988bbd69-8d …
=> Questionnaire cleanup efforts

dojo/product/views.py, dojo/test/views.py
Yet another part of translation for some part product and test modules. 
Also I refactored imports for test/views.py
=> Translation & refactor test, product

dojo/metrics/views.py
=> Fix bug with sorting top 10 products in /metrics

dojo/tools/sarif/parser.py, unittests/tools/test_sarif_parser.py
This adds the "CodeFlows" part of SARIF results to the findings description (partly resolves #6600) to make the finding more understandable.
=> Add Code Flows to finding's description for SARIF test results

.github/workflows/submodule-update.yml
Automatically keep external documentation repo up to date on each pull request. New documentation will be hosted at https://documentation.defectdojo.com/
=> Add workflow to update external documentation repo

dojo/jira_link/views.py
=> Fix assignee bug in JIRA view

docs/content/en/integrations/social-authentication.md, dojo/pipeline.py, dojo/remote_user.py, dojo/settings/settings.dist.py, requirements.txt
Implementation for https://owasp.slack.com/archives/C014H3ZV9U6/p1658840111091849
=> Auth: Add RemoteUser implementation

dojo/notifications/helper.py, dojo/settings/settings.dist.py
This PR sorts findings in notification for better UX
=> Sort findings in notifications

dojo/endpoint/views.py, dojo/finding/queries.py, dojo/metrics/views.py, dojo/templates/dojo/metrics.html, dojo/utils.py, unittests/test_metrics_queries.py
We actively using defect dojo for collecting findings.
On the current moment we have 10 000 findings. 
We noticed that when we loading a metrics pages our god is falling down with 500 error (out of memory problem). To solve the problem we optimized a metric page. This PR is contain solve for optimization 
This improvement halves the memory consumption for finding processing
=> Optimize metrics

helm/defectdojo/templates/django-ingress.yaml
Related to https://github.com/DefectDojo/django-DefectDojo/issues/6466
=> switch to Has Capabilities

dojo/tools/veracode/parser.py, unittests/scans/veracode/veracode_scan_sca_mitigated.xml, unittests/tools/test_veracode_parser.py
The Veracode SCA mitigation part is not parsed, meaning that findings aren't being marked as mitigated in DD.
=> Parse mitigation status for Veracode SCA findings

dojo/forms.py
A fix for https://github.com/DefectDojo/django-DefectDojo/issues/6897
Tested that it gets pushed to JIRA successfully with the change.
=> Fix error when promoting stub finding to JIRA

dojo/filters.py
Added a simple filter to filter findings directly in the API for the existance of JIRA issues
=> Added filter for existance of JIRA issue in finding API

.github/workflows/gh-pages.yml, .github/workflows/k8s-testing.yml
https://github.com/actions/runner-images/issues/6002
=> Rev actions to latest ubuntu version per deprecation

helm/defectdojo/templates/celery-beat-deployment.yaml, helm/defectdojo/templates/celery-worker-deployment.yaml, helm/defectdojo/templates/django-deployment.yaml, helm/defectdojo/values.yaml
As proposed in #6935, I have added the option to add custom pod labels.
=> added option to add labels using podLabels: {} #6935

dojo/api_v2/serializers.py, dojo/models.py
Corrected issue #6170 by making the product editable in the Tool_Product_Settings model.
=> [Fix] API - Tool Product Settings (#6170)

dojo/jira_link/helper.py
get_jira_meta() function in did not check if jira.createmeta() raises an exception. In case an exception was raised, it was not logged anyhow, the logs contained only "invalid JIRA Project Config.." message in DEBUG stream.
This commit stores an error triggered by jira.createmeata() in logs and displays it to a user. The commit also slightly improves quotes formatting for debug-level error message.
=> dojo: jira_link: improve error reporting when fetching Jira metadata

dojo/forms.py
A fix for https://github.com/DefectDojo/django-DefectDojo/issues/7030
=> Fix for error on pushing an adhoc finding to JIRA

dojo/settings/settings.dist.py
=> :bug: fix for wpscan

dojo/importers/importer/importer.py
A fix for https://github.com/DefectDojo/django-DefectDojo/issues/7098
Tested:
- Importing a new test doesn't close old findings of the same type in a different engagement in the same product.
- Importing a new test does close old findings of the same type in the same engagement.
=> Only close old findings in the importer in the same engagement.

dojo/tools/checkov/parser.py, unittests/scans/checkov/checkov-report-severity.json, unittests/tools/test_checkov_parser.py
A fix for https://github.com/DefectDojo/django-DefectDojo/issues/7114
=> Parse checkov severity

dojo/api_v2/serializers.py, dojo/forms.py, dojo/importers/reimporter/reimporter.py, dojo/test/views.py
A follow-on from https://github.com/DefectDojo/django-DefectDojo/pull/7150.
=> Implement create_finding_groups_for_all_findings in the Reimporter

dojo/api_v2/serializers.py
The swagger docs for the importer/reimporter are very incomplete. I copied the helptext over from the forms to improve it. There are still gaps, but it's a lot better than before.
=> Improve Swagger documentation for the importer/reimporter

docs/content/en/getting_started/upgrading.md
Please wait for #7200 to be merged before this one is merged. Need to test the workflow
=> Add upgrade docs for 2.17.x

dojo/tools/qualys/csv_parser.py
=> Remove last instance of "is_Mitigated"

Dockerfile.django-alpine
After review with @alles-klar i've split the pr #7166 .
* Dockerfile for an alpine based django docker image
This should also satisfy the issue #5907
See #7166
=> Dockerfile for alpine-based django docker image

tests/finding_test.py
After review with @alles-klar i've split the pr #7166 .
* While running the integration tests building the alpine django image i've faced an issue testing finding deletion.
See #7166
=> Fixed finding deletion in integration test

dojo/product_type/views.py, dojo/templates/dojo/delete_product_type.html, dojo/templates/dojo/delete_product_type_group.html, dojo/templates/dojo/delete_product_type_member.html, dojo/templates/dojo/edit_product_type.html, dojo/templates/dojo/edit_product_type_group.html, dojo/templates/dojo/edit_product_type_member.html, dojo/templates/dojo/new_product_type.html, dojo/templates/dojo/new_product_type_group.html, dojo/templates/dojo/new_product_type_member.html, dojo/templates/dojo/paging_snippet.html, dojo/templates/dojo/product_type.html, dojo/templates/dojo/view_product_type.html
Yet another part page translation. Now - product type pages
=> Translate product type

dojo/api_v2/serializers.py
The recent fix I did to the importer + reimporter mean that the active/verified booleans are actually set to false by default, instead of None.
=> Importer + Re-Importer are setting active/verified to false by default

dojo/settings/settings.dist.py
issues spanning  multiple endpoints were being swallowed by reimport
=> Add endpoints to Qualys dedupe settings

helm/defectdojo/Chart.yaml
Fix for deprecated helm version
=> Update rabbit chart version

dojo/tools/anchore_grype/parser.py
A fix for https://github.com/DefectDojo/django-DefectDojo/issues/7229
=> Fixing error when grype location is empty

dojo/survey/views.py, dojo/templates/defectDojo-engagement-survey/create_related_question.html
Two issues:
- Updating the name of a survey question resulted in a 500 due to an incorrect url reverse
- Remove some javascript that hid the title of the question for multichoice questions (led to the submit button not even working)
[sc-264] [sc-122]
=> Survey Bugs: Submit multichoice question, 500 when editing name

dojo/templates/dojo/users.html, dojo/templates/dojo/view_user.html, dojo/user/views.py
Taking advantage of the last login field that is already stored by Django user. Also added a banner at login to specify when the last login was
[sc-282]
=> Add last login field to users page

docs/content/en/getting_started/upgrading.md
Upgrade notes for the latest  rabbitmq helm release.
=> Upgrade notes

dojo/product/queries.py, dojo/product/views.py, dojo/product_type/queries.py
In this PR I optimized working with db. 
For /product/<id> page I decreased count from 43 to 31 queries (~28%). 
You could see screenshots below as proof
Before
After
=> Optimize call db query for product page

.github/labeler.yml, .github/release-drafter.yml
- Mark PRs related to update of language localization data.
- Add section to release notes
=> Localization: Mark PRs + release notes

nginx/nginx.conf, nginx/nginx_TLS.conf
In this PR I added gzip compression by default for nginx (also TLS). This decrease packet size for download by client and increase speed load
=> Add gzip for nginx

dojo/tools/bugcrowd/parser.py
Fixing typo in bugcrowd parser
=> Fixing typo in bugcrowd parser

dojo/tools/sonarqube_api/api_client.py
This PR is trying to fix #7365
=> SonarQube: Handle non-JSON response in test

dojo/product/views.py, dojo/templates/dojo/product_metrics.html, dojo/utils.py
I optimized a html source for product/<id>/metrics page. 
Page contain a not optimized code for counting chart graphic. In big data this page will be huge.
=> Optimize output in html for product/metrics page

dojo/jira_link/helper.py, dojo/middleware.py, dojo/settings/settings.dist.py
Adds arbitrary headers to defectdojo
=> Add arbitrary header setting, forward to jira

dojo/tools/rusty_hog/parser.py, unittests/tools/test_rusty_hog_parser.py
=> Rustyhog: Make JIRA/Confluence URLs clickable in description

dojo/api_v2/views.py, dojo/finding/views.py
A fix for https://github.com/DefectDojo/django-DefectDojo/issues/7429
Looks like some instances were missed as part of https://github.com/DefectDojo/django-DefectDojo/pull/6193/files
=> Use Finding.status_finding instead of endpoint_status

dojo/tools/generic/parser.py, tests/dedupe_test.py, unittests/scans/generic/generic_custom_test.json, unittests/tools/test_generic_parser.py
This is @damiencarol's work #5967, rebased and opened as new PR
=>  Add dynamic Test_Type for Generic parser [originaly #5967]

dojo/static/dojo/css/dojo.css, dojo/templates/400.html, dojo/templates/403.html, dojo/templates/404.html, dojo/templates/500.html
Added FontAweomse icons to previously implemented custom error pages.
[sc-464]
=> Added FontAwesome icons to error pages

README.md
Just updating the slack invitation URL
=> Update Slack Invitation link for OWASP

docs/content/en/integrations/parsers/file/generic.md
=> Docs: Add documenation for #7471

dojo/templates/dojo/dashboard.html, dojo/utils.py
I prepared dashboard page to localization. Also I refactored pages
=> Localization + refactor dashboard

dojo/importers/importer/importer.py, dojo/importers/reimporter/reimporter.py, dojo/tools/anchore_enterprise/parser.py, dojo/tools/anchorectl_policies/parser.py, dojo/tools/appspider/parser.py, dojo/tools/checkov/parser.py, dojo/tools/clair_klar/parser.py, dojo/tools/crashtest_security/parser.py, dojo/tools/dependency_track/parser.py, dojo/tools/gitlab_dep_scan/parser.py, dojo/tools/gitleaks/parser.py, dojo/tools/huskyci/parser.py, dojo/tools/ibm_app/parser.py, dojo/tools/immuniweb/parser.py, dojo/tools/nessus/parser.py, dojo/tools/neuvector/parser.py, dojo/tools/neuvector_compliance/parser.py, dojo/tools/npm_audit/parser.py, dojo/tools/nsp/parser.py, dojo/tools/ort/parser.py, dojo/tools/ossindex_devaudit/parser.py, dojo/tools/snyk/parser.py, dojo/tools/sonarqube/parser.py, dojo/tools/sslyze/parser.py, dojo/tools/trufflehog3/parser.py, dojo/tools/twistlock/parser.py, dojo/tools/vcg/parser.py, dojo/tools/xanitizer/parser.py
Reaction on https://github.com/DefectDojo/django-DefectDojo/pull/7482/files#r1087718601
=> Forward parser errors to users

dojo/home/urls.py, dojo/home/views.py, dojo/static/dojo/css/dojo.css, dojo/templates/base.html, dojo/templates/dojo/support.html
=> Added Support Tab and Support Links

dojo/templatetags/display_tags.py
Remove trailing bracket for SLA information in UI
=> Remove trailing bracket for SLA information in UI

dojo/tools/qualys/csv_parser.py
Fixed a bug in the Qualys CSV parser that was setting `Finding.mitigated` to a `date` object. It is not a `datetime` object.
No changes
No changes needed - only minor bug fix
**Checklist**
- [✔] Make sure to rebase your PR against the very latest `dev`.
- [✔] Features/Changes should be submitted against the `dev`.
- [✔] Bugfixes should be submitted against the `bugfix` branch.
- [✔ ] Give a meaningful name to your PR, as it may end up being used in the release notes.
- [✔] Your code is flake8 compliant.
- [✔] Your code is python 3.11 compliant.
Moderators: Labels currently …
=> Qualys CSV Finding.mitigated fix

dojo/finding/helper.py, dojo/models.py
I think it would be useful to be able to group by Finding Title. For example, you might want to push to a single JIRA all semgrep findings of a particular type, and not care about the filepath.
=> Add the ability to group by the finding title

.github/workflows/refresh_helm_lock_file.yaml
When a contributor pushes any changes to the helm, it will detect and automatically refresh chart.lock file.
=> Refresh lock file on helm changes

dojo/importers/importer/importer.py, dojo/importers/reimporter/reimporter.py, dojo/importers/reimporter/utils.py, dojo/importers/utils.py
There's a lot of duplicate code in the importer/reimporter to do with endpoints, this PR does some code consolidation.
=> A cleanup of the endpoint code used by the importer/reimporter

dojo/importers/reimporter/reimporter.py
Fix for https://github.com/DefectDojo/django-DefectDojo/issues/7568
**Checklist**
=> Fix #7568 do_not_reactivate notes on each (re)import

docs/content/en/integrations/social-authentication.md
Reaction for:
- #7495
- #7598
- https://owasp.slack.com/archives/C2P5BA8MN/p1668191790863909
- https://owasp.slack.com/archives/C2P5BA8MN/p1667080622637429
- https://owasp.slack.com/archives/C2P5BA8MN/p1654728072771859
=> Docs: Groups from Identity Providers

dojo/product/views.py
A fix for https://github.com/DefectDojo/django-DefectDojo/issues/7590
=> Enable GitHub integration for existing products

dojo/tools/api_blackduck/api_client.py
This fix should avoid error: `'BlackduckAPI' object has no attribute 'get_asset'`
More details (and story behind): https://owasp.slack.com/archives/C2P5BA8MN/p1676985422740079?thread_ts=1675768685.949799&cid=C2P5BA8MN
=> BlackduckAPI: remove test_product_connection

dojo/tools/cyclonedx/parser.py, unittests/scans/cyclonedx/nested-component-log4j.json, unittests/tools/test_cyclonedx_parser.py
Import Scan: Flatten nested components in cycloneDx JSON format.
Tested manually.
Changed only for JSON not for XML files.
=> [cyclonedx-json] flatten components

dojo/api_v2/views.py
=> Add prefetching to Tests endpoint

dojo/api_v2/serializers.py, dojo/api_v2/views.py
=> Add prefetching to Endpoint, Endpoint Status, and Engagement

dojo/api_v2/views.py
Reduce the number of calls in technologies endpoint from 3 to 1 (technologies, product ID query, user ID query
[sc-613]
=> Add prefetching to technologies endpoint

dojo/api_v2/views.py
=> Add prefetch to stub findings endpoint

dojo/api_v2/permissions.py, dojo/api_v2/serializers.py, dojo/api_v2/views.py, dojo/filters.py, dojo/fixtures/dojo_testdata.json, dojo/models.py, dojo/risk_acceptance/queries.py, dojo/urls.py, unittests/test_apiv2_methods.py, unittests/test_rest_framework.py
There was not a risk acceptance api endpoint. This PR adds it
=> Add Risk Acceptance (read) API Endpoint

dojo/templates/dojo/delete_group.html
The button is not named correctly
=> fix(UI): wrong button name for deleting group

dojo/tools/dependency_track/parser.py, unittests/scans/dependency_track/many_findings_with_alias.json, unittests/scans/dependency_track/many_findings_with_empty_alias.json, unittests/tools/test_dependency_track_parser.py
This is an additional fix for issue: 7582 
There was an edge case where the alias array coming from dependency-track is empty. This ensures we correctly fall back to the previous default in this case.
The test now includes this edge case for 1 finding
-
**Checklist**
- [ x] Bugfixes should be submitted against the `bugfix` branch.
- [ x] Give a meaningful name to your PR, as it may end up being used in the release notes.
- [ x] Your code is python 3.11 compliant.
- [ x] Add applicable tests to the unit tests.
- Import Scans (for …
=> Fix for empty alias

dojo/api_v2/permissions.py, dojo/api_v2/serializers.py, dojo/api_v2/views.py, dojo/authorization/authorization.py, dojo/authorization/roles_permissions.py, dojo/cred/views.py, dojo/filters.py, dojo/fixtures/dojo_testdata.json, dojo/templates/dojo/view_cred_details.html, dojo/urls.py, unittests/test_rest_framework.py
Add Credential Mapping and API Endpoint
=> Add Credential Mapping and API Endpoint

dojo/templates/dojo/view_finding.html
It would be useful to link directly inside a finding to the finding group.
Tested this works OK
=> Add link to finding group from inside finding

dojo/db_migrations/0118_remove_finding_images.py, dojo/engagement/views.py, dojo/finding/helper.py, dojo/jira_link/helper.py, dojo/management/commands/import_github_languages.py, dojo/pipeline.py, dojo/risk_acceptance/helper.py, dojo/tools/dependency_check/parser.py, dojo/tools/dependency_track/parser.py, dojo/utils.py
Just a cleanup to fix some deprecation errors about logger.warn.
=> Fix code warnings about logger.warn

readme-docs/CONTRIBUTING.md
changed path to tests as they referred to the folder readme-docs
=> Update path to tests in CONTRIBUTING.md

dojo/templates/dojo/findings_list_snippet.html
fixing for DataTables popup error  
#7523 
=> fixing datatable column count

dojo/pipeline.py
Context https://owasp.slack.com/archives/C2P5BA8MN/p1679994704686659
=> Azure-groups: raise error on broken request

dojo/authorization/roles_permissions.py, dojo/finding/views.py, dojo/templates/base.html, dojo/templates/dojo/add_template.html, dojo/templates/dojo/dev_env.html, dojo/templates/dojo/endpoints.html, dojo/templates/dojo/engagement.html, dojo/templates/dojo/engineer_metrics.html, dojo/templates/dojo/findings_list_snippet.html, dojo/templates/dojo/groups.html, dojo/templates/dojo/note_type.html, dojo/templates/dojo/product.html, dojo/templates/dojo/product_type.html, dojo/templates/dojo/report_findings.html, dojo/templates/dojo/templates.html, dojo/templates/dojo/test_type.html, dojo/templates/dojo/users.html, dojo/templates/dojo/view_finding.html, dojo/templates/dojo/view_test.html, dojo/templatetags/navigation_tags.py
Fixes #7523 on view test page
Fixes #7988 [sc-812] on view test page and all findings list pages
Both pf the above provided a good opportunity to properly format and cleanup the finding list pages
Fix permission schemes for finding templates [sc-813]
=> Finding List Fixes + Finding Template Permission Fixes

dojo/templates/base.html, dojo/templates/dojo/components.html, dojo/templates/dojo/findings_list_snippet.html, dojo/templates/dojo/product.html, dojo/templates/dojo/product_components.html, dojo/templates/dojo/view_finding.html, dojo/templates/dojo/view_test.html
I noticed that when we have over 250 products page /products is loaded to slow in Chromium based browser. After doing research on this topic, I fixed it in this MR
=> Optimized calling popover plugin

dojo/benchmark/views.py
Same fix as #7959 but in a different place
Fixes #8078
=> Remove MySQL incompatibility from benchmarks

helm/defectdojo/templates/celery-beat-deployment.yaml, helm/defectdojo/templates/celery-worker-deployment.yaml, helm/defectdojo/values.yaml
This PR fixes problem of mounting certificate to other django components than uwsgi.
=> Fix helm certificate mounts 

docs/content/en/getting_started/running-in-production.md
Fixed a typo for the word default
**Checklist**
This …
=> Typo fix for running-in-production.md

dojo/finding/views.py
After enabling the "Automatically Sync Findings" feature flag in the Jira Instance setting pages, opening/closing Findings via the drop down menu was not updated the ticket status in Jira. It looks like this part of the codebase was simply forgotten when this feature was implemented.
=> Add support for Jira auto sync when opening and closing findings

dojo/templates/dojo/findings_list_snippet.html, dojo/templates/dojo/view_finding.html, dojo/templates/dojo/view_test.html, dojo/templatetags/authorization_tags.py
A continuation of #7027 
[sc-1028]
=> Make requests of a peer review available to those with read access

dojo/tools/api_blackduck/importer.py, dojo/tools/api_bugcrowd/importer.py, dojo/tools/api_cobalt/importer.py, dojo/tools/api_edgescan/importer.py, dojo/tools/api_sonarqube/importer.py, dojo/tools/api_vulners/importer.py, unittests/tools/test_api_bugcrowd_importer.py, unittests/tools/test_api_cobalt_importer.py, unittests/tools/test_api_edgescan_importer.py, unittests/tools/test_api_sonarqube_importer.py
Solution for https://github.com/DefectDojo/django-DefectDojo/issues/8165
Not necessary
=> API parsers: Make errors in importers more verbose (add product name and id)

dojo/tools/api_sonarqube/importer.py, unittests/tools/test_api_sonarqube_importer.py, unittests/tools/test_api_sonarqube_parser.py
This PR is intend to optimize the import of Sonarqube findings via API.
- Added the Issue permalink as reference as suggested in #6834 
- Addded the severity of hotspots to the defectdojo findings instead of hardcoded "Info" #8150 
Feature is tested and already implemented at our DD instance.
**Checklist**
=> fix Sonarqube importer

dojo/settings/settings.dist.py
This PR is related to the not working Dependency Check deduplication  #8228.  Its just a small adjustment on the HASHCODE_FIELDS_PER_SCANNER.
Works as it should.
=> fix - Dependency Check deduplication #8228

docker/entrypoint-initializer.sh, dojo/announcement/signals.py, dojo/settings/settings.dist.py
Behavior on when banners were created is inconsistent
=> Update banner checks

dojo/finding/views.py
The current code was throwing an exception
```
File "~/django-DefectDojo/venv/lib64/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
File "~/django-DefectDojo/venv/lib64/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
File "~/django-DefectDojo/dojo/authorization/authorization_decorators.py", line 30, in _wrapped
return func(request, *args, **kwargs)
File "~/django-DefectDojo/dojo/finding/views.py", line 588, in view_finding
"burp_request": burp_request,
UnboundLocalError: local variable 'burp_request' referenced before assignment
```
Declaring burp_request outside the try catch block is …
=> Fix `BurpRawRequestResponse` reference before assignment error

dojo/tools/tenable/csv_format.py, dojo/tools/tenable/xml_format.py, unittests/scans/tenable/tenable_many_vuln.csv, unittests/tools/test_tenable_parser.py
=> Tenable: Further safeguarding, hardening, and conversions

dojo/tools/testssl/parser.py, unittests/scans/testssl/failed_target.csv, unittests/tools/test_testssl_parser.py
=> fix fatal error in testssl result #8269

dojo/tools/drheader/parser.py, unittests/tools/test_drheader_parser.py
=> fix drheader parser #8281

dojo/tools/api_bugcrowd/parser.py, unittests/scans/api_bugcrowd/bugcrowd_broken_bug_url.json, unittests/tools/test_api_bugcrowd_parser.py
Context: https://owasp.slack.com/archives/C2P5BA8MN/p1686321072168679
=> Api Bugcrowd: Fix handling of invalid endpoint

dojo/tools/huskyci/parser.py, dojo/tools/hydra/parser.py, dojo/tools/ibm_app/parser.py, dojo/tools/immuniweb/parser.py, dojo/tools/intsights/parser.py, dojo/tools/jfrog_xray_api_summary_artifact/parser.py, dojo/tools/jfrog_xray_unified/parser.py, dojo/tools/jfrogxray/parser.py, dojo/tools/kics/parser.py, dojo/tools/kiuwan/parser.py, dojo/tools/kubebench/parser.py, dojo/tools/meterian/parser.py, dojo/tools/microfocus_webinspect/parser.py, dojo/tools/mobsfscan/parser.py
Update files with PEP8 standars in folders dojo/tools/
dojo/tools/hydra
dojo/tools/huskyci
dojo/tools/ibm_app
dojo/tools/immuniweb
dojo/tools/intsights
dojo/tools/jfrog_xray_api_summary_artifact
dojo/tools/jfrog_xray_unified
dojo/tools/jfrogxray
dojo/tools/kics
dojo/tools/kiuwan
dojo/tools/meterian
dojo/tools/microfocus_webinspect
dojo/tools/mobsfscan
=> Update files with PEP8 standards in folder dojo/tools #004

dojo/tools/qualys/parser.py
During Qualys "import_scan_results", add the vulnerability type to the description. The mapping of the types is described in https://success.qualys.com/discussions/s/question/0D52L00004TnzgISAR/explanation-of-ig-vuln-practice
**Checklist**
=> Extract vulnerability type for Qualys scan import

dojo/filters.py
=> Fix finding/test engagement tag API filter 

nginx/nginx_TLS.conf
Context: https://owasp.slack.com/archives/C2P5BA8MN/p1688660837154789
Fix: https://github.com/DefectDojo/django-DefectDojo/issues/3452
=> Fix: HTTP->HTTPS redirect path

readme-docs/DOCKER.md
Update DOCKER.md "run with docker compose using https"
Change 1) Under "run with docker compose using https" added clarity to nginx secrets path (nginx/nginx_TLS.conf) -- to make it easier for newer users to identify the correct file to edit.
Proposed Change 2) I also touched line 298 to highlight the need for clarity surrounding this line. In the docker-compose.override.https.yml file (https://github.com/DefectDojo/django-DefectDojo/blob/master/docker-compose.override.https.yml), making the != True change is not correct with the syntax when comparing the docker-compose.override.https.yml file. This can cause newer users who are learning DefectDojo a small headache. Furthermore, when setting the actual value of GENERATE_TLS_CERTIFICATE: 'false' and restarting the containers, the nginx …
=> Update DOCKER.md "run with docker compose using https"

dojo/announcement/signals.py, dojo/announcement/urls.py, dojo/announcement/views.py, dojo/api_v2/exception_handler.py, dojo/api_v2/mixins.py, dojo/api_v2/permissions.py, dojo/api_v2/prefetch/__init__.py, dojo/api_v2/prefetch/mixins.py, dojo/api_v2/prefetch/prefetcher.py, dojo/api_v2/prefetch/schema.py, dojo/api_v2/prefetch/utils.py, dojo/api_v2/schema/__init__.py, dojo/api_v2/schema/extra_schema.py, dojo/api_v2/schema/utils.py, dojo/api_v2/serializers.py, dojo/api_v2/views.py, dojo/authorization/authorization.py, dojo/authorization/authorization_decorators.py, dojo/authorization/roles_permissions.py, dojo/banner/urls.py, dojo/banner/views.py, dojo/benchmark/urls.py, dojo/benchmark/views.py, dojo/components/sql_group_concat.py, dojo/components/urls.py, dojo/components/views.py
Update files with PEP8 standars in folders dojo/
dojo/announcement
dojo/announcement
dojo/api_v2
dojo/authorization
dojo/banner
dojo/benchmark
dojo/components
=> Update files with PEP8 standards in folder dojo #002

dojo/tools/dockle/parser.py, dojo/tools/drheader/__init__.py, dojo/tools/drheader/parser.py, dojo/tools/dsop/parser.py, dojo/tools/eslint/__init__.py, dojo/tools/eslint/parser.py, dojo/tools/fortify/__init__.py, dojo/tools/fortify/parser.py, dojo/tools/generic/parser.py, dojo/tools/ggshield/parser.py, dojo/tools/github_vulnerability/parser.py, dojo/tools/gitlab_container_scan/parser.py, dojo/tools/gitlab_dast/parser.py, dojo/tools/gitlab_dep_scan/parser.py, dojo/tools/gitlab_sast/parser.py, dojo/tools/gitlab_secret_detection_report/parser.py
Update files with PEP8 standars in folders dojo/tools/
dojo/tools/dockle
dojo/tools/drheader
dojo/tools/dsop
dojo/tools/eslint
dojo/tools/fortify
dojo/tools/generic
dojo/tools/ggshield
dojo/tools/github_vulnerability
dojo/tools/gitlab_api_fuzzing
dojo/tools/gitlab_container_scan
dojo/tools/gitlab_dast
dojo/tools/gitlab_dep_scan
dojo/tools/gitlab_sast
dojo/tools/gitlab_secret_detection_report
=> Update files with PEP8 standards in folder dojo/tools #002

dojo/tools/dawnscanner/__init__.py, dojo/tools/dawnscanner/parser.py, dojo/tools/dependency_check/parser.py, dojo/tools/dependency_track/parser.py, dojo/tools/detect_secrets/parser.py, dojo/tools/dockerbench/parser.py
Update files with PEP8 standars in folders dojo/tools/
dojo/tools/dawnscanner
dojo/tools/dependency_check
dojo/tools/dependency_track
dojo/tools/detect_secrets
dojo/tools/dockerbench
=> Update files with PEP8 standards in folder dojo/tools #001

.github/workflows/integration-tests.yml, Dockerfile.integration-tests-debian, docker/entrypoint-integration-tests.sh, dojo/filters.py
This PR  fixes #7760 and will identify issues similar to it.
=> Fix invalid OpenAPI schema + Add integration test

dojo/finding/views.py
Context: https://owasp.slack.com/archives/C2P5BA8MN/p1690402861680949
=> Correct exception of editing finding with multiple req/resp pairs

dojo/reports/views.py
=> Add more SLA related fields to excel/csv reports

requirements.txt
Previous default is mysql-rabbitmq, updating references in this doc to correct the new default as postgres-redis.
Please update any documentation when needed in the [documentation …
=> Doc fix default postgres redis

dojo/settings/settings.dist.py, dojo/tools/semgrep/parser.py, unittests/scans/semgrep/semgrep_version_1_30_0_line_26.json, unittests/scans/semgrep/semgrep_version_1_30_0_line_27.json, unittests/tools/test_semgrep_parser.py
Semgrep parser has fingerprint field to track unique vulnerabilities. Current implementation does not handle this properly.
-
-
**Checklist**
=> Semgrep parser unique id from tool

dojo/tools/awssecurityhub/parser.py, unittests/scans/awssecurityhub/securityhub_inspector_no_vulnerabilities.json, unittests/tools/test_awssecurityhub_parser.py
=> Update ASW-SH Inspector to accommodate findings without vulnerabilities or remediation

dojo/filters.py, dojo/finding/views.py, dojo/templates/dojo/view_finding.html
Manually created:
Not touched
Reactivated
History
=> Finding: Add "last mentioned" and history of changes of finding

dojo/engagement/views.py, dojo/tools/trivy/parser.py, unittests/tools/test_trivy_parser.py
This feature adds the causes from the CauseMetadata Key in the findings to know where is exactly the problem. In the finding description, the lines of code are added when the scan finds the Key code in CauseMetadata key of the Json File.
The unittests ran successfully after updating the finding descriptions.
=> Enhance Trivy parser

dojo/tools/asff/parser.py
Advance the ASFF report according to the linked issue description.
=> Advance ASFF report #8462

docker-compose.yml, docker/environments/mysql-rabbitmq.env, docker/environments/mysql-redis.env, docker/environments/postgres-rabbitmq.env, docker/environments/postgres-redis.env
Fix https://github.com/DefectDojo/django-DefectDojo/issues/8303
=> Docker-compose: use variables for depends_on

dojo/engagement/views.py
=> Fix: if Development_Environment "Development" was removed

Dockerfile.integration-tests-debian, requirements.txt
Bump Django from 4.1.10 to 4.1.11 - CVE-2023-41164
Django=4.1.10 is vulnerable to CVE-2023-41164 and requirements.txt calls out 4.1.10 specifically prior to this bugfix suggestion to bump it to 4.1.11. …
=> Bump Django from 4.1.10 to 4.1.11 - CVE-2023-41164

docker-compose.yml
Fix https://owasp.slack.com/archives/C2P5BA8MN/p1695063859155169
=> Fix: Use default values for DD_DOCKERCOMPOSE_[BROKER|DATABASE]

dojo/tools/qualys/csv_parser.py
[sc-2303]
The parser now validates and includes v3 and v3.1 headers. Also the parser for the datetime was changed using dateutils parser.parse function
=> Update Qualys CSV parser to include CVSSv3.1 data headers

docs/content/en/integrations/parsers/file/anchore_grype.md
Adding a parser guide, links and a sample code block with acceptable JSON for Grype.
See Wiki: https://internal-docs.defectdojo.com/en/engineering/list-of-parsers/anrchore-grype
=> add parser template to anchore_grype.md

dojo/reports/views.py
[sc-2338]
This fix allows the user export to excel and csv the findings properly. The error is now wrapped in a `try...catch` statement and the exception is being logged for visibility.
=> Excel Export throws 500 error code

dojo/templates/dojo/product.html
[sc-2297]
Now the code validates that `data`  within render function, in criticality column, should have a value. According to datatables documentation:  https://datatables.net/manual/tech-notes/4#Resolution
=> Validate undefined and null value in criticality column table products

dojo/tools/sarif/parser.py, unittests/scans/sarif/codeQL-output.sarif, unittests/tools/test_sarif_parser.py
1. Fixed a CodeQL report processing error when there was no "region" field in the report
2. Improved unittest
3. Added more information for description. 
4. Added localizaton
=> Add translation, fix bug, and some improvements for SARIF parser

docs/content/en/integrations/parsers/file/rusty_hog.md
advance the description of rustyhog
=> advance the description of rustyhog

docs/content/en/integrations/burp-plugin.md
Adding a sunset notice to Burp Plugin documentation
=> add sunset notice to burp-plugin.md

docs/content/en/getting_started/architecture.md
=> Fix typo in docs

dojo/decorators.py
typo error in `dojo_ratelimit` function
fixes #8976
Fixed typo bug in dojo_ratelimit function
**Checklist**
Please clear everything below when submitting your pull request, it's here purely for …
=> Correct typo in rate limiting

dojo/tools/nuclei/parser.py, unittests/scans/nuclei/multiple_v3.json, unittests/tools/test_nuclei_parser.py
see issue https://github.com/DefectDojo/django-DefectDojo/issues/8920
=> fix nuclei #8920

docs/content/en/integrations/parsers/file/trivy_operator.md
Add docs for the trivy dojo report operator.
=> add trivy-dojo-operator docs

dojo/utils.py
This fixes the issues described here: https://github.com/DefectDojo/django-DefectDojo/issues/9012 
**Checklist**
Please clear everything below when submitting your pull request, it's here purely …
=> fix metrics to also calculate risk acceptance and duplicate findings.

dojo/tools/harbor_vulnerability/parser.py, unittests/scans/harbor_vulnerability/harborapipip.json, unittests/tools/test_harbor_vulnerability_parser.py
=> fix harbor according to issue #9014

dojo/tools/bundler_audit/parser.py
=> Fix Bundler parser

dojo/tools/nuclei/parser.py
=> hotfix for nuclei to get it back working #9017

dojo/filters.py
This change maintains the original query set passed into the filter
=> Update Finding/Product SLA filters

dojo/api_v2/views.py
Small rewrite to more compact a readable ViewSets.
More readable code ~ less bugs
Note: There is no effect on the API schema.
=> API: Use more readable ViewSets

dojo/models.py, dojo/remote_user.py, dojo/tools/qualys_webapp/parser.py
Inspired by https://github.com/DefectDojo/django-DefectDojo/pull/9002#discussion_r1399291562
=> Clean dojo.settings imports

dojo/settings/settings.dist.py
Take a look at the following issue: https://github.com/DependencyTrack/dependency-track/issues/1915
=> :bug: fix dependencytrack deduplication

helm/defectdojo/templates/django-deployment.yaml, helm/defectdojo/templates/django-service.yaml
Fix the way ports are referenced in the Helm chart by using port names.
Fix also the port name of the uWSGI container which was the same as the NGINX container.
Add a port for NGINX exporter in Service to allow ServiceMonitor, same idea as this closed PR #8240
Please update any documentation when needed in the [documentation folder](https://github.com/DefectDojo/django-DefectDojo/tree/dev/doc …
=> Use port names in Helm chart

dojo/tools/trivy/parser.py, unittests/tools/test_trivy_parser.py
=> Trivy: Add k8 cluster resource objects

docs/content/en/integrations/importing.md
fix some typos in importing documentation
=> fix typos in importing documentation

.github/workflows/release-drafter.yml
There are no releases on the `dev` branch
**Checklist** …
=> Drop DEV branch from release-drafter

docs/content/en/integrations/parsers/file/checkov.md
Fixed version of closed PR https://github.com/DefectDojo/django-DefectDojo/pull/8798
=> Update checkov.md with corrected typo

dojo/tools/zap/parser.py
=> :bug: fix zap, issue #9242

docs/content/en/contributing/how-to-write-a-parser.md, docs/content/en/contributing/parser-documentation-template.md, unittests/test_parsers.py
New pull request containing parser documentation template, and expanded guide on writing parser documentation.
Closes #8960
=> Parser guideline updates

dojo/tools/cyclonedx/parser.py, unittests/scans/cyclonedx/issue_9277.json, unittests/tools/test_cyclonedx_parser.py
=> 🐛CycloneDX: Add default for description

dojo/settings/settings.dist.py
=> :bug: fix deduplication for trivy, #9290

dojo/tools/kiuwan/parser.py, unittests/scans/kiuwan/issue_9308.csv, unittests/tools/test_kiuwan_parser.py
=> :bug: fix kiuwan

dojo/db_migrations/0196_notifications_sla_breach_combined.py
Solution for https://github.com/DefectDojo/django-DefectDojo/pull/8659#issuecomment-1885748955
=>  Fix db migration 0195/0196

dojo/remote_user.py, dojo/settings/settings.dist.py, unittests/test_remote_user.py
- Enabler for https://github.com/DefectDojo/django-DefectDojo/pull/8691#issuecomment-1725578410 #9264
- Simplify the settings section for easier testing, but not breaking functionality
=> Unittests for REMOTE_USER

dojo/tools/semgrep/parser.py, unittests/scans/semgrep/issue_8435.json, unittests/tools/test_semgrep_parser.py
=> :bug: Semgrep: Accommodate description snippets

unittests/scans/trivy/issue_9333.json, unittests/tools/test_trivy_parser.py
Raise testcoverage to proof issue #9333 works fine
=> Trivy Parser: Expand Unit Tests

dojo/tools/asff/parser.py, unittests/scans/asff/many_vulns.json, unittests/scans/asff/one_vuln.json, unittests/tools/test_asff_parser.py
Followup for this PR:
https://github.com/DefectDojo/django-DefectDojo/pull/8742
=> Update ASFF parser to create endpoints

docs/content/en/integrations/parsers/file/redhatsatellite.md, dojo/tools/redhatsatellite/__init__.py, dojo/tools/redhatsatellite/parser.py, unittests/scans/redhatsatellite/many_findings.json, unittests/scans/redhatsatellite/no_findings.json, unittests/scans/redhatsatellite/one_finding.json, unittests/tools/test_redhatsatellite_parser.py
=> :sparkles: add redhatsatellite parser

dojo/tools/npm_audit/parser.py, unittests/scans/npm_audit/issue_7897.json, unittests/tools/test_npm_audit_parser.py
=> :bug: fix npm audit, issue #7897

dojo/tools/cyclonedx/parser.py, unittests/scans/cyclonedx/issue_8022.json, unittests/tools/test_cyclonedx_parser.py
=> :bug: fix missing recommendation for cyclonedx

dojo/templates/base.html
=> API: Remove v2 OpenAPI2 Docs from menu

dojo/db_migrations/0197_parser_merge.py
@mtesauro, @Maffooch, @dsever could you please review the PR fast? It is a fix for release v2.31.0 upcomming on monday.
=> :bug: fix migration

dojo/settings/settings.dist.py, dojo/tools/mobsf/parser.py
fixes:
- issue #7936 
- https://github.com/DefectDojo/django-DefectDojo/blob/master/unittests/scans/mobsf/allsafe.json can't be uploaded without throwing an error because of severity "good".
=> :bug: fix mobsf deduplication and severity mapping

dojo/filters.py
Make the filtration of acceptable statuses defined in a SLA violation a bit tighter
[sc-4470]
=> Update SLA Violation Filter query

helm/defectdojo/Chart.lock, helm/defectdojo/Chart.yaml
=> Revert psqlha version from v13 to v9

dojo/tools/snyk/parser.py, unittests/scans/snyk/snykcontainer_issue_epss.json, unittests/tools/test_snyk_parser.py
Follow up for closed #9527.
This PR adds support for importing the EPSS score from Snyk files import.
=> :tada: Snyk epss update

dojo/tools/qualys/csv_parser.py
The qualys parser was adding incorrect CVE from previous findings 
[sc-4582]
=> Qualys: Correct CVE assignment

dojo/tools/clair/clair_parser.py, dojo/tools/clair/clairklar_parser.py, dojo/tools/clair/parser.py
based on the [comment](https://github.com/DefectDojo/django-DefectDojo/pull/9522#discussion_r1508265527)  from @cneill I wanted to split also Clair
=>  🔨 restructure clair parser

.github/workflows/test-helm-chart.yml
This PR fixes Helm testing issues
e.g. https://github.com/DefectDojo/django-DefectDojo/pull/9551
Sorry for delay I had to find time to replicate exact behavior.
=> [HELM CT] Update component versions

dojo/reports/urls.py, dojo/reports/views.py, dojo/templates/dojo/finding_pdf_report.html
[sc-2860]
This changes converted the function views (HTML, CSV and Excel) exports to classes
Also the CSV and Excel export now contains tags in a column.
=> Func views to class based views in finding exports

docs/content/en/integrations/parsers/file/crunch42.md, dojo/settings/settings.dist.py, dojo/tools/crunch42/parser.py, unittests/scans/crunch42/crunch42_many_findings.json, unittests/scans/crunch42/crunch42_many_findings2.json, unittests/tools/test_crunch42_parser.py
[sc-2729]
Added 42Crunch parser, docs, and unittests using `DEDUPE_ALGO_UNIQUE_ID_FROM_TOOL` as dedupe field
=> Added crunch42 parser

components/yarn.lock
=> remove flotaxis, #9700

.github/workflows/k8s-tests.yml
This test will no longer be supported per https://github.com/DefectDojo/django-DefectDojo/discussions/9690
[sc-4779]
=> Helm: Remove PSQLHA Test

.github/workflows/ruff.yml
Improve Ruff output for GitHub Action
=> Ruff: better log output for GitHub Actions

dojo/forms.py, dojo/models.py, dojo/tools/burp_api/parser.py, dojo/tools/checkmarx/parser.py, dojo/tools/sslyze/parser_json.py, dojo/tools/sslyze/parser_xml.py, dojo/user/views.py, pyproject.toml
Remove E713 from `lint.ignore` and fix the findings
=> Ruff: Solve E713

dojo/engagement/views.py, dojo/filters.py, dojo/forms.py, dojo/templates/dojo/add_findings_as_accepted.html, dojo/templates/dojo/view_risk_acceptance.html, dojo/widgets.py
[sc-3336]
this feature imporves the UI in risk_acceptance view in the part where the user accepts aditional findings. Now a table is shown when the user can select multiple findings and search or filter by multiple fields.
=> improve risk acceptance UI (accept aditional findings)

dojo/endpoint/views.py, pyproject.toml
Remove F601 from `lint.ignore` and fix the finding
=> Ruff: Solve F601

dojo/tools/wazuh/parser.py, unittests/tools/test_wazuh_parser.py
Reproduce:
Import https://github.com/DefectDojo/django-DefectDojo/blob/master/unittests/scans/wazuh/many_findings.json in the GUI
=> :bug: fix wazuh date

dojo/settings/settings.dist.py
leftover from: https://github.com/DefectDojo/django-DefectDojo/pull/9355
=> remove Clair Klar Scan deduplication

dojo/tools/snyk/parser.py, dojo/tools/snyk_code/parser.py
=> :bug: fix snyk, multiple cwes

requirements.txt
It looks like supervisor is not used
=> remove supervisor

.flake8
Apply F841 outside of migrations that are already used
=> Flake8: Change F841

.github/workflows/k8s-tests.yml
There has been wrongly configured k8s redis test.
=> Fix: wrong parameters for k8s redis test

.flake8, dojo/tools/scout_suite/parser.py
Remove E704 from `.flake8` and fix the finding
=> Flake8: Solve E704

dojo/models.py, dojo/tools/contrast/parser.py, dojo/tools/generic/parser.py, dojo/tools/gitlab_dast/parser.py, dojo/tools/microfocus_webinspect/parser.py, dojo/tools/pmd/parser.py, dojo/tools/spotbugs/parser.py, dojo/tools/trivy/parser.py, dojo/tools/trivy_operator/parser.py, dojo/tools/trustwave/parser.py, dojo/tools/trustwave_fusion_api/parser.py, pyproject.toml
Add support for https://docs.astral.sh/ruff/rules/#flynt-fly in Ruff
=> Ruff: add FLY

requirements.txt
It looks like xlrd is not really used.
=> remove xlrd

dojo/decorators.py, dojo/jira_link/helper.py, dojo/models.py, dojo/tools/awssecurityhub/parser.py, dojo/tools/threagile/parser.py, pyproject.toml, tests/base_test_class.py, unittests/tools/test_threagile_parser.py
Add support for some parts of https://docs.astral.sh/ruff/rules/#tryceratops-try in Ruff.
All `TRY` rules are good but so much of manual fixes are needed.
=> Ruff: add some TRY

docs/content/en/getting_started/upgrading/2.32.md
Colon in front matter removed to fix broken docs build
=> fix doc breaking due to colon in front matter

dojo/tools/npm_audit_7_plus/parser.py, unittests/test_apply_finding_template.py
During multiple merges we missed some Flake8 rules
=> Flake8: Fix leftover of W504 and E402

.github/workflows/fetch-oas.yml, .github/workflows/integration-tests.yml, .github/workflows/rest-framework-tests.yml
Addressing sporadic unit test failures in response to https://github.com/actions/runner-images/issues/9557
=> GHA: Update `docker-compose` refs to `docker compose`

dojo/tools/horusec/parser.py, unittests/scans/horusec/issue_9939.json, unittests/tools/test_horusec_parser.py
=> fix horusec null characters issue, #9939

dojo/tools/anchore_grype/parser.py, unittests/scans/anchore_grype/issue_9942.json, unittests/tools/test_anchore_grype_parser.py
=> fix anchore_grype null characters issue, #9942

.dryrunsecurity.yaml
Minor update to DryRun Security config
=> Updated DryRun Security config

dojo/templates/dojo/findings_list_snippet.html, dojo/templates/dojo/view_test.html, dojo/tools/checkmarx_one/parser.py, unittests/scans/checkmarx_one/vulnerabilities_from_scan_results.json, unittests/tools/test_checkmarx_one_parser.py
Adding some additional parsing for different report formats offered by Checkmarx One
[sc-5414]
=> Checkmarx One: Add additional parsing for different report formats

dojo/settings/settings.dist.py
https://access.redhat.com/articles/explaining_redhat_errata 
--> Add RHBA and RHEA
--> Also FEDORA
=> advance vulnerability urls

dojo/wsgi.py, ruff.toml
Add T10 checker but mute on the places where it is needed.
https://docs.astral.sh/ruff/rules/#flake8-debugger-t10
=> Ruff: add T10

docker/install_chrome_dependencies.py, ruff.toml
Add and fix INP rule
https://docs.astral.sh/ruff/rules/#flake8-no-pep420-inp
=> Ruff: add and fix INP

dojo/api_v2/views.py, dojo/authorization/authorization.py, dojo/decorators.py, dojo/engagement/views.py, dojo/finding/views.py, dojo/metrics/views.py, dojo/notifications/views.py, dojo/product/views.py, dojo/reports/views.py, dojo/risk_acceptance/helper.py, dojo/survey/views.py, dojo/test/views.py, dojo/views.py, ruff.toml
Add new rule: RSE
https://docs.astral.sh/ruff/rules/#flake8-raise-rse
=> Ruff: add and fix RSE

dojo/templates/dojo/custom_html_toc.html, dojo/templates/dojo/endpoint_pdf_report.html, dojo/templates/dojo/engagement_pdf_report.html, dojo/templates/dojo/finding_pdf_report.html, dojo/templates/dojo/product_endpoint_pdf_report.html, dojo/templates/dojo/product_pdf_report.html, dojo/templates/dojo/product_type_pdf_report.html, dojo/templates/dojo/test_pdf_report.html
Expand on the whitespace filtering in the table of contents of a given report
[sc-7039]
=> Report ToC: Expand on whitespace escaping

requirements.txt
it looks like coverage is not used anymore
=> remove coverage from requirements.txt

dojo/templates/dojo/view_product_details.html
Cosmetic UX change - metrics in product view are now clickable and redirect to findings view with severity filter
=> Cosmetic UX change - clickable product metrics - redirect to findings with severity filter

helm/defectdojo/templates/_helpers.tpl
Remove leftover from debugging
=> fix(helm): Remove leftover from debugging (db-migration-checker)

dojo/cred/views.py, dojo/endpoint/views.py
Taking over for #10664 as these changes must go into `bugfix`, not `master
Closes #10664 
[sc-7039]
=> Permission fixes

dojo/tools/nmap/parser.py, unittests/tools/test_nmap_parser.py
=> :bug: fix nmap parser, add script output #10456

dojo/utils.py, ruff.toml
Add Python Linter Error rules and fix one https://docs.astral.sh/ruff/rules/#error-e_1
=> Ruff: Add and fix PLE

dojo/finding/helper.py, dojo/management/commands/rename_mend_findings.py, dojo/tools/api_bugcrowd/parser.py, dojo/utils.py, ruff.toml
Fix formatting for logging https://docs.astral.sh/ruff/rules/#flake8-logging-format-g
=> Ruff: Add and fix G001 and G002

dojo/models.py, ruff.toml
Add and fix RUF025: https://docs.astral.sh/ruff/rules/unnecessary-dict-comprehension-for-iterable/
=> Ruff: Add and fix RUF025

helm/defectdojo/templates/initializer-job.yaml, helm/defectdojo/values.yaml
=> fix(helm): Break circular dependency

helm/defectdojo/templates/_helpers.tpl, helm/defectdojo/values.yaml
```markdown
This Pull Request introduces a critical fix related to the resource allocation for the `dbMigrationChecker` container in the `defectdojo` chart. Previously, the `dbMigrationChecker` container incorrectly inherited resource limits from the `uwsgi` container, which could lead to potential performance and reliability issues.
The resource allocation configuration for the `dbMigrationChecker` container has been decoupled from the `uwsgi` container. This ensures that `dbMigrationChecker` has its own dedicated resources, thereby preventing any unintended resource sharing or conflicts.
- **Previous Configuration**: Resource values for the `dbMigrationChecker` container were inherited from `.Values.django.uwsgi.resources`.
```yaml
{{- toYaml .Values.django.uwsgi.resources | nindent 10 …
=> upd: [helm] resource optimization

dojo/tools/aqua/parser.py, unittests/scans/aqua/issue_10849.json, unittests/tools/test_aqua_parser.py
=> :sparkles: add epss for aqua parser #10849

readme-docs/KUBERNETES.md
Fixed the replica reference for celery(beat & workers). The old reference doesn't exist based on the fields in the helm values file.
I've tested and the replicas are created as expected using the new reference. Also `redis.replicas` is not valid. The defectdojo helm chart doesn't use this field at all and only one replica would be created regardless. 
Willing to work with someone to fix further issues relating to K8S deployment as I plan to deploy defectdojo on K8s within the next few days
If this is a new parser, [the parser …
=> Fixed replica reference for celery worker in Kubernetes.MD

ruff.toml
Merge single rules to one (+ add exception for not fixed ones)
=> fix(ruff): consolidate RUF rules

dojo/api_v2/exception_handler.py
JSON parsing errors can be too verbose. This PR makes parser errors less verbose
[sc-7463]
=> JSON Parsing Errors: Make errors less verbose

helm/defectdojo/templates/network-policy.yaml
Previously created [PR to the dev](https://github.com/DefectDojo/django-DefectDojo/pull/10869)
=> [Helm] Fix typo in ingress netpol

dojo/tools/semgrep/parser.py, unittests/scans/semgrep/high-medium-low-severities.json, unittests/tools/test_semgrep_parser.py
Semgrep has added support for a few more severities that need to be supported
[sc-7576]
=> Semgrep Parser: Add new severities

README.md
[sc-7802]
Updating readme moderators to current set, move Jannik to Hall of Fame.
=> remove mods, add Jannik to Hall of Fame

dojo/templates/base.html, dojo/templates/dojo/support.html
Modified Get Support button with new icon and Upgrade text.
Updated the Support page Pro section with newer items and added help text where relevant.
Changed Meet the Creators button to Go Pro!
[sc-7805]
=> Update support text and buttons

.github/ISSUE_TEMPLATE/support_request.md
=> Update link to Slack in Issue template

dojo/tools/osv_scanner/parser.py
Add some safer dict access
[sc-8021]
=> OSV Parser: Robustify

docs/content/en/changelog/changelog.md
Staging changes to the pro docs for 2.41.2 - if there are any Pro features or UX-affecting OS features that need to be noted in the changelog, please add them to this PR :)
=> [docs] Pro Docs release notes - 2.41.2

dojo/api_v2/serializers.py
=> fix(ruff_sim): Wrong handling non-file API import

dojo/api_v2/serializers.py
=> api spec: SLA days remaining can be null

docs/content/en/customize_dojo/user_management/configure_sso.md, docs/content/en/open_source/archived_docs/integrations/social-authentication.md, docs/content/en/open_source/rate_limiting.md
Fix some broken links (and some auto-linting done by VSCode)
=> Docs: fix broken links

readme-docs/CONTRIBUTING.md
The link to the parser creation documentation is now not working. So, just changing that to the one that works.
**Checklist**
- enhancement
- performance
- feature
- bugfix
- dependencies
- settings_changes (when the PR introduces changes or new …
=> corrected link for parser guide

dojo/forms.py, dojo/management/commands/jira_refactor_data_migration.py, dojo/tools/gitleaks/parser.py, dojo/tools/sslscan/parser.py, dojo/tools/sslyze/parser_xml.py, dojo/tools/trufflehog3/parser.py, dojo/user/validators.py, dojo/utils.py, ruff.toml, tests/close_old_findings_dedupe_test.py, tests/close_old_findings_test.py, tests/dedupe_test.py, unittests/tools/test_jfrog_xray_api_summary_artifact_parser.py, unittests/tools/test_meterian_parser.py, unittests/tools/test_snyk_parser.py, unittests/tools/test_stackhawk_parser.py
Add rule [explicit-string-concatenation (ISC003)](https://docs.astral.sh/ruff/rules/explicit-string-concatenation/#explicit-string-concatenation-isc003) and fix it. And merge all `ISC*` rules
=> Ruff: Add and fix ISC003 + merge ISC

docs/config/_default/menus/menus.en.toml, docs/content/en/about_defectdojo/contact_defectdojo_support.md, docs/content/en/changelog/changelog.md, docs/content/en/open_source/installation/running-in-production.md
- add deprecation notice for Async import in open-source
- add 'Contact Support' to top menu
- update changelog 2.43.4 
[sc-10226]
=> Async Deprecation Notice + additional docs changes

docs/content/en/open_source/contributing/parser-documentation-template.md
- This pull request updates the parser-documentation-template.md file to improve structure and detail. The changes include:
- Updated the format of the template to include more details.
- Added placeholders and general instructions for each section to make it easier for contributors to create new parser documentation.
- Added a numbered list to identify all fields parsed or not parsed for contributors to follow.
- Included general guidance on how to map fields, handle deduplication, and manage occurrences in the parser.
This change is purely documentation-related and should not affect any functionality or code in DefectDojo.
=> Update parser documentation template to include additional detail.

dojo/benchmark/urls.py, dojo/benchmark/views.py
=> :bug: fix benchmark internal server error

dojo/templatetags/display_tags.py, ruff.toml, unittests/tools/test_semgrep_parser.py
Add rule [zip-without-explicit-strict (B905)](https://docs.astral.sh/ruff/rules/zip-without-explicit-strict/#zip-without-explicit-strict-b905) and fix it
=> Ruff: Add and fix B905

dojo/tools/openvas/csv_parser.py, dojo/tools/openvas/xml_parser.py, unittests/scans/openvas/many_vuln.xml, unittests/tools/test_openvas_parser.py
OpenVAS improvements:
- strip spaces from hostname, fixes #11904
- create endpoints in xml parser, fixes #11695
- use string based severity value in XML parser (same as in CSV parser), fixes #11695
- add IP name to description, somewhat fixes #11695 
unit tests adjusted
=> OpenVAS endpoint and severity improvements

dojo/tools/gitlab_dast/parser.py, unittests/scans/gitlab_dast/issue_12050.json, unittests/tools/test_gitlab_dast_parser.py
=> :bug: fix gitlab dast to parse request response pair #12050

dojo/api_v2/views.py, dojo/engagement/views.py, dojo/finding/views.py, dojo/jira_link/helper.py, dojo/management/commands/csv_findings_export.py, dojo/management/commands/import_surveys.py, dojo/tools/blackduck/importer.py, dojo/tools/blackduck_binary_analysis/importer.py, dojo/utils.py, ruff.toml, tests/Import_scanner_test.py, tests/base_test_class.py
Add rule [builtin-open (PTH123)](https://docs.astral.sh/ruff/rules/builtin-open/#builtin-open-pth123),
merge it
and fix `/dojo`.
It is still problematic in `/unittests`, but I would prefer not to change that many files in one PR.
=> Ruff: Add PTH123, merge PTH, fix in `/dojo`

dojo/tools/ort/parser.py
=> :tada: resolve todo in ort parser

dojo/jira_link/helper.py
- Following up with an extension of #11125 
- Updated a variable name to not conflict with the function being called
[sc-10710]
=> Jira Finding Groups:  Confusion on strings vs functions

ruff.toml, unittests/dojo_test_case.py, unittests/test_apiv2_scan_import_options.py, unittests/test_endpoint_meta_import.py, unittests/test_factory.py, unittests/test_import_reimport.py, unittests/test_importers_closeold.py, unittests/test_importers_importer.py, unittests/test_parsers.py, unittests/test_rest_framework.py
Next iteration for [builtin-open (PTH123)](https://docs.astral.sh/ruff/rules/builtin-open/#builtin-open-pth123)
=> Ruff: Fix PTH123 in `unittests` (exclude `unittests/tools`)

docs/content/en/changelog/changelog.md
Changelog update - removes old versions from navigator and notes Beta UI change for 2.44.4
=> changelog 2.44.4

dojo/finding/views.py
beautifies try except block in download_finding_pic
=> :lipstick: beautify download_finding_pic in finding view

docs/package-lock.json, docs/package.json
Duplicate of #12175 on the bugfix branch
=> Vite: Bump to 6.2.5

readme-docs/DOCKER.md
The use `Exploitation` was likely not intended
=> Update wording in application versioning

docs/content/en/connecting_your_tools/parsers/file/immuniweb.md, dojo/tools/immuniweb/parser.py, unittests/scans/immuniweb/ImmuniWeb-multiple-vuln.json, unittests/tools/test_immuniweb_parser.py
=> immuniweb json parser

dojo/templates/base.html
No rocket science, just use `.min.js` and `.min.css` if exist
=> feat(perf): Speed-up loading by using smaller resources (js,css)

dojo/settings/settings.dist.py
https://support.hcl-software.com/csm?id=kb_article&sysparm_article=KB0108401
https://help.hcl-software.com/commerce/8.0.0/install/refs/rigrecfix_security.html
=> Implement HCL Commerce KB vulnids

dojo/templates/dojo/engagement_pdf_report.html
=> :bug: Fix Django template engagement_pdf_report #12201

dojo/tools/aqua/parser.py, unittests/tools/test_aqua_parser.py
simplifies parser
fixes #12181
=> :lipstick: :beetle: Fix Aqua parser severity justification

dojo/settings/settings.dist.py
e.g.
- https://alas.aws.amazon.com/AL2/ALAS-2025-2807.html
- https://alas.aws.amazon.com/AL2/ALASTOMCAT9-2025-016.html
- https://alas.aws.amazon.com/AL2/ALASPYTHON3.8-2025-018.html
=> :tada: Add Amazon Linux Security Center advisory to vulnid

dojo/templatetags/display_tags.py
https://cert-portal.siemens.com/productcert/html/ssa-503939.html
https://cert-portal.siemens.com/productcert/html/ssa-187636.html
https://vulners.com/slackware/SSA-2025-074-01
https://vulners.com/slackware/SSA-2025-073-01
=> :bug: Differentiate between slackware and siemens vulnid

docs/content/en/customize_dojo/user_management/configure_sso.md
saml-tracer looks like a useful troubleshooting tool.
=> saml: provide link to saml-tracer browser add-on

dojo/settings/settings.dist.py, dojo/templatetags/display_tags.py
https://mirrors.aliyun.com/alinux/cve/alinux2.xml?spm=a2c63.p38356.0.0.12dd1431YixbqA&file=alinux2.xml
e.g. https://mirrors.aliyun.com/alinux/cve/alinux2-sa-20250007.xml
=> Implement Albibaba Linux vulnids

docs/content/en/customize_dojo/user_management/configure_sso.md
- fixing a typo on SSO page
- explaining google a bit better
=> [docs] sso maintenance

docs/content/en/connecting_your_tools/connectors/connectors_tool_reference.md
Just some minor tweaks to the Semgrep connector docs for Dojo Pro
=> Minor Semgrep connector docs tweaks

.github/workflows/release-nightly-dev.yml
Perform nightly builds only in core repository
=> fix(nighly): Avoid forks

helm/defectdojo/templates/_helpers.tpl, helm/defectdojo/templates/celery-beat-deployment.yaml, helm/defectdojo/templates/celery-worker-deployment.yaml, helm/defectdojo/templates/django-deployment.yaml, helm/defectdojo/templates/initializer-job.yaml, helm/defectdojo/templates/sa.yaml, helm/defectdojo/templates/tests/unit-tests.yaml, helm/defectdojo/values.yaml
This PR allows to disable the Kubernetes ServiceAccount creation via the Helm chart values, and specify an external one. 
`helm template .` with the following combinaison of values. Results has been compared to what is rendered with the upstream Helm Chart code.
- (default values) `create = true`: renders exactly the same than the upstream chart 
- `create=true` `name=mycustomname`: same manifests than the upstream chart, but the created SA name has changed
- `create=false` `name=externalsa`: the ServiceAccount manifest is not rendered anymore, all the resources …
=> feat(helm): allow to use an external serviceAccount

README.md
=> Update contributors in README.md

dojo/tools/hcl_appscan/parser.py
=> :bug: fix missing CWE in HCL Appscan #12468

dojo/tools/cyberwatch_galeax/parser.py, unittests/tools/test_cyberwatch_galeax_parser.py
Fix bug causing the Cyberwatch (galeax) parser to not show up in the parser's list in the UI (Class name didn't match the parser folder after the changes)
=> bugfix cyberwatch parser

dojo/settings/settings.dist.py, dojo/templatetags/display_tags.py
https://mirrors.aliyun.com/alinux/3/cve/alinux3.xml?spm=a2c63.p38356.0.0.12dd1431YixbqA&file=alinux3.xml
=> Alibaba Cloud Linux 3 Security Advisory

dojo/tools/openvas/csv_parser.py, unittests/tools/test_openvas_parser.py
Adresses #12447
Ran `python manage.py test unittests.tools.test_openvas_parser --keepdb` tests which all passed.
=> Include CVSS score in finding when using OpenVAS csv parser

dojo/tools/ms_defender/parser.py
=> Fixing linter issue

dojo/metrics/views.py
Fixes #12534 and #12399
Simple metrics was only showing findings closed in the selected month when they were also opened in the selected month.
I t could be that was intentional at the time it was implemented, but I believe it makes more sense to count all findings that were closed in that month regardless of when they were opened.
=> simple metrics: count closed findings not opened in current month

dojo/settings/settings.dist.py
https://euvd.enisa.europa.eu/vulnerability/EUVD-2025-17599
=> :tada: Add EUVD vulnid

dojo/jira_link/helper.py, dojo/templates/issue-trackers/jira_full/jira-description.tpl, dojo/templates/issue-trackers/jira_full/jira-finding-group-description.tpl, dojo/templates/issue-trackers/jira_limited/jira-description.tpl, dojo/templates/issue-trackers/jira_limited/jira-finding-group-description.tpl
I made a mistake when making a commit in the previous PR so I decided to close it and create a clean one.
If you find something wrong, please change it directly.
=> Fix Finding_Text

dojo/settings/settings.dist.py
https://tailscale.com/security-bulletins
https://tailscale.com/security-bulletins#ts-2025-004
=> :tada: Add Tailscale vulnid

dojo/tools/twistlock/parser.py, unittests/scans/twistlock/findings_include_packages.json, unittests/scans/twistlock/no_vuln.json, unittests/scans/twistlock/one_vuln.json, unittests/tools/test_twistlock_parser.py
Parse compliances from Twistlock reports (and some more metadata).
Fixes #12769
=> twistlock: parse compliances

dojo/db_migrations/0236_finding_fix_available.py
Hi @mtesauro, @valentijnscholten and @Maffooch 
could you please merge this fast as this is a hotfix for the dev branch?
=> :bug: rebase dev branch db_migrations

dojo/tools/dependency_check/parser.py, unittests/tools/test_dependency_check_parser.py
Dependency Check includes some CVSS v3 fields to construct the vector manually. We should attempt to use it where we can
=> Dependency Check: Support CVSS v3

dojo/settings/settings.dist.py
https://advisories.ncsc.nl/advisory?id=NCSC-2025-0191
https://advisories.ncsc.nl/advisory?id=NCSC-2025-0232
=> :tada: Add NCSC vulnid

dojo/db_migrations/0238_finding_fix_available.py, dojo/models.py, dojo/settings/settings.dist.py
[#12793](https://github.com/DefectDojo/django-DefectDojo/pull/12793#issuecomment-3095418494)
=> :bug: Fix db_migration fix_available field to allow None

docs/assets/js/docsearch.js, docs/assets/scss/app.scss, docs/assets/scss/common/_custom.scss, docs/assets/scss/common/_variables-docsearch.scss, docs/config/_default/params.toml, docs/config/postcss.config.js, docs/layouts/partials/footer/script-footer-custom.html, docs/layouts/partials/header/header.html, docs/package-lock.json, docs/package.json
This PR adds [Algolia Docsearch](https://docsearch.algolia.com/) to our documentation, a crawler / search index builder which we can use to inform doc optimization efforts.  This crawler is hosted by Algolia for free.
- Better indexing will allow us to render more contextual search information - better categorization of results, for example
- Algolia also logs search queries on our docs site, and we can use this information to improve docs and optimize the results sent back.
This is a free service which is currently set up using my DefectDojo Inc credentials.
This tool requires us to add a public API key to the repo.  I'm anticipating some alarm bells, so here's an explanation of why this is necessary and how it works
- The API key is needed to fetch the scraped indices and return the …
=> [docs] Add Algolia Docsearch

dojo/tools/checkov/parser.py
=> checkov: add null check

README.md
We don't want to waste your time, so if you're unsure whether your hypothetical enhancement meets the criteria for approval, please file an issue to get pre-approval before beginning work on a PR.
Learn more here: https://github.com/DefectDojo/django-DefectDojo/blob/master/readme-docs/CONTRIBUTING.md#submission-pre-approval
If this is a new parser, [the parser guide](https://docs.defectdojo.com/en/open_source/contributing/how-to-write-a-parser/) may be worth (re)reading.
Please update any documentation when needed in the …
=> Updates ReadMe.MD

Dockerfile.django-alpine, Dockerfile.nginx-alpine, Dockerfile.nginx-debian
Increase Alpine in all used images
=> feat(docker): Use Alpine 3.22 in docker images

dojo/settings/settings.dist.py
https://cvepremium.circl.lu/vuln/wid-sec-w-2025-1468
=> :tada: Add wid-sec-w vulnid

dojo/engagement/views.py, dojo/test/views.py, unittests/test_import_reimport.py
If there was any mistake in the forms, UI did not provide any feedback.
If `DD_CREATE_CLOUD_BANNER=True`, it showed _Pro comes with support. ..._ but there was no information what can be wrong (not even in logs).
`View` had been validating forms, but it has not provided any feedback.
Now it createsa  regular error message.
=> fix(eng/test-validate_forms): Show error if form is not valid

dojo/tools/anchore_engine/parser.py, unittests/tools/test_anchore_engine_parser.py
https://github.com/DefectDojo/django-DefectDojo/issues/12633#issuecomment-3056091243
=> :tada: Add fix_available to AnchoreEngine

dojo/settings/settings.dist.py
=> Add SCA vulnid and fix example for SSA:

dojo/engagement/views.py, dojo/product/views.py, dojo/templates/dojo/snippets/engagement_list.html, dojo/templates/dojo/view_eng.html
=> :tada: Add fix_available information to engagement views

dojo/templates/dojo/view_test.html, dojo/test/views.py
=> :tada: Add number of fix_available information to test view

dojo/tools/aqua/parser.py, unittests/tools/test_aqua_parser.py
https://github.com/DefectDojo/django-DefectDojo/issues/12633
=> :tada: Add fix_available information to aqua parser #12633

dojo/tools/qualys_hacker_guardian/parser.py
=> Update the Qualys Hacker Guardian parser to be compatible with larger CSV files

dojo/tools/jfrog_xray_unified/parser.py, unittests/tools/test_jfrog_xray_unified_parser.py
=> :tada: Add fix_available information to jfrog xray unified parser #12633

dojo/tools/semgrep_pro/parser.py
=> ruff fixes

dojo/settings/settings.dist.py
=> :tada: Add OXAS-ADV- vulnid

dojo/finding/views.py, dojo/forms.py
Bulk Edit was not updating the `under_review` flag of the selected findings.
[sc-11768]
=> bulk edit: update under_review flag

dojo/jira_link/helper.py
=> Add an Engagement's branch_tag in Jira Epic's description

dojo/settings/settings.dist.py
e.g. 
https://aws.amazon.com/security/security-bulletins/AWS-2025-005
https://aws.amazon.com/security/security-bulletins/AWS-2025-007
=> Add AWS security bulletins to vulnid

docs/content/en/changelog/changelog.md
Updates Pro changelog for 2.50.4.
=> [docs] Pro changelog oct 3

dojo/engagement/views.py, dojo/forms.py
=> ui import: allow providing test title
