DefectDojo/django-DefectDojo

- dojo/fixtures/test_type.json
- dojo/forms.py
- dojo/templates/dojo/add_checkmarx_scan.html
- dojo/templates/dojo/import_scan_results.html
- dojo/tools/burp/parser.py
- dojo/tools/checkmarx/__init__.py
- dojo/tools/checkmarx/parser.py
- dojo/tools/factory.py
Sample Checkmarx XML file for testing: https://github.com/aaronweaver/scannerxml/blob/master/checkmarx-sample.xml
> Support for importing Checkmarx Findings

- ansible/roles/webserver/tasks/app.yml
- dojo/tools/burp/parser.py
- dojo/tools/checkmarx/parser.py
- dojo/tools/nessus/parser.py
- dojo/tools/nexpose/parser.py
- dojo/tools/veracode/parser.py
- dojo/tools/zap/parser.py
- setup.py
would someone please test with a sample file?
> changed xml to defusedxml

- setup.py
Hey guys, the new version of polymorphic breaks additional installed django apps.
> Fixed polymorphic version

- dojo/tasks.py
- reports.sh
Will submit PR with doc updates shortly.
> added reports script and updated tasks.py to work out of box

- docs/features.rst
- dojo/engagement/views.py
- dojo/models.py
- dojo/settings.dist.py
- dojo/templates/dojo/view_eng.html
- setup.bash
hey @grendel513 @cneill here is the new PR with merge conflicts removed.
I corrected the issues identified in the other PR as best I could.
Fixed spacing.
Added hasattr attribute to safely check if settings.ENABLE_DEDUPLICATION is available.
removed legacy save, however super save must be called twice for the many to many mappings.
added doc info on deduplication.
**Other things I added:**
added OSX support for setup.bash
added blank / null for the image field on findings
tested changes on Ubuntu 16.04 and OSX
> added deduplication of findings

- .travis.yml
- docker/docker-startup.bash
- tests/login.py
In travis define two environment vars: DOJO_ADMIN_USER & DOJO_ADMIN_PASSWORD. Set them to whatever you want.
> Travis and beginning of Selenium tests

- dojo/templates/dojo/report_builder.html
- dojo/templates/dojo/reports.html
- dojo/urls.py
@grendel513, I'm in a catch 22 for testing. I don't have an old settings file, so if I comment out URL_PREFIX I get in error from settings.py. I ran the urls.py and didn't hit any errors. Please let me know if you see other problems.
> Added has attr to URLs

- dojo/forms.py
- dojo/templates/dojo/view_test.html
- dojo/test/urls.py
- dojo/test/views.py
> Able to bulk update Findings from Test view page

- dojo/endpoint/urls.py
- dojo/endpoint/views.py
- dojo/forms.py
- dojo/templates/dojo/add_endpoint_meta_data.html
- dojo/templates/dojo/edit_endpoint_meta_data.html
- dojo/templates/dojo/view_endpoint.html
- tests/endpoint_metadata_tests.py
Implemented functionality for adding/editing metadata for endpoints.
> Added Endpoint metadata functionality

- setup.bash
Did a first pass at cleaning up the setup.bash script.
Biggest change was to consistently quoting Bash variables so that special characters don't mess up the various commands that use them.
> Initial setup.bash cleanup

- components/bower.json
- dojo/engagement/views.py
- dojo/forms.py
- dojo/metrics/urls.py
- dojo/metrics/views.py
- dojo/models.py
- dojo/settings.dist.py
- dojo/templates/base.html
- dojo/templates/dojo/metrics.html
- dojo/templatetags/event_tags.py
- dojo/tools/appspider/parser.py
Functional addition to add health dashboards to Dojo.
> Health Dashboards

- dojo/finding/views.py
Fixes #186 - stub findings with and without tags can now be deleted
> Fixes #186

- dojo/finding/views.py
- dojo/test/views.py
- dojo/utils.py
As I mentioned in slack, it seems to me that notes ought to have an @username type notification system like jira or github etc. Here's a go at making one.
> Add @mentions to notes

- dojo/utils.py
Basically a followup to https://github.com/OWASP/django-DefectDojo/pull/217#issuecomment-278454580
> improved @mention alerts

- dojo/user/views.py
One of three alternatives I'm providing for fixing #213. This would make the checkboxes actually work as advertised the first time.
> Fix213 - make checkboxes work on add

- dojo/finding/urls.py
- dojo/finding/views.py
- dojo/forms.py
- dojo/management/commands/csv_findings_export.py
- dojo/management/commands/jira_async_updates.py
- dojo/management/commands/push_to_jira_update.py
- dojo/models.py
- dojo/templates/dojo/defect_finding_review.html
- dojo/templates/dojo/view_eng.html
- dojo/templates/dojo/view_finding.html
- dojo/utils.py
Jira Updates:
- Added review process for validating tickets have been fixed correctly, if not the ticket can be re-opened
- Created a management script for marking tickets to be reviewed and setting an alert
Management Script:
- Export to csv will export the findings as a flat file 
Engagement Description:
- Added an optional engagement description field 
Will followup with another PR for updating documentation.
> Jira status update, management scripts and engagement description.

- dojo/forms.py
- dojo/management/commands/jira_async_updates.py
- dojo/models.py
- dojo/product/views.py
- dojo/templates/base.html
- dojo/templates/dojo/delete_tool_product.html
- dojo/templates/dojo/edit_tool_config.html
- dojo/templates/dojo/edit_tool_product.html
- dojo/templates/dojo/edit_tool_type.html
- dojo/templates/dojo/new_tool_config.html
- dojo/templates/dojo/new_tool_product.html
- dojo/templates/dojo/new_tool_type.html
- dojo/templates/dojo/tool_config.html
- dojo/templates/dojo/tool_type.html
- dojo/templates/dojo/view_product.html
- dojo/templates/dojo/view_tool_product.html
- dojo/tool_config/urls.py
- dojo/tool_config/views.py
- dojo/tool_product/urls.py
- dojo/tool_product/views.py
- dojo/tool_type/urls.py
- dojo/tool_type/views.py
- dojo/urls.py
Enhancement allows AppSec teams to track the various tools used by developers and what security services have been applied to the product.
A new configuration menu bar item is added and Tool Config and Jira added.
Tools consist of categories: SAST, DAST, IAST, Build Servers and Repo's.
Add your tools and services such as your jenkins, git and security tools.
On the product view screen, scroll down to the bottom to configure tools and URL's for that particular product.
> Tool Type and Product Enhancement

- cryptotest.py
- dojo/__init__.py
- dojo/cred/urls.py
- dojo/cred/views.py
- dojo/forms.py
- dojo/models.py
- dojo/product/views.py
- dojo/search/views.py
- dojo/templates/base.html
- dojo/templates/dojo/delete_cred_product.html
- dojo/templates/dojo/edit_cred.html
- dojo/templates/dojo/edit_cred_product.html
- dojo/templates/dojo/new_cred.html
- dojo/templates/dojo/new_cred_product.html
- dojo/templates/dojo/simple_search.html
- dojo/templates/dojo/view_cred.html
- dojo/templates/dojo/view_cred_details.html
- dojo/templates/dojo/view_cred_product.html
- dojo/templates/dojo/view_product.html
- dojo/templates/dojo/view_test.html
- dojo/templatetags/display_tags.py
- dojo/test/views.py
- dojo/tool_product/views.py
- dojo/urls.py
- dojo/utils.py
- setup.py
New credential manager added:
Product View
@mtesauro Can you add the config settings DB_KEY to ansible?
> Added Credential Manager

- CONTRIBUTING.md
- README.md
Fixed the markdown errors in README and changed the CONTRIBUTION file to have 'master' as the default branch.
> Fixed README and CONTRIBUTING file.

- setup.bash
Previous commit / pull request was incomplete.
> Added MySQL setup host and port variables in setup.bash (Issue #126)

- README.md
> Bugfix Links in README

- docs/dojo-production.rst
- docs/labels.rst
- dojo/engagement/views.py
- dojo/forms.py
- dojo/models.py
- dojo/templates/dojo/engagement.html
- dojo/templates/dojo/view_eng.html
- dojo/templates/dojo/view_product.html
- wsgi.py
- wsgi_params
Adds leads to tests.
Modifies /engagement for easier access to tests
**Changes Product models for tech manager, product manager, etc back to the legacy text fields since I'm not aware of a good way to currently / easily add their information**
> Adds leads to tests

- components/bower.json
- dojo/forms.py
- dojo/templates/base.html
- dojo/tools/nessus/parser.py
Additionally it removes an unneeded CSS import and usage in base HTML.  timeline.css is no longer needed and was causing 404 errors.
> Fixes #289

- dojo/filters.py
- dojo/forms.py
- dojo/metrics/views.py
- dojo/templates/dojo/metrics.html
fixes #331 and other metrics quirks and errors
> fixes #331 and other metrics quirks and errors

- dojo/fixtures/test_type.json
- dojo/forms.py
- dojo/templates/dojo/import_scan_results.html
- dojo/tools/factory.py
- dojo/tools/openvas_csv/__init__.py
- dojo/tools/openvas_csv/parser.py
Hello
Just added a new Import Scan on Tests. I saw that OpenVAS was missing so added a simple OpenVAS CSV import by cloning the generic one and changing the fields to reflect the columns of the OpenVAS CSV Results. 
Let me know if you want me to change anything.
Regards,
Daniel
> OpenVAS CSV Import on tests

- dojo/templates/dojo/view_product.html
Since the additional information view (meta-data list view) is not very clear and overlapping data, implemented the JQuery according control to make it clean.
> Implement the JQuery accordion control for the metadata list view

- dojo/forms.py
> Updating to add Info via the UI

- .travis.yml
> Push To DockerHub

- .travis.yml
> Fixing dockerhub login issue.

- dojo/models.py
- dojo/tasks.py
- dojo/tools/qualys/parser.py
- dojo/tools/qualyswebapp/parser.py
> Improves dedupe, fixes xml issue

- Dockerfile
Pull from local directory so that docker builds the correct version of DefectDojo.
> Docker file now pulls from local commit.

- dojo/models.py
> fix #438: UnicodeEncodeError by adding finding with german Umlauts

- components/package.json
> Pinning boostrap to v3 until v4 can be tested. This will address the CSS issue.

- dojo/models.py
- dojo/utils.py
> Adds JIRA push threshold when all issues are being pushed

- dojo/models.py
- dojo/utils.py
- setup.py
> Adds custom labels to JIRA via System Settings

- dojo/engagement/views.py
- dojo/tools/skf/parser.py
I make the date parsing like the other importers (although the other way works, just for making it all the same way) and fix the overwritten. After the parser imports the values, the view.py was overwritten the date with the start date of the test.
> Fix Date issue with imports

- dojo/forms.py
- dojo/product/views.py
> Fixes missing JIRA Conf on product edit

- dojo/forms.py
- dojo/models.py
- dojo/templates/dojo/view_finding.html
- dojo/utils.py
> Adding custom URI validator for tool and tools settings, fixed spelling.

- dojo/utils.py
> Dedupe circular fix 2

- setup.py
Align setup.py dependencies with what's listed in requirements.txt
> Aligned python dependencies with requirements.txt file

- dojo/engagement/views.py
- dojo/test/views.py
> Import tweak

- dojo/unittests/test_vcg_parser.py
Another unittest file to be moved and executed regularly. 
I believe, this was the last one.
> Moved and adapted VCG Scan parser unit tests

- dojo/engagement/views.py
- dojo/test/views.py
> Min change

- wsgi.py
Hi everyone,
this PR modifies the error of the wsgi.py file, which may lead to a failure to run.because migrating the settings.py dict.
The first time to PR :)
>  repair uwsgi error

- requirements.txt
- setup.py
> Bumped the Django version to the currently latest and greatest

- dojo/product/views.py
- dojo/templates/dojo/view_product.html
> Adding paging to closed engagements.

- dojo/filters.py
- dojo/management/commands/csv_findings_export.py
- dojo/management/commands/jira_async_updates.py
- dojo/management/commands/push_to_jira_update.py
- dojo/management/commands/stamp_finding_last_reviewed.py
- dojo/views.py
- requirements.txt
- setup.py
Updated the auditlog dependency due to a bug in auditlog when deployed with a MySQL database. This issue has been fixed in django-auditlog==0.4.0 (https://github.com/jjkester/django-auditlog/releases/tag/v0.4.0), and this PR just takes the latest version. 
All the changes in files other than requirements.txt are formatting adaptions (mostly PEP-8 compliant, except for long strings and similar) as well as removal of unused (auditlog) imports. 
Tests are green.
> Update auditlog dependency

- dojo/forms.py
- dojo/templates/dojo/import_scan_results.html
- dojo/tools/bandit/__init__.py
- dojo/tools/bandit/parser.py
- dojo/tools/checkmarx/parser.py
- dojo/tools/factory.py
- dojo/tools/ssllabs/__init__.py
- dojo/tools/ssllabs/parser.py
> Importer for SSLlabs and bandit.

- .travis.yml
- scripts/travis-smoke-test.sh
Added tests verifying entrypoint processes are startable and don't crash due to some misconfiguration.
> Dojo processes smoke tests

- dojo/metrics/views.py
- dojo/models.py
- dojo/templates/dojo/metrics.html
> Update links to correct 404 on Product Metric Page

- dojo/api.py
- dojo/object/parser.py
> Updating build details importer and artifact check bug.

- docs/upgrading.rst
- dojo/fixtures/test_type.json
> Updating documentation

- .travis.yml
- dojo/__init__.py
> Working on Version Tagging for Docker.

- README.md
- docs/upgrading.rst
- dojo/__init__.py
- dojo/fixtures/system_settings.json
- dojo/forms.py
- dojo/management/commands/system_settings.py
- dojo/models.py
- dojo/static/dojo/css/dojo.css
- dojo/templates/403.html
- dojo/templates/404.html
- dojo/templates/dojo/clear_finding_review.html
- dojo/templates/dojo/open_findings.html
- dojo/templates/dojo/product.html
- dojo/templates/dojo/view_finding.html
- dojo/templates/dojo/view_product.html
- dojo/templatetags/display_tags.py
- dojo/tools/openvas_csv/parser.py
- dojo/utils.py
- requirements.txt
- setup.py
> Grading for Products 

- dojo/forms.py
Fix missing tags in "Update Finding Template" and "Create Findings from Template"-function
> fix #338 missing tags in Template

- dojo/templatetags/display_tags.py
- dojo/utils.py
> Updating slack notifications.

- entrypoint_scripts/test/travis-integration-test.sh
- tests/check_status.py
This fixes a hidden error that occurred in all tests up to now. The exact point in time at which this error started is not known. The reason for the hidden error to occur was an incompatibility between the downloaded Selenium ChromeDriver version and the available Chrome version on Travis. 
The resolution for the main problem is to install the latest versions of Selenium as well as ChromeDriver.
Additionally, the integration test script has been adapted such that this kind of error is noticed more quickly. 
----
> Raise and fix Selenium test failures

- .gitignore
- ansible/dev-install/templates/settings.py.j2
- components/package.json
- dojo/settings/settings.dist.py
Removed the postinstall script, which was automatically added to the ``package.json`` file. 
Discussion of this PR took place in issue #545.
> Removed symlink-creating postinstall script, according to issue #545

- dojo/benchmark/urls.py
- dojo/benchmark/views.py
- dojo/forms.py
- dojo/models.py
- dojo/templates/dojo/benchmark.html
- dojo/templates/dojo/delete_benchmark.html
- dojo/templates/dojo/view_test.html
- dojo/templatetags/display_tags.py
- dojo/test/views.py
> Updating mass update and benchmarks

- dojo/models.py
- dojo/static/dojo/css/dojo.css
- dojo/templates/dojo/product_pdf_report.html
- dojo/templates/dojo/view_finding.html
- dojo/templatetags/display_tags.py
- dojo/tools/burp/parser.py
- requirements.txt
- setup.py
> Adding markdown support and burp importer multiple findings

- dojo/reports/views.py
- dojo/templates/dojo/product_pdf_report.html
- dojo/templates/dojo/view_product_details.html
- dojo/templates/report_base.html
- dojo/templatetags/display_tags.py
> HTML Report improvements

- dojo/celery.py
- dojo/settings/settings.dist.py
- dojo/tools/nessus/parser.py
> Celery Bug Fix

- .gitignore
> Remove DB files from git

- dojo/unittests/test_api_v1.py
I was in the process of debugging something when I decided to write a unittest to better understand how things work. Instead of throwing it to the trash can (API v2 is coming...), I decided to rather contribute these tests here. 
> Some APIv1 unittests

- dojo/management/commands/migrate_finding_templates.py
- dojo/management/commands/migrate_product_contacts.py
- dojo/management/commands/notify_isoc.py
- dojo/management/commands/run_scan.py
- dojo/wsgi.py
Adapted settings imports to consider Django's settings object instead of accessing the settings file directly.
> Adjusted settings imports

- dojo/templates/dojo/edit_product.html
- dojo/templates/dojo/new_eng.html
- dojo/templates/dojo/new_product.html
- dojo/templates/dojo/view_eng.html
- dojo/templates/dojo/view_product.html
> Adding markdown support for product and engagement

- dojo/settings/settings.dist.py
- dojo/templates/dojo/add_findings.html
- dojo/templates/dojo/add_template.html
- dojo/templates/dojo/apply_finding_template.html
- dojo/templates/dojo/edit_findings.html
- dojo/templates/dojo/edit_product.html
- dojo/templates/dojo/new_eng.html
- dojo/templates/dojo/new_product.html
- dojo/templates/dojo/promote_to_finding.html
- requirements.txt
- setup.py
- upgrade.bash
> New upgrade script, removed spell check from markdown

- dojo/templates/dojo/engagement.html
> Fixed Enagagement from all engagements

- dojo/templates/dojo/add_findings.html
- dojo/templates/dojo/add_template.html
- dojo/templates/dojo/apply_finding_template.html
- dojo/templates/dojo/edit_findings.html
- dojo/templates/dojo/promote_to_finding.html
- dojo/templates/dojo/view_finding.html
This PR adds an edit and save hotkey to the process of finding creation.
If you view a finding on the _view_finding.html_, you can press "**e**" to edit the finding. If you are in promote, edit, add from template or add a add new finding editor, you can press "**ctrl+s**" to save the finding. This behaviour helps in the work with findings or in the review.
> Add finding hotkeys

- dojo/benchmark/views.py
- dojo/finding/urls.py
- dojo/finding/views.py
- dojo/models.py
- dojo/templates/base.html
- dojo/templates/dojo/open_findings.html
- dojo/templates/dojo/view_eng.html
- dojo/templates/dojo/view_engagements.html
- dojo/templates/dojo/view_product_details.html
- dojo/utils.py
> Benchmark and menu updates

- dojo/finding/urls.py
- dojo/finding/views.py
- dojo/forms.py
- dojo/models.py
- dojo/product/views.py
- dojo/static/dojo/css/dojo.css
- dojo/templates/base.html
- dojo/templates/dojo/add_template.html
- dojo/templates/dojo/merge_findings.html
- dojo/templates/dojo/open_findings.html
- dojo/templates/dojo/product.html
- dojo/templates/dojo/templates.html
- dojo/templates/dojo/view_eng.html
- dojo/templates/dojo/view_engagements.html
- dojo/templates/dojo/view_finding.html
- dojo/templatetags/display_tags.py
- dojo/test/views.py
- dojo/tools/checkmarx/parser.py
- dojo/urls.py
- dojo/utils.py
> Merge findings and apply template remediation by CWE

- .flake8
- dojo/tools/nmap/parser.py
- dojo/unittests/test_endpoint_metadata.py
- [X ] Your code is pep8 compliant (Dojo's code isn't currently pep8 compliant, but we're trying to correct that)
> NMAP UDP none check

- ISSUE_TEMPLATE.md
- README.md
- entrypoint_scripts/common/dojo-shared-resources.sh
- setup.py
> Centospostgresfix2

- ISSUE_TEMPLATE.md
- README.md
- entrypoint_scripts/common/dojo-shared-resources.sh
- setup.py
Reverts DefectDojo/django-DefectDojo#600
> Revert "Centospostgresfix2"

- ISSUE_TEMPLATE.md
- README.md
- entrypoint_scripts/common/dojo-shared-resources.sh
- setup.py
Reverts DefectDojo/django-DefectDojo#615
> Revert "Revert "Centospostgresfix2""

- dojo/__init__.py
- dojo/celery.py
- dojo/finding/views.py
- dojo/forms.py
- dojo/settings/settings.dist.py
- dojo/system_settings/views.py
- dojo/tasks.py
- dojo/templates/dojo/system_settings.html
- dojo/templates/dojo/view_eng.html
- dojo/templates/dojo/view_product_details.html
- dojo/templates/dojo/view_test.html
- dojo/utils.py
> Celery status update, minor bug fixes

- dojo/finding/views.py
- dojo/templates/dojo/open_findings.html
- dojo/templates/dojo/product.html
- dojo/templates/dojo/view_test.html
- dojo/test/views.py
> Menu for product search page, merge findings in test

- dojo/finding/views.py
- dojo/forms.py
- dojo/jira_link/views.py
- dojo/models.py
- dojo/static/dojo/css/dojo.css
- dojo/templates/dojo/add_template.html
- dojo/templates/dojo/open_findings.html
- dojo/templates/dojo/templates.html
- dojo/templates/dojo/view_test.html
- dojo/utils.py
> Template match by CWE and title, jira notes update

- dojo/finding/views.py
- dojo/models.py
- dojo/templates/dojo/view_cred.html
- dojo/tools/dependencycheck/parser.py
- dojo/tools/retirejs/parser.py
- dojo/tools/snyk/parser.py
- dojo/tools/ssllabs/parser.py
- dojo/utils.py
> Minor bug fixes

- dojo/fixtures/test_type.json
- dojo/forms.py
- dojo/templates/dojo/import_scan_results.html
- dojo/tools/factory.py
- dojo/tools/trustwave_csv/__init__.py
- dojo/tools/trustwave_csv/parser.py
> Trustwaveloader

- dojo/filters.py
- dojo/finding/views.py
- dojo/forms.py
- dojo/models.py
- dojo/templates/dojo/open_findings.html
- dojo/templates/dojo/view_test.html
> bulk update improvements, and grade update

- dojo/api.py
- dojo/engagement/views.py
- dojo/filters.py
- dojo/finding/views.py
- dojo/forms.py
- dojo/models.py
- dojo/product/views.py
- dojo/tasks.py
- dojo/templates/dojo/up_risk.html
- dojo/templates/dojo/view_eng.html
- dojo/templates/dojo/view_engagements.html
- dojo/templates/dojo/view_finding.html
- dojo/templates/dojo/view_risk.html
- dojo/templates/dojo/view_test.html
Added create, update to engagement, test, finding, risk. Minor bug fixes.
> Risk Exceptions, created and update fields

- README.md
- SPONSORING.md
- dojo/forms.py
- dojo/models.py
- dojo/rules/urls.py
- dojo/rules/views.py
- dojo/templates/dojo/delete_rule.html
- dojo/templates/dojo/edit_rule.html
- dojo/templates/dojo/new_rule.html
- dojo/templates/dojo/new_rule2.html
- dojo/templates/dojo/rules.html
- dojo/utils.py
> Rules Rework

- dojo/cred/urls.py
- dojo/cred/views.py
- dojo/endpoint/views.py
- dojo/reports/views.py
- dojo/static/dojo/css/dojo.css
- dojo/templates/base.html
- dojo/templates/dojo/dashboard.html
- dojo/templates/dojo/engagement_pdf_report.html
- dojo/templates/dojo/paging_snippet.html
- dojo/templates/dojo/product_metrics.html
- dojo/templates/dojo/product_pdf_report.html
- dojo/templates/dojo/rules.html
- dojo/templates/dojo/snippets/engagement_list.html
- dojo/templates/dojo/view_cred_prod.html
- dojo/templates/dojo/view_eng.html
- dojo/templates/dojo/view_engagements.html
- dojo/templates/dojo/view_product.html
- dojo/templates/dojo/view_product_details.html
- dojo/templates/dojo/view_test.html
- dojo/templates/dojo/view_tool_product_all.html
- dojo/templates/report_base.html
- dojo/tool_product/urls.py
- dojo/tool_product/views.py
> Reporting shortcuts and endpoints, css. Creds and tools on product

- dojo/__init__.py
- dojo/models.py
- dojo/static/dojo/css/dojo.css
- dojo/tasks.py
- dojo/templates/dojo/dashboard.html
- dojo/templates/dojo/view_eng.html
- dojo/templates/dojo/view_product_details.html
> CSS tweaks, language graph

- dojo/templates/dojo/view_product_details.html
> product overview tweak

- dojo/templates/dojo/view_test.html
The hotkey function was triggered if an user type the character 'a' or 'e' in notes or potential finding input field.
> fix hotkey bug in test view

- docker/docker-startup.bash
I just want to fix this so that the docker install works.
> Convert dojo.settings to dojo.settings.settings

- dojo/__init__.py
- dojo/api.py
- dojo/api_v2/serializers.py
- dojo/engagement/views.py
- dojo/forms.py
- dojo/jira_link/views.py
- dojo/management/commands/dedupe.py
- dojo/models.py
- dojo/product/urls.py
- dojo/product/views.py
- dojo/static/dojo/css/dojo.css
- dojo/tasks.py
- dojo/templates/base.html
- dojo/templates/dojo/delete_presets.html
- dojo/templates/dojo/edit_presets.html
- dojo/templates/dojo/new_params.html
- dojo/templates/dojo/new_product.html
- dojo/templates/dojo/snippets/engagement_list.html
- dojo/templates/dojo/view_eng.html
- dojo/templates/dojo/view_engagements.html
- dojo/templates/dojo/view_presets.html
- dojo/templates/dojo/view_product_details.html
- dojo/templatetags/display_tags.py
- dojo/unittests/test_rest_framework.py
- setup.py
> Engagement Enhancements / API REST V2

- dojo/jira_link/views.py
- dojo/models.py
> Disable jira webhook by default

- dojo/fixtures/test_type.json
- dojo/forms.py
- dojo/templates/dojo/import_scan_results.html
- dojo/tools/clair/parser.py
- dojo/tools/factory.py
- dojo/tools/npmaudit/parser.py
Clair scans Docker images and can output findings in JSON. Added support for importing said findings.
> Add support for JSON output of Clair scans

- dojo/test/views.py
This pull requests is for additional validation for adding new findings with JIRA integration. 
Previously, if the finding was not marked as 'Active' or 'Verified' but 'Push to JIRA' was selected, the form would still be accepted, only for an alert to pop up later saying that the finding was not active or verified, since the check for Active/Verified currently only happens in the `add_issue` function in dojo/utils.py. Instead, I have changed it such that the form is not accepted in the first place, which I feel makes more sense since the user will immediately know that they forgot to (or did not know that they had to) check Active/Verified if the finding is to be pushed to JIRA. 
Similarly, for Info severity, it is lower than the lowest JIRA minimum severity which can be set. Hence, if a …
> additional validation checks for add_findings

- entrypoint_scripts/common/dojo-shared-resources.sh
Dojo superuser password reset script 'docker/setup-superuser.expect' fails, when 'expect' package doesn't exist. So explicitly added 'expect' package to list of packages to be installed.
> Added 'expect' package to list of packages to be installed.

- dojo/api_v2/serializers.py
On import, skip duplicate findings for the same engagement if the scan
is automated.  A scan is assumed to be automatic when the following
conditions are satisfied:
- Deduplication is activated
- The test tool is static
- The engagement type is CI/CD
@aaronweaver what are your thoughts about this idea?
TODO:
- Maybe, we should also add an opt-in flag in the system settings for this feature?
- Needs to be rebased if #722 is merged.
> APIv2:  Skip duplicate findings on import under certain conditions

- dojo/management/commands/migrate_meta.py
- setup.py
> Fixing migration script for meta

- dojo/metrics/views.py
- dojo/models.py
- dojo/templates/dojo/metrics.html
With this patch, I can use SQLite as the database in my dev environment :)
> Make `Finding.age` a property and use it instead of custom SQL query

- dojo/tools/dependencycheck/parser.py
> Mark Dependency Check findings as static

- dojo/models.py
Fixes age issue for remediated findings.
> Finding age patch

- dojo/tools/nexpose/parser.py
> UTF-Encoding fix for nexpose parser

- requirements.txt
More here - https://stackoverflow.com/questions/50444988/celery-attributeerror-async-error
> Fix Celery + Kombu Bug

- dojo/models.py
- dojo/tools/nexpose/parser.py
> Hashcode calculate on first save

- dojo/tools/dependencycheck/parser.py
- dojo/unittests/test_dependency_check_parser.py
> Dependency Check: Use CWE field if present

- dojo/models.py
- dojo/templatetags/display_tags.py
> Hashcode fix #780;endpoint in display tags

- dojo/forms.py
> Forms patch for delete

- .flake8
- dojo/engagement/views.py
- dojo/forms.py
- dojo/models.py
- dojo/templates/dojo/dashboard-metrics.html
- dojo/templates/dojo/dashboard.html
- dojo/templates/dojo/import_scan_results.html
- dojo/templates/dojo/view_finding.html
- dojo/templates/dojo/view_test.html
- dojo/templatetags/display_tags.py
- dojo/tools/awsprowler/__init__.py
- dojo/tools/awsprowler/parser.py
- dojo/tools/awsscout2/__init__.py
- dojo/tools/awsscout2/parser.py
- dojo/tools/burp/parser.py
- dojo/tools/factory.py
- dojo/tools/mobsf/parser.py
> Prowler and Scout2, MobSF for iOS

- requirements.txt
> Requests update

- dojo/fixtures/test_type.json
- dojo/tools/acunetix/parser.py
- dojo/tools/acunetix/parser_helper.py
- dojo/tools/acunetix/parser_models.py
- tests/validate_acunetix_scan_xml.py
> Fixes fixture issue and env parse issue

- dojo/api_v2/serializers.py
- dojo/api_v2/views.py
- dojo/endpoint/views.py
- dojo/forms.py
- dojo/management/commands/migrate_meta.py
- dojo/models.py
- dojo/product/views.py
- dojo/templates/dojo/edit_endpoint_meta_data.html
- dojo/templates/dojo/edit_product_meta_data.html
- dojo/unittests/test_apiv2_metadata.py
Hey there,
some changes to the metadata feature :)
> Changes to metadata feature

- dojo/forms.py
- dojo/models.py
- entrypoint_scripts/misc/reports.sh
> Removes PDF reports. Fixes save issue

- dojo/engagement/views.py
- dojo/models.py
- dojo/test/views.py
- dojo/utils.py
> Reworked false positive

- dojo/tools/burp/parser.py
> Bugfix in Burp Parser DefectDojo/django-DefectDojo/issues/823

- README.md
>  Fixes permission issue

- components/package.json
Reverts DefectDojo/django-DefectDojo#867
> Revert "prevent sb-admin-2 from 4.0.0 upgrade"

- components/package.json
> prevent sb-admin-2 from 4.0.0 upgrade

- components/package.json
Reverts DefectDojo/django-DefectDojo#868
> Revert "Revert "prevent sb-admin-2 from 4.0.0 upgrade""

- dojo/templates/dojo/add_endpoint.html
- dojo/templates/dojo/add_related.html
- dojo/templates/dojo/add_template.html
- dojo/templates/dojo/add_tests.html
- dojo/templates/dojo/apply_finding_template.html
- dojo/templates/dojo/edit_endpoint.html
- dojo/templates/dojo/edit_findings.html
- dojo/templates/dojo/edit_object.html
- dojo/templates/dojo/edit_product.html
- dojo/templates/dojo/edit_test.html
- dojo/templates/dojo/import_scan_results.html
- dojo/templates/dojo/new_eng.html
- dojo/templates/dojo/new_object.html
- dojo/templates/dojo/new_product.html
> fixed XSS bug in tags.

- dojo/templatetags/display_tags.py
- [X ] Your code is flake8 compliant (Dojo's code isn't currently flake8 compliant, but we're trying to correct that)
> Output encoding for markdown

- dojo/development_environment/views.py
- dojo/forms.py
- dojo/templates/dojo/edit_dev_env.html
Fixes #886 
Added new feature to delete an environment variable from the Environment list.
> added delete option in environment list.

- entrypoint_scripts/common/common-os.sh
- entrypoint_scripts/os/linux.sh
Linux Mint is based on Debian and Ubuntu so all are same only os name and version is changed.
> add linux mint 19 support

- dojo/views.py
Regarding the issue #759, where a server error was thrown when trying to view a users history.
The error message said, that the variable 'object_value' was undefined.
> object_value in views.py initialized

- dojo/api.py
Reverts DefectDojo/django-DefectDojo#834
> Revert "Update api.py"

- Dockerfile.initializer
- Dockerfile.uwsgi
- KUBERNETES.md
- helm/defectdojo/requirements.lock
- helm/defectdojo/requirements.yaml
- helm/defectdojo/templates/celery-deployment.yaml
- helm/defectdojo/templates/django-deployment.yaml
- helm/defectdojo/templates/initializer-job.yaml
- helm/defectdojo/values.yaml
> PostgreSQL support added, image names fixed.

- dojo/tools/dependencycheck/parser.py
> fix issue #922

- dojo/tools/burp/parser.py
- dojo/tools/zap/parser.py
Tested in my environment - works.
> Burp Parser - minor bugfix in urlparse method.  Change nettloc to netloc

- docker/entrypoint-unit-tests.sh
- helm/defectdojo/templates/django-deployment.yaml
- helm/defectdojo/templates/tests/django-unit-tests.yaml
- helm/defectdojo/templates/tests/smoke-test.yaml
> Make unit tests use Django database.

- Dockerfile.django
- KUBERNETES.md
- README.md
- docker-compose.yml
- docker/entrypoint-initializer.sh
- docker/entrypoint-unit-tests.sh
- docker/entrypoint-uwsgi.sh
- helm/defectdojo/templates/configmap.yaml
- helm/defectdojo/templates/secret.yaml
- helm/defectdojo/templates/tests/django-unit-tests.yaml
- helm/defectdojo/values.yaml
> documentation fixed, minor docker-compose adjustments.

- dojo/filters.py
> Fix issue #931

- requirements.txt
> Updated lxml==4.2.5

- DOCKER.md
- Dockerfile.django
- docker-compose.yml
- dojo/forms.py
- dojo/templates/dojo/import_scan_results.html
- requirements.txt
- setup.py
> Compose timing startup changed, removed SonarCube until official Sonarcube export

- README.md
- dojo/models.py
> Updated Readme & made hash_code uneditable from UI

- .travis.yml
- travis/before-install.sh
- travis/script.sh
> Added container security checks

- Dockerfile.django
- docker/entrypoint-initializer.sh
> Change initializer to urandom

- README.md
Fix twitter handle in README.md
> Fix twitter handle in README.md

- dojo/fixtures/test_type.json
- dojo/forms.py
- dojo/templates/dojo/import_scan_results.html
- dojo/tools/anchore_engine/__init__.py
- dojo/tools/anchore_engine/parser.py
- dojo/tools/factory.py
> The Anchore Engine is an open source project that provides a centralized service for inspection, analysis and certification of container images. The Anchore engine is provide as a Docker container image that can be run standalone or on an orchestration platform such as Kubernetes, Docker Swarm, Rancher or Amazon ECS.
Anchore-CLI is the command line tool to interact with Anchore-Engine. Anchore-CLI provides a reporting capability in JSON for different commands. One of them is getting all vulnerabilities detected on docker images using ```--json``` flag. More info here: https://anchore.freshdesk.com/support/solutions/articles/36000003882-security-vulnerability-reporting
Sample: ```anchore-cli --json image vuln node:latest all```
Sample scan file in this PR: …
> Anchore-Engine JSON vulnerability report importer

- dojo/api_v2/serializers.py
Make deduplication_on_engagement work with skip duplicates, fixes #1002.
> Make deduplication_on_engagement work with skip duplicates

- DOCKER.md
- docker-compose.override.yml
- docker-compose.yml
- [x ] Your code is flake8 compliant (DefectDojo's code isn't currently flake8 compliant, but we're trying to correct that.)
> Dev version of compose, mysql volume and utf8mb4 support

- dojo/tools/npmaudit/parser.py
- dojo/unittests/scans/npm_audit_sample/many_vuln.json
- dojo/unittests/scans/npm_audit_sample/no_vuln.json
- dojo/unittests/scans/npm_audit_sample/one_vuln.json
- dojo/unittests/test_npm_audit_scan_parser.py
> add unittest for npm audit scan parser

- .gitignore
- dojo/finding/views.py
- dojo/forms.py
- dojo/models.py
- dojo/templates/dojo/findings_list.html
- dojo/templates/dojo/view_test.html
- dojo/test/views.py
- dojo/utils.py
- bulk push to jira
- tooltip on jira isuse link logo/image
- extra fields from engagement sent to jira description field
> jira integration improvements including bulk push to jira

- DOCKER.md
- Dockerfile.django
- docker-compose.yml
- docker/entrypoint-initializer.sh
- docker/entrypoint-uwsgi-dev.sh
- dojo/settings/settings.dist.py
- nginx/nginx.conf
- Nginx max upload size changed to 800mb "Closes: #1016" 
- Tests for admin users creation to avoid create duplicates entries and fixtures "Closed: #1003"
- Dev mode for development with manage.py
> Docker dev compose improvements

- dojo/templates/base.html
This PR builds ontop of #1020 and applies some more fixes to the menus.
> Accessibility fixes

- README.md
> fix quickstart instructions with new docker-compose.yml files

- Dockerfile.django
Reduces the size of the docker image
---
> Slimmer docker image

- Dockerfile.django
Reverts DefectDojo/django-DefectDojo#1044
> Revert "Slimmer docker image"

- requirements.txt
Deduplication of entries in requirements.txt
> Deduplication of entries in requirements.txt

- dojo/tools/anchore_engine/parser.py
> Fixes #1069 - anchore import

- dojo/api_v2/views.py
- dojo/engagement/services.py
- dojo/engagement/views.py
> Close/reopen an engagement from API

- dojo/unittests/test_engagement_planner.py
- dojo/unittests/test_rest_framework.py
- dojo/unittests/test_tool_run.py
Should fix the issues from the CI tests: https://api.travis-ci.org/v3/job/519344279/log.txt
> Fix for unit tests in sec automation

- Dockerfile.build
- Dockerfile.django
- Dockerfile.nginx
- travis/script.sh
Adding a new build image to build the django and nginx image. This removes the dependency
between the django(release) image and the nginx image.
Also adding a condition which breaks the pipeline when the docker build fails.
Last discussion about this topic: #1044
> Slimmer docker images

- dojo/templates/dojo/simple_search.html
> Fixes a spelling mistake in search operator `language`

- README.md
Please only merge after https://github.com/DefectDojo/Documentation/pull/36
> Adding Sponsor

- README.md
Please first merge https://github.com/DefectDojo/Documentation/pull/37
> Add Signal-Iduna as sponsor

- tests/Product_unit_test_example.py
> Example of product unit test

- tests/Product_unit_test_example.py
- tests/check_status.py
- tests/check_status_ui.py
- tests/smoke_test.py
> Credential Modifications

- dojo/models.py
- requirements.txt
- setup.py
> Automatic Title case finding titles

- dojo/fixtures/test_type.json
- dojo/forms.py
- dojo/templates/dojo/import_scan_results.html
- dojo/tools/factory.py
- dojo/tools/sonatype/parser.py
- dojo/unittests/scans/sonatype/many_vulns.json
- dojo/unittests/scans/sonatype/one_vuln.json
- dojo/unittests/test_sonatype_parser.py
Got my hand on a sonatype json report. This is a parser based on it (which I cannot share).
The unittests have a glimpse of what it looks like though.
Cheers,
fred
> Sonatype parser

- dojo/tools/gosec/parser.py
Adding line, confidence, formatting for code which can be already in backtick form.
Adding ref to being built documentation in references field.
> minor improvements to gosec parser

- dojo/tools/anchore_engine/parser.py
> Adding cve field to anchore parser and extra crlf to description

- dojo/tools/snyk/parser.py
> Adding cve and dynamic cwe values to snyk importer

- dojo/tools/kiuwan/parser.py
> fix kiuwan cwe issue

- tests/Environment_unit_test.py
- tests/Product_type_unit_test.py
fix #1134 
implemented environment test for the following:
- Add
- Edit
- Delete
> Environment unit test

- dojo/tools/kiuwan/parser.py
I've corrected and aligned DefectDojo finding severity with Kiuwan defects priorities. This is the resulting mapping:
DefectDojo =>Kiuwan
Critical => Very High
High => High
Medium = >Normal
Low = > Low
Info = >Very Low
Additionally, now I'm assigning the Finding.file_path and Finding.line with info coming from the Kiuwan defect to render Location and Line Number in the Finding's details page in the front end
> Kiuwan import improvements

- dojo/filters.py
Fix issue #1143 
funny enough I only added a single word to fix this. as you can see in my commit.
If this is not what is expected do let me know.
> Fix open finding filter inconsistency

- dojo/fixtures/test_type.json
- dojo/forms.py
- dojo/templates/dojo/import_scan_results.html
- dojo/tools/cobalt/parser.py
- dojo/tools/factory.py
- dojo/unittests/scans/cobalt/cobalt_many_vuln.csv
- dojo/unittests/scans/cobalt/cobalt_no_vuln.csv
- dojo/unittests/scans/cobalt/cobalt_one_vuln.csv
- dojo/unittests/test_cobalt_parser.py
> Cobalt.io Scan Importer

- .flake8
> Fixes flake8 issue

- dojo/benchmark/views.py
- dojo/models.py
- dojo/product/views.py
- dojo/templates/dojo/view_product_details.html
- dojo/templatetags/display_tags.py
This is the implementation for enhancement #1120.
> Enhancement #1120

- travis/deploy.sh
Changing frequency of deployments to Heroku.
> Heroku deployments changed to merge

- .flake8
- travis/deploy.sh
> Travis Deployment

- .github/ISSUE_TEMPLATE/importer_request.md
- PULL_REQUEST_TEMPLATE.md
> Templates updates for Python3 and Scanner

- .github/ISSUE_TEMPLATE/importer_request.md
- PULL_REQUEST_TEMPLATE.md
- travis/deploy.sh
> Template updates

- requirements.txt
> update git dependencies

- dojo/fixtures/test_type.json
- dojo/forms.py
- dojo/templates/dojo/import_scan_results.html
- dojo/tools/factory.py
- dojo/tools/mozilla_observatory/parser.py
- dojo/unittests/scans/mozilla_observatory/mozilla_gitlab_two_vuln.json
- dojo/unittests/scans/mozilla_observatory/mozilla_google_many_vuln.json
- dojo/unittests/scans/mozilla_observatory/mozilla_no_vuln.json
- dojo/unittests/test_mozilla_observatory_parser.py
> Mozilla Observatory Scan importer

- dojo/finding/views.py
- dojo/fixtures/test_type.json
- [x ] Your code is flake8 compliant
> Add PR#1255 and correct fixtures mistake

- dojo/api_v2/views.py
- dojo/models.py
- dojo/test/views.py
> Fixed API_V2 user permissions

- dojo/api_v2/views.py
- requirements.txt
> downgrade rest-swagger for APIv2 compatability

- PULL_REQUEST_TEMPLATE.md
> Update PR template for legacy branch

- dojo/tools/sonatype/parser.py
…and provide direction
PR against `dev` for fix. Will also submit to `python3_dev` branch.
> Amending description for sonatype issues

- dojo/engagement/views.py
- dojo/test/views.py
These are my fixes for #1322 and #1323.
> Fixes #1322 and  #1323

- travis/before-install.sh
Adding some stuff to the travis flake8 tests. In reference to #1320.
> Add potential travis flake8 fixes

- PULL_REQUEST_TEMPLATE.md
> Update PR template on master

- dojo/templates/dojo/simple_search.html
It does help quite a lot when searching for previous investigations, and navigating through a number of the same CVEs to find the original or pinpoint the right one is correlation with the already added engagement and related tests.
> Adding status to finding results

- dojo/tools/anchore_engine/parser.py
> Anchore - remove dynamic finding

- dojo/forms.py
- dojo/models.py
- dojo/templates/dojo/new_product.html
This is my fix for #1319. Product forms should now be consistent with each other.
> Fixes #1319

- dojo/fixtures/test_type.json
- dojo/forms.py
- dojo/templates/dojo/import_scan_results.html
- dojo/tools/factory.py
- dojo/tools/wpscan/parser.py
- dojo/unittests/scans/wpscan/wordpress_many_vuln.json
- dojo/unittests/scans/wpscan/wordpress_no_vuln.json
- dojo/unittests/scans/wpscan/wordpress_one_vuln.json
- dojo/unittests/test_wpscan_parser.py
> Wpscan Importer

- dojo/models.py
> Make Finding.long_description NoneType safe for CVE and Severity

- dojo/fixtures/test_type.json
- dojo/forms.py
- dojo/templates/dojo/import_scan_results.html
- dojo/tools/factory.py
- dojo/tools/sslscan/parser.py
- dojo/unittests/scans/sslscan/sslscan_many_vuln.xml
- dojo/unittests/scans/sslscan/sslscan_no_vuln.xml
- dojo/unittests/scans/sslscan/sslscan_one_vuln.xml
- dojo/unittests/test_sslscan_parser.py
> Sslscan Importer

- dojo/finding/views.py
Set Notes created on Review Request to Private by default 
#1344
(this is just a line of code update)
> Mark Notes as Private By Default on Review Request

- dojo/fixtures/test_type.json
- dojo/test/views.py
> Fix re-import-scan and remove dupe fixture

- dojo/tools/veracode/parser.py
> Veracode fix static and dynamic issue

- dojo/unittests/test_utils.py
- dojo/utils.py
- requirements.txt
- setup.py
The pycrypto library is no longer maintained and contains a least one big security issue (https://github.com/dlitz/pycrypto/issues/176). 
Furthermore saving credentials wasn't working.
---
> replace pycrpto

- dojo/templates/dojo/view_test.html
> fix status column to show under review option

- dojo/api_v2/serializers.py
- dojo/api_v2/views.py
- dojo/urls.py
Issue #1343
Add Endpoint for fetching Notes with Api V2
> Add Notes Endpoint to Api version2

- dojo/tools/ssl_labs/parser.py
> fix ssllabs importer problem if suites not provided

- Dockerfile.django
- Dockerfile.nginx
> Update master branch with mysql docker fixes

- dojo/templates/dojo/product_endpoint_pdf_report.html
- dojo/templates/dojo/product_metrics.html
- dojo/templates/dojo/product_pdf_report.html
- dojo/templates/dojo/view_product.html
PR to fix an issue that was opened back in #789 and the bot automatically closed the issue without a proper fix on the some of the page templates
This fixes #1387
> Fix JUMFlot issues. Fixes #1387

- dojo/tools/nikto/parser.py
Nikto has 2 “NIKTOSCAN” tags now, updating the root to find the scan details and also improve description parsing/importing
Fix issue #1382
> Fix nikto parsing and importing. FIxes #1382

- Dockerfile.django
- Dockerfile.nginx
> Add DockerFile fixes to legacy branch

- dojo/finding/views.py
- dojo/forms.py
- dojo/templates/dojo/edit_findings.html
- dojo/templates/dojo/findings_list.html
- dojo/templates/dojo/form_fields.html
- dojo/templates/dojo/view_test.html
- dojo/test/views.py
This is my enhancement for #1339. Tags can now be added to findings via the bulk edit menu of findings list and view test.
> Enhancement #1339

- dojo/tools/nessus/parser.py
In reference to issue #1399 
The users Nessus scan file had vulnerabilities that did not contain descriptions. An extra check was added to determine if a description field was present in a vulnerability before adding it. Flake8 fixes were also implemented 
> Add check for empty descriptions

- CONTRIBUTING.md
> Update CONTRIBUTING.md to contribute to dev instead master

- dojo/finding/views.py
> Fix finding template tags

- dojo/tools/clair_klar/parser.py
As I found out, the "FixedBy" is not mandatory set by clair klar.
> Fix missing "FixedBy"

- .travis.yml
- dojo/user/views.py
> Fix user edit form to remove products.

- dojo/test/views.py
> Bug fix at re_import_scan_result

- dojo/product/views.py
- dojo/templates/dojo/product_metrics.html
> CWE statistics in product metrics

- dojo/finding/views.py
- dojo/forms.py
- dojo/templates/dojo/add_findings.html
- dojo/templates/dojo/apply_finding_template.html
- dojo/test/views.py
> Fix tags in all finding templates

- dojo/finding/urls.py
- dojo/finding/views.py
- dojo/templates/dojo/templates.html
This is my enhancement for #1342. Finding templates can now be downloaded into a JSON file.
> Enhancement #1342

- dojo/tools/qualys/parser.py
Some Qualys scans are reports might not have the CVSS score to define the severity of a finding.
This commit fixes the importing, assigns severity from Qualys severity if CVSS score is not present and improves parsing of data.
> Fix Qualys parsing and importing. FIxes #1384

- dojo/finding/views.py
- dojo/templates/dojo/findings_list.html
This is my enhancement for #897. Bulk Edit no longer resets the filters. 
In addition, whenever a user wants to delete multiple findings, the user will be greeted with "Are you sure you want to delete these findings?" instead of "Are you sure you want to delete this finding?"
> Enhancement #897 and Minor Wording Change

- dojo/object/parser.py
- dojo/tools/anchore_engine/parser.py
- dojo/tools/arachni/parser.py
- dojo/tools/bandit/parser.py
- dojo/tools/brakeman/parser.py
- dojo/tools/clair/parser.py
- dojo/tools/clair_klar/parser.py
- dojo/tools/dawnscanner/parser.py
- dojo/tools/gosec/parser.py
- dojo/tools/jfrogxray/parser.py
- dojo/tools/mobsf/parser.py
- dojo/tools/mozilla_observatory/parser.py
- dojo/tools/netsparker/parser.py
- dojo/tools/npm_audit/parser.py
- dojo/tools/nsp/parser.py
- dojo/tools/php_security_audit_v2/parser.py
- dojo/tools/php_symfony_security_check/parser.py
- dojo/tools/retirejs/parser.py
- dojo/tools/safety/parser.py
- dojo/tools/snyk/parser.py
- dojo/tools/sonatype/parser.py
- dojo/tools/ssl_labs/parser.py
- dojo/tools/twistlock/parser.py
- dojo/tools/whitesource/parser.py
- dojo/tools/wpscan/parser.py
Fix JSON based parser for the last time. Not sure what went wrong on the last one.
> Fix JSON based parsers again

- dojo/templatetags/display_tags.py
> fix release mode git commit showing issue

- .gitignore
- docker-compose.override.yml
- travis/script.sh
This file is supposed to be a symbolic link, which is by default not present. 
It was mistakenly commited with in content the name of the destination.
> remove docker-compose override file with incorrect content

- dojo/api_v2/serializers.py
- dojo/api_v2/views.py
>  Add Ability to Manage Findings Tag with Api v2

- dojo/tools/dependency_check/parser.py
Add CVSS3 as the default and use CVSS3 as fallback.
> Add CVSS3 as default on behalf of SDA SE

- dojo/forms.py
> fix initial date format

- dojo/finding/views.py
- dojo/test/views.py
If the Jira Pkey table was empty, an exception would be thrown. This behavior is corrected by the pull request.
> Correct overlooked error in #1498

- dojo/api.py
> API Filter Enhancements for Engagements

- dojo/tools/twistlock/parser.py
- dojo/unittests/scans/twistlock/no_vuln.json
- dojo/unittests/test_twistlock_parser.py
> fixes #1566 add unittest and try-catch.

- helm/defectdojo/templates/NOTES.txt
> issue_1542 fix - Using dynamic secret name

- dojo/api.py
> add v1 api enhancements

- dojo/filters.py
- dojo/fixtures/test_type.json
> Fix Closed/Accepted Finding errors

- dojo/filters.py
Include additional fields that can be used for filtering the product view
> Improve Product view filtering

- dojo/filters.py
Make the same checks for finding.cwe for each filter type.
> fix finding.cwe in filters

- dojo/api_v2/serializers.py
- dojo/api_v2/views.py
> Ability to Add And Remove Notes with API v2 Finding Endpoint

- dojo/templates/dojo/view_test.html
> Fix "Under Review" not showing in test view

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/importer_request.md
- .github/ISSUE_TEMPLATE/security_issue.md
- dojo/api_v2/serializers.py
- dojo/models.py
> Mrod product update

- dojo/jira_link/views.py
- dojo/models.py
- dojo/settings/settings.dist.py
- dojo/tasks.py
- dojo/tools/sonarqube_api/api_client.py
- dojo/tools/sonarqube_api/updater_from_source.py
- dojo/tools/tool_issue_updater.py
> [SonarQube API] Manage manual changes

- dojo/templates/dojo/asciidoc_report.html
- dojo/templates/dojo/endpoint_pdf_report.html
- dojo/templates/dojo/engagement_pdf_report.html
- dojo/templates/dojo/finding_pdf_report.html
- dojo/templates/dojo/metrics.html
- dojo/templates/dojo/product_endpoint_pdf_report.html
- dojo/templates/dojo/product_pdf_report.html
- dojo/templates/dojo/product_type_pdf_report.html
Add space to table of contents and fix #1603
> Add space to table of contents and fix #1603

- dojo/endpoint/views.py
- dojo/engagement/views.py
- dojo/finding/views.py
- dojo/object/views.py
- dojo/product/views.py
- dojo/test/views.py
Allow to use tags with spaces included
---
> Fix bug when using tags with spaces

- dojo/notes/views.py
- dojo/templates/dojo/snippets/comments.html
As mentioned in the #1604 editing a note is restricted with two conditions.
**The line below allows only the staff users to edit any note**
```ruby
@user_passes_test(lambda u: u.is_staff)
```
**The following condition allows only the author of the note and the super user to edit notes.**
```ruby
if page is None or str(request.user) != note.author.username and not request.user.is_superuser:
raise PermissionDenied
```
With the combination of these two conditions, …
> Change note editing restrictions

- dojo/tools/netsparker/parser.py
Hi,
Like my other PR for sslyze parser, the parser of netsparker crash if the report does not contain all values.
Best regards
> Fix undefined and null value issue in netsparker import

- dojo/tools/sslyze/parser.py
Hello,
In some cases, sslyze export does no contain checked key, and result in crash during import
Bests regards
> Fix sslyze XML parser for undefined value

- dojo/jira_link/views.py
> Fix #1600 argument type for json.loads

- dojo/forms.py
> Fix bug in simple metrics

- README.md
> Update Slack invite

- README.md
Just adding a link in the README for my profile info.
> Add Fred's link to LI

- dojo/api_v2/views.py
> apiv2, ability to filter engagement by name

- dojo/templates/dojo/product.html
- dojo/templates/dojo/view_finding.html
Fix motivated by #1616 
Thanks to @MarianG for finding the solution in an identical situation.
Fix motivated by #1717 
Additionally, fix the discrepancy between descriptions and mitigation/impact text boxes when viewing a finding. the same text would appear differently between fields.
> Fix hover issue in product list

- dojo/templatetags/display_tags.py
Fixes #1653 
Just another place to change to query Active findings and not Active, Verified findings as we initiated the change. It's a bit all over the place.
> Adapting to Active findings for count

- Dockerfile.busybox
- Dockerfile.django
- Dockerfile.nginx
Bumping all base images a notch.
> Bumping parent docker images

- .github/release-drafter.yml
- .github/workflows/release-drafter.yml
- PULL_REQUEST_TEMPLATE.md
This would go hand in hand with more attention to labels when some issues come in.
> A bit fancier release-drafter template

- dojo/tools/safety/parser.py
> fix safety scan

- dojo/tools/snyk/parser.py
> added snyk custom ID in references

- dojo/settings/settings.dist.py
- dojo/tools/__init__.py
- dojo/tools/qualys/parser.py
- add date to Finding
- add qid as unique_id_from_tool
- parser handles active/verified status now
---
> Improve Qualys Parser

- dojo/tools/h1/parser.py
Changes:
1. Added date report was submitted (would love for this to be the Date Discovered in Defect Dojo but it doesn't seem to set it..?)
2. Added the reporter's username
3. Added the "Weakness" (if present)
4. Added the Triaged date (if present)
5. Added the CVSS Score (if present)
6. In References, added any Issue Tracker reference information (JIRA, ServiceNow, etc) that you may have on your report in H1.
7. Fixed some typos (one of them pretty major, all **high's** would be categorized and **info**
When submitting a pull request, please make sure …
> HackerOne: Updated parser, fixed typos, added some other fields from JSON

- dojo/home/views.py
- dojo/metrics/views.py
- dojo/product/views.py
- dojo/static/dojo/js/index.js
- dojo/templates/dojo/dashboard-metrics.html
- dojo/templates/dojo/dashboard.html
- dojo/templates/dojo/product_metrics.html
- dojo/templates/dojo/view_product.html
- dojo/urls.py
- dojo/utils.py
As I have over 10000 findings in my instance, I'm getting nice visibility of the bottlenecks in Defect Dojo.
Turns out that the dashboard itself and the underlying get_punchcard_data where big bottlenecks.
**Option 1**: Disable the punchcard. But there is no fun in that :-)
**Option 2**: Do some optimizations.
I went for Option 2. Took a bit of time, but great way to learn lots of things about Python, Django, Django ORM, Mysql and Defect Dojo.
**Changes made:**
- Pie chart:
The dashboard is showing a pie chart with all-time severity count. 
It populated this by retrieving ALL findings and associated data from the database and let some django code count the severities.
I've rewritten this to use an aggregate in the queryset.
- Severity by month graph:
Was only showing findings reported by …
> dashboard and punchcard performance improvements

- dojo/test/views.py
> Add get_object_or_404 to view_test

- README.md
> add moderator information

- PULL_REQUEST_TEMPLATE.md
a few tips on using git. that will give us nicer git history :)
> add git tips

- dojo/tools/burp_enterprise/parser.py
- enhancement
- feature
- bugfix
- dependencies
> Generalize for multiple endpoints (Burp Enterprise Scan)

- dojo/filters.py
fixes #1874 , see that issue for more details.
> bugfix: severity-filter, always allow all 5 choices

- dojo/context_processors.py
- dojo/settings/settings.dist.py
- dojo/templates/dojo/login.html
- PR for documentation has been created on DefectDojo/Documentation#74
but also including documentation here
- [N/A] Model changes must include the necessary migrations in the dojo/db_migrations folder.
- [N/A] Add applicable tests to the unit tests.
- enhancement
- feature
- bugfix
- dependencies
> Implement Gitlab OAuth2 authentication. Fix #1966

- dojo/settings/settings.dist.py
#1967 merged a little too quickly with flake8 issue. This fixes them.
Thanks @alles-klar for the :eyes:  !
> Fix flake8

- dojo/tools/outpost24/parser.py
fixes for #1968
- enhancement
- feature
- bugfix
- dependencies
> Fix outpost24 parser

- dojo/engagement/views.py
- dojo/tools/burp_enterprise/parser.py
- enhancement
- feature
- bugfix
- dependencies
> BurpE Parser Scale Upgrade

- dojo/tasks.py
- dojo/utils.py
Signed-off-by: Matt Sicker <boards@gmail.com>
- enhancement
- feature
- bugfix
- dependencies
> Reduce log spam in unit tests

- dojo/engagement/views.py
- dojo/test/views.py
- dojo/tools/burp/parser.py
- dojo/tools/burp_enterprise/parser.py
- enhancement
- feature
- bugfix
- dependencies
> [BurpE] Add multiple request/response tabs

- dojo/templates/dojo/view_finding.html
Addresses https://github.com/DefectDojo/django-DefectDojo/issues/1989
- enhancement
- feature
- bugfix
- dependencies
> Keyboard shortcuts to navigate to previous and next finding

- dojo/fixtures/test_type.json
- dojo/forms.py
- dojo/templates/dojo/import_scan_results.html
- dojo/tools/anchore_enterprise/parser.py
- dojo/tools/factory.py
- dojo/unittests/scans/anchore_enterprise/invalid_checks_format.json
- dojo/unittests/scans/anchore_enterprise/many_checks.json
- dojo/unittests/scans/anchore_enterprise/no_checks.json
- dojo/unittests/scans/anchore_enterprise/one_check.json
- dojo/unittests/test_anchore_policy_check.py
This adds a new parser for policy checks created by Anchore enterprise. The translation from a policy check to a dojo's finding looks like this:
```
Finding: DefaultPolicy - gate|vulnerabilities - trigger|CVE-2020-8840+openapi-generator-cli-4.0.0.jar:jackson-databind
title: DefaultPolicy - gate|vulnerabilities - trigger|CVE-2020-8840+openapi-generator-cli-4.0.0.jar:jackson-databind
description: CRITICAL Vulnerability found in non-os package type (java) - /usr/openapi/openapi-generator-cli-4.0.0.jar:jackson-databind (CVE-2020-8840 - https://nvd.nist.gov/vuln/detail/CVE-2020-8840)
cve: CVE-2020-8840
severity: Critical
references: Policy ID: 48e6f7d6-1765-11e8-b5f9-8b6f228548b6
Tirgger ID: CVE-2020-8840+openapi-generator-cli-4.0.0.jar:jackson-databind
component name: …
```
> Add a parser for policy checks created by Anchore enterprise

- CONTRIBUTING.md
Similar to #2031, but for `master`
> Update master/CONTRIBUTING.md to reflect reality after python3 upgrade

- CONTRIBUTING.md
> Update CONTRIBUTING.md after migration to python3.

- dojo/settings/settings.dist.py
fix merge artifact from #1955 (this fixes all JIRA stuff not being displayed)
> fix removed system settings processor

- dojo/context_processors.py
- dojo/settings/settings.dist.py
- dojo/templates/dojo/login.html
This commit add out-of-the-box support for
Auth0 as an Identity-Provider.
- enhancement
- feature
- bugfix
- dependencies
> Implement Auth0 OAuth2 authentication

- dojo/templates/dojo/view_product_details.html
only show donut if donut (language) data is available, fixes #2005
the donut div is not rendered if there are no languages for this product.
this PR disables the javascript from trying to populate the non-existing donut div
> only show donut if donut (language) data is available, fixes #2005

- dojo/api_v2/views.py
> add version to filter fields

- dojo/forms.py
- dojo/tools/dsop/parser.py
- dojo/unittests/test_dsop_parser.py
- enhancement
- feature
- bugfix
- dependencies
> fix various DSOP parser issues

- dojo/templates/dojo/findings_list.html
- dojo/templates/dojo/view_test.html
- tests/Finding_unit_test.py
- tests/Test_unit_test.py
Fixes #1995 and adds an integration test to prevent future regressions
> quickfix #1995 bulk edit in view_test

- dojo/templates/dojo/product.html
Another javascript fix, this time for #2050 
Turns out by fixing the javascript we now see that the default ordering is wrong, this PR fixes that as well.
> fix #2050 broken javascript datatable product list

- dojo/google_sheet/views.py
- dojo/test/views.py
> Fix for issue #1993

- dojo/db_migrations/0033_remove_finding_duplicate_list.py
#2009 was merged without enough checks from me on migration chain of dependencies. This PR fixes this (small) problem.
> fix migrations after #2009

- KUBERNETES.md
- helm/defectdojo/templates/secret-mysql.yaml
- helm/defectdojo/templates/secret-postgresql.yaml
- helm/defectdojo/templates/secret-rabbitmq.yaml
- helm/defectdojo/templates/secret-redis.yaml
- helm/defectdojo/templates/secret.yaml
- helm/defectdojo/values.yaml
- travis/script.sh
- helm upgrade was re-initializing the secrets that are stored inside of the defectdojo chart
- do not create those specific secrets by default
see comments at the end of https://github.com/DefectDojo/django-DefectDojo/pull/1752
NB: this also has some valuable corrections: https://github.com/DefectDojo/django-DefectDojo/pull/1881
> Fix kubernetes helm upgrade

- dojo/tools/dsop/parser.py
- enhancement
- feature
- bugfix
- dependencies
> DSOP parser missing fields

- dojo/static/dojo/css/dojo.css
- dojo/templates/dojo/dashboard.html
If you hover over the graph, you will see the exact values now.
> fix dashboard graph - show values

- dojo/api_v2/serializers.py
- dojo/api_v2/views.py
Fixes #2119 
- enhancement
- feature
- bugfix
- dependencies
> honor note_type property on POST /findings/{id}/notes/

- DOCKER.md
removed obsolete and now wrong sentence
> Minor DOCKER.md fix for ptvsd

- dojo/tools/hadolint/parser.py
Fixing Issue #1741 and minor description improvement
---
- enhancement
- bugfix
> Hadolint parser fix

- dojo/tools/acunetix/parser.py
- dojo/tools/acunetix/parser_helper.py
- dojo/unittests/scans/acunetix/many_findings.xml
- dojo/unittests/scans/acunetix/one_finding.xml
- dojo/unittests/test_acunetix_parser.py
This is a PR to fix issues in Acunetix parser (Issue #1936 )
I have also improved few more things:
- Improved output for reference URLs
- Added Unit tests
- Removed unecessary variables
---
- enhancement
- bugfix
> Acunetix parser fix

- .github/release-drafter.yml
- .github/workflows/release-drafter.yml
Needed also to make sure `master` does not get overidden with the wrong settings.
`master` is already running with this configuration.
> updating dev release-drafter

- DefectDojoMaintainers.md
prefer MAINTAINERS.md instead, also existing -- and also out of date.
- enhancement
- performance
- feature
- bugfix
- dependencies
- New Migration
If the dev branch has changed since you started working on it, please rebase your work after the current dev. …
> Remove unused (outdated) maintainers file

- dojo/product/views.py
fix copy-paste to prevent GH config to show on product edit
> fix copy-paste to prevent GH config to show on product edit

- dojo/notifications/helper.py
- dojo/utils.py
fix some import issues which broke jira error handling after #2148 (sorry about that)
> Email notification improvements fix imports

- dojo/tools/bundler_audit/parser.py
This PR is to fix issue #2239
The parser needed some encoding changes (Python2 to Python3)
bugfix
> Fixing Bundler audit scan

- dojo/forms.py
Changes:
- technical contact, product manager, team manager: sort dropdown by fullname
- authorized users: user fullname instead of username, sort by fullname
> edit product: sort username dropdowns by (full) name

- dojo/db_migrations/0039_test_version.py
- [x ] Your code is flake8 compliant 
- [x ] Your code is python 3.5 compliant (specific python >=3.6 syntax is currently not accepted)
- enhancement
- feature
- bugfix
- dependencies
> Fix db migrations for test version field

- docker/entrypoint-integration-tests.sh
- adopt improvements from travis
- allow to run integrations tests with self-signed certificates
> adopt improvements for docker integrations-tests from travis

- dojo/utils.py
remove some leftover print statements
> remove some leftover print statements

- dojo/__init__.py
> Fix dojo version

- dojo/templates/dojo/engagements_all.html
- dojo/templates/dojo/findings_list.html
- dojo/templates/dojo/product.html
some columns are not really useful to be able to hide or they just look plain weird in the column visibility screen because they are really a dropdown menu. this PR fixes/improves that.
Also simpligies the datatables config a bit.
> datatables: improve column visibility settings

- .github/workflows/plantuml.yml
Explicitly adding workflow on dev too.
GH doc seems to say it has to be on the branch, but I think/thought it's only on the default branch. Would not make sense otherwise.
But for the sake of troubleshooting I guess..
> Adding GH action on dev branch

- Dockerfile.django
- Dockerfile.nginx
> docker: update to python 3.6

- dojo/product/views.py
- dojo/templates/dojo/product.html
> More GitHub integration fixes

- dojo/product/views.py
Should fix https://travis-ci.org/github/DefectDojo/django-DefectDojo/jobs/686661501 -- untested.
> Initialize gform var initialize gform var

- README.md
> README.md: Fix link to setup.bash docs

- dojo/finding/views.py
- dojo/test/views.py
bulk updating jira alert logic fixed to not alert on issues that have no jira config
> JIRA Config Bulk update fix

- docker/entrypoint-integration-tests.sh
- dojo/templates/dojo/engagement.html
- dojo/templates/dojo/engagements_all.html
- dojo/templates/dojo/findings_list.html
- dojo/templates/dojo/product.html
- tests/Endpoint_unit_test.py
- tests/Engagement_unit_test.py
- tests/Environment_unit_test.py
- tests/Finding_unit_test.py
- tests/Import_scanner_unit_test.py
- tests/Note_type_unit_test.py
- tests/Product_type_unit_test.py
- tests/Product_unit_test.py
- tests/Test_unit_test.py
- tests/User_unit_test.py
- tests/base_test_class.py
- tests/dedupe_unit_test.py
- tests/ibm_appscan_test.py
- tests/local-integration-tests.bat
- tests/local-integration-tests.sh
- tests/smoke_test.py
- travis/integration_test-script.sh
Merge pull request #2403 from valentijnscholten/chrome83-findings-list
integration tests: wait for findings list to load
> backport fixes for integration tests to 1.6.1 

- dojo/notifications/helper.py
- make sure fields don't exceed max length (fixes #2411)
- catch exceptions, log them, and continue sending next alert
- don't log (harmless) exceptions about not yet implemented message templates
> improve error handling notifications

- DOCKER.md
add known issue about finding images not working in release mode
> add known issue about finding images not working in release mode

- dojo/templates/dojo/view_eng.html
Move Check List and Engagement Questionnaire to a collapsable field to be viewed when desired. This enhancement is to make room for multiple new features at the engagement level. Requested by @mtesauro 
- enhancement
- feature
- bugfix
- dependencies
> Declutter view engagement page

- dojo/search/views.py
fixes #2480
I think this has been there for a long time, but it's a quick fix anyway.
I don't think normal users (non staff / non superuser) have anything to do with templates anyway, but at least this fixes the error.
> search: fix for non-staff non-superusers

- Dockerfile.django
- Dockerfile.integration-tests
- Dockerfile.nginx
With additional care this time around.
> Upgrade docker containers to python 3.6

- dojo/fixtures/test_type.json
- dojo/forms.py
- dojo/templates/dojo/import_scan_results.html
- dojo/templates/dojo/view_finding.html
- dojo/tools/bugcrowd/parser.py
- dojo/tools/factory.py
- dojo/unittests/scans/bugcrowd/BugCrowd-many.csv
- dojo/unittests/scans/bugcrowd/BugCrowd-one.csv
- dojo/unittests/scans/bugcrowd/BugCrowd-zero.csv
- dojo/unittests/test_bugcrowd_parser.py
BugCrowd parser with unit tests as well as making similar findings collapsed by default as requested by @mtesauro 
- enhancement
- feature
- bugfix
- dependencies
> BugCrowd parser and collapse similar findings by default

- DOCKER.md
- README.md
- dojo/__init__.py
- setup.py
- release aftercare: merge hotfix 1.6.2 into 1.6.5
- bump version numbers
> release aftercare: merge hotfix 1.6.2 into 1.6.5

- dojo/github_issue_link/urls.py
- dojo/models.py
- dojo/templates/dojo/product.html
- dojo/utils.py
Some jira fixes for unreferences issues and:
- #2460
- Most of #2458 I guess, but this will be left as an exercise to @dayal18 ;-)
> JIRA fixes

- dojo/finding/views.py
> Fix JIRA update issue if issue already linked

- dojo/api_v2/serializers.py
- dojo/fixtures/dojo_testdata.json
- dojo/models.py
- dojo/templatetags/display_tags.py
- dojo/unittests/test_rest_framework.py
> return age and sla days remaining for findings apiv2

- dojo/models.py
> fixed duplicate_finding_set function to not throw error

- dojo/github.py
An earlier search/replace messed up here.
> fix github issue creation

- setup/scripts/common/prompt.sh
- setup/setup.bash
To be accompanied by a docs update.
Rebased onto `release/1.6.5` to get the word out quickly.
Docs update: https://github.com/DefectDojo/Documentation/pull/97
> setup.bash EOL

- dojo/tools/ibm_app/parser.py
> Fix IBM appscan severity capitalization

- SECURITY.md
Amendments to how security issues should be worked on to avoid premature disclosure and protect DefectDojo users.
> Changes to SECURITY.md

- README.md
- dojo/finding/views.py
- dojo/github.py
- dojo/github_issue_link/urls.py
- dojo/jira_link/views.py
- dojo/models.py
- dojo/notifications/helper.py
- dojo/search/views.py
- dojo/tasks.py
- dojo/templates/dojo/product.html
- dojo/templates/dojo/snippets/engagement_list.html
- dojo/test/views.py
- dojo/tools/npm_audit/parser.py
- dojo/tools/qualys/parser.py
- dojo/unittests/scans/npm_audit_sample/empty_with_error.json
- dojo/unittests/test_npm_audit_scan_parser.py
- dojo/utils.py
- setup/scripts/common/prompt.sh
- setup/setup.bash
- travis/integration_test-script.sh
Do NOT squash-merge, but use regular merge!
This PR merges `release/1.6.5` "back into" `dev`. This time it contains a lot of commits as `dev` was a lot behind in terms of commits.
Would be good to review this one, as there were quite a bit of conflicts.
> merge release/1.6.5 into dev

- dojo/product/views.py
- dojo/test/views.py
Code changes in test/views.py is for #2521 
Code changes in product/views.py is for #2577
> Jira fixes for #2521 #2577

- DOCKER.md
add docker-compose build to docker readme
> doc: add docker-compose build

- setup/scripts/common/dojo-shared-resources.sh
Removed pwgen for Docker-only inside install_db.
This fixes #2500
> Added pwgen for all platforms.

- dojo/static/dojo/css/dojo.css
- dojo/templates/dojo/notifications.html
> remove BREAK in html

- dojo/forms.py
- dojo/templates/dojo/view_eng.html
- dojo/test/views.py
> Add description to test add and edit

- dojo/fixtures/test_type.json
This PR will fix test_type of HuskyCI (rename HuskyCi to HuskyCI Report)
Label: bugfix
> fix: rename HuskyCi to HuskyCI Report in test_type

- dojo/finding/views.py
- dojo/utils.py
This is a fix for updating issues in JIRA from DDJ.  On DDJ 1.6.5, when an issue is closed or re-opened, DDJ doesn't update existing JIRA issues.  This ticket will set the push_to_jira flag when an update that has a JIRA ticket changes status.  
Also included are a couple minor logging updates to log issues when DDJ tries to update a JIRA ticket and there is a problem with the update.  This change will log the event and send the response from JIRA.
When …
> Fix push close and re-open from DDJ to JIRA

- DOCKER.md
trouble shooting steps for changing the password.
> added steps for changing the password

- Dockerfile.nginx
- docker/entrypoint-nginx.sh
Benefits are less vulerabilities and a slimmer image.
> Switch Nginx image to Alpine

- dojo/tools/aqua/parser.py
- dojo/unittests/scans/aqua/many_v2.json
- dojo/unittests/scans/aqua/one_v2.json
- dojo/unittests/test_aqua_parser.py
@madchap 
Supersedes #2708.
This fixes #2389
> Add support for another Aqua format

- dojo/tools/gitleaks/parser.py
[Gitleaks v5](https://github.com/zricethezav/gitleaks/releases/tag/v5.0.0) adds 2 interesting new fields: lineNumber and operation.
This PR adds the line number and the operation type (addition, deletion) to the finding's description.
> Gitleaks v5 - parser update

- dojo/tools/eslint/parser.py
when ruleId=null or message=null, there is a 500 error. This avoid it
> ESLint parser title error checking

- dojo/tools/awssecurityhub/parser.py
- dojo/unittests/scans/awssecurityhub/many_findings.json
- dojo/unittests/scans/awssecurityhub/one_finding.json
- dojo/unittests/scans/awssecurityhub/repeated_findings.json
NOTE: This closes #2780.
- enhancement
- performance
- feature
- bugfix
- dependencies
- settings_changes (when the PR introduces changes or new settings in settings.dist.py)
If the dev …
> #2780 Support either prop defined as findings or Findings in AWS Security Hub Parser

- dojo/api.py
- dojo/api_v2/serializers.py
- dojo/test/views.py
> Fix duplicated findings in reimport

- dojo/unittests/test_utils_deduplication_reopen.py
- dojo/utils.py
This PR closes https://github.com/DefectDojo/django-DefectDojo/pull/2526
This PR is regarding https://github.com/DefectDojo/django-DefectDojo/issues/2525
If the dev branch has changed since you started working on it, please rebase your work after the current dev.
On your working branch `mybranch`:
```
git rebase dev mybranch
```
In case of conflict:
```
git mergetool
git rebase --continue
```
When everything's fine on your local branch, force push to your `myOrigin` remote: 
```
git push myOrigin --force-with-lease
```
To cancel everything: 
```
git rebase --abort
```
```
git rebase -i origin/dev
```
- Replace `pick` by `fixup` on the commits you want squashed out
- Replace `pick` by `reword` on the first commit if you want to change the commit message
- Save the file and quit your editor …
> hotfix: do not reopen false positives and out_of_scope on behalf of SDA SE

- dojo/search/views.py
> search: fix when searching for empty string

- .travis.yml
- travis/before-install.sh
- travis/script.sh
Related to: https://github.com/DefectDojo/django-DefectDojo/pull/2547 
Upgrade to: 
- K8S_VERSION=v1.19.0
- MINIKUBE_VERSION=v1.12.3
- HELM_VERSION=v2.16.10
Now minikube uses docker driver
> Upgrade components  minikube k8s helm

- dojo/notifications/helper.py
Hi,
As described in issue #2713 created by another user, we receive repeated slack notifications.
When a system notification is created, DefectDojo try to send it to all administrators via slack. But if a user is not found in slack and a main slack channel is defined, the notification is redirected to this channel.
So I suggest that you send notifications to admins only if a dedicated channel is not defined.
That's all.
Thanks by advance
> Fix notifications spam (issue #2713)

- dojo/engagement/views.py
- dojo/templates/dojo/view_eng.html
Motivated by #2837 
- enhancement
- performance
- feature
- bugfix
- dependencies
- settings_changes (when the PR introduces changes or new settings in settings.dist.py)
If the dev branch has changed since you started working on it, please rebase your work after the current dev.
On your working branch `mybranch`:
```
git rebase dev mybranch
```
In case of conflict:
```
git mergetool
git rebase --continue
```
When everything's fine on your local branch, force push to your `myOrigin` remote: 
```
git push myOrigin --force-with-lease
```
To cancel everything: 
```
git rebase --abort
```
```
git rebase -i origin/dev
``` …
> update threat model download process

- .gitignore
- .travis.yml
- helm/defectdojo/templates/_helpers.tpl
- helm/defectdojo/templates/celery-beat-deployment.yaml
- helm/defectdojo/templates/celery-worker-deployment.yaml
- helm/defectdojo/templates/configmap.yaml
- helm/defectdojo/templates/django-deployment.yaml
- helm/defectdojo/templates/extra-secret.yaml
- helm/defectdojo/templates/initializer-job.yaml
- helm/defectdojo/templates/secret-postgresql.yaml
- helm/defectdojo/values.yaml
- travis/script.sh
Squashed k8s helm extending configs
> K8s helm extending configs v2

- dojo/templates/dojo/asciidoc_report.html
- dojo/templates/dojo/custom_asciidoc_report_endpoints.html
- dojo/templates/dojo/custom_asciidoc_report_findings.html
- dojo/templatetags/get_endpoint_status.py
Added a few clauses to the 'get_endpoint_status python' file to account for remediated endpoints as well as findings with no endpoint status. This fixes issue #2744
> Fixes problems generating AsciiDOC product report

- dojo/settings/settings.dist.py
No functional change.
Adding a few environment variables, in order to have a bit more control when using helm's `extraConfigs`.
> Adding more envvars to settings.py

- helm/defectdojo/Chart.yaml
- helm/defectdojo/requirements.lock
- helm/defectdojo/templates/configmap.yaml
- helm/defectdojo/templates/django-deployment.yaml
- nginx/nginx_TLS.conf
While tests passed on https://github.com/DefectDojo/django-DefectDojo/pull/2839, trying again some stuff on minikube it would not work.
This PR is to fix what was missed.
> Fixing helm /var/run issue

- dojo/finding/views.py
> Fix edit findings function

- Dockerfile.django
- Dockerfile.integration-tests
- Dockerfile.nginx
Reverts DefectDojo/django-DefectDojo#2891
Cannot build because of unsigned signatures.
> Revert "build(deps): bump python from `09bb817` to `e525911`"

- .travis.yml
- travis/before-script.sh
- travis/script.sh
Improvements:
- replaced helm2 with helm3
- abandoning tiller component
> Helm3 transition

- dojo/tools/anchore_enterprise/parser.py
This results in objects such as checks and images not being a dictionary when parsing a empty policy.
Signed-off-by: Cosmin Cojocar <ccojocar@cloudbees.com>
- enhancement
- performance
- feature
- bugfix
- dependencies
- New Migration (when the …
> Import empty Anchore policies without error

- dojo/templates/dojo/change_pwd.html
- dojo/templates/dojo/login.html
- dojo/templates/dojo/snippets/endpoints.html
- dojo/templatetags/get_endpoint_status.py
- dojo/test/views.py
- dojo/tools/qualys_infrascan_webgui/parser.py
- dojo/tools/sonarqube_api/importer.py
- dojo/utils.py
* Fix reporting of endpoints and file paths. File paths for static scans were omitted from reports entirely. Also made it possible for both endpoints and file paths to be displayed simultaneously for dynamic/static scanners.
* Remove loud headers from SonarQube API importers because they broke reports table of contents.
* restrict autocomplete from password forms
* Improve cipher strength on encryption functions in utils.py
* Restrict resolved entities Qualys InfraScan XML Parser
> Security and Bug Fixes

- dojo/finding/views.py
> closed findings: filter by is_Mitigated instead of mitigated

- dojo/filters.py
- dojo/metrics/views.py
- dojo/models.py
- dojo/product/views.py
- dojo/templates/dojo/dashboard-metrics.html
- dojo/templates/dojo/metrics.html
- dojo/templates/dojo/product_metrics.html
- dojo/test/views.py
- dojo/utils.py
Modify metrics to provide measurements on `Findings` and `Endpoint_Statuses`. This applies to metrics on the `product` and `product_type` levels.
> Calculate metrics by endpoint status

- dojo/forms.py
> fix add finding from template req_resp key error

- dojo/templates/dojo/custom_asciidoc_report_endpoints.html
- dojo/templates/dojo/custom_asciidoc_report_findings.html
> Fix custom report endpoint_status error

- README.md
Companion PR at https://github.com/DefectDojo/Documentation/pull/131
> Adding short API block in README

- docker/entrypoint-integration-tests.sh
Fixes a copy and paste mistake.
> Bugfix typo in docker integration tests

- dojo/engagement/views.py
- dojo/forms.py
- dojo/product/views.py
- dojo/user/helper.py
Permissions weren's checked when adding engagement.
Dropdown with products wasn't filtered for non staff users.
fixes #2999
> add engagement: fix permission checks

- dojo/api.py
> Fix APIv1 Endpoint_Status bug

- dojo/templates/dojo/finding_related_row.html
fix jira column on similar findings rows
> fix jira column on similar findings rows

- dojo/api.py
- dojo/api_v2/serializers.py
> Fix burp request/response encoding errors in API

- docker-compose.override.https.yml
The same change as #3041 but for `docker-compose.override.https.yml`.
> Fix nginx port in docker-compose.override.https.yml

- dojo/management/commands/create_endpoint_status.py
Add an endpoint status creation script per the moderator meeting. Will be adding a note into the release draft as well.
associated [documentation](https://github.com/DefectDojo/Documentation/pull/144)
> Add endpoint_status creation script

- .github/workflows/flake8.yml
- .github/workflows/integration-tests.yml
- .github/workflows/unit-tests.yml
> master->dev: github action workflow config sync

- dojo/templates/dojo/api_key.html
- dojo/templates/tastypie_swagger/index.html
- dojo/unittests/test_apiv2_metadata.py
apiv1 deprecation: show warning on docs and api key pages
> apiv1 deprecation: show warning on docs and api key pages

- dojo/jira_link/views.py
- dojo/tool_type/views.py
- dojo/utils.py
In response to #3103 and a correction on #3016 
Fixes #3102
> Add 'options' to JIRA connections

- Dockerfile.django
- dojo/tools/safety/parser.py
Fixes https://github.com/DefectDojo/django-DefectDojo/issues/2795
> enable safety parser to work offline

- .github/workflows/k8s-testing.yml
Github workflow for k8s helm deployment on the top of the minikube
Builds docker images
Deploying matrix of config 
Tests deployment within the k8s
> GitHub Action for kubernetes tests

- .github/workflows/k8s-testing.yml
> workflows: master -> dev sync

- dojo/api_v2/views.py
Adding prefetch_related fields.
> APIv2 findings performance improvements

- .travis.yml
travis: disable all tests due to hanging jobs and migration to GitHub Actions
> travis: disable all tests due to hanging jobs and migration to GitHub Actions

- .github/workflows/new-release-pr.yml
Fixes https://github.com/DefectDojo/django-DefectDojo/issues/3115
> GHA release: update version in package.json

- dojo/templatetags/display_tags.py
> Update url_shortner to fix bugs and show more meaningful part of the endpoint

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Add more explicit note about required information and the necessitiy to specify the exact error message being observed.
> Issue and PR template update

- dojo/tools/veracode/parser.py
This PR fixes two issues that were preventing us from importing Veracode reports.
Changes:
- Handle when mitigation dates are not present in the report. (It uses None instead.)
- Truncate the component name when it is too long to fit in the database.
> Veracode parser bug fixes.

- .github/workflows/k8s-testing.yml
- helm/defectdojo/values.yaml
Setting k8s in actions to use:
-  imagePullSecrets
-  kubectl to fetch django web
- documented way of secret creation in  helm values
> GitHub Action: k8s helm dockerhub login

- dojo/endpoint/views.py
PR for #3167 :
Added import statement in /dojo/endpoint/view.py
Tests completed successfully and the application works fine on our server.
Target branch is master.
> fix view all endpoints: added import statement for #3167

- dojo/jira_link/views.py
- dojo/notifications/helper.py
- dojo/tool_type/views.py
fixes adding / editing JIRA config which is broken in 1.9.0 and 1.9.1
fixes #3162 #3163
> fix jira add/edit configuration

- .github/workflows/k8s-testing.yml
sync master to dev after k8s workflow updates #3183
> sync master to dev after k8s workflow updates #3183

- KUBERNETES.md
Per the move from https://kubernetes-charts.storage.googleapis.com/ to https://charts.helm.sh/stable
> k8s stable repo doc change

- dojo/filters.py
- dojo/finding/views.py
- dojo/models.py
- dojo/product/views.py
This adds the following new filters:
- Allow viewing findings from a particular engagement or set of engagements.
- Allow filtering the list of engagements by status.
> Add finding > engagement and engagement > status filters.

- .github/workflows/k8s-testing.yml
* Refactoring gitlab k8s action
* Uncommenting branches
Co-authored-by: Dubravko Sever <dubravko.sever@pan-net.eu>
> GHA-k8s: merge master into dev

- dojo/fixtures/defect_dojo_sample_data.json
The title pretty much sums this up. This fixture is only used for demo purposes, so it will affect a handful of people for the better.
> Update defect_dojo_sample_file.json to work with recent versions

- dojo/reports/views.py
> Remove excessive qs in report generator

- dojo/reports/views.py
backporting #3175 to 1.9.3 branch
> fix reports: add missing Q import

- dojo/jira_link/views.py
> jira: use correct url for dojo_alert notification

- dojo/jira_link/views.py
- dojo/tools/sonarqube_api/updater_from_source.py
Got bitten by this using the jira webhook.
Links to https://github.com/DefectDojo/django-DefectDojo/pull/2990 which is still waiting for response.
> Fix JIRA owner instead of reporter

- .github/release-drafter.yml
Added a section as per our office hours discussions today.
> Release drafter - add breaking changes section

- dojo/jira_link/helper.py
- dojo/test/views.py
Attempting to re-import a scan does not work when there is no valid Jira config. I also made a slight performance change to the jira_helper stuff too, but nothing major.
> Allow re-import scan to function without JIRA

- dojo/context_processors.py
- dojo/filters.py
- dojo/finding/views.py
- dojo/models.py
- dojo/settings/settings.dist.py
- dojo/templates/base.html
- dojo/templates/dojo/findings_list_snippet.html
- dojo/user/views.py
- Closed Finding view has columns misaligned
- Set mitigated time in the finding list bulk edit
- Add configurable option to remove notifications dropdown (default to false)
- Add configurable option to prefetching of tags (default to true)
- Remove endpoint status objects from endpoint filters
> Various bug fixes in various places

- dojo/tools/awssecurityhub/parser.py
- dojo/unittests/scans/awssecurityhub/many_findings.json
> aws security hub: fix handling of missing lastObservedAt

- dojo/api_v2/serializers.py
- dojo/test/views.py
> reimport: don't try to set component_name for absent findings

- dojo/tools/nikto/parser.py
Fixes nikto issue reported in https://github.com/DefectDojo/django-DefectDojo/issues/3268
The regex probably needs rework. This PR is to get a working nikto parser before the next release.
> Nikto quick fix

- dojo/metrics/views.py
> Fix NoneType error on Metrics page

- .github/workflows/k8s-testing.yml
Added checks against of errors as final checks.
If errors detected: dump logs
> K8s additional checks 26 11

- dojo/finding/views.py
- dojo/jira_link/helper.py
fix #3352 
linking a finding to an existing JIRA issue failed with a NoneType exception.
> jira: fix link existing jira issue

- .github/workflows/flake8.yml
- .github/workflows/integration-tests.yml
- .github/workflows/new-release-master-into-dev.yml
- .github/workflows/unit-tests.yml
merge from master to dev https://github.com/DefectDojo/django-DefectDojo/pull/3382
> GHA: disable login for PR related workflows (#3382)

- docker/entrypoint-uwsgi.sh
> Remove comment to fix #3392

- helm/defectdojo/requirements.lock
Adjusting to the yaml, it got out of sync.
> Update helm requirements.lock

- docker-compose.override.dev.yml
- docker-compose.override.ptvsd.yml
In dev environment volume for threat was missing
> Adding volume for threat image in dev

- Dockerfile.django
- Dockerfile.nginx
> Dockerfile: don't upgrade pip

- dojo/context_processors.py
- dojo/settings/settings.dist.py
- dojo/templates/dojo/login.html
Aesthetic enhancement, when integrating with OAuth services, usually the application would redirect to external page for authentication purpose and username/password input form created a login process confusion.
- Allowing input form to be hidden (showing by default)
> [feat/login-form] Allowing login forms to be hidden

- .github/workflows/new-release-tag-docker.yml
Reverts DefectDojo/django-DefectDojo#3454 which reverted #3416
> Revert "Revert "release workflow: simplify matrix""

- dojo/reports/views.py
> tagulous/reports: fix old prefetch fields

- dojo/reports/views.py
- tests/Report_builder_unit_test.py
fixes #3485 - but now properly including re-enabling commented out tests
> tagulous/reports: fix old prefetch fields - take 2

- dojo/fixtures/test_type.json
- dojo/forms.py
- dojo/templates/dojo/import_scan_results.html
- dojo/tools/sarif/parser.py
Add missing data in fixtures and some UI elements to import a SARIF report from the UI.
> Add missing modifications for SARIF format

- docker/entrypoint-celery-beat.sh
- docker/entrypoint-celery-worker.sh
the entrypoints for celery were not yet given the full set of external mount options for settings related files.
> celery entrypoints: support all settings related mounts

- dojo/tools/gitlab_sast/parser.py
- dojo/unittests/scans/gitlab_sast/gl-sast-report-confidence.json
- dojo/unittests/scans/gitlab_sast/gl-sast-report-cwe.json
- dojo/unittests/scans/gitlab_sast/gl-sast-report-many-vuln.json
- dojo/unittests/test_gitlab_sast_parser.py
GitLab SAST doesn't always set the parameter ``confidence`` for a vulnerability, leading to an exception when importing the vulnerabilities.
> Parameter confidence is optional and CWE's are not always numerical in GitLab SAST

- dojo/tools/clair/parser.py
> feat(clair parser): parse component name and version

- .github/workflows/k8s-testing.yml
Implementing retry for  fetching login page
> Adding retry into the k8s workflow

- BRANCHING-MODEL.md
- doc/branching_model.puml
Addresses https://github.com/DefectDojo/django-DefectDojo/issues/3587
Preview the schema at https://www.planttext.com
> Update to release workflow

- dojo/tools/microfocus_webinspect/parser.py
- dojo/unittests/test_microfocus_webinspect_parser.py
> Improve Micro Focus Webinspect parser

- dojo/tools/appspider/parser.py
- dojo/unittests/scans/appspider/one_vuln.xml
- dojo/unittests/test_appspider.py
> Add more unit tests for AppSpider report parser

- dojo/models.py
some old code left behind after migration to `tagulous`
> remove old/dead/left-behind code

- helm/defectdojo/Chart.yaml
- helm/defectdojo/requirements.lock
- helm/defectdojo/requirements.yaml
- helm/defectdojo/templates/celery-beat-deployment.yaml
- helm/defectdojo/templates/celery-worker-deployment.yaml
- helm/defectdojo/templates/django-deployment.yaml
- helm/defectdojo/templates/initializer-job.yaml
- helm/defectdojo/templates/tests/unit-tests.yaml
- helm/defectdojo/values.yaml
To enable postgresql to work with restricted SCC in OpenShift and setting some resource specifications too, to work with limit ranges.
> Exposing additional securityContext settings in parent values.yaml

- dojo/tools/burp_api/parser.py
- dojo/unittests/scans/burp_api/many_vulns.json
- dojo/unittests/test_burp_api_parser.py
fix "impact can not be none" error
> Fix impact bug on Burp REST API parser and add more unit tests

- dojo/product/views.py
for some errors the form would post and page refreshed but errors were not shown.
> add product: fix missing error messages

- dojo/decorators.py
- dojo/jira_link/views.py
- dojo/unittests/test_jira_webhook.py
jira cloud doesn't send the key for authors of comments, we need to fallback to username and hope for the best.
bug introduced in #3606 so not yet released, only in dev atm.
> jira: fix broken author check for cloud

- dojo/templates/dojo/view_eng.html
view engagment layout div structure was broken after #3566 . not sure if this is perfect fix but at least it looks back to normal now.
> fix engagement styling bug

- dojo/endpoint/views.py
- dojo/reports/views.py
- dojo/utils.py
According to `dojo/utils.py`, the function `redirect` has 2 parameters.
https://github.com/DefectDojo/django-DefectDojo/blob/279debf699ed2512f0af53696df5b95bcf02597f/dojo/utils.py#L1670-L1674 
This means that these calls are bugs:
https://github.com/DefectDojo/django-DefectDojo/blob/279debf699ed2512f0af53696df5b95bcf02597f/dojo/endpoint/views.py#L445
https://github.com/DefectDojo/django-DefectDojo/blob/279debf699ed2512f0af53696df5b95bcf02597f/dojo/reports/views.py#L321
> Fix bug in redirect function call

- README.md
> Add info on the demo site to the README

- README.md
- tests/base_test_class.py
> master-into-dev: use --disable-dev-shm-usage to start chrome (#3739)

- dojo/templatetags/display_tags.py
- dojo/templatetags/event_tags.py
- dojo/templatetags/navigation_tags.py
remove unused leftover display tags
> template tags: remove unused leftover tags

- dojo/unittests/tools/test_safety_parser.py
Fix a unit test that is broken for now.
> Safety parser: fix error in unit tests

- dojo/filters.py
- dojo/templates/dojo/dashboard.html
> risk acceptance rename left over reporter to owner

- dojo/templates/dojo/add_findings.html
- dojo/templates/dojo/view_eng.html
- tests/test_test.py
there was a javascript error on the add_findings page when adding a finding to a test. 
this PR fixes the error, and adds that screen to the integration tests.
> tests: fix add finding javascript error

- .github/workflows/gh-pages.yml
Trigger gh-pages build when push to dev branch.
> feat(docs): trigger gh-pages build on push to dev

- requirements.txt
fixes #3878 after upgrading to pyjwt 2.0.1
> update social-auth-core to support pyjwt 2.0.1

- dojo/api.py
- dojo/api_v2/serializers.py
- dojo/engagement/views.py
- dojo/test/views.py
- dojo/tools/nexpose/parser.py
- dojo/unittests/scans/nexpose/report_auth.xml
- dojo/unittests/tools/test_nexpose_parser.py
This pull request fixes 2 bugs:
Tag works well now:
Linked to https://github.com/DefectDojo/django-DefectDojo/issues/3869
> Nexpose parser bugfixes

- dojo/templates/dojo/view_eng.html
Added test strategy URL to display in the engagement sidebar
> Updates to Engagements sidebar

- dojo/tools/checkmarx/parser.py
- dojo/tools/factory.py
- dojo/tools/sonarqube/parser.py
- dojo/unittests/tools/test_checkmarx_parser.py
- dojo/unittests/tools/test_sonarqube_parser.py
This pull request implement a missing feature, the detailed mode for 2 parsers
* Checkmarx Scan
* SonarQube Scan
> Dynamic infrastructure: implement detailed mode

- dojo/templates/dojo/view_test.html
> view_test: fix paging of findings

- dojo/templates/dojo/view_test.html
> view_test: fix paging of findings (backport to 1.13.x)

- .github/workflows/test-helm-chart.yml
- ct.yaml
- helm/defectdojo/Chart.yaml
- helm/defectdojo/templates/django-ingress.yaml
- helm/defectdojo/values.yaml
Lint helm charts to help with silly errors.
Addresses https://github.com/DefectDojo/django-DefectDojo/issues/3766
> [GHA] Lint helm charts

- .github/workflows/k8s-testing.yml
- helm/defectdojo/templates/django-ingress.yaml
Added into minikube config to test k8s v.1.16.0 and  v.1.20.0
> GHA: Test multiple k8s versions

- dojo/finding/views.py
This was a typo as the PR with Manage Files was not merged until like October 2020
> Change Finding Image deprecation to 2021 rather than 2020

- README.md
Finally getting around to adding this
> Add LinkedIn to Readme

- dojo/tools/openvas_csv/parser.py
- dojo/unittests/scans/openvas/report-e2759495-f26d-4089-9c56-12a10dc36c9c.csv
- dojo/unittests/tools/test_openvas_csv_parser.py
OpenVAS parser fix error and add unit tests
> OpenVAS parser: fix error and add unit tests

- README.md
adds some high level topics we are working on, without promising anything. still good to share some info.
> add magical illusionary roadmap

- dojo/db_migrations/0001_initial.py
- dojo/models.py
Fix typo in models. Crital => Critical
> Fix typo in models. Crital => Critical

- docs/content/contributing/how-to-write-a-parser.md
dont' need now to modify dojo/fixtures/test_type.json according to @damiencarol in https://github.com/DefectDojo/django-DefectDojo/pull/4030#discussion_r590554793
> Fix for new parser infra

- dojo/tools/aqua/parser.py
- dojo/unittests/tools/test_aqua_parser.py
Add CVSS3 score if exists.
Add unittests for it
> Update Aqua-scanner import for CVSS3 finding field

- dojo/utils.py
This PR aims to resolve issues #3991 and #4052.
I have fixed the typo in models.py and duplicate code in a_counts, earlier there were 2 elif having same conditions due to that total value for a_count was always zero. I have changed it according to the condition.
@damiencarol  please review the PR and suggest me changes.
Thanks.
> Fix Typo and duplicate code error 

- dojo/settings/settings.dist.py
Adding: deduplication rules for Nexpose scanner
> Nexpose dedup settings

- dojo/settings/settings.dist.py
- dojo/tools/burp_api/parser.py
- dojo/unittests/tools/test_burp_api_parser.py
> Burp REST API: implement de-duplication and request/response

- dojo/templates/dojo/view_test.html
Same code snippet as used with Findings, just added and tested with Tests. Works as expected.
> Updates Bulk Edit status combination/validation for Tests

- docs/content/basics/features.md
As discussed in pull request #4065
> Remove generation of PDF reports in documentation

- docker/extra_settings/README.md
- docs/content/integrations/social-authentication.md
> Some typo fixes

- dojo/jira_link/views.py
fixing a copy and paste artifact
> jira webhook update datetime parse fix

- dojo/api_v2/prefetch/schema.py
- dojo/api_v2/schema/extra_schema.py
- dojo/api_v2/schema/utils.py
- dojo/api_v2/serializers.py
- dojo/api_v2/views.py
- dojo/risk_acceptance/api.py
- dojo/settings/settings.dist.py
- dojo/unittests/test_swagger_schema.py
- dojo/urls.py
- requirements.txt
> api docs: switch back to supported drf-yasg

- dojo/finding/views.py
- dojo/forms.py
- dojo/jira_link/helper.py
Visual Studio code pointed me to a undeclared variable which lead me to fixing the push to JIRA to stub findings (when promoting potential findings to real findings).
> stub/potential findings: fix push to JIRA

- dojo/tools/sarif/parser.py
- dojo/unittests/scans/sarif/bash-report.sarif
- dojo/unittests/scans/sarif/dependency_check.sarif
- dojo/unittests/scans/sarif/taint-python-report.sarif
- dojo/unittests/tools/test_sarif_parser.py
This pull request reduce the title in a smart way to fix an error on title limit.
I also added more SARIF reports from different tools and more unit tests for data.
Also this PR add limited support for CVEs when the rule ID is a CVE.
> SARIF parser: fix error when titles are to long

- docs/content/integrations/import.md
- dojo/tools/nikto/parser.py
- dojo/unittests/scans/nikto/juice-shop.json
- dojo/unittests/tools/test_nikto_parser.py
> Nikto parser: add support for JSON format

- dojo/tools/wpscan/parser.py
- dojo/unittests/scans/wpscan/empty.json
- dojo/unittests/scans/wpscan/sample.json
- dojo/unittests/scans/wpscan/wordpress.json
- dojo/unittests/scans/wpscan/wpscan.json
- dojo/unittests/tools/test_wpscan_parser.py
> WPScan: Add more tests and fixes missing finding

- dojo/tools/mobsf/parser.py
- dojo/unittests/tools/test_mobsf_parser.py
the parser is broken since the big refactoring of Dynamic Infrastructure.
Fixes #4158
> Fix MobSF parser

- dojo/tools/nexpose/parser.py
Fixings broken URL formatting.
> Fix: Nexpose ref URL format

- .github/workflows/new-release-tag-docker.yml
- KUBERNETES.md
revert https://github.com/DefectDojo/django-DefectDojo/pull/3849 and https://github.com/DefectDojo/django-DefectDojo/pull/4143
@valentijnscholten said.
> Revert Helm chart PRs, suspected to cause GHA to hang

- .github/workflows/new-release-tag-docker.yml
- KUBERNETES.md
Reverts DefectDojo/django-DefectDojo#4170
so basically reimplement #3849 and #4143
> Publish the Helm chart tarball with each release (try 2)

- dojo/tools/trustwave/parser.py
- dojo/unittests/tools/test_trustwave_parser.py
> Trustwave parser: switch endpoints to unsaved_endpoints 

- dojo/tools/generic/parser.py
- dojo/unittests/scans/generic/generic_csv_defect_dojo.csv
- dojo/unittests/tools/test_generic_parser.py
> Generic parser: fix endpoint management

- dojo/tools/anchore_engine/parser.py
- dojo/unittests/scans/anchore/many_vulns.json
- dojo/unittests/tools/test_anchore_engine_parser.py
Implement CVSS v3 score for Anchoer Engine parser
> [anchore parser] add cvssv3_score when available

- dojo/unittests/tools/test_safety_parser.py
> Fixes safety parser unit test#4191 (#4192)
