DefectDojo/django-DefectDojo

- setup.bash
Not everyone cares about running things as root, especially in test environments, so I'm taking out the requirement to install as a non-root-user in setup.bash.
JUST BE CAREFUL, KIDS! ONLY YOU CAN PREVENT FOREST FIRES!
> Removing non-root-user requirement for setup.bash

- setup.bash
- setup.py
Fixes install, tested on Centos 6.6, Fedora 21 and Ubuntu 14.04 servers. No pervious packages other than git and mysql installed on boxes before setup.bash was executed.  Mysql user needs to exist before install script is executed.
> Fixes #12 and #22

- CONTRIBUTING.md
- LICENSE.md
- README.md
- license.md
Closes #40.
- Switching to the Simplified BSD 3-clause license
- Moving CONTRIBUTING.md to root directory for consistency purposes
> Switching to Simplified BSD license, moving CONTRIBUTING doc to root

- ansible/roles/webserver/tasks/app.yml
- setup.py
Issue found by Michael Dong. I have set dojo to install 0.3.1 rather than 0.3.2
> django-audit log 0.3.2 breaks install

- dojo/engagement/views.py
- dojo/tools/zap/parser.py
In Zap (2.4.2), the lowest priority is called ‘Informational’, causing problems on import. This fixes that.
> improvements to zap parser

- ansible/roles/webserver/tasks/app.yml
Correcting error message:
```
TASK [webserver : Create Django superuser] *************************************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "failed": true, "msg": "unsupported parameter for module: sudo_user"}
```
The error appears to be due to errant indention of the sudo and sudo_user modules in app.yml here:
```
- name: Create Django superuser
shell: echo "from django.contrib.auth.models import User; User.objects.create_superuser('{{ dd_super_user }}', '{{ dd_super_user_email }}', '{{ dd_super_user_pass }}')" | {{ venv_dir }}/bin/python {{ dd_install_dir }}/manage.py shell && touch /home/{{ dd_user }}/.supercreated
args:
creates: /home/{{ dd_user }}/.supercreated
sudo: yes
sudo_user: '{{ dd_user }}'
```
Removing the preceding space from the sudo and sudo_user …
> Issue #71: correcting ansible module indentation

- dojo/forms.py
- dojo/management/commands/migrate_product_contacts.py
- dojo/models.py
- dojo/templates/dojo/add_user.html
- dojo/templates/dojo/edit_product.html
- dojo/templates/dojo/new_product.html
- dojo/templates/dojo/profile.html
- dojo/templates/dojo/users.html
- dojo/templates/dojo/view_product.html
- dojo/user/views.py
Takes care of #62. Product now has three new fields: product_manager, team_manager, and technical_contact.
These replace the fields prod_manager, manager, and tech_contact.
The new fields are foreign keys to User objects.
User is now extended by UserContactInfo which adds ability to store a title, phone, cell, twitter and github for each user.
In order for these changes to work correctly, updaters must run the following commands:
`./manage.py makemigrations dojo`
`./manage.py migrate`
`./manage.py migrate_product_contacts`
Fields prod_manager, manager, and tech_contact are no longer used anywhere, but left in Product model for backwards compatibility.  They will be removed in future updates.  References to these in the project have been replaced by new fields product_manager, …
> Takes care of #62

- dojo/metrics/views.py
- dojo/models.py
- dojo/settings.dist.py
- dojo/templates/dojo/metrics.html
- dojo/templates/dojo/pt_counts.html
- dojo/templates/dojo/research_metrics.html
- dojo/templates/dojo/simple_metrics.html
- dojo/templates/dojo/view_engineer.html
- dojo/templatetags/display_tags.py
Now able to set the following `settings.py` attribute:
S_FINDING_SEVERITY_NAMING = True/False
True will display S0, S1, S2, ect in most places
False will display Critical, High, Medium, etc
For new installations the attribute defaults to False.
For existing installations the attribute needs to be added.
> Takes care of #159

- dojo/api.py
- dojo/urls.py
I was able to implement a importscan method to the API through tastypie. I probably did some things wrong because I'm not too familiar with tastypie. Tell me if there's anything I should change.
To test it you'll want to do a command like the following:
`curl -F "file=@report123.json" -H "Authorization: ApiKey admin:xxxxxxxxxxxxxxxxxxx" -F 'scan_type=Arachni Scan' -F 'tags=testing' -F 'active=true' -F 'scan_date=11/23/2016' -F 'eid=1' http://127.0.0.1:8000/api/v1/importscan/`
> Create ability to import scans from the tastypie API

- dojo/api.py
- dojo/urls.py
After the suggestion by @YSaxon I decided to add the re-import scan capability based largely off of the import scan endpoint I added earlier. You can test it with the following curl command:
```
curl -i -F "file=@report123.json" -H "Authorization: ApiKey admin:XXXXXXXXXXXXXXX" -F 'scan_type=Arachni Scan' -F 'tags=testing' -F 'verified=false' -F 'active=false' -F 'scan_date=2016/11/29' -F 'test=/api/v1/tests/1/' http://127.0.0.1:8000/api/v1/reimportscan/
```
> Add the reimport scan capabilities

- dojo/api.py
- dojo/test/views.py
I found a bug where when you went to re-import a scan it wouldn't add the endpoints or requests for the new findings.
> Fixing Re-Importing scan functionality

- dojo/forms.py
- dojo/management/commands/push_to_jira_update.py
- dojo/models.py
- dojo/utils.py
Added improved Jira error handling, including bubbling up asynch events to the alerts UI. Modified the models to only allow one jira issue per finding. Updated a couple lists to order alphabetically.
> Jira and order update

- dojo/api.py
Hi,
There is typo in MultipartResource class name which breaks the API.
It would be great if it could be fixed in the master version. :)
All the best,
Istvan
> api syntax fix

- docs/features.rst
- dojo/forms.py
- dojo/templates/dojo/import_scan_results.html
- dojo/tools/factory.py
- dojo/tools/nsp/parser.py
- dojo/tools/retirejs/parser.py
This adds the ability to import [Retire.js](http://bekk.github.io/retire.js/) JavaScript scans JSON outputs. 
Note: I didn't implement Node support for now as the output is too verbose - thousands of vulnerable paths etc. This is for JS only scans (ie. with the `--js` flag). I will implement Node support later on.
Sample command to run a JS vulnerability scan and output to a JSON file:
`retire --js --outputformat json --outputpath retirejs-json-output.json`
Then import into DefectDojo with the Retire.js Scan option.
For the Node Security Platform - you can output to JSON format using `nsp check --output json` and then pipe/save that to a file and import it to DefectDojo with the Node Security Platform Option.
> Add Retire.JS JavaScript and Node Security Platform Scanner Support

- dojo/test/views.py
- dojo/views.py
This PR fixes a bug with a missing qs reference in the history view as well as a bug that makes the search view throw an error due to a double qs reference.
> Fix queryset errors

- README.md
Dependency issues may exist with Ubuntu 14.04, however the install script works fine for 16.04.2
> Updated Readme to reflect Ubuntu 16.04.2 requirement

- docs/features.rst
- dojo/forms.py
- dojo/models.py
- dojo/templates/dojo/import_scan_results.html
- dojo/templates/dojo/view_finding.html
- dojo/tools/factory.py
- dojo/tools/nmap/__init__.py
- dojo/tools/nmap/parser.py
This PR addresses issue #218.
It adds a parser for nmap XML files, and creates informational findings with basic details about identified services from them.
It also extends the Endpoint model to include port and fqdn in order to improve filtering and reporting possibilities in the future.
> nmap XML file parsing support

- setup.bash
The nodejs and python-pip packages are available through epel-release. Also, libmysqlclient-dev package is not available on the repos and the nodejs installation script was installing a deprecated version.
This was tested on a CentOS 7 machine.
> Changed dependencies list for YUM installation

- dojo/engagement/urls.py
- dojo/engagement/views.py
- dojo/forms.py
- dojo/templates/base.html
- dojo/templates/dojo/calendar.html
- dojo/test/urls.py
- dojo/test/views.py
This PR addresses issue #237.
It adds functionality in the calendar to view calendars by tests or engagements, as well as filtering those by a set of users or unassigned engagements/tests.
> View and filter tests/engagements and users in calendar

- dojo/filters.py
- dojo/models.py
This PR addresses #330 and #336.
#330 - the default severity naming is now non-numerical if no system settings have been set.
#336 - users will now only see findings from products that they're authorised to view in the findings widget in the report builder.
> Minor bugfixes

- dojo/static/dojo/css/dojo.css
The PR wraps the text in pre-tags in the finding view which improves the legibility of findings.
> wrap pre-tags in the finding view

- dojo/reports/views.py
This patch fixes a bug that occurred when generating a report from the Engagements page when the client is using a different port in the host header than Defect Dojo is listening on locally (e.g., port forwarding/SSH tunneling, but it could happen in other scenarios). The backend task that attempts to generate the PDF report would try to connect to the external port and the connection would be refused. Now, we simply ignore the port by checking if there is a ":" in the host header and stripping it out if it does exist.
> Fix PDF Report Generation When Host Header Contains a Different External Port

- docs/dojo-production.rst
There were errors in the nginx configuration with a fresh clone from master. I've corrected these, added a note to double-check the location paths, and updated the name of the install script to reflect the new name (setup.bash vs install.bash).
> Fix errors/outdated information

- setup.bash
Found while using the new setup.bash to build a new docker image.  The final bower command failed due to permissions issues.  This fixes that bug.
> Fix a typo and a permissions issue with non-interactive bower install

- setup.bash
Adding a `cd ..` to the setup.bash script after running `bower install` and before running `collectstatic`
> adding "cd .." to fix collectstatic

- .travis.yml
- Dockerfile
Docker file now works for reporting as it starts both celery processes needed by Dojo. You can launch the docker like:
$ docker run -d -p 8000:8000 --name=dojo mtesauro/defect-dojo:1.1
And then go to http://localhost:8000 in a browser. Default login is admin / admin
Note that you have to have -p 127.0.0.1:8000:8000 to keep Travis CI happy.
> Updated/fixed Dockerfile and temporarily disabled Zap tests in Travis

- dojo/tasks.py
- setup.py
When creating a **custom** **report** that has a table of contents and its placed at the bottom of the report or anywhere but the top, the generated PDF will always generate the TOC on the first page at the top of the report, rather than respect the order specified in the frag & drop interface. 
This is a missing default with the [pdfkit](https://pypi.python.org/pypi/pdfkit) library where the `cover_first` attribute isn't passed. This PR add this flag, only when you add a cover page widget to your PDF report. Bumping the version of pdfkit to 0.6.1 where the `cover_first` attribute is recognized.
This doesn't seem to affect Product/Engagement reports as the report filter doesn't provide you with the option to provide a cover page.
> Fix Cover Page PDF Rendering Above TOC on Custom Reports

- dojo/__init__.py
Updating `dojo/__init__.py` to reflect the latest version (1.2.0), point to the current git repository location, and use https for links.
> Updating __init__.py metadata

- dojo/product/views.py
I've encountered this exception while adding (with a POST request) an ad-hoc finding to a product and pushing it to JIRA:
```
Exception Type: NameError at /product/2/ad_hoc_finding
Exception Value: global name 'add_issue_task' is not defined
```
I think it is only a missing import of "add_issue_task" from "dojo.tasks".
----
> added missing import of add_issue_task

- dojo/tools/openvas_csv/parser.py
If OpenVas found same vulnerability on different hosts, Dojo will ignore duplicates. Sample [csv](https://github.com/OWASP/django-DefectDojo/files/1555460/report.txt) in attached file.
> Add IP for hash in openvas parser.

- run_dojo.bash
Hi all,
this is just a minor (and very small) fix for "run_dojo.sh". The way the shell script is written implies to run 'python manage.py runserver' in the background. If it should stay in the forground, lines 19-21 would be obsolete (https://github.com/OWASP/django-DefectDojo/blob/master/run_dojo.bash#L19-L21).
Thanks in advance,
Tilmann H.
----
- [N/A] Your code is pep8 compliant (Dojo's code isn't currently pep8 compliant, but we're trying to correct that)
- [N/A] If this is a new feature and not a bug fix, you've included the proper docuemntation under the /docs folder
> run_dojo.sh: run 'python manage.py runserver' in background

- dojo/models.py
The null argument in the model definition threw a warning during migration application.
> Removed null argument for ManyToMany field creation

- .travis.yml
Add an exit statement triggered in case of failing tests, also letting travis know tests have failed.
Otherwise, tests may seem "green", even if problems have occurred during test execution.
> Let tests fail

- scripts/travis-integration-test.sh
This PR mainly adds a loop that gives the container used for integration tests a bit more time to come up. It waits at most 5 x 10secs for the container to spin up. 
The motivation for this PR were recent test failures on TravisCI, due to containers not being ready for a curl request yet.
> Avoid integration test failures due to timeouts

- requirements.txt
- setup.py
Added back SQLAlchemy requirement, since the Celery broker URL transport part explicitely requires it to be installed (the 'sqla' part of sqla+sqlite://... in the [CELERY_]BROKER_URL).
> Added back SQLAlchemy requirement

- components/package.json
As elaborated in issue #482, I think the raphael dependency is not required, since it comes with "justgage" already and only causes problems during installation, due to a ssh connection to github. 
``justgage/raphael-2.1.4.min.js`` is loaded in ``metrics.html``. No other inclusions of raphael scripts have been found. Therefore, it is assumed to be safe to remove this dependency.
> Remove yarn raphael dependency

- Dockerfile
Small `Dockerfile` change to allow devs to set env variables for an external db in the `docker build` command instead of modifying the `Dockerfile` using build args.
This makes it easier to use an external database, while keeping repos in sync with the upstream repository by avoiding merges.
The current build doesn't change because defaults are set (blank strings) so no errors get thrown if someone does not choose to use a build arg.
[dockerfile ARG reference](https://docs.docker.com/engine/reference/builder/#arg)
[docker build command build arg reference](https://docs.docker.com/engine/reference/commandline/build/#set-build-time-variables---build-arg)
> External db build args

- .flake8
- .travis.yml
This PR adds support for flake8 tests for code quality on Dev Branch. Whenever someone pushes code to dev branch, this code will run and only lint the files which have been changed in that PR request against master branch. 
So Instead of achieving pep8 in one go, we will only check PRs and little by little, we will achieve pep8 :) 
Also this PR ignores the following checks using .flake8 file. Once all the pep8 issues are taken care, we can work on enable those checks. 
E501: line too long (> 79 characters)
E127: Continuation line missing indentation or outdented
Scan complexity is set to 10 so it won't go deeper. 
- [] If this is a new feature and not a bug fix, you've included the proper documentation under the /docs folder
> Add flake8 for achieveing pep8, the devops way

- dojo/tools/nessus/parser.py
The nessus xml parser supposed the xml tag _risk_factor_ as severity classification. However, each ReportItem in the nessus xml has an attribute _severity_ which represents the "correct" tenable severity rating.
> replace risk_factor tag with severity attribute in nessus xml parser

- dojo/celery.py
- dojo/settings/settings.dist.py
Adapt settings to new settings names introduced by Celery 4.0 and documented at http://docs.celeryproject.org/en/latest/userguide/configuration.html
Note that Celery 4.1 has a known bug, ignoring the TIMEZONE setting described in https://github.com/celery/celery/issues/4717.
The change in ``dojo/celery.py`` may be breaking for users having copy&pasted their own settings file (having taken over the default settings). Manual adaption of their settings file is necessary. 
> Adapt Celery config

- dojo/tools/qualys/parser.py
Hello,
I tried to upload a Qualys scan and I got an error. The error was produced because the parser looks for the DNS tag and this tag is not always in the XML.
With this change if DNS is not in the XML, the endpoint is going to be created using the IP.
Also, I changed the way of creating the endpoint when the FQDN is available because currently it creates only one endpoint without name.
Regards,
> If the server does not have FQDN, create the endpoint with the IP

- dojo/tools/nessus/parser.py
If an item of the nessus xml file is empty (e.g. `<plugin_output></plugin_output>`), the parser will crash when try to access the text of the element.
> fix nessus xml parser if item is None or empty

- dojo/test/views.py
- dojo/utils.py
This pull request is to fix two bugs which I found while using DefectDojo. 
The first fix is for adding findings from template - findings added from templates cannot be pushed to JIRA successfully as the `cleaned_data` attribute of the `jform` in `add_temp_findings` is accessed before calling `jform.is_valid` when calling `add_issue_task.delay`, which would fail.
The second fix is for handling empty component names when updating JIRA issues. Unlike in the `add_issue` function, there isn't a check for empty component names in the `update_issue` function, which causes a JIRA error to occur when findings with no components are edited.
> bugfix for templated findings and empty component handling

- dojo/fixtures/test_type.json
- dojo/forms.py
- dojo/templates/dojo/import_scan_results.html
- dojo/tools/factory.py
- dojo/tools/npmaudit/parser.py
The Node Package Manager has an 'Audit' package which checks npm dependencies.
Commits add support for the '--json' output of 'npm audit'.
> Added support for JSON import of NPM Audit scans

- dojo/management/commands/run_scan.py
- dojo/scan/views.py
- dojo/templatetags/display_tags.py
`eval` is used for parsing Python literals in the model field `IPscan.services`.  As `eval`
executes the given string as Python code, this is dangerous and should
be avoided.  For literal parsing, `ast.literal_eval` can be used instead.
See:  https://docs.python.org/2/library/ast.html#ast.literal_eval
> Replace `eval` with `ast.literal_eval`

- dojo/api_v2/serializers.py
- dojo/unittests/test_rest_framework.py
This PR removes some redundant serializer fields in APIv2 as they match the default settings.
For `(Stub)Finding`, this PR sets the `reporter` field to the current user of the API so that the APIv2 behaves the same as DefectDojo's UI. (Do you actually want this? :) )
> APIv2: Clean up redundant serializer fields

- dojo/user/urls.py
The previous APIv2 key URL matches the `settings.LOGIN_EXEMPT_URLS` so that no
authentication has been enforced. Fortunately, an unauthorized access from an anonymous user results in an error page. I propose to change the APIv2 key URL to match the schema of the APIv1 key URL.
> APIv2: Change APIv2 key URL to fix missing authentication

- dojo/api_v2/serializers.py
Add `default`s and `allow_null=True` to serializer fields where the
corresponding model field has the same properties.
> APIv2:  Add `default`s and `allow_null=True` to some serializer fields

- dojo/api_v2/serializers.py
- dojo/unittests/test_rest_framework.py
This PR modifies the APIv2 so that the IDs of an object are used as identifier instead of the object's URL.
Additionally, this PR removes a lot of serializer field definitions as the generated default fields can be used now.
> APIv2:  Use IDs instead of URLs as identifier for objects

- dojo/models.py
- dojo/settings/settings.dist.py
Add unique constraints on the following fields:
- `Product.name`
- `Product_Type.name`
- `Tool_Type.name`
- `JIRA_Issue.jira_id`
- `Engagement.(name,target_start,product)`
- `Endpoint.(protocol,host,path,query,fragment,product)`
Now, all these objects can be uniquely identified by their names which is handy for synchronizing DefectDojo's state with external sources.
Some parts of the code already relied on the unique constraints, for example by using `Model.objects.get(name=<...>)`. (There are probably even more cases)
In turn, this requires `max_length <= 1024` for the corresponding char fields
and `innodb_large_prefix` must be ON which is the default for MySQL >= 5.7.7.
See also: https://stackoverflow.com/questions/45233362/django-says-that-mysql-does-not-allow-unique-charfields-to-have- …
> Add unique constraints for some model fields

- dojo/api_v2/serializers.py
- dojo/api_v2/views.py
- dojo/urls.py
This PR adds an APIv2 endpoint for `Product_Type`s.
This also resolves one of the inconsistencies mentioned in #682.
> APIv2: Add ProductType endpoint

- dojo/endpoint/views.py
Currently, adding an endpoint for a product fails with the following error:
```
NoReverseMatch at /endpoints/add
Reverse for 'view_endpoint' with no arguments not found. 1 pattern(s) tried: [u'endpoint/(?P<eid>\\d+)$']
```
Fix this by redirecting to the endpoint overview for the specific product.
> Fix endpoint add view

- dojo/api_v2/serializers.py
Two nitpicks for the import scan endpoint:
- Set today as default scan date
- Actually save the provided tags
> APIv2: Scan import fixes

- dojo/forms.py
- dojo/tasks.py
- dojo/utils.py
Disabled autocomplete for DateFields with datepicker class as the autocomplete dialog overlaps with the calendar if its large enough:
Also fixed the logs for update_issue_task, which was logging "add issue task" instead of "update issue task".
> Disabled autocomplete for date fields

- dojo/models.py
`self.title` is a unicode string and thereby `hash_string` is a unicode string as well. So, no need to `decode` it.
Fixes #706.
> Fix `Finding.get_hash_code` unicode handling

- dojo/tools/dependencycheck/parser.py
We had a `dependency-check-report.xml` where a reporter had a German umlaut in their name which broke the parser :)
The fix is to just replace all byte format strings with unicode format strings.
> Fix unicode handling in Dependency Check parser

- dojo/engagement/views.py
- dojo/finding/views.py
Currently, pushing to JIRA fails the following exception in the Celery
worker.  Fix this by re-adding the check whether a `JIRA_Issue` object
exists for the `Finding` or `Engagement`.
```
DoesNotExist('JIRA_Issue matching query does not exist.',)
File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 382, in trace_task
R = retval = fun(*args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 641, in __protected_call__
return self.run(*args, **kwargs)
File "/home/defectdojo/django-DefectDojo/dojo/tasks.py", line 235, in update_issue_task
update_issue(find, old_status, push_to_jira)
File "/home/defectdojo/django-DefectDojo/dojo/utils.py", line 1064, in update_issue
j_issue = …
```
> Fix JIRA integration

- dojo/static/dojo/css/highlight.css
- dojo/templates/dojo/view_finding.html
- dojo/templatetags/display_tags.py
- requirements.txt
Based on the issue #736 and a bug in the finding view by using the triple-tick, i've added the markdown extensions fenced_code and a default css theme (can be replaced with another theme from https://github.com/richleland/pygments-css/blob/master/). Now, if you use the triple-tick without any language addition, the view will rendering html code.
If you add a supported language like java or python, your source code will be displayed with syntax highlighting. E.g. java
or python
> source code highlighting

- dojo/search/views.py
Hey there,
currently, the simple search does not work with tags that contain dashes (f.e. CVE-xxxx-yyyy :wink: ).  
This is due to the regex pattern `[\w']+` which is used for splitting the search string into tags. This regex also splits at dashes.
However, `TaggedItem.objects.get_by_model` actually accepts a string and split it into tags by itself. This PR would remove the regex splitting altogether.
See also: https://django-tagging.readthedocs.io/en/develop/#id3
> Simple search does not work for tags with dashes

- dojo/templates/dojo/apply_finding_template.html
- dojo/templates/dojo/apply_finding_template_form_fields.html
This patch adds three buttons to the 'apply template to finding' view for applying the same option (Keep, Replace, Combine) to all fields.
I'm not that familiar with JavaScript, but it works for me :smile: 
Before:
After:
> Apply Template: Add buttons for applying the same option to all fields

- dojo/api_v2/serializers.py
I forget the case that someone manually marks a finding as duplicate. In that case, any duplicates of this duplicates should be skipped as well.
> APIv2: Also skip duplicates of duplicates on import

- dojo/api_v2/serializers.py
A finding needs to be mitigated to not show up under Metrics.
See also https://github.com/DefectDojo/django-DefectDojo/pull/748
> An automated closed finding should be marked as mitigated

- dojo/filters.py
Hey there,
this PR adds a new filter option for the findings view so that findings can be filtered by 'having an attached JIRA issue'.  This filter is quite useful for our workflows.  Looks like this:
> Add a `Has JIRA issue` filter option to the findings view

- dojo/api_v2/views.py
- dojo/fixtures/test_type.json
- dojo/forms.py
- dojo/templates/dojo/import_scan_results.html
- dojo/tools/brakeman/__init__.py
- dojo/tools/brakeman/parser.py
- dojo/tools/factory.py
- [Brakeman](https://github.com/presidentbeef/brakeman) is a well-known scanner for RoR projects
- We use DELETE API endpoints for automatic deletion of stale/closed engagements and findings, and bulk remove of tests, for instance, basing on their tags
> DELETE API endpoints for engagements, tests and findings and support for JSON import of Brakeman scans

- dojo/api_v2/serializers.py
- dojo/models.py
This allows to retrive the test type name for each test when requesting the test API.
> add test_type_name to test API

- dojo/models.py
71befb56 introduced a regression where we stopped computing hash codes
for new Findings.
Fixes #797.
> Fix hash code computation for Findings

- dojo/api_v2/serializers.py
- dojo/api_v2/views.py
- dojo/urls.py
You can make a get request on /api/v2/test_types to get the test types list.
> Add test types in api v2

- dojo/fixtures/test_type.json
- dojo/forms.py
- dojo/templates/dojo/import_scan_results.html
- dojo/tools/factory.py
- dojo/tools/safety/parser.py
Adds support for Saftey scanner released by pyup.io detailed [here](https://github.com/pyupio/safety). I wasn't able to find the mentioned /docs folder so mentioned documentation has not been included. PR [#7](https://github.com/DefectDojo/sample-scan-files/pull/7) has also been submitted to [sample-scan-files](https://github.com/DefectDojo/sample-scan-files) with sample scan data.
Safety does not include severity levels for each finding, so all findings are being set to Info as is seen with other scanners. CVE data is not included in scan json data, so the Safety DB JSON is obtained to be included.
> Adding support for Safety scans

- dojo/models.py
See https://docs.djangoproject.com/en/2.1/ref/databases/#notes-on-specific-fields
Fixed error (mysql):
==> logs/dojo.log <==
File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/runserver.py", line 124, in inner_run
self.check(display_num_errors=True)
File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 405, in check
raise SystemCheckError(msg)
django.core.management.base.SystemCheckError: SystemCheckError: System check identified some issues:
ERRORS:
dojo.Product_Type.name: (mysql.E001) MySQL does not allow unique CharFields to have a max_length > 255.
> Fix max_length on primary key Product.name

- dojo/templates/dojo/findings_list.html
- dojo/tools/nessus/parser.py
- Fix bulk status change in findings(verified, false positive and out of scope): there was a problem with several same id attributes on the same page.  
- Fix Nessus report parsing: if Nessus plugin output contains HTML, the finding page markup is broken. Plugin output is now wrapped in a code block.
> Fix bulk edit in findings and nessus report parsing

- dojo/models.py
- dojo/tools/checkmarx/parser.py
fix issue #875.
checkmarx sample to reproduce this issue.
[checkmarx_sample_to_reproduce_#875.zip](https://github.com/DefectDojo/django-DefectDojo/files/2931565/checkmarx_sample_to_reproduce_.875.zip)
> fix issue #875

- dojo/api.py
- dojo/api_v2/serializers.py
- dojo/api_v2/views.py
- dojo/tools/factory.py
- dojo/urls.py
This feature allows to create a test with an specific test_type decoupling it from value of scan_type when importing findings from API
Additional features added: Extended API v1 and v2 to allow:
- For v1:
- create and update Product_Type
- create and update Development_Environment
- create and update Test_Type
- For v2:
- create and update Development_Environment
- For both versions:
- Be able to override the test_type created independently of scan_type selected
> New feature request: Allow decoupling test_type and scan_type method when importing from API

- setup/requirements.txt
Update celery because of a bug in 4.2.1 -  https://github.com/celery/celery/issues/4849
On behalf of DB Systel GmbH.
> update celery because of a bug in 4.2.1

- .travis.yml
- KUBERNETES.md
- helm/defectdojo/templates/celery-deployment.yaml
- helm/defectdojo/templates/django-deployment.yaml
- helm/defectdojo/templates/initializer-job.yaml
- helm/defectdojo/values.yaml
- travis/before-install.sh
- travis/before-script.sh
- travis/script.sh
Build all Docker images via Travis, create a Minikube, deploy Helm charts there, test them, undeploy.
> Travis stuff added.

- helm/defectdojo/templates/django-ingress.yaml
- helm/defectdojo/values.yaml
- Added the possibility to define more annotations for django ingress manifest 
- Added the possibility to set an secretName for the ingress tls part. 
Background is that it is possible to set a default tls secret in the nginx-ingress-controller: `--default-ssl-certificate` which catches all and could make sense if you have multiple ingress controllers with specific wildcard certificates. More information: https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/cli-arguments.md
> annotations and secretName

- ISSUE_TEMPLATE.md
Since deploying to Kubernetes is now in 'master', and setup.bash has
been renamed legacy-setup.bash, add an option to declare issues
related to Kubernetes deployments.
Keeping the setup.bash option at the moment, for transition from legacy.
Signed-off-by: Piotr PAWLICKI <piotrek@seovya.net>
> Add Kubernetes option in ISSUE_TEMPLATE.md

- dojo/endpoint/views.py
- dojo/engagement/views.py
- dojo/jira_link/views.py
- dojo/product/views.py
- dojo/rules/views.py
- dojo/test/views.py
- dojo/user/views.py
This avoids computing what is needed for the deletion confirmation view (GET) for the deletion itself (POST) too.
> Fix 964, first issue

- dojo/models.py
Uploading a burp suite report that contained certain characters ended up with throwing errors due to the `str(self.description)` which would end up with a partial report upload .
For example the "Interesting input handling: Magic value: null" issue generated by the Burp Pro Plugin Backslash Powered Scanner ended up not uploading due to the fact that it contained a multi-line table .
> Fixes an issue with certain reports

- dojo/fixtures/test_type.json
- dojo/forms.py
- dojo/templates/dojo/import_scan_results.html
- dojo/tools/dawnscanner/__init__.py
- dojo/tools/dawnscanner/parser.py
- dojo/tools/factory.py
I followed [these instructions](https://github.com/DefectDojo/django-DefectDojo/wiki/Creating-a-new-importer-(scanner)) to add **dawnscanner** JSON report importer (https://github.com/thesp0nge/dawnscanner). 
**dawnscanner** is another security scanner for ruby web applications, including _Rails_, _Sinatra_ and _Padrino_.
**dawnscanner** supports JSON output (with -j option)
> Added DawnScanner json report importer

- dojo/api_v2/serializers.py
- dojo/utils.py
Regression was caused by e4cbdfa#diff-63c97e945dc0af3507d89798a8841819
I also fixed a typo and renamed a method to make its purpose more clear.
This fixes #983 and is an iteration of #1000 
I fixed all flake8 warnings shown by visual studio code.
> fix deduplication_on_engagement that was broken due to optimistic linting

- dojo/api_v2/serializers.py
- dojo/utils.py
During #983 and #1002 I realized that deduplication_on_engagement is not yet support with close_old_findings during imports. I think this is needed because otherwise the import could close findings in other engagements and the whole idea of deduplication_on_engagement (I think) is to keep all "duplicate checks" inside the engagement instead of the product.
> make deduplication_on_engagement work with close_old_findings

- dojo/models.py
- dojo/tools/snyk/parser.py
Fixes an issue where reports containing certain characters were not being properly decoded by `str(self.description)`
Waiting for @madchap to also confirm that snyk reports are coming in nicely with these changes .
> Fixes UTF-8 issues when computing Hashes

- dojo/fixtures/test_type.json
- dojo/forms.py
- dojo/templates/dojo/import_scan_results.html
- dojo/tools/bundler_audit/__init__.py
- dojo/tools/bundler_audit/parser.py
- dojo/tools/factory.py
> bundler-audit is a patch-level verification for Bundler
Tool URL: https://github.com/rubysec/bundler-audit
**bundler-audit** tool outputs results in standard output, formatted as multi-line with headers like the GEM name and version with vulnerabilities, CVE, description of the issue, mitigation and URL with the Advisory reference.
Tool can be executed with ```bundle-audit check``` on the ruby project folder where the ```Gemfile.lock``` file is
Sample scan file in this PR: https://github.com/DefectDojo/sample-scan-files/pull/14
This parser will import the findings
> Bundle-audit tool output importer

- dojo/tools/burp/parser.py
Some burp issues don't have a request/response pair , for example OS Command Injection with a timeout will only have a request and not a response .
> Fix burp issues that don't have a req/resp pair

- components/package.json
- dojo/static/dojo/css/dojo.css
- dojo/static/dojo/js/index.js
- dojo/templates/base.html
This PR makes the side menu accessible to assistive technologies such as screenreaders for visually impaired users.
The metismenu plugin has been upgraded to the latest version (v3.0.4), too.
> Made side menu accessible to assistive technologies

- dojo/tools/burp/parser.py
This is an enhancement in order to handle findings that contain Burp collaborator interactions which have additional request/response pairs and additional information that was normally ignored or breaking the importing of the report .
The collaborator interaction data is being aggregated and then added to the description of the finding as well as the additional request/response pairs from the server->collaborator . Also attached the applicable report files .
[TestBurpScan4.xml.txt](https://github.com/DefectDojo/django-DefectDojo/files/3056037/TestBurpScan4.xml.txt)
[TestBurpScan5.xml.txt](https://github.com/DefectDojo/django-DefectDojo/files/3056039/TestBurpScan5.xml.txt)
When submitting a pull request, please make sure you have …
> Handle Burp Collaborator issues

- docker/entrypoint-uwsgi.sh
- nginx/nginx.conf
Troubleshoots 'upstream timed out' on POST import_scan_results when importing big checkmarx reports (60MB; 3k findings)
```
172.18.0.1 - - [08/Apr/2019:16:08:49 +0000] "GET /alerts/count HTTP/1.1" 200 12 "http://localhost:8080/engagement/1/import_scan_results" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36" "-"
2019/04/08 16:09:51 [error] 6#6: *1 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.18.0.1, server: , request: "POST /engagement/1/import_scan_results HTTP/1.1", upstream: "uwsgi://172.18.0.4:3031", host: "localhost:8080", referrer: "http://localhost:8080/engagement/1/import_scan_results"
```
this configuration is for 30mn (10mn wasn't enough)
> tune uwsgi read timeout

- dojo/engagement/views.py
Currently when deleting a cicd engagement, DD returns to the engagement overview screen instead of the *cicd* engagement overview screen.
I have used the same if statement found in 5 other places to fix this small nuisance
> cicd engagments: return to cicd overview after deleting a cicd engagement

- docker/entrypoint-uwsgi.sh
After more testing, this timeout is not required: the one set in the nginx.conf alone seems enough right now. 
Anyway this parameter was not active as I've lost a backslash when merging
> remove http timeout from the entrypoint as it's not required

- dojo/templatetags/display_tags.py
- requirements.txt
Fix markdown_render function that executing markdown javascript payload.
eg : `[xss](javascript:window.onerror=alert;throw%20document.cookie)`
> Fix markdown_render function

- dojo/api_v2/serializers.py
deduplication: fix bug in skip_duplicates for deduplication_on_engagement.
with skip_duplicates and duplication_on_engagement it was looking for duplicates in the engagement AND in the product, this commit fixes that. it was introduced recently in #1007
> deduplication: fix bug in skip_duplicates for deduplication_on_engagement

- dojo/utils.py
fix #1034 
I think there is no need for `if` statement on `severity_values`. because it returns `none` type when there are no active findings.
> fix product grading

- dojo/templatetags/display_tags.py
The table of tests on an engagement page shows a summary of findings in the header row (total, critical, high, medium, low, ...). If there no verified, active findings, the summary is hidden.
We think it would be better to always show it.
> Always show summary of findings in table header

- dojo/engagement/views.py
On the view engagement page currently the list of tests is ordered only by name (test_type__name).
Apart from that it relies on the natural ordering of the tests.
I think it would be best to ensure the newest tests are on type. Especially in a CI/CD scenario you can have lots of tests and you don't want to be scrolling or pagina too much.
Let me know what you think. I would even go further and only order by '-updated' and leave out the ordering by test name.
> View engagement: order tests by type and updated

- dojo/api_v2/serializers.py
Add 'stale' tag for findings that are closed because they no longer appear in scan results/imports
This will make it more clear which findings (in a list view) are closed because they are 'stale'.
> Add 'stale' tag for findings that are closed because they no longer appear in scan results/imports

- dojo/templates/dojo/view_test.html
The merge button is never shown because the `view_test.html` page is looking for a variable called `tab_product` which isn't used anywhere in the DD code base as far as I can see.
In other places the variable referenced is `product_tab`, so this PR uses that same variable now also for `view_test.html` and now the merge button is visible in expected scenario's.
> fix merge button visibility in view_test

- docker/entrypoint-unit-tests.sh
This PR is related to #1098 and adds the test as discussed with @aaronweaver.
Testing explicitly if migrations apply cleanly is not required, as the Django test runner applies them automatically before running the tests and hence would reveal problems itself.
> Test verifying there are no unmigrated model changes

- dojo/tools/checkmarx/parser.py
- dojo/unittests/scans/checkmarx/utf8_various_non_ascii_char.xml
We have done a couple of fixes already on this but we haven't fixed it for filenames. 
When non-ascii utf-8 characters are found in source code filenames, importing the report makes defectdojo fail with errors like: 
`'ascii' codec can't encode character u'\xe9' in position 24: ordinal not in range(128)`
I've also enriched the checkmarx parser unit test with this case.
> fix utf-8 non-ascii char in source code filenames for checkmarx parser

- dojo/forms.py
- dojo/templates/dojo/import_scan_results.html
- dojo/tools/factory.py
- dojo/tools/twistlock/parser.py
- dojo/unittests/scans/twistlock/findings_include_packages.json
- dojo/unittests/scans/twistlock/many_vulns.json
- dojo/unittests/scans/twistlock/one_vuln.json
- dojo/unittests/test_twistlock_parser.py
Seems to be working for me for a couple big files, with diffferent twistcli options.
The `unknown` status for a CVE could also be used here when in the model.
Shamelessly C-V from the snyk parser.
Thanks for your review.
- [ WILL DO] If this is a new feature and not a bug fix, you've included the proper documentation in the ReadTheDocs documentation folder. https://github.com/DefectDojo/Documentation/tree/master/docs or provide feature documentation in the PR.
> twistlock parser

- dojo/finding/views.py
Hi,
I tried to create a PR compatible to your `CONTBUTION.md`, but I'm not a 100% sure if I did everything needed. Please give me a hint, if I'm missing something. I'm happy to update my code where it's needed.
You can see the differences easier with `git diff -w`
---
This commit fixes an issue during finding review. As soon as you have
Jira configured, but no Jira ticket appended, an exception was thrown
because the system wanted to close the Jira ticket at the same time.
The Jira ticket is now no longer required - you can close the finding
without a related Jira ticket.
Closes #1081
> Fix: Review Finding Without Jira Ticket But With Jira Config

- dojo/tools/twistlock/parser.py
Got bitten by it today. This fixes it.
> Twistlock parser fix for riskFactors + cve field

- dojo/fixtures/test_type.json
Realized that test_type were missing the twistlock and blackduck parsers. Amended fixtures here, including @dr3dd589's Kiuwan parser.
> Amending fixtures for test_type, adding twistlock, blackduck and kiuwan

- tests/Product_type_unit_test.py
fix #1131 
Implemented test for the following:-
- Add product type
- Edit product type
- Delete product type
> Product type Unit test

- dojo/tools/blackduck/parser.py
Forgot the cve field when creating the parser. This fixes it.
> Add cve field to Blackduck parser

- tests/Engagement_unit_test.py
- tests/product_selenium_unittest.py
fix #1133 
implemented the following tests:
> Engagement unit test

- dojo/utils.py
Fixes #1148 
Some email functions seem to be dead code, may need some cleanup.
This is a barebone fix to get emails working (tested review requests, products), at least when sending to gmail and other email providers that care about From headers. All seems to transit through this function.
To be done through other PRs likely, but related:
* Minimal email documentation. Currently none.
* Remove dead code related to email in utils.py.
* Add templates for specific notifications instead of overusing "other.tpl"
My change seems to be flake8 compliant, but the rest of the file is not in some parts. I can eventually take a look at that.
----------
> Fixes #1148: email not being received because of missing From header

- dojo/api.py
- dojo/settings/settings.dist.py
- dojo/tasks.py
- dojo/utils.py
Fixes https://github.com/DefectDojo/django-DefectDojo/issues/1176 for APIv1 and gui import. Add debug logs
Regarding the deduplication: 
- fix comparison between  find.line and new_finding.line which was always false due to different types ( find.line is a long while new_finding.line is a string)
- Remove date from the comparison: when importing through APIv1 date is given by scan-date field. When importing through the GUI, date is given by "Scan Completion Date". Findings may be duplicate no matter which scan dates are given
Regarding the logs: 
- I have created a specific logger to be able to tune it independently of the utils.py logger. When there are many findings, we'll have logs for each finding in the database if the logger is configured in debug. For this reason, by default the …
> Fix 1176 checkmarx deduplication

- helm/defectdojo/values.yaml
The logLevel is used only in the ConfigMap which is shared by the worker and beat.
Also the resource requests are missing a subkey.
With these changes the helm chart should be fully functioning.
> Fix(helm): logLevel and resource.requests are set on wrong level

- dojo/filters.py
Use QuerySet for ```severity``` choices. This approach significantly decreases filtering time. 
> Optimised filtering

- dojo/templates/dojo/simple_search.html
This is my enhancement for #1155. Added columns for engagement and associated test whenever a finding is pulled up in the simple search. The engagement column lists the engagement that the finding is associated with. The associated test column displays the test that the finding is associated with. If the associated test is not titled, the associated scan is displayed instead.
> Enhancement #1155

- dojo/models.py
- dojo/templates/dojo/view_finding.html
> fix static and dynamic type finding

- dojo/fixtures/test_type.json
- dojo/forms.py
- dojo/templates/dojo/import_scan_results.html
- dojo/tools/factory.py
- dojo/tools/whitesource/parser.py
- dojo/unittests/scans/whitesource_sample/okhttp_many_vuln.json
- dojo/unittests/scans/whitesource_sample/okhttp_no_vuln.json
- dojo/unittests/scans/whitesource_sample/okhttp_one_vuln.json
- dojo/unittests/test_whitesource_parser.py
> Whitesource Importer

- dojo/fixtures/test_type.json
- dojo/forms.py
- dojo/tools/contrast/parser.py
> fix #1257 and unicode error in Contrast importer

- dojo/templates/base.html
- dojo/templates/dojo/delete_alerts.html
- dojo/user/urls.py
- dojo/user/views.py
This is my enhancement for #1211. Added a "Clear all alerts" tab below the "See all alerts" option in the Alerts drop-down menu. Clicking on clear all alerts prompts the user with a page stating "The following alerts will be deleted" followed by the titles of the alerts, and a delete alert button. Clicking on delete alerts will purge all alerts.
> Enhancement for #1211

- dojo/finding/views.py
- dojo/templates/dojo/view_finding.html
This is my enhancement for #1238. Added Previous and Next buttons on view finding. Clicking next takes the user to the finding after the one it's currently looking at, and previous takes the user to the finding after. If the finding that the user is viewing if the first finding, the previous button will not display. Similar case with the next button; Next button is not displayed when the user is looking at the last finding.
> Enhancement #1238

- dojo/api_v2/serializers.py
> Test type shouldn't be limited to valid scan types

- dojo/templates/dojo/login.html
Social Authentication via Google or OKTA is now disabled by default. Users will need to navigate to the documentation for guidance with setup and enabling.
> Disable social-auth by default

- dojo/templates/dojo/ad_hoc_findings.html
- dojo/templates/dojo/add_findings.html
- dojo/templates/dojo/add_template.html
- dojo/templates/dojo/apply_finding_template.html
- dojo/templates/dojo/edit_findings.html
- dojo/templates/dojo/edit_presets.html
- dojo/templates/dojo/edit_product.html
- dojo/templates/dojo/new_eng.html
- dojo/templates/dojo/new_params.html
- dojo/templates/dojo/new_product.html
- dojo/templates/dojo/promote_to_finding.html
Referencing issue #1290 
Adds spellcheck to text boxes that have a buttons for underline, bold, and so on.
> Add spell check to textarea boxes

- components/package.json
- package.json
Since version 3.10.0, there are breaking changes in the fullcalendar
yarn package version, which breaks the calendar functionality on Dojo.
Jquery support has been removed on version 4.0 as seen on link:
https://fullcalendar.io/blog/2018/04/alpha-release-jquery-removal
Jquery version mismatches happen if we use version 3.10.0
Thus, hardcoding to version 3.9.0
> Harcoding fullcalendar pkg version. Fixes #1011

- requirements.txt
Using  git+git as the protocol for connectivity is not good corporate on 
environments, as this might not respect the proxy settings configured
on the server/client performing the install or the firewall might block port
9418 used by git protocol.
Using git+https will respect proxy settings and allow likely allows
the build to complete as it will pull the dependency from GitHub using HTTPS
> Use git+https instead of git+git for GitHub on requirements.txt . Fixes #1297

- dojo/templates/dojo/view_product_details.html
After the "Benchmark Progress" feature implementation, the Metadata and
Contacts area is not rendering on the right side of the screen as they
used to, and now render below the benchmark progress.
This commit fixes the mismatched div entries and size of the benchmark
the panel so the page can properly render
> Product details rendering fix. Fixes #1305

- dojo/tools/twistlock/parser.py
Fixes #1302 
Added minor cosmetic changes as well. Tested locally.
> Merging against `dev` which is now the python3 one, if I am not mistaken.
> Use severity field instead of cvss score to classify

- dojo/api.py
This is a fix for the API ImportScan. Added True for the active and verified of the import parser factory calls. The two checks correspond to whether or not the user trusts the 'Active' and 'Verified' columns of a generic findings import file.
> API ImportScan Fix

- dojo/api_v2/serializers.py
This merge request will fix the following Warning when mitigation performed by an api_v2 request:
> fix a naive datetime for Finding.mitigated

- dojo/api_v2/serializers.py
- dojo/test/views.py
Use the scan date in findings during a reupload instead of the date from the test. In a finding you want to know when the finding was found and not when the test started.
(on behalf of DB Systel GmbH)
> Fix scan date when reuploading scans

- .travis.yml
In Travis CI, __sudo: required__ no longer is.
> Travis CI: The sudo: tag is now deprecated in Travis

- Dockerfile.django
- Dockerfile.nginx
The python3 docker image was updated to debian buster (https://github.com/docker-library/python/commit/2a11f610a56ff3c0f0157790dde940894fad7a1a). This breaks the current docker build, so we have to update/rename some packages.
---
> Fix DefectDojo build caused by Python3 docker update

- dojo/tools/checkmarx/parser.py
Hello,
Some import of checkmarx scan fail because of bad char encoding.
See : https://github.com/DefectDojo/django-DefectDojo/issues/1369
> checkmarx import failed because of bad char 

- dojo/engagement/views.py
- dojo/finding/views.py
- dojo/object/parser.py
- dojo/product/views.py
- dojo/templates/dojo/alerts.html
- dojo/templates/dojo/migrate_alerts.html
- dojo/test/views.py
- dojo/user/urls.py
- dojo/user/views.py
- tests/Finding_unit_test.py
- tests/Import_scanner_unit_test.py
Modifications motivated by issue #1314 
If data is imported from another instance, the domains found in the url field of an alert will most likely not match. After importing, run the alert migration process found at /migrate_alerts to strip the domain from each alert. They will be compatible with any instance after that. In addition to the conversion, all alerts made from here forward will have the relative path of the object referenced in the url field.
>  Modify alert url to be compatible with any host/domain

- dojo/db_migrations/0001_initial.py
- dojo/db_migrations/0006_django2_upgrade.py
Related to #1287
During the python3 migration 'product_grade_b'  was accidentally renamed to 'product_grade_'. This PR reverts the renaming.
This PR may break current installation which are based on the dev branch (python3) but makes the current branch compatible with installations which are based on the master branch. 
---
> Fix python3 migration issue #1287

- dojo/forms.py
Disable the 'push to jira' checkbox, as to prevent accidental override in jira.
For example, a user enters the relationship through the `jira_finding_mappings` endpoint (v2). This offers a little safeguard without moving much of the code, especially if several users review and are not necessarily aware of the inner workings (most of them).
Ideally, a little "?" should be put next to the checkbox to warn about the potential risk.
@aaronweaver @valentijnscholten could this be something intermediate while waiting for a proper implementation of #1040 ?
**Note: DefectDojo is now on Python3 and Django 2.2. Please submit your pull requests to the 'python3_dev' branch as the 'dev' branch is only for bug fixes. Any PR's submitted to the 'dev' branch should also be converted to Python3 and submited …
> Disable the 'push to jira' checkbox prevent accidental overwrite

- dojo/filters.py
When jira is enabled, accessing Findings view results in a 500 error due to finding filter uses a deprecated argument (name) instead new one (field_name). This PR fix this issue.
> Fix deprecated filter argument

- dojo/templates/dojo/asciidoc_report.html
- dojo/templates/dojo/custom_asciidoc_report_endpoints.html
- dojo/templates/dojo/custom_asciidoc_report_findings.html
- dojo/templates/dojo/custom_pdf_report_endpoint_list.html
- dojo/templates/dojo/custom_pdf_report_finding_list.html
- dojo/templates/dojo/endpoint_pdf_report.html
- dojo/templates/dojo/engagement_pdf_report.html
- dojo/templates/dojo/finding_pdf_report.html
- dojo/templates/dojo/product_endpoint_pdf_report.html
- dojo/templates/dojo/product_pdf_report.html
- dojo/templates/dojo/product_type_pdf_report.html
- dojo/templates/dojo/report_findings.html
- dojo/templates/dojo/request_report.html
- dojo/templates/dojo/test_pdf_report.html
> Include tags in reports

- dojo/api.py
- dojo/api_v2/serializers.py
- dojo/db_migrations/0009_endpoint_remediation.py
- dojo/models.py
- dojo/signals.py
- dojo/tasks.py
- dojo/test/views.py
- dojo/unittests/test_apiv2_scan_import_options.py
- dojo/utils.py
- tests/dedupe_scans/dedupe_cross_1.csv
- tests/dedupe_scans/dedupe_endpoint_1.xml
- tests/dedupe_scans/dedupe_endpoint_2.xml
- tests/dedupe_unit_test.py
Deduplication has been heavily tested and tweaked to fit the the description found in the documentation. Major difference here is now new findings will default to being of type dynamic. This change was motivated as a tweak to deduplication to standardize how a finding will be declared as a duplicate. Too many factors were left as a responsibility of a scan parser.
A new finding will default to dynamic. If mentioned finding has a line number and path, but no endpoints, it will be defined as static instead. If at any time a finding has a line number, …
> Refractor deduplication and implement with django signals

- CONTRIBUTING.md
- Dockerfile.django
- Dockerfile.nginx
- PULL_REQUEST_TEMPLATE.md
- README.md
- docker-compose.yml
We have discussed it a little bit in slack: this PR pins the external docker image versions in order to have a reproducible build and avoid issues like the one we had recently on mysql change within the python image.
I have also pinned the digests because identifiers like python:3.7.4-slim-buster are not immutable, meaning that the image can change and keep the same identifier. 
After this we'll need to update versions from time to time. 
I have found a project that automatically creates pull request when a new image is released we could try that? It's free for open source projects:
https://renovatebot.com/blog/docker-mutable-tags
https://github.com/marketplace/renovate/plan/MDIyOk1hcmtldHBsYWNlTGlzdGluZ1BsYW45NTk=#pricing-and-setup
NB: i have found that image id is different from digest. …
> Pin versions of external docker images for more stability

- dojo/tools/checkmarx/parser.py
- dojo/unittests/test_apiv2_scan_import_options.py
- dojo/unittests/test_checkmarx_parser.py
Fixes https://github.com/DefectDojo/django-DefectDojo/issues/1431
- remove utf-8 conversions: they are not needed in python3 as strings are utf-8 by default and those "encode" calls return bytes instead of string (thus appearing as b'mystring' in the GUI)
- improve unit test : add content check, not only counts
> fix #1431: checkmarx imports bytes instead of strings and add unit tests

- Dockerfile.busybox
- Dockerfile.django
- docker-compose.override.unit_tests.yml
The fix includes: 
- add docker/entrypoint-unit-tests-devDocker.sh entrypoint file in Dockerfile.django (merge error from python2 branch I guess)
- replace hello-world image by busybox with fixed version
- for some reason the hello-world image wasn't working anymore with [] entrypoint. Maybe due to a change in the docker image itself. while looking for a solution i've found this busybox image which is also much smaller.
- I have fixed the image version for more stability
The last issue remaining is those multiple occurences of errors 
```
celeryworker_1  | [2019-07-29 08:29:50,725: ERROR/MainProcess] Task dojo.tasks.async_dupe_delete[0ac89d26-4462-4440-81e1-ce0b6aac82b7] raised unexpected: DoesNotExist('System_Settings matching query does not exist.')
```
although it's not preventing the …
> Fix #1428: unit-tests not working in docker env

- dojo/tools/burp/parser.py
BURP report format in XML is creating tags that may or may not containing a value, even though an XML tag exists.
With this change, we maintain backward compatibility, but also perform a check to see if a VALUE exists after we validated a TAG exists, thus addressing hard to re-produce issues whenever we have empty values for empty remediation/issueBackground tags.
There is also a PR for an example burp report found at: https://github.com/DefectDojo/sample-scan-files/pull/31
> Ensure BURP report tags are not empty. Fix #1224

- dojo/finding/views.py
- dojo/object/parser.py
- dojo/tools/anchore_engine/parser.py
- dojo/tools/arachni/parser.py
- dojo/tools/bandit/parser.py
- dojo/tools/brakeman/parser.py
- dojo/tools/clair/parser.py
- dojo/tools/clair_klar/parser.py
- dojo/tools/dawnscanner/parser.py
- dojo/tools/gosec/parser.py
- dojo/tools/jfrogxray/parser.py
- dojo/tools/mobsf/parser.py
- dojo/tools/mozilla_observatory/parser.py
- dojo/tools/netsparker/parser.py
- dojo/tools/npm_audit/parser.py
- dojo/tools/nsp/parser.py
- dojo/tools/php_security_audit_v2/parser.py
- dojo/tools/php_symfony_security_check/parser.py
- dojo/tools/retirejs/parser.py
- dojo/tools/safety/parser.py
- dojo/tools/snyk/parser.py
- dojo/tools/sonatype/parser.py
- dojo/tools/ssl_labs/parser.py
- dojo/tools/twistlock/parser.py
- dojo/tools/whitesource/parser.py
- dojo/tools/wpscan/parser.py
At some point, importing scanners based on the JSON format was broken. When parsing the JSON file, contents would be read in as bytes instead of strings, and trigger an exception. With these changes, scans are read and decoded to strings, and then parsed.
> Fix json based import scanners

- Dockerfile.nginx
Many third party software uses dockercompose declarations to discover things like which port may map to publish the application.
> Declare exposed port in nginx docker configuration

- dojo/api_v2/permissions.py
- dojo/api_v2/serializers.py
- dojo/api_v2/views.py
- dojo/static/dojo/js/index.js
- dojo/templates/dojo/asciidoc_report.html
After Trying to add Ability to generate report through Api as requested in Issue #1352 .  I discovered that this would be a very huge enhancement capability for defect-Dojo if reports can be generated in JSON format straight from Api without the GUI. So I took my time to get this done as best as I can.
> Added Api v2 Feature For Report Generation

- DOCKER.md
- dojo/forms.py
- dojo/templates/dojo/import_scan_results.html
- dojo/tools/sonarqube/parser.py
- dojo/unittests/scans/sonarqube/sonar-6-findings.html
- dojo/unittests/scans/sonarqube/sonar-no-finding.html
- dojo/unittests/scans/sonarqube/sonar-rule-undefined.html
- dojo/unittests/scans/sonarqube/sonar-single-finding.html
- dojo/unittests/scans/sonarqube/sonar-table-in-table.html
- dojo/unittests/test_sonarqube_parser.py
List of changes: 
- Reactivate sonarQube parser. (more info: see https://github.com/DefectDojo/django-DefectDojo/issues/810)
- Fix it for python3
- add file_path and line_number
- fix an issue with the logic for finding the vulnerabilities and the rules
- before it was finding all the "tbody" and expect to find data always at the same nth tbody. 
- However sometimes there are more "tbody" in the rules description, and when there are no vulnerabilities found, one of the tbody disappears so it didn't work. Fix by using xpath instead to locate the list of vuln and the rules. 
- force the findings as static findings (they were dynamic before)
- add unit tests
Beware that you'll need the last version of the sonar html export for this to work. it's here …
> Reactivate sonar

- dojo/tools/retirejs/parser.py
Improve Retire.JS parser to work with other versions. Also fix references from being displayed as bytes instead of strings.
> Improve Retire.JS parser

- dojo/tools/trufflehog/parser.py
- tests/dedupe_unit_test.py
Trufflehog fix motivated from #1482 
Dedupe path change is for obvious reasons.
> Fix Trufflehog and change dedupe test file path

- dojo/finding/views.py
- dojo/templates/dojo/findings_list.html
- dojo/templates/dojo/view_test.html
- dojo/test/views.py
Motivated by #1496 
Findings no longer display Jira status if the associated product is not configured with Jira. If a user is looking at all findings independent from products, the Jira statuses will appear simply if Jira is enabled.
> Remove JIRA status if product is not configured

- dojo/api_v2/serializers.py
- dojo/models.py
In response to #1478, deduplication now allows line numbers specified as 'None' to be valid, and therefore a candidate for deduplication. This is NOT a final solution, nor as a distraction or mitigation of the bigger problem. This is purely meant as a temporary method for users that are accustomed to the previous implementation.
> Return dedupe to a "working" state

- dojo/product/views.py
Based on previous discussions where it was decided that open findings didn't need to be marked as verified, this is a quick fix to display metrics in the Product's tab.
Fixes #1518
> Adjust finding status to display product metrics

- Dockerfile.django
- docker-compose.override.dev.yml
In docker dev mode, the volumes for the initializer and celerybeat containers are missing. 
- For the initializer it's important for db_migrations: without this volumes, we still needed to rebuild the django image after each change, even in dev mode (because the db_migrations are done in the initializer container, not uwsgi which already has this volume)
- add also celerybeat for completeness
'+ fixing a typo in Dockerfile.django
> add missing volumes in docker dev mode

- dojo/filters.py
If the cwe is None (which is the default), displaying the accepted finding will throw a type error. This is a relict form the python 3 migration: https://docs.python.org/3/whatsnew/3.0.html#ordering-comparisons
on behalf of DB Systel GmbH
> Fix bug when displaying accepted findings

- dojo/templates/dojo/asciidoc_report.html
- dojo/templates/dojo/endpoint_pdf_report.html
- dojo/templates/dojo/engagement_pdf_report.html
- dojo/templates/dojo/finding_pdf_report.html
- dojo/templates/dojo/product_endpoint_pdf_report.html
- dojo/templates/dojo/product_pdf_report.html
- dojo/templates/dojo/product_type_pdf_report.html
- dojo/templates/dojo/snippets/comments.html
- dojo/templates/dojo/test_pdf_report.html
- dojo/templatetags/get_note_status.py
Changes motivated by #1554, #1555, and #1546
Generating a Test PDF report no longer throws a 500 error. Additionally, generating a table of contents for any of PDF reports now shows tagged findings in the correct severity sections. Newlines are also now respected in the text field of a note. Newlines will appear when veiwed in an individual finding as well as all pdf reports.
> Fix tables of contents and test pdf report

- dojo/tools/whitesource/parser.py
The whitesource parser fails if the report does not contain all information. Now it uses an empty string as default value instead.
On behalft of DB Systel GmbH
---
- [] Add applicable tests to the unit tests.
> Fix Whitesource parser

- dojo/fixtures/test_type.json
- dojo/forms.py
Signed-off-by: Fred Blaise <fred.blaise@protonmail.com>
Found out some space removal introduced a month ago during some "cleanup", breaking XRay ingestion. Fixing these here.
This broke the intake with error `Unknown Test Type`.
> fix introduced regression to ingesting Xray scan

- helm/defectdojo/templates/_helpers.tpl
- helm/defectdojo/templates/celery-beat-deployment.yaml
- helm/defectdojo/templates/celery-deployment.yaml
- helm/defectdojo/templates/celery-worker-deployment.yaml
- helm/defectdojo/templates/configmap.yaml
- helm/defectdojo/templates/django-deployment.yaml
- helm/defectdojo/templates/initializer-job.yaml
- helm/defectdojo/values.yaml
When deploying defect dojo using the helm chart, is not easy to use an external Relational Database ( that may be a better solution in production in example).
This PR aim to ease the use of an external DB with the helm charts
> Ease use of external db in helm charts

- dojo/context_processors.py
- dojo/pipeline.py
- dojo/settings/settings.dist.py
- dojo/templates/dojo/login.html
- dojo/urls.py
As more and more enterprises are leveraging Office 365 and Azure,
implementing Azure AD authentication using OAuth would be extremely
helpful as an alternative from relying on AD/LDAP connectivity, enabling
admins to deploy Defect Dojo in the cloud without having to send
authentication requests back to on-premises AD/LDAP.
This implementation is based on social-core, building upon the
pre-existing OKTA and Google integration.
- PR for documentation has been created on https://github.com/DefectDojo/Documentation/pull/53 
but also including documentation here 
- [N/A] Model changes must include the necessary migrations in the dojo/dd_migrations folder.
- [N/A] Add applicable tests to the unit tests. …
> Implement Azure AD Tenant OAuth. Fix #1307

- dojo/utils.py
Fixes #1571 
The idea is to not have to go to DD to see a note of a reasonable size (arbitrarily, 200 chars).
I don't think the threat model for DD accounts for the note information not to be sent to unauthorized parties anyways, since whatever generic email address could be put at the global settings level. In the case of SAML, the user email is also assumed to be correct and owned by said user.
> increase strip from 20 to 200 chars

- dojo/engagement/urls.py
- dojo/engagement/views.py
- dojo/templates/base.html
- dojo/templates/dojo/engagements_all.html
**Adding All Engagements**
Dojo menu had a "All Engagements" entry, but it opened Active Engagements only. This change still respects the Active Engagements but introduces the All Engagements view
**DataTables now available on All Engagements**
Introducing support for DataTables for all engagements view
> Adding the All Engagements View

- dojo/templates/dojo/simple_search.html
On the simple search results, adding a new column to contain the Finding ID (Dojo ID) and also include engagement version and engagements tag under the engagement column.
Fixes #1559
> Add finding ID, Eng. Version and tags to search results. Fixes #1559

- dojo/tools/openvas_csv/parser.py
Issues:
OpenVas Scan Result were not imported.
Solution:
Adapt the code for python 3
We've edit dojo/tools/openvas_csv/parser.py , now it is able to import the scan without a 500 error and with the Findings.
Related issues : https://github.com/DefectDojo/django-DefectDojo/issues/1575
> Bug Fix Import OpenVas Scan Result

- dojo/tools/dependency_check/parser.py
Fixes #1610 
If several `<cwe>` within node `<cwes>` the first one is taken. DD's model does not allow for several today.
> fix dependency-check cwe parsing

- dojo/tools/spotbugs/parser.py
Hello,
Spotbugs import failbecause of byte object not properly decoded.
See: https://github.com/DefectDojo/django-DefectDojo/issues/1613
> spotbugs import failed

- dojo/tools/qualys/parser.py
The qualys parser crashed if the cvss scorce is 0.
---
- [] Add applicable tests to the unit tests.
> Fix bug in qualys parser

- dojo/templates/dojo/paging_snippet.html
Add options to show all and 500 elements on a page with pagination
---
- [] Add applicable tests to the unit tests.
> Show more elements on a page

- DOCKER.md
- README.md
- docker/setEnv.sh
- setup/README.MD
Drop Kubernetes from supported installation method in favor of setup.bash.
Fix syntax error for OSX users when selecting docker-compose environments.
> [Dev] Modify installation README's

- dojo/templatetags/display_tags.py
- requirements.txt
The PR #1049 has broken the markdown rendering. After adding some multi-line code, the UI was not able to display the correct representation of the markdown input (see screenshots below).
This PR takes the default bleach_whitelist tags from [bleach_whitelist.py](https://github.com/yourcelf/bleach-whitelist/blob/master/bleach_whitelist/bleach_whitelist.py) and extends the "safe" html tags with the required tags to support all available markdown functions (see comments). Now, all dangerous html tags or attributes will be filtered/removed and the markdown render works as expected (see screenshots below).
If the additional html tags should not be used in defect dojo, it should be considered to remove the code highlighting or table feature.
> Expand default bleach whitelist

- docker/entrypoint-uwsgi-dev.sh
- docker/entrypoint-uwsgi-ptvsd.sh
- docker/entrypoint-uwsgi.sh
Adding multi process and multi-thread by default to avoid blocking.
Otherwise, you may just be watching an import for 5 minutes and not do anything else.
> adding multi-procs and threads by default

- dojo/models.py
If a endpoint does not contain colon, it causes problems with deduplication.
---
> Fix bug with endpoints without colons

- dojo/metrics/views.py
Hi !
repost because i failed by posting it on master
Metrics on /metrics/simple only return values from the day instead of the month (or the chosen month).
So i added in the djangoo orm filter the precision of a month instead of taking only one day.
I may recommend also to change the name of the variable "now" to "date_asked" or something like that, but it is your code :)
Very nice project !!!!
> Repair Simple Metrics data displayed on /metrics/simple route

- dojo/tools/whitesource/parser.py
Minor fix to take cvss3 by default, to make cli and UI give the same results.
> Minor whitesource cvss3 fix

- DOCKER.md
- README.md
This PR fixes a minor typo in readme and introduces small improvements of docker documentation by use of `docker-compose` instead of `docker`.
That simplifies commands and makes them independent of the name of the project directory.
> Documentation fixes

- dojo/api_v2/views.py
- dojo/settings/settings.dist.py
- dojo/urls.py
- requirements.txt
Using drf_yasg for the generation of swagger documentations allowed to use api generator like openapi-generator (https://github.com/OpenAPITools/openapi-generator). In first tests it worked very well and I am currently working on a api wrapper in python, generated by openapi-generator. 
Furthermore the api documentation contains much more details, e.g. return types. 
---
> drf_yasg for api documentation

- dojo/templates/dojo/add_findings.html
The browser should create a new window / pop-up if a user wants to add an endpoint to a newly created finding. However, jQuery crashs with a Deferred exception and the browser doesn't create a new window:
```
jquery.min.js:2 jQuery.Deferred exception: Cannot read property 'document' of null TypeError: Cannot read property 'document' of null
at HTMLDocument.<anonymous> (http://localhost:8080/endpoints/1/add?_popup:141:25)
at l (http://localhost:8080/static/jquery/dist/jquery.min.js:2:29375)
at c (http://localhost:8080/static/jquery/dist/jquery.min.js:2:29677) undefined
```
After adding the `RelatedObjectLookups.js`, the pop-up will be created.
> Fixing endpoint pop-up in add_findings.html  

- .dependabot/config.yml
Addresses #1678 
Dependabot should issue PR against `dev` and not `master`.
This config would normally work for python and yarn dependencies.
> Dependabot config - target_branch

- dojo/pipeline.py
Today, any new social login user gets `staff` permissions, meaning in the current state, gets access to all of defectdojo's data. This is definitely not great for confidentiality of information.
This simple change I guess is the only thing needed to just have the new user as a regular user with no right, which would then trigger a better out-of-band workflow to request just the necessary access to defectdojo.
Provides a workaround for #1697 
@Maffooch I saw the blame pointing to you there.. would you agree?
> No staff for new social logins

- dojo/tools/php_security_audit_v2/parser.py
Reference to **Issue #1701** 
Simple fix to check for errors + warnings rather than just errors > 0.
Using provided json file:
[phpcs_security_audit.txt](https://github.com/DefectDojo/django-DefectDojo/files/3965604/phpcs_security_audit.txt)
Originally 18 findings were created, after the update there are 19. 
Missing finding was a finding that contained only a warning. 
Internal.LineEndings.Mixed
> Updated php parser to report on warnings even with no errors

- dojo/tools/checkmarx/parser.py
- dojo/unittests/scans/checkmarx/single_finding_false_positive.xml
- dojo/unittests/test_checkmarx_parser.py
Imports checkmarx vuln with false positive status when found as such in checkmarx report
In WIP because I have based this branch on https://github.com/DefectDojo/django-DefectDojo/pull/1665 where checkmarx parser was modified a lot. 
It's actually just a couple of lines of code in checkmarx parser.py for this PR
Note that ticking "active" / "verified" in the GUI may lead to status such as: 
active, verified, false positive
this is because active and verified when ticked in the GUI overwrites what is done by the parser.
> Checkmarx set false positive status

- dojo/tools/fortify/DefaultReportDefinitionAllIssues.xml
- dojo/tools/fortify/README.md
- dojo/tools/fortify/parser.py
- dojo/unittests/scans/fortify/fortify_few_findings.xml
- dojo/unittests/scans/fortify/fortify_many_findings.xml
- dojo/unittests/test_fortify_parser.py
Fortify parser now contains the following information:
1. Abstract details (short definition)
2. Explanation (of finding)
3. Snippet
4. Source details (if available)
5. Mitigation with Recommendation and Tips (if available)
Fortify parser now also creates a single Finding from each issue in the XML (rather than trying to collect them all into buckets)
List of Findings
Details of a finding
Description containing an Explanation
Mitigation information for a finding
I used [this](https://github.com/JoyChou93/java-sec-code) code to create an FPR with Fortify, generated the XML and uploaded it for a total of 324 Findings. (334 were created, 10 were removed for deduplication, which I verified and am satisfied with). The XML is also added to the repo for unit tests, but I'll include it here: …
> Fortify Parser Overhaul

- dojo/templates/dojo/findings_list.html
Updated datatable because the endpoint popup didnt work. The hover-trigger was missing
This affected the "open Findings" View. Basically the trigger was not set in the data-tables, but as far as I know the only location for endpoints in datatables was in the "open findings" view, which uses the findings_listtemplate
> Updated datatable because the endpoint popup didnt work. 

- dojo/models.py
This addresses an issue from #1628 when a finding with no CVE, CWE, file
path, or line number would list all findings from the same product which
can potentially grow unbounded.
@madchap @jeffret-b
> Limit number of similar findings displayed to 10

- helm/defectdojo/templates/initializer-job.yaml
This only fails when resources are defined for the initializer container/pod
```
initializer:
resources:
limits:
cpu: 1
```
Instructions to reproduce
Download Helm (I used [Helm 3.0.2](https://github.com/helm/helm/releases/tag/v3.0.2))
```
$ cd django-DefectDojo
$ helm add stable https://kubernetes-charts.storage.googleapis.com/
$ helm depency update ./helm/defectdojo
$ helm depency build ./helm/defectdojo
$ helm template --set initializer.resources.limits.cpu=1 -n defect-dojo defect-dojo ./helm/defectdojo
```
Scroll until you find
```
...
````
Note:
Looks like the `requirements.lock` file is outdated. Would you like me to add this change to the PR or raise a new PR for it?
```
diff --git a/helm/defectdojo/requirements.lock b/helm/defectdojo/requirements.lock
index 2465554d..09029639 …
```
> [Helm] Fix resources indentation. Closes #1663

- dojo/finding/views.py
Images are binaries and should be read as such. 
The FileIterWrapper helper reads more than binaries, so we must set the B flag on the open function, not the IterWrapper when reading images.
Fixes #1674 and possibly #1633
> Read images as binaries. Fixes #1674

- .dependabot/config.yml
Pushing dependabot config to master (default) branch, so that it actually takes effect.
> Pushing dependabot config to master

- dojo/api_v2/serializers.py
- dojo/engagement/views.py
- dojo/forms.py
- dojo/templates/dojo/import_scan_results.html
- dojo/test/views.py
Option to manually add endpoints to scans
In some cases it is helpful to have the opportunity to manually add endpoints to scans. One example is a clair scan which you want to map to a specific server.
on behalf of DB Systel GmbH
---
> Add endpoints to scan

- dojo/tools/clair/parser.py
Currently CVE References are not added to Findings when those are imported from clair reports.
- [y] Your code is flake8 compliant 
- [y] Your code is python 3.5 compliant
- [y] Model changes must include the necessary migrations in the dojo/dd_migrations folder.
> Added CVE Reference to imported findings from clair

- docker/entrypoint-uwsgi-ptvsd.sh
Running ptvsd with threads and potentially multi-processes will mess with you soon or later.
If you're debugging something anyways, you probably do not need multiple threads, but rather will like to have 100% of your breakpoints work or hot-reload to be super fast.
fyi @ptrovatelli
> Removing threading from ptvsd entrypoint

- dojo/tools/dependency_check/parser.py
Since ff9057cf9e80d5508d6a6a9774b6aa77dae99817 my owasp dependency checker imports are failing because the CVE field has been limited to 20 characters.
This makes sense, but apparently the owap dependency checker parser uses the "name" field as CVE and sometimes it doesn't contain a valid CVE value but a textual description of the vulnerability.
i.e. when there is no CVE for this vulnerability I presume.
Options considered:
- Keep as-is: let imports fail. Not an option because it happens all the time
- Truncate: simplest for now, but while typing this I realize it might lead to strange CVE values
Possible improvement: check if the value matches regex, if not, do not set CVE.
At least it's working again now and we can gain some experience with the kind of values we see in the name/cve …
> owasp_dependency_checker: truncate too long cve fields

- dojo/finding/views.py
- dojo/models.py
Currently similar findings doesn't respect the deduplication_on_engagement flag and allows users to mark findings from other engagements as duplicate. When you have dedeuplication removal turned on this will remove the duplicate issue which is probably not what the users want in this scenario.
This PR makes sure the similar finding view only returns findings within the same engagement iff deduplication_on_engagement is turned on.
And it prevents the marking as duplicate from happening alltogether by adding some checks to the lower level code.
> Make Similar findings play nice with dedupe on engagement

- dojo/templates/dojo/view_finding.html
The list with similar findings doesn't show the title, so you need to open each similar findings to check out what it is (providing that cwe is equal or empty and cve is equal or empty and filepath is equal or empty). This happens a lot with the npm audit scan as it doesn't have most of these fields.
This small change adds a tooltip to the finding (date) to make it easier to compare. There's no room to add the full title.
> similar findings: add tooltip to show title

- dojo/tools/dependency_track/parser.py
- dojo/tools/npm_audit/parser.py
- dojo/tools/php_symfony_security_check/parser.py
I am observing some findings marked as dynamic even though they are imported from the OWASP Dependency Checker / Track scans. Third party dependencies should be treated as static, so a good start is to mark them as static in the parser/import.
> dependency checkers: provide better defaults for static/dynamic field

- dojo/fixtures/test_type.json
- dojo/forms.py
- dojo/templates/dojo/import_scan_results.html
- dojo/tools/factory.py
- dojo/tools/outpost24/parser.py
- dojo/unittests/scans/outpost24/none.xml
- dojo/unittests/scans/outpost24/one.xml
- dojo/unittests/scans/outpost24/sample.xml
- dojo/unittests/test_outpost24_parser.py
@madchap @jeffret-b @Wadeck @daniel-beck
> Add basic parser for Outpost24 scan format

- dojo/templates/dojo/findings_list.html
When viewing a list of findings currently it's hard to see in which engagement a finding is.
When you're using deduplication_on_engagement you will (can) have multiple identical findings in different engagements. I added a tooltip to show the engagement name with the product (as there's not really enough to add another text column).
I also added a tooltip with the specific test title to the foundby value, this can be beneficial again in some scenario's.
> findings_list: add tooltips for engagement name and test title

- dojo/templates/dojo/view_eng.html
- dojo/templates/dojo/view_test.html
- dojo/templatetags/display_tags.py
Currently the list of tests in an engagement and also the view tests page shows the target_start and target_end date without localizing them.
I'm in CET and this means tests will be 1 day off always. On import the datetime is set to UTC in the database. This works fine for datetimes, which are localized correctly by django.
But when shortening them to the date part only, it fails.
i.e. target_start = 'Feb 01, 2020' on import, results in 2020-01-31 23:00:00 in the database, which is shown on screen as 'Jan 31, 2020' (instead of 'Feb 01, 2020').
~~I don't know why this is and found lots and lots of (stack overflow) posts around the same issues.~~
~~In the end I just created a filter that helps us to localize the date.~~
Fixes #970
> show local dates for tests target_start and target_end

- dojo/settings/settings.dist.py
- dojo/tools/npm_audit/parser.py
the module name in the npm audit report can be used as filepath, and the cve field will also be populated.
specified filepath + cve + cwe as extra fields for dedupe
> Npm audit add file path and configure dedupe fields

- dojo/finding/views.py
- dojo/forms.py
- dojo/templates/dojo/apply_finding_template.html
- dojo/templates/dojo/apply_finding_template_form_fields.html
- dojo/templatetags/as_json.py
This fixes the merge options for the tags attribute. The following problems are solved:
1) The form's data value for the tags is overwritten in the view, thus the template had no
way of determining the actual Finding's tag value. The view now explicitly passes these
on to the template.
2) The template value in the `onchange` handler was not handled properly, as it was a
QuerySet: The `data-template-value` field contained the `__repr__` value of the
queryset (i.e., `<QuerySet ...>`) rather than the tag names.
3) The (ugly) inline `onchange` handler for the select was not handling the case of a
multi-select properly. This is fixed now with a dedicated handler for the tag field.
4) The available tags in the `ApplyFindingTemplateForm` were missing those tags that
are only used within …
> Apply Template to Finding: Fix merge options for tags

- dojo/templates/dojo/apply_finding_template.html
- dojo/templates/dojo/apply_finding_template_form_fields.html
The markdown rich text fields used in the apply template to finding view
shadow the underlying textareas. Thus, the update of the textarea's value
has no effect.
This commit stores the MDE JavaScript objects on the the field's DOM
object. The change of the contents is now performed on the MDE elements
using their designated method rather than directly on the textarea
element.
> Apply template to Finding: Fix merge options for markdown text fields

- dojo/settings/settings.dist.py
- dojo/tasks.py
- dojo/tools/factory.py
- dojo/tools/php_symfony_security_check/parser.py
Importing PHP Symfony Security Checker seems to be broken for a long time as the scan_type became out of sync in factory.py in 86f2de355c2cc80ce44ad8b437aa87d8afce89d4 (at least in APIv2)
This small commit changes the id/key in factory.py to match with those in test_type.json etc.
> Fix PHP Symfony Security Checker import and dedupe

- KUBERNETES.md
- README.md
- docker/entrypoint-uwsgi-ptvsd.sh
- helm/defectdojo/Chart.yaml
- helm/defectdojo/requirements.lock
- helm/defectdojo/requirements.yaml
- helm/defectdojo/templates/_helpers.tpl
- helm/defectdojo/templates/celery-beat-deployment.yaml
- helm/defectdojo/templates/celery-deployment.yaml
- helm/defectdojo/templates/celery-worker-deployment.yaml
- helm/defectdojo/templates/django-deployment.yaml
- helm/defectdojo/templates/django-ingress.yaml
- helm/defectdojo/templates/initializer-job.yaml
- helm/defectdojo/templates/secret-mysql.yaml
- helm/defectdojo/templates/secret-postgresql.yaml
- helm/defectdojo/templates/secret-rabbitmq.yaml
- helm/defectdojo/templates/secret-redis.yaml
- helm/defectdojo/templates/secret.yaml
- helm/defectdojo/templates/tests/unit-tests.yaml
- helm/defectdojo/values.yaml
Various fixes and improvments for kubernetes: 
- Fixed yaml identations
- Convert to kubernetes 1.16 using "kubectl convert". This probably didn't change much but this is the first thing I tried when nothing was working for me :) . I have kept the changes which is basically a bit of identation and formating changes; it's more standard this way I guess because it's how kubernetes "natively" idents yaml. 
- add option "django.ingress.activateTLS" : before having this option, if you hadn't setup TLS, the application wasn't working (HTTP 404). Now we have a first step without TLS with a working application. (I haven't tested TLS yet)
- comment out nginx ingress controller annotation: due to this annotation, the application could only work with nginx controller (example: with traefik, HTTP 404 …
> Kubernetes 1.16 / helm3 improvements

- dojo/finding/views.py
- dojo/models.py
- dojo/test/views.py
- dojo/tools/tool_issue_updater.py
Since the sonarqube (api) integration, every update to an issue or every issue created, triggers the creation of an async celery task to update the original issue in sonarqube.
This makes sense for issues that were imported from sonarqube. But not for all other issues. In CI/CD environment this leads to lots and lots of celery tasks that basically do nothing but generate overhead :)
So I wrapped the async tool update code in a function that only creates the async task if applicable.
For now this only applies to imports from sonarcube. 
The original functions do not refer to "sonarqube updater" but a more generic "tool_issue_updater". So maybe it was designed to be a mechanism for other tools in the future?
As I didn't want to change much to this, I just created a simple wrapper function. …
> Only run async tool issue updated when applicable

- dojo/test/views.py
updated code to set date to target start if date is the default date of 'today'
Date setting behavior will be the same for new findings on re-import as well as new findings on initial import.
Bug: #1855
> Fixing re-import finding date logic

- dojo/templates/dojo/view_test.html
In a CI/CD setup and/or when using reupload / reimport, it's useful to be able to see last date the test was updated. There's room enough on this page, so I added a column with the date. It includes a tooltip with the full datetime fore more CI/CD greatness.
> add Updated column to view_test

- dojo/templates/dojo/engagement_pdf_report.html
- dojo/templates/dojo/simple_search.html
- dojo/templates/dojo/test_pdf_report.html
Following #1835 I found some more places where target_start and target_end for engagement/test where not localized before being displayed.
In theory I think we might have to apply the "|date" filter everywhere also where finding.date, note.date etc is being used. However for now I think the test/engagement dates are the most sensitive to a "1 day off issue", so I fixed those first and will leave the rest as-is for now.
> use local dates for tests and engagement start/end dates

- dojo/utils.py
There is a try..except around the dashboard punchcard code to help iron out corner cases.
The `raise(e)` in there was accidentally left from debugging, this PR removes it.
> Bugfix dashboard do not reraise e

- dojo/engagement/views.py
- dojo/test/views.py
Was getting pretty annoyed by the **500 Internal Server Error** message when there are exceptions in the parser logic. 
Not sure if this is the _most correct_ way to solve the problem but I gave it a shot.
Reloads the page with an error message that I pull straight from the exception. Up to the coder of the parser logic to make sure the error message is useful. (i.e. Key error message are pretty useless by themselves)
I just print the exception message in the error, could change this to have less information (just something like "there were errors importing scan results" without specifying the errors)
Following screenshot was generated by adding to the hackerone parser:
`raise Exception("Raising an exception in the parser for error testing.")`
> Added exception catching, error message, and redirect

- README.md
Update OWASP invite link to https://owasp-slack.herokuapp.com/
> Update slack invite URL to use the OWASP heroku invite rotator app

- helm/defectdojo/requirements.lock
- helm/defectdojo/requirements.yaml
This allows the use of Helm named repositories and uses caching layers
or other repositories managers like Nexus, Artifactory, S3 buckets...
Signed-off-by: Carlos Juan Gómez Peñalver <carlosjuangp@gmail.com>
------
> dev: chg: use Helm named repositories. Closes #1728

- DOCKER.md
- Dockerfile.nginx
- docker-compose.override.https.yml
- docker-compose.yml
- docker/entrypoint-nginx.sh
- nginx/nginx_TLS.conf
Generate TLS Certificate
The Nginx generates a TLS Certificate on every start if there is the environment variable is not set. You can add your own cetrificate by mounting it to /etc/nginx/ssl/ and setting GENERATE_TLS_CERTIFICATE to false. You can activate the TLS configuration fo nginx with the environment variable USE_TLS.
From my point of view it is an security issue that the certificate is inlcuded during the docker build step. It should be added at the runtime not at buildtime.
Hardening on the TLS Configuration of nginx.
----
**Note: DefectDojo is now on Python3 and Django 2.2.1 Please submit your pull requests to the 'dev' branch as the 'legacy-python2.7' branch is only for bug fixes. Any new features submitted to the legacy branch will be ignored and …
> TLS Improvments

- Dockerfile.nginx
- Upgarde NodeJS version :
Upgrade from version 11.x to 12.x due to decprecation warning, since nodejs 11.x is no longer actively supported
```
================================================================================
================================================================================
DEPRECATION WARNING                            
Node.js 11.x is no longer actively supported!
You will not receive security or critical stability updates for this version.
You should migrate to a supported version of Node.js as soon as possible.
Use the installation script that corresponds to the version of Node.js you
wish to install. e.g.
* https://deb.nodesource.com/setup_10.x — Node.js 10 LTS "Dubnium" (recommended)
* https://deb.nodesource.com/setup_12.x — Node.js 12 LTS "Erbium" …
```
> Upgrade NodeJS and Fixing issue #1931

- dojo/db_migrations/0030_prod_type_meta.py
- dojo/models.py
- travis/integration_test-script.sh
Migration needs an update because another migration was merged just before #1899 was merged.
It also seems that 'active=True' reappeared for active finding count.
> Performance prefetching phase1 migrationfix

- dojo/tools/crashtest_security/parser.py
Due to a minor change in the output format, the importer crashes and produces a 500 server error.
A test file in the new format is provided here: https://github.com/DefectDojo/sample-scan-files/pull/45
> Fix import error for Crashtest Security importer

- dojo/tools/crashtest_security/parser.py
I just noticed another crash during the import of a Crashtest Security Scan file, in the case that the scan contains any skipped test case.
This PR fixes prevents this crash by adding a check for skipped tests.
> Fix import error for Crashtest Security importer for skipped scans

- dojo/management/commands/dedupe.py
- dojo/tasks.py
To have a complete view in the dedupe log, this PR makes sure also background tasks and management tasks are logging to the `deduplicationLoigger`.
> dedupe: also log background tasks and management tasks

- dojo/api_v2/views.py
Fixes https://github.com/DefectDojo/django-DefectDojo/issues/1977
While we may decide to do something more later on is a different discussion, but we should revert this back to what it was. See related issue for more info.
- enhancement
- feature
- bugfix
- dependencies
> Revert import scan to original permission checks

- .github/release-drafter.yml
- .github/workflows/release-drafter.yml
Changing the release-drafter to add `dev` branch on top of `master`, given our flow, to get the more granular merge info.
> release-drafter to work with dev branch

- Dockerfile.nginx
Based off `1.5.4` tag, created this `1.5.4.1` to be clean and not force-push.
Should also be tagged `1.5.4.1` upon merge and released.
> Backport nodejs fix

- dojo/tools/burp_enterprise/parser.py
https://github.com/DefectDojo/django-DefectDojo/pull/1964 was apparently missing flake8 compliance.
Hit issues with Travis when it tried to run tests on other PRs.
- enhancement
- feature
- bugfix
- dependencies
> Fix Burp Enterprise flake8

- dojo/context_processors.py
- dojo/engagement/views.py
- dojo/finding/views.py
- dojo/product/views.py
- dojo/product_type/views.py
- dojo/search/views.py
- dojo/settings/settings.dist.py
- dojo/templates/base.html
- dojo/templates/dojo/dashboard.html
- dojo/templates/dojo/findings_list.html
- dojo/templatetags/navigation_tags.py
- travis/integration_test-script.sh
- travis/script.sh
Similar to #1899 prefetching most date up front to reduce queries and increase performance.
Includes some small cosmetic changes and no longer performs 5 queries per page to display the alert count.
- prefetch related data when displaying active / all engagements
- prefetch related data when displaying list of findings
- prefetch related data when displaying search results
- add check for old codepaths to only prefetch when possible
- order recently closed findings by descending closed (mitigated) date
- cache alert counts while rendering pages/templates -> needs a change to `settings.py`.
> performance gains by prefetching in more places

- requirements.txt
Pygments is never used in the code. Related to https://github.com/DefectDojo/django-DefectDojo/pull/2004.
> remove dependency pygments

- .github/release-drafter.yml
- .github/workflows/release-drafter.yml
Despite web yaml validators saying it was valid, yamllint didn't... and it seems release-drafter is no longer working after the last mods.
So fixing a couple things that yamllint complained about:
```
$ yamllint .github/release-drafter.yml 
.github/release-drafter.yml
1:1       warning  missing document start "---"  (document-start)
17:12     error    trailing spaces  (trailing-spaces)
```
```
$ yamllint .github/workflows/release-drafter.yml 
.github/workflows/release-drafter.yml
1:1       warning  missing document start "---"  (document-start)
3:1       warning  truthy value should be one of [false, true]  (truthy)
16:11     warning  comment not indented like content  (comments-indentation)
16:81     error    line too long (101 > 80 characters)  (line-length)
```
This PR removes errors …
> yamllint satisfaction

- dojo/templates/dojo/apply_finding_template_form_fields.html
Fixes #2048, handle None (empty) value for CWE properly when applying a finding template to a finding.
> fix #2048 handle None value for CWE in apply finding template

- dojo/settings/settings.dist.py
fixes #2064 
a middleware is needed to make sure the auditlog post_save signals know the actor of the action
https://django-auditlog.readthedocs.io/en/latest/usage.html#actors
> add required middleware to set actor_id in auditlog entries

- tests/Endpoint_unit_test.py
- tests/Engagement_unit_test.py
- tests/Environment_unit_test.py
- tests/Finding_unit_test.py
- tests/Import_scanner_unit_test.py
- tests/Note_type_unit_test.py
- tests/Product_type_unit_test.py
- tests/Product_unit_test.py
- tests/Test_unit_test.py
- tests/User_unit_test.py
- tests/base_test_class.py
- tests/check_status.py
- tests/check_status_ui.py
- tests/dedupe_unit_test.py
- tests/ibm_appscan_test.py
- tests/local-integration-tests.bat
- tests/local-integration-tests.sh
- tests/local-unit-tests.sh
- tests/smoke_test.py
During #2002 I ran into the fact that Integration tests are quite slow.
(and we also see this in Travis that sometimes the test gets killed because it takes too long)
This PR does *not* change the test coverage, it just improves the way they are structured and run:
- Extract duplicated (setUp) code into `BaseTestCase`
- Reuse browser session to save lots of time
- Import between testcases in a normale way
- Add some comments on how to initialize webdriver for local tests, visible browser window, etc
- Add some `local-xxxx` scripts to facilitate how to start the tests locally
- Set verbosity in testrunnen. (Let the integration tests log what they are doing as sometimes it's not clear in Travis which tests have been run / skipped / commented out)
This looks like a big PR, but that is only …
> simplify and speedup integration tests

- dojo/utils.py
Current Alert:
"Jira update issue", no link to finding
With this PR:
"JIRA update issue (<product_name[:25]>)", link to finding
> add url and product name to jira alert message

- dojo/tools/npm_audit/parser.py
fixes #2059
npm audit parser: limit vulnerable paths to max 25, add advisory url to description,
> npm audit parser: limit vulnerable paths to max 25

- dojo/templates/dojo/edit_findings.html
fixes javascript error in #2006. the javascript is trying to manipulate elements that are not in the html if there are no dupes. this PR prevents that.
> only show dupes dropdown if there are dupes, fixes #2006

- travis/before-install.sh
Disable for now as the error below breaks everything Travis.
```
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100  1232  100  1232    0     0   6508      0 --:--:-- --:--:-- --:--:--  6518
This script requires superuser access to install apt packages.
You will be prompted for your password by sudo.
+ dpkg -s apt-transport-https
+ echo deb https://cli-assets.heroku.com/apt ./
+ dpkg -s heroku-toolbelt
+ true
+ curl https://cli-assets.heroku.com/apt/release.key+ apt-key add -
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100   952  100   952    0     0   4643      0 --:--:-- --:--:-- --:--:--  4643
gpg: invalid armor header: …
```
> Disable heroku install for now as an error is generated 

- dojo/product/views.py
Should fix https://github.com/DefectDojo/django-DefectDojo/issues/2013, even though after re-reading it, I think this PR is going to mostly be some type of cleanup.
Finding open view
Product open finding view
Both queries go to https://github.com/DefectDojo/django-DefectDojo/blob/dev/dojo/finding/views.py#L467 per the urls.py.
- enhancement
- feature
- bugfix
- maintenance (a.k.a …
> fix some queries so that open include active verified and not verified

- dojo/models.py
- dojo/system_settings/views.py
- dojo/unittests/test_system_settings.py
The codebase is using lots of `System_Settings.objects.get()` calls to read the system settings. This results in lots of database queries. Sometimes over a 100 queries just to render one page.
Alternatives considered:
1. Rewrite all occurrences into something like `get_system_settings()` to abstract away from the implementation of system settings as a model
2. Use threadlocals in some way
3. Use a full blown Redis ORM cache or similar
Although option 3 provides many benefits, it's also an extra step/hurdle/maintenance burden. Also having 100s of queries for a single will page will never lead to optimal results.
So I opted for option 4:
4. Sneaky caching of System_Settings model
Basically it's a fully supported features of Django ORM to use custom managers for your model. For example to …
> performance: cache system_settings in views

- dojo/tools/checkmarx/parser.py
- dojo/unittests/test_checkmarx_parser.py
Per Checkmarx Support, SimilariyID+PathID should be used to identify unique findings.
I am using the dev branch to add this change as it has the latest rework from https://github.com/DefectDojo/django-DefectDojo/pull/1665 
Please do let me know if I am missing something :)
Thanks,
SD
> Adding SimilarityID and PathID concatenation as unique_id_from_tool for Checkmarx Parser

- dojo/tools/anchore_engine/parser.py
- dojo/unittests/scans/anchore/many_vulns.json
- dojo/unittests/test_anchore_parser.py
The anchore parser has a `dupe_key` variable made up of certain vuln characteristics, to directly avoid re-importing findings inside the parser.
However, inconsistencies creeped in as the `package_path` filled for java vulnerabilities was not taken into account. That led to not all findings being imported because of it and have incomplete report.
The unittest has been amended with concrete examples. 
- Import Scans (for new …
> Anchore parser fix to consider package_path

- .github/release-drafter.yml
- .github/workflows/release-drafter.yml
Opened a ticket in the release-drafter gh as well..
Until then, would like to push the exact same config in `dev` that what is on `master`. It would be odd to have to replicate the config in all branches and not just the default one as their page and comments seems to hint at, but since `dev` PRs are getting drafted and not `dev`'s, I guess it does not hurt to try.
> copycat release-drafter config on dev branch

- docker/entrypoint-initializer.sh
Make sure to not give a new non-working admin passwd if present in DB, and print the command to create a new superuser in case the user cannot remember.
> docker initializer: do not give a new non-working passwd if admin present in DB

- dojo/api_v2/serializers.py
The current ImportScan api_v2 endpoint does not return the id of the test that was created. I needed this when writing some new unittests and I think it can be useful for all kinds of (ci/cd) scenario's too.
> apiv2: add test.id in result of importscan

- dojo/tools/jfrogxray/parser.py
- dojo/unittests/test_jfrogxray_parser.py
- enhancement
- feature
- bugfix
- dependencies
> Add component name and version for JFrog scans

- tests/dedupe_unit_test.py
Quite often the Travis build fails because the integration tests sees an incorrect amount of duplicates. But sometimes the exact same commit builds fine. The theory is that Travis is sometimes so slow that it takes a bit of time for the background celery task to run/complete.
This PR implements a 5s wait time and 4 tries when checking for duplicates and hopefully makes the builds more stable.
> integration-tests: add wait/retry when checking for duplicates

- helm/defectdojo/templates/django-deployment.yaml
- helm/defectdojo/templates/initializer-job.yaml
- helm/defectdojo/values.yaml
- add a nodeselector in the initializer job
- fix nodeSelector in django deployment (was at the root, should be under django as in values.yaml)
- add limits
> kubernetes: fix node selectors; add limits

- dojo/api_v2/serializers.py
- dojo/engagement/views.py
- dojo/finding/views.py
- dojo/models.py
- dojo/object/parser.py
- dojo/product/views.py
- dojo/search/views.py
- dojo/settings/settings.dist.py
- dojo/tag/prefetching_tag_descriptor.py
- dojo/templates/dojo/engagement.html
- dojo/templates/dojo/engagements_all.html
- dojo/test/views.py
- dojo/unittests/test_rest_framework.py
- dojo/unittests/test_taggit_tags.py
- dojo/utils.py
- requirements.txt
- setup.py
This solves part of #1812.
When Defect Dojo displays a list of findings / products / engagements it performs an additional query for each row in the table. This query retrieves the tags for 1 row at a time. So a list of 25 products results in 25 database queries. The active engagements page even has more queries, 25 for the products and then an additional one for each engagement. In my instance this resulted in 100+ only to retrieve tags. This PR resolves that in line with best practices around Django ORM. 
So we can keep using the current taggit library and we don't have to do a complex migration right-away.
Changes made:
- Add a `GenericRelation` from models that can be tagged. This is needed to be able to find tags with a model instance.
- Patch the `TagDescriptor` coming with …
> Prefetch tags and more to remove 1+N queries problem

- dojo/templates/dojo/product.html
quotes were missing around "asc" on the product list page resulting in javascript errors.
> product list: add missing quotes around asc for table sorter

- dojo/templates/dojo/product.html
- tests/Finding_unit_test.py
- tests/Product_unit_test.py
- tests/base_test_class.py
- tests/local-integration-tests.bat
We have seen about 7 PRs / issues around javascript erros lately. These are now all fixed, but we should check for javascript errors in the integration tests.
(EDIT Actually found another one using this PR: #2095)
This PR adds those checks. At the end of every test (so each method), there is a check to see if there are no javascript errors.
This can be checked earlier manually by calling `self.assertNoConsoleErrors()`.
Currently the docker build used by Travis doesn't support images for findings, so these errors are ignored.
- removed superfluous login_page method
- add settings for logging for javascript console
- move delete_image earlier so the javascript errors disappear again
- add test_list_products to make sure product list is free of javascript errors
- add …
> Integration test: Assert absence of javascript errors

- dojo/middleware.py
- dojo/settings/settings.dist.py
Hey there,
I noticed that both middlewares execute their custom logic only *after* the request is handled.
Wrt the `LoginRequiredMiddleware`, this allows unauthenticated users to execute requests even if the request URL is not on the whitelist `settings.LOGIN_EXEMPT_URLS`.  The unauthenticated user cannot see the result of the request, though.
EDIT: As suggested by @valentijnscholten, this PR removes the timezone middlware.
Best,
Felix
> Fix middlewares

- docker/entrypoint-initializer.sh
Won't work as well in a copy-paste situation.
> fix uwsgi typo in initializer log

- dojo/settings/settings.dist.py
This commit fixes an issue where the trailing slash of callbacks URLs is removed
(DD_SOCIAL_AUTH_TRAILING_SLASH=(bool, False) and makes the login process fail as
it differs from the LOGIN_EXEMPT_URLS URLs that are allowing URLs with the trailing
slash.
This commit also generalizes the allowed call-back URLs to ```complete/``` instead
of cherry-picking the different IdPs. I'll simplify the process to add new IdPs
in the future.
Last but not least this commit also revert what has been introduced into #PR 2079
where DD_SOCIAL_AUTH_TRAILING_SLASH was set to False. I understand now that it was
bad idea to do that as it modifies the call-back URL that is sent to the IdP by
removing the trailing slash, it'll probably break existing social-auth deployments
as the allowed-call-back-url will need …
> Social-auth: Fix call-back URLs

- dojo/templates/dojo/view_finding.html
When viewing findings which have "similars", the similar takes a big amount of place.
And if the finding has "extra" info, such as components, or I imagine endpoint info and such, you have to scroll down or minimize the "similar finding" block, which is aggravating.
This moves the "similar findings" block below these.
> Move similar finding below actual finding main info

- dojo/api_v2/views.py
In order to re-create an existing association, we must know the finding_id to find, then delete and (re)create. (The patch method does not work due to the unique database constraint on finding_id).
This basically allows to `GET` the association with the finding_id alone.
> [apiv2] Add capability to query by finding_id on the jira_finding_mapping endpoint

- dojo/api_v2/serializers.py
- dojo/api_v2/views.py
- dojo/notes/views.py
This PR grants superuser users the ability to delete notes from the API, and also make the `patch` endpoint work to remove a note from a finding.
When wanting to remove a note from a finding with the same user from the UI or from the APIv2, the APIv2 forbid me to delete if not the same user, something we don't have from the UI.
Also, the `patch` or `put` methods were actually forbidden (error 405), even though specified on the `remove_note` endpoint, it had to be specified also on the `notes` to work.
Since both seemed to achieve the same thing, …
> Allow staff users to delete notes

- dojo/unittests/test_system_settings.py
Lately we have seen a lot of `DoestNotExist` exceptions on `System_Settings` in the travis builds (causing failures). Usually this was after migrations failed with Travis saying some table alreadys exists, even though it should have been starting with an empty db.
Today however I saw a build failing which did have no migration errors, only this error on `System_Settings`. So just to be sure it's not the cause of the failures, I've added a try-except block around it. Similar to what is done in `get_system_setting` in `utils.py`.
> unittests: check for existence of system_settings db record

- dojo/unittests/test_system_settings.py
I don't know what went wrong with my own tests, then travis, then 2 approvers, but obviously my PR #2105 contains a syntax error. this PR fixes it
Good thing is that the exception is being triggered, which might mean this PR will help travis become more successful.
```
======================================================================
ERROR: test_system_settings_update (dojo.unittests.test_system_settings.TestSystemSettings)
----------------------------------------------------------------------
File "/app/dojo/unittests/test_system_settings.py", line 10, in test_system_settings_update
system_settings = System_Settings.objects.get()
File "/app/dojo/models.py", line 104, in get
return cache.get_or_set(self.CACHE_KEY, lambda: …
```
> system settings test: fix copy-paste error

- dojo/fixtures/test_type.json
- dojo/forms.py
- dojo/templates/dojo/import_scan_results.html
- dojo/tools/factory.py
- dojo/tools/harbor_vulnerability/parser.py
- dojo/unittests/scans/harbor_vulnerability/harbor-0-vuln.json
- dojo/unittests/scans/harbor_vulnerability/harbor-1-vuln.json
- dojo/unittests/scans/harbor_vulnerability/harbor-5-vuln.json
- dojo/unittests/scans/harbor_vulnerability/harbor_0_vuln.json
- dojo/unittests/test_harbor_vulnerability.py
- enhancement
---
Harbor (https://github.com/goharbor/harbor) has the ability to scan all containers and itself acts as a bridge between the scanner and the image. We wanted to utilise that function from Harbor.
I've added a documentation PR on Harbor integration per following link
https://github.com/DefectDojo/Documentation/pull/79
> Adding a parser from Harbor vulnerability API

- dojo/templates/dojo/test_pdf_report.html
Just a quick little typo fix.
Issue:
When generating an HTML report for a Test, test notes were not appearing.
Cause:
Typo - was looking at find.notes rather than test.notes
> Fix test notes not appearing in report + cosmetic improvement

- dojo/models.py
- dojo/utils.py
- tests/Engagement_unit_test.py
- tests/Import_scanner_unit_test.py
- tests/Product_unit_test.py
- tests/Test_unit_test.py
- tests/base_test_class.py
- tests/dedupe_unit_test.py
- tests/ibm_appscan_test.py
- tests/local-integration-tests.bat
- tests/local-integration-tests.sh
- tests/smoke_test.py
- travis/integration_test-script.sh
- travis/script.sh
Integration tests were failing randomly in Travis. Turns our this was not Travis' fault, but our own code.
This PR fixes two main problems with Defect Dojo / Integration tests.
- Dedupe tests failing. This was caused by a corner cases being affected by #1953. The cache there is local per worker, so if you have multiple workers, you can have stale system settings for at most 30s. This is usualy OK, but in integration tests it's an issue. This PR contains a workaround, proper fix to follow based on #2164
- `StaleElementReferenceException` by Selenium. This was caused by #1586. After the page is loaded, the datatables javascript applies itself to the DOM and changes it. It wraps itself around the original products table causing the element that selenium just found to go stale. This is a bit …
> integration tests fixes and improvements

- .github/release-drafter.yml
Just removing empty line to align on `dev`. Still don't really know why release-drafter do not work on both.
> Removing extra line

- dojo/api_v2/serializers.py
- dojo/models.py
- dojo/templates/dojo/engagement.html
- dojo/templates/dojo/engagements_all.html
- dojo/templates/dojo/snippets/engagement_list.html
- dojo/templates/dojo/view_eng.html
- dojo/test/views.py
- dojo/utils.py
- tests/Engagement_unit_test.py
- tests/Test_unit_test.py
- tests/base_test_class.py
- tests/local-integration-tests.bat
Some CI/CD related improvements I implemented during due to due usage:
- (fix) #1926 Mitigate only once on reuploads
- show overdue also in list of active/all engagements
- ci/cd:
- set target_end to to the date of the latest scan import
- use 10 day grace period before ci/cd engagement becomes overdue
The idea is that for CI/CD engagement a target_end usually doesn't make sense. By updating the target_end whenever a scan is uploaded it becomes nicely apparent which engagements are scanned regularly. We have a policy that every project(or branch) should be scanned at least weakly, so a 10 day grace period fits nicely with that.
> Cicd improvements: reupload mitigation, overdue

- .github/workflows/plantuml.yml
- .github/workflows/release-drafter.yml
Upon a PR merging, will auto-generate the png and svg output for a given .puml file (plantUML), like the ones we are introducing through PR #2003
> Add plantuml github action + use major version for RD

- helm/defectdojo/values.yaml
According to the description _Option to use "postgresql" or "mysql" database type, by default "postgresql" is chosen_, it should be postgresql?
> Update values.yaml mysql default description

- dojo/management/commands/fix_loop_duplicates.py
Erroring due to missing `get_system_settings`
```
$ docker exec -ti madchap_ddojo_uwsgi_1 bash -c 'python manage.py fix_loop_duplicates'
enabling audit logging
patching TagDescriptor
File "manage.py", line 11, in <module>
execute_from_command_line(sys.argv)
File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
utility.execute()
File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 375, in execute
self.fetch_command(subcommand).run_from_argv(self.argv)
File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 224, in fetch_command
klass = load_command_class(app_name, subcommand)
File …
```
> fix crash when running fix_loop_duplicates.py

- dojo/tools/nessus/parser.py
The commit fixes an issue where Nessus reports in the CSV format are not processed correctly. The parser was broken since the Python2->Python3 migrations (strings were Bytes and now it's Unicode).
- enhancement
- feature
- bugfix
- dependencies
> parser: nessus: Fix CSV import

- dojo/finding/views.py
This errors occurs in case of a save request with an invalid form:
Internal Server Error: /template/XXX/edit
[...]
File "./dojo/finding/views.py", line 1242, in edit_template
'count': count,
UnboundLocalError: local variable 'count' referenced before assignment
> Finding:  Fix unbound variable error in `edit_template`

- dojo/api_v2/views.py
Fixes #2118
There would be probably more to fix, but now that there is an example, it may be easier for those who notice -- including myself :)
> Amend swagger doc to have the proper serializer displayed

- docker/entrypoint-initializer.sh
- dojo/middleware.py
- dojo/models.py
- dojo/settings/settings.dist.py
- dojo/system_settings/views.py
- dojo/tasks.py
- dojo/utils.py
- tests/dedupe_unit_test.py
fixes #2164 and properly fixes the workaround from #2160 
This is an improved caching of system settings. The one in #1954 was using the django cache.
This works fine under normal use, but when using multiple workers even the limited ttl of 30s is too much.
This PR introduces a middleware to cache the system_settings during a single request.
It uses a threadlocal, which should be used with care. In this case it's reliable because the middleware 
always cleans up the threadlocal at the end of the request.
Anythin that is not a request (celery tasks) will not use the middleware, so are not affected and will always 
query the database.
Alternatives considered:
- Use an external query caching tool such as Redis. 
This can still be used, but I didn't want to introduces more …
> cache system_settings v2

- dojo/finding/views.py
- dojo/product/views.py
- dojo/templates/dojo/product_endpoint_pdf_report.html
- dojo/templates/dojo/product_metrics.html
The product metrics page/tab has been subject of some reported issues lately, mainly around closed/inactive findings not being shown en in general the reported numbers being different from what they see when they click on one of the tiles. (#2130, #2187, questions on slack)
This PR:
- Fixes inactive and closed queries (Closed==mitigated, Inactive==not mitigated but also not active).
- Renames a div for accepted_findings (was called reported_findings)
- Aligns and simplifies the queries for inactive findings in finding/views.py
- Add title/tooltip to explain statuses
This is in initial step for #2215 , but there's lots more todo in future PRs as described in #2215.
> product_metrics: fix and align statuses with views

- dojo/templates/dojo/findings_list.html
- dojo/templates/dojo/view_test.html
fix some pages where the finding.title was not yet truncated causing the remaining columns to fall of the screen.
> improve layout handling of finding title

- dojo/templates/dojo/all_product_findings.html
- dojo/templates/dojo/custom_pdf_report_endpoint_list.html
- dojo/templates/dojo/custom_pdf_report_finding_list.html
- dojo/templates/dojo/endpoint_pdf_report.html
- dojo/templates/dojo/engagement_pdf_report.html
- dojo/templates/dojo/finding_pdf_report.html
- dojo/templates/dojo/metrics.html
- dojo/templates/dojo/product_endpoint_pdf_report.html
- dojo/templates/dojo/product_pdf_report.html
- dojo/templates/dojo/product_type_pdf_report.html
- dojo/templates/dojo/report_endpoints.html
- dojo/templates/dojo/request_endpoint_report.html
- dojo/templates/dojo/request_report.html
- dojo/templates/dojo/simple_search.html
- dojo/templates/dojo/snippets/engagement_list.html
- dojo/templates/dojo/templates.html
- dojo/templates/dojo/test_pdf_report.html
- dojo/templates/dojo/view_eng.html
- dojo/templates/dojo/view_risk.html
in `view_eng.html` we use the django built-in filter `truncatechars`. However currently on `dev` this outputs something like this:
```
<tr>
<td><strong>Commit Hash</strong></td>
<td><em class="t…</td>
</tr>
<tr>
<td><strong>Branch/Tag</strong></td>
<td>develop</td>
</tr>
<tr>
<td><strong>Orchestration</strong></td>
<td>
<em class=" text-muted"="">Not Specified</em>
</td>
</tr>
````
which breaks the html because it opens a `<em>` tag and never closes it.
using django built-in filter `truncatchars_html" must be used
> fix broken html due to invalid truncate

- dojo/tools/nmap/parser.py
Without this bug fix we sometimes got a "Server 500" error when importing nmap scan result xml files (see [stacktrace.log](https://github.com/DefectDojo/django-DefectDojo/files/4528633/stacktrace.log)).
The reason was that the description field could fill up to several hundreds MegaBytes because of the faulty nmap parser. The parser appended wrongly host info by iterating over the wrong xml node ("root" instead of "host"), so the host info within the description became wrongly longer and longer.
We also renamed some variable names in the parser to comply with python naming conventions. Last but not least we reformatted the output of the description for easier reading.
> bugfix nmap parser

- dojo/settings/settings.dist.py
- dojo/tools/clair/parser.py
- dojo/tools/clair_klar/parser.py
This commit fixes an issue where the finding type was defaulting
to "dynamic" for both Clair and Clair_klar parsers. Now DDJ will
be able to properly deduplicate findings based on clair and
clair_klar reports.
- enhancement
- feature
- bugfix
- dependencies
> parser: clair/klar: set finding type to "static"

- docker-compose.override.dev.yml
This PR ensures that the environment variable DD_ADMIN_USER and DD_ADMIN_PASSWORD present at build time are passed on to the initializer for the docker-compose-dev override environment.
This allows users to choose a predicatble admin password (and username) in dev. 
When you are working with different branches / pull requests it's not uncommon to clear containers/images/volumes often, which results in a new random admin password everytime. With this PR it becomes predictable.
The release docker-compose-override still generates a random admin password on initialization.
> docker-compose-dev: allow chosing of admin password

- dojo/templates/dojo/findings_list.html
- dojo/templates/dojo/product.html
- dojo/templatetags/display_tags.py
Same as #2311 , but contains only the fix to disable clientside sorting on initial page load.
> fix default sorting findings and products

- dojo/fixtures/test_type.json
- dojo/forms.py
- dojo/templates/dojo/import_scan_results.html
- dojo/tools/factory.py
- dojo/tools/gitlab_sast/parser.py
- dojo/unittests/scans/gitlab_sast/gl-sast-report-0-vuln.json
- dojo/unittests/scans/gitlab_sast/gl-sast-report-1-vuln.json
- dojo/unittests/scans/gitlab_sast/gl-sast-report-many-vuln.json
- dojo/unittests/test_gitlab_sast_parser.py
Integration for GitLab SAST integrates into GitLab's Continuous Integration and leverages FLOSS scanning tools for the most common languages (<https://docs.gitlab.com/ee/user/application_security/sast/#supported-languages-and-frameworks>). It then reads the results of those tools and creates a report in a common JSON format.
Website: https://docs.gitlab.com/ee/user/application_security/sast/
PR for documentation: https://github.com/DefectDojo/Documentation/pull/84
PR for sample files: https://github.com/DefectDojo/sample-scan-files/pull/49
- N/A Model changes must include the necessary migrations in the dojo/db_migrations folder.
> Add GitLab SAST parser

- dojo/engagement/views.py
- dojo/filters.py
- dojo/finding/views.py
- dojo/middleware.py
- dojo/product/views.py
- dojo/product_type/views.py
- dojo/test/views.py
- dojo/utils.py
there were some places where prefetching wasn't working, resulting in 250+ queries per page.
this PR reorders some queries for accepted findings, false positive findings, out of scope findings.
it also renames 2filters with typo's.
in a future PR we should do some code deduplication here...
> reorder queries to make prefetching work everywhere

- dojo/api_v2/serializers.py
Add email field in APIv2 user endpoint. Requested by @mtesauro 
- enhancement
- feature
- bugfix
- dependencies
> Add email to APIv2 user get request

- dojo/api.py
- dojo/api_v2/serializers.py
- dojo/api_v2/views.py
- dojo/fixtures/dojo_testdata.json
- dojo/unittests/test_rest_framework.py
- dojo/urls.py
Add API v1 and v2 endpoints for managing Nots Types. This was requested by @mtesauro 
- enhancement
- feature
- bugfix
- dependencies
> Add Note Type APIv2 endpoint

- dojo/templates/dojo/apply_finding_template_form_fields.html
As `replace` is the default action taken for tags, this makes the select allowing
to choose the option select `replace` by default. Therefore, it is no longer
necessary to change the value twice if one wants to choose `keep`.
(Previously, "Keep" as first option was selected even though "Replace" was the action performed by default)
> Apply Template to Finding: Use replace as default option for tags

- dojo/engagement/views.py
- dojo/filters.py
- dojo/finding/urls.py
- dojo/finding/views.py
- dojo/metrics/views.py
- dojo/note_type/views.py
- dojo/product/urls.py
- dojo/product/views.py
- dojo/product_type/views.py
- dojo/templates/dojo/findings_list.html
- dojo/test_type/views.py
- tests/Finding_unit_test.py
When listing all the findings and statuses for #2215, I noticed the views in `finding/views.py` that show findings, were basically all the same with some small differences like display name and filter criteria.
This PR deduplicates that:
- Deduplicate code in `finding/views.py`
- Simplify loading of CWE dropdown
- Fix javascript error when displaying findings with/without jira config (fixes #2317)
- Remove `found_by` and `prod_type` code from views, they did nothing and are set by the filter
- Simplify prefetching as we don't need the pagination workaround here due to the queries being simple.
- Define reusable query fragements which define "Open Findings", "Accepted Findings", etc.
- Replace `all_product_findings` by `product_open_findings` as it is the same.
This can be further improved …
> deduplicate code in finding views

- dojo/templates/base.html
I always find myself hovering and clicking on the menubar on the left expecting it open products or finding or whatever. But the user has to hover first, it then opens a submenu and then the user can select and click an item.
This PR adds a link to the menu item in the menu bar itself. The above still works, but for lazy users like me you can just click the item in the menu bar and go to All engagements or all products or open findings etc
> add default actions for main menu

- dojo/filters.py
- dojo/home/views.py
- dojo/metrics/views.py
- dojo/utils.py
Some date fields like `mitigated` and `risk_acceptance_created` are `DateTimeFields`, which results in queries like
SELECT * FROM FINDING WHERE MITIGATED > '2020-04-29 21:18:00'
when you want the findings mitigated in the last 7 days, apart from the fact that this is not what you want, it also prevents propert caching by any query caching module that some people may or will be using (I am running django-cachalot).
By adapting any query filters from `filter(finding__mitigated__range=[start,end])` to 'filter(finding__mitigated__date__range=[start,enf])` it will result in the queries we want
SELECT * FROM FINDING WHERE MITIGATED > '2020-04-29'
I simplified a bit because in reality there will be timezone conversions in the queries as well and an end date.
I also removed the filter 'created' …
> always use __date__range for ranging datetime fields

- dojo/settings/settings.dist.py
- dojo/templates/dojo/findings_list.html
- dojo/templates/dojo/view_test.html
- dojo/templatetags/display_tags.py
I have seen some weird stuff happening when users are merging findings and then the next (re)import comes from jenkins or any other ci tooling.
Sometimes existing findings get closed and the new ones get created, but the new ones are then removed by dedupe. And then when the user had chosen merge and delete initially the findings are gone.
Could be some bugs in the importer, but don't have the time to look into it.
Just added a quick setting to allow sysadmins to disable merging alltogether.
It's in settings.py as I don't want to spend too much time maintaining a database migration for this.
> merge findings: allow setting to disable it

- dojo/api.py
- travis/script.sh
- enhancement
- feature
- bugfix
- dependencies
> Pin Flake8 version in travis, fix other Flake8 violation

- Dockerfile.django
- Dockerfile.nginx
Reverts DefectDojo/django-DefectDojo#2178
It broke the build
> Revert "docker: update to python 3.6"

- dojo/user/views.py
Whenever a session expires or is deleted, or somebody is starting with a clean database, an old browser session will poll for alerts every 5s. This creates exceptions in the logs due to the user no longer being logged in.
Multiply by 50 if you have 50 users ;-)
This PR adds a decorated that requires the user to be logged in to perform the alert_count function. If not logged in, the response is a 302 redirect to the login.
> require login for alert count

- dojo/tools/safety/parser.py
- dojo/unittests/scans/safety/example_report.json
- dojo/unittests/scans/safety/multiple_cves.json
- dojo/unittests/scans/safety/no_cve.json
- dojo/unittests/test_safety_parser.py
Bug fixes for safety parser:
- fixed issue #1754 when cve for finding is `None`
- fixed issue with importing empty file
- set cve to finding's object for safety
> Fix safety parser (Issue #1754)

- dojo/settings/settings.dist.py
- dojo/tools/zap/parser.py
- dojo/unittests/scans/zap/empty_2.9.0.xml
- dojo/unittests/scans/zap/some_2.9.0.xml
- dojo/unittests/test_zap.py
The current dedupe config for ZAP scans is "not unique enough':
`ZAP Scan': ['cwe', 'endpoints', 'severity']`
even our own zap sample contains multiple different findings with the same `cwe` + `endpoints` + `severity`, so we need to include either the `name` or `pluginid` or `alert` fields.
https://github.com/DefectDojo/django-DefectDojo/blob/dev/tests/zap_sample.xml
Only the `name` field is available in defect dojo and it is stored in the `title` field, so unfortunately we have to include the `title` field`
Also add unittests for the zap parser as they were missing (just basic tests as any other parser, not dedupe or anything).
> zap parser: add title to dedupe fields + unittests

- dojo/static/dojo/js/index.js
When importing a scan via the UI, a datepicker pops up right in your face.
I think it would be nicer to only open it when users click on the datefield that belongs to it.
> import scan ui: don't open datepicker by default

- dojo/static/dojo/css/dojo.css
The content of the popovers in Benchmarks page was not visible. 
**Before**
**After**
> Fixing visibility of popover content in Benchmarks page

- dojo/templates/dojo/view_product_details.html
Updating to **0% Complete** as the default value for Benchmark progress instead of just **Complete**
**Before**
**After**
> More descriptive Benchmark progress bar

- dojo/finding/views.py
- dojo/github.py
- dojo/templates/dojo/edit_finding.html
- dojo/templates/dojo/findings_list.html
Addresses https://github.com/DefectDojo/django-DefectDojo/issues/2351
Also aligns case to `GitHub` in cases that I could see show on screen.
fyi @mestrade
> Do not show "push to github" if no product config set

- .dependabot/config.yml
- .github/workflows/plantuml.yml
- DOCKER.md
- README.md
- helm/defectdojo/values.yaml
- setup/postgresql.txt
In the new (git flow based) branching/release model, our branches should never be behind master. At least not for a long time or for many commits.
Currently `dev` and also `release/1.6.0` are 62 commits behind. This PR resolves that for the `release/1.6.0` branch. After the release, the release branch will be merged to `master`, but also to `dev` as per git flow and the plantuml diagram by @madchap 
The step in this PR is only needed one-time because in the past we didn't have a clear branching/releasing model.
Does this make sense?
> Merge master into release 1.6.0

- dojo/engagement/views.py
- dojo/models.py
- dojo/notifications/helper.py
- dojo/user/views.py
Add a check to avoid exceptions for users created without usercontactinfo (i.e. via /admin, or manage.py createsuper).
> make notifications work with users created without usercontactinfo

- dojo/tools/dependency_check/parser.py
the field from which we parse the CVE does not always contain a CVE, so we check have to check that before setting CVE, otherwise we get garbage in the cve field in DD.
> dependency check parser: only set cve when available

- components/package.json
- components/yarn.lock
- dojo/finding/views.py
- dojo/models.py
- dojo/templates/dojo/view_finding.html
Bugfix:
- The field `duplicate_finding_id` was recently removed in the dedupe fields overhaul, braking the showing of buttons for similar findings to mark them as duplicate (or ofiginal).
Enhancements:
- Not only show similar findings, but also show identical findings based on hash_code within the same product. This shows you on which engagement (branch) a finding is also seen. 
- With dedupe on engagement enabled, the buttons for marking as duplicate in this case won't work as there is a server side check to prevent this from completing.
- Hiding the buttons from the template is too much hassle as you need to expose certain functions from the views as template tags. Or just copy and paste code into the html template.
- Also improved the layout a bit to make it more readable.
I'm …
> similar findings: fix bug and extend with identical issues

- docker/entrypoint-integration-tests.sh
- dojo/templates/dojo/engagement.html
- dojo/templates/dojo/engagements_all.html
- dojo/templates/dojo/findings_list.html
- dojo/templates/dojo/product.html
- tests/Endpoint_unit_test.py
- tests/Engagement_unit_test.py
- tests/Environment_unit_test.py
- tests/Finding_unit_test.py
- tests/Import_scanner_unit_test.py
- tests/Note_type_unit_test.py
- tests/Product_type_unit_test.py
- tests/Product_unit_test.py
- tests/Test_unit_test.py
- tests/User_unit_test.py
- tests/base_test_class.py
- tests/check_status.py
- tests/dedupe_unit_test.py
- tests/ibm_appscan_test.py
- tests/local-integration-tests.bat
- tests/local-integration-tests.sh
- tests/smoke_test.py
- travis/integration_test-script.sh
Turns out the chrome update to 83 somehow broke our integration tests in some ways. Sometimes they work, sometimes they don't. This PR tries to eliminate race conditions / timing issues:
- findings_list uses datatables, we have to wait for it to be initialized before accessing the page. Same as we did for products/engagements.
- there are 88 checks in the tests where we match the `.text` value of the whole `body` with an expected string. this no longer works as the body keeps changing due to javascript events. we could have maybe used an explicit wait everytime, but that feels clunky and is slow. so I rewrote some stuff. Still in some places it is looking for the body as I can't get all xpath `text()` examples to work in our setup.
Every time I use selenium it feels clunky and even the …
> integration tests: wait for findings list to load

- dojo/tools/gosec/parser.py
This PR just remove unused/unnecessary variables in the Gosec parser.
Some static strings have been removed because they don't have value and take space in the DB.
- enhancement
> Cleaning Gosec parser code

- dojo/api_v2/views.py
- dojo/reports/views.py
**Steps to reproduce**
Steps to reproduce the behavior:
1. Create a new Product Type
2. In the Product Type List page, click on Report button (next to "Edit Product Type")
**Expected behavior**
User should be taken to Generate Product Type Report page.
**Traceback** (optional)
```
Traceback:
File "/usr/local/lib/python3.5/site-packages/django/core/handlers/exception.py" in inner
34.             response = get_response(request)
File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py" in _get_response
115.                 response = self.process_exception_by_middleware(e, request)
File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py" in _get_response
113.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)
File …
```
> Fixing Product Type Report error when there are no findings

- components/package.json
- components/yarn.lock
- dojo/templates/dojo/ad_hoc_findings.html
- dojo/templates/dojo/add_findings.html
- dojo/templates/dojo/add_template.html
- dojo/templates/dojo/apply_finding_template.html
- dojo/templates/dojo/edit_finding.html
- dojo/templates/dojo/edit_presets.html
- dojo/templates/dojo/edit_product.html
- dojo/templates/dojo/import_scan_results.html
- dojo/templates/dojo/merge_findings.html
- dojo/templates/dojo/new_eng.html
- dojo/templates/dojo/new_params.html
- dojo/templates/dojo/new_product.html
- dojo/templates/dojo/promote_to_finding.html
SimpleMDE hasn't been updated in [4 years.](https://github.com/sparksuite/simplemde-markdown-editor/commit/6abda7ab68cc20f4aca870eb243747951b90ab04) 
[EasyMDE ](https://github.com/Ionaru/easy-markdown-editor)is the most popular and active fork of SimpleMDE. 
This _should_ fix #2410 now that we have `spellChecker` set to false.
> Replaced SimpleMDE with EasyMDE

- docker-compose.override.dev.yml
- docker-compose.override.ptvsd.yml
- nginx/nginx.conf
Partial fix for #2045, makes finding images work in docker development setup.
Making it work in release mode will have to wait until @devGregA has finalized the migration to AppVeyor.
> make finding images work in docker dev and ptvsd setup

- dojo/models.py
- dojo/notifications/helper.py
- dojo/tasks.py
There were some issues with notifications / alerts after the revamp earlier:
- alerts were not created for staff/admin users
- ~~alerts were failing for product_added notifications~~ already fixed in #2412
> fix alerts for product_added, and more

- dojo/tools/npm_audit/parser.py
- dojo/unittests/scans/npm_audit_sample/empty_with_error.json
- dojo/unittests/test_npm_audit_scan_parser.py
fixes #2220
this PR makes sure that if an error element is present in de npm audit report, the import will fail / stop.
the error indicates the audit was unsuccesful and we should not continue.
currently the import continues and thinks there are no vulnerabilities so it closes any existing findings in defect dojo :-)
it also sets component_name and component_version, as those were not yet set.
I'm dogfooding this.
> npm audit parser: fixes

- dojo/utils.py
This change makes sure that if a finding has been seen before, the history will be marked as verified.
> False positive history: Recognized false positives marked as verified

- dojo/__init__.py
- setup.py
When releasing `1.6.1`, version numbers were not updated. The version number in `setup.py` wasn't updated since `1.5.4`.
> fix version numbers missed in 1.6.1

- dojo/api_v2/views.py
Looking to leverage the unique_id_from_tool field to find specific Findings via the API. Would love to get this merged in sometime.
> added unique_id_from_tool filter to APIv2 when retrieving findings

- dojo/jira_link/views.py
This is a fix for bug 2501.
The current version version fo DDJ uses the existence of an "issue" key in the JIRA webhook to determine if a webhook request is an update to the state of the ticket or a new comment.  The current version of JIRA may include an "issue" key for comment update.  This breaks the current classification method.  
https://developer.atlassian.com/server/jira/platform/webhooks/#executing-a-webhook
JIRA provides a key-value ("webhookEvent") to determine the type of message that is being sent.  
**Note: DefectDojo is now on Python3.5 and Django 2.2.x Please submit your pull requests to the 'dev' branch as the 'legacy-python2.7' branch is only for bug fixes. Any new features …
> Fix JIRA webhook event type compares

- helm/defectdojo/values.yaml
This PR adds a hint to the helm `values.yaml` about how to fix Gateway Timeouts that frequently happened in our setup during dependency-scan uploads with a default nginx-ingress configuration.
Labels:
enhancement
> k8s: Add hint about preventing gateway timeouts

- dojo/models.py
This will fix issue #2485
When creating an ad-hoc finding against a project, the product/view.py calls the model.py Finding.save() twice.  The findings save then creates multiple issues in JIRA.  I got this fix from Apipia and tested it in my environment.
> Fix duplicate issues create in JIRA when creating an ad-hoc finding

- dojo/tools/qualys/parser.py
- dojo/tools/qualys_webapp/parser.py
As discussed on H1,
this PR disable XXE when parsing Qualys reports.
PS: this vulnerability was automatically found by [SonarQube](https://www.sonarqube.org/)/[SonarCloud](https://sonarcloud.io/)/[SonarLint](https://www.sonarlint.org/) products during our work to improve [XXE vulnerabilities detection](https://jira.sonarsource.com/browse/RSPEC-2755) for Python.
Eric
> Disable XXE when parsing Qualys reports

- dojo/api_v2/serializers.py
- dojo/engagement/views.py
- dojo/settings/settings.dist.py
- dojo/test/views.py
- dojo/utils.py
Add a check in the scan report import and re-import APIs which verifies iif the scan report size is below a pre-defined maximum size when the data is validated by the serializer.
fixes #2346 
cc @madchap 
Signed-off-by: Cosmin Cojocar <cosmin.cojocar@gmx.ch>
- enhancement
- performance
- …
>  Check the size of the scan report when is imported through API

- dojo/notifications/helper.py
- dojo/utils.py
fixes #2564
- change exotic use of `user` into `initiator` when sending notifications for mentioning a user
- don't send notifications to all admins if specific recipients are selected
- fix notification settings handling for users that are mentioned
> mentioning a user: fix notifications

- dojo/api_v2/serializers.py
- tests/Finding_unit_test.py
- tests/Product_unit_test.py
- tests/base_test_class.py
- tests/dedupe_unit_test.py
As seen in #2370 sometimes exceptions occur in background (celery) processes. By running some integration tests (also) with `block_execution` enabled, everything will run synchronously in the django/uwsgi process.This allows us to catch some of these exceptions in the integration testsuite.
> run some Integration tests with block execution = true

- helm/defectdojo/templates/initializer-job.yaml
- helm/defectdojo/values.yaml
add missing affinity for the initializer, plus a couple of affinity/nodeselector templates in the values.yaml
> kubernetes: add missing affinity

- .travis.yml
- tests/base_test_class.py
- tests/dedupe_unit_test.py
- travis/script.sh
Currently there are 2 travis steps doing almost exactly the same:
`docker` | `integration tests`
---------|--------------------
build containers | build containers
start containers | start containers
check if defect dojo is running | check if defect dojo is running
_ | perform integration test suite 
This PR merges these 2 steps to make it more efficient and not burn too many trees with our testsuite.
I noticed there are two ways to build the containers right now in the travis scripts, but since we're moving away from travis I didn't want to spend time there to see which one is best.
> travis: merge docker step with integration tests step

- dojo/jira_link/views.py
- dojo/models.py
- dojo/utils.py
This PR improves few things related to notes:
- Private notes are not exported to Jira (change discussed on Slack)
- Jira configuration name is added to dropdown in product settings. This adds more context to the Jira configuration selection when a single Jira user is used across several Jira boards/configurations
- Jira notifications in DD are updated to use the Jira configuration name instead of the Jira URL. Using the Jira URL is confusing if we have several configuration using the same Jira host.
- enhancement
> Notes improvements (UI and Jira integration)

- travis/integration_test-script.sh
Sometimes erros occur in the celery worker but our current tests suite doesn't see these and ignores them. This could make the travis builds be "false positively green". This PR checks the celery worker logs for ERRORs after each integration test, and fails if ERRORs are found.
This PR will also make sure the tests keep running even if one of them fails. This allows for a complete overview of all failures in 1 travis run instead of needing multiple runs if there are multiple issues.
> integration tests: grep celery work logs for ERRORs

- dojo/api_v2/views.py
This makes it possible to filter the /findings APIv2 endpoint by `is_Mitigated` status. 
This will output only findings that are not "mitigated": 
`&is_Mitigated=0`
I have left the `mitigated` filter just in case, altough it's probably a typo (it's the date of mitigation, not the mitigated status) .
> API V2: add the possibility to filter by "is_Mitigated" status

- dojo/context_processors.py
- dojo/settings/settings.dist.py
- dojo/templates/dojo/login.html
- dojo/urls.py
- requirements.txt
Copy of #2573 due to hastily deletion of old branch.
Adds a plugin that makes SAML2 authentication setup very similar to the OAuth suite currently in place.
[Documentation](https://github.com/DefectDojo/Documentation/pull/102)
> Add SAML2 support

- dojo/api.py
- dojo/api_v2/serializers.py
- dojo/engagement/views.py
- dojo/test/views.py
In an instance when using a scanner that does not require a file, such as the SonarQube API importer, an exception is thrown when trying to retrieve the file from the request. While it does not inhibit the UI, it is still annoying to see in the logs.
```
Jun 23 23:04:58 ip-172-31-26-104 dojo[13105]: Internal Server Error: /test/59/re_import_scan_results
Jun 23 23:04:58 ip-172-31-26-104 dojo[13105]: Traceback (most recent call last):
Jun 23 23:04:58 ip-172-31-26-104 dojo[13105]:   File "/opt/dojo/lib/python3.6/site-packages/django/utils/datastructures.py", line 78, in __getitem__
Jun 23 23:04:58 ip-172-31-26-104 dojo[13105]:     list_ = super().__getitem__(key)
Jun 23 23:04:58 ip-172-31-26-104 dojo[13105]: KeyError: 'file'
Jun 23 23:04:58 ip-172-31-26-104 dojo[13105]: During handling of …
```
> Exception preventing in (re)import-scan

- dojo/models.py
- dojo/search/views.py
This PR fixes some issues with the simple search and includes some enhancements:
Fixes:
- Workaround to be able to search for CVE (see #1092 #2081)
- Allow search by finding id (i.e. for those seeing a JIRA issue with a Defect Dojo id in it)
Enhancements:
- Add fields to indexing to allow them to search them:
```
'id', 'title', 'cve', 'url', 'severity', 'description', 'mitigation', 'impact', 'steps_to_reproduce',
'severity_justification', 'references', 'sourcefilepath', 'sourcefile', 'hash_code', 'file_path',
'component_name', 'component_version', 'unique_id_from_tool'
```
Because this PR updates the django-watson config for the `Finding` model, a index rebuild is needed. I thought about adding the rebuild as a migration. But that could lead to seriously long migrations for larger …
> Search by CVE and index extra fields

- dojo/finding/views.py
- dojo/templates/dojo/view_test.html
- dojo/test/views.py
Fixes #2623 and another missing prefetch when viewing a list of findings with 1 or more endpoints
> jira issue and endpoints prefetching fixes

- docker/entrypoint-uwsgi-dev.sh
- dojo/api_v2/serializers.py
- dojo/api_v2/views.py
- dojo/fixtures/dojo_testdata.json
- dojo/forms.py
- dojo/product/urls.py
- dojo/product/views.py
- dojo/templates/base.html
- dojo/templates/dojo/new_tech.html
- dojo/templates/dojo/view_product_details.html
- dojo/unittests/test_rest_framework.py
- dojo/urls.py
Supersedes #2309 
Previously, managing technologies (renamed from app_analysis) was only accessible through APIv1. Now, they can also be managed through the UI on the product page or APIv2. This was requested by @mtesauro
Docker-compose dev config also has a change to reduce wait times in auto reloading for processes to be killed off. Instead of the default 60 seconds, processes will now be killed after 1 seconds.
> Add Technology (App Analysis) management via UI and APIv2

- dojo/finding/views.py
- dojo/forms.py
- dojo/github.py
- dojo/models.py
- dojo/product/views.py
- dojo/templates/dojo/edit_finding.html
- dojo/templates/dojo/view_finding.html
- dojo/test/views.py
- dojo/utils.py
bugfixes:
- bulk edit with push to github: create github issue instead of JIRA issue
improvements:
- set `duedate` field based on SLA targets when creating JIRA issue and if SLA is enabled in DD
- display jira issue + url in  edit_finding
- display github issue + url in  edit_finding (fixes #2607)
- simplify displaying of jira_issue and github_issue in view_finding
- send full url to DD finding to JIRA / GitHub instead of only finding id
- send labels to JIRA in the same call as creating/updating an issue
maintenance
- if a user has set `block_execution` set to True in their profile, the JIRA/GitHub actions will now run in uwsgi and not in celery. (similar to what happens with dedupe, notifications etc)
- simplify code around accessing jira/github issue and configuration in view/edit …
> JIRA/github improvements and fixes July 2020

- dojo/models.py
For some reason sometimes the `usercontactinfo` doesn't exist for some users in a clean instance, so made the code a bit more safe.
> jira hotfix when no usercontactinfo for reporter

- dojo/finding/views.py
- dojo/utils.py
Setting duedate field based on SLA in #2630 breaks JIRA integration if the `duedate` field is not available for that JIRA project + issuetype.
This PR retrieves metadata from JIRA and only sets `duedate` field when possible.
Now that we have the metadata anyway, we also set the environment field to contain the list of endpoints for the finding if possible.
> jira: only set duedate when field is available in jira

- .github/ISSUE_TEMPLATE/bug_report.md
The current git command in the bug report template doesn't output the branch the user is on. So it's not always clear if the user is on `master` or `dev` or maybe something like `1.6.5`.
New command:
```
(venv_dd) valentijn@LAP$ git show -s --format="[%ci] %h: %s [%d]"
[2020-07-08 15:48:13 +0200] b4e3faa8: bug report template: better git cmd [ (HEAD -> bug-report-template, origin/bug-report-template)]
```
> bug report template: better git cmd

- dojo/templates/dojo/import_scan_results.html
Follow-up to https://github.com/DefectDojo/django-DefectDojo/pull/2626
> In-page doc for twistlock now accepting CSV as input

- dojo/endpoint/views.py
- dojo/product/views.py
- dojo/templates/dojo/edit_product_meta_data.html
Removing Product/Endpoint metadata was secretive such that leaving the field empty would remove the item. There was no mention of this anywhere. To make is more usable, a checkbox is added to make it clearly removable and done so in bulk.
> Add obvious way to delete metadata in UI

- docker/entrypoint-uwsgi-dev.sh
- docker/entrypoint-uwsgi-ptvsd.sh
- docker/entrypoint-uwsgi.sh
This commit adds a variable DD_UWSGI_BUFFER_SIZE to set the USWGI buffer-size, so it'll then be possible to set a custom buffer-size as the default one is very small (4096 Bytes) and can cause issue with large cookies.
> uwsgi: add variable to configure the buffer-size

- dojo/tools/gitleaks/parser.py
TLDR: _After using the current version of the Gitleaks parser (that I developed) in production for quite some time, I realized that the deduplication algorithm was too strict and not efficient._
The current version reports (almost) every single instance of a secret across all files and commits, etc. which means secrets related findings are duplicated many times. When a secret is identified in source code, it should be considered as leaked and it's better to use DD to do a proper deduplication job and return 1 unique finding/secret than dozen of findings/secrets that will need more engineering time to triage.
This new update to the deduplication algorithm will reduce the number of findings to 1 per actual secret which I think is the best way to handle this particular use case.
Current …
> Update to Gitleak deduplication algorithm

- dojo/tools/generic/parser.py
- dojo/unittests/test_generic_finding_upload.py
Previously, the parser looked for the active and verified columns twice:
First, by looking for such column names and, secondly, by checking
column number 9 and 10 (which are fixed).  This PR removes the
latter part.
> Fix generic parser

- helm/defectdojo/Chart.yaml
- helm/defectdojo/templates/celery-beat-deployment.yaml
- helm/defectdojo/templates/celery-worker-deployment.yaml
- helm/defectdojo/templates/configmap.yaml
- helm/defectdojo/templates/django-deployment.yaml
- helm/defectdojo/templates/initializer-job.yaml
- helm/defectdojo/templates/sa.yaml
- helm/defectdojo/templates/secret-mysql.yaml
- helm/defectdojo/templates/secret-postgresql.yaml
- helm/defectdojo/templates/secret-rabbitmq.yaml
- helm/defectdojo/templates/secret-redis.yaml
- helm/defectdojo/templates/secret.yaml
- helm/defectdojo/templates/tests/unit-tests.yaml
- helm/defectdojo/values.yaml
The following improvements are made to the helm chart:
- create a dedicated service account for all pods created by defectdojo and allows custom annotations (e.g. this is useful for workload identity)
- add support for cloudsql-proxy which is deployed as a side car container in all Pods which needs to connect to DB
- extend the mysql and postgresql secrets to allow to inject a user password via a helm value when the in-cluster DB is not used (e.g. useful for an external cloud hosted DB)
- change the deployments to use the same secret for DB password instead of expecting secrets to be created outside of the helm chart
- fix the celery host in the configmap
- increase the chart version to 1.1.0
Signed-off-by: Cosmin Cojocar <cosmin.cojocar@gmx.ch>
When submitting a pull request, please make …
> Improve the helm chart and add support for cloudsql-proxy

- PULL_REQUEST_TEMPLATE.md
- dojo/db_migrations/0048_create_endpoint_status.py
* After the upgrade to 1.7.0, endpoints on a finding were no longer displayed in the UI. This is because an Endpoint_Status object had not been created for the endpoint/finding pair. This migration will create and Endpoint_Status object for each Endpoint associated with a Finding. 
* Fix typo in PR template that I just now noticed :)
> Add migration to create endpoint_status objects

- dojo/templates/dojo/edit_rule.html
- dojo/templates/dojo/endpoints.html
- dojo/templates/dojo/findings_list.html
- dojo/templates/dojo/new_rule.html
- dojo/templates/dojo/view_endpoint.html
- dojo/templates/dojo/view_eng.html
- dojo/templates/dojo/view_engagements.html
- dojo/templates/dojo/view_finding.html
- dojo/templates/dojo/view_product_details.html
- dojo/templates/dojo/view_test.html
- popovers were broken on `view_test` page (fixes #2631)
- extracted `tooltip` and `popover` javascript calls into `base.html`
- moved the `notes` icon from the JIRA column to the title column
- improved styling of notes icon and number of notes displayment
- some small js / whitespace changes here and there
> fix popovers in view_test and improve js overall

- dojo/api_v2/serializers.py
- dojo/cred/views.py
- dojo/engagement/views.py
- dojo/finding/views.py
- dojo/forms.py
- dojo/github_issue_link/views.py
- dojo/management/commands/push_to_jira_update.py
- dojo/models.py
- dojo/notifications/helper.py
- dojo/object/parser.py
- dojo/product/views.py
- dojo/rules/views.py
- dojo/tag/prefetching_tag_descriptor.py
- dojo/tasks.py
- dojo/test/views.py
- dojo/tools/acunetix/parser.py
- dojo/tools/aws_prowler/parser.py
- dojo/tools/aws_scout2/parser.py
- dojo/tools/dependency_check/parser.py
- dojo/tools/outpost24/parser.py
- dojo/tools/php_symfony_security_check/parser.py
- dojo/tools/qualys/parser.py
- dojo/tools/qualys_infrascan_webgui/parser.py
- dojo/tools/twistlock/parser.py
- dojo/tools/whitesource/parser.py
- dojo/unittests/test_notifications.py
- dojo/unittests/test_taggit_tags.py
- dojo/user/helper.py
- dojo/utils.py
- bugfix on `edit_engagement`
- set note author to be `jira` after pushing/linking to JIRA issue instead of `finding.reporter`. This is not perfect, but in celery we don't have the request object so we don't know who is actually pushing it.
- rename `add_issue` and `update_issue` in utils to more explicit `add_jira_issue` and `update_jira_issue`
- cleanup left over print/log statements from #2649 
- cleanup other print/log statements because they are not my favourite
> JIRA: small bugfixes, improvements and cleanup

- dojo/tools/sonarqube_api/api_client.py
While I was configuring the DefectDojo integration with SonarQube API, I came across the following problem, Sonarqube was returning StatusCode 403, after researching a bit, I found that error occurred because sonarqube was behind a WAF that did not accept requests without user-agent, I made this small change that solved my problem!
> Added user-agent in sonarqube api requests

- dojo/api_v2/serializers.py
- dojo/api_v2/views.py
- dojo/fixtures/dojo_testdata.json
- dojo/unittests/test_rest_framework.py
- dojo/urls.py
Add the ability to attach sonarqube tool configs to a product, manage issues, and issue transitions.
> Add Sonarqube integration endpoints to APIv2

- .gitignore
- dojo/tools/burp_enterprise/parser.py
Improve Burp Enterprise parser to correctly import the correct amount of findings, include multiple endpoints on a single finding, and deduplicate description fields.
Since it hasn't been done before, I've added survey fixtures to the gitignore list. Every time fixtures are loaded, the fixtures file needs to be updated to accommodate to polymorphic id before being loaded. Now it will never be seen as a modified file. 
- [] If this is a new feature and not a bug fix, you've included the proper documentation in the ReadTheDocs documentation folder. https://github.com/DefectDojo/Documentation/tree/master/docs or provide feature documentation in the PR.
> Improve Burp Enterprise parser and update gitignore

- dojo/models.py
This commit fixes an issue with Jira when using the PATCH method on the api_v2. It's now possible to send only ```{"push_to_jira": "True"}``` on a certain finding without repushing all the fields like we would do with a PUT or a POST.
I've tested the patch and it doesn't break the push_to_jira mechanism from the web-interface.
I'll also send a PR later to simplify the logic to avoid that kind of hack -> https://github.com/DefectDojo/django-DefectDojo/blob/master/dojo/api_v2/serializers.py#L482 (re-creating an a temporary object to enrich it....).
> api_v2: fix push_to_jira when using the PATCH method

- dojo/api_v2/views.py
This commit fixes an issue where notes were not pushed to Jira when they were created from the API_V2.
> api_v2: fix push notes to Jira

- dojo/tools/npm_audit/parser.py
- dojo/unittests/scans/npm_audit_sample/many_vuln.json
recently the npm published a advisory without a CWE. Instead of using an empty/null value for the CWE field, they have set it to `CWE-`. The npm audit parser chokes on that. This PR fixes that. 
In the future we should ook at extracting some common / shared logic for parsers: #2808
> npm audit parser: fix cve parsing

- dojo/settings/settings.dist.py
- dojo/tools/trivy/parser.py
- dojo/unittests/scans/trivy/trivy_mix.json
- dojo/unittests/test_trivy_parser.py
Fixes bug #2824 
When importing trivy scans:
- Adds missing cwe to the extracted fields
- Adds the type (npm, pip, cargo, debian, alpine, etc) to the description
- Adds missing component_name, component_version fields
- Sets finding as a static_finding
It also updates the settings so deduplication works with findings imported from trivy scans.
labels:
bugfix
settings_changes
> BUG-2824, add missing trivy finding fields and settings for deduplication

- dojo/templates/dojo/simple_search.html
I found out that if you delete findings from Defect Dojo, they remain behind in the watson search index. 
It might work if findings are deleted via DD because it will use pre delete signal. But sometimes people cleanup via database queries and run `buildwatson` to rebuild the index. however even after running `buildwatson` to rebuild the index, the search entries remain. So we have to check if objects connected to searchentries still exist before trying to render them to prevent the template from crashing with a 500 error.
I've asked django-watson for info: https://github.com/etianen/django-watson/issues/276
The PR basically adds some ifs here and there, but also some indentation changes it seems.
> Search fix watson references to deleted findings

- dojo/finding/views.py
- dojo/forms.py
- dojo/templates/dojo/edit_finding.html
- dojo/templates/dojo/finding_related_row.html
The parent duplicate status + dropdown on the edit finding page has two (breaking) issues:
1) When the page is loaded, the first findingin the dropdown is selected. So when quickly editing a finding to change a field and pressing save leads to the parent/original finding being changed silently
2) On the view finding page duplication can be managed and the finding can be marked as a finding that will not occur on the dropdown above. Basically meaning the finding can no longer be edited without breaking the duplicate relationship.
Solutions:
A) Add the similar finding filtering stuff also to the edit finding page. Could be done but would require either a long dropdown, or some ajaxy filtering and tables.
Feel free to add that, but for now that's too much work. Especially because all the …
> edit finding: fix parent/original duplicate + small fixes

- dojo/finding/views.py
- dojo/forms.py
- dojo/product/views.py
- dojo/test/views.py
Add the ability to add and edit request and response pairs in the UI
Requested by @mtesauro
> Add request_response pairs to the UI

- helm/defectdojo/Chart.yaml
- Bump chart to 1.3.0 due to the most recent changes brought about by PR #2847
- Bump defectdojo app version to latest released one, 1.7.1.
> Bump helm chart versions

- dojo/tools/nessus/parser.py
Added a field within the Nessus XML Scanner for cve's so now you can import nessus reports by .xml files. This partially fixes issue #2762 Since the issue reporter never responded to the query for a sample csv file, I cannot test importing nessus reports using .csv type, only .xml type.
> Fixed cve field showing None when importing nessus .xml reports

- dojo/templates/dojo/engagements_all.html
Added couple parameters for the Django date pipeline in the engagements_all html code. This fixes issue #2661
> Fixed dates sorted alphabetically

- dojo/api_v2/serializers.py
- dojo/settings/settings.dist.py
- dojo/test/views.py
- dojo/tools/dependency_check/parser.py
- dojo/tools/php_symfony_security_check/parser.py
- dojo/unittests/test_dependency_check_parser.py
- dojo/unittests/test_php_symfony_security_check_parser.py
- requirements.txt
me: "Let me quickly add some code to set `component_name` and `component_version` for some scanners".
10 hours later:
This PR:
- set component name + version for php symfony checker
- set component name + version for owasp dependency checker
- set component name + version for existing findings on reimport scan
update:
This week v6.0.0 from owasp dependency check was released which changed some things. They are backwards compatible, although some optional fields are now only available in a newer format / differently named xml tags.
I have updated the PR to reflect this, i.e. it will handle identifiers like:
```
<identifiers>
<identifier type="cpe" confidence="HIGHEST">
<name>cpe:/a:apache:xalan-java:2.7.1</name>
<url>https://web.nvd.nist.gov/view/vuln/search-results?adv_search=true&amp;cves …
```
> Set component name/version for php symfony & dependency check parsers

- dojo/api_v2/views.py
- dojo/filters.py
This PR is the second in a seri (https://github.com/DefectDojo/django-DefectDojo/pull/2717) to improve DDJ APIv2. As of today the `/products` api endpoint does not support:
* multiple values for the same key
* ordering
* partial text-string search
With this PR we will be able to query most of the fields of the `products` endpoint, except a few ones that are not relevant, and we'll be able to do sorting on the most relevant ones. We'll also be able to do test-string search on strings fields.
> apiv2: fix multi-value and sorting on /products

- dojo/tools/sonarqube_api/importer.py
The length of it is limited. Prevent MySQLdb._exceptions.DataError: (1406, "Data too long for column 'title' at row 1").
> Bugfixing when the title of a vulnerability is more than 511 characters in SonarQube API

- dojo/api_v2/serializers.py
- dojo/finding/views.py
- dojo/templates/dojo/findings_list.html
- dojo/templates/dojo/snippets/endpoints.html
- dojo/templates/dojo/view_test.html
- dojo/templatetags/get_endpoint_status.py
- dojo/test/views.py
Add visual representation of how many endpoint status objects are attached to each finding
> Quantify endpoint status objects when viewing findings

- dojo/db_migrations/0042_risk_acceptance_improvements.py
With existing risk acceptances in the database I got some error when running the migrations: psycopg2.errors.NotNullViolation: column "name" contains null values
Setting the default value to a dummy string instead of None fixes this error. Should not have any impact on current installations because the field is renamed by the following instruction anyway.
> bugfix for risk acceptance migration

- dojo/tools/veracode/parser.py
- dojo/unittests/scans/veracode/many_findings.xml
- dojo/unittests/scans/veracode/one_finding.xml
- dojo/unittests/test_veracode_parser.py
The veracode parser didn't fully work: false positives didn't get detected as such.
Since we're just using the 'detailed XML report's from veracode, it seems their structure was changed a bit (or it never actually worked).
In any case, I decided to refactor the whole parser, split some code, got rid of some deeply nested loops (using xpath) etc.
On the fly, some more details (loc, sast-source) were added to the report.
In addition, as veracode now produces SCA findings in that same report, I added parsing for that as well:
As for a unit test: there wasn't one, and I didn't add one, since I have already been spending quite some of my clients time on this.
Manually tested cases:
-   import a fresh report with both SAST and SCA findings from veracode: all findings imported with correct data …
> Veracode import: fixed false-positives and added SCA findings

- dojo/api_v2/serializers.py
- dojo/api_v2/views.py
- dojo/unittests/test_rest_framework.py
Add a `post` function to APIv2 that creates users.
> Add user post endpoint to APIv2

- .github/workflows/flake8-your-pr.yml
I wanted to do some testing with GitHub Actions, as they are now free for public repositories.
The idea: "Let me quickly add a flake8 action/check"
Reality: There are N different actions all doing something with flake8 on PRs. None of them did what I wanted, or were failing in some way with errors.
Solution: As any real developer, I created the N+1-th flake8 GitHub action :-D
Honestly I just forked an existing one, but made it work better. Some of the others were posting all the flake8 violations as comments on the PR. But that was cluttering too much, so this one annotates the source code in the "Files Changed" tab.
So you can see exactly where the violations are. The annotations will just dissappear when they are fixed. See example image below.
I didn't make this GitHub action a …
> add flake8 check as github action

- renovate.json
I had to make some tests/changes to the renovate config directly on master. Merging them "back" into dev to get in sync again and not getting surprised at the next release.
> sync renovate config from master

- docker/entrypoint-unit-tests-devDocker.sh
- dojo/api_v2/serializers.py
- dojo/api_v2/views.py
- dojo/models.py
- dojo/unittests/test_rest_framework.py
Fixes #2948 
When adding jira_push_all and push_to_jira to the api, there was a bug introduced by passing on the push_to_jira as a model field instead of a parameter. This had no downside yet for us, until in #2801 code was added that was trying to use this field to fix another bug where push_to_jira wasn't passed for PATCH (update) requests. That caused loops to occur:
findings.save -> update_jira_issue -> finding.save -> update_jira_issue -> finding.save -> ... (#2948)
This PR fixes this by:
- reverting the changes in #2801 
- fixing the original bug in the serializer.update()
According to the django docs the current of handling push_to_jira in the api is not how it was envisioned, and a get_serializer_context should be used. But that had other side effects when I tried it. So I decided …
> jira: fix looping when pushing from api

- dojo/settings/settings.dist.py
- dojo/tools/veracode/parser.py
I added the use of `unique_id_from_tool` during import, so that deduplication can be much more effective.
We had problems since the description-field was part of the hashing, but it changed sometimes, for example when a component has the version in it's name, highly dependent on how teams implement their CI/CD.
For SAST findings, we rely now on the app_id and issue_id from the report.
For SCA, it's vendor, library and version.
edit: Also moved the variable stuff (that component name) and veracode issue id to the references section, which should keep the description field a bit more static.
> Veracode: use unique_id_from_tool (fixed deduplication issues)

- README.md
Add info on how to fetch initial credentials inside the quick-start guide on the README.
> doc: add credentials tips into quick-start

- dojo/apps.py
restore `id`, `url` and `unique_id_from_tool` as indexable fields in watson. this allows for search by finding id, i.e.
`finding:1234`
needs an index rebuild, docs: https://github.com/DefectDojo/Documentation/pull/138
> search: restore missing index fields

- dojo/tools/zap/parser.py
#2284 
ZAP Parser:
* disabled fqdn to ip resolving;
* changed main endpoint visualization from IPport to scheme://fqdn:port
> ZAP parser: do not resolve hostname to IP address during endpoint creation (#2284)

- .gitignore
- Dockerfile.django
- docker/certs/readme.txt
When building Dockerfile.django with DOCKER_BUILDKIT=1 option in docker, the build fails with:
failed to solve with frontend dockerfile.v0: failed to build LLB: lstat /var/lib/docker/tmp/buildkit-mount548069851/certs: no such file or directory
> Don't copy inexistent certs folder in Dockerfile.django

- dojo/api_v2/serializers.py
Create endpoint status objects from APIv2. This feature was missing from 1.7.0 and was just discovered in 1.8.0 due to some updated displays surrounding endpoint status objects.
> Fix APIv2 Endpoint Status bug

- dojo/api_v2/views.py
**- bugfix: to #2992  latest "release/1.8.0" master**
If in doubt you can use dev branch, it will just roll-out later. 
> Bugfix: Authorized User only gets findings through API of which he is the reporter of #2992

- dojo/filters.py
This PR add / fixes some issues with two fields in the `findings` filter of the APIv2 (`test__test_type` and `test__engagement`). It also removes some unused code (related to the UI) that was initially wrongly copy/pasted when creating filters that are dedicated to the API.
For ref: https://owasp.slack.com/archives/C014H3ZV9U6/p1602624904093500
> apiv2: add misssing fields for filtering and remove UI related stuff

- dojo/api_v2/views.py
In this PR we add the following to the API V2 :
- New endpoint to delete a product.
- New endpoint to delete an environment.
We have tested that in both cases the deletion cascade correctly. 
These changes have been made in collaboration with @xens
> Add delete methods for products and environments in api v2

- components/package.json
Name and version are required fields and some tools (i.e. whitesource) fail if they are missing.
> Add required fields in package.json

- helm/defectdojo/templates/celery-beat-deployment.yaml
- helm/defectdojo/templates/celery-worker-deployment.yaml
- helm/defectdojo/templates/django-deployment.yaml
- helm/defectdojo/templates/initializer-job.yaml
- helm/defectdojo/templates/secret-mysql.yaml
- helm/defectdojo/templates/secret-postgresql.yaml
- helm/defectdojo/templates/secret-redis.yaml
- helm/defectdojo/templates/tests/unit-tests.yaml
- helm/defectdojo/values.yaml
Allow to use a specific key in existing secrets for database passwords.
> Allow specifying the key for the database secrets

- helm/defectdojo/Chart.yaml
- helm/defectdojo/requirements.lock
- helm/defectdojo/requirements.yaml
This reverts commit 082d576a12ba4e632d7237fb46eafd639f8ad790.
Reverting since `conditions` no longer work if moving to Chart v2 with dependencies in the Chart.yaml itself.
> Revert "Move helm deps to Chart.yaml (#3013)"

- dojo/settings/settings.dist.py
Do you also NOT like this log line appearing everywhere? 
```
No config file found at /home/john_doe/.titlecase.txt
```
This PR suppresses that.
> title: suppress superfluous log lines

- dojo/jira_link/views.py
- dojo/settings/settings.dist.py
- dojo/tool_type/views.py
- dojo/utils.py
Add a variable in settings to specify whether SSL certs will be verified by Jira. The default is `True` in the package used on our integration, so it will be the same in settings. Reference to the argument in their [docs](https://jira.readthedocs.io/en/latest/api.html#jira).
> Add SSL verification variable to JIRA integration

- docker-compose.yml
If `DD_PORT` is set, it overwrites not only the published port but also the target port, which is wrong because nginx always listens on port 8080 inside the container. The same is true for port 8443 with TLS enabled.
This pull request also adds the variable `DD_TLS_PORT` (by default 8443) that allows setting the port for HTTPS to a different value than the port for HTTP.
> Fix nginx port definition in docker-compose.yml

- dojo/templates/dojo/view_test.html
fixes #3027 
The javascript for the bulk edit menu was lagging behind the javascript being used by findings_list.html.
But the real cause was that datatables need to initialized before assigning any listeners to the checkboxes.
hopefully one day somebody will get rid of the view_test.html generating it's own table and just reuse findings_list.html :-)
> view_test: fix javascript for bulk edit enablement

- dojo/context_processors.py
- dojo/settings/settings.dist.py
- dojo/templates/base.html
The SAML package we use does not have a logout endpoint that does anything worthwhile. This additional setting allows IdP logout endpoints to be leveraged. If the setting is specified, an additional logout button will be available with that link.
- [ x] Add the proper label to categorize your PR.
> Add configurable SAML2 logout endpoint

- docker/entrypoint-uwsgi.sh
- [N/A ] Your code is flake8 compliant.
- [N/A ] Your code is python 3.6 compliant (specific python >3.6 syntax is currently not accepted).
- [N/A] Model changes must include the necessary migrations in the dojo/db_migrations folder.
- [N/A] Add applicable tests to the unit tests.
This minor enhancement adds an if statement to the existing entrypoint_uswgi.sh to allow the settings file in a container to be overridden by one that is bind mounted or otherwise injected into the container at /settings/.  If the uwsgi container is started with the path /settings/settings.py, that settings.py file will overwrite the one 'baked" into the Docker container.
Note: If you don't inject a file at /settings/settings.py via a bind mount or similar, there is no change to the current behaviour for the …
> Modify uwsgi entrypoint to allow for overriding settings.py

- dojo/settings/settings.dist.py
- requirements.txt
For monitoring purposes and automatic tokenization by logging systems, the json format is much better.
This PR introduces the ability to turn on JSON logging instead of/in parallel of standard console logging.
As the requirement will be in there, users can also tweak the `LOGGING` variable to their liking.
> Add json logging to Django

- dojo/api_v2/views.py
- dojo/risk_acceptance/api.py
- dojo/settings/settings.dist.py
- dojo/urls.py
- requirements.txt
upgrade to drf-yaswg2 which is needed for django rest framework 3.12 and higher, see #2925 and linked PRs their from libraries.
> upgrade to drf_yasg2 which is needed for django rest framework 3.12 and higher

- tests/Finding_unit_test.py
fixes #3064  and #2371 no longer seems to be an issue
- fix integration tests errors due to race condition on mark finding for review
- apply template to finding test enabled again also when jira is enabled as 2371 no longer seems to be an issue
> integration tests: fix mark finding for review errors

- helm/defectdojo/Chart.yaml
- helm/defectdojo/templates/celery-beat-deployment.yaml
- helm/defectdojo/templates/celery-worker-deployment.yaml
- helm/defectdojo/templates/django-deployment.yaml
- helm/defectdojo/values.yaml
Allows to put annotations for django pod, celery pods.
Useful to add monitoring annotation, for example. Tested with datadog here, works well.
Also bumped up chart version as well as app version we didn't do last release.
> Add annotations for pods

- dojo/celery.py
- dojo/settings/settings.dist.py
Follow-up from #3062
It turns out that celery hijacks the logger settings from django, so logging was not following what was set.
This PR fixes that. Without it celery continues to log as it wishes without considering our logging settings.
Also, the PR introduces a new variable called `DD_LOGGING_FORMAT` to be able to override the console logging format.
I also added a `django.security` logger, because I stumbled upon it and thought it would not hurt.
> Add DD_LOGGING_FORMAT variable, celery logger section

- dojo/templatetags/display_tags.py
Fixes #3061 
Per previous decisions around the active status of findings, and also linked to the enhancement that will be brought by https://github.com/DefectDojo/django-DefectDojo/pull/3029 (showing more details about status findings per test) adjusting the query to display findings summary per severity.
This way, the overall "Test" head bar will show a count active, non-duplicates findings, whatever their status.
Actual details of findings status will be per test line, through the above linked PR.
> Test header bar - findings count fix

- dojo/settings/settings.dist.py
- dojo/templatetags/display_tags.py
This Pull request introduces a new optional env variable to allow end users to configure a custom version in the footer of `base.html` 
modified:   dojo/settings/settings.dist.py
modified:   dojo/templatetags/display_tags.py
Let me know if I should also submit a sibling pull request to this file: https://github.com/DefectDojo/Documentation/blob/master/docs/settings-docs.rst
> Optional env variable for custom footer version

- tests/dedupe_unit_test.py
a while ago we switch to block mode to run the dedupe integration tests as we thought celery was causing delays / tests to fail.
turned out it was caused by javascript (root of all evil). so we're switching back in this pr to non-block mode to let celery do the dedupe. good to have it tested that way to see of celery etc works.
> integration tests: let celery handle dedupe again as before

- dojo/templates/dojo/new_product_type.html
Noticed a small typo in the placeholder text of the "new product type" form.
This was newly added in 1.9 via #3007
> Fix Placeholder Text in New Product Type Form

- .travis.yml
- travis/before-install.sh
- travis/script.sh
As discussed / proposed on Slack:
- Travis tets are extremely slow
- The non-k8s tests are running fine in GitHub Actions
The plan was to let both Travis and GitHub actions run alongside eachother for a couple of weeks. But waiting times for Travis are currently up to 3-4 hours sometimes, which breaks the feedback loop we need.
This PR:
- disables/removes all non-k8s tests / steps from the travis build
- reduces the build matrix for k8s tests to alleviate the strain on travis and reduce our waiting times.
Proposed for after the release of 1.9.0
> travis: remove non-k8s tests, reduce matrix for k8s

- .dockerignore
- .gitignore
- DOCKER.md
- Dockerfile.django
- docker/entrypoint-initializer.sh
- docker/extra_fixtures/readme.txt
This PR allows user to add their own fixtures to docker image that are automatically loaded by the initializer.
> Allow to load extra fixtures in docker deployment

- dojo/settings/settings.dist.py
Djanog has a TEMPLATE_DEBUG config setting that provides extra information when an error occurs in a template AND DEBUG is set to True.
This PR allows us to configure this using DD_ env variable, and sets default to False.
> allow TEMPLATE_DEBUG to be set in settings

- dojo/engagement/views.py
- dojo/filters.py
- dojo/finding/urls.py
- dojo/product/views.py
- dojo/settings/settings.dist.py
- dojo/templates/dojo/snippets/engagement_list.html
- dojo/templates/dojo/view_eng.html
- dojo/templatetags/display_tags.py
Addresses https://github.com/DefectDojo/django-DefectDojo/issues/3001
I always find myself wondering how many mitigated findings or active/verified are in the engagements when looking at a glance.
With so many CI/CD imports, at a glance look become important.
This PR adds a couple columns when viewing engagements,
and drilling to tests
> Add more findings info to engagement/test views

- dojo/decorators.py
- dojo/engagement/services.py
- dojo/engagement/views.py
- dojo/finding/views.py
- dojo/management/commands/dedupe.py
- dojo/management/commands/rename_whitesource_findings.py
- dojo/management/commands/test_celery_decorator.py
- dojo/models.py
- dojo/product/views.py
- dojo/signals.py
- dojo/tasks.py
- dojo/test/views.py
- dojo/tools/tool_issue_updater.py
- dojo/utils.py
Currently the code is "scattered" with logic to decide if a task should be handled asyncrhonously by celery, or in the foreground:
```
if Dojo_User.wants_block_execution(request.user):
update_jira_issue(finding, True)	
else:	
update_jira_issue.delay(finding, True)
```
There were 18 ocurrences. and this PR brings that down to 2 occurrences. This done by implementing a decorator `dojo_async_task` that decides if the underlying task (function) should be executed asynchronously or in the foreground.
This PR also removes all wrapping / glue code from tasks.py as that is not needed.
```
@app.task(name='applying rules')	
def async_rules(new_finding, *args, **kwargs):	
logger.info("applying rules")	
sync_rules(new_finding, *args, **kwargs)
```
This PR also removes the dedupe_signal. It was called …
> Centralize logic to decide on async or foreground tasks

- dojo/product_type/views.py
- dojo/user/views.py
Fixed a bug introduced in #3007. Users were not being removed as an authorized user in the database, but were shown as being removed from the form. This obviously carries quite a bit of risk.
> Revoke access to authorized users after removal

- dojo/filters.py
- dojo/test/views.py
Fix bug where endpoint_status objects are not being created for ad-hoc findings being created from the test level. Also removed endpoint_statuses from all filters as they were not helpful and cluttered things.
> Fix endpoint_status filter and bug in ad-hoc finding creation

- dojo/filters.py
- dojo/test/views.py
Repeat of #3137 on the correct branch
Fix bug where endpoint_status objects are not being created for ad-hoc findings being created from the test level. Also removed endpoint_statuses from all filters as they were not helpful and cluttered things.
> Fix endpoint_status bug for ad-hoc findings

- dojo/product_type/views.py
- dojo/user/views.py
Repeat of #3142 on the correct branch
Fixed a bug introduced in #3007. Users were not being removed as an authorized user in the database, but were shown as being removed from the form. This obviously carries quite a bit of risk.
> Fix Authorized User bugs

- docker/entrypoint-uwsgi.sh
- helm/defectdojo/templates/django-deployment.yaml
- helm/defectdojo/values.yaml
- nginx/nginx.conf
- nginx/nginx_TLS.conf
The current liveness and readiness checks are done on the nginx container which proxy to uswgi. If uwsgi hangs or is overloaded, only the nginx container is restarted.
This PR correct this by doing the following:
* nginx: Check the liveness of nginx by using a dummy endpoint. This will avoid nginx getting restarted because of uwsgi failure.
* nginx: Check the readiness by checking the availability of uwsgi. In case of uwsgi failure, nginx will be removed from the loadbalancer but won't be restarted.
* uwsgi: Enabled the http server and check the availability of uwsgi. In case of failure, uwsgi will be restarted. There is no point to do readiness on this container since there is no service for it.
> Kubernetes liveness and readiness improvement

- .github/workflows/k8s-testing.yml
kubernetes helm repo is not available anymore, so we are going to  use charts.helm.sh/stable
> Moving away from kubernetes to charts repo 

- dojo/jira_link/views.py
- dojo/notifications/helper.py
- dojo/tool_type/views.py
- dojo/utils.py
we see recurring issues around exceptions on missing meta data. this PR logs meta data to DEBUG to help troubleshooting support tickets.
> jira: add logging of metadata

- dojo/settings/settings.dist.py
Recently somebody (from Switzerland ;-)) introduced a DD_LOGGING_FORMAT variable.
The variable is used to configure *handlers*  and not formatters, so this PR renames it to DD_LOGGING_HANDLER.
I considered making it backwards compatible, but couldn't find a straigforward way. The variable is new in 1.9.0 and I don't think may people are using it.
With the new `local_settings.py` setup people will have to review their settings anyway when upgrading.
> logging: improve variable naming for HANDLERs

- CONTRIBUTING.md
- dojo/settings/template-local_settings
- requirements.txt
With the new `local_settings.py` solution, people can easily add extra configuration/settings. For example to enable the Django Debug Toolbar (https://github.com/jazzband/django-debug-toolbar).
The only thing missing is the right package(s) in `requirements.txt`. Although it only requires a 1 or 2 line change, I've run into issues with as it can give conflicts. Or git requires you to stash your changes before you can pull. And before you know it you spend 5 minutes waiting for a docker build to complete and another 2-3 minutes for the initializer to complete only to find out dojo won't start because the debug toolbar is not installed.
I suggest that we inlude the debug toolbar (+1 helper package) by default in our requirements.txt.
It's only a couple of KB of space, but greatly simplifies …
> django-debug-toolbar: add example config + required pip packages

- dojo/api_v2/serializers.py
Fix the issue raised in #3100. 
Introduce serializers for the related fields instead of accessing the fields directly from the model. While this follows the design principles of django it also changes a bit the structure of the returned object. More specifically, we don't have all the referred fields as direct children of the parent JSON object `related_fields`. Instead, we have an object with the same structure as defined in the models.
This fix also adds the swagger documentation for the response as it was missing from the current implementation.
Note : I kept the name `related_fields`, however, we might want to rename it ?
> APIv2: Use serializers instead of direct access to fields of model instance

- .github/workflows/new-release-pr.yml
- .github/workflows/new-release-tag-docker.yml
update workflow to allow releasing from an existing `release/x.y.z.` branch so we can do hotfix/bugfix releases.
example run for hotfix release from release/0.0.0: https://github.com/valentijnscholten/django-DefectDojo/runs/1362518559?check_suite_focus=true
example run for feature release from dev: https://github.com/valentijnscholten/django-DefectDojo/runs/1362516962?check_suite_focus=true
> github action release workflow: support bugfix/hotfix releases

- helm/defectdojo/values.yaml
Unsure why `DEBUG` was the default, `INFO` seems like a better start.
> Reduce default loglevel values to INFO

- dojo/tools/qualys/parser.py
Some Qualys VM/OS reports do not have a LAST_FIXED date in the report. This handles the problem by using None instead as the LAST_FIXED instead of failing to import.
> Handle null LAST_FIXED date in Qualys VM/OS report.

- .github/workflows/new-release-tag-docker.yml
I didn't want to try it live when doing 1.9.0, now tested manually, works fine.
If someone take the workflow and try on his own GH org, then the docker push will push to the org of the same name on dockerhub.
> [GHA] Push image in one's org

- dojo/api_v2/serializers.py
- dojo/api_v2/views.py
- dojo/unittests/test_rest_framework.py
This allows updating user profiles via the API and additionally allows setting the user's superuser status.
> APIv2: Allow updating users and set is_superuser

- dojo/api.py
The Burp plugin seems to be breaking because of the missing import.
> Fix missing base64 import

- dojo/tasks.py
The async task would still run even if the Finding SLA enabled was actually disabled.
> Check if Finding SLA enabled to run SLA notifications

- .github/workflows/k8s-testing.yml
to support testing and eventually passing of https://github.com/DefectDojo/django-DefectDojo/pull/2859
This add should not change anything, since the actual chart taken into consideration is in requirements.yaml
> Add bitnami to helm repo list

- dojo/templates/dojo/system_settings.html
fixes #3211 
error happened when the jira secret was empty and the jira secret disable checkbox was checked.
It's because the field is mandatory but empty. The django javascript tries to focus the field and display the error. Not sure how to fix it. Workaround is to put some value in there.
> system setting: set random secret when jira secret is disabled and empty

- dojo/engagement/urls.py
- dojo/engagement/views.py
found out (the hard way) that there is some unused code around creating engagements.
this PR removes the unused method. (creating new engagements is handled by https://github.com/DefectDojo/django-DefectDojo/blob/76d84516e7af0af975123c2c714b915a817b98e0/dojo/product/views.py#L897
> remove unused new_eng view

- dojo/templates/dojo/view_finding.html
The CWE link on the finding page is missing a `"`, which causes the link to go to the wrong location and also malforms the HTML on the page.
> Fix CWE URL on the finding page.

- dojo/settings/settings.dist.py
By default the log output from DD is not displaying any date or time. Personally I prefer to have the default to use the `verbose` logformat which basically only adds a datetimestamp at the beginning of the line.
> add datetime to logformat (use verbose)

- docker/entrypoint-unit-tests-devDocker.sh
- dojo/tools/npm_audit/parser.py
- dojo/unittests/scans/npm_audit_sample/many_vuln_npm7.json
- dojo/unittests/test_npm_audit_scan_parser.py
Node 15 has been released, which includes npm7. This completely changes the output of `npm audit --json`.
I was about to update the parser to handle the new format, but found out most of the fields we're using are missing.
I raised a report at: https://github.com/npm/npm-audit-report/issues/45
For now I have implemented a blunt check in the parser to prevent npm7 reports from being uploaded. Without that check, the parser thinks the report is empty and it will close all open findings in defect dojo (if `close_old_findings=true` is specified on `reimport_scan`).
> npm audit: refuse npm7 or higher as it misses most important fields

- dojo/finding/views.py
- dojo/templates/dojo/findings_list_snippet.html
- dojo/templates/dojo/view_test.html
- dojo/templatetags/get_endpoint_status.py
- dojo/test/views.py
fixes #3234
endpointstatus querying was inefficient resulting in slow page loads and 600+ queries.
> endpoint_status: prefetch part1

- dojo/templates/dojo/view_product_details.html
> Fixes mouse-over help for product notifications includes a non-rendered link (unclickable) #2905

- dojo/templates/dojo/view_test.html
fixes #3225 
bulk delete was not available on `view_test` due to outdated permission check.
> allow bulk delete in view_test

- dojo/decorators.py
- dojo/github.py
- dojo/management/commands/test_celery_decorator.py
- dojo/settings/settings.dist.py
- dojo/tools/tool_issue_updater.py
- dojo/utils.py
based on 3091, so merge that first. there's also a quickfix (but not complete fix) for #3099 
Currently Defect Dojo is sending the full model instances to celery. These can be fairly large, especially if there are fields stored such as `unsaved_request` and `unsaved_response`. These can be large base64 encoded "blobs" putting straing on celery / rabbitmq. The current approach only works because we are using the "insecure" `pickle` serializer, which at some point we have to get rid of (#3093)
This PR adds a setting / environment variable (DD_)CELERY_PASS_MODEL_BY_ID to convert all models to ids before calling celery. Inside the celery tasks the models will be loaded from the database based on this id.
This is done using 2 decorators that can be transparently used on celery tasks to make …
> Celery: only send model ids and not full instances

- dojo/tools/netsparker/parser.py
To fix error on unexpected BOM in vulnerabilities json exported from Netsparker 5.8
uwsgi_1         | the JSON object must be str, not 'bytes'
uwsgi_1         | Traceback (most recent call last):
uwsgi_1         |   File "./dojo/tools/netsparker/parser.py", line 22, in __init__
uwsgi_1         |     data = json.loads(str(tree, 'utf-8'))
uwsgi_1         |   File "/usr/local/lib/python3.5/json/__init__.py", line 315, in loads
uwsgi_1         |     s, 0)
uwsgi_1         | json.decoder.JSONDecodeError: Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)
uwsgi_1         |
uwsgi_1         | During handling of the above exception, another exception occurred:
uwsgi_1         |
uwsgi_1         | Traceback (most recent call last):
uwsgi_1         |   File …
> Change encoding from utf-8 to utf-8-sig

- dojo/templates/base.html
- dojo/utils.py
At the product level, the number of findings displayed in the product tabs only counted active AND verified findings. It now counts findings that are active regardless fo verification status. Additionally, the the "View Open Findings" tab now queries findings that are active instead of active and verified.
> Update open finding definition on product level

- dojo/settings/settings.dist.py
fixing my left over mistake in settings.dist.py
> settings.dist.py: reduce default log level from DEBUG to INFO

- dojo/management/commands/clear_alerts.py
- dojo/settings/settings.dist.py
- dojo/templates/base.html
Add the option to disable the notification recount through the `alerts/count` endpoint. Also add a manage.py command to remove alerts from the database with the options of removing the entire table, just system alerts, or alerts belonging to specific users. They tend to add up quickly with many users!
> Set flag for auto refresh of alert/counts

- dojo/metrics/views.py
I looked through the rest of the "Accepted_Risk.objects" instances in the repo and this was the last one. Hopefully we can put this issue behind us now!
> Fix Accepted Risk reporter/owner in engineer metrics

- dojo/settings/settings.dist.py
as discussed with @madchap it would be better to disable by default.
recently I enabled SLA in system settings and unaware of this other setting in settings.py it generated 430k notifications overnight :-)
> sla notify: disable by default, add explanation to settings

- dojo/finding/views.py
- dojo/models.py
- dojo/settings/settings.dist.py
- dojo/templates/dojo/findings_list_snippet.html
- dojo/templates/dojo/view_finding.html
- dojo/templates/dojo/view_test.html
the view_finding page is quite slow due to the amount of queries executed and data retrieved.
this PR optimizes it a bit, but the real gain must come from #3236 
also adds a `settings.DD_SIMILAR_FINDINGS_MAX_RESULTS` setting to tune the max number of similar findings returned (default 25 instead of previous 10).
> performance: optimize a bit view_finding, max similar findings=25

- dojo/api_v2/views.py
- dojo/unittests/test_rest_framework.py
The goal of this PR is to support metadata operations directly on the findings endpoints to avoid having to perform double queries. More specifically, by introducing `/findings/{id}/metadata` we can directly interact with the metadata of a given findings without having to first retrieve its id and then perform the operation. This is quite similar to what is already done with the notes and the tags.
Concretely, we introduce the methods `POST`, `GET`, `PUT`, `DELETE` on `/findings/{id}/metadata`. We decided to not support `PATCH` as a metadata, for a given finding, is only a tuple (name, value) and the name is required to identify the metadata on which we want to perform the operation. Hence, we don't think that there is any advantage is supporting `PATCH` at the moment.
This PR also add …
> API_V2 : Add metadata operation on findings endpoints

- dojo/jira_link/helper.py
I noticed the new field `jira_project` was not set on JIRA_Issue creation. Nothing major, but the value could be used in the future.
> jira: set jira_project when creating JIRA_Issue

- dojo/api_v2/serializers.py
- dojo/test/views.py
in the past findings didn't have a `component_name` and `component_version` fields. when reimporting a scan these existing findings are now updated with these fields to get these populated.
> reimport: set component_name&version on existing findings

- dojo/forms.py
- dojo/jira_link/helper.py
- dojo/templates/dojo/ad_hoc_findings.html
- dojo/templates/dojo/add_findings.html
- dojo/templates/dojo/edit_finding.html
- dojo/templates/dojo/finding_related_row.html
- dojo/templates/dojo/findings_list_snippet.html
- dojo/templates/dojo/import_scan_results.html
- dojo/templates/dojo/new_eng.html
- dojo/templates/dojo/view_eng.html
- dojo/templates/dojo/view_finding.html
- dojo/templates/dojo/view_product_details.html
- dojo/templates/dojo/view_test.html
- dojo/templatetags/display_tags.py
in #3200 there was a `jira_url` filter that was (supposed to be) "smart". Turns out there are many variations of findings with a jira issue or findings wanting to display a jira project url if they have no issue, but only on the edit screen, but not in the findings list, etc. etc. 
so this PR splits out the `jira_url` filter into two seperate filters so it's clear what it does and will or will not display.
thanks @madchap for reporting.
> jira: split url handling for issues and projects

- dojo/models.py
- dojo/templates/issue-trackers/jira-description.tpl
- dojo/templatetags/display_tags.py
fixes #3271 
A more structural fix for everything around `User` vs `Dojo_User` would be better, but we ran into some issues: #3278
> jira: fix mailto link in description

- dojo/settings/template-local_settings
the debug_toolbar approach with local_settings.py doesn't work after all. It only worked on my machine because I had some previous static files from debug_Toolbar still laying around.
the nginx containers needs the settings at build time, so any apps that generate static files need to be added to INSTALLED_APPS in `settings.dist.py` for now. Maybe we can think of a better way, but we want to avoid copying `local_settings.py` into the release containers (I think), so that's way it's on the `.dockerignore` list.
if some docker expert has a better idea, let me know. For now I'd thought to get this PR so people don't get stuck on missing static files.
> debug_toolbar: add known issue + fix for static files

- dojo/unittests/dojo_test_case.py
- dojo/unittests/test_rest_framework.py
- dojo/unittests/test_taggit_tags.py
in the near future I am going to work on replacing the `django-taggit` library with `django-tagulous`.
to capture the current behavior, I have added some more test cases around tags. this will help with regression testing after the move to `django-tagulous`
> tags: add testcases

- dojo/fixtures/dojo_testdata.json
- dojo/jira_link/views.py
- dojo/unittests/test_jira_webhook.py
I discussed #3290 with @madchap and we decided I should put my money where my mouth is.
So this is my take a improving error handling of the JIRA webhook, and fix #3290 
Has updated unit tests to test scenarios with missing JIRA_Issue or missing Finding or missing Engagement.
Will also correctly ignore comments/udpates for engagements, as these have no findings attached in Defect Dojo.
Any exceptions that are not anticipated are not catched same as we do not catch those on any other page / view / api endpoint in Defect Dojo.
also added a fix for #3217 while I was at it
> jira_webhook: improve error handling

- dojo/templates/dojo/product_metrics.html
This was erroneously redirecting for a product's metrics page to
False Positives, not Total Positives (aka 'All findings.' in markup).
Fixes #3303.
> Fix Product Metrics link to false positives.

- dojo/tools/awssecurityhub/parser.py
Different aws securityhub findings have different time formats.
fixes #3276
> fix importing aws securityhub timestamp

- dojo/engagement/views.py
- dojo/product/views.py
engagements without JIRA config would not get updated on form submit due to a similar bug as in #3295 
add/edit product is not suffering from this.
> jira: fix add/edit engagement if no jira config used

- dojo/finding/views.py
When a non-staff user opens the list of finding in one of the products, he sees not only the findings of this particular product but all findings for all products he is allowed to see. This is due to a bug, where the queryset for the findings doesn't get a new filter to limit the findings to his products but a new filter is created, which disregards the initial selection.
This bug fix uses the previously defined filter and uses it for the authorization.
> Correct filter for findings for non-staff users

- dojo/api_v2/serializers.py
- Sets or clears mitigated date based on the value of is_Mitigated
- Sets or clears mitigated_by based on the value of is_Mitigated and current user context
> apiv2: set mitigated date if applicable

- dojo/tools/aqua/parser.py
When a score is 4 or 7, it becomes "Critical" as those values were not caught.
@valentijnscholten @madchap
> Aqua parser: correct missing values

- dojo/tools/qualys_webapp/parser.py
- dojo/unittests/test_qualys_webapp_parser.py
Severities for issue recorded in Dojo from Qualys did not reflect the same number of vulnerabilities. Since all "information gathered" and "Sensitive Content" categories have a different severity scale,  they will be marked as informational. Additionally, Low severity items were being marked as Info in Dojo. The mapping is very strange, so this is a stab
> Align Qualys WAS severities with the those in the UI

- helm/defectdojo/templates/secret-rabbitmq.yaml
- helm/defectdojo/values.yaml
**Helm deployment option broken until this is merged.**
As we moved to Bitnami repo, the rabbitMQ chart got bumped 2 major version.
A key changed from `rabbitmq` to `auth`.
_Support: There could also be some "support" strain, where a statefulset cannot be upgraded due to k8s immutable specification around volume claims, so deleting the statefulset would be required for the upgrade_
> Fix helm rabbitMQ not grabbing secret after move to bitnami

- helm/defectdojo/templates/secret-postgresql.yaml
If you use an external postgreSQL, you'd still have a secret yet have it disabled within the helm chart.
> Helm posgreSQL, use existing secret even if postgres not enabled

- dojo/api_v2/serializers.py
- dojo/api_v2/views.py
The method `save` in the serializers for import scan and re-import scan can fail if the file parsed is not of the type given by scan type. As a result, the client gets an error 500 without any error message. Therefore, this PR aim at solving that issue by raising an exception which is catched in the viewset and transformed into a ParseError that yields an HTTP error 400 with an error message.
Currently, I wrote a generic message since there is not error handling in the `import_parser_factory` that would yield a more specific error message. Let me know if you think that something else would be more appropriate.
> FIX APIv2 : Add exception when parser fail to avoid error 500 without error info

- Dockerfile.django
- Dockerfile.nginx
switch to old legacy resolver due to pip now using a new more strict resolver that we cannot use yet
> pip: use old legacy resolver

- dojo/api_v2/views.py
This adds the ability to filter test types by name to APIv2, which is possible in APIv1.
> APIv2: allow filtering of test types by name

- docker-compose.yml
- docker/entrypoint-celery-beat.sh
- docker/entrypoint-celery-worker.sh
If you want to add a new CELERY_BEAT_SCHEDULE or override deduplication algorythms by way of HASHCODE_FIELDS_PER_SCANNER and friends, the configuration needs to also be propagated to the celery containers and not only uWSGI.
> Include local_settings in celery containers if present

- dojo/jira_link/helper.py
Closing an engagement (e.g. via the API) that has a JIRA instance associated with it leads to an Internal Server Error:
```
ERROR:django.request:Internal Server Error: /api/v2/engagements/1217/close/
File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
response = self.process_exception_by_middleware(e, request)
File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
File "/usr/local/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in …
```
> Fix Internal Server Error when closing engagements

- dojo/filters.py
After #3410 there was still an instance where unauthorzed endpoints were shown.
Original security release:
Adresses: Security Advistory [GHSA-96vq-gqr9-vf2c](https://github.com/DefectDojo/django-DefectDojo/security/advisories/GHSA-96vq-gqr9-vf2c)
A user can see vulnerable endpoints and details about their findings in a report, when he is not autorized for these products.
A user can see products, product types and details about their findings in metrics reports, when he is not autorized for these products.
This information about products and findings should only be revealed, when a user is explicitly allowed seen them or he is set as staff or superuser.
Similar data leakage could occur due to Django caching metrics globally instead of per user. …
> security: correct incomplete fix for #3410 / GHSA-96vq-gqr9-vf2c

- dojo/api_v2/views.py
This PR is an improvement of the (sub)endpoint recently added, `/finding/{id}/metadata`. In the current implementation, the semantic of PUT is only an update semantic, meaning that if the given metadata does not exist, it will not create it. However, since we are in the particular case where a metadata can be uniquely identified by a pair `(finding_id, metadata_name)` we think it makes sense to change the semantic to that of update or create. Note that this does not contradict the original semantic intended for the PUT operation in the context of REST API since we are not identifying the metadata with an ID.
The main advantage of this improvement is to reduce the number of queries from two to one in the case where we want to do an update or create. We also kept the POST operation to still …
> [APIv2] Update put semantic and doc for endpoint /finding/{id}/metadata

- dojo/api_v2/views.py
- dojo/finding/views.py
- dojo/unittests/test_rest_framework.py
This exposes the duplicate finding functionality through the REST v2 API, as currently there is no way to (that I know of) reassign duplicate findings while preserving the duplicate cluster through the API.
The following endpoints are added:
- `GET ​/findings​/{id}​/duplicate​/` - Returns the contents of `duplicate_cluster`.
- `POST ​/findings​/{id}​/duplicate​/reset​/` - Resets the duplicate status of a finding.
- `POST ​/findings​/{id}​/original​/{new_fid}​/` - Allows reassignment of duplicate findings.
The three endpoints use logic from the already existing `dojo/finding/views.py` file instead of creating duplicate code.
> Add duplicate finding support to API v2.

- dojo/settings/settings.dist.py
- dojo/tools/tool_issue_updater.py
fixes #3413 
since 1.10.x some celery tasks are located in `dojo/tools/tool_issue_udpater.py`.
for some reason celery doesn't detect these tasks.
strange coincidence is that any changes made to that file also don't trigger any hot reloading by uwsgi.
can't figure out why, so for now we add explicit CELERY_IMPORTS to settings to detect the tasks correctly again
> celery imports for dojo.tools.tool_issue_updater

- dojo/api_v2/views.py
- dojo/filters.py
- dojo/models.py
- dojo/product/views.py
- dojo/reports/views.py
- dojo/templates/dojo/product_type_pdf_report.html
- tests/Product_unit_test.py
- tests/Report_builder_unit_test.py
The reports for ProductType, Product, Engagement and Test are trying to load all findings into a dropdown in a filter.
This causes severe performance issues once you start having a somewhat larger instance. And it discloses finding titles to unauthorized users.
This PR fixes that and along the way I ran into two bugs in the product type report that are now fixed (#3431)
This PR also adds a basic selenium test for each report.
> reports: fix performance issues and small bugs

- dojo/tools/nikto/parser.py
- dojo/unittests/scans/nikto/nikto-report-many-vuln.xml
- dojo/unittests/scans/nikto/nikto-report-old-format.xml
- dojo/unittests/scans/nikto/nikto-report-one-vuln.xml
- dojo/unittests/scans/nikto/nikto-report-zero-vuln.xml
- dojo/unittests/test_nikto_parser.py
Nikto can produce results for multiple hosts in one scan, eg. by reading nmap output to supply a list of hosts and ports to scan. The current Nikto parser reads only the result of the first host. With this pull request it will iterate over the results for all scanned hosts. This will only work for the new file type (nxvmlversion="1.2").
> Nikto parser for scan of multiple hosts

- dojo/jira_link/helper.py
- dojo/models.py
Findings with an Info severity do not get an SLA. When creating new issues to push to JIRA, a findings SLA is used to set the due date on the JIRA issue. Since Info findings don't have an SLA, trying to add one results in an exception and the issue is not pushed. This added check just ignores that field if it is an Info finding.
> Allow Info findings to be pushed to JIRA without SLA

- .github/workflows/new-release-tag-docker.yml
the current workflow builds all images twice. once to push version `x.y.z` and once to push `latest`
this workflow simplifies this, which also results in the sha's for both tags being the same (which is good).
> release workflow: simplify matrix

- .github/workflows/new-release-tag-docker.yml
Reverts DefectDojo/django-DefectDojo#3416
Although unrelated, we're seeing unti test failures after merging this. Just reverting to see if it is related to this PR or not.
```
uwsgi_1         | ======================================================================
uwsgi_1         | ERROR: test_zero_findings (dojo.unittests.test_dsop_parser.TestDsopParser)
uwsgi_1         | ----------------------------------------------------------------------
uwsgi_1         | Traceback (most recent call last):
uwsgi_1         |   File "/app/dojo/unittests/test_dsop_parser.py", line 11, in test_zero_findings
uwsgi_1         |     parser = DsopParser(file, Test())
uwsgi_1         |   File "/app/dojo/tools/dsop/parser.py", line 14, in __init__
uwsgi_1         |     f = pd.ExcelFile(file)
uwsgi_1         | …
```
> Revert "release workflow: simplify matrix"

- requirements.txt
fixes #3455 by pinning xlrd and pandas.
pins some other dependencies as well to the version currently installed by pip.
pinning ensures stability and triggers dependabot to create PRs to keep up to date.
> pin all python / pip dependencies

- dojo/api_v2/views.py
- dojo/finding/views.py
This PR is pretty straight forward, part of the code was still using the old method `add_comment_task` that has been replaced by `add_comment`. This resulted in errors when adding notes to findings. Therefore, we replace the old method by the new method which solve the problem.
Let me know if there is more to it as I'm not completely familiar with the new integration :).
> [FIX] Remove call to old method and add call to new method for jira integration

- Dockerfile.nginx
In the Dockerfile it says:
># The code for the build image should be idendical with the code in
># Dockerfile.django to use the caching mechanism of Docker.
this PR makes Dockerfile.nginx back in sync with Dockerfile.django again
> make build image for nginx the same as django

- dojo/tools/fortify/parser.py
Fixed issue with Fortify parser where the import will fail if there is no Primary.Snippet value for a given finding. Added issue id and exception handling during parsing so we know where the import failed. In some cases (ok, in my case) <Primary> stanza doesn't have a <Snippet>.
> Tweaked Fortify Parser To Handle Missing Code Snippet For Finding

- dojo/api_v2/serializers.py
https://github.com/DefectDojo/django-DefectDojo/pull/2983 introduced bug (maybe a typo?) which caused a server error when importing a scan with an additional endpoint.
> apiv2: fix endpoint status creation during scan import

- dojo/filters.py
- dojo/reports/views.py
- dojo/templates/dojo/product.html
- tests/Report_builder_unit_test.py
fixes #3446 
also fixes one other place where the `duplicate_finding` field in filters was retrieving *all* findings.
in other places I removed that field from the filters. That field was added later to defect dojo and I think it was missed when excluding fields that are not really useful to filter on. I doubt anyone is using it (especially since the reports seem a bit shaky anyway).
if really needed, people can add it back in easily.
> report: fix report from products list and more

- dojo/models.py
- dojo/templatetags/display_tags.py
Display tags did not correctly create the popup required to display the status of a findings SLA. Also cleaned up the logic when determining a findings SLA by removing the ugly "is Info" check.
> Fix popup message on SLA displays

- CONTRIBUTING.md
- DOCKER.md
- dojo/settings/settings.dist.py
- dojo/settings/template-local_settings
Whenever people report bugs / issues, it's good to have DEBUG logs available. This PR allows to easily turn on DEBUG logging without having to rebuild containers or modifying settings files.
- adjust log level based on DEBUG value. DEBUG=True -> log level DEBUG, otherwise log level INFO
- add DD_LOG_LEVEL setting to allow finetuning / overriding
- update docs
> logging: add DD_LOG_LEVEL setting

- dojo/jira_link/helper.py
at some point we (I) decided it was a good idea to add a note to finding when a jira issue was created for it or when an existing jira issues was linked or unlinked. 
in hindsight this created too much noise and we commented out the code.
This PR:
- removes the commented out code
- removes the other places where notes were still created
> jira: don't add notes when creating/linking findings

- dojo/api_v2/views.py
- dojo/jira_link/helper.py
- dojo/unittests/dojo_test_case.py
- dojo/unittests/test_jira_import_and_pushing_api.py
- dojo/unittests/vcr/jira/JIRAConfigAndPushTestApi.test_import_with_push_to_jira_add_comment.yaml
#3453 showed we need a test case for adding a note to a finding and make sure it is pushed to JIRA (and doesn'r raise an exception). This PR implements that (basic) test case.
Side effects:
- note_type and private are now optional to provide in the API request when adding a note
- author text in jira comment now uses username if there is no fullname for the author
> jira: add api test for adding note/comment

- dojo/tools/microfocus_webinspect/parser.py
- dojo/unittests/scans/microfocus_webinspect/Webinspect_many_vuln.xml
- dojo/unittests/test_microfocus_webinspect_parser.py
- Fixing WebInspect parser mentioned in issue [3470](https://github.com/DefectDojo/django-DefectDojo/issues/3470)
- Adding test cases to verify the fix for [3470](https://github.com/DefectDojo/django-DefectDojo/issues/3470)
**Descriptions**
The WebInspect parser was implemented assuming the `SectionText` of each `ReportSection` would always contain data. Also, it assumes that every `Issue` will have a `Classification` with a `kind` attribute equal to `CWE`
Issue 3470 provides a file where not all `SectionText` contains data, and not every `Issue` has a `Classification` of the kind `CWE`
To test this fix, I've added some entries from the report provided in issue 3470 to the existing WebInspect parser test files in …
> WebInspect Parser fails to process Issues without CWE and ReportSection with an empty SectionText

- docker/entrypoint-integration-tests.sh
- entrypoint_scripts/test/travis-integration-test.sh
- setup/scripts/test/travis-integration-test.sh
- tests/base_test_class.py
- tests/local-integration-tests.bat
- tests/local-integration-tests.sh
- tests/search_test.py
- travis/integration_test-script.sh
In #3449 I added some integration tests for search, but turns out they weren't enable in the entrypoint scripts. This PR corrects that.
> enable search tests

- dojo/api_v2/serializers.py
- dojo/engagement/views.py
- dojo/fixtures/development_environment.json
- dojo/fixtures/dojo_testdata.json
- dojo/forms.py
- tests/Finding_unit_test.py
- tests/ibm_appscan_test.py
This commit add the ability to specify the `Environment` (prod, dev, ...) when importing scan data from both the APIv2 and the UI.
The current behavior of DDJ is to put everything inside the `Development` environment (APIv2+UI) when importing data without being able to specify it. I modified this logic and it'll put everything inside the `Default` environment if not specified when importing data from the APIv2, and when uploading data from the UI the user will need to specify it manually.
* I haven't added the ability to edit the `Environment` when using the `reimport_scan` endpoint, I didn't think that it was relevant and it's still possible to edit the environment afterwards by editing the associated `test`. Let me know what you think.
* I wasn't sure if it was best to specify the …
> Allow to specify the `Environment` when importing data from the APIv2 and the UI

- dojo/filters.py
- dojo/forms.py
- dojo/notifications/helper.py
- dojo/reports/views.py
- dojo/test/views.py
- requirements.txt
BugFix 1. I **believe** from tagulous, a notion of a ‘CastTaggedQuerySet' is introduced. When Googling, I only saw this type with reference to tagulous. Our report generator does not know how to handle this. QuerySets are only referenced in two locations in the generate report method and only come from a few sources. There maybe a more eloquent fix, but to keep consistent with other if else logic.  I simply added an 'or' in the same style which seems to have corrected the issues. I believe we want to treat CastTaggedQuerySet in the same fashion as QuerySets.
BugFix 2. Function not updated to reflect removal of args parameter. Line 21 helper/notifications still has args even though it appears all other functions were rewritten to use kwargs. create_notification causes closing engagements / …
> Various Bug Fixes. Make 'Active' Default On Scan Import Forms

- dojo/models.py
Addresses https://github.com/DefectDojo/django-DefectDojo/issues/3524
Essentially, only the blue SLA would show the number instead of 0. The orange one (mitigated past SLA) already was working.
> Retain SLA days for mitigated findings

- dojo/engagement/views.py
- dojo/test/views.py
prefetch engagement / test data to avoid slow calendar rendering
also fixes #3550 by making sure caching happens on a per user basis
> calendar: speedup and security fix

- dojo/tools/bandit/parser.py
- dojo/unittests/scans/bandit/many_vulns.json
- dojo/unittests/scans/bandit/no_vuln.json
- dojo/unittests/scans/bandit/one_vuln.json
- dojo/unittests/test_bandit_parser.py
This PR add unit tests for Bandit parser.
I used a recent version of Bandit (`1.7.0`)
> Add unit tests for Bandit parser

- dojo/settings/settings.dist.py
- dojo/tasks.py
- dojo/unittests/test_cleanup_alerts.py
Some users receives a lot of alerts but never reads or deletes them. This feature deletes the oldest x (default 999) alerts per user. The feature can be disabled by set DD_MAX_ALERTS_PER_USER to -1.
> feat(alerts): automated cleanup of alerts per user

- dojo/forms.py
- dojo/test/views.py
fixes #3563 
only affects UI.
In the API the reimport doesn't allow to modify tags. We could add it, but it would result in lots of glue code to either replace existing tags or add to existing tags or find a way to delete them and add new ones etc. It's easier to let the user decide and use the API to modify any tags straight on the test object if needed.
> Reimport (UI): Preserve existing tags when reimporting scan/test

- dojo/test/views.py
- dojo/unittests/test_jira_import_and_pushing_api.py
- dojo/unittests/vcr/jira/JIRAConfigAndPushTestApi.test_import_push_to_jira_reimport_with_push_to_jira.yaml
When re-uploading scan files, changes in status such as mitigated and reactive findings were not being updated in jira despite push all issues being set or just pushing individual imports.
> Send status changes from re-import to jira

- dojo/tools/qualys/parser.py
The qid in Qualys is not unique.
> fix(qualys-parser): map qid to vuln_id_from_tool

- dojo/tools/snyk/parser.py
This PR addresses two minor bugs:
* **unique_id** param can generate duplicated values for two different Findings when different Snyk issues with the same "title" affect the same component in a project. E.g: 
* https://snyk.io/vuln/SNYK-JAVA-ORGOWASPANTISAMY-31591 
* https://snyk.io/vuln/SNYK-JAVA-ORGOWASPANTISAMY-598767
* **Severity** level extractor ranges are missing CVSS values 4.0 and 7.0 as stated in https://nvd.nist.gov/vuln-metrics/cvss
> Snyk parser fixes

- dojo/endpoint/views.py
- dojo/product/views.py
- dojo/reports/views.py
- dojo/survey/views.py
- dojo/tools/acunetix/parser_helper.py
- dojo/tools/qualys_webapp/parser.py
- dojo/tools/veracode/parser.py
- dojo/unittests/test_deduplication_logic.py
- dojo/utils.py
- tests/validate_acunetix_scan_xml.py
the old lxml parser is not safe against XEE out of the box, so we have to disable entity resolution.
also fixes an open redirect
includes fixes for suggestions from sonar:
- remove hardcoded logging config changes
- check user controlled view parameter that is reflected in templates
> Security: Prevent XEE in parsers, Prevent open redirect

- dojo/api.py
- dojo/settings/settings.dist.py
- dojo/unittests/test_api_v1.py
Now that APIv1 is deprecated, it might be best to disable it by default. It can be enabled by setting `DD_LEGACY_API_V1_ENABLE` environment variable to `True`. Or by setting `LEGACY_API_V1_ENABLE` to `True` in a `local_settings.py` file.
By default all apiv1 request return a 400 message with an error:
```
BadRequest at /api/v1/findings/1234/
{"error": "{'code': 666, 'message': \"APIv1 is deprecated and may contain vulnerabilities. It's disabled by default. At your own risk it can be enabled by setting DD_LEGACY_API_V1_ENABLE to True, or by setting LEGACY_API_V1_ENABLE to True in  settings(.dist).py or local_settings.py\"}"}
```
When APIv1 is enabled again, it will work, but will also return some warnings:
```
Response Headers
{
...
"deprecation": "true",
"warning": "666 APIv1 APIv1 is …
```
> APIv1: disable by default

- dojo/api_v2/serializers.py
- dojo/engagement/views.py
- dojo/settings/settings.dist.py
- dojo/test/views.py
- dojo/unittests/dojo_test_case.py
- dojo/unittests/scans/anchore/one_vuln_many_files.json
- dojo/unittests/test_import_reimport.py
- dojo/utils.py
```
some parsers generate 1 finding for each vulnerable file for each vulnerability
i.e
#: title                     : sev : file_path
1: CVE-2020-1234 jquery      : 1   : /file1.jar
2: CVE-2020-1234 jquery      : 1   : /file2.jar
if we don't filter on file_path, we would find 2 existing findings
and the logic below will get confused and map all incoming findings
from the reimport on the first finding
```
for Anchore we fix this here, we may need a broader fix (and testcases)
or we may need to change the matching logic here to use the same logic
as the deduplication logic (hashcode fields)
```
if scan_type == 'Anchore Engine Scan':
if item.file_path:
findings = findings.filter(file_path=item.file_path)
```
I have refactored the existing 9 testscases to be run against the APIv2 and UI.
And …
> fix anchore reimport, sync reimport logic API<->UI, add unit tests

- dojo/tools/snyk/parser.py
- dojo/unittests/scans/snyk/all-projects_many_vulns.json
- dojo/unittests/scans/snyk/all-projects_no_vulns.json
- dojo/unittests/scans/snyk/all-projects_one_vuln.json
- dojo/unittests/scans/snyk/single_project_many_vulns.json
- dojo/unittests/scans/snyk/single_project_no_vulns.json
- dojo/unittests/scans/snyk/single_project_one_vuln.json
- dojo/unittests/test_snyk_parser.py
This PR addresses the following features:
* Support for Snyk JSON reports generated with the --all-projects (e.g: Maven multi module projects). 
* Added the following missing fields for each Finding generated from a report:
* CVSS3
* Severity justification 
* Mitigation
* References
* Minor visual changes:
* Added link to the Snyk Vulnerability Database for the referenced Snyk IDs.
* Added bold format to the details section within the issue description.
TODO:
> Snyk parser enhancements

- docker/entrypoint-unit-tests-devDocker.sh
- docker/entrypoint-unit-tests.sh
- dojo/unittests/test_swagger_schema.py
This PR adds a first version of the test suite for the swagger schema. This is the test used to report #3342. I have divided the test cases into two categories. The test that are currently succeeding and the tests that are failing. The later have been tagged as `broken`. By doing so, we can run the first category by calling
`python manage.py test dojo.unittests.test_swagger_schema.py --exclude-tag broken`
and the second category by calling
`python manage.py test dojo.unittests.test_swagger_schema.py --tag broken`
Ideally, this test would be implemented in the current pipeline first, by adding `--exclude-tag broken` to the command called by the job in charge of running the unit tests then by adding a new job that would run only that test but with `--tag broken` and that job would be …
> Add swagger schema test with tagged test cases

- dojo/filters.py
`django.utils.six` is a vendored version of the package `six` that we already have as a dependency.
As it is only used 1 time in `filters.py`, this import is completely useless.
(!) This simple reference break compatibility with Django 3.x as Django project cleaned there vendoring by removing it of 3.x branch.
Reference [https://docs.djangoproject.com/en/3.0/releases/3.0/#removed-private-python-2-compatibility-apis](https://docs.djangoproject.com/en/3.0/releases/3.0/#removed-private-python-2-compatibility-apis)
> Remove usage of django.utils.six vendored library version of six

- dojo/settings/settings.dist.py
during one of the bigger revamp PRs we broke the 3-hourly job that syncs data from sonarqube into defect dojo for findings originally imported from sonarqube: `dojo.tools.tool_issue_updater.update_findings_from_source_issues`
> Fix sonarqube 3-hourly sync job

- dojo/api_v2/prefetch/__init__.py
- dojo/api_v2/prefetch/mixins.py
- dojo/api_v2/prefetch/prefetcher.py
- dojo/api_v2/prefetch/schema.py
- dojo/api_v2/prefetch/utils.py
- dojo/api_v2/schema/__init__.py
- dojo/api_v2/schema/extra_schema.py
- dojo/api_v2/schema/utils.py
- dojo/api_v2/views.py
- dojo/unittests/test_rest_framework.py
**Note**
Follow-up to #3154. I decided to open a new PR as mentioned since we changed a lot since then and it was easier (avoiding rebasing, etc.). Feel free to close the old PR when you think that it's not useful anymore.
**Summary**
This PR add two new components to the APIv2
1. Prefetching Mixins : We introduce two new mixins that can be used in place of their standard counterparts found in the django API. Both mixins add to the endpoints they target (read and list) the support for prefetching fields at relational depth 1. The fields that can be prefetched are those that are represented by One-to-One and One-to-Many relationships. Invalid field are simply ignored. 
The prefetched data is returned in the response under the top-level attribute `prefetch`. This attribute acts as a form a …
> [APIv2] Prefetch Mixins + Composable Swagger Schema

- dojo/templates/dojo/findings_list_snippet.html
- dojo/templates/dojo/view_test.html
When wanting to look at a glance or eventually take a screenshot, seeing the jira bug does not help much.
This PR reverts to the old display we used to have.
> Findings list: Display jira key instead of jira bug icon

- .github/workflows/flake8.yml
- .github/workflows/integration-tests.yml
- .github/workflows/k8s-testing.yml
- .github/workflows/new-release-tag-docker.yml
- .github/workflows/unit-tests.yml
- Dockerfile.busybox
- Dockerfile.django
- Dockerfile.integration-tests
- docker-compose.override.integration_tests.yml
- docker-compose.override.unit_tests.yml
- docker-compose.override.unit_tests_cicd.yml
- docker/entrypoint-integration-tests.sh
- docker/entrypoint-unit-tests.sh
TL;DR;
All tests in GitHub Actions have become a lot faster. 
Integration tests before:
After:
Others are also a couple of minutes faster each.
Changes:
- Use Docker Layer Caching. If we only change some code, all the expensive build steps are cached (pip install -r requirements.txt etc)
- Build images in parallel and use artifact upload/download to pass on to the next job (in the same workflow)
- Use dummy image for initializer, celery(worker|beat) and nginx on unit tests
- Finetune Dockerfile.xxxx to make sure as much layers as possible can be cached
- Don't start any containers that are not needed for unit tests
> GHA: Docker build caching and other speed improvements

- dojo/settings/settings.dist.py
- dojo/tools/snyk/parser.py
- dojo/unittests/test_snyk_parser.py
This PR addresses the following changes regarding deduplication of Snyk Findings:
- Add Snyk issues as "static_findings"
- Add "unique_id_from_tool" field
- Generate "file_path" field from the vulnerable path of the component ("from" attribute of the JSON report). We remove the versions of the components in the vulnerable path in order to allow deduplication across different version of the same PRODUCT.  
- Set Snyk deduplication algorithm to DEDUPE_ALGO_HASH_CODE
- Set fields for computing Hash Code. 
- Updated unit test
> Snyk findings: deduplication enhancements

- dojo/notifications/helper.py
make notifications synchronous due to bug in django-tagulous, see #3677
> notifications: make them synchronous

- dojo/db_migrations/0066_django_tagulous.py
make tagulous migration work with (legacy) products without a product type. (fixes #3683)
if a product is found without a product type (prod_type==0), we create a `_tag migration lost and found` product type and attach the product to it.
this a rare case where updating an existing migration is harmless as we're not changing the database schema, just the data migration. this will only affect people for which the migration was failing.
for those people, you need to comment out the following part in `dojo/db_migrations/0066_django_tagulous.py`:
``` 
migrations.RunPython(copy_existing_tags_to_tags_from_django_tagging_field, migrations.RunPython.noop),
```
So basically everything before the first RunPython command.
> Fix tag migration for legacy products

- dojo/filters.py
- dojo/templates/dojo/view_finding.html
the recent generic file upload fields were not excluded from filters, so every page with a filter was loading metadata for all uploaded files in the database
> files upload: remove from filters

- docker/entrypoint-integration-tests.sh
- dojo/forms.py
- dojo/jira_link/helper.py
- dojo/product/views.py
- dojo/product_type/urls.py
- dojo/product_type/views.py
- tests/base_test_class.py
- tests/product_test.py
- tests/product_type_test.py
- tests/report_builder_test.py
while investigating #3653 I noticed that adding a product via the product type view is using different logic to initialize the forms 
no jira, no github, no checks, etc.
we should reuse the add product functionality for adding a new product from the side menu.
also adds some logging to help with #3653
> add product via prod_type: use normal add product logic

- dojo/forms.py
- dojo/settings/settings.dist.py
- dojo/tools/dependency_track/parser.py
- dojo/unittests/scans/dependency_track_samples/dependency_track_3.8.0_2021-01-18.json
- dojo/unittests/test_dependency_track_parser.py
fixes #3647
- add dedupe hash code config
- add file_path to make legacy dedupe happy
- add vuln_id_from_tool field
- make title format/value more useful
- allow .txt file uploads
- extend unit tests
> dependency track parser: fix dedupe, set hash code fields

- dojo/tools/fortify/parser.py
- dojo/unittests/test_fortify_parser.py
The date parser on the Fortify parser was not totally accurate because of the punctuation used within the report. The `dateutil` parser would receive an input like `Oct31,2020,` and it would record the date in dojo as October 21, 2021. Instead, the parser will get an input of `Oct.31.2020` and the date will be recorded on the finding correctly.
> Fix date format on Fortify parser

- tests/dedupe_test.py
in the dedupe test there could be cases where the integration test was failing because it couldn't find the "No findings" text because the datatables initialization wasn't finished
> integration tests: wait for findings datatable

- docker/entrypoint-initializer.sh
- docker/wait-for-it.sh
The initializer takes about 1m55s to initialize the database. Not too bad if you do this once in your lifetime. 
But it adds up on every test run on GitHub actions. And locally when you want to test a PR, it keeps you waiting.
Turns our there are two quick wins here:
- Load all fixtures in a single `loaddata` command, turns out to be a lots faster (~40s saved)
- Don't run `buildwatson`, there is no need to reindex an empty database (~4s saved)
> initializer: import fixtures all at once, skip watson build

- dojo/tools/awssecurityhub/parser.py
> AWS Security Hub: set 'active' flag default to False

- dojo/api_v2/views.py
fixes #3679
a recent PR changed the error handling of the api v2 to catch everything and wrap it in a parseerror.
this leads to all exceptions being turned into a 400 error which means:
- the exception is not logged
- the exception is not returned in the api response
- the response code is 400 instead of 500 leading to wrong conclusions by users / log parsers
I tried to contact the original author of the reason for this try-catch, but I am not getting any reponse.
This PR reverses it, which will help us and others, for example in #3725
> api v2: remove try-catch that swallows all exceptions

- dojo/api_v2/serializers.py
- dojo/engagement/views.py
- dojo/filters.py
- dojo/forms.py
- dojo/templates/dojo/view_eng.html
- dojo/test/views.py
Continuing on #2241
The version field for Test objects was not shown in similar ways as for engagements. And it wasn't possible to set it on import/reimports via the UI and also not via reimport in the API v2.
> test.version: add missing places in UI, filters and importers

- tests/base_test_class.py
to avoid ERR_INSUFFICIENT_RESOURCES errors
source: https://developers.google.com/web/tools/puppeteer/troubleshooting
> integration tests: use --disable-dev-shm-usage to start chrome

- dojo/filters.py
Add the ability to filter tags of all objects instead of just findings. For example, when generating an engagement report, some tests might be tagged to be reported while others are tagged to be excluded. Only one test tag needs to be specified instead of tagging each finding in the test to be reported. This policy also applies to products and engagements.
> Allow Findings filter by tags of all object levels

- dojo/api_v2/views.py
check for authorized products was missing the product_Type claus for the TestsViewset endpoint on the api leading to some tests not being returned even though authorized on the product_type level
> api: fix authorized product allowance for Test retrieval

- helm/defectdojo/templates/django-ingress.yaml
I got some 
```  unknown field "kubernetes.io/ingress.class" in io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta, ValidationError(Ingress.metadata): unknown field "kubernetes.io/tls-acme" in io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta, ValidationError(Ingress.metadata): unknown field "nginx.ingress.kubernetes.io/proxy-body-size" in io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta, ValidationError(Ingress.metadata): unknown field "nginx.ingress.kubernetes.io/proxy-read-timeout" in io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta, ValidationError(Ingress.metadata): unknown field "nginx.ingress.kubernetes.io/ssl-redirect" in io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta]```
When updating the chart. 
The `annotations` is already with 2 indents, so below needs to be `4` and the leading …
> Fix helm chart

- dojo/api_v2/permissions.py
- dojo/api_v2/serializers.py
- dojo/api_v2/views.py
- dojo/risk_acceptance/api.py
[CWE-284](https://cwe.mitre.org/data/definitions/284.html)
The API v1 and v2 are lacking appropriate access controls.
Both APIs v1 and v2 allowed to retrieve findings, endpoints and other data for which a user was not authorized. The main endpoints affected are the ones to generate report, retrieval of notes, retrieval of endpoints as well as nested objects inside endpoints.
We have added additional authorization checks to fix this in APIv2. APIv1 being deprecated and disabled by default since 1.12.0, it shoud no longer be used. APIv1 has not been and will not be fixed. We recommend to all users to switch to APIv2 for continued support and security fixes, and to report bugs or missing features to the project.
* Disable untrusted users.
* Disable APIs. APIv1 is disabled by default since …
> Security fixes for reports/notes/enpoints via APIv2

- dojo/tools/gitlab_dep_scan/parser.py
- dojo/unittests/scans/gitlab_dep_scan/gl-dependency-scanning-report-1-vuln-missing-component.json
- dojo/unittests/scans/gitlab_dep_scan/gl-dependency-scanning-report-2-vuln-missing-component.json
- dojo/unittests/tools/test_gitlab_dep_scan_parser.py
1. Improve GitLab dependency scanning parser, adding component name and version for the findings.
2. Removed SAST components, since they are not present in this kind of report.
Current findings from GitLab dependency scanning have this structure:
Now they will appear as:
> Improve GitLab dependency scanning parser

- dojo/forms.py
The max characters in the UI form element for Product name was 50 but the model and API is 255 - see [here](https://github.com/DefectDojo/django-DefectDojo/blob/master/dojo/models.py#L617).
This PR makes the UI max the same as the others.
Docker image mtesauro/defectdojo-django:test-pr was built successfully to test the PR and ensure the UI worked as expected.
> Updated UI product name max chars to match model and API

- dojo/engagement/views.py
- dojo/templates/dojo/view_risk_acceptance.html
two bugs fixed:
- when adding a risk acceptance with a note, a many2many relationship related error occurred
- the 'e' keydown event (to edit the risk acceptance) conflicted with the notes textarea (works fine on every other page we use the same construct)
> risk acceptance: fix notes bugs

- dojo/tools/dsop/parser.py
- dojo/unittests/tools/test_dsop_parser.py
- requirements.txt
Refactor DSOP parser to not use pandas.
Fix one bug that don't detect CVE for Twistlock CVE data.
Need https://github.com/DefectDojo/django-DefectDojo/pull/3763 first
> DSOP parser: remove pandas and fix twistlock CVE

- dojo/filters.py
- dojo/metrics/views.py
- dojo/models.py
- dojo/unittests/test_metrics_queries.py
- dojo/utils.py
This PR builds on the unit tests merged in #3743 (which assert on the number of ORM queries made in the metrics endpoint), and updates the implementation to decrease the count of queries. This is aided by splitting the queries in to separate functions from the main view function, which might be a technique to use on the additional metrics views.
(This builds on original PR #3438. Since several of the changes in #3438 were addressed in #3549, this separates out the remaining changes into a new clean PR.)
> Metrics query optimizations

- dojo/product/views.py
the products list should only prefetch github config data if github integration is enabled.
> products: only prefetch github data if enabled

- dojo/product_type/views.py
There was a count query that counted all the authorized users for each product type when showing all product types. The result is never used, so the count can be omitted.
> product types: remove unused count prefetch

- dojo/jira_link/views.py
webhook had some copy and paste madness causing issues when un-accepting a finding.
> jira webhook: fix risk acceptance handling

- dojo/settings/settings.dist.py
The Dependency Track scanner was configured to use `'component'` in its dedupe hashcode, but that field does not exist and is not in `HASHCODE_ALLOWED_FIELDS`. As a result deduplication falls back to default fields, with suboptimal results. Most likely `component` was a typo of `component_name` here (could also add the component version like other scanners, but [as the parser documents](https://github.com/DefectDojo/django-DefectDojo/blob/08bc2f906b34cd6f76f5abc4e5e6d801fa556bbd/dojo/tools/dependency_track/parser.py#L130), DT does not always supply a version).
> Fix deduplication hashcode fields for Dependency Track scanner

- dojo/templates/dojo/product_type.html
- dojo/templates/dojo/view_product_type.html
This PR makes the UI for product types nicer. The attributes for critical product and key product have been shown as True or False in the list of product types and when viewing a single product type. With this PR they are shown as a red cross or a green tick, similar to the boolean fields in the list of users.
> Show boolean fields in product types as icons

- dojo/product/views.py
- dojo/test/views.py
tags were not stored for findings created manually via the UI
> store tags for new (ad hoc) findings

- dojo/tools/anchore_engine/parser.py
- dojo/unittests/scans/anchore/many_vulns_2.4.1.json
- dojo/unittests/tools/test_anchore_parser.py
Some recent version of anchore had renamed one attribute `imageDigest` to `image_digest`
This break the current parser.
> anchore parser: Fix image_digest/imageDigest error

- dojo/jira_link/views.py
Adding a few lines to help in debugging without full debug turned on.
As it turns out, the findings were not saved? I could reproduce that with `finding.save()` calls, the finding status did reflect the jira status, but not without.
> finding.save() + add logging of the JIRA issue key to jira webhook

- dojo/jira_link/views.py
Linked to #3839 forgot to remove one of the `finding.save()`
> Quick fix to remove a useless call to finding.save()

- dojo/api_v2/serializers.py
in the api the test.id field was already returned, but in a way that it didn't show up in the swagger docs. now we add it as a serializer field officially so the docs are correct.
> import_scan: add test response field to swagger docs

- dojo/api_v2/serializers.py
- dojo/test/views.py
- dojo/unittests/dojo_test_case.py
- dojo/unittests/test_import_reimport.py
Fix issue https://github.com/DefectDojo/django-DefectDojo/issues/3848 regarding the reimport of reports where previous findings marked as false positive and/or out of scope are re-activated instead of ignored. Now the history of false positive and out of scope findings is properly preserved.
> Reimport: keep false positive and out of scope history #3848

- Dockerfile.integration-tests
- Dockerfile.nginx
node v14 is the current/active LTS version, so we should start using that.
also bumps yarn to the latest version
includes a small optimization to only update the newly added APT repositories and not update ALL apt repositories again
> node/yarn: update to v14 and 1.22.10

- dojo/jira_link/helper.py
- dojo/management/commands/rename_whitesource_findings.py
- dojo/management/commands/test_celery_decorator.py
- dojo/notifications/helper.py
- dojo/risk_acceptance/helper.py
- dojo/settings/settings.dist.py
- dojo/tasks.py
- dojo/tools/tool_issue_updater.py
- dojo/utils.py
Fixes https://github.com/DefectDojo/django-DefectDojo/issues/3865
Now shows
```
$ docker-compose exec celerybeat sh -c 'celery -A dojo inspect registered'
[15/Feb/2021 09:12:31] INFO [dojo.models:3356] disabling audit logging
-> celery@9f983fab23f5: OK
[...]
* dojo.risk_acceptance.helper.expiration_handler
[...]
```
and command runs
```
$ docker-compose exec uwsgi /bin/bash -c 'python manage.py risk_acceptance_handle_expiration'
[15/Feb/2021 09:12:55] INFO [dojo.models:3356] disabling audit logging
[15/Feb/2021 09:12:58] INFO [dojo.risk_acceptance.helper:141] expiring 0 risk acceptances that are past expiration date
[15/Feb/2021 09:12:58] INFO [dojo.risk_acceptance.helper:150] notifying for 0 risk acceptances that are expiring within 10 days
```
> Fix risk acceptance celery handler + align @task decorators

- dojo/settings/settings.dist.py
One can host DefectDojo under a sub-directory (Ex. example.com/defectdojo) by modifying `DD_URL_PREFIX`, `DD_STATIC_URL`, and `DD_LOGIN_REDIRECT_URL`, but the Login URL also needs to be changed and there is currently no way of easily doing so.
> Allow Login URL to be changed

- dojo/engagement/views.py
- dojo/templates/dojo/checklist.html
When trying to edit a previously completed checklist, it was not loaded and instead the user had to start with an empty checklist again. With this fix, the checklist will be loaded and the user can continue where she stopped before.
> Fix editing of Engagement checklist

- dojo/authorization/authorization_decorators.py
- dojo/product/views.py
- dojo/product_type/views.py
Further tests on the merged new authorization system showed three areas, where the behaviour was not exactly the same as before when old authorization is still active:
- dojo/authorization/authorization_decorators.py: Call legacy user authorization, otherwise non-staff users can't view product types where they are an authorized user
- dojo/product/views.py: Staff users are allowed to add new products
- dojo/product_type/views.py: Don't save product type members
> Auth V2: three fixes for the new autorization system

- setup.py
Related slack thread: https://owasp.slack.com/archives/C014H3ZV9U6/p1613934621008200
[jsonlines](https://pypi.org/project/jsonlines/) - it looks like this is the package that was intended. That is the one referenced in requirements.txt
[json-lines](https://pypi.org/project/json-lines/) - this is the one that it currently points to in the master branch.
This PR updates to the proper package and most recent version.
> fix typo in setup.py for jsonlines

- dojo/engagement/views.py
- dojo/filters.py
- dojo/finding/views.py
- dojo/home/views.py
- dojo/metrics/views.py
- dojo/templates/base.html
- dojo/templates/dojo/dashboard.html
- dojo/templates/dojo/snippets/engagement_list.html
- dojo/unittests/test_dashboard.py
This PR fixes #3749 and a bunch of other bugs related to the dashboard. See the commits' messages for some details:
* UI: fix filtering findings by "Risk Accepted", "Acceptance Date", "Risk Acceptance Reporter". Previously they were wrongly filtered by `test__engagement__risk_acceptance`. Now they are correctly filtered by `risk_acceptance`.
* UI: allow filtering closed and accepted findings by "Duplicate".
* UI: allow not staff users to view closed and accepted findings. (They already were able to view all findings.)
* Tests: add tests for the dashboard.
* UI: fix the dashboard.
* Refactor: `dojo.home.views`. (No semantic changes.)
* UI: fix the "Products" and "Metrics" sidebar menus. Move the default menu item to the top.
* UI: fix the "Engagements" sidebar menu a …
> Make the dashboard consistent

- dojo/urls.py
When hosting DefectDojo under a sub-directory, the URL for API V2 documentation is broken since it doesn't use the URL_PREFIX value. 
If `DD_URL_PREFIX` is set to 'defectdojo/', then the URL should be https://example.com/defectdojo/api/v2/doc/
> API V2 Documentation should use URL Prefix (if set)

- dojo/finding/views.py
- dojo/templates/dojo/finding_related_list.html
- dojo/templates/dojo/paging_snippet.html
- dojo/templates/dojo/view_finding.html
small bugfix after #3812 to avoid duplicate initialization of similar findings table when viewing duplicate or original findings.
> aftercare: fix datatables viewing duplicate findings
