DefectDojo/django-DefectDojo

dojo/filters.py

This merge request introduces a new feature to the Report Builder.
It enables users to filter findings based on the lifecycle of a product.
The main use case is to provide the possibility to generate reports covering only production-grade products.
Use cases tested manually:
* no value chosen: displays all findings
* all values chosen: same, displays all findings
* "production" lifecycle chosen: only products with lifecycle "production" are taken into account
Update not needed for this minor improvement.

[ENHANCEMENT] Add Product Lifecycle filtering to Report Builder

---

dojo/api_v2/views.py
dojo/urls.py

Swagger is loading OpenAPI schema from `.../api/v2/oa3/schema/?format=json`. Bigger file, longer loading.
This PR define custom `OpenApiJsonRenderer` which decreases the size of the OpenAPI definition schema.
How? Default JSON using default `indent=4` which generates a lot of whitespace noise - easier for humans to read but useless for computers.
Plus I replaced the default schema from YAML with smaller JSON.
Fun facts about default renderer:
- You are not able to set a higher indent than 8 (a higher number will be downscaled to 8) - makes sense otherwise, it would be a perfect target for DOS; I didn't override this behaviour
- Even if you set indents in the HTTP header, you are not able to force the renderer to avoid print at least one space newline (compare 1014219 vs 708145)
Before …

OpenAPI schema: Use renderer with small size by default

---

dojo/static/dojo/css/dojo.css
dojo/templates/dojo/view_risk_acceptance.html

[sc-3141]
This bugfix shows the Add selected Findings button in a visible color  in /engagement/id/risk_acceptance/id/edit url
now it shows like the following.

fix button color in risk acceptance bug

---

dojo/settings/settings.dist.py

Addressing https://github.com/DefectDojo/django-DefectDojo/issues/7867
This is improving the customization via env variables for hashcode field configurations, and deduplication algorithms, to allow for unknown scanners (not hardcoded in `settings.dist.py`)

Improve DD_DEDUPLICATION_ALGORITHM_PER_PARSER DD_HASHCODE_FIELDS_PER_SCANNER

---

dojo/templates/dojo/view_finding.html

Show Vulnability ID from tool if defined
Defined:
Not defined:

UI: Show Vuln ID from tool

---

dojo/tools/sonarqube/parser.py
unittests/scans/sonarqube/sonar-table-in-table-with-whitespace.html
unittests/tools/test_sonarqube_parser.py

[sonar-report 3.1.1](https://github.com/soprasteria/sonar-report/releases/tag/3.1.1) has somechange in report template. It leads to some information parsed not correctly as Severity and some whitespace remains. 
See: [https://github.com/soprasteria/sonar-report/commit/7dab559e7ecf9ed319345e9262a8b160bd3af94f](https://github.com/soprasteria/sonar-report/commit/7dab559e7ecf9ed319345e9262a8b160bd3af94f)
This pull request fixes the Severity compare and removes some whitespace lead and trail of properties. 
I added a new Test for the new template format and ran `unittests.tools.test_sonarqube_parser.TestSonarQubeParser` to make sure that works with old unitest.
**Checklist**
Please …

Fixbug: sonarqube severity property and remove sonarqube whitespace lead and trail properties

---

README.md

Just cleaning up some broken links, typos, formatting, etc. in the main README.

Fixing README links and formatting

---

helm/defectdojo/templates/celery-beat-deployment.yaml
helm/defectdojo/templates/celery-worker-deployment.yaml

This can be useful to use pod affinity/antiaffinity for celery components.

Add subcomponent labels for celery beat and worker helm templates

---

docker/entrypoint-uwsgi-dev.sh
dojo/user/views.py

Add some error logging to SMTP server failures when attempting to reset user password
```
[01/Dec/2023 03:15:20] ERROR [dojo.user.views:647] SMTP Server Connection Failure: [Errno 111] Connection refused
```

Add logging statement for failed password reset validation logic

---

dojo/finding/views.py

Corrects the order of object saves to prevent the following error:
```
File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 56, in inner
^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/dojo/authorization/authorization_decorators.py", line 45, in _wrapped
return func(request, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/dojo/finding/views.py", line 2081, in add_template
finding_helper.save_vulnerability_ids_template(
File "/app/dojo/finding/helper.py", line …
```

Finding Template: Correct save ordering

---

dojo/filters.py

Correct stack trace:
```
[04/Dec/2023 10:57:38] ERROR [dojo.api_v2.exception_handler:36] 'Product' object has no attribute 'burprawrequestresponse_set'
File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
response = handler(request, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "build/bdist.linux-x86_64/egg/pro_enhancements/finding/api/views.py", line 46, in list
File "/usr/local/lib/python3.11/site-packages/drf_spectacular/drainage.py", line 193, in wrapped_method
return method(self, request, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/dojo/api_v2/prefetch/mixins.py", line 21, in list
results.append(serializer.to_representation(entry))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File …
```

Correct SLA filter for Finding API

---

.github/labeler.yml
.github/workflows/pr-labeler.yml

Making changes to the `labeler.yml` file to upgrade to [`v5` of the labeler action](https://github.com/actions/labeler/releases/tag/v5.0.0), which requires a new format.
See the docs here for more details: https://github.com/actions/labeler#match-object
[sc-3543]

Updated actions/labeler version, labeler.yml format

---

dojo/jira_link/helper.py

this will fix #8785
this will fix #8785 , by adding the jira.project default_assignee (when defined) to the issue creation api call instead of adding a second step to do it.
this was tested in 2.23.2 and allowed to create issues in a Jira project where no 'unassigned' or 'automatic' assignee was allowed.
**Checklist**
- Import Scans (for …

Update helper.py to fix #8785

---

dojo/tools/codechecker/parser.py
dojo/tools/dependency_check/parser.py
dojo/tools/vcg/parser.py
unittests/test_parsers.py

unittest to catch errors described in #9024 and #9017

add unittest for .read() and utf-8 #9024

---

dojo/tools/whitesource/parser.py
unittests/scans/whitesource/okhttp_one_vuln.json
unittests/tools/test_whitesource_parser.py

I've extended the Whitesource parser so that it stores CVSS score and vector in the corresponding fields of the generated findings.
I've extended the `tools.test_whitesource_parser.TestWhitesourceParser.test_parse_file_with_one_vuln_has_one_findings` to check these two new filled fields.
n/a
**Checklist**
- enhancement
- performance
- feature
- bugfix
- dependencies
- settings_changes (when the PR …

Store CVSS score and vector in Whitesource imports

---

dojo/filters.py

This merge request introduces an "Unknown" option to the existing filters in Product and Engagement lists for:
* Product lifecycle,
* Business Criticality,
* Platform, 
* Origin.
This is how it looks like:
It follows the scheme already used in other filters, like the boolean ones:

[ENHANCEMENT] Allow filtering Products and Engagements on unset properties

---

dojo/wsgi.py

Drop
```python
django-defectdojo-uwsgi-1         | Can't listen for client connections: [Errno 98] Address already in use
django-defectdojo-uwsgi-1         | Traceback (most recent call last):
django-defectdojo-uwsgi-1         |   File "/app/dojo/wsgi.py", line 50, in <module>
django-defectdojo-uwsgi-1         |     debugpy.listen(("0.0.0.0", debugpy_port))
django-defectdojo-uwsgi-1         |   File "/usr/local/lib/python3.11/site-packages/debugpy/public_api.py", line 31, in wrapper
django-defectdojo-uwsgi-1         |     return wrapped(*args, **kwargs)
django-defectdojo-uwsgi-1         |            ^^^^^^^^^^^^^^^^^^^^^^^^
django-defectdojo-uwsgi-1         |   File "/usr/local/lib/python3.11/site-packages/debugpy/server/api.py", line 143, in debug
django-defectdojo-uwsgi-1         | …
```

Debug: Avoid useless error in logs

---

dojo/models.py

Fix for vulnerabilities not included in host/endpoint views after reopening. More info: https://github.com/DefectDojo/django-DefectDojo/issues/8450
After commenting the lines on test environment, vulnerabilities that were reopened are properly shown on endpoint and host view. I was trying to find out how "status_finding__mitigated" filter works but couldn't find it. In my opinion it is not necessary to check it when "mitigated__isnull" filter is also verified.

Fix for vulns not included in host/endpoint views after reopening

---

.github/workflows/fetch-oas.yml
.github/workflows/release-drafter.yml

In the future, I would like to add API changes to release notes. As preparation, I would like to release OpenAPI Specifications with each release as assets.

Add OpenAPI Specification to Release Assets

---

.github/workflows/release-3-master-into-dev.yml

Any update of the timestamp in the release-note file every time is not necessary.
First "after release" change is enough.
This kind of change is useless:
https://github.com/DefectDojo/django-DefectDojo/pull/9143/files#diff-99337e27a744dd0c3795c83c1dc92a777e26911585e1707eceeff96d61ffad57R4

Docs: "Create upgrade notes to documentation" only once

---

dojo/models.py

Reverts DefectDojo/django-DefectDojo#9077
@WojTecH94 apologies for the revert here. I missed the red X that unit tests were failing when approving this PR

Revert "Fix for vulns not included in host/endpoint views after reopening"

---

dojo/tools/awssecurityhub/parser.py
unittests/tools/test_awssecurityhub_parser.py

Add component_name to AWS SecurityHub parser findings.

:tada: added component_name to AWSSecurityHub

---

dojo/models.py

This customizes the built-in (and enabled by default) Django Admin interface, and adds a visual way to add, remove, and modify notifications in DefectDojo.
This is a workaround for #9192.
This is how the notification list will look like:
This is how the a single notification editor will look like:
Tested manually.
Django Admin functionality is not described in the documentation.

Django Admin pages for editing Notifications

---

dojo/settings/settings.dist.py
requirements.txt

The first step to removal of drf-yasg
If somebody uses `DD_DEFAULT_SWAGGER_UI=False` (a.k.a. do not load swagger from CDN but from static resources), this will not point the user to drf-yasg statics but to drf_spectacular_sidecar.
Tested locally.
Inspired by https://drf-spectacular.readthedocs.io/en/latest/readme.html#self-contained-ui-installation

API: replace local swagger (drf-yasg -> sidecar)

---

dojo/tools/trivy/parser.py
unittests/scans/trivy/issue_9092.json
unittests/tools/test_trivy_parser.py

:bug: fix trivy parser cvss score severity discrepance #9092

---

dojo/tools/burp_api/parser.py
unittests/scans/burp_api/fix_issue_9128.json
unittests/tools/test_burp_api_parser.py

:bug: Handle when Burp Rest API Json file contains binary

---

dojo/models.py
unittests/test_import_reimport.py
unittests/test_jira_import_and_pushing_api.py
unittests/tools/test_stackhawk_parser.py

- /app/dojo/models.py:2566: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
- ... DeprecationWarning: It is deprecated to return a value that is not None from a test case
- /app/unittests/tools/test_stackhawk_parser.py:243: DeprecationWarning: Please use assertRegex instead.

Fix DeprecationWarnings

---

.github/workflows/release-x-manual-helm-chart.yml

- Pinning of django images during a release. 
- fix to show the real name of "release-X: Release helm chart" in the list of actions

Pinning of django versions into a helm release

---

dojo/tools/ssh_audit/parser.py
unittests/scans/ssh_audit/bug_fix.json
unittests/tools/test_ssh_audit_parser.py

fix a Keyerror:
kex['notes']['info']  is not available here.

:bug: fix error 500 for ssh-audit

---

dojo/finding/views.py
dojo/notifications/helper.py
dojo/templates/notifications/alert/review_requested.tpl
dojo/templates/notifications/mail/review_requested.tpl
dojo/templates/notifications/msteams/review_requested.tpl
dojo/templates/notifications/slack/review_requested.tpl
dojo/utils.py

This PR does the following:
- Implements notification templates for finding review requests
- Overrides user notification settings for request reviews with system level notification settings
- Before this change, if the system level notifications for finding review requests were enabled, but a given user did not have the notifications enabled on their personal scope, then that user would not receive a notification. This means that the system level notifications were being ignored for this action
- Clean up the `get_full_url` function to remove redundancy with another function
I do not have access to a teams instance to test this template. I modeled it as closely to other teams notifications templates as I could

Improve Request Review Notifications

---

dojo/tools/trivy/parser.py
unittests/scans/trivy/issue_9263.json
unittests/tools/test_trivy_parser.py

Fix #9263 
- Makes None Type in CVSS Score to "Info Finding"
- Adds CVSSv2

:bug: None Type in cvss score in Trivy #9263

---

dojo/fixtures/dojo_testdata.json
dojo/settings/settings.dist.py
dojo/tasks.py
unittests/test_flush_auditlog.py

This PR creates the possiblity to recycle the auditlogs that are generated by DefectDojo.
You can simply specify a retention period in the settings-file DD_AUDITLOG_FLUSH_RETENTION_PERIOD. If you set the value to "-1" the flushing is disabled.
1 Point to highlight is that I explicitly used the raw_delete method since we had a lot of trouble with the performance of the default delete. I also think that it is feasible here, since we do not have external references to the log-entries.
There are 3 more tests added in the unit-tests that should cover the most important points of the new feature (check if disabling works, check if logs are flushed, check if only the logs are flushed that fall into the specified period)
**Checklist**
This checklist is for your …

Feature: Add Auditlog Retention and Cleanup

---

dojo/tools/qualys/parser.py
unittests/tools/test_qualys_parser.py

Add cvss value to finding and only overwrite values if not already set
This is because of XML Report Layout of Qualys. It has CVSS Values on concrete Finding and in the Knowledgebase.   The values in the concrete Finding are more accurate and are parsed at first. It would be much better to stick with those values and only use the ones from the Knowledgebase if CVSS values from concrete finding are missing
**Checklist**

QualysParser: add cvss value to finding

---

helm/defectdojo/templates/initializer-job.yaml
helm/defectdojo/values.yaml

Closes #9267
This PR adds the option to add additional labels to the initializer job. This can be done in the values file like:
```yaml
initializer:
labels: {
key: value
}
```
Contrary to what I mentioned in the Issue, it is already possible to add labels to the Deployment Pods via `podLabels`, see [here](https://github.com/DefectDojo/django-DefectDojo/blob/master/helm/defectdojo/values.yaml#L65-L68). Which only made it necessary to add the option to the Job aswell. 
I saw 3 options to make this possible: 
1. Add `labels` directly to initializer, same as annotations and therefore scope the additional labels only to the initializer job (which is as of writing this the only job).
2. Add `jobLabels` as a global value, same as `podLabels`. This would be more future-proof in …

:sparkles: Add option for additional labels on initializer

---

.github/workflows/fetch-oas.yml
.github/workflows/release-drafter.yml

- The test stack was built on top of the `dev` branch by default. It needs to be built from the version tag.
- Wrong code was used, wrong tags have been placed to OpenAPI Speficications
- Build of images is skipped, docker hub images are used (time save).
```
$ curl -L https://github.com/DefectDojo/django-DefectDojo/releases/download/2.29.4/oas.yaml | head
info:
title: Defect Dojo API v2
version: 2.30.0-dev
description: Defect Dojo - Open Source vulnerability Management made easy. Prefetch
related parameters/responses not yet in the schema.
paths:
/api/v2/api-token-auth/:
post:
operationId: api_token_auth_create
```
```
```

Release-drafter: Checkout to version

---

dojo/tools/nikto/parser.py
unittests/scans/nikto/issue_9274.json
unittests/tools/test_nikto_parser.py

🐛 Nikto: Support v2.5.0 format

---

dojo/templates/dojo/findings_list_snippet.html
dojo/templates/dojo/view_finding.html

[sc-2859]
This feature allows the user see the test_type information when the found_by is not available.
In the Findings list:
In the Finding view:

Update finding templates to use test_type rather then found_by

---

dojo/tools/veracode/json_parser.py

Updates the license mapping in the veracode JSON parser to correctly map the Non-OSS categorization to 0 rather to 5
[sc-3900]

Veracode: Update license mapping

---

Dockerfile.django-alpine
Dockerfile.django-debian
Dockerfile.integration-tests-debian
docker/entrypoint-celery-worker.sh
docker/entrypoint-initializer.sh
docker/entrypoint-integration-tests.sh
docker/entrypoint-unit-tests-devDocker.sh
docker/entrypoint-unit-tests.sh
docker/entrypoint-uwsgi-dev.sh
docker/entrypoint-uwsgi.sh
docker/entrypoint.sh
docker/secret-file-loader.sh
dojo/settings/settings.dist.py

Follow the security recommendation for Kubernetes deployments: https://django-environ.readthedocs.io/en/latest/tips.html#docker-style-file-based-variables
Local test:
```diff
diff --git a/docker-compose.override.debug.yml b/docker-compose.override.debug.yml
index 40bb4e4c3..2c651eff1 100644
--- a/docker-compose.override.debug.yml
+++ b/docker-compose.override.debug.yml
@@ -8,8 +8,12 @@ services:
environment:
DD_DEBUG: 'True'
DD_ADMIN_USER: "${DD_ADMIN_USER:-admin}"
-      DD_ADMIN_PASSWORD: "${DD_ADMIN_PASSWORD:-admin}"
+      DD_ADMIN_PASSWORD_FILE: "/run/secrets/dd_admin_password"
DD_EMAIL_URL: "smtp://mailhog:1025"
+      DD_SECRET_KEY_FILE: "/run/secrets/dd_secret_key"
+    secrets:
+      - dd_admin_password
+      - dd_secret_key
ports:
- target: ${DD_DEBUG_PORT:-3000}
published: …
```

Support "_FILE" environmental variables

---

dojo/risk_acceptance/helper.py
tests/finding_test.py

When setting or removing a risk exception on a given finding, the endpoint statuses were not updated. With this PR, endpoint statuses on a finding that is being risk accepted will have a status of mitigated + risk accepted. When the risk exception expires or is removed, the endpoint statuses for a given finding will revert to active to match the finding
[sc-3960]

Endpoint Status: Accommodate Risk Exceptions

---

dojo/tools/kiuwan/parser.py
unittests/scans/kiuwan/issue_9308.csv
unittests/scans/kiuwan/kiuwan_defects.csv
unittests/tools/test_kiuwan_parser.py

Updated the kiuwan parser to fix some imports. 
1. Added the file to the description to have a unique hash for findings that are the same except the file name. This solves issue #9308
2. Added a check if the vulnerability column is present in the import. This solves issue #9307
After making the changes in the parser the import ran successfully for the attached import file from the issues.
Tested with larger CSV exports from kiuwan production instances as well.

Improve kiuwan import parser

---

dojo/tools/microfocus_webinspect/parser.py
unittests/tools/test_microfocus_webinspect_parser.py

:bug: MicroFocus WebInspect: Add better error handling

---

.github/workflows/fetch-oas.yml
.github/workflows/release-2-tag-docker-push.yml
.github/workflows/release-drafter.yml

This PR updates the structure and flow of the release drafter process. Now that OAS schemas are appended to each release object, it might be a better approach to make the release drafting process less event driven. Here is what the PR proposes:
- Remove the trigger to run the release drafter on pushes to master
- This is necessary as the docker images to generate the OAS schemas for a given release X are not public yet
- One approach is to build the docker images before generating the release, but this slows down the release process overall
- Explicitly run the release drafter workflow as step 2 of the release (this creates the the release, builds/uploads the helm chart, and pushes the newest images to dockerhub) only after the docker images have been pushed
- The OAS schema generator …

Restructure Release Drafter Flow

---

.github/workflows/gh-pages.yml
Dockerfile.nginx-alpine
Dockerfile.nginx-debian

This PR updates to Node 20.x since it is in LTS until May of 2026
I went through all of the major pages in the app and looked for console warnings/errors and did not find anything :) I believe this to be because yarn is being used as the package manager
[sc-3685]

Update to Node 20.x in all the places

---

dojo/tools/govulncheck/parser.py
unittests/scans/govulncheck/many_vulns_new_version.json
unittests/scans/govulncheck/many_vulns_new_version_custom_severity.json
unittests/scans/govulncheck/no_vulns_new_version.json
unittests/tools/test_govulncheck_parser.py

This Pull Request introduces several key enhancements to the `govulncheck` parser, aiming to provide more detailed and actionable vulnerability data within DefectDojo. The updates focus on enriching the parsed information with additional contextual details and traceability, making it easier for users to understand and act upon the findings.
Note : 
- Changes have been made to the parsing of the new `govulncheck` format. The old format is of course still supported.
- Feel free to provide any suggestions or feedback for further improvements; If any part of the code is unclear, I can add explanatory comments or even rewrite sections for better clarity and understanding.
**Key Changes** : 
1. **Richer finding title.** 
- The parser now constructs the title using a combination …

Enhancements to Govulncheck parser

---

dojo/views.py

Opening the file as bytes skips an extra step to encode the file
[sc-3999]

Open attached files as bytes

---

dojo/filters.py

[sc-4046]
https://github.com/DefectDojo/django-DefectDojo/issues/9414
Now the finding filters risk accepted was removed the duplicated
the remaining filter now shows `Expired` instead `Was`

remove duplicated risk accepted

---

dojo/templates/issue-trackers/jira_full/jira-description.tpl

When pushing a finding to JIRA, the CVSS score is already being passed, but the vector string is equally important

Add CVSS vector string to JIRA description

---

docs/content/en/integrations/notifications.md

1. This PR updates the Notifications documentation page with more info on how to create a Slack app, as well as a JSON app manifest to quickly configure the necessary permissions and bot settings.
For users looking to add a Slack integration to Dojo, using this manifest creates a bot with all required OAuth permissions as listed in docs. These are steps a user already has to take to get the Slack integration working, so using this manifest allows them to skip manual configuration and speeds this up.
User will still have to locate the OAuth Bot Access token and add it to DefectDojo to complete integration.
2. Also moved the Microsoft-teams paragraph to the correct heading.

advance notifications.md with expanded slack guide

---

dojo/templates/dojo/findings_list_snippet.html
dojo/templates/dojo/view_test.html

Update static finding favicon

---

docs/content/en/integrations/parsers/file/mend.md
docs/content/en/integrations/parsers/file/whitesource.md

Changes the title of Whitesource documentation to reflect Whitesource's rebrand to Mend.io .  See https://www.mend.io/ .
Also adds Parser documentation template along with link to Mend.io documentation for reference.

Update and rename whitesource.md to mend.md

---

dojo/importers/importer/importer.py

Importing the cvss module via:
```
from cvss import CVSS3
```
_and_ given a CVSS vector string such as:
```
cvss_vector_str = 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N'
```
the following severity calculation returns string values of, "None" instead of the expected string values of "Info":
```
cvss_obj = CVSS3(cvss_vector_str)
severities = cvss_obj.severities()
print(severities)
('None', 'None', 'None')
print(severities[0])
'None'
print(type(severities[0]))
<class 'str'>
```
This is quite a small change, however, if you want me to update `unittests/test_importers_importer.py`, please provide recommendations on the preferred approach.
**Checklist**
- [X ] Make sure to rebase your PR against the very latest `dev`.
- …

dojo/importers/importer/importer.py - Change "None" string to "Info" from cvss module when a CVSS vector string should evaluate to "Info"

---

dojo/tools/trivy_operator/parser.py
unittests/scans/trivy_operator/vulnerabilityreport_extended.json
unittests/tools/test_trivy_operator_parser.py

This feature allows adding Target, Class, PackagePath and PackageType already managed in trivy reports
related to:
**trivy-operator** [additionalVulnerabilityReportFields](https://github.com/aquasecurity/trivy-operator/blob/main/deploy/helm/values.yaml#L318C1-L320C42)
```
additionalVulnerabilityReportFields: ""
```

Trivy Operator Parser additionalVulnerabilityReportFields

---

docs/content/en/integrations/parsers/file/wfuzz.md
dojo/tools/wfuzz/parser.py
unittests/scans/wfuzz/issue_7863.json
unittests/tools/test_wfuzz_parser.py

:bug: WFuzz: Add additional severity mappings

---

docker/entrypoint-integration-tests.sh
docker/entrypoint-unit-tests-devDocker.sh
docker/entrypoint-unit-tests.sh
dojo/settings/settings.dist.py
tests/base_test_class.py

This PR sets more strict rules for test environments to be motivated to fix issues as soon we know about them.
It also adds some exceptions (`filterwarnings`) that need to be solved - they should be solved one by one to avoid large PR.
- `RemovedInDjango50Warning` - Fixed in https://github.com/DefectDojo/django-DefectDojo/pull/9491
- `invalid escape sequence.*`
- `'cgi' is deprecated and slated for removal in Python 3.13` - Fixed in https://github.com/DefectDojo/django-DefectDojo/pull/9108
- `DateTimeField .+ received a naive datetime .+ while time zone support is active.`
- `unclosed file .+`
For integration tests:
- `executable_path has been deprecated, please pass in a Service object`
- `use options instead of chrome_options`
- `desired_capabilities has been deprecated, please pass in …

Be strict about Warnings during testing

---

dojo/tools/github_vulnerability/parser.py
unittests/scans/github_vulnerability/github-vuln-version.json
unittests/tools/test_github_vulnerability_parser.py

The affected version from GitHub is not imported by the parser. I think this change is better than the one proposed in https://github.com/DefectDojo/django-DefectDojo/pull/9457 which just adds the range of impacted versions, and not the range of the vulnerable version detected.
Test added.

Parse GitHub vulnerability version

---

dojo/tools/sarif/parser.py

Currently SARIF parser looking for list of rules in `run["tool"]["driver"]` object.
Although SARIF report generated by https://github.com/github/codeql-action lists rules under `run["tool"]["extensions"]` object. This results in finding's CWE, Severity and Description not being populated with information according to the rule.
Now parser checks for driver object as usual but then also checks for extensions object ([link](https://docs.oasis-open.org/sarif/sarif/v2.1.0/errata01/os/sarif-v2.1.0-errata01-os-complete.html#_Toc141790782) to the SARIF specification). This way i was able to populate CWE, Severity and Description fields from the report of my CodeQL action. This is also may be useful for other scanners that populates extensions instead of driver

Fix SARIF parser with CodeQL rules

---

dojo/jira_link/helper.py

With the recent upgrade from the python third party library for jira from version 3.5.2 to 3.6.0, two methods were renamed/repurposed that we were relying on. This PR updates this part of the code to restore functionality
fixes #9509
[sc-4203]

Jira Server/DataCenter: Update meta methods

---

dojo/jira_link/views.py

In a situation where a screen requiring a comment during an issue transition, and comment will will be sent under the `issue_updated` event. Some times an additional event for `comment_added` would occur, but this was not a universal case. To achieve this adopted behavior, the following actions were taken:
- Move the original `comment_added` operations to a function
- Add an additional query for identical notes created in the last 30 seconds to remove the possibility of duplicated notes in the event both webhook events are captured
- Updated to safer dict access methods to reduce chances of exceptions
[sc-4202]

Jira Webhook: Catch comments from other issue updates

---

dojo/api_v2/serializers.py
dojo/forms.py
unittests/test_swagger_schema.py

Disallow the possibility of duplicate tool types
UI:
API:
```
{
"non_field_errors": [
"A Tool Type with the name already exists"
],
"message": "{'non_field_errors': [ErrorDetail(string='A Tool Type with the name already exists', code='invalid')]}"
}
```
[sc-4239]

Disallow duplicate tool types

---

dojo/templates/dojo/dashboard.html

URL redirects were behaving strangely without this leading slash. it seems it was missed when all the others were added
[sc-4182]

Engagement Surveys: Add missing leading slash

---

dojo/templates/dojo/engagement.html
dojo/templates/dojo/engagements_all.html
dojo/templates/dojo/snippets/engagement_list.html

[sc-2740]
This bugfix removes the overdue tag in the completed engagements that before showed it.

Fix "Overdue" tag still visible with closed issues

---

components/package.json
dojo/templates/dojo/dashboard-metrics.html
dojo/templates/dojo/endpoint_pdf_report.html
dojo/templates/dojo/engagement_pdf_report.html
dojo/templates/dojo/finding_pdf_report.html
dojo/templates/dojo/product_endpoint_pdf_report.html
dojo/templates/dojo/product_metrics.html
dojo/templates/dojo/product_pdf_report.html
dojo/templates/dojo/product_type_pdf_report.html
dojo/templates/dojo/test_pdf_report.html
dojo/templates/dojo/view_endpoint.html

[sc-2602]
Since this library will no longer be maintained, it has been removed to make the app be secure and without vulnerabilities.

Remove flot-axis JS library

---

dojo/settings/settings.dist.py

The Setting `USE_L10N` is overridden later in the `settings.dist.py`. It is not necessary to keep it as EnvVar because there is no real effect.

Remove DD_USE_L10N

---

dojo/settings/settings.dist.py

It looks like this was just some side-effect during other tests. It can be directly dropped.

Remove filterwarnings for "unclosed file"

---

docs/content/en/integrations/parsers/file/wfuzz.md
dojo/tools/wfuzz/parser.py
unittests/scans/wfuzz/one_finding_responsecode_missing.json
unittests/tools/test_wfuzz_parser.py

see issue https://github.com/DefectDojo/django-DefectDojo/issues/6182

:bug: WFuzz: Generalize severity mapping

---

docs/content/en/integrations/parsers/file/burp_dastardly.md
dojo/tools/burp_dastardly/__init__.py
dojo/tools/burp_dastardly/parser.py
dojo/tools/chefinspect/__init__.py
dojo/tools/gcloud_artifact_scan/__init__.py
dojo/tools/hcl_appscan/__init__.py
dojo/tools/humble/__init__.py
dojo/tools/kubeaudit/__init__.py
dojo/tools/ms_defender/__init__.py
dojo/tools/openvas/__init__.py
dojo/tools/redhatsatellite/__init__.py
dojo/tools/ssh_audit/__init__.py
unittests/scans/burp_dastardly/many_findings.xml
unittests/tools/test_burp_dastardly_parser.py

:sparkles: add burp dastardly

---

docker/entrypoint-unit-tests-devDocker.sh
docker/entrypoint-unit-tests.sh

There are no broken unittests. It is not needed run these tests separately.

Remove handling of broken unittests

---

dojo/tools/dependency_track/parser.py
unittests/scans/dependency_track/dependency_track_4.10_2024_02_11.json
unittests/tools/test_dependency_track_parser.py

This PR shall be merged after #9516 or #9520.
It adds support for importing the EPSS score from DependencyTrack files import.

🎉 importing epss score from DependencyTrack output

---

docs/content/en/integrations/parsers/file/asfd.md
docs/content/en/integrations/parsers/file/clair.md
docs/content/en/integrations/parsers/file/clair_klar.md
unittests/test_parsers.py

#9355 --> I forgot to adapt the docs in this PR

fix clair docs according to PR #9355

---

dojo/tools/awssecurityhub/parser.py
unittests/tools/test_awssecurityhub_parser.py

This PR should be merged after #9516.
It adds support for importing the EPSS score from AWS Inspector via AWS SecHub.

:tada: Importing EPSS score from AWS Inspector via AWS SecHub

---

dojo/engagement/views.py

If `import_scan` fails in the following block, `test` is not set. The user should be redirected to where he/she/they came from.
https://github.com/DefectDojo/django-DefectDojo/blob/d698a7a1ff2a914754a541140b236dd3092d7e8e/dojo/engagement/views.py#L732-L752
I suppose the user should be redirected to the mentioned place with the prefilled form (to avoid the necessity to refill it again). I need to know how to do it here.

Fix engagement/view if import fail

---

.github/workflows/pr-labeler.yml

Resync labels. For PRs which has been accidentally opened to/from the wrong branch.
E.g.:
- https://github.com/DefectDojo/django-DefectDojo/pull/9516
- https://github.com/DefectDojo/django-DefectDojo/pull/9500
- https://github.com/DefectDojo/django-DefectDojo/pull/9067
- https://github.com/DefectDojo/django-DefectDojo/pull/9490

Labeler: Add sync-labels

---

dojo/models.py
dojo/survey/views.py

When using questionnaires, deleting an an engagement/product/product-type will result In the following errors:
Engagement
```
[14/Feb/2024 13:56:06] INFO [django.request:241] OK: /engagement/256/delete
File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/base.py", line 306, in _commit
return self.connection.commit()
^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.ForeignKeyViolation: update or delete on table "dojo_answer" violates foreign key constraint "dojo_choiceanswer_answer_ptr_id_e9da2254_fk_dojo_answer_id" on table "dojo_choiceanswer"
DETAIL:  Key (id)=(62) is still referenced from table "dojo_choiceanswer".
```
Product/ProductType
```
[16/Feb/2024 17:59:23] ERROR [django.request:241] Internal Server Error: /product/1/delete
Traceback …
```

Questionnaires: Correct nested object deletions

---

dojo/jira_link/helper.py

A couple fields are overwritten by DefectDojo when findings are pushed to an existing jira ticket. This can be destructive for developers in the following ways:
- Priority: This field often reflects the timeline a particular issue may be fixed. Developers may have more specific context for why a vulnerability may not be as severe as initially thought.
- Labels: Labels could be used to sort issues in a given queue to determine who works on a given ticket. When a finding is pushed to jira again after creation, these new labels should not be overwritten
These fields should be respected to avoid stomping on any changes/process set by developers
[sc-4264]

Jira: Append labels and respect priority on update

---

dojo/endpoint/views.py
dojo/models.py

When visiting the "All Hosts" view, I was encountered with a 500 error page for the following exception:
```
File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 56, in inner
^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
return callback(request, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/dojo/endpoint/views.py", line 109, in …
```

Correct Endpoint "Hosts" views when the host field is `None`

---

dojo/db_migrations/0187_nessus_to_tenable.py
dojo/db_migrations/0197_parser_merge.py
dojo/db_migrations/0199_whitesource_to_mend.py

Fix #9600
If the user manually disabled TestType, it is not safe to run `get_or_create` with a static variable. It should be moved to `defaults`

Fix broken migration 0197

---

dojo/models.py

When attempting to export findings to a CSV/Excel report,  the following error is produced:
```
[20/Feb/2024 20:09:06] ERROR [dojo.reports.views:965] Error in attribute: can't compare datetime.datetime to datetime.date
[20/Feb/2024 20:09:06] INFO [django.request:241] OK: /reports/csv_export
File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 56, in inner
^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/dojo/reports/views.py", line 985, in csv_export
and (not …
```

CSV/Excel Report: Correct date/datetime comparison error

---

docs/content/en/integrations/parsers/file/npm_audit.md

As NPM_Audit files are not supported past v6, adding this note to documentation.  Currently NPM_Audit scans past v6 omit many relevant data fields from the JSON export, which creates 'stub Findings' which need to be updated through a different process.
Staging a docs update until we decide what to do: whether to update the NPM-audit parser to create those stub Findings or to leave things the way they are.

Extend npm_audit.md with unsupported v7 notice

---

dojo/search/views.py

When tagging objects in the formate of `metadata-key:metadata-value`, searching with the simple search operation will throw out the `metadata-value` portion due to the splitting of all colons in given search query. Splitting only on the first colon will correct this behavior
Before:
```
[25/Feb/2024 02:27:55] DEBUG [dojo.search.views:425] query:     tag:owner:someone product:prod
[25/Feb/2024 02:27:55] DEBUG [dojo.search.views:426] operators: {'tag': ['owner'], 'product': ['prod']}
[25/Feb/2024 02:27:55] DEBUG [dojo.search.views:427] keywords:  []
```
After:
``` 
[25/Feb/2024 02:28:24] DEBUG [dojo.search.views:425] query:     tag:owner:someone product:prod
[25/Feb/2024 02:28:24] DEBUG [dojo.search.views:426] operators: {'tag': ['owner:someone'], 'product': ['prod']}
[25/Feb/2024 02:28:24] …
```

Correct search queries containing colons

---

dojo/settings/settings.dist.py

Remote filterwarnings for "cgi is deprecated and slated"

---

dojo/templates/dojo/view_finding.html

This updates the EPSS score to display 2 decimal places of precision instead of 3 in the "view Finding" view to be consistent with its presentation in the "list Findings" view. Displaying 3 decimal places seems like overkill even if EPSS can go out to many decimal places, since it's technically **5** decimal places with the multiplication by 100 to get a percentage. I just forgot to post a comment about this on the original PR #9516 before it was merged.

Making EPSS float formatting consistent in 'view Finding'

---

dc-integration-tests.sh

Adding a `dc` helper script to run integration tests a bit easier. This script consists of docker compose commands borrowed from the unit test workflow.

Add integration tests script

---

dojo/api_v2/serializers.py

Fix #9643
There is still an open question: Is this the only place with this kind of bug?
Check analysis in https://github.com/DefectDojo/django-DefectDojo/issues/9643#issuecomment-1971291731

FindingGroupSerializer: not break schemas when JIRAIssue not available

---

dojo/metrics/views.py
dojo/product/views.py
dojo/templates/dojo/product_metrics.html
unittests/test_metrics_queries.py

There was some disparity regarding the flags that consist of a given status. A prime example is product type metrics only measuring verified findings while most of defectdojo does not. Unification of these queries to those in `dojo.finding.helper` not only makes status of a given finding more consistent from page to page, but it also will make any future changes to a status a much smaller lift, and reduce the chances of creating bugs
[sc-4459]

Metrics: Status unification

---

docs/content/en/integrations/parsers/file/snyk_code.md
dojo/settings/settings.dist.py
dojo/tools/snyk_code/parser.py
unittests/scans/snyk_code/single_project_many_vulns.json
unittests/scans/snyk_code/snykcode_issue_9270.json
unittests/tools/test_snyk_code_parser.py

[sc-4509]
A new `SnykCodeParser` was added and the deduplication is based on `ruleID` and `URI` (`file_path`).
The unittests for this parser were added as well.
https://github.com/DefectDojo/django-DefectDojo/issues/9604

Added Snyk Code Parser

---

dojo/filters.py

[sc-3125]
With this feature, the user will be able to filter the finding objects with three new filters:
- On -  return only the findings reported on the given date.
- Before - return only the findings reported before the given date
- After - return only the findings reported after the given date
This filters were added to UI and API endpoints.
- API
- UI

Extend APIv2 Findings endpoint and UI filters to accept new date filters

---

docs/content/en/getting_started/upgrading/2.12.md
docs/content/en/getting_started/upgrading/2.13.md

Upgrade Notes: Move breaking helm change notice from 2.13.x -> 2.12.x

---

dojo/components/views.py
dojo/product/views.py

To avoid `RemovedInDjango50Warning - In Django 5.0, StringAgg() will return None instead of an empty string if there are no rows. Pass default=None to opt into the new behavior and silence this warning or default=Value('') to keep the previous behavior.`
Note: Discovered in #9503

StringAgg: use default Value('')

---

dojo/tools/github_vulnerability/parser.py
unittests/scans/github_vulnerability/issue_9582.json
unittests/tools/test_github_vulnerability_parser.py

Fix github parser issue 9582

---

dojo/settings/settings.dist.py

This setting is here to override default renderer of forms (use div-based, instred of table-based).
It has effect only on templates that use "{{ form }}" in the body. Only "Delete forms" now.
The setting is here to avoid RemovedInDjango50Warning.
More info:
- https://docs.djangoproject.com/en/4.1/ref/forms/renderers/#django.forms.renderers.DjangoTemplates
- https://docs.djangoproject.com/en/5.0/ref/forms/renderers/#django.forms.renderers.DjangoTemplates
Notes:
- Remove this setting in Django 5.0 because DjangoDivFormRenderer will become deprecated and the same class will be used by default DjangoTemplates.
- Discovered during debugging #9503
Btw, there is no visual difference.
Before:
After:

Force to use DjangoDivFormRenderer

---

requirements.txt

Fixes #9629 
The Swagger UI project recently released a new version that created some issues rendering schema and response bodies. The drf-spectacular-sidecar library is a containerized version of the Swagger UI that affords us a monthly pinned release. 
Version 2024.3.4 contains the fixed version 5.11.9 of Swagger UI
Please see the linked issue for more analysis and details

Upgrade drf-spectacular-sidecar to 2024.3.4

---

dojo/settings/settings.dist.py

Most of the endpoints in the drf-spectacular docs do not have any meaningful examples or response bodies present. This makes the API much more difficult to use. fixes #9629 
[sc-4511]

DRF Spectacular: Enable sidecar by default

---

dojo/tools/checkmarx/parser.py
unittests/tools/test_checkmarx_parser.py

We could no longer import Checkmarx reports because the finding date field had a datetime value. This fix resolves the issue.

Bugfix: checkmarx parser - datetime is no longer put into the Finding.date field

---

dojo/models.py
dojo/utils.py
unittests/test_notifications.py

This PR uses python functionality which was added in newer python versions (3.6+) and thus deprecates method merge_sets_safe in utils.py. Furthermore, itertools is not needed anymore in utils.py. Thus, we don't need to import itertools.

Deprecate merge_sets_safe in dojo/utils.py

---

dojo/jira_link/helper.py

Most of the push/update to jira logic is  surrounded in a single try/catch, so if any step of the process goes wrong, the entire process fails. This is not ideal in some cases. The case that caught my attention the most is when the default assignee on a product no longer exists in Jira, so when a new issue is created, the link between dojo and jira is never established because of the failed assignee step. This results in a new ticket in jira that is never linked back to defectdojo, and ultimately led to duplicate jira tickets.
[sc-4460]

Jira: Improve alerting on a per step basis

---

docs/content/en/integrations/parsers/file/pip_audit.md
dojo/tools/pip_audit/parser.py
unittests/scans/pip_audit/empty_new.json
unittests/scans/pip_audit/many_vulns_new.json
unittests/scans/pip_audit/zero_vulns_new.json
unittests/tools/test_pip_audit_parser.py

Updating pip-audit parser to handle new JSON file format [sc-3854]

Updating pip-audit parser to handle new JSON file format

---

dojo/endpoint/views.py
dojo/models.py
dojo/product/views.py
dojo/templates/base.html
dojo/templates/dojo/endpoints.html
dojo/templates/dojo/product.html
dojo/templates/dojo/view_endpoint.html
dojo/utils.py

When working with endpoints, I thought it was a little misleading that findings needed to be verified to be counted on a given endpoint/host. A finding being active seems like a more accurate representation. To maintain the previous behavior of counting verified findings, I kept the count and added a link to the query:
This PR also changes how endpoints are measured on a given product. Instead of counting vulnerable hosts / endpoints based on the status of findings, they will now be based on the status of an endpoint statuses. Fixes #9413 
[sc-4752]

Endpoints: Remove "verified" query on listing pages

---

.github/workflows/ruff.yml

There are some warnings on the ruff linter action related to the deprecated default `check` action. The action must be explicitly set now
[sc-4736]

Ruff Linter: Resolve deprecation notice

---

dojo/api_v2/serializers.py
dojo/engagement/views.py
dojo/forms.py
dojo/importers/importer/importer.py
dojo/importers/reimporter/reimporter.py
dojo/test/views.py

Adds a toggle for applying tags to endpoints at import/reimport time
[sc-4869]

Import/Reimport: Add toggle for applying tags to endpoints

---

dojo/models.py
unittests/test_endpoint_model.py

Redefine the vulnerability status of an endpoint to consider endpoint statuses rather than findings. An endpoint can only be considered mitigated when all endpoint statuses are marked as mitigated. This aligns with the behavior exhibited by the bulk mitigate feature on the view endpoint page

Endpoints: Redefine vulnerable definition

---

.dryrunsecurity.yaml

Update config of DryRun Security
N/A
N/A
**Checklist**

Updated DryRun Security config

---

.flake8
dojo/templatetags/display_tags.py
pyproject.toml

Remove E731 from `lint.ignore` and fix the findings

Ruff: Solve E731

---

dojo/test/views.py

[sc-3143]
The initial data for the form in Add finding manually for test, now changes DAST field to false by default, the current value is set to True.
Now the default value is False.
No docs provided

set Dynamic finding to false by default in add finding manually to test

---

.dryrunsecurity.yaml

Minor PR to fix typo in GH usename in DryRun Security config

Fix typo of github username in DryRun Security config

---

dojo/filters.py

[sc-4929]
The Finding filters `not_test__tags` and `test_tags` was returning the same dataset when used on a GET /finding/ request.
The `exclude='True'` was missing in the `not_test__tags` field in API Finding filter. The exclude parameter was added.
Now the filter works properly.

Fix finding filter in API `not_test__tags'

---

dojo/tools/nikto/json_parser.py
dojo/tools/nikto/parser.py
dojo/tools/nikto/xml_parser.py

🔨 Refactor nikto to separate json and xml

---

.flake8
dojo/models.py
dojo/settings/settings.dist.py
dojo/tools/factory.py
dojo/wsgi.py
pyproject.toml
wsgi.py

Remove E402 from `lint.ignore` and fix the findings

Ruff: Solve E402

---

dojo/api_v2/serializers.py

[sc-4953]
The `tags` field in Import and reimport Api endpoints are optional. The `TagListSerializerField` now validates if the given value is empty, if it is, and the field has the `allow_empty` option as True, then the validation returns an empty list, making the field as valid.
The tests were made manually

Make tags optional for import and reimport API endpoints

---

dojo/tools/api_bugcrowd/api_client.py
dojo/tools/api_bugcrowd/parser.py
dojo/tools/kics/parser.py

Fix violations that probably haven't been detected in the original PR but are in place

Flake8: Fix E201, E202 and E231

---

.github/workflows/k8s-tests.yml

There are still some leftovers from pgha in the k8s action.

[k8s] Remove pgha from actions

---

.flake8

Remove `F405` and `F812`. Violations that are not in the code anymore.
`exclude` section can be removed because `dojo/unittests` and `['.git', '__pycache__']` is default for this parameter.
`max-complexity` can be removed because ignore for `C901` (Function is too complex) is already in place.

Flake8: Remove useless ignores

---

dojo/tools/qualys/parser.py

Use a copy of the issue_row object for the _temp-Finding variable because otherwise changes in _temp will reflect to issue_row which is a bad idea
The problem was detected when we uploaded relatively large Qualys Scan results to dojo. All of a sudden the cvss_scores have been set to 0.0 for some findings. We found that the changes that are made to the `_temp` object are automatically transferred to the issue_row object in the parser. Thus fields, such as title, port_status, active, cvss_score and cvss_vector are set in the issue_row variable. For the next finding iteration those …

fix qualys parser: Finding object inconsistencies - use a copy of the issue_row object 

---

dojo/tools/netsparker/parser.py
unittests/scans/netsparker/issue_9816.json
unittests/tools/test_netsparker_parser.py

- https://github.com/DefectDojo/django-DefectDojo/issues/9816
- cvss31 was missing 
- item["State"] can be None

:bug: fix multiple netsparker issues

---

dojo/tools/redhatsatellite/parser.py
unittests/tools/test_redhatsatellite_parser.py

This PR removes cve from redhatsatellite and migrates to unsaved_vulnerability_ids. See https://github.com/DefectDojo/django-DefectDojo/pull/9791#pullrequestreview-1958009612

redhatsatellite: migrate cve to unsaved_vulnerability_ids

---

dojo/tools/bundler_audit/parser.py
unittests/tools/test_bundler_audit_parser.py

This PR removes cve from bundler, but unsaved_vulnerability_ids already exists. See https://github.com/DefectDojo/django-DefectDojo/pull/9791#pullrequestreview-1958009612

bundleraudit: remove cves

---

dojo/tools/sysdig_reports/parser.py
unittests/tools/test_sysdig_reports_parser.py

This PR migrates sysdig_reports from cve to unsaved_vulnerability_ids. See https://github.com/DefectDojo/django-DefectDojo/pull/9791#pullrequestreview-1958009612

sysdig_reports: migrate cve to unsaved_vulnerability_ids

---

dojo/tools/openvas/csv_parser.py
unittests/scans/openvas/report_using_CVE.csv
unittests/scans/openvas/report_using_openVAS.csv
unittests/tools/test_openvas_parser.py

See https://github.com/DefectDojo/django-DefectDojo/discussions/9780

add cve values to openvas csv parser

---

docker-compose.override.debug.yml
docker-compose.override.dev.yml
docker-compose.override.integration_tests.yml
docker-compose.override.unit_tests.yml
docker-compose.override.unit_tests_cicd.yml
docker/entrypoint-integration-tests.sh
docker/entrypoint-unit-tests-devDocker.sh
docker/entrypoint-unit-tests.sh

- Move PYTHONWARNINGS to EnvVar
- Be strict in debug as well
- Do not fail but be more verbose in dev

Move PYTHONWARNINGS to EnvVar

---

docs/content/en/usage/features.md
dojo/api_v2/serializers.py
unittests/test_rest_framework.py
unittests/test_tags.py

When supplying tags to the import and reimport endpoints through the swagger page, the resulting curl command on the tags form data looks like this:
```
...
-F 'tags=one,two,three'
...
```
When the serializer processes this request, a single string with the value `one,two,three` will be applied to any objects requested to be tagged. This is misleading and incorrect. Instead, the string should be split with commas as the delimiters.
[sc-4993]

API Import/Reimport: Convert string tags to lists

---

dojo/api_v2/serializers.py
dojo/models.py

CVSS overrides are creating issues for reimport due to the calculation of hash codes. This functionality needs to be reverted for the time being
[sc-5098]

CVSS Override: Revert #9744

---

dojo/settings/settings.dist.py
dojo/tools/qualys/csv_parser.py
dojo/tools/qualys/parser.py

It was discovered that qualys does not have a Critical severity per their [severity knowledgeable article](https://qualysguard.qg2.apps.qualys.com/portal-help/en/malware/knowledgebase/severity_levels.htm). To accommodate the correct mapping with as little impact to hash codes without changing severities of existing findings, we can offer an opt in setting adopt the new behavior outlined In the knowledge base article linked above
[sc-5119]

Add legacy parsing method for qualys

---

docs/content/en/integrations/notifications.md
dojo/notifications/helper.py
dojo/settings/settings.dist.py
unittests/test_notifications.py

Revert a small part from #9227.
Full explanation in https://github.com/DefectDojo/django-DefectDojo/pull/8824#issuecomment-1986098912

Add NOTIFICATIONS_SYSTEM_LEVEL_TRUMP

---

dojo/tools/sslyze/parser_json.py
unittests/scans/sslyze/issue_9848.json
unittests/tools/test_sslyze_parser.py

fixes #9848 
I copied an exisiting unittestfile and changed the value of "heartbleed" to null to reproduce the issue. Then, I fixed the code.

Bugfix for NoneType Error in SSLyze parser

---

dojo/tools/nancy/parser.py
unittests/tools/test_nancy_parser.py

This PR removes cve from nancy and migrates to unsaved_vulnerability_ids. See https://github.com/DefectDojo/django-DefectDojo/pull/9791#pullrequestreview-1958009612

nancy: migrate from cve to unsaved_vulnerability_ids

---

dojo/tools/yarn_audit/parser.py
unittests/tools/test_yarn_audit_parser.py

This PR removes cve from yarn_audit and migrates to unsaved_vulnerability_ids. See https://github.com/DefectDojo/django-DefectDojo/pull/9791#pullrequestreview-1958009612

yarn_audit: migrate from cve to unsaved_vulnerability_ids

---

dojo/tools/osv_scanner/parser.py
unittests/tools/test_osv_scanner_parser.py

This PR removes cve from osv_scanner and migrates to unsaved_vulnerability_ids. See https://github.com/DefectDojo/django-DefectDojo/pull/9791#pullrequestreview-1958009612

osv_scanner: migrate from cve to unsaved_vulnerability_ids

---

docker-compose.override.debug.yml
docker-compose.override.dev.yml
docker-compose.override.https.yml
docker-compose.override.integration_tests.yml
docker-compose.override.unit_tests_cicd.yml
docker-compose.yml

Solve Warning
```bash
WARN[0000] .../django-DefectDojo/docker-compose.yml: `version` is obsolete 
WARN[0000] .../django-DefectDojo/docker-compose.override.yml: `version` is obsolete
```
More info:
> The top-level `version` property is defined by the Compose Specification for backward compatibility. It is only informative.
> 
> Compose doesn't use `version` to select an exact schema to validate the Compose file, but prefers the most recent schema when it's implemented.
From https://github.com/compose-spec/compose-spec/blob/master/04-version-and-name.md

Remove 'version' from docker-compose

---

pyproject.toml

Add checks that are fully solved and do not need any fixes - as prevention for the future.
`lint.select` has been split into lines (for easier readability and adding new ones). They are ordered based on https://docs.astral.sh/ruff/rules

Ruff: Add checks that are fully solved

---

dojo/models.py
dojo/settings/settings.dist.py

Set of changes that will be needed during the upgrade to Django 4.2 and it is safe to perform them in 4.1.
To decrease the migration scope of #9493

PreDjango 4.2 fixes

---

dojo/tools/sonarqube/sonarqube_restapi_json.py
unittests/tools/test_sonarqube_parser.py

This PR removes cve from sonarqube and migrates to unsaved_vulnerability_ids. See https://github.com/DefectDojo/django-DefectDojo/pull/9791#pullrequestreview-1958009612

sonarqube: cve to vulnerability_ids

---

dojo/tools/checkmarx_one/parser.py
unittests/scans/checkmarx_one/api_export.json
unittests/tools/test_checkmarx_one_parser.py

[sc-5278]
The API exported files now are compatible with Checkmarx one parser. The parser add the `sca` and `sca-container` types to make them compatibles.
The unittests ran properly.

Checkmarx one parser support API exported files

---

.github/workflows/detect-merge-conflicts.yaml

Solve Node v16 vs v20 warning.
https://github.com/eps1lon/actions-label-merge-conflict/releases/tag/v3.0.0
Not detected by renovate/dependabot because of change of naming convention.

GH-action: Detect Merge Conflicts - update v3

---

dojo/remote_user.py
unittests/test_remote_user.py

Combination of https://github.com/DefectDojo/django-DefectDojo/pull/9108/ and enabled `DD_AUTH_REMOTEUSER_ENABLED` was breaking API Swagger because of removed `settings.SWAGGER_SETTINGS`. 
```python
uwsgi-1         | [18/Apr/2024 12:50:56] ERROR [dojo.api_v2.exception_handler:41] 'Settings' object has no attribute 'SWAGGER_SETTINGS'
uwsgi-1         | Traceback (most recent call last):
uwsgi-1         |   File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
uwsgi-1         |     response = handler(request, *args, **kwargs)
uwsgi-1         |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
uwsgi-1         |   File "/usr/local/lib/python3.11/site-packages/drf_spectacular/views.py", line 84, in get
uwsgi-1         |     return …
```

Fix: Broken Swagger when Remote User enabled

---

helm/defectdojo/values.yaml

Pin newer image until there is no psql migration procedure prepared.

Helm postgresql: Upgrade image

---

unittests/tools/test_spotbugs_parser.py

The PR #9990 to upgrade `html2text` hit a unit test failure due to a whitespace issue. This should resolve it so we can merge the `html2text` upgrade PR.
Spotbugs test that was failing now passes:
```
System check identified no issues (0 silenced).
test_description (unittests.tools.test_spotbugs_parser.TestSpotbugsParser.test_description) ... ok
test_file (unittests.tools.test_spotbugs_parser.TestSpotbugsParser.test_file) ... ok
test_find_file_path (unittests.tools.test_spotbugs_parser.TestSpotbugsParser.test_find_file_path) ... ok
test_find_sast_source_line (unittests.tools.test_spotbugs_parser.TestSpotbugsParser.test_find_sast_source_line) ... ok
test_find_sast_source_path (unittests.tools.test_spotbugs_parser.TestSpotbugsParser.test_find_sast_source_path …
```

Fixing Spotbugs unit test error with new html2text version

---

dojo/tools/asff/parser.py

Resolving the issue with the deprecated netaddr `is_private` method by replacing with `not is_global` ([ref](https://netaddr.readthedocs.io/en/latest/api.html#netaddr.IPAddress.is_global))
ASFF tests now pass, but I haven't added a separate test to confirm that this still behaves exactly the same as `is_private` did.

Replacing deprecated netaddr 'is_private' call

---

dojo/models.py

For parser that do not supply a date, or the scan completion date is not set, the finding will not be saved correctly. This PR sets the current timezone aware date on the finding before it is saved to the database in the event that a date is not already supplied
Fixes #9712, #9724

Set Finding date if nothing is set from the parser

---

dojo/tools/semgrep/parser.py
unittests/scans/semgrep/sca_deployments_vulns.json
unittests/tools/test_semgrep_parser.py

Fix to a previous PR
**Checklist**
- enhancement
- performance
- feature
- bugfix
- dependencies
- …

Updates to semgrep parser

---

dojo/filters.py
dojo/product/views.py
dojo/templates/dojo/product.html

[sc-5627]
As #6629 describes, there are views where sorting is made "lexicographically." The main problem I found is that sorting is performed by the front end (the page doesn't reload on sorting). Tables that don't perform sorting on the backend, like the ones displayed at `/product/{pid}/engagements,` will need another approach.
For the `All products` view, using a filter for findings_count on the backend allows us to sort numerically and sort over the complete dataset instead of being limited by the rows shown on the current page.
By implementing this change, we directly address the issue outlined in #8127, providing a more efficient sorting and filtering mechanism for the displayed data.

Fix numerical sorting in the old UI for Active/Verified findings

---

dojo/filters.py

[sc-3150]
Add target start and target end filters on engagements.

Filter All Engagements by Date

---

dojo/jira_link/views.py
unittests/test_jira_webhook.py

The jira webhook relies on the django response handlers to provide warning logs in the event of 400, 403, and 404 error codes. However, to remove those warnings, all warnings must be removed, and that is not really ideal. Instead, let's reduce the severity of the logs, and not use 4xx error codes.
[sc-5693]

Jira Webhook: Reorg logging and responses

---

dojo/components/views.py
dojo/endpoint/views.py
dojo/engagement/views.py
dojo/filters.py
dojo/metrics/views.py
dojo/product/views.py
dojo/reports/views.py
dojo/reports/widgets.py
dojo/templates/dojo/metrics.html
unittests/test_metrics_queries.py

In #10038, an opt in performance enhancement was added for improving the response time of finding pages. This PR extends that behavior to the rest of the filters throughout the application
[sc-5695]

String Based Filtering: Follow on for #10038

---

dojo/tools/qualys/parser.py

The Parser used a Date Field for the mitigation_date, however… the Finding-Model requires a DateTime Field which is not compatible and imports are getting canceled. The fix is simply to remove the "to_date" conversion, because we do not want to change the Finding Model
Please update any documentation when needed in the [documentation …

Parser: Fix Qualys Parser Mitigation Date Issue 

---

docs/content/en/_index.md

This PR is mainly related to the  https://documentation.defectdojo.com/ deployment, in order to consolidate all references to the commercial offering onto this single page.
The change is mainly to ensure that DefectDojo Open Source docs and DefectDojo Inc's Knowledge Base are differentiated and identified in both locations.

extend _index.md with link to Knowledge Base

---

dojo/models.py
ruff.toml

Fix some `DJ` rules - https://docs.astral.sh/ruff/rules/#flake8-django-dj
Included:
- `DJ003`
- `DJ012`
- `DJ013`
Not included for now:
- `DJ001`
- `DJ006`
- `DJ007`
- `DJ008`

Ruff: add and fix some of DJ rules

---

docs/content/en/integrations/social-authentication.md

Using certain markdown links prevents the docs from building correctly locally, as 'https://the_hostname_you_have_gitlab_deployed:your_gitlab_port/profile/applications' etc are not real URLs. 
Although this problem might be due to my own Hugo settings/version, I think it would be less problematic to remove the non-existent URL from the docs altogether, so that readers understand that this is an example url and not intended to be a functioning link.

remove non-working links from social-authentication.md

---

docs/content/en/link_knowledge-base.md

Add a link to the DefectDojo Knowledge Base on the documentation sidebar with a book icon.  Along the same lines as my previous PR: https://github.com/DefectDojo/django-DefectDojo/pull/10002
The change is mainly to ensure that DefectDojo Open Source docs and DefectDojo Inc's Knowledge Base are differentiated and identified in both locations.

add Knowledge Base link to docs sidebar element

---

dojo/remote_user.py
dojo/settings/settings.dist.py
unittests/test_remote_user.py

`RemoteUser` is usually used behind AuthN proxy and users should not know about this mechanism from Swagger because it is not usable by users.
It should be hidden by default.

RemoteUser: Hide from Swagger

---

dojo/tools/awssecurityhub/compliance.py
dojo/tools/awssecurityhub/guardduty.py
dojo/tools/awssecurityhub/inspector.py
unittests/tools/test_awssecurityhub_parser.py

fix awssecurityhub findings

---

dojo/tools/hcl_appscan/parser.py
unittests/scans/hcl_appscan/issue_10074.xml
unittests/tools/test_hcl_appscan_parser.py

see #10074 
However, the scanfile was not very helpful as a lot of values were rotated (e.g. also severity and cwe) and I had to rotate those back to get something useful.
I figured out that some severity values were None and fixed it with the scan file.

:bug: fix hcl_appscan, handle severity is None #10074

---

docs/content/en/integrations/parsers/file/progpilot.md
dojo/tools/progpilot/__init__.py
dojo/tools/progpilot/parser.py
unittests/scans/progpilot/progpilot.json
unittests/scans/progpilot/progpilot2.json
unittests/scans/progpilot/progpilot3.json
unittests/scans/progpilot/progpilot4.json
unittests/tools/test_progpilot_parser.py

:sparkles: implement progpilot SAST parser #10044

---

docs/content/en/contributing/how-to-write-a-parser.md

This PR helps to not spread the idea to use cve as the Finding field. See https://github.com/DefectDojo/django-DefectDojo/pull/9791#pullrequestreview-1958009612

remove cve field from docs

---

dojo/product/views.py

When measuring Affected Endpoints:
- Fix an incorrect `.get()` that results in a 500 error code response
- Add an annotation for `finding__cwe` within the `endpoint_querys` utility (without it, the CWE vulnerability graphs are always blank)
[sc-5921]

Product Metrics Bugfixes

---

dojo/views.py

Because DefectDojo uses a custom error handler for 400/500 errors that does not set a status code, 200 status codes will be returned even when an exception is raised. This means that Django logs those exceptions at the INFO level rather than a more appropriate `WARNING` / `ERROR` level. This patch simply sets the status codes to 400/500.
In my testing, 500 status codes are now returned when exceptions are raised, and those requests are now logged at an `ERROR` level.
[sc-5912]

Setting status code on 400/500 errors

---

dojo/tools/redhatsatellite/parser.py

:lipstick: remove unnecessary content from redhatsatellite findings

---

dojo/templates/notifications/mail/other.tpl
dojo/templates/notifications/mail/report_created.tpl
dojo/templates/notifications/mail/review_requested.tpl
dojo/templates/notifications/mail/user_mentioned.tpl

Some URLs have not been displayed as links.

fix(notifications-email): Use a for urls

---

docs/content/en/integrations/parsers/api/sonarqube.md

Typo in documentation mentioned in Slack: https://owasp.slack.com/archives/C2P5BA8MN/p1715589858425459?thread_ts=1715347782.044819&cid=C2P5BA8MN

Fix(api-sq): Doc: typo in multi branch scanning

---

dojo/api_v2/serializers.py
dojo/forms.py
dojo/templates/dojo/view_eng.html
dojo/templates/dojo/view_finding.html
dojo/templates/dojo/view_test.html

When using the API to upload files, it was noticed that `FILE_UPLOAD_TYPES` settings was not being enforced. This PR adds enforcement of this setting. Additionally, these files should be downloaded to disk rather than being rendered by the browser
[sc-5953]

Object File Uploads: Add validations and download functionality

---

dojo/importers/base_importer.py
dojo/importers/default_importer.py
dojo/importers/default_reimporter.py
dojo/templates/dojo/view_eng.html
dojo/templates/dojo/view_test.html

- Updating validation a bit to make more robust
- Add some blocks to a few templates
[sc-2909]

Importers: Small corrections

---

dojo/apps.py
dojo/endpoint/signals.py
dojo/endpoint/views.py
dojo/engagement/signals.py
dojo/engagement/views.py
dojo/finding/views.py
dojo/finding_group/signals.py
dojo/finding_group/views.py
dojo/jira_link/views.py
dojo/middleware.py
dojo/models.py
dojo/notifications/helper.py
dojo/product/signals.py
dojo/product/views.py
dojo/product_type/signals.py
dojo/product_type/views.py
dojo/settings/settings.dist.py
dojo/tags_signals.py
dojo/test/signals.py
dojo/test/views.py
dojo/tools/api_sonarqube/importer.py
dojo/utils.py
unittests/dojo_test_case.py
unittests/test_notifications.py
unittests/test_rest_framework.py

Purpose of this PR: If some action triggers the creation of a notification during clicking in UI. The same notification should be triggered also if the same happens via API. Until now many actions have been avoiding these notifications. Implementation is done by Django Signals.
Some notes:
- General rule: if the object is removed in cascade (e.g. removal product triggers removal of all engagements, tests, ...) notification is created only for the highest removed element (to avoid spamming).
- The only exception to this ^ general rule is the removal of the Product. If Product Type is removed, notification is triggered for all Products as well
- PR hasn't announced any new notifications. All of them have been created based on existing implementation.
- There is a set of notifications which …

Consolidation of notification creation

---

dojo/api_v2/serializers.py
dojo/filters.py
dojo/templates/dojo/users.html
dojo/templates/dojo/view_user.html

I bumped into a situation when we were investigating when the user was created. I found it useful to add it to some of the views. Before it was only in the user's personal profile.
Now, it is in
- API response
- List of users
- It is useable for sorting
- User's profile (available by admins)

feat(user): Show date of user creation

---

dojo/tools/progpilot/parser.py

see discussion in https://github.com/DefectDojo/django-DefectDojo/issues/10044

:bug: reset description in progpilot after each finding

---

dojo/tools/sarif/parser.py
unittests/scans/sarif/issue_10191.json
unittests/tools/test_sarif_parser.py

:bug: fix SARIF, issue #10191

---

docs/content/en/contributing/how-to-write-a-parser.md

Added section to indicate best practice for opening files using with.

Added with best practice for file open

---

dojo/filters.py
dojo/templates/dojo/report_builder.html

[sc-5885]
Fixed missing filter on Discovery Date. Now able to specify a range with from and to. 
Tested locally and includes a fix for when labels are 'missing' in the report builder html.

Improving date of discovery filter

---

dojo/tools/noseyparker/parser.py

**Current issue with the Nosey Parker parser:**
The parser currently grabs a code snippet for the secret found in source code. This code snippet is taken directly from the Nosey Parker JSONL output. However, in some cases, secrets are printed out in Defect Dojo (in plaintext) if they are in the line before and after the matching secret. 
**Checklist**

Nosey Parker description fixes

---

dojo/importers/default_reimporter.py

When a vulnerability is present in  a report multiple times, but with different status, there is an opportunity for the following exception:
```
duplicate key value violates unique constraint "dojo_test_import_finding_test_import_id_finding_i_e6f366e5_uniq"
DETAIL:  Key (test_import_id, finding_id)=(4108, 948) already exists.
```

Test_Import: Correct exception for multiple findings in the same object

---

unittests/scans/generic/test_import_report1.json
unittests/scans/generic/test_import_report2.json
unittests/test_import_reimport.py

Import History: Adding a few tests

---

dojo/test/views.py

this line will keep template finding cvssv3 field in the new created finding
this is a fix for #10162. The cvssv3 vector will be preserved from the finding template.
it was tested and it works. it preserves the cvssv3 vector in the new created finding.
**Checklist**
Please clear everything below when submitting your pull request, it's here purely for …

Update views.py to fix #10162

---

Dockerfile.django-alpine
Dockerfile.django-debian
Dockerfile.integration-tests-debian
Dockerfile.nginx-alpine
Dockerfile.nginx-debian

Looks like Renovate and/or Dependabot are not able to identify higher versions
- If Debian names are used
- If 2 versions are mentioned in the tag
This should be addressed somehow, for now, let's fix it by hand.
Fix for #10277

fix(docker): Bump versions (python 3.11, alpine 3.20)

---

dojo/tools/sonarqube/sonarqube_restapi_json.py
unittests/scans/sonarqube/findings_over_api.json

self explanatory (see changes)

Sonarqube flow field contains dict

---

dojo/tools/redhatsatellite/parser.py

RedHatSatellite module_streams field is dict within list

---

dojo/tools/ms_defender/parser.py

I removed some information in the description. This information is already described within the endpoints to calm the deduplication of MsDefender ['title', 'description']. The problem is that the description changes as soon as a client gets a new IP Address.

Calm the deduplication of MsDefender

---

dojo/utils.py

This is a fix for the issue described here: https://github.com/DefectDojo/django-DefectDojo/issues/10237 which was introduced by myself in the original fix for the metrics here: https://github.com/DefectDojo/django-DefectDojo/pull/9013

fix NoneType exception in case of simple risk acceptance

---

Dockerfile.django-debian
Dockerfile.integration-tests-debian
Dockerfile.nginx-debian

fix(docker): Bump versions (python 3.11, debian bookworm)

---

dojo/tools/qualys_webapp/parser.py
unittests/tools/test_qualys_webapp_parser.py

This PR fixes the wrong passing of parameter `enable_weakness` in the Qualys Webapp parser.
It was identified during the preparation of https://github.com/DefectDojo/django-DefectDojo/pull/10085
@iwalton3, I noticed, you have been implementing this functionality in https://github.com/DefectDojo/django-DefectDojo/pull/3427. Can you confirm, that it was a bug and that this is the correct behavior?
Problematic are lines 358 and 396 where `enable_weakness` is passed into `is_info`, not into `enable_weakness`

fix(Qualys parser): wrong handling enable_weakness

---

dojo/templates/dojo/login.html

Fix for https://github.com/DefectDojo/django-DefectDojo/issues/10292
No visual changes. Whole area of social login buttons reacts to clicks now. No need to point cursor directly on the text inside button anymore.
Edit:
Screenshot before:
Screenshot after:

Make social login buttons fully clickable

---

dojo/tools/netsparker/parser.py
unittests/scans/netsparker/issue_10311.json
unittests/tools/test_netsparker_parser.py

:bug: fix netsparker issue #10311

---

dojo/importers/options.py

Fix for
- #10343
- https://owasp.slack.com/archives/C2P5BA8MN/p1717610907551889
- https://owasp.slack.com/archives/C2P5BA8MN/p1717611262044439

fix(imp-options): Wrong type-checker in validate_api_scan_configuration

---

dojo/api_v2/serializers.py

Currently the openapi spec lists these properties as required in UserProfile objects:
```
"required": [
"dojo_group_member",
"global_role",
"product_member",
"product_type_member",
"user",
"user_contact_info"
]
```
However, response may not included `global_role` or `user_contact_info`, if they are not set. With this change the required properties are:
```
"required": [
"dojo_group_member",
"product_member",
"product_type_member",
"user"
]
```
This is useful for generating clients from the openapi spec.
I don't believe there are tests for this.
This is just a change to the openapi spec.
**Checklist**

Mark UserProfile properties user_contact_info and global_role as optional

---

dojo/filters.py

With the "Filter String Matching Optimization" mode enabled in system settings, a few links within the UI have been broken:
- Product Type list - clicking on finding counts returns all findings a user has access to
- Product Endpoints - Clicking on hosts or endpoints returns all hosts or endpoints a user has access to
Adding a hidden filter that is not renderable on the page will support the object based filtering without fetching all of the objects at the time of request
[sc-6296]

String Filtering: Support ID matching for links on listing pages

---

dojo/importers/default_importer.py
dojo/importers/default_reimporter.py

In the importer and reimporter, correct arguments passed to `add_findings_to_auto_group` 
[sc-6289]

Importer: Correct `add_findings_to_auto_group` args

---

dojo/filters.py

With the "Filter String Matching Optimization" mode enabled in system settings, filtering by reviewers is not possible as there is typo. The correct typo from `reviewer` to `reviewers` allows the filter class to access the `reviewers` field on the Finding model
[sc-6164]

String Filtering: Correct Typo For Reviewers

---

dojo/api_v2/serializers.py

When using a tool such as openapi-python-client to generate a library based on Defectdojo's OpenAPI, the resulting library will crash when using the 'user_profile/' endpoint if the user never logged in. This may happen when a token was generated straight from the API, instead of the webUI.
This patch fixes the serializers to make last_login nullable.
To reproduce:
1) create a new user but DO NOT LOGIN
2) generate a token for that user
3) retrieve Defectdojo's OpenApi, and generate a library using openapi-python-client (do not use v.0.20.0, it fails)
4) using the library, access `user_profile/` for that user.
**Checklist**
- [✔️ ] Make sure to rebase your PR against the very latest `dev`.
- [N/A ] Features/Changes should be submitted …

openapi fix: allow last_login to be null

---

dojo/importers/default_importer.py
dojo/importers/default_reimporter.py

When `DD_ASYNC_FINDING_IMPORT` is enabled, there is a type error related to how the findings are collected. Please see the issue for the related stack trace and additional information
closes #10362

Async Importer: Correct typing bug with `DD_ASYNC_FINDING_IMPORT` enabled

---

.github/workflows/build-docker-images-for-testing.yml
.github/workflows/integration-tests.yml
.github/workflows/k8s-tests.yml
.github/workflows/rest-framework-tests.yml
Dockerfile.django-alpine
Dockerfile.django-debian
Dockerfile.integration-tests-debian
docker-compose.yml
docker/entrypoint-celery-beat.sh
docker/entrypoint-celery-worker.sh
docker/entrypoint-initializer.sh
docker/entrypoint-unit-tests-devDocker.sh
docker/entrypoint-unit-tests.sh
docker/reach_database.sh
dojo/settings/settings.py

In cases where the `settings.dist.py` hash is incorrect in incoming PRs, containers will boot loop during unit tests until they timeout. By default this timeout is 360 minutes, or 6 hours. This prevents units tests from actually running for all other PRs
This PR adds a breakout condition after 10 seconds of not being able to query the database through Django's `db_shell` to allow unit tests to exit quicker. In addition, I also added some timeouts for GHA action jobs just in case we run into a similar situation down the road
[sc-6360]

Entrypoint Scripts: Add container level breakouts to prevent doom loopings

---

unittests/test_rest_framework.py

In an attempt to isolate various functions of the rest framework tests to create a more dependable testing environment, I stumbled upon the real issue here. When running the delete preview test (this is the one that is consistently failing), the first step in the test is to first get all objects in the database by calling the LIST endpoint, and then getting the first one in the list
The problem here is that MySQL and Postgres may be sorting things differently ([from the minimal reading I have done so far](https://stackoverflow.com/questions/24434053/sorting-order-behaviour-between-postgres-and-mysql)) and can give a theory for why these issues only really appeared when switching databases for the unit tests
The solution here is going to be to add another parameter that will allow for …

Rest Framework Tests: Isolate tests by request type

---

.github/workflows/integration-tests.yml
requirements.txt
unittests/test_remote_user.py
unittests/test_user_queries.py

Upgrade to Django 5.x https://github.com/DefectDojo/django-DefectDojo/pull/9258 might be quite complated but we need to go to at least 4.2.13 because 4.1.x is not supported anymore (check https://www.djangoproject.com/download/)
Needs to be checked/considered:
- Might be handy: _[CharField.max_length](https://docs.djangoproject.com/en/5.0/ref/models/fields/#django.db.models.CharField.max_length) is no longer required to be set on PostgreSQL, which supports unlimited VARCHAR columns._
- We might need to change some lines for `makemigrations`: _The [makemigrations --check](https://docs.djangoproject.com/en/5.0/ref/django-admin/#cmdoption-makemigrations-check) option no longer creates missing migration files._

Upgrade Django to 4.2.13

---

dojo/tools/acunetix/parse_acunetix360_json.py
unittests/scans/acunetix/issue_10370.json
unittests/tools/test_acunetix_parser.py

In automated reports from Acunetix 360 to be imported into defect dojo. One vulnerability make the import crash due to no classification provided by Acunetix
#10370

:bug: fix Nonetype in Acunetix, #10370

---

dojo/templates/issue-trackers/jira_full/jira-finding-group-description.tpl
dojo/templates/issue-trackers/jira_limited/jira-finding-group-description.tpl

When findings groups are pushed to Jira, the URLs to represent the product, engagement, test, and even findings, are not functioning correctly. The reason for this is because the variable used to define the URL for each of the objects above is not actually in scope:
```
{% url 'view_finding_group' finding_group.id as finding_group_url %}
{% url 'view_product' finding.test.engagement.product.id as product_url %}
{% url 'view_engagement' finding.test.engagement.id as engagement_url %}
{% url 'view_test' finding.test.id as test_url %}
```
`finding_group` is present, and that links works, but `finding` is not in scope, and therefore does not produce the correct URLs
[sc-6434]

Jira Finding Group Templates: Correct object links

---

.github/ISSUE_TEMPLATE/bug_report.md

Address to Slack in the bug report template doesn't exist anymore, so this PR updates it to the right link.

fix: slack address on issue template

---

dojo/notifications/helper.py

For the correct handling of translations, in the strings that use string interpolation (placing variables to translated text), preparation steps need to be performed in the following order:
1. translate string with placeholders
2. replace placeholders with variables
If steps are executed in opposite order, it is not possible to perform translation.
Context: https://docs.djangoproject.com/en/5.0/topics/i18n/translation/#internationalization-in-python-code

fix(loc): Do not use _(...) in combination with format

---

dojo/api_v2/views.py
dojo/filters.py
dojo/reports/views.py
dojo/reports/widgets.py
dojo/templates/dojo/report_filter_snippet.html

This PR extends the string based filtering to the finding report filter. Currently, all of the following objects the user has access to are fetched on each page load:
- Product types
- Products
- Endpoints
- Engagements
- Tests
- Test Types
- Users,
- Tags (for each of the models)
On instances with large amounts of data, rendering this filter is as follows for my server 40k findings
- Object based filtering: ~15 seconds
- String based filtering: ~1.5 seconds
[sc-6622]

Finding Reports: Support string based filtering

---

dojo/templates/notifications/mail/scan_added.tpl

This PR makes the "scan added" email notification easier to read.
If there is a long list of findings, it might be harder to read it. From now on, notifications are "collapsed" into detail section and only the number of findings is visible. Users can click on the name of the category and see the full list.
Before:
After:
After, when you open 2 groups:
No hard magic 🪄 , only simple HTML tags.

feat(email notif): Scan_added - put findings to `<details>`

---

docker/entrypoint-unit-tests-devDocker.sh
docker/entrypoint-unit-tests.sh

Test robustness of unittests. They should pass in any order.

Shuffle tests

---

dojo/tools/acunetix/parse_acunetix360_json.py
unittests/scans/acunetix/issue_10435.json
unittests/tools/test_acunetix_parser.py

:bug: fix acunetix360 NoneType object #10435

---

dojo/api_v2/serializers.py

This PR adds more metadata about the user to `/api/v2/user_contact_infos/` endpoint.
Before:
```json
{
"id": 1,
"title": null,
"phone_number": "",
"cell_number": "",
"twitter_username": null,
"github_username": null,
"slack_username": "lalal",
"slack_user_id": null,
"block_execution": true,
"force_password_reset": false,
"user": 1
}
```
After:
```json
{
"id": 1,
"user_profile": {
"id": 1,
"username": "admin",
"first_name": "Admin",
"last_name": "User",
"email": "admin@defectdojo.local",
"date_joined": "2024-06-14T08:35:49.750327Z",
"last_login": "2024-06-14T14:53:57.859457Z",
"is_active": true,
"is_superuser": true,
"configuration_permissions": []
},
"title": null,
"phone_number": "",
"cell_number": "",
"twitter_username": null,
"github_username": null,
"slack_username": "lalal", …
```

feat(api - user contact): Add all user data

---

dojo/models.py

Make strings translatable and remove redundancy

fix(Risk_Acceptance): Remove redundancy in strings of Treatments

---

dojo/jira_link/helper.py

When DefectDojo processes groups of findings to generate the Jira environment, it sometimes adds unnecessary "\n" characters. This happens when multiple findings are grouped, even if their endpoints are empty. In contrast, single findings with unset endpoints do not add extra carriage returns.
This fix ensures the Jira environment is generated using existing endpoints only, maintaining consistency across both grouped and single findings.
I don't believe there are tests for this
This is a minor bug fix that shouldn't need any documentation updates
**Checklist**

The Jira environment is built using only existing endpoints

---

dojo/endpoint/utils.py
dojo/engagement/views.py
dojo/filters.py
dojo/importers/base_importer.py
dojo/importers/options.py
dojo/jira_link/helper.py
dojo/models.py
dojo/notifications/helper.py
dojo/okta.py
dojo/product/views.py
dojo/templatetags/display_tags.py
dojo/tools/burp_enterprise/parser.py
dojo/tools/jfrog_xray_unified/parser.py
dojo/tools/qualys_webapp/parser.py
dojo/tools/veracode/json_parser.py
dojo/tools/veracode_sca/parser.py
dojo/tools/xanitizer/parser.py
dojo/utils.py
ruff.toml
tests/close_old_findings_dedupe_test.py
tests/dedupe_test.py

New rule PIE
https://docs.astral.sh/ruff/rules/#flake8-pie-pie

Ruff: add and fix PIE

---

docker/entrypoint-unit-tests-devDocker.sh
docker/entrypoint-unit-tests.sh

Reverts DefectDojo/django-DefectDojo#10335

Revert "Shuffle tests"

---

helm/defectdojo/values.yaml

In the whole helm template `logLevel` is used only in ConfigMap
https://github.com/DefectDojo/django-DefectDojo/blob/81c123e8d92024b965ddd3c985640e2fe398007b/helm/defectdojo/templates/configmap.yaml#L24
However, mentioned `logLevel` is used from `.Values.celery.logLevel` (not from `.Values.celery.worker.logLevel`) so the definition of `.Values.celery.worker.logLevel` is obsolete.

fix(helm-celery): Drop unused variable logLevel

---

requirements.txt

Django 4.2 introduced support for Psycopg 3
> Psycopg 3 support[¶](https://docs.djangoproject.com/en/5.0/releases/4.2/#psycopg-3-support)
> Django now supports [psycopg](https://www.psycopg.org/psycopg3/) version 3.1.8 or higher. To update your code, install the [psycopg library](https://pypi.org/project/psycopg/), you don’t need to change the [ENGINE](https://docs.djangoproject.com/en/5.0/ref/settings/#std-setting-DATABASE-ENGINE) as django.db.backends.postgresql supports both libraries.
> 
> Support for psycopg2 is likely to be deprecated and removed at some point in the future.
> Source: https://docs.djangoproject.com/en/5.0/releases/4.2/#psycopg-3-support
This PR is blocked by #9493

Feat(psql): Use psycopg3

---

dojo/api_v2/serializers.py

Currently the OpenAPI spec lists the properties `related_fields`, `jira_creation` and `jira_change` as required in `Findings` objects. However, response may include these fields as null if they are not set. 
This PR updates the specification to mark these properties as nullable. This is useful for generating clients from the openapi spec.
I don't believe there are tests for this.
This is just a change to the openapi spec.
**Checklist**

Mark Finding properties related_fields, jira_creation and jira_change as nullable

---

helm/defectdojo/values.yaml

fix(helm-psql): Drop pinning of old version of postgresql

---

docs/config.dev.toml
docs/config.master.toml
docs/content/en/integrations/ldap-authentication.md
docs/content/en/integrations/parsers/file/fortify.md
docs/content/en/integrations/parsers/file/veracode.md
docs/content/en/integrations/social-authentication.md
docs/content/en/usage/productgrading.md

I found [`mermaid`](https://mermaid.js.org/) quite handy during the preparation of documentation for #7311.
Unfortunately, when `mermaid` is enabled `guessSyntax` has to be disabled otherwise graphs are not rendered (because `guessSyntax` marks `mermaid` snippets as `language-fallback` and they are not rendered at all).
I added languages to places where they have been probably guessed in the past. Now they do not need to be guessed.

fix(doc): Disable markup.highlight.guessSyntax + enable mermaid

---

.github/renovate.json

Since we have [deprecated MySQL and RabbitMQ as of v2.36.0](https://github.com/DefectDojo/django-DefectDojo/discussions/9690), this PR will remove them from the list of packages for which Renovate will open PRs for every version bump (as seen with e.g. #10502 #10510). This is part of our gradual removal of these packages now that they are no longer supported.
This PR should be reverted once these packages are totally removed.
N/A
N/A

Direct Renovate to ignore MySQL and RabbitMQ packages

---

docs/content/en/getting_started/upgrading/2.36.md

As #10507 is accepted and merged, it would be good to add upgrade instructions to users.

fix(doc): Breaking Change for HELM deployments with PostgreSQL

---

dojo/finding/views.py
dojo/finding_group/views.py
ruff.toml

Add G1 and G2 rules + fix G2
https://docs.astral.sh/ruff/rules/#flake8-logging-format-g

Ruff: add and fix G1 and G2

---

dojo/api_v2/views.py

Correcting copy/paste errors from #10503
The `get_fitlerset` method uses the request object to perform database filtering based upon the kwargs supplied in the request body. The intended behavior is to use the `get_queryset` method to override the functionality that fetches _all_ objects from the database, with filtering being performed afterwards.

API: Convert `get_filterset` calls to `get_queryset`

---

dojo/api_v2/serializers.py
unittests/test_apiv2_notifications.py

During the implementation of #7311, I noticed specific edge cases that the implemented `validate` function did not handle correctly.
If there is an existing System Notification (user=None, product=None, template=false), it is not possible to add a Notification Template. It failed with `Notification for user and product already exists` even though it wasn't true. So I add a `template` flag to the checking query. However, I also needed to reorder checkers because "existing template" would fail with `Notification for user and product already exists` so a reorder was needed.

fix(api-notif): Fix order of validators

---

Dockerfile.django-alpine
Dockerfile.nginx-alpine
requirements.txt

Since the update of the base python docker image from alpine:3.16 to 3.20 we've had segmentation faults while connecting to aws rds postgres databases. With the debug environment variable from the psycopg2 dependency we found connection issues while connecting to our database (see logs below).
Building the psycopg3 postgresql adapter instead of using the pre-build dependency as it's described in the [psycopg3 installation documentation](https://www.psycopg.org/psycopg3/docs/basic/install.html#local-installation) the connection could be established again as expected.
Also see the [slack thread](https://owasp.slack.com/messages/C2P5BA8MN/p1717509947946239) on this issue.
I've locally build and tested both the alpine and debian django +nginx dockerimages and …

fix(deps): build psycopg3 instead of using pre-build binary

---

requirements.txt

While waiting for the acceptance of #10409, it might be a good idea to upgrade Django at least to `4.2.14` to mitigate known issues: https://docs.djangoproject.com/en/5.0/releases/4.2.14/
This change is not offered by `dependabot` because it is monitoring only the latest versions (in running configuration).

Fix(django): Upgrade of 4.2.14

---

dojo/importers/default_importer.py
dojo/importers/default_reimporter.py
unittests/dojo_test_case.py
unittests/test_import_reimport.py

The `minimum_seveirty` flag was parsed and managed by the `ImporterOptions` class, but was never actually used by the Importers. This PR corrects that and adds a unit test to ensure the flag is working as expected.
[sc-6837]

Import: leverage the minimum severity flag

---

dojo/endpoint/utils.py

When a single endpoints is found in the endpoint get or create helper method, we do not want to raise a warning

Endpoint get or create: Do not raise warning when there is an existing endpoint

---

dojo/tools/factory.py

Return the ability to remove a given test type from being used, but without deleting the test type. This change has the following impacts for test types with a False `active` status:
- Import forms will not list inactive test types
- Creating/editing a test will not allow for an inactive test type to be selected
There is a slight caveat to this such that the API swagger schema does not appear to be calling the function to generate the list of test types each time the schema is loaded. The test type list is updated on uwsgi reload. My best guess is the schema is being cached on the server somehow. 
[sc-6869]

Test Types: Return support for disabling test types via the `active` flag

---

dojo/endpoint/views.py
dojo/finding_group/views.py
dojo/github_issue_link/views.py
dojo/group/views.py
dojo/jira_link/views.py
dojo/product/views.py
dojo/survey/views.py
dojo/templates/dojo/delete_alerts.html
dojo/user/views.py

There are a few objects that were missed in the addition of the `DELETE_PREVIEW` setting to prevent the full chain of associated objects from being expanded into memory. The list is as follows:
- Alerts
- Jira Instance
- Endpoints
- Questionnaires
- Github Links
- Engagement Presets
- Finding Groups
- Groups (users)
- User
Fixes #10532 
[sc-6873]

Delete Preview: Expand on missed objects

---

dojo/api_v2/serializers.py

The endpoint_to_add option on POST /import is incorrectly described in the API docs:
Helptext says that this field allows you to add a new Endpoint, but this is inaccurate. Instead, this method looks for an existing Endpoint ID in the database and associates it with the incoming Findings.
I am changing the help text so that it is described accurately. I am also reflecting the help text to/reimport because this method works in the same way on that endpoint.
- Tested /import endpoint to ensure feature works as described
- Tested /reimport endpoint to ensure feature works as described
[sc-6963]

/import helptext correction: endpoint_to_add

---

dojo/finding/views.py

when I have push notes enabled in a product with manually synced findings to JIRA and I close the finding with a note, I expect the note to also get synced to JIRA
[sc-6729]

Close Findings: Push notes if `push notes` is enabled

---

dojo/importers/options.py

The `endpoints_to_add` parameter is not functioning as expected. Adding some polish to the options compression corrects this
[sc-6962]

Option Compression: add some polish

---

dojo/tools/aqua/parser.py
unittests/scans/aqua/issue_10585.json
unittests/tools/test_aqua_parser.py

Catch cases where an aqua report may not have any vulnerabilities. In this case, the aqua parser should not through an exception, but simply pass on that section of the report
closes #10585

Aqua: Improve exception handling for reports without vulnerabilities :bug:

---

docs/content/en/usage/features.md

`skip_duplicates` has not been used in DefectDojo since deduplication was refactored in 2019: see PR https://github.com/DefectDojo/django-DefectDojo/pull/1395.  This commit removes the API reference from docs.

remove outdated skip_duplicates API reference from docs

---

dojo/finding/views.py
dojo/forms.py

- Allow for closing a finding when clearing a review
- Enforces the `under_review` flag is set to `False` when reopening or closing a finding
[sc-3366]

Finding Open/Close/Review: Enforce more status standardization

---

dojo/importers/options.py

When compressing importer options, we need to accommodate any unsaved objects a bit better
[sc-7013]

Option Compression: Accommodate unsaved objects a bit better

---

helm/defectdojo/templates/_helpers.tpl
helm/defectdojo/templates/celery-beat-deployment.yaml
helm/defectdojo/templates/celery-worker-deployment.yaml
helm/defectdojo/templates/django-deployment.yaml
helm/defectdojo/values.yaml

Previous implementation used `initialDelaySeconds` set to `120s` which might be fine for standard (default resource allocation), first-time starting (with empty database) instances. Mentioned fact is problematic for:
- instances that are "under-resourced" and start-ups might be longer and `120s` might not be enough
- instances that are "over-resourced" and start-ups might be much shorter and `120s` might be wasting of time (to wait until the instance is marked as `Ready`)
- instances that are already deployed and just need upgrade (with no or only just a couple of migrations). In this case, it  is wasting of time again.
- instances with multiple replicas when each replica needs to wait 2 minutes without the reason. Waisting of time again.
This solution does not solve #10197 but at least …

feat(initContainer): Tune start-up process

---

dojo/tools/qualys_webapp/parser.py

The Qualys WebApp parser is not using defusedXML like the rest of the parsers. This needs to change as defusedXML is widely considered to be the more secure option

Update Qualys WebApp parser to use DefusedXML

---

dojo/api_v2/views.py
dojo/engagement/views.py
dojo/utils.py
dojo/views.py

The management of file uploads within DefectDojo is inconsistent under a handful of scenarios related to permissions and functionalities. This PR accomplishes the following:
- Unify the logic to create a `FileResponse` to ensure the same `Content-Disposition` and naming conventions
- Add some extra checks around permissions of files, and the objects that hold them

Uploaded File Management: Centralize file serving and bolster error handling

---

dojo/engagement/views.py

Returns the permission check when viewing an engagement after it was omitted during the conversion to CBV

Engagement: Add missing permission check to view an Engagement

---

dojo/importers/base_importer.py
dojo/importers/default_importer.py
dojo/importers/default_reimporter.py

When importing an empty scan report through the import endpoint, it is possible for two tests to be created during a single request

Importer: Correct logic bug for empty scan reports

---

docs/content/en/contributing/how-to-write-a-parser.md

I would recommend to either go with lxml or defusedxml, but don't use a mixture of both.
https://discuss.python.org/t/status-of-defusedxml-and-recommendation-in-docs/34762/19
I chose lxml as defusedxml got the last update in March 2021

remove defusedxml in favor of lxml

---

dojo/tools/bearer_cli/parser.py
unittests/tools/test_bearer_cli_parser.py

:bug: fix Bearer CLI missing Scan Type #10652

---

unittests/test_factory.py

The [How to write a parser doc](https://documentation.defectdojo.com/contributing/how-to-write-a-parser/) mentions this about parser class names:
> The class name must be the Python module name without underscores plus `Parser`. Example: When the name of the Python module is `dependency_check`, the class name shall be `DependencyCheckParser`
This PR adds a unit test to ensure there are no new "orphan" parsers that will be unusable within Dojo because they don't match this guidance (factory logic [here](https://github.com/DefectDojo/django-DefectDojo/blob/master/dojo/tools/factory.py#L116-L131))
Test passes once the fix in #10654 is applied. That PR should go first, and this one will likely need to rebased once it's merged.

Parser name matches module name test

---

requirements.txt

https://github.com/goinnn/django-multiselectfield looks like alive again (https://github.com/goinnn/django-multiselectfield/issues/141) with more fixes (including Django 5 support - needed for #10409) than https://github.com/DefectDojo/django-multiselectfield.
`django-multiselectfield` in version `0.1.13` was released and it is pinned in `requirements.txt` now

fix(multiselectfield): Use original repo

---

docker/entrypoint-unit-tests-devDocker.sh
docker/entrypoint-unit-tests.sh

The rest framework tests have been very flakey not that they are actually producing failures for GHAs (this part is a good thing)
To increase stability for these tests, we should revert the `--prallel` and `--shuffle` flags
[sc-7127]

Rest Framework: Remove Parallel + Shuffle

---

docs/content/en/getting_started/upgrading/2.37.md

Fix typo (probably from copy-pasting)

fix(docs): Typo in "Release Notes" link

---

ruff.toml

Add rules which are already fixed

Ruff: Add some harmless rules

---

dojo/tools/aqua/parser.py
unittests/tools/test_aqua_parser.py

fix aqua parser #10585

---

requirements.txt

Django 4.2.15 corrects some security issues (replaces #10699)
[sc-7125]

Update to Django 4.2.15

---

.github/workflows/k8s-tests.yml

Run k8s on the latest version of k8s and minikube, as described in the comment.

fix(k8s): run k8s test on the latest version of k8s and minikube

---

dojo/tools/nikto/parser.py
dojo/tools/utils.py
ruff.toml

Ruff: Add and fix D3

---

dojo/engagement/views.py
dojo/jira_link/views.py
dojo/management/commands/jira_async_updates.py
dojo/management/commands/rename_mend_findings.py
dojo/management/commands/test_celery_decorator.py
dojo/settings/settings.py
dojo/tools/qualys/csv_parser.py
dojo/tools/qualys_webapp/parser.py
ruff.toml
tests/Import_scanner_test.py
tests/zap.py
unittests/test_parsers.py
unittests/tools/test_api_sonarqube_parser.py

Remove F821 from `lint.ignore` and fix the findings.
This excluded quite critical parts. I'm quite surprised, that there have not been any failing unittests or complaining users.

Ruff: Solve F821

---

docs/content/en/_index.md

Change described password for DefectDojo demo site to reflect the actual password, as listed on the readme.

OS Docs - Add accurate password for DefectDojo demo site

---

dojo/utils.py

[sc-7211]
Notifications were being sent for findings even if the SLA severity was 'not enforced' per settings. This checks for enforcement of the finding severity and, if not enforced, skips notification.
Tested with python manage.py sla_notifications.

if severity not enforced do not notify

---

.github/workflows/k8s-tests.yml
helm/defectdojo/templates/initializer-job.yaml
helm/defectdojo/values.yaml

This PR adds `--wait` and `--wait-for-jobs` to `helm install` to test that there is not some circular dependency or other bug disabling deployment.
Also some additional debug outputs were added.

feat(helm): Use `--wait` during tests

---

Dockerfile.integration-tests-debian

Due to some issues we've encountered with Selenium + Google Chrome >= 128, this pins the version to 127 temporarily to fix integration test workflows.

Pinning Chrome version

---

dojo/tools/npm_audit_7_plus/parser.py
unittests/scans/npm_audit_7_plus/issue_10801.json
unittests/tools/test_npm_audit_7_plus_parser.py

:bug: fix npm audit v7+, issue #10801

---

dojo/tools/sysdig_reports/sysdig_data.py
ruff.toml

Add and fix https://docs.astral.sh/ruff/rules/#flake8-type-checking-tch
Specially: https://docs.astral.sh/ruff/rules/typing-only-standard-library-import/

Ruff: Add and fix TCH

---

dojo/filters.py
dojo/middleware.py
dojo/tools/nexpose/parser.py
dojo/tools/veracode/xml_parser.py
dojo/urls.py
ruff.toml

Fix some ruff ARG rules https://docs.astral.sh/ruff/rules/#flake8-unused-arguments-arg

Ruff: Add and fix ARG003,4,5

---

unittests/tools/test_appcheck_web_application_scanner_parser.py

It might be better to fix based on recommendations - not avoid it.

feat(unittest): Not avoid PLW1514

---

dojo/templates/dojo/view_product_details.html

For faster movement around UI, it is handy to have clickable links if it is possible.

feat(ui): Make ProdType clickable (in Prod detail)

---

dojo/forms.py

Until now, when a user has no permission to add Prod or edit ProdType (a.k.a `get_authorized_product_types(Permissions.Product_Type_Add_Product)` is empty) but the same user still has permission to edit product (Maintainer for that specific product), generated edit form for Product contained empty list for `Product Types`. So user wasn't able to edit this product.
From now on, it does not matter which other permissions a user has, the list of product types contains at least ProdType which is already assigned - so it is possible to submit the form.

fix(edit-prod): Add assigned PT to queryset

---

tests/base_test_class.py
tests/close_old_findings_dedupe_test.py
tests/close_old_findings_test.py
tests/dedupe_test.py
tests/finding_test.py
tests/notes_test.py
tests/product_type_member_test.py
tests/report_builder_test.py
unittests/test_deduplication_logic.py
unittests/test_jira_config_product.py
unittests/test_parsers.py
unittests/tools/test_appcheck_web_application_scanner_parser.py
unittests/tools/test_asff_parser.py
unittests/tools/test_auditjs_parser.py
unittests/tools/test_chefinspect_parser.py
unittests/tools/test_meterian_parser.py
unittests/tools/test_noseyparker_parser.py
unittests/tools/test_yarn_audit_parser.py

Python supports many useful checkers in unittests which (if a test does not pass) are able to provide useful information about the context (why it is not going through, on which position).
It might be good to prefer these `assert*`. And it is not possible to add context as an additional parameter for faster troubleshooting.

feat(unittests): Try to avoid assertTrue/False

---

dojo/importers/default_reimporter.py

When reimporting, findings that previously had multiple vulnerability IDs will suddenly only have a single vulnerability ID (the primary one, or the first one that was created). Two things are occurring here:
- **Where are the vulnerability IDs going?**: When reimports occur, the current finding that exists in the database has its vulnerability IDs are processed, which includes removing all of them before hand. The step that is missing is that the existing finding does not have any `unsaved_vulnerability_ids`. The incoming finding does though. The solution is to set the existing findings `unsaved_vulnerability_ids` to what is set by the incoming finding. That way, if there are any differences between the two (such as the a CVE no longer applying to a vulnerability, or one gets added) then …

Reimport: Set Vulnerability ID from incoming finding

---

dojo/templates/dojo/product.html
dojo/templates/dojo/view_product_details.html

Viewing a product's API scan config is permissible if the product can be viewed. However, the UI would only display the "View API Scan Config" button if the user had permission to at least edit a product. This PR corrects the permission checks in the UI to display the button when a user has permission to view a product
[sc-7458]

Product API scan config: Display view scan configs button for all products

---

dojo/tools/fortify/fpr_parser.py
dojo/tools/fortify/parser.py

The fortify parser made a lot of assumptions on the exact structure of the XML, and did not leave much room for error. This PR accommodates the absences of some data, as well as supporting some variance in formats
[sc-7434]

Fortify Parser: Fortification of the the FPR parsing

---

dojo/tools/threat_composer/parser.py
unittests/scans/threat_composer/threat_composer_many_threats.json

Threat Composer has different behavior for _metadata_ depending on whether it is a threat or a mitigation. In the case of the threat, the 'metadata' key always exists even if no data has been included. However, in mitigation that key may not exist. A fix has been included to validate the 'metadata' key in the mitigation, including an empty list if it does not exist. In addition, comments of the assumptions have been included.

Manage not defined metadata in mitigations and add assumptions comments

---

ruff.toml

This PR was created based on https://github.com/DefectDojo/django-DefectDojo/pull/10111#pullrequestreview-2264320904
Context:
- https://docs.astral.sh/ruff/rules/#mccabe-c90
- https://docs.astral.sh/ruff/rules/complex-structure/
- https://docs.astral.sh/ruff/settings/#lintmccabe
It is far from "perfect" but let's start with adding this rule and we will see how we will be able to improve it over time.
Just some small statistic:
```python
count complexity 
28 11 
29 12 
16 13 
15 14 
9 15 
8 16 
15 17 
7 18 
6 19 
3 20 
3 21 
3 22 
1 23 
7 24 
4 25 
2 26 
1 27 
5 28 
1 29 
2 30 
2 31 
1 32 
1 33 
2 36 
1 37 
1 38 
1 40 
1 42 
1 46 
1 48 
1 57 
2 69 
```

Ruff: Add C90

---

dojo/product/queries.py
dojo/product/views.py
dojo/product_type/queries.py
dojo/product_type/views.py
dojo/templates/dojo/view_product_details.html
dojo/templates/dojo/view_product_type.html

Until now, UI listed only regular members of Prod or ProdType. From now on, owners of Prods are transparently informed that also `Global_Role` members also have access to their data.
In ProdType:
In Prod:

feat(members): List global role members in Prod and ProdType

---

.github/workflows/release-3-master-into-dev.yml

When doing a release that contains settings changes in the `bugfix` branch as well as the `dev` branch, it is inevitable that settings SHA will not be correct when merging master back into the dev branch. To accommodate this, we can regenerate the SHA with the contents of the two branches merge together. This _should_, in theory, reduce the chances of conflicts at release time, or remove them entirely

GHA Release: Update settings SHA when creating PR from master

---

.github/workflows/build-docker-images-for-testing.yml
.github/workflows/release-x-manual-docker-containers.yml

The docker caches in this repo are filling up pretty often. This is in part due to so many unique PRs coming through and using the caches to store their docker layers. It is so awesome to see such engagement, but the cache issues are causing sporadic failures when the cache gets full. To mitigate these cache fills, a cron has been running to periodically empty the caches. This begs the question: "if we are clearing the cache so often, are we really benefitting from having It"
[sc-7396]

GHA: Remove Docker Caches

---

dojo/api_v2/prefetch/prefetcher.py

When prefetching via the API, the serializer to user is dynamically fetched. There are cases where there is more than one `ModelSerializer` on defined, and the wrong one is selected. This PR adds a dict to specify the preferred serializer to user a per model basis
The motivation for this PR is when prefetching a finding with files. Before this PR, a 500 error would be generated
[sc-6061]

Prefetch Serialization: Add a preference during mapping

---

dojo/templatetags/display_tags.py

When attaching files to a finding, images will have a thumbnail generated for quick glance viewing. Currently PDFs are part of the whitelist file extensions that allow a thumbnail to be generated, but that does not work, so we get a "cannot find image" icon
[sc-7547]

Manage Images: Do not display thumbnail for PDF

---

dojo/api_v2/views.py

- The /api/v2/global_role endpoint does not support prefetching, but it really should
- I felt sorta icky copy pasting the whole drf-spectacular schema extension, so I added a function to generalize it, then add it to all of the viewsets that already supported prefetch via the `PrefetchDojoModelViewSet` mixin
[sc-7579]

Prefetching: Add swagger docs for models already supporting prefetching

---

dojo/api_v2/serializers.py
dojo/forms.py
tests/user_test.py
unittests/test_apiv2_notifications.py
unittests/test_apiv2_user.py
unittests/test_rest_framework.py

Creating local users is not the best experience. To accommodate a flow that supports sending temporary passwords to user, and forcing them to login again, we need to make the password field and email field required attributes for new users
[sc-7616]

User: Make email required at all times, password required for new users

---

dojo/api_v2/serializers.py
dojo/api_v2/views.py
dojo/engagement/views.py
dojo/finding/views.py
dojo/jira_link/helper.py
dojo/risk_acceptance/helper.py

When managing risk exceptions, it would very nice to have record on the finding when the finding is added/removed from a risk exception object, or when a simple risk exception is set via the boolean flag. This can achieved but adding a note on the finding
This PR does not address:
- Setting/Unsetting simple risk exception in the edit finding form
- Setting/Unsetting simple risk exception vie the API
- Setting/Unsetting simple risk exception during bulk edit
[sc-7544]

Risk Exceptions: Add/Remove notes when finding is added/removed from risk exception

---

dojo/tools/awssecurityhub/inspector.py
unittests/scans/awssecurityhub/issue_10956.json
unittests/tools/test_awssecurityhub_parser.py

:bug: fix AWSSecurityHub EPSS Score #10956

---

dojo/api_v2/views.py

Generating the response schema for some API endpoints with prefetching will break the Swagger UI:
[sc-7682]

Prefetch: Disable on some viewsets due to payload size

---

dojo/api_v2/serializers.py

Fixes a bug that caused tags in finding templates created via the API to be split into single-letter tags instead of preserving the intended full tags.
Example of correctly and wrongly created tags for the tag "string":

Fix tag creation bug in FindingTemplateSerializer (letters instead of full tags)

---

dojo/tools/trivy/parser.py
unittests/scans/trivy/issue_10991.json
unittests/tools/test_trivy_parser.py

Solves #10991
Added check for `cluster_name` with `None` when parsing trivy kubernetes scan results.
Added unittest with case when ClusterName is empty in trivy kubernetes scan.
```shell-session
./dc-unittest.sh --test-case unittests.tools.test_trivy_parser.TestTrivyParser
...
test_issue_10991 (unittests.tools.test_trivy_parser.TestTrivyParser.test_issue_10991) ... ok
...
```
**Checklist**

Compare trivy results cluster_name with None

---

requirements.txt

Hot reloading appears to be broken in. 2.0.27. The linked GitHub issue is the same behavior that I am seeing
https://github.com/unbit/uwsgi/issues/2681

Downgrade uwsgi to 2.0.26

---

dojo/tools/netsparker/parser.py
unittests/scans/netsparker/issue_11020.json
unittests/tools/test_netsparker_parser.py

Attempt to accommodate any date string format that could be present in the report. In the event that a super strange format cannot be parsed (an example I saw was `03/02/2019 15:50:29 (UTC-06:00)` that is handled explicitly) then the current time will be used rather than throwing an exception
closes #11020 
[sc-7855]

Netsparker: Attempt to accommodate any date string format

---

dojo/templates/dojo/view_test.html

[sc-7768]
Fixes issue#11010
Update path for Full Risk Acceptance when clicking the ... and choosing Add Risk Acceptance... next to a finding in the finding list.

fix for Add Risk Acceptance on Finding List dropdown Not Working

---

dojo/reports/views.py

This PR is aimed to fix an bug when exporting excel reports for findings that has the finding_group field set, causing the Excel file to have displaced columns to the left starting from the finding_group one. This is caused because when trying to add that key from the Finding Ojbject, it is raising an Exception, and it should display the string `"Value not supported"`, line 1002.
The problem is that when this situation happens, it is not increasing the column number value and when the next iteration is processed, the next key is overwriting the values of the column mentioned above, causing this way the displacement of the rest of the columns.
**Checklist**

Fixing bug in Excel Exporter

---

docs/content/en/integrations/importing.md
dojo/api_v2/serializers.py

When a user passes a currently non-existent Development_Environment into import or re-import, and auto_create_context is true, it will now be created if it does not already exist instead of failing with a 500 server error.
Comments also added to indicate the expectation that the call to get_or_create succeeds.
[sc-7806]

Fix for issue #10207  non-existent env import

---

docker/entrypoint-initializer.sh
dojo/fixtures/sla_configurations.json

It would be nice ship dojo with an SLA config that easily omits SLA configs on a per product basis
[sc-7952]

SLA Config: Add new config that does not enforce SLA

---

dojo/tools/tenable/csv_format.py
unittests/scans/tenable/issue_11102.csv
unittests/tools/test_tenable_parser.py

:bug: fix tenable #11102

---

dojo/jira_link/helper.py

Accommodating a strange behavior where a finding group sometimes prefers `obj.status` rather than `obj.status()`
```
File "/app/dojo/jira_link/helper.py", line 666, in push_to_jira
return add_jira_issue_for_finding_group(group, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/dojo/decorators.py", line 73, in __wrapper__
return func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
File "/app/dojo/decorators.py", line 46, in __wrapper__
return func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/celery/local.py", line 182, in __call__
return self._get_current_object()(*a, **kw)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/celery/app/task.py", line 411, in …
```

JIRA Finding Groups: Accommodate status function inconsistency

---

dojo/engagement/views.py
dojo/forms.py
dojo/utils.py

To be consistent with the main Manage Files features across objects, the threat uploads feature needs to have server side extension validation, as well as forcing files to be downloaded
[sc-8130]

Threat Uploads: Server side file extension validation + force downloads

---

helm/defectdojo/templates/configmap.yaml

The deployment using helm is not working at the moment when using the default values. 
As redis.master is not existant in the values.yaml, it crashes when it tries to render template. 
One can now deploy defectdojo.

fix: broker configuration fix for deployment

---

docs/content/en/integrations/notification_webhooks/_index.md
docs/content/en/integrations/notification_webhooks/engagement_added.md
docs/content/en/integrations/notification_webhooks/product_added.md
docs/content/en/integrations/notification_webhooks/product_type_added.md
docs/content/en/integrations/notification_webhooks/scan_added.md
docs/content/en/integrations/notification_webhooks/test_added.md
dojo/notifications/helper.py
dojo/templates/notifications/webhooks/subtemplates/base.tpl
unittests/test_notifications.py

To give the user more information about the events that triggered a webhook, I've slightly modified the logic to ensure that `description` is always populated with _something_, and `title` is included as well in the webhook JSON body. Unfortunately, we aren't always consistent with how we call `create_notification`:
* Sometimes `title` is populated with something that isn't really a "title" at all but more of a description, like the [number of findings added in a scan](https://github.com/DefectDojo/django-DefectDojo/blob/fb442d2defd9ba4aa9c5ece79cde8e1362f33ffb/dojo/notifications/helper.py#L570-L577)
* Sometimes `title` is populated with a formatted string with e.g. [product + engagement name](https://github.com/DefectDojo/django-DefectDojo/blob/dev/dojo%2Fengagement%2Fsign …

Always populating `description`, adding `title` for webhook payloads

---

dojo/tools/tenable/csv_format.py
unittests/tools/test_tenable_parser.py

:tada: add tenable plugin to reference #11127

---

dojo/tools/trivy_operator/checks_handler.py
dojo/tools/trivy_operator/parser.py
dojo/tools/trivy_operator/secrets_handler.py
dojo/tools/trivy_operator/vulnerability_handler.py
unittests/scans/trivy_operator/findings_in_list.json
unittests/tools/test_trivy_operator_parser.py

Trivyoperator has a new report structure.

:tada: fix TrivyOperator new report structure

---

dojo/api_v2/serializers.py

When a scan was imported or reimported, the engagement_end_date was not being used and was defaulting to now + 365 days. This change sets the target_end appropriately for engagements.
[sc-8190]

Fix for engagement_end_date not being used

---

dojo/jira_link/helper.py
dojo/models.py
dojo/utils.py
dojo/views.py
ruff.toml
tests/Import_scanner_test.py
tests/finding_test.py

PTH101
PTH102
PTH103
PTH104
PTH105
PTH106
PTH107
PTH108
PTH109
PTH110
PTH111
PTH114
PTH115
PTH116
PTH117
PTH119
PTH121
PTH124

Ruff: Add and fix multiple flake8-use-pathlib

---

dojo/tools/acunetix/parse_acunetix360_json.py
dojo/tools/acunetix/parse_acunetix_xml.py
unittests/scans/acunetix/issue_11206.json
unittests/tools/test_acunetix_parser.py

:bug: fix Acunetix date #11206

---

dojo/templates/notifications/alert/engagement_closed.tpl
dojo/templates/notifications/mail/engagement_closed.tpl
dojo/templates/notifications/msteams/engagement_closed.tpl
dojo/templates/notifications/slack/engagement_closed.tpl

Add a MS Teams, Email, Alert, and Slack template for engagement closed.
[sc-6170]

add engagement closed MS teams, Email, Alert, and Slack  template

---

dojo/importers/options.py

When adding tags on a model object through the UI or API, the tag is forced to lowercase. Here is an example of the finding model with this requirement:
https://github.com/DefectDojo/django-DefectDojo/blob/fafe5c3cc5f1287963e4681979095b8b8064575f/dojo/models.py#L2571
The issue is that when doing imports, something is bypassed in the way that tags are being added to the model. They are being added like any other many to may relationship, but the `force_lowercase` flag is not being respected for some reason. Instead, we can just force the tags to be lowercased ourselves when the importer processes the tags
[sc-8280]

Importers: Force tags to lowercase

---

helm/defectdojo/templates/_helpers.tpl
helm/defectdojo/values.yaml

This PR
- enables a static name for the Initializer job
- do not change the default behavior
- was already mentioned [here](https://github.com/DefectDojo/django-DefectDojo/pull/11016#issuecomment-2443930306) as enabled
- might be useful for systems that use HELM only to generate templates (like ArgoCD).

feat(helm): Add support for staticName for initializer

---

helm/defectdojo/templates/initializer-job.yaml

The job isn't working well when using an external database because the init container checking if the database is accessible isn't taking the same env values as the container that is initializing the database config
I propose to fix this little issue by simply uniformizing the env provided on the initContainer and the container.
The fix is minor, if you need more information, feel free to ask.

fix(helm): add missing env config on job

---

.github/workflows/build-docker-images-for-testing.yml
.github/workflows/fetch-oas.yml
.github/workflows/integration-tests.yml
.github/workflows/k8s-tests.yml
.github/workflows/release-drafter.yml
.github/workflows/rest-framework-tests.yml

With the upcoming deprecations of version 3 of `actions/upload-artifact` and `actions/download-artifact`, we must get to v4 by following the [migration guide](https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md)
[sc-8285]

GHA Artifacts: Update to v4

---

dojo/decorators.py
ruff.toml

Add S108 https://docs.astral.sh/ruff/rules/hardcoded-temp-file/ and fix it.
- In unittests, they are compared to files from findings - they are not used for writing of content - so it is safe
- `on_exception_log_kwarg` from `dojo/decorators.py` is used nowhere in the project. It looks like it is a leftover from previous testing.

Ruff: Add and fix S108

---

dojo/finding/views.py
dojo/templates/dojo/findings_list_snippet.html

This PR adds a list of reviewers (assigned with the "request peer review" feature) to the UI in the finding pages.
I believe this would make for better finding visualization, and this is something that some users might miss, as noted in issue #10434's discussion.
I have tested (manually) all of the finding listing pages. Except when the findings are filtered by closed, all of the assigned reviewers should be displayed in the rightmost column.  
**Disclaimer**
Please, note that this is my first open source contribution PR ever, so, explaining stuff assuming I know very little about open source might be a good call. 
I'm open to any feedback and to implement any changes that might be necessary. Although I read the contribution guidelines, it's likely that I …

Display reviewers on finding pages.

---

dojo/api_v2/serializers.py
dojo/api_v2/views.py
dojo/jira_link/helper.py

**Title:** Update Jira Epic Engagement in API v2
**Description:**
This pull request includes updates to the Jira Epic engagement functionality in the API v2. The changes aim to improve the integration and handling of Jira Epics within the DefectDojo application.
**Changes:**
- Updated the API v2 engagment endpoint to handle Jira related epic.
**Engagment Edit view**
**API v2 Engagment endpint**
**Jira Epic Update**
- Title
- Priority

API: Engagement update jira epic

---

dojo/tools/bearer_cli/parser.py

:bug: fix bearer_cli #11245

---

dojo/api_v2/serializers.py
dojo/api_v2/views.py

[sc-856]
Added 'batch' endpoint for metadata to create or update multiple metadata at once. The same constraints still apply: can only be added to a single product, finding, or endpoint at a time and the metadata must be unique across the parent object id and the name of the metadata.

DojoMeta: Ability to create or update multiple objects in batch

---

dojo/models.py
dojo/templatetags/display_tags.py

[sc-2885]
When a user requests a review of a Finding, there is a record of who requested a review but nothing about who was requested to review it.
This PR adds this record.

Update audit log with actual requested reviewers

---

dojo/tools/trivy_operator/clustercompliance_handler.py
dojo/tools/trivy_operator/parser.py
unittests/scans/trivy_operator/clustercompliancereport.json
unittests/tools/test_trivy_operator_parser.py

- Enables Trivy Operator to parse the clustercompliance report.
- Refactoring of trivy operator parser to have it better structured.

:tada: Add Trivy Operator clustercompliance report

---

dojo/filters.py
dojo/templates/dojo/endpoints.html

This allows sorting endpoints by ID, both in UI and API.
The UI doesn't have any ID column, so it's not click-accessible, however advanced user can still make use of it via `o=` in the URL.
Motivation is that we do not have a "created" date field in endpoints, in order to find the latest additions.
Sorting by ID (descending in this use case) is a good alternative and less impactful than adding a new date field to the model.
Also adding a small fix in the endpoint list template: when endpoints lose the "product" (not sure how it happens but it did), we're not even able to "see" them as the app would break. Even if there are many more templates that also break, this is the one that lists the endpoints and it already flags "broken" endpoints anyway (though it was not possible to see that …

Allow sorting endpoints by ID

---

dojo/tools/trivy_operator/checks_handler.py
dojo/tools/trivy_operator/secrets_handler.py
dojo/tools/trivy_operator/vulnerability_handler.py
unittests/tools/test_trivy_operator_parser.py

Some TrivyOperator tags were empty

:bug: fix trivyoperator tags

---

dojo/tools/checkmarx_one/parser.py
unittests/scans/checkmarx_one/checkmarx_one_format_two.json
unittests/tools/test_checkmarx_one_parser.py

Modified the parser to accept the case where results may have a missing description. The description and title is then taken from the severity + queryName
[sc-8947]

Update CheckMarx One parser for imports where description is None

---

helm/defectdojo/templates/django-deployment.yaml

Support for debug port `tcp/3000` was dropped in #10692
This is not needed anymore

cleanup(helm): Drop support for TCP/3000

---

dojo/tools/sarif/parser.py
unittests/tools/test_sarif_parser.py

In sarif results -> locations provided list of files by sarif standart. In many scanners like semgrep each item in results contain one file in locations, but in some scanners like mobsfscan scanner reports contain multiple files for one item:
Example for located in tests mobsfscan [report](https://github.com/DefectDojo/django-DefectDojo/blob/master/unittests/scans/sarif/mobsfscan.json#L71):
```
"results": [
{
"message": {
"text": "The App logs information. Please ensure that sensitive information is never logged."
},
"level": "note",
"locations": [
{
"physicalLocation": {
"region": {
"snippet": {
"text": "            Log.d(\"Diva\", \"Error occurred while creating database: \" + e.getMessage());"
},
"endColumn": 88,
"endLine": 57,
"startColumn": 13,
"startLine": 57
}, …
```

Fix sarif parser location files processing

---

dojo/tools/sarif/parser.py
helm/defectdojo/templates/django-deployment.yaml
unittests/tools/test_sarif_parser.py

Release 2.41.0: Merge Bugfix into Dev

---

dojo/filters.py

[sc-4131]
Added a filter for Has Any JIRA which will filter the findings on having group jira or jira_issue. This will also allow a dashboard tile to exist that shows all findings with any type of JIRA issue.

Add a filter for Findings for Has Any JIRA (grouped or single)

---

dojo/finding/views.py

[sc-2890]
This update displays the [user fullname (username)] for both the reviewer and the reviewees.

Request Review Notification Update to Usernames

---

dojo/static/dojo/js/metrics.js

[sc-8650]
Addresses #11254 
The graph on the dashboard for "Reported Finding Severity by Month" is currently displaying data in days, rather than months. And when there is only 1 data point (all findings are from the same day as it was in the demo case in the issue above) then the graph does not display correctly.
This changes the minimum data point to 1 and specifies that the data is by month. This should display accurate, if not visually appealing, data when there is only 1 month's worth of data. As time progresses, the chart will look better and will display up to 6 months of Reported Finding Severity by Month.

Update Reported Finding Severity by Month on the dashboard to be by month instead of day.

---

dojo/api_v2/views.py

[sc-6050]
Returns a BAD_REQUEST status and an error message when attempting to POST a note with a Note Type of 'is_single' - if another Note with that Note Type already exists on the given object (finding, engagement, test).

Disallow multiple single-use notes on a single object 

---

dojo/finding/views.py
ruff.toml

Remove "RUF027" from ignored and fix it.
https://docs.astral.sh/ruff/rules/missing-f-string-syntax/

Ruff: Enable and fix RUF027

---

dojo/endpoint/utils.py
dojo/endpoint/views.py
dojo/jira_link/views.py
dojo/models.py
dojo/product/helpers.py
dojo/reports/views.py
dojo/tools/api_bugcrowd/importer.py
dojo/tools/api_bugcrowd/parser.py
dojo/tools/blackduck/parser.py
dojo/tools/blackduck_binary_analysis/parser.py
dojo/tools/cyclonedx/xml_parser.py
dojo/tools/gosec/parser.py
dojo/tools/sarif/parser.py
dojo/tools/tenable/xml_format.py
dojo/tools/veracode/json_parser.py
dojo/user/views.py
ruff.toml
tests/base_test_class.py
unittests/test_deduplication_logic.py
unittests/test_false_positive_history_logic.py
unittests/test_rest_framework.py

Remove "RUF010" from ignored and fix it.
https://docs.astral.sh/ruff/rules/explicit-f-string-type-conversion/
I see no reason to use `str(...)` in combination with `f"{...}`.
Ruff recommended `f{...!s}` but I believe this is easier and sufficient.

Ruff: Enable and fix RUF010

---

docs/content/en/open_source/upgrading/2.36.md

Update 2.36.md to fix typo's in version number

---

dojo/product_type/views.py
dojo/templates/dojo/view_product_type.html

Add filters to the products listed on the detail page of a particular product type. This will be helpful if and when the number of products under the product type grows beyond a single page.
[sc-4748]

Add Filters to the Products under View Product Type

---

dojo/tools/generic/json_parser.py

When the users are using "Generic Findings Import", it does not allow them to set `epss_score` and `epss_percentile`. This is only because of the historical reason (limitation of allowed fields has been implemented before `epss_*` was added to `Findings`.
Context: https://owasp.slack.com/archives/C2P5BA8MN/p1732001998945879

feat(parser: generic): Allow epss_* parameters

---

.github/workflows/build-docker-images-for-testing.yml
.github/workflows/cancel-outdated-workflow-runs.yml
.github/workflows/detect-merge-conflicts.yaml
.github/workflows/fetch-oas.yml
.github/workflows/gh-pages.yml
.github/workflows/integration-tests.yml
.github/workflows/k8s-tests.yml
.github/workflows/plantuml.yml
.github/workflows/pr-labeler.yml
.github/workflows/release-1-create-pr.yml
.github/workflows/release-2-tag-docker-push.yml
.github/workflows/release-3-master-into-dev.yml
.github/workflows/release-drafter.yml
.github/workflows/release-x-manual-docker-containers.yml
.github/workflows/release-x-manual-helm-chart.yml
.github/workflows/release_drafter_valentijn.yml
.github/workflows/rest-framework-tests.yml
.github/workflows/ruff.yml
.github/workflows/shellcheck.yml
.github/workflows/test-helm-chart.yml

Official documentation recommends SHA pinning: https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions#using-third-party-actions
Also, renovate [supports this syntax](https://docs.renovatebot.com/modules/manager/github-actions/).

feat(GHA): Add SHA pinning

---

docker/setEnv.sh

`debug` env was removed in #10692
The selector needs to be removed as well.
Until now, `./docker/setEnv.sh` was showing `debug` as an available option:
```bash
$ ./docker/setEnv.sh        
Using 'release' configuration.
-> You can switch to 'dev' with './docker/setEnv.sh dev'
-> You can switch to 'debug' with './docker/setEnv.sh debug'
-> You can switch to 'unit_tests' with './docker/setEnv.sh unit_tests'
-> You can switch to 'integration_tests' with './docker/setEnv.sh integration_tests'
```

fix(setEnv): remove debug from list

---

docker-compose.yml

Add variables for `nginx` service in `docker-compose.yml`.
Without them, nginx will create default `/run/defectdojo/usgi_server` which is
```
server uwsgi:3031;
```
Having these variables will give opportunity to change the name of the `uwsgi` service in `docker-compose.yml` and properly create  `/run/defectdojo/usgi_server`

Add uwsgi vars to docker-compose.yml

---

.github/workflows/release-x-manual-helm-chart.yml

The previous implementation used an old version of `helm`, which was pinned in `.github/workflows/release-x-manual-helm-chart.yml`. Renovate and Dependable ignored these values.
Version `v3.4.0` did not support `oci` protocol for pulling charts (support was added in `v3.5` as an experiment and from `v.3.8` by default; source: https://helm.sh/docs/topics/registries/). The current latest version is [`v3.16.3`
](https://github.com/helm/helm/releases/)
The issue has not been noticed because:
- dependency repo (psql) did not use `oci` as default
- linter and release used different method for setup `helm`
This change removes pinning in the "release" step. It uses exactly the same method as the `helm` linter https://github.com/DefectDojo/django-DefectDojo/blob/fc603485650db2e4b9ce532bacda5cfad4ec …

fix(helm): Unpin old HELM version

---

docs/content/en/connecting_your_tools/parsers/generic_findings_import.md
dojo/tools/generic/csv_parser.py
unittests/scans/generic/generic_csv_with_epss.csv
unittests/tools/test_generic_parser.py

epss_score and epss_percentile have been added to the generic parser for csv files
test created to validate that the new headers are read in correctly
documentation on generic parser updated to include the new fields
[sc-9384]

Add EPSS score and percentile to generic csv parser

---

dojo/api_v2/serializers.py

The help on the Active/Verified options for the Import and Reimport Scan APIs is misleading. The help says 'Override the active setting from the tool' and 'Override the verified setting from the tool' which suggests that True means 'Yes, do that', and False would mean 'No, don't override the tool'. However, viewed that way, there is no way to set the Active/Verified, just a way to say 'override' it with "something". The UI allows for a third option: "None" which means do NOT override the tool instead of Override the Tool with This Setting. This PR allows the API to also have a 'None' option and updates the help text to match what is given in the UI.
fixes #11235 
[sc-9259]

Allow None Option for Active/Verified on Import/Reimport to Mirror UI Options

---

docs/config/_default/menus/menus.en.toml
docs/content/en/changelog/changelog.md

Adds Pro release notes for 2.41.3, and adds a 'Changelog' link to the documentation navbar to locate the changelog more easily.

update changelog, add changelog link to navbar

---

docs/content/en/changelog/changelog.md

Release notes for DefectDojo Pro 2.41.4:
- **(API)** Changed functionality of 'Force To Active / Verified' flag: True now forces to Active, while False will keep the tool's status (rather than forcing to Inactive).
- **(Beta UI)** Added ability to regenerate / copy your API token
- **(Beta UI)** Fixed bug preventing date / planned remediation dates from being added via Bulk Edit
- **(Import)** Added fields for EPSS score and percentile to Generic Findings Import parser

Add pro release notes for 2.41.4

---

dojo/finding/views.py
dojo/fixtures/dojo_testdata.json
dojo/jira_link/helper.py
dojo/risk_acceptance/helper.py
unittests/test_jira_import_and_pushing_api.py
unittests/vcr/jira/JIRAImportAndPushTestApi.test_import_grouped_reopen_expired_sla.yaml

[sc-9132]
When a risk exception expires, and reopens all of the associated findings, those changes should be reflected in jira.

Update JIRA for Finding Group When Risk Acceptance Expires

---

README.md
docs/content/en/open_source/api-v2-docs.md
docs/content/en/open_source/ldap-authentication.md

Updates broken links on readme.md to fix https://github.com/DefectDojo/django-DefectDojo/issues/11500

Readme docs update

---

dojo/product/views.py

Fix [RUF046](https://docs.astral.sh/ruff/rules/unnecessary-cast-to-int/). Enabler for #11490

Ruff: Fix RUF046

---

dojo/forms.py

Fix [RUF051](https://docs.astral.sh/ruff/rules/if-key-in-dict-del/). Enabler for #11490.

Ruff: Fix RUF051

---

dojo/importers/base_importer.py
dojo/jira_link/views.py
dojo/tools/scantist/parser.py
dojo/tools/utils.py
dojo/tools/wiz/parser.py
unittests/test_finding_model.py
unittests/tools/test_sonarqube_parser.py

Fix [D403](https://docs.astral.sh/ruff/rules/first-word-uncapitalized/). Enabler for #11490.

Ruff: Fix D403

---

dojo/finding/views.py
dojo/importers/default_reimporter.py
dojo/product/views.py
dojo/test/views.py
unittests/tools/test_tfsec_parser.py

Fix [RUF056](https://docs.astral.sh/ruff/rules/falsy-dict-get-fallback/). Enabler for #11490

Ruff: Fix RUF056

---

dojo/tools/kubescape/parser.py

- This is a change on the kubescape parser
- It removes the resource objects (a whole manifest) from "steps to reproduce" as it is often so long (thousands of lines) that conflicts with the default Jira configurations of maximum accepted length of fields, resulting on the failing to create a Jira ticket via the Defect Dojo integration
- Note that also, there is arguably little value on storing this very large objects on the database (for duplicate and original findings)
- Potentially, the Jira integration should validate that, but that isn't possibly the case

Kubescape: Reduce the size of steps to reproduce

---

dojo/templates/dojo/notifications.html

Dojo was using a static URL while changing the context in the notification menu.
Now, URL is generated from SITE_URL
Reported on https://owasp.slack.com/archives/C2P5BA8MN/p1729065595314239

fix(notification): Use site_url in notification contexts

---

dojo/tools/openvas/xml_parser.py

We are facing difficulties saving a finding to later perform the disambiguation of findings into problems, which will summarize a group of findings into a single problem. There are already several parsers from other tools that pass the variable test as a parameter to the Finding class. I believe there should be no issues with doing something like this.
More information here #11432

including test for Finding in xml parser

---

.dryrunsecurity.yaml
Dockerfile.django-alpine
Dockerfile.django-debian
docker/entrypoint-first-boot.sh
docker/entrypoint-initializer.sh

Extracting first boot portion of script into its own file. 
[sc-8584]

extract first boot portion of script

---

dojo/filters.py

Added EPSS score and percentile range filters. You can set the values to the same number for exact matches.
[sc-7760]

Adding range filters for EPSS

---

dojo/api_v2/serializers.py

When creating/removing a simple risk exception, we create a "paper trail" by adding a note to the finding indicating the action taken. 
[sc-7578]

Notes on Findings for Simple Risk Acceptance

---

dojo/decorators.py
dojo/tools/qualys/parser.py
dojo/tools/qualys_infrascan_webgui/parser.py
dojo/tools/veracode/xml_parser.py

Fix [RUF052](https://docs.astral.sh/ruff/rules/used-dummy-variable/). Enabler for #11490. Alternative to #11450

Ruff: Fix RUF052

---

dojo/models.py

Adding some potential guardrails for race conditions related to async delete
[sc-8961]

Async Delete: Race condition bolstering

---

helm/defectdojo/templates/celery-beat-deployment.yaml
helm/defectdojo/templates/celery-worker-deployment.yaml
helm/defectdojo/templates/configmap.yaml
helm/defectdojo/templates/django-deployment.yaml
helm/defectdojo/templates/network-policy.yaml
helm/defectdojo/values.yaml

Just adding some annotations to helm templates to increase the possibilities in the definition for different resources.

Adding annotations to different resources

---

dojo/filters.py

Fixes filtering for  mitigation for the on/before/after fields
[sc-7759]

Mitigated On/Before/After now use DateTimeFilter

---

dojo/api_v2/serializers.py

There was an instance one PR on `bugfix`, and one PR on `dev` that were touching similar areas of code around the same time . The issue is that each of these PRs were never tested together until they both lived in `dev` 
This PR corrects the use cases of one to pass the tests of the other
[sc-9909]

Fix unit tests

---

docs/content/en/open_source/upgrading/2.42.md

Fix the order of notes
Before change:

fix(doc): Fix order for upgrade notes

---

dojo/user/queries.py

When a user is added to a group with the global role Owner those users should be able to be requested to review any Finding that exists. They should also be able to be added as leads on tests and engagements. 
[sc-9708]

Request Review does not apply RBAC in an expected way

---

docs/content/en/changelog/changelog.md

Adding user-facing changes to Changelog page in docs.

Pro Release Notes 2.42.2

---

.dryrunsecurity.yaml

Add Valentijn to dryrun exempt list

---

.github/workflows/update-sample-data.yml
unittests/test_sample_data.py

The data in the sample data fixture is super old, and needs to be updated. This PR adds a new binary to slide the dates of all objects forward based on the most recent date in the fixture vs today. So for example, the latest date in this fixture file was in October 2021. This is a little over three years ago, so the binary will slide all dates in the file roughly three years forward
The GHA is set to run quarterly and open up a new PR to be reviewed with the changes outlined above
[sc-9788]

Add GHA updater for keep sample data at a reasonable date

---

dojo/templates/dojo/paging_snippet.html

Fixes #11590
The respective nav section is recognised under the aria-label "Pagination navigation". 
The current page has assigned value `aria-disabled true` with `tabindex -1` for better navigation. Instead of "1", "2", "3"... screen reader says "Page 1" / "Page 2" etc...  When using page size dropdown button, user will hear "xyz items per page" instead of just a number.
`<li>` elements are assigned presentation role and their nested `<a>` elements are assigned to menuitem role for more intuitive orientation with keyboard.

Added accessibility for the pagination snippet

---

dojo/templates/dojo/alerts.html

Alerts are being HTML escaped in places where they should not be. Rather on relying on the default HTML escaping, we should use the markdown bleaching templatetag to allow for more options in object titles. Here is a before and after of an innocuous alert vs a dangerous one (no xss triggered here). 
Before: 
After:
[sc-9944]

View Alerts: Sanitize and mark safe

---

dojo/models.py

Recently when debugging a hash_code field config related issue I added this log line which could be helpful.

Log hashcode config not found

---

dojo/static/dojo/css/dojo.css
dojo/templates/dojo/login.html

**Page / Screen Title**
Defect Dojo login
**Page URL / Screen ID**
https://demo.defectdojo.org
**Error Title**
Creating links that are not visually evident without color vision
**Error Severity**
Serious
**Status**
Fail
**Accessibility Issue**
[Description of issue] "I forgot my password" and "I forgot my username" are links without underline and its not visually evident without color vision.
[Impact on users] Users may not know that they are links and can be misleading.
[Pattern] Within the login page.
[Sample of code] `<a id="reset-password" href="/password_reset/">I forgot my password</a>`
**Remediation**
[Recommendation] 
Please remove styles on the hyperlinks so that it is visually easy to know that its an hyperlink. 
[Additional Resources] …

Make links in the login page visually obvious

---

dojo/tools/nmap/parser.py
dojo/tools/openvas/xml_parser.py

i'm including the script_id from tool to consider in the parser of `nmap` and `openvas` fixing a problem of get the id from openvas parser who get the id by the param of the tag.

Fixing openvas parser and including script_id for openvas and nmap

---

dojo/tools/wiz/parser.py
dojo/tools/wizcli_common_parsers/parsers.py
unittests/scans/wiz/multiple_findings.csv
unittests/tools/test_wiz_parser.py

The Wiz CLI parser only imported findings with status `Open` whereas other (Wiz) parsers always import all findings regardless of status.
fixes #11581
Unit test updated.
**Checklist**

Wiz parser: Import findings regardless of status

---

dojo/api_v2/prefetch/mixins.py

When attempting a prefetch with multiple parameters, the response would only return one of the prefetch parameters. 
[sc-6144]

Prefetching multiple endpoints should return all prefetch models

---

dojo/settings/settings.dist.py

- Alphabetical ordering
- added examples where possible
- added a hyphen where possible to make the keys more unique

:tada: make vulnids more robust

---

dojo/notifications/views.py

Adding a Webhook notification was producing this error:
It appears that the `get_webhook_manager_instance` method was intended to return a `WebhookNotificationManger` but maybe there was a typo. With this fix, the test "ping" runs successfully again.
Ruff also auto-fixed some code styling in this file...

Fix Webhook notification test

---

docs/content/en/open_source/upgrading/2.42.md
docs/content/en/open_source/upgrading/2.43.md
dojo/tools/rusty_hog/parser.py
unittests/tools/test_rusty_hog_parser.py

Improvements to Rusy Hog parser:
- For Confluence and JIRA scans, set `file_path` to contain URL of scanned page;
- Ensure `found_secret_string` is actually a `String` and not a `list`;
- Add `Reason` to `description`;
Unit tests updated.
No updates needed
**Checklist**

RustyHog: improve description and file_path

---

dojo/management/commands/import_surveys.py
dojo/tools/mobsf/parser.py
dojo/utils.py

https://github.com/DefectDojo/django-DefectDojo/pull/11630

Fix to bump ruff to 0.9.3

---

.github/workflows/gh-pages.yml
_config.yml

fix: Cleanup of old files and notes

---

docker/entrypoint-initializer.sh
docker/entrypoint-unit-tests-devDocker.sh
docker/entrypoint-unit-tests.sh
docker/unit-tests.sh
readme-docs/CONTRIBUTING.md

Historically the `initializer` and other scripts automatically made new migration files for any changes made to the database model. This is practical for (first time) users making modifications to the Defect Dojo codebase.
But when these migrations end up in production or even staging environments, it may prevent these user from ever being able to upgrade to new upstream releases.
It's possible to merge custom migration with upstream migrations and keep upgrading to newer upstream Defect Dojo releases. But this requires a bit of Django knowledge, which users might not realize until they're stuck in production with an out of sync data model.
This PR (suggests to) remove(s) the `makemigrations` step and instead warns the users if the datamodel was changed without …

Remove makemigrations from scripts

---

dojo/templates/dojo/view_test.html

In the event an empty report is submitted, and there are no findings to be closed, the test_import_finding_action_set will be empty. When viewing import history objects, there is no indication as to what occurred. 
[sc-9738]

Import History: Make the absence of action more clear

---

dojo/jira_link/helper.py
unittests/vcr/jira/JIRAConfigEngagementEpicTest.test_add_engagement_with_jira_project_and_epic_mapping.yaml
unittests/vcr/jira/JIRAImportAndPushTestApi.test_engagement_epic_creation.yaml
unittests/vcr/jira/JIRAImportAndPushTestApi.test_engagement_epic_mapping_enabled_create_epic_and_push_findings.yaml

When attempting to create an Epic in Jira, this error was raised:
``"Field 'customfield_xyz' cannot be set. It is not on the appropriate screen, or unknown."``
The Jira integration needs a custom_field value for 'Epic Name'.  However, Jira Project settings might not actually use 'Epic Name' as a field when creating Epics.  Atlassian made a change in [*August 2023*](https://community.atlassian.com/t5/Jira-articles/Upcoming-changes-to-epic-fields-in-company-managed-projects/ba-p/1997562) which combined the 'Epic Name' and 'Epic Summary' fields.
Newer Jira Projects might not use this field when creating Epics by default, which results in this error message. It looks like they've just changed the default metadata required for Epic creation.  They've left things so that older Projects and API …

Jira Epic Mapping: Support for the removal of `Epic Name` custom fields

---

docs/content/en/open_source/installation/configuration.md
helm/defectdojo/templates/celery-beat-deployment.yaml
helm/defectdojo/templates/celery-worker-deployment.yaml
helm/defectdojo/templates/configmap-local-settings-py.yaml
helm/defectdojo/templates/django-deployment.yaml
helm/defectdojo/templates/initializer-job.yaml
helm/defectdojo/values.yaml

This PR adds the ability to use `local_settings.py` in k8s setup as well

feat(helm-local_settings): Add option to add local_settings.py

---

docker/entrypoint-initializer.sh

The banner URL `defectdojo.com/pricing` is outdated, this link should simply go to defectdojo.com instead.  Thanks @valentijnscholten for noticing this!

Edit defectdojo.com/pricing link

---

dojo/templates/issue-trackers/jira_full/jira-description.tpl
dojo/templates/issue-trackers/jira_full/jira-finding-group-description.tpl

In cases when a finding has `"` (very prevalent with JSON blobs) the final body submitted to jira looks something like this:
```
{
&quot;findings&quot;: [
{
&quot;title&quot;: &quot;test title3&quot;,
&quot;description&quot;: &quot;Some very long description with\n\n some UTF-8 chars à qu&#x27;il est beau&quot;,
&quot;severity&quot;: &quot;Medium&quot;
}
]
}
```
The reason for this is because of the HTML escaping from the `render_to_string` is tampering with the contents of the finding. To mitigate this, applying the `safe` template tag to mark the contents of the finding as "not to be touched" allows for the contents to be shipped to jira without issue. This `safe` template tag can be a scary thing as it may welcome some malicious opportunities if used irresponsibly, but as we are …

Jira Template: Do not HTML encode before shipping to jira

---

dojo/endpoint/views.py
dojo/engagement/views.py
dojo/finding/views.py
dojo/finding_group/views.py
dojo/jira_link/helper.py
dojo/jira_link/views.py
dojo/notifications/helper.py
dojo/product/views.py
dojo/tasks.py
dojo/test/views.py
dojo/tool_config/views.py
dojo/tools/api_sonarqube/importer.py
ruff.toml

Add rule [TRY401](https://docs.astral.sh/ruff/rules/verbose-log-message/) and fix it.

Ruff: Add and fix TRY401

---

.github/workflows/k8s-tests.yml
docker/entrypoint-celery-beat.sh
docker/entrypoint-celery-worker.sh
docker/entrypoint-initializer.sh
docker/entrypoint-integration-tests.sh
docker/entrypoint-nginx.sh
docker/entrypoint-unit-tests.sh
docker/entrypoint-uwsgi-dev.sh
docker/entrypoint-uwsgi.sh
docker/reach_database.sh
docker/unit-tests.sh

Reopen #10497
Extend `wait_for_database_to_be_reachable`. Not only for simple operation but check that DB is compatible.
Added based on https://github.com/DefectDojo/django-DefectDojo/issues/10490
This PR also contains changes from #11650 because they are needed for proper testing of this functionality.

feat(db-checker): Extension of "db reachable"

---

Dockerfile.django-alpine

Until know, it wasn't possible to build `alpine` locally and run it:
```bash
$ export DEFECT_DOJO_OS=alpine
$ ./dc-build.sh       
Checking docker compose version
Supported docker compose version
Building docker compose
[+] Building 0.1s (1/1) FINISHED                                                                  docker:default
=> [uwsgi internal] load build definition from Dockerfile.django-alpine                                    0.0s
=> => transferring dockerfile: 4.34kB                                                                      0.0s
failed to solve: target stage "django" could not be found
```
The same naming convention for both images is needed.

fix(dockerfile): rename django stage in alpine

---

.github/workflows/k8s-tests.yml

feat(k8s-test): Try login and obtain API token

---

dojo/locale/en/LC_MESSAGES/django.po
dojo/templates/dojo/calendar.html

Fixes #11660 
As calendar is from a standalone library, the aria-labels were included using their built-in [viewRender hook ](https://fullcalendar.io/docs/v3/viewRender)
This is a tiny enhancement that is not visible from outside but improves the accessibility of DefectDojo.
Before:
After:

Accessibility calendar switch buttons

---

.github/workflows/update-sample-data.yml

Step forward from #11672 already offers.

feat(gha): Update and pin "peter-evans/create-pull-request"

---

.github/workflows/update-sample-data.yml

As all others GHA: Full version pin + update
replacement for #11671

feat(gha): Pin and update actions/checkout

---

helm/defectdojo/templates/_helpers.tpl

There was a missing successful message for `db-migration-checker`. It might be a bit confusing if the last message of the container is `Database is not migrated to the latest state yet` or if there is a message at all.

feat(db-migration-checker): Add successful message

---

dojo/home/views.py
unittests/test_dashboard.py

dashboard: last 7 days should be 7 days

---

Dockerfile.nginx-debian

The nginx image is built using Debian Bookworm, but was installing the NodeJS version built for Debian Bullseye.
This PR corrects that.

NodeJS: Correct Debian bullseye reference

---

unittests/test_sample_data.py

For some reason, loading sample data in a local setting does not work with `auditlog.logentry` entries, but it has been working in out unit tests. This PR will remove all `auditlog.logentry` entries from the sample data to ensure that both cases can work.
[sc-10141]

Sample Data: Remove audit logs entries

---

dojo/tools/aws_inspector2/parser.py
unittests/scans/aws_inspector2/aws_inspector2_many_vul.json
unittests/tools/test_aws_inspector2_parser.py

Fixing a quick bug with how the AWS Inspector2 parser handles mitigated date parsing.

Fixing call to date_parser in AWS Inspector2 parser

---

.github/labeler.yml
.github/release-drafter.yml

Changes in the `ruff.toml` file indicated that some improvement connected to linters was performed. Why not label these PRs and group them in release notes? It increases the readability of notes.

feat(release): Label and group linters

---

dojo/tools/noseyparker/parser.py

Rule Text ID does not contain the cleartext credentialset in v 0.22.0

:bug: fix Noseyparker description

---

readme-docs/DOCKER.md

dc-unittest.sh -> run-unittest.sh

DOCKER.md: remove leftover `dc-` references

---

dojo/finding/views.py
dojo/jira_link/helper.py
dojo/notifications/helper.py
dojo/templates/base.html

Historically the current notification system always propagates all messages to all channels configured for the notification type / source.
Some messages however are not relevant for all channels, for example reasons why findings cannot be pushed to JIRA.
But we do need to display these alerts in the UI because that's the only place where users can see feedback of these errors/warnings.
This PR introduces an `alert_only` flag to indicate that notifications should only be an alert.
It does reuse all the existing `NotificationManager` logic around System vs Personal notifications, templating and recipients.
This PR also fixes a bug where the "See All Alerts / Clear All Alerts" buttons where not shown due to a Javascript error.
Fixes #11575
Creating a unit …

jira push error reasons should not be propagated to all channels

---

helm/defectdojo/templates/media-pvc.yaml

- Currently when trying to use media-pvc template it fails with the following error:
```
install.go:214: [debug] Original chart version: ""
Error: template: defectdojo/templates/media-pvc.yaml:13:20: executing "defectdojo/templates/media-pvc.yaml" at <.Values.extraLabels>: nil pointer evaluating interface {}.extraLabels
helm.go:84: [debug] template: defectdojo/templates/media-pvc.yaml:13:20: executing "defectdojo/templates/media-pvc.yaml" at <.Values.extraLabels>: nil pointer evaluating interface {}.extraLabels
```
The main issue is related to having in the template the following:
```yaml
{{ with .Values.django.mediaPersistentVolume }}
```
the “dot” (.) now refers to .Values.django.mediaPersistentVolume. In other words, inside that with block, writing
```yaml
{{ …
```

fix: media-pvc template extraLabels

---

requirements.txt

Fix #11799
For some reason pip was installing an old version of `pyopenssl`, something like `22.0.x`. With `pip freeze` I couldn't find any constraints that pointed to the need of an old version. This PR pins `pyopenssl` to `25.0.0` which also fixes #11799

Pin pyopenssl to something recent

---

ruff.toml

After many fixes, we can safely merge some rules without touching the code. I move `FIX002` so we can merge all `FIX` rules.

Ruff: Merge safe rules (A, FIX, PLW01)

---

dojo/api_v2/serializers.py
dojo/importers/base_importer.py

Fixes and see: #6217
This PR catches integrity errors that might happen if the background dedupe delete job deletes findings before the import process is fully completed. In the absence of transactions, for now we implement this "fix".
Manual testing only as creating a unit test / integration test is not feasible within a reasonable timeframe.

Duplicate Delete errors: catch IntegrityErrors (A)

---

dojo/templates/base.html

The "Search" text area has no labels corresponding to it. 
**Accessibility Issue**
[Impact on users] If a form control does not have a properly associated text label, the function or purpose of that form control may not be presented to screen reader users. Form labels also provide visible descriptions and larger clickable targets for form control.
[Steps to reproduce] While using the WAVE addon for FireFox, run it on the page and you will get this error.
**Remediation**
The aria-label had a typo which was fixed.

Fix aria-label in search box

---

dojo/tools/zap/parser.py

Return Feedback about wrong File Format in ZAP

---

dojo/survey/views.py

When editing a survey question, a 404 is presented for a valid object. At some point, the content type for Questions changed to `Defect Dojo` (the verbose name of the app) rather than `dojo` (the common name)
There is only one place where the name of the content type is accessed, so adding some backward compatible checks corrected the issue
[sc-10195]

Surveys: Correct Question 404

---

dojo/templates/dojo/endpoints.html
dojo/templates/dojo/findings_list_snippet.html

Fixes #11818 
Screenshot with screen reader before:
Screenshots with screen reader after:

Added labels for checkbox column headers

---

dojo/static/dojo/css/dojo.css
dojo/static/dojo/js/index.js
dojo/templates/dojo/login.html

If a user is using only the keyboard, they are not able to tab on "Show Password" within the login page.
**Impact on users**
People who are blind (who cannot use devices such as mice that require eye-hand coordination).
People with low vision (who may have trouble finding or tracking a pointer indicator on screen).
Some people with hand tremors find using a mouse very difficult and therefore usually use a keyboard.
**Steps to reproduce**
When you start tabbing within the login page, from the top (URL), Focus goes to Username and then password, and then Login, bypassing show Password.
**Remediation**
Have the "Show Password" keyboard operable by allowing tabbing on the element to be gained.
Image below shows "Show Password" being tabbed over:
Instead of just using the div …

Allow tab to "Show Password" within Login Page

---

dojo/db_migrations/0222_clean_old_sessions.py
dojo/settings/settings.dist.py
dojo/tasks.py

I witnessed a situation when session table `django_session` increased to a size of 3.43GB with 10M tuples. It was the largest table in the whole DefectDojo.
After investigation, I found out that until the user does not log out proactively, the session is not removed even if it is expired:
> Clearing the session store[¶](https://docs.djangoproject.com/en/5.1/topics/http/sessions/#clearing-the-session-store)
> ... If you’re using the database backend, the django_session database table will grow. ...
> ... If the user logs out manually, Django deletes the row. **But if the user does not log out, the row never gets deleted**. ...
> **Django does not provide automatic purging of expired sessions**. Therefore, it’s your job to purge expired sessions on a regular basis. Django provides a …

fix(sessions): Clean old expired sessions

---

dojo/filters.py
unittests/dojo_test_case.py
unittests/test_tags.py

When using the `tags` filter on a finding, the operation applied with multiple tags is an `OR`, but an `AND` expression would be desired. To avoid creating some breaking changes, this PR adds new filters with the filters for `*tags__and` in all the places where tag filters are currently used
[sc-10134]

API Tags: Add filter for `AND` expressions

---

docs/content/en/changelog/changelog.md

Updating release notes for February releases 2.43.[0-3].
[sc-10206]

Release Notes: 2.43.3

---

requirements.txt

https://www.cvedetails.com/cve/CVE-2024-37891/ 
" Users are advised to update to either version 1.26.19 or version 2.2.2"
https://github.com/DefectDojo/django-DefectDojo/pull/11455

:arrow_up: Bump urllib3 to 1.26.20

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/support_request.md

Ask for these versions as users sometimes run into problems running (very) old versions.

github templates: ask for docker compose and helm version

---

dojo/templates/dojo/view_product_details.html

Until the table was showing only the name of the ProdType but there was a chance for misunderstanding that is the name of ProdType and permissions are inherited. Now it is explicitly mentioned next to name of ProdType

fix(ui): Increase readability in "Members" list

---

docker/entrypoint-integration-tests.sh
docs/content/en/open_source/upgrading/2.44.md
dojo/engagement/views.py
tests/Import_scanner_test.py
tests/close_old_findings_dedupe_test.py
tests/close_old_findings_test.py
tests/dedupe_test.py
tests/report_builder_test.py

Remove unused variables and fix the error(s) in integration tests caused by Ruff linting PRs.
```
integration-tests-1  | ======================================================================
integration-tests-1  | ERROR: test_import_same_engagement_tests (__main__.CloseOldDedupeTest.test_import_same_engagement_tests)
integration-tests-1  | ----------------------------------------------------------------------
integration-tests-1  | Traceback (most recent call last):
integration-tests-1  |   File "/app/tests/base_test_class.py", line 24, in wrapper
integration-tests-1  |     return func(self, *args, **kwargs)
integration-tests-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
integration-tests-1  |   File "/app/tests/close_old_findings_dedupe_test.py", line 141, in …
```

fix / cleanup paths in integration tests

---

docs/content/en/connecting_your_tools/parsers/file/trustwave.md

Updates the Trustwave parser documentation with detailed field mappings and additional information. Includes:
- Total fields and their mapping details
- CSV field order and descriptions
- Parser behavior details
- Links to sample data and tool information
1. Documentation change only
2. Verified locally using Hugo server
3. Verified by human and AI LLM review

docs: Updating Trustwave parser documentation with detailed field mappings

---

README.md
readme-docs/CONTRIBUTING.md
readme-docs/DOCKER.md
readme-docs/RELEASING.md

markdown docs: fix dead links

---

helm/defectdojo/Chart.yaml
helm/defectdojo/templates/extra-secret.yaml
helm/defectdojo/templates/secret-postgresql-ha-pgpool.yaml
helm/defectdojo/templates/secret-postgresql-ha.yaml
helm/defectdojo/templates/secret-postgresql.yaml
helm/defectdojo/templates/secret-redis.yaml
helm/defectdojo/templates/secret.yaml
helm/defectdojo/values.yaml

Allow adding annotations to secret resources. 
E.g.: A Kubernetes mutating webhook that makes direct secret injection using annotations - https://bank-vaults.dev/docs/mutating-webhook/annotations/

feat(helm): Add secret annotations

---

helm/defectdojo/templates/django-deployment.yaml
helm/defectdojo/values.yaml

Use case - when I deploy a chart with pvc (ReadWriteOnce), I can't update my Deployment:
```
Multi-Attach error for volume "<volume-name>" Volume is already exclusively attached to one node and can't be attached to another
```
```yaml
...
spec:
...
strategy:
type: Recreate
```
Empty.
**Checklist**

fix(helm): add spec.strategy in deployment django

---

dojo/static/dojo/js/metrics.js
dojo/templates/dojo/dashboard-metrics.html
dojo/templates/dojo/dashboard.html
dojo/templates/dojo/metrics.html
dojo/templates/dojo/product_metrics.html
dojo/templates/dojo/view_product_details.html

Fixes #11798
Adding accessibility features for graphs and charts. Basically no visual difference in appearance just added some aria attributes, and tables, with description within the sr-only class
Before
After
tables for complex graphics example

Added accessibility for charts

---

dojo/notes/urls.py
dojo/notes/views.py

Recent linter updates changed some view method parameter names to avoid shadowing builtin names; this patch simply updates the corresponding url routes to use these new names.
[sc-10365]

Notes history/edit/delete bugfix

---

dojo/importers/base_importer.py
dojo/importers/default_importer.py
dojo/importers/default_reimporter.py
dojo/settings/settings.dist.py

- Added warnings to async_process_findings
- Added comments in settings.dist.py
Note:
I took the text for the warnings  and comments from the [documentation](https://docs.defectdojo.com/en/open_source/installation/running-in-production/#asynchronous-import) . Let me know if I should change this text to something potentially more helpful.
[sc-6355]

Async Finding Import: Mark the feature as deprecated

---

docs/content/en/open_source/archived_docs/integrations/source-code-repositories.md

Small docs update responding to #11945

docs: source-code-repositories: clarify default scm type

---

dojo/importers/default_reimporter.py

`findings_reactivated` and `findings_untouched` had been dropped during some migration, and copy-pasting from `DefaultImporter` did not work.
Notifications are triggered correctly but list (e.g. in email) is empty.

fix(notif): Add findings_reactivated and findings_untouched again

---

docker/entrypoint-unit-tests-devDocker.sh
docker/entrypoint-unit-tests.sh
docker/entrypoint-uwsgi-dev.sh
docker/entrypoint-uwsgi.sh

Some entrypoint scripts where using `sh` which doesn't recognize `if [[...` used in places like `wait_for_database_to_be_reachable`
Fixes these errors on startup:
```
/entrypoint-uwsgi.sh: 21: [[: not found
```
Credits to @9alexx3 on Slack for suggesting this fix.

docker entrypoints: use bash everywhere

---

dojo/tools/checkmarx_cxflow_sast/parser.py
ruff.toml

Add rule [class-as-data-structure (B903)](https://docs.astral.sh/ruff/rules/class-as-data-structure/#class-as-data-structure-b903) and fix it

Ruff: Add and fix B903

---

dojo/templates/dojo/profile.html
dojo/templates/dojo/view_group.html
dojo/templates/dojo/view_product_details.html
dojo/templates/dojo/view_product_type.html
dojo/templates/dojo/view_user.html

The links to existing permissions/groups documentation (e.g. [https://documentation.defectdojo.com/usage/permissions/](https://documentation.defectdojo.com/usage/permissions/)) no longer exist.
This pull request updates documentation links for Product Type and Product membership, as well as Group Membership in the User, Group, Product Type, and Product views.
[sc-10454]

update permissions documentation links to reflect correct paths

---

docs/content/en/open_source/upgrading/2.42.md
docs/content/en/open_source/upgrading/2.43.md
docs/content/en/open_source/upgrading/2.44.md

Some small fixes here mainly around quoting.

upgrade notes: correct dedupe command lines

---

readme-docs/DOCKER.md

Some example commands where using `docker ...` instead of `docker compose`.

DOCKER.md: use docker compose everywhere

---

helm/defectdojo/templates/django-deployment.yaml

For `nginx-prometheus-exporter` from `v1.0.0`, the flag format was changed. Old is still not deprecated, but there is already a warning:
```
the flag format is deprecated and will be removed in a future release, please use the new format: --nginx.scrape-uri
```

fix(helm-metrics): Flag format for promExporter changed

---

dojo/utils.py

Encounted by a user on Slack.
Fixes a `NoneType` error when the selected set of models for mass update is actually empty.

dedupe command: fix NoneType on empty set of models

---

.github/workflows/validate_docs_build.yml
docs/package-lock.json
docs/package.json

The deployment of the docs have been breaking recently. This PR pins the version of the dependencies, and adds a unit tests to determine if dependency updates will break the build
[sc-10568]

Docs: Pin versions and add GHA for testing build failures

---

dojo/jira_link/helper.py
dojo/jira_link/views.py
dojo/settings/settings.dist.py

When interacting with jira tickets that attached finding groups, we should no be opening any findings on the DefectDojo side because jira has no way of knowing if a finding really should be reopened or not
[sc-10319]

Jira Webhook: Prevent finding group findings from being reopened

---

helm/defectdojo/templates/initializer-job.yaml

If the Kubernetes Namespace has ResourceQuotas set. the "wait-for-db" pod is unable to start, as resources are forced to be set.
For simplicity, I would use the same resources as for the main container from the Job
**Checklist**
- [ x ] Bugfixes should be submitted against the `bugfix` branch.
- [ x ] Give a meaningful name to your PR, as it may end up being used in the release notes.
- [] Add the proper label to categorize your PR.

add resources to wait-for-db

---

docs/content/en/customize_dojo/user_management/configure_sso.md

Recently this text was improved. I suggest a further improvement. Mainly to make it more clear that if users opt to put the environment variables inside local_settings.py, they need to remove the `DD_` prefix.
If this turns out to be still not clear for users I think we will have to remove any references to `local_settings.py` here and just point to the open source configuration page which explains this in more detail.

sso docs: make environment variables vs local_settings more explicit

---

dojo/importers/default_importer.py
dojo/importers/default_reimporter.py

When processing many imports at once, it was noticed that memory of the redis container was maintaining a very high level. This is because the findings parsed from the submitted report were being saved on the Importer class, and in scope for the entire duration of the process. We should not maintain the list of parsed findings after they have been consumed 
[sc-10595]

Import Memory Handling: Do not maintain parsed findings long term

---

docs/content/en/open_source/archived_docs/usage/features.md

Second try of https://github.com/DefectDojo/django-DefectDojo/pull/12119:
This feature summary page is useful in search until we get more "Tags" documentation written, so it should not be excluded from search.

remove exclude_search from Features page

---

dojo/settings/settings.dist.py
dojo/templatetags/display_tags.py

It depends, but some use "SSA:" and some use "SSA-" to define the slackware security advisory. This PR covers both.

:tada: Add slackware security advisory to vulnid

---

docs/content/en/share_your_findings/jira_integration/connect_to_jira.md
docs/content/en/share_your_findings/jira_integration/troubleshooting_jira.md

Adds some more troubleshooting steps around JIRA webhooks.

jira docs: add ssl certificate instructions

---

docs/content/en/open_source/installation/running-in-production.md

Instructs users to change the AES encryption key when running in production.

docs: running in production should change aes key

---

dojo/context_processors.py
dojo/settings/settings.dist.py
dojo/templates/base.html

Re-creation of https://github.com/DefectDojo/django-DefectDojo/pull/12054
Issue: Session timeout without letting the user either extend the time or have any type of indication that the session is about to expire.
A warning will appear shortly before the session expires using Bootstrap's modal components warning the user their session will expire soon.
**Impact on Users**
People with physical disabilities often need more time to react, to type and to complete activities. People with low vision need more time to locate things on screen and to read. People who are blind and using screen readers may need more time to understand screen layouts, to find information and to operate controls. People who have cognitive or language limitations need more time to read and to …

Session timeout notification

---

docs/content/en/connecting_your_tools/parsers/file/rusty_hog.md
dojo/tools/rusty_hog/parser.py
unittests/tools/test_rusty_hog_parser.py

:hammer: RustyHog: handle empty reports correctly to fix #10584

---

.github/renovate.json

Until now, every time when new version of the package was released, Renovate offered the latest version (so far so good). This might not be the best situation if it is not possible to update to the latest one (change of license or some other radical change), but upgrading to a higher patch (same major and minor) is safe.
Thanks to this PR, renovate will open a separate PR if there is a newer patch for the same minor.
This will help with:
- Upgrade of Redis `7.2.5` to `7.2.7` (without jumping to `7.4` - https://github.com/DefectDojo/django-DefectDojo/pull/10651, https://hub.docker.com/_/redis/tags?name=7.2.7)
Note: we will need the same for dependabot, because of:
- `urllib3`: `1.26.18` -> [1.26.20](https://pypi.org/project/urllib3/1.26.20/) vs …

fix(renovate): Add separateMinorPatch

---

dojo/models.py
dojo/product/helpers.py
dojo/sla_config/helpers.py
dojo/utils.py

This PR optimizes the updating of the `sla_expiration_date` field. A change to an SLA Configuration or Product can trigger a recalculation of this field for all affected findings. 
Before this PR this took ~8.5 minutes for 20k findings. This is on a i9 16 core with an NVM SSD. 
This PR used the `mass_model_updater` function that has proven to work more efficiently. Now the job completes in ~30s time.
Before this PR, every finding would be post processed in the background celery work. This isn't needed as a change to the SLA expiration doesn't affect dedupe or pushing to JIRA. Also the product grade would be calculated for each affected finding (so multiple times per product). This is not needed. This background work took over 30 minutes for 20k (I killed the instance after 30 minutes). …

sla_config: use mass update for recalculation

---

docs/content/en/connecting_your_tools/parsers/file/h1.md
dojo/tools/h1/parser.py
unittests/scans/h1/vuln_disclosure_main_state.json
unittests/tools/test_h1_parser.py

Hacker One Vulnerability Disclosure parser improvements
For H1 Vulnerability Disclosure reports the field `main_state` should be used. This field can be `open` or `closed`. To be safe we consider everything `Active` unless the `main_state` is `closed`.
Additional changes:
- Update docs on supported formats
- Parse `closed_at` field as mitigation date
- Parse CVSS3 data
- Parse asset metadata
- Parse cve_ids

h1: vulnerability disclosure parser improvements

---

docs/content/en/open_source/contributing/how-to-write-a-parser.md

The how-to-write-a-parser contained code that made Ruff unhappy.

Linting: Update how-to-write-a-parser.md to not contain Ruff violations

---

dojo/importers/base_importer.py

Sometimes (as in #12168) findings get mitigated during import because the finding is mitigated in the scan report. That scan report can also contain a `mitigated` timestamp. Currently DefectDojo always overwrites this timestamp during reimport. This PR changes that to no overwrite it. 
This is just a quickfix as the root cause is that the findings are already closed and don't need to be seen as old findings are they are still in the report. We'll work on that in a later PR.

close old findings: don't overwrite mitigated timestamp

---

dojo/templates/notifications/mail/engagement_added.tpl
dojo/templates/notifications/mail/engagement_closed.tpl

Until now, the product's name has been rendered as `None`. Probably some old copy-paste issue.

fix(notif): Product name not rendered correctly

---

dojo/importers/default_reimporter.py
dojo/tools/checkmarx_one/parser.py
unittests/dojo_test_case.py
unittests/scans/checkmarx_one/one-open-one-false-positive.json
unittests/scans/checkmarx_one/two-false-positive.json
unittests/test_import_reimport.py
unittests/tools/test_checkmarx_one_parser.py

When performing a reimport, the status of a finding from the report that is either false positive, out of scope, or risk accepted is being discarded. This is due to a flaw in the  way findings are calculated for the `close_old_findings` function.
Let's say we have a finding in the database that is active. In the next reimport, the same finding is being reported form the tool as false positive. Reimport will do the following:
1.  Store the list of original findings
2. Parse the findings
3. Find a match between this new false positive finding, and the existing active finding
4. Set the active finding to false positive, and save the finding to the database
5. Determine the findings to be closed by subtracting the findings from the report from the original list of findings from step 1.
- This …

Reimport: Special statuses should be respected from reports

---

helm/defectdojo/Chart.yaml

Reverts DefectDojo/django-DefectDojo#12271

Revert "Release: Merge back 2.45.2 into dev from: master-into-dev/2.45.2-2.46.0-dev"

---

docs/content/en/connecting_your_tools/parsers/file/wiz.md

Update the Wiz Parser documentation including detailed mapping of standard .csv format and SCA .csv format to DefectDojo finding.
Update to Wiz.io Scanner and SCA parser documentation detailing support for both standard and SCA .csv exports.  Tests included side-by-side review by importing .csv files from unittests/scans/wiz and correlating .json export using DefectDojo API GET Findings endpoint.  Additional details derived by correlating parser functions within wiz python.py.
No Wiz parsers were injured or altered in the making of this documentation.

Update Wiz parser documentation - Standard & SCA imports

---

dojo/importers/base_importer.py
dojo/tools/tenable/csv_format.py

Throw a clear error message when `Plugin Name` or `asset.name` are missing from the CSV report.

tenable: check mandatory columns before importing

---

dojo/models.py
unittests/test_sla_calculations.py

Fixes #12299 introduced in #11924
The old code had parsing in place for parsers that didn't set the `finding.date` correctly. These parsers provided a `str` instead of `date`. This PR ensures this implicit parsing is performed with the simplified SLA logic.
This implicit parsing was tucked away in the `_age()` method: https://github.com/DefectDojo/django-DefectDojo/blob/8e7cc01142c5f8d7b31b85e686cbd28d341ad2ca/dojo/models.py#L3004-L3007
The unit tests of parsers don't trigger this SLA logic, we'll look to add more checks to the parser unit tests in a future PR.
All affected parsers are now working again:

sla: parse finding.date implicitly

---

docs/content/en/open_source/upgrading/2.46.md
dojo/db_migrations/0201_populate_finding_sla_expiration_date.py
dojo/models.py
dojo/settings/settings.dist.py
dojo/utils.py

As reported in #11833 the SLA Business days feature is nog longer working. There are currently no plans to reintroduce it. This PR removes left over code and configuration settings to avoid confusion.
If the feature returns, it will probably be part of the SLA Configuration settings so it can re-use the existing recalculation logic on configuration changes.
Please follow #11833 for future developments.

Remove non-working DD_SLA_BUSINESS_DAYS feature to avoid confusion

---

dojo/templates/notifications/webhooks/subtemplates/base.tpl
dojo/templates/notifications/webhooks/subtemplates/engagement.tpl
dojo/templates/notifications/webhooks/subtemplates/findings_list.tpl
dojo/templates/notifications/webhooks/subtemplates/product.tpl
dojo/templates/notifications/webhooks/subtemplates/product_type.tpl
dojo/templates/notifications/webhooks/subtemplates/test.tpl
dojo/templatetags/as_json.py
unittests/test_notifications.py

Fix #11959 and https://owasp.slack.com/archives/C2P5BA8MN/p1744296388842759

fix(webhook): Missing quotation -> broken rendering

---

dojo/templates/dojo/findings_list_snippet.html
dojo/templates/dojo/view_test.html
tests/import_scanner_test.py

Adds the author and date to the most recent note display in lists of findings.
The js/css lib used doesn't support styling the content, this is what it looks like:
The unrelated commit is a Ruff fix that was automatically applied. When I remove it, it complains that it is a Ruff violation :-) So I left it.

most recent note: show date/author

---

dojo/api_v2/serializers.py
unittests/test_rest_framework.py

Until now, the API endpoint `POST /api/v2/risk_acceptance/` (which also applies to `PUT` and `PATCH`) has not accepted `recommendation` and `decision`. As a result, DD used the default value (fix for recommendation and accept for decision). There was no error message.
For `GET` requests, DD translated the chosen value (one of `A`, `V`, `M`, `F`, `T`) to human-readable form.
It sounds nice, but not if it means that fields are not writable.
This PR dropped `SerializerMethodField`s with `get_...` methods, which locked these fields to read-only mode. Now, during the creation of RiskAcc, the user is able to define `recommendation` and `decision`.
The only "disadvantage" is that it is now unable to see a human-readable form anymore.
APIs are not for humans but for machines, so simple values …

fix(api): Enable to set `recommendation` and `decision` in `risk_acceptance`

---

dojo/jira_link/views.py

This PR updates a few things to catch some corner cases:
- Remove the check for the same author when looking for existing comments
- There is [a check further up in the webhook comment processor to skip comments from jira made by the same user that created the jira instance in dojo](https://github.com/DefectDojo/django-DefectDojo/blob/477583eb674a6a93516a2b794cd9889cb6d7ab81/dojo/jira_link/views.py#L234-L238). This is great for all smaller teams, but not larger ones
- In cases where this is not true, like when a service account is connecting to jira, only the case is considered when the webhook could fire twice (see description in #9513), the content of the message must be checked as well. This will not cause a regression as the content is still a safe check.
- Check for note contents …

Jira webhook comment duplicate patch

---

docs/content/en/connecting_your_tools/parsers/generic_findings_import.md
dojo/importers/base_importer.py
dojo/importers/default_importer.py
dojo/importers/default_reimporter.py
dojo/tools/generic/json_parser.py
dojo/tools/parser_test.py
requirements.txt
unittests/scans/generic/generic_custom_test_with_meta.json
unittests/test_generic_meta_import.py
unittests/tools/test_generic_parser.py

Generic Finding Import is capable of importing data from the report that influences the name of the test type and some other fields on the test. This behavior could be expanded to also influence the `static_tool` and `dynamic_tool` fields as well.
The following things were added to accomplish this:
- Expand the `ParserTest` class  to accommodate the new fields
- Rework the dynamic test parser in the importers to allow for fields to be set during import, and overwritten during reimport if fields are supplied
- Unit tests at the parser and import/reimport level to cover to above
- Docs to explain how these fields are used
[sc-11026]

Generic Parser: Support Test Type Meta

---

dojo/tools/tenable/csv_format.py
dojo/tools/tenable/utils.py
dojo/tools/tenable/xml_format.py
tests/import_scanner_test.py
unittests/scans/tenable/nessus/nessus-template.csv
unittests/tools/test_tenable_parser.py

Users reported on Slack that the Nessus CSV report can contain fields that are currently not parsed by DefectDojo:
Reference: https://owasp.slack.com/archives/C2P5BA8MN/p1743609798217049
This PR parses some more fields in the csv parse:
- epss_score
- more references
- vpr score
- stig score
- canvas
- metasploit exploitable
- core impact
- canvas
- plugin information
To me it's not clear what some of these fields, but probably anyone using Nessus will understand. So it's good to have these values in the description, references or severity_justification field.
We decided for now not to parse the CWE field that is present in the XREF fields as it would influence the hash code calculation which we would not be able to get aligned with older findings that did not have the cwe field parsed …

nessus: parse more fields

---

.github/workflows/release-1-create-pr.yml

- Adds a dropdown choice to the GHA that kicks off the OS release. Currently this is a free form text field which could lead to shenanigans. 
- Adds input validation based on branch and release number. We expect dev releases last octet to end in "0" and bugfix releases to be 1 or greater. 
Validated working and non-working combinations of branch to release number. 
- dev with 2.33.1 (failed validation, as expected)
- dev with 2.33.0 (pass)
- bugfix with 2.33.0 (fail)
- bugfix with 2.33.1 (pass)
- either branch with letters, non-alphanum chars, etc. (fail).

Add input validation (branch to release num) for the release gha

---

docs/package-lock.json
dojo/static/dojo/css/dojo.css

**Page / Screen Title**
Dashboard
**Page URL / Screen ID**
https://demo.defectdojo.org/dashboard
**Error Title**
Focus Indicator Disappears While Tabbing
**Error Severity**
Serious.
**Status**
Fail
**Accessibility Issue**
[Description of issue]
When Tabbing throughout the application, the focus indicator disappear.
[Impact on users]
- This Success Criterion helps anyone who relies on the keyboard to operate the page, by letting them visually determine the component on which keyboard operations will interact at any point in time.
- People with attention limitations, short term memory limitations, or limitations in executive processes benefit by being able to discover where the focus is located.
[Pattern] Start tabbing from the url and throughout the application.
[Steps to reproduce] When …

Focus Indicator Disappears While Tabbing - DefectDojo Accessibility issue (Serious)

---

.github/workflows/gh-pages.yml
.github/workflows/slack-pr-reminder.yml

Disable execution of specific GHA in forks.
They would just fail, and it just generates noise.

fix(GHA): Avoid some actions in forks

---

dojo/locale/en/LC_MESSAGES/django.po
dojo/templates/login/forgot_username.html

Just fix a typo in the UI when going to the clicking on "I forgot my username" from the login UI
No test here.
N/A

ui: fix "retrieve my username" typo

---

dojo/finding/views.py

In #11738 we reduced the noise for when a push to jira was triggered for findings that were not active or not verified. 
There was one place left where this message was still logged on `ERROR` level. Since this is a normal scenario, logging to `DEBUG` is sufficient. User triggering this action via the UI are still getting a msg as feedback. 
Reported via Slack: https://owasp.slack.com/archives/C2P5BA8MN/p1746205059640759

jira push: log inactive/verified message to debug

---

.github/workflows/release-x-manual-helm-chart.yml

The helm chart publish step had a hardcoded `ref: master` on the checkout step.
Now that we have the `nightly-dev` builds merged and enabled, this means the wrong ref is checked out for the helm cart publishing. It overwrites the latest release info in the helm chart.
This PR fixes the checkout ref.
For now I have disabled the `nightly-dev` builds and I've regenerated the helm-chart for 2.46.0:  
- https://github.com/DefectDojo/django-DefectDojo/actions/runs/14864126991/job/41736476121
- https://github.com/DefectDojo/django-DefectDojo/commit/e10b8fe3e41295e0f616c84ad86bd3589adbfb54
Thanks @kiblik for raising this and working together on a fix.

helm chart publisher: use proper ref for checkout

---

dojo/forms.py
dojo/utils.py
tests/finding_test.py

Fixes #12394 where any save action via the UI will clear the `tags` field on the saved object.
Any `clean_<fieldname>` method in Django must return the cleaned value of the field. If nothing is returned, the field will become empty. https://docs.djangoproject.com/en/5.2/ref/forms/validation/
Confirmed validation is working OK:
I tried to add a simple smoke test for the tags field in the UI tests, but it's not trivial as the tags field is dynamically generated on the client-side.
REST API validation and modification of objects is working fine (has test cases)

tags: prevent validation from removing tags

---

docs/content/en/open_source/performance.md

The [performance enhancements](https://docs.defectdojo.com/en/open_source/performance/) page in the docs mentions "Asynchronous Import" as a feature. This PR removes this mention. This will be great to merge once this feature has been depreciated.
[sc-6361]

Update Docs For Asynchronous Import Feature Removal

---

dojo/utils.py
unittests/test_rest_framework.py

When downloading files with quotes in the title stored in DefectDojo, some browsers truncate the name of file, while others replace the problematic characters with a hyphen. I think the replacement mechanism is the most sound one as it leaves the file in a workable state still
[sc-11081]

Managed Files: Sanitized file name before downloading

---

dojo/tools/ms_defender/parser.py

The check to bail out early expects a `vulnerabilities/` folder entry to always be present in the zip file if there are files in that folder. We've seen that this is not always the case as some zips do not contain entries for folders, only entries for actual files.
This PR changes the "bail out check" to work well in both scenario's.
Raised by user on Slack: https://owasp.slack.com/archives/C2P5BA8MN/p1747126211915059

defender: fix no vulnerabilities check

---

dojo/api_v2/serializers.py
unittests/dojo_test_case.py
unittests/test_tags.py

When attempting to attach multiple tags during a reimport through the swagger docs page, the curl request that is generated places all submitted tags in the same form field in a comma separated list. In the recent changes from #1294, commas are not longer allowed. This PR allowed for tag enforcement in lists, but not when a string is passed. Unfortunately correcting the generated curl request is not really feasible, so we must return to approach of splitting all tags from the API by commas.
Slack Context: https://defectdojo-workspace.slack.com/archives/C2P5BA8MN/p1747055360228049 
[sc-11116]

Tags: Add support for comma separation for multipart forms (import/reimport)

---

dojo/reports/views.py

Enhance logging for errors during Excel exports. Or rather they are warnings, so we log them at `warning` level from now on.
Inspired by #11911
Added later: Some more testing lead me to what I believe is a copy-and-paste error where `get_foreign_keys()` was not called. 
So the PR now also fixes the conversion problem and outputs finding group values correctly:

excel export: enhance handling of finding groups, better logging

---

.gitignore
tests/finding_test.py
unittests/test_finding_model.py
unittests/test_rest_framework.py

While working on #12440 I decided to add the test cases from there also to the current bugfix branch to capture the old behaviour of the "old" RegEx based `cvssv_validator`.
This also helps us with understanding #8264

cvssv3: backport tests

---

dojo/templates/dojo/ad_hoc_findings.html
dojo/templates/dojo/add_findings.html
dojo/templates/dojo/add_group.html
dojo/templates/dojo/add_risk_acceptance.html
dojo/templates/dojo/add_template.html
dojo/templates/dojo/apply_finding_template.html
dojo/templates/dojo/edit_finding.html
dojo/templates/dojo/edit_presets.html
dojo/templates/dojo/edit_product.html
dojo/templates/dojo/edit_product_type.html
dojo/templates/dojo/new_eng.html
dojo/templates/dojo/new_params.html
dojo/templates/dojo/new_product.html
dojo/templates/dojo/new_product_type.html
dojo/templates/dojo/promote_to_finding.html
dojo/templates/dojo/view_risk_acceptance.html

Fixes #12363 
To make native spell checking work with EasyMDE text fields, we need to DISABLE spell checking on the field.
This was already done, but we also need to change the `inputStyle` to `contenteditable`.
This wasn't clear to a lot of people including me: https://github.com/Ionaru/easy-markdown-editor/issues/617, for which I raised https://github.com/Ionaru/easy-markdown-editor/pull/619
The change to `contenteditable` doesn't seem to have a noticable effect, I can still create/edit findings and other objects. Just to be safe I added it to 2.47.0 and not the first upcoming `bugfix` release.

easymde: enable native/browser spell checker

---

dojo/settings/settings.dist.py

I noticed that `CELERY_LOG_LEVEL` get stomped on when a higher severity of `DD_LOG_LEVEL` is used

Celery Logging: Respect CELERY_LOG_LEVEL

---

docs/content/en/connecting_your_tools/parsers/file/anchorectl_policies.md
dojo/tools/anchorectl_policies/parser.py
unittests/scans/anchorectl_policies/new_format_many_violations.json
unittests/scans/anchorectl_policies/new_format_no_violation.json
unittests/scans/anchorectl_policies/new_format_one_violation.json
unittests/scans/anchorectl_policies/new_format_one_violation_description_severity.json
unittests/tools/test_anchorectl_policies_parser.py

This PR fixes the AnchoreCTL Policies Report parser to support both legacy and new formats generated by the AnchoreCTL tool. Users reported issues importing newer format policy reports from AnchoreCTL with the `-o json` flag, as the parser expected a list at the root level, but new format has an object with an `evaluations` array.
The changes:
- Add detection logic to identify the new format (object with 'evaluations' array)
- Implement transformation logic to convert new format data into a structure compatible with existing parser logic
- Improve error handling with more descriptive messages
- Make field extraction more robust with proper fallbacks for both formats
Extended the test suite by adding 4 new test cases that specifically target the new format: …

Add new "evaluations" format support to Anchorectl parser 

---

dojo/importers/default_reimporter.py
dojo/utils.py

In some scenario's the reimporter will fall back to the legacy dedupe algorithm that looks at the `title` and `severity` of existing findings. Although this is not a preferred situation, it happens when no dedupe hash field configuration is present for the parser.
At the time of writing this is the case for the OpenVAS parser. This can lead to false negative matching behavior as reported in #12378. This is because Defect Dojo uses `titlecase` to format the title of a finding before saving. So existing findings will can have a different `title` from the findings being processed by the reimporter because the latter are not saved yet.  Since Postgres is performing case sensitive comparisons by default, we have to explicitly make the comparison case insensitive with this PR.
There are no …

legacy reimport: make matching on title case-insensitive

---

docs/content/en/open_source/contributing/how-to-write-a-parser.md
dojo/tools/fortify/fpr_parser.py
dojo/tools/ms_defender/parser.py
dojo/tools/ptart/retest_parser.py
unittests/tools/test_ms_defender_parser.py

The MS Defender parser was caching parsed findings over time. This PR fixes that and adds a note to the how-to-write-a-parser guide.
Reported on community Slack: https://owasp.slack.com/archives/C2P5BA8MN/p1747924116271049?thread_ts=1747917376.987169&cid=C2P5BA8MN

ms defender: do not cache parsed findings

---

dojo/settings/settings.dist.py
dojo/tools/bearer_cli/parser.py
unittests/tools/test_bearer_cli_parser.py

I'm storing the unique fingerprint from bearer which is always present in the scan file in the field unique_id_from_tool. I also changed the deduplication algorithm setting in dojo/settings/settings.dist.py from DEDUPE_ALGO_HASH_CODE to DEDUPE_ALGO_UNIQUE_ID_FROM_TOOL_OR_HASH_CODE
There is no existing unit test to extend.
Updating the documentation should not be necessary for this tiny change
**Checklist**
This is my first PR for defect dojo, please let me know if I made a mistake. I'll fix it right away.

Store fingerprint from bearer in unique_id_from_tool

---

dojo/templates/dojo/product_metrics.html

Hi,
The footer for "Week to Week by Severity" and "Critical Week to Week" in detailed metrics displays a gap that is not present in the other metrics.
Note: Please disregard the rounded corners in the image — they are part of a small experiment. This issue also occurs in the unmodified version.
The issue is cause by closing the "panel panel-default" `<div>` too early.

Bugfix: fixed wrong panel-footer margin in detailed metrics

---

dojo/jira_link/helper.py

Probably Fixes #12158
The JIRA helper was checking whether a new JIRA issue needed to be created or an existing needed to be updated. 
This check happened before the task was submitted to Celery for background processing. This check was too early as by the time the `add_jira_issue` task was picked up by Celery there could have been another `add_jira_issue` task before that which had already created an issue. This could happen in certain scenario's with a slow celery worker, slow JIRA and/or fast import-reimport touching the same findings.
This PR now moves the check for an existing JIRA issue inside the celery task itself to avoid this scenario.
In theory duplicates could still happen when running multiple workers in parallel. To avoid that we would some kind of locking to ensure only one …

push to jira: check for existing jira issue inside celery task 

---

dojo/api_v2/views.py
dojo/filters.py

Adds filters to the `metadata` endpoint that can filter on `name` and `value` in a case insensitive way
[sc-11313]

Dojo Meta: Migrate to `filterset_class` + Add case Insensitive filters

---

dojo/templates/base.html
dojo/templates/dojo/login.html

When logging in with SAML, the `next` parameter is not respected like it is for other SSO providers
[sc-11368]

SAML Login: Respect `next` parameter

---

dojo/jira_link/helper.py

I noticed that Findings that were "Risk Accepted" in JIRA did not set the `finding.risk_accepted` field. Also a full `Risk_Acceptance`  was created even if that feature was disabled for the product. This PR corrects this.
This code is executed when a webhook is coming from JIRA or when the management command  `jira_status_reconciliation` is run.

JIRA helper: respect simple/full risk acceptance on webhook processiing

---

docker-compose.yml

This change blocks the start of `uwsgi`, `celerybeat`, and `celeryworker` until `initializer` is not `completed_successfully`. This is useful for:
- avoiding errors in `uwsgi`, `celerybeat`, and `celeryworker` during start-up when the db is not ready
- make it easier to identify errors with `initializer` (they might get easily lost within other logs).

feat(docker): Depends_on based on initializer

---

docs/content/en/open_source/contributing/how-to-write-a-parser.md

Removes some leftover instructions that are no longer needed with docker setup.

remove outdated (mysql) test database instructions

---

dojo/api_v2/exception_handler.py
dojo/api_v2/serializers.py
dojo/api_v2/views.py
dojo/jira_link/helper.py
dojo/models.py
unittests/dojo_test_case.py
unittests/test_finding_helper.py
unittests/test_jira_import_and_pushing_api.py
unittests/test_tags.py
unittests/vcr/jira/JIRAImportAndPushTestApi.test_groups_create_edit_update_finding.yaml

When creating or updating findings (or other entities that have a `tags` field), the `Finding.save()` method was called multiple times. Ultimately the `finding` was saved correctly, but this lead to unnecessary use of resources and could in the future lead to problems if/when the Defect Dojo could be relying more on Django signals such as `post_save()`. 
The above was caused by the way the `tags` fields were implemented long ago. I tried to tweak the `TaggitSerializer` to prevent the duplicate saves from happening, but this lead nowhere. Then I realized I could just tweak our `TagListSerializer` to make it work without the "extra" `TaggitSerialiser`. 
I also looked at the `from tagulous.contrib.drf import TagSerializer`, but that doesn't support the single string with multiple comma …

API: prevent duplicate saves of taggable entities or when pushing to JIRA

---

docs/content/en/connecting_your_tools/external_tools.md

Description
On the "External Tools: Universal Importer & DefectDojo-CLI (Pro)" docs page, universal importer code blocks still reference "defectdojo-cli". Those references were changed to "universal-importer." Changes were tested using hugo.
[sc-11468]

Change CLI tool reference in docs

---

dojo/api_v2/views.py
dojo/filters.py
unittests/test_apiv2_user.py

Allow filtering on `last_login` and `date_joined` to help users manage user via the API. Inspired by #12611

API: Allow filtering users on last_login/date_joined

---

unittests/tools/test_checkmarx_cxflow_sast_parser.py

Small fix to get rid of warnings/unclosed files during unit tests.

checkmarx: close files used in unit tests

---

dojo/user/views.py

In certain SSO scenario's the user can end up with a `/login` url without any `next` parameter. This would result in a ` NoneType`  error. This PR fixes this by sending users to `/dashboard`  by default. Inspired by #6907

login next param: set default for sso redirects

---

dojo/fixtures/benchmark_category.json
dojo/fixtures/benchmark_requirement.json
dojo/fixtures/benchmark_type.json
dojo/product/views.py
dojo/templates/dojo/product.html

* **Symptom:** The Benchmark-Type dropdown on the product page always showed a single entry, **“OWASP ASVS v3.1”**, even though **v4.0.1** (and other types) were already loaded in the DB.  
* **Root cause:** The view didn’t pass the full list of enabled `Benchmark_Type` records to the template.  
* **Fix:** `dojo/product/views.py` now fetches `Benchmark_Type.objects.filter(enabled=True)` and exposes it in the context → the dropdown lists *all* enabled benchmarks.
* **Added OWASP ASVS 5.0**:
Includes the latest ASVS 5.0 as a selectable benchmark, with new categories and initial requirements.
* **Why**:
Previously, only the old ASVS 3.1 was visible in the dropdown, even though 4.0.1 was already in the database. ASVS 3.1 is quite outdated, so it’s nice to have more up-to-date standards …

Feature/asvs 5.0 benchmark

---

docs/content/en/connecting_your_tools/parsers/file/trivy.md
dojo/tools/trivy/parser.py
unittests/scans/trivy/all_statuses.json
unittests/tools/test_trivy_parser.py

Trivy has a "status" field for triaging which is currently unmapped:
"status": "affected" or "not_affected" or "fix_deferred" or "will_not_fix"
This would be useful information to handle.
see: https://trivy.dev/latest/docs/configuration/filtering/
"Affected": the package is affected by the flaw on this platform
"Not affected": the package, which ships on this platform, is not affected by the flaw
"Fix deferred": the package is affected by the flaw on this platform, and may be fixed in the future
"Under investigation": it is currently unknown whether the flaw affects the package on this platform, and is under investigation
"Will not fix": the package is affected by the flaw on this platform, but there is no current intention to fix it (primarily for flaws that are of Low or Moderate impact …

trivy: map status field

---

dojo/tools/twistlock/parser.py
unittests/scans/twistlock/one_vuln_no_link_no_description.json
unittests/tools/test_twistlock_parser.py

Make the twistlock parser safer by not directly referencing dict entries, fixes #12694

twistlock json: safely get fields

---

dojo/endpoint/signals.py
dojo/engagement/signals.py
dojo/finding_group/signals.py
dojo/product/signals.py
dojo/product_type/signals.py
dojo/test/signals.py
dojo/utils.py

Correcting the following:
```python
File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 453, in trace_task
R = retval = fun(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 736, in __protected_call__
return self.run(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/dojo/utils.py", line 2331, in delete_chunk
obj.delete()
File "/app/dojo/models.py", line 1614, in delete
super().delete(*args, **kwargs)
File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 1273, in delete
return collector.delete()
^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/django/db/models/deletion.py", line 508, in delete
signals.post_delete.send(
File …
```

Async Delete: Correct instances of multiple audit log entries for delete

---

dojo/engagement/views.py
dojo/finding/views.py
dojo/product/views.py
dojo/product_type/views.py
dojo/templates/dojo/engagement.html
dojo/utils.py

Fixes [DefectDojo #12575](https://github.com/DefectDojo/django-DefectDojo/issues/12575)
This PR is a pure-Python refactor that keeps every public API and template untouched while eliminating the two main performance bottlenecks reported in the issue:
•	Correlated sub-queries per row → replaced with a single Subquery aggregation + Coalesce helper (build_count_subquery)
•	Many small “counter” queries → moved to conditional Count() annotations executed once per list view

Optimize queryset annotations & prefetches to cut DB time for test / finding / product views (issue #12575)

---

Dockerfile.django-alpine
Dockerfile.django-debian
docker-compose.override.dev.yml
docker-compose.override.integration_tests.yml
docker/entrypoint-celery-worker-dev.sh
docker/entrypoint-uwsgi-dev.sh
readme-docs/DOCKER.md
requirements.txt

Improvements to hot-reloading/autoreload:
- fix path to `/app/dojo/settings/settings.py`
- also reload on `.html` and `.tpl` changes
- enable autoreload on the `celeryworker`
For `celery` it could be done without `watchmedo`, but that would require installting pypi package `celery[dev]` which would end up also in production. I'm not sure of the impact of that, so I avoided it.

dev: hot reloading improvements celery/html/tpl

---

docker/entrypoint-unit-tests-devDocker.sh
dojo/decorators.py
unittests/dojo_test_case.py
unittests/scans/stackhawk/stackhawk_many_vul_without_duplicated_findings.json
unittests/scans/stackhawk/stackhawk_many_vul_without_duplicated_findings_subset.json
unittests/test_importers_performance.py

This PR ads a unit test for import/reimport that captures the number of queries executed and the number of dojo async tasks created/generated.
By capturing this we help ourselves in the future when PRs affected the number of queries. Sometimes this is intended and OK. Sometimes it means there's an unforeseen side effect that lowers performance.
I have some performance related PRs coming up and it will be nice to see the numbers go down.
I choose the StackHawk parser because its samples have multiple endpoints per finding making it a good case to also cover the endpoint part of the import/reimport process.

unittests: import query/task count capture

---

dojo/management/commands/import_all_unittest_scans.py

I needed a way to load some realistic data into Defect Dojo. Not just one or two big scans, but ideally a couple of products + engagements + tests.
As an experiment I created this management command that imports all unit test sample scans present in the repository.
It's a naive first implementation:
- ignores subfolders
- ignores errors during import
- can only handle 1 scan_type per parser
- has some copy and pasted code from elsewhere 
I am committing it anyway as it might be useful for others or maybe other can improve upon it :-)
A similar approach could be just to have an end-to-end test in the test suite that imports all sample scans and ensures there are no errors ("smoke test").
It can also be used for users to just get the import process going and see how the system holds up …

add management command to import all unit test sample scans

---

dojo/forms.py

If we look at the import scan result screen in the UI:
If we look at the API description for the same fields:
I found this confusing the first time I saw and it made me check the code to make sure they were setting the same fields (and they are).
This PR tries to put them in sync, by rephrasing the ones in the UI (as those seem the furthest from the actual variable intent).
I think it could be done the other way around or even switching the field to choices field (`Do not close`, `Close at engagement level`, `Close at product level`) but those would impact API consumers...
**Checklist**

Consistent "Close old findings" between UI and API

---

dojo/tools/ms_defender/parser.py

Fixes #12767
Not sure if this was really a bug, but it seems like different zip file creators create different types of zip.
This time it seems that the zip contains some additional empty files with the same name as the folder that holds the true/real files.
This PR skips those and ass some more error handling for future non-default scenario's.

ms_defender: skip empty files from zip

---

dojo/templatetags/display_tags.py
dojo/tools/anchore_grype/parser.py
unittests/scans/anchore_grype/anchore_grype_epss_problem.json
unittests/tools/test_anchore_grype_parser.py

Fixes #12819 
When the original vulnerability id is not a CVE, the parser must look harder in the related vulnerability data to find the EPSS data.
This might not be a 100% complete fix as for that the parser needs to be changed to parse all related vulnerabilities instead of just the first one. Anyone with Grype knowledge please advise :-) For now this at least fixes the one known problem case.

Anchore grype EPSS fix

---

dojo/tools/trivy/parser.py
unittests/scans/trivy/cvss_severity_source.json
unittests/scans/trivy/issue_9092.json
unittests/tools/test_trivy_parser.py

Trivy scans reports the source of where the severity field comes from. We use this field to associate a CVSS score with the finding. In cases where the severity source does not have a CVSS vector, it would be beneficial to still include a vector from the first match in the following list:
- Detected Severity Source
- NVD
- GHSA
- Redhat
- Bitnami
In the sample scan files, there was a CVSS score that did not match the CVSS vector, so I updated it

Trivy: Use CVSS scores from other vendors where applicable

---

dojo/api_v2/serializers.py
dojo/models.py

The `products` API endpoint returns the list of ids of all active findings for each product.
This is slow in larger instances or large page sizes.
This PR optimizes the query a little bit. For a 100K finding instance the response time went from ~6s to ~0.9s. Of course the mileage may vary depending on available resources and dataset specifics.
I tried fursther optimizing is using prefetching. But prefetching across multiple relationship levels in Django ORM isn't possible in one ago and requires some aggregation/counting in python making it slower again.
[sc-11611]

product api: optimize list of finding ids

---

dojo/api_v2/serializers.py

As part of #12782 the default value for `close_old_findings` was swapped from `True` to `False`. This PR restores that functionality

Reimport: Restore default for `close_old_findings` to `True`

---

docs/content/en/connecting_your_tools/parsers/file/snyk_code.md
dojo/tools/mayhem/parser.py
dojo/tools/sarif/parser.py
dojo/tools/snyk/parser.py
dojo/tools/snyk_code/parser.py
unittests/tools/test_snyk_code_parser.py

Over time two Sarif based parsers were added because they needed some custom parser logic to fully parse their scan reports:
- Mayhem
- Snyk Code
This resulted in some code duplication. This PR changes the Sarif base parser to be extensible and uses this to simplify the Snyk Code and Mayhem parsers. I didn't go as far as to create extension hooks for each an every field. This PR now has some examples that can be used in future PRs if more fields need to be extendible.
Initially I had the CWE parsing logic for the Mayhem `taxa` based CWEs also in an extenstion hook. But then I found out that the "taxa" format is actually somewhat official Sarif formatting. Also there was already code in the base Sarif parser looking for CWEs in various places. So the PR adds the "taxa way" to the base …

reuse Sarif base parser for snyk and mayhem parsers

---

dojo/middleware.py
run-unittest.sh
unittests/dojo_test_case.py
unittests/test_importers_performance.py
unittests/test_tags.py

There'll be a sequence of import performance related PRs. They are separated into small PRs to simplify review and troubleshooting. As they all use `test_importers_performance`, they'll build on eachother. So they'll have to be merged by natural ordering.
- system settings weren't set in the correct way, resulting in some settings like product grading left enabled resulting in incorrect query counts
- tags weren't provided in the `test_importers_performance.py`
- updated query counts
I also identified that the caching of System_Settings was not working in test cases, which is now fixed.

perf1: test cases: fix caching of system settings

---

docs/content/en/connecting_your_tools/parsers/file/anchore_grype.md

As a follow up to #12825 a little note on the `--by-cve` parameters of anchore grype.

anchore_grype docs: add info about --by-cve

---

dojo/engagement/signals.py
dojo/finding/helper.py
dojo/models.py
dojo/product/signals.py
dojo/product_type/signals.py
dojo/test/signals.py
dojo/utils.py

There are cases of async delete where the same resource is deleted by separate requests. For example, deleting an engagement followed by that engagement's product will produce exceptions in the product tasks where the engagement does not exist. In this case, we know the object is already deleted, so we can simply ignore the error

Async Delete: Handle exceptions for duplicate requests

---

dojo/static/dojo/css/dojo.css

[sc-11702]
This pull requests fixes an issue introduced to the DataTable search functionality that placed the table search `div` on a new line (styled to `display: block;` rather than `display: inline-block;`).
Before:
After:

fix datatable search box location with style override

---

dojo/api_v2/serializers.py
dojo/forms.py
dojo/validators.py

It is possible to import/reimport any file extension. The UI already enforces a handful of extensions that are allowed, but the API does not validate in the same way 
https://github.com/DefectDojo/django-DefectDojo/blob/2748b8d05450800a36b9282f5bd917bf6e673046/dojo/forms.py#L649-L653
A validation error will look like this:
```json
"file": [
"File extension “exe” is not allowed. Allowed extensions are: xml, csv, nessus, json, jsonl, html, js, zip, xlsx, txt, sarif."
],
```

Support for whitelisted file extensions

---

nginx/nginx.conf
nginx/nginx_TLS.conf

This reverts commit e9d987206cd747b76df89605e9bf8108e8abdfc4.

quickFix: invalid config in "Feat(nginx): Add support for IPv6"

---

docs/config/_default/params.toml
docs/package-lock.json

the new `docsearch` dependencies got removed from the `package-lock.json` file during the release due to conflict resolution. When developing locally, the command `npm run dev` is used, which reads from `package.json` and then updates the `package-lock.json` file. However, when docs are deployed for production, the `package-lock.json` file is used to avoid pulling in any upgrades.
The search function is busted because it is trying to reference packages that are not installed

Docs: Restore `package-lock.json`

---

dojo/templatetags/display_tags.py
dojo/templatetags/navigation_tags.py

In cases of an exception, I was receiving an error page from nginx rather than getting the 5xx response hosted by django. This was caused from a key error of the `request` object in the context of a given view

Display Tags: Do not rely on the request object being present

---

dojo/importers/default_reimporter.py

When adding a note to a finding to state that it was not reactivated, we don't need to call save on the finding itself.
The same approach was taken in the past for close_old_findings.

performance do_not_reactivate: adding a note doesn't need a finding save

---

docker/entrypoint-unit-tests-devDocker.sh

applies only to local running of unit tests: this entrypoint had some changes used for testing, but should be reverted to the version that runs all tests.

restore entrypoint-unit-tests-devDocker.sh

---

readme-docs/DOCKER.md

Alternative command useful for automation.

ADD: Alternative command to change password

---

requirements.txt
unittests/test_rest_framework.py

Supersedes #12917
upgrades cvss to 3.6, as originally proposed by Dependabot, but fixes cvssv4 test to account for them fixing CVSS metric order to comply with spec

Bump cvss from 3.4 to 3.6 

---

helm/defectdojo/templates/_helpers.tpl
helm/defectdojo/values.yaml

Fix #12955 
Set default value of postgresql.postgresServer to 127.0.0.1 so helm install won't failed if it's not defined.
Move the comment on postgresServer at the beginning of postgresql item, to ease the usage of external instance.
```
helm template . --values myvalues.yaml --show-only templates/configmap.yaml
```
```
---
apiVersion: v1
kind: ConfigMap
metadata:
name: defectdojo
labels:
app.kubernetes.io/name: defectdojo
app.kubernetes.io/instance: defectdojo
app.kubernetes.io/managed-by: Helm
helm.sh/chart: defectdojo-1.6.203-dev
data:
.... 
DD_DATABASE_HOST: 127.0.0.1
.... 
```
N/A 
**Checklist**

Fix 12955 / Set default value of postgresql.postgresServer to 127.0.0.1 in helm chart

---

dojo/forms.py
dojo/validators.py

[dojo/tools/fortify/parser.py](https://github.com/DefectDojo/django-DefectDojo/blob/master/dojo/tools/fortify/parser.py) expects FPR reports to have the .fpr extension, yet .fpr is not part of the allowed import extensions.
Via the UI, it is not listed as _supported type_ but it can still be uploaded (by choosing _any type_). But via API it is simply not possible.
* .fpr shows up as supported type in the report file browse dialog of import scan UI
* .fpr files can be imported via import-scan/reimport-scan API endpoints
**Checklist**

allow .fpr extension when importing scan

---

dojo/management/commands/csv_findings_export.py
dojo/management/commands/dedupe.py
dojo/management/commands/import_surveys.py
dojo/management/commands/push_to_jira_update.py
dojo/management/commands/rename_mend_findings.py
dojo/management/commands/stamp_finding_last_reviewed.py

During a deeper analysis of #12974 (why there are `locale` definitions in commands), I noticed that they are copy-paste leftovers and were never used. They can be removed.
I was trying to identify the reason for `locale` in those many commands which has never been used.
```bash
$ git log -p -S'locale = ' dojo/management/commands | grep 'locale'              
-locale = timezone(get_system_setting('time_zone'))
-locale = timezone(get_system_setting('time_zone'))
-locale = timezone(get_system_setting('time_zone'))
-locale = timezone(get_system_setting('time_zone'))
-                    current_scan.date = locale.localize(datetime.today())
-            msg += " was performed on " + locale.normalize(
-                                       date=locale.localize(datetime.today()))
-locale = …
```

fix(timezone/commands): Drop obsolite 'locale' definitions

---

dojo/tools/blackduck/importer.py
dojo/tools/blackduck_binary_analysis/importer.py
dojo/tools/blackduck_component_risk/importer.py
unittests/tools/test_blackduck_binary_analysis_parser.py
unittests/tools/test_blackduck_component_risk_parser.py
unittests/tools/test_blackduck_parser.py

I found that while doing some importing using python request, black duck zip files had to be imported with `rb` mode in the files parameter:
```python
[("file", open(file_path, "rb"))]
```
However, when attempting to process CSV files in this way, I would constantly get an exception for two reasons:
- The `temporary_file` function does not work well with bytes
- Following the check if a file is zipped, the file pointer is not reset, so there are no bytes to read, which lead to a None type exception
To mitigate this, we need to support byte imports are a first class citizen. I checked the other black duck parsers as well to get them up to speed

BlackDuck: Support import in plaintext or bytes

---

dojo/engagement/views.py

Django raised `AttributeError: 'NoneType' object has no attribute 'id'` when a user visited `DD/product/<id>/import_scan_results` and triggered `failure_redirect`.

fix(eng/failure_redirect): Fix rendering when coming from product site

---

dojo/filters.py

When string based filtering is enabled, the product lifecycle filter was totally missing. This is due to a mistake in how the. object vs non object finding filters were constructed
[sc-11750]

Finding Filters: Add Product Life Cycle filter to be supported in both finding filters

---

dojo/settings/settings.dist.py
dojo/tools/harbor_vulnerability/parser.py
unittests/tools/test_harbor_vulnerability_parser.py

https://github.com/DefectDojo/django-DefectDojo/issues/12633#issuecomment-2989905282
I removed also the mitigation from dedeuplication as this was only there to close the old finding in case the mitigation becomes available.

:tada: Add fix_available to Harbor

---

Dockerfile.django-alpine
Dockerfile.django-debian
docker-compose.override.dev.yml
docker-compose.yml
requirements-dev.txt
requirements.txt

I wasn't going to spend time on this, but then Cursor AI got it right almost on the first go.
Some dependencies are only needed for development, we shouldn't install those in the release ("production")  images.

docker: remove dev dependencies from release images

---

dojo/templates/base.html

Rename duplicate 'Dashboard' to 'Finding Groups'
In 2.50.0 https://github.com/DefectDojo/django-DefectDojo/pull/12814 has a second 'Dashboard' named tile in the navigation bar.  This PR aims to rename it to something more appropriate like 'Finding Groups'.

Rename duplicate 'Dashboard' to 'Finding Groups'

---

dojo/utils.py
unittests/test_importers_performance.py

The grades of products are calculated quite often:
- every hour
- every finding.save()
- bulk edit
- ...
This PR ensures the product gets updated only if the grade has changed. This prevents unnecessary database writes.

product grade: only update product if grade has changed

---

Dockerfile.nginx-alpine

The PR that split off the dev dependencies caused the static file collection to file after the debug-toolbar enablement option via environment variables. Small follow up PR to fix this.

debugtoolbar: fix for requirements-dev.txt

---

.github/workflows/release-1-create-pr.yml
.github/workflows/release-3-master-into-dev.yml

When the version is updated, HELM docs become outdated and need to be adjusted.

feat(helm): Trigger update of Helm docs when version is changed

---

.github/workflows/test-helm-chart.yml

I was asked to prepare a more understandable description.

feat(helm): Better explanation for failing GHA

---

Dockerfile.django-alpine
Dockerfile.django-debian

This is a follow up from the discussion on https://github.com/DefectDojo/django-DefectDojo/pull/13162 related to keeping changes to Dockerfiles at a minimum for now.
I've taken just the wheel dropping piece of that PR and opened this one with it.
Out of that PR, this is the one with most benefit (drop 1/6 of image size) with least changes.
Also, part of that PR was already merged in https://github.com/DefectDojo/django-DefectDojo/pull/13095
No build time improvement, but considerable size reduction which helps in CI with pushing and pulling the images, as not every setup has the docker registry sitting right next to the CI agent 😄 
* `time docker build -t x9x -f Dockerfile.django-??? . --progress plain --no-cache --target release` used for the builds (on …

dockerfiles: drop wheels from layers

---

dojo/api_v2/serializers.py
dojo/forms.py

This fixes #13163 
> Old findings no longer present in the new report get closed as mitigated when importing. If service has been set, only the findings for this service will be closed. 
The current tooltip misled me into thinking that `when service is NOT set, all findings are considered regardless of service`, yet it is not the behavior: when service is not set, only findings without a service will be closed.
I thought it could be just me and my english but at least [ChatGPT agrees](https://chatgpt.com/share/68cae627-0c30-800c-99ac-e07e6e922176) 😄 
Tried to come up with a smaller change but in the end I think just making it explicit does not make it too big anyway.
**Checklist**

make close_old_findings tooltip clearer when service is not set

---

dojo/tools/api_blackduck/api_client.py

Unit tests are failing due to a deprecation warning in the black duck pypi package. The library does not appear to be very active these days, so ignoring the warning feels like the quickest path to getting our tests back on track

Unit Tests: Ignore deprecation Warning from BlackDuck pypi package

---

.github/workflows/test-helm-chart.yml

We would like to provide more ArtifactHub-compatible metadata (see #13197, #13195), so it would be good to know that the metadata is generated correctly

feat(helm): Add ArtifactHub Linter

---

dojo/tools/sonarqube/sonarqube_restapi_json.py

[sc-11829]
I added the line field everywhere relevant except for [this location](https://github.com/Jino-T/django-DefectDojo/blob/7c0f3f0252c7a76d5c5863ca186360c7c3856d2d/dojo/tools/sonarqube/soprasteria_helper.py#L77). I trusted the comment left here. Let me know if I should overrule this.

Added Line Field for SonarQube Scan and SonarQube Scan Detailed Scan Types

---

dojo/finding/views.py

Fixes #13273
Adds some finding and context info to the alert title similar to other notifications in Defect Dojo

requested review: add data to notification title

---

dojo/tools/aws_inspector2/parser.py
unittests/tools/test_aws_inspector2_parser.py

Enhance the AWS Inspector2 parser to extract CVSS details from findings and update related tests to validate the new functionality.

Add CVSS details extraction to AWS Inspector2 parser

---

dojo/api_v2/serializers.py
dojo/api_v2/views.py
dojo/finding/helper.py
dojo/finding/views.py
dojo/forms.py
unittests/test_rest_framework.py

Fixes #6078
I thought it would be nice to allow the Finding API to accept `mitigated` and `mitigated_by` values for super users and when `settings.EDITABLE_MITIGATED_DATA` was `True`.
This PR adds that. It also normalizes the check in all place.
Two notes:
- The Close Finding UI form did not allow setting these fields at all. Now it does if the setting is enabled and the user is a superuser.
- The Close Finding API allowed non-superusers to modify the `mitigated` timestamp field if the `EDITABLE_MITIGATED_DATA`  was enabled. Not sure if this was intentional, but this PR now guards that field by the same central helper method. So only superusers can set if and `EDITABLE_MITIGATED_DATA` must be enabled. Is this oké?
- The Close Finding UI and API have this missing note types functionality. …

enhance/normalize EDITABLE_MITIGATED_DATA handling

---

dojo/models.py

Streamline the retrieval process for vulnerability IDs and endpoints in the Finding model by separating logic for unsaved and saved states, improving code clarity and maintainability.

Refactor vulnerability ID and endpoint retrieval in Finding model

---

dojo/user/views.py

In #13273 it's reported that the ordering of alerts can be different depending on the context. Let's make it explicit.

make alert order explicit

---

.github/workflows/release-nightly-dev.yml

Until now, `Release-Nightly: Build & Push DEV` has been triggered multiple times between 5:00 and 5:59 UTC. But we needed it only once.
https://github.com/DefectDojo/django-DefectDojo/actions/workflows/release-nightly-dev.yml

fix(gha): Run Release-Nightly only once a day
